### PR TITLE
Make several descriptor parameters const

### PR DESCRIPTION
**Pull request by satirebird**
I made several descriptor parameters const. This allows to use statically initialized variables. I also updated several function docs.

There is one line in src/lv_draw/lv_draw_label.c:219 I am not sure whats is the intention. I think this is relict from testing?
`dsc->decor  = LV_TEXT_DECOR_UNDERLINE;`

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thanks, it looks good. Also thank you for fixing the comments.

The `decor` part was really a leftover from testing. I've removed it.

**Comment by kisvegabor** [comment]
The CI fails of an unrelated warning which is already fixed in master. 

So I merged it.

**Comment by satirebird** [comment]
The only function where I couldn't make the descriptor be const was the `lv_canvas_draw_text()` function. The align parameter is translated to a `lv_txt_flag_t` and stored in the descriptor. Theoretically, the align parameter could be removed because the information is already in the descriptor parameter. But this is an API change.

**Comment by kisvegabor** [comment]
That's true, the align parameter could be merged to `flag`. Let's postpone it to v8. (Added to the [roadmap](https://github.com/lvgl/lvgl/blob/master/docs/ROADMAP.md)).

As a workaround - to make all descriptors `const` - we can copy the  `lv_draw_label_dsc_t` function argument to a local variable and modify the `flag` there. 
What do you think?

**Comment by satirebird** [comment]
I think merging the parameter in V8 is the sufficient. 
The gcc is able to warn if the parameter could be const. I have tried to compile the sources with -Wsuggest-attribute=const. There are several other places where the parameter could be const. I think it helps a bit to avoid some errors (and the compile should be able to optimize better)
But the additional compiler flag produces some other strange outputs. If I have some more time I will go into it and try to understand whats does it mean.

**Comment by kisvegabor** [comment]
> But the additional compiler flag produces some other strange outputs. If I have some more time I will go into it and try to understand whats does it mean.

That would be very welcome! Thank you in advance!

**Pull request merged**
