### PR TITLE
OpenGL ES 2.0 Rendering

### PR DESCRIPTION
**Pull request by tanaytekin**
### Description of the feature or fix

It is a draft PR will be updated.

Related issue: #3329 

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

I can't really comment about the internal OpenGL ES part, but high level parts look good. 

I'd be happy to try it out if there were a short list of instructions to get started. This way I could the test the docs too :slightly_smiling_face:

**Comment by tanaytekin** [comment]
> Hi,
>
> I can't really comment about the internal OpenGL ES part, but high level parts look good.
>
> I'd be happy to try it out if there were a short list of instructions to get started. This way I could the test the docs too slightly_smiling_face

Hi,

To use GL drawing codes there is a GL context must be created beforehand, so a separate driver [fork](https://github.com/rainlab-inc/lv_drivers/tree/gles) is also required.

There is an example app that uses lv_driver fork and instructions are here: https://github.com/rainlab-inc/lvgl-opengl

The master branch uses SDL for GL context generation. There is also glfw branch(keyboard - touch screen doesnt work yet)  for testing purposes.

**Comment by kisvegabor** [comment]
Thanks! I've tried both branches of `rainlab-inc/lvgl-opengl` but got errors :slightly_frowning_face: 

I needed to add `#define  LV_GPU_GLES_GLAD_INCLUDE_PATH <GLES2/gl2.h>` to `lv_conf.h` and `lv_drv_conf.h`, else there were many error. After that still there a few error that I couldn't solve so easily. 

Maybe do you have uncommited/unpushed changes?

BTW, I simply built it with CMake.

**Comment by tanaytekin** [comment]
> Thanks! I've tried both branches of `rainlab-inc/lvgl-opengl` but got errors slightly_frowning_face
> 
> I needed to add `#define LV_GPU_GLES_GLAD_INCLUDE_PATH <GLES2/gl2.h>` to `lv_conf.h` and `lv_drv_conf.h`, else there were many error. After that still there a few error that I couldn't solve so easily.
> 
> Maybe do you have uncommited/unpushed changes?
> 
> BTW, I simply built it with CMake.

Hi

Did you update submodules with `git submodule update --remote`? I have also manually updated the submodules in master and glfw branch. Can you try again? Thanks.

**Comment by kisvegabor** [comment]
It looks better with the latest changes but I still get this linking error:
```shell
[100%] Linking C executable lvgl-opengl
/usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `glfw_gles_init':
glfw_gles.c:(.text+0x5): undefined reference to `glfwInit'
/usr/bin/ld: glfw_gles.c:(.text+0x14): undefined reference to `glfwWindowHint'
/usr/bin/ld: glfw_gles.c:(.text+0x23): undefined reference to `glfwWindowHint'
/usr/bin/ld: glfw_gles.c:(.text+0x32): undefined reference to `glfwWindowHint'
/usr/bin/ld: glfw_gles.c:(.text+0x41): undefined reference to `glfwWindowHint'
/usr/bin/ld: glfw_gles.c:(.text+0x50): undefined reference to `glfwWindowHint'
/usr/bin/ld: glfw_gles.c:(.text+0x79): undefined reference to `pthread_create'
/usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `window_create':
glfw_gles.c:(.text+0x23a): undefined reference to `glfwCreateWindow'
/usr/bin/ld: glfw_gles.c:(.text+0x250): undefined reference to `glfwMakeContextCurrent'
/usr/bin/ld: glfw_gles.c:(.text+0x25a): undefined reference to `glfwSwapInterval'
/usr/bin/ld: glfw_gles.c:(.text+0x270): undefined reference to `glfwSetFramebufferSizeCallback'
/usr/bin/ld: glfw_gles.c:(.text+0x286): undefined reference to `glfwSetCursorPosCallback'
/usr/bin/ld: glfw_gles.c:(.text+0x29c): undefined reference to `glfwSetMouseButtonCallback'
/usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `window_update':
glfw_gles.c:(.text+0x607): undefined reference to `glfwSwapBuffers'
/usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `handle_events':
glfw_gles.c:(.text+0x81a): undefined reference to `glfwPollEvents'
/usr/bin/ld: glfw_gles.c:(.text+0x829): undefined reference to `glfwWindowShouldClose'
/usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `monitor_glfw_gles_clean_up':
glfw_gles.c:(.text+0x88c): undefined reference to `glfwDestroyWindow'
/usr/bin/ld: glfw_gles.c:(.text+0x891): undefined reference to `glfwTerminate'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lvgl-opengl.dir/build.make:108: lvgl-opengl] Error 1
make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/lvgl-opengl.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

I've installed these as requirements:
```shell
sudo apt-get install libglfw3-dev libgles2-mesa-devlibepoxy-dev
```

**Comment by embeddedt** [comment]
@kisvegabor Did you create your CMake build folder after installing the dependencies or before? I'm not sure if CMake picks up on newly installed libraries automatically.

**Comment by kisvegabor** [comment]
Good idea! I run cmake again, but unfortunately it didn't help.

**Comment by tanaytekin** [comment]
> It looks better with the latest changes but I still get this linking error:
> 
> ```shell
> [100%] Linking C executable lvgl-opengl
> /usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `glfw_gles_init':
> glfw_gles.c:(.text+0x5): undefined reference to `glfwInit'
> /usr/bin/ld: glfw_gles.c:(.text+0x14): undefined reference to `glfwWindowHint'
> /usr/bin/ld: glfw_gles.c:(.text+0x23): undefined reference to `glfwWindowHint'
> /usr/bin/ld: glfw_gles.c:(.text+0x32): undefined reference to `glfwWindowHint'
> /usr/bin/ld: glfw_gles.c:(.text+0x41): undefined reference to `glfwWindowHint'
> /usr/bin/ld: glfw_gles.c:(.text+0x50): undefined reference to `glfwWindowHint'
> /usr/bin/ld: glfw_gles.c:(.text+0x79): undefined reference to `pthread_create'
> /usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `window_create':
> glfw_gles.c:(.text+0x23a): undefined reference to `glfwCreateWindow'
> /usr/bin/ld: glfw_gles.c:(.text+0x250): undefined reference to `glfwMakeContextCurrent'
> /usr/bin/ld: glfw_gles.c:(.text+0x25a): undefined reference to `glfwSwapInterval'
> /usr/bin/ld: glfw_gles.c:(.text+0x270): undefined reference to `glfwSetFramebufferSizeCallback'
> /usr/bin/ld: glfw_gles.c:(.text+0x286): undefined reference to `glfwSetCursorPosCallback'
> /usr/bin/ld: glfw_gles.c:(.text+0x29c): undefined reference to `glfwSetMouseButtonCallback'
> /usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `window_update':
> glfw_gles.c:(.text+0x607): undefined reference to `glfwSwapBuffers'
> /usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `handle_events':
> glfw_gles.c:(.text+0x81a): undefined reference to `glfwPollEvents'
> /usr/bin/ld: glfw_gles.c:(.text+0x829): undefined reference to `glfwWindowShouldClose'
> /usr/bin/ld: lib/liblv_drivers.a(glfw_gles.c.o): in function `monitor_glfw_gles_clean_up':
> glfw_gles.c:(.text+0x88c): undefined reference to `glfwDestroyWindow'
> /usr/bin/ld: glfw_gles.c:(.text+0x891): undefined reference to `glfwTerminate'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/lvgl-opengl.dir/build.make:108: lvgl-opengl] Error 1
> make[1]: *** [CMakeFiles/Makefile2:143: CMakeFiles/lvgl-opengl.dir/all] Error 2
> make: *** [Makefile:149: all] Error 2
> ```
> 
> I've installed these as requirements:
> 
> ```shell
> sudo apt-get install libglfw3-dev libgles2-mesa-devlibepoxy-dev
> ```

Did master branch work? This linking error kinda strange.  Also did you do `git submodule sync` and `git submodule update` after switching to the `glfw` branch?

**Comment by kisvegabor** [comment]
On master (after submodule update) I got:
```
/home/kisvegabor/projects/lvgl/lvgl-opengl/lv_drivers/sdl/sdl_gles.c:17:10: error: #include expects "FILENAME" or <FILENAME>
   17 | #include LV_GPU_GLES_GLAD_INCLUDE_PATH
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

On the `glfw` branch also after submodule update: see the log I posted above

@embeddedt could you also try it out?
```
sudo apt-get install libglfw3-dev libgles2-mesa-devlibepoxy-dev
git clone https://github.com/rainlab-inc/lvgl-opengl.git --recurse-submodules 
cd lvgl-opengl
git checkout glfw
git submodule update
mkdir build
cd build
cmake ..
make -j
```

**Comment by embeddedt** [comment]
I'm not using Ubuntu at the moment so the `apt` command wouldn't work for me, but I was able to compile without problems following the rest of your steps exactly. It seems that it must be something specific to your system.

**Comment by kisvegabor** [comment]
I've tried a couple of things and read some forums but still no luck. Are you both on Windows or Mac (i.e. not Linux)?

**Comment by tanaytekin** [comment]
Hello, I am currently using Arch Linux.
I'll try to compile it on Ubuntu when I find some time.

**Comment by fantomid** [comment]
Hello, I got these linking errors with libepoxy and Ubuntu:
```
[100%] Linking C executable lvgl-opengl
/usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `sdl_gles_init':
sdl_gles.c:(.text+0xe): undefined reference to `SDL_Init'
/usr/bin/ld: sdl_gles.c:(.text+0x1d): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: sdl_gles.c:(.text+0x2c): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: sdl_gles.c:(.text+0x3b): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: sdl_gles.c:(.text+0x4a): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: sdl_gles.c:(.text+0x59): undefined reference to `SDL_GL_SetAttribute'
/usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o):sdl_gles.c:(.text+0x68): more undefined references to `SDL_GL_SetAttribute' follow
/usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `sdl_gles_init':
sdl_gles.c:(.text+0x8c): undefined reference to `SDL_CreateThread'
/usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `sdl_gles_event_handler':
sdl_gles.c:(.text+0x36d): undefined reference to `SDL_PollEvent'
/usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `window_create':
sdl_gles.c:(.text+0x3d9): undefined reference to `SDL_CreateWindow'
/usr/bin/ld: sdl_gles.c:(.text+0x3ef): undefined reference to `SDL_GL_CreateContext'
/usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `window_update':
sdl_gles.c:(.text+0x797): undefined reference to `SDL_GL_SwapWindow'
/usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `monitor_sdl_gles_clean_up':
sdl_gles.c:(.text+0xb77): undefined reference to `SDL_DestroyWindow'
/usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `tick_thread':
sdl_gles.c:(.text+0xb96): undefined reference to `SDL_Delay'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lvgl-opengl.dir/build.make:89: lvgl-opengl] Error 1
make[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/lvgl-opengl.dir/all] Error 2
```

I solved the problem with modifications in the CMakeLists.txt file of the lvgl-opengl project:
```
target_link_libraries(lv_drivers epoxy SDL2)

target_link_libraries(lvgl-opengl lvgl::lvgl lvgl::examples lvgl::demos lv_drivers)
```

=> SDL2 with lv_drivers

**Comment by embeddedt** [comment]
> Are you both on Windows or Mac (i.e. not Linux)?

I'm using Arch like @tanaytekin is; that explains why it works out of the box for me.

**Comment by kisvegabor** [comment]
@fantomid 
Based on your suggestion I could make it work with these settings:
```cmake
target_link_libraries(lv_drivers epoxy glfw pthread)
```

@tanaytekin I've tested the OpenGL-ES backend with the widget demo and found the following.
FYI, as a reference you can see SW rendered widgets demo here https://lvgl.io/demos

First screen:
image

- No border around "Your name", "Min. 8 chars." etc
- The letter spacing looks strange. It's like there is no kerning
- The icon is missing from the blue circle button in bottom right corner
- The indicator of the slider some extra pixels on the right. If I adjust the slider the whole indicator will be blue.

Second screen:
image
image

- Not divider lines on charts
- No lines on the first chart (It uses a complicated masking to have faded area under the line, I think it's not critical to make it work)
- The arc gauges are not rendered

**Comment by tanaytekin** [comment]
> Hello, I got these linking errors with libepoxy and Ubuntu:
> 
> ```
> [100%] Linking C executable lvgl-opengl
> /usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `sdl_gles_init':
> sdl_gles.c:(.text+0xe): undefined reference to `SDL_Init'
> /usr/bin/ld: sdl_gles.c:(.text+0x1d): undefined reference to `SDL_GL_SetAttribute'
> /usr/bin/ld: sdl_gles.c:(.text+0x2c): undefined reference to `SDL_GL_SetAttribute'
> /usr/bin/ld: sdl_gles.c:(.text+0x3b): undefined reference to `SDL_GL_SetAttribute'
> /usr/bin/ld: sdl_gles.c:(.text+0x4a): undefined reference to `SDL_GL_SetAttribute'
> /usr/bin/ld: sdl_gles.c:(.text+0x59): undefined reference to `SDL_GL_SetAttribute'
> /usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o):sdl_gles.c:(.text+0x68): more undefined references to `SDL_GL_SetAttribute' follow
> /usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `sdl_gles_init':
> sdl_gles.c:(.text+0x8c): undefined reference to `SDL_CreateThread'
> /usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `sdl_gles_event_handler':
> sdl_gles.c:(.text+0x36d): undefined reference to `SDL_PollEvent'
> /usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `window_create':
> sdl_gles.c:(.text+0x3d9): undefined reference to `SDL_CreateWindow'
> /usr/bin/ld: sdl_gles.c:(.text+0x3ef): undefined reference to `SDL_GL_CreateContext'
> /usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `window_update':
> sdl_gles.c:(.text+0x797): undefined reference to `SDL_GL_SwapWindow'
> /usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `monitor_sdl_gles_clean_up':
> sdl_gles.c:(.text+0xb77): undefined reference to `SDL_DestroyWindow'
> /usr/bin/ld: lib/liblv_drivers.a(sdl_gles.c.o): in function `tick_thread':
> sdl_gles.c:(.text+0xb96): undefined reference to `SDL_Delay'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/lvgl-opengl.dir/build.make:89: lvgl-opengl] Error 1
> make[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/lvgl-opengl.dir/all] Error 2
> ```
> 
> I solved the problem with modifications in the CMakeLists.txt file of the lvgl-opengl project:
> 
> ```
> target_link_libraries(lv_drivers epoxy SDL2)
> 
> target_link_libraries(lvgl-opengl lvgl::lvgl lvgl::examples lvgl::demos lv_drivers)
> ```
> 
> => SDL2 with lv_drivers

@fantomid Fixed it thanks :pray:

**Comment by tanaytekin** [comment]
> @fantomid Based on your suggestion I could make it work with these settings:
> 
> ```cmake
> target_link_libraries(lv_drivers epoxy glfw pthread)
> ```
> 
> @tanaytekin I've tested the OpenGL-ES backend with the widget demo and found the following. FYI, as a reference you can see SW rendered widgets demo here https://lvgl.io/demos
> 
> First screen: image
> 
>     * No border around "Your name", "Min. 8 chars." etc
> 
>     * The letter spacing looks strange. It's like there is no kerning
> 
>     * The icon is missing from the blue circle button in bottom right corner
> 
>     * The indicator of the slider some extra pixels on the right. If I adjust the slider the whole indicator will be blue.
> 
> 
> Second screen: image image
> 
>     * Not divider lines on charts
> 
>     * No lines on the first chart (It uses a complicated masking to have faded area under the line, I think it's not critical to make it work)
> 
>     * The arc gauges are not rendered

Thanks for the feedback :bow: 

There are some missing and incorrect implementations, I hope someone can help :pray: 

>     * The letter spacing looks strange. It's like there is no kerning

I think we may need pixel perfect rendering for this. Especially letters like `i` look very strange.

**Comment by kisvegabor** [comment]
> There are some missing and incorrect implementations, I hope someone can help pray
> I think we may need pixel perfect rendering for this. Especially letters like i look very strange.

I'm not familiar with OpenGL (ES) but LVGL's side I'd be happy to help!

**Pull request closed without merging**
