### PR TITLE
chore(docs): Update Zephyr documentation

### PR DESCRIPTION
**Pull request by faxe1008**
In the meantime support for the keypad pseudo device was added. Also add a small section about performance tuning.

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you! The name `VDB` (Virtual Display Buffer) is bit used since v8. Would you like to keep it for historical reasons or is it possible to to update to a more recent naming? E.g. draw_buf

**Comment by faxe1008** [comment]
@kisvegabor kconfig symbol deprecation is quite a lengthy process on our side. We need to mark it as deprecated and only one release later can remove it, so 8-9 months of time. I think that looking at this cost, the name is still fairly accurate :^)

**Review by kisvegabor — APPROVED** [review]
Okay, all good for me then! :slightly_smiling_face:

**Review by liamHowatt — APPROVED** [review]
Looks good. Wasn't sure if maybe the configs should be \*\*\`\`CONFIG_LV_Z_VDB_SIZE\`\`\*\* for monospace but I think it looks fine.

image

**Pull request merged**
