### PR TITLE
lv_log: fix warnings

### PR DESCRIPTION
**Pull request by tjstyle**
Just little fix warning for mismatch int printf argument

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thanks for the update. My only concern is I'm not sure `%lu` is known by every `printf` implementation.  

Maybe it would be clearer to change the `line` parameter to `int`. What do you think?

**Comment by tjstyle** [comment]
Ok, I also think will more clear if change the line parameter. please check the revision.

**Comment by embeddedt** [comment]
@kisvegabor @tjstyle Making a change like that is probably going to generate warnings/errors (if `-Werror`) because the signedness of existing code may differ. I personally think a change like this has to go into `dev-5.3`.

**Comment by kisvegabor** [comment]
@embeddedt  AFAIK the `__LINE__` macro gives `int`.
Anyway, `v5.3` will be released in a few weeks, so for simplicity, I merged it into `dev-5.3` as you suggested

**Review by embeddedt — APPROVED** [review]
:+1:

**Pull request merged**
