### PR TITLE
feat(draw): optimize helium asm

### PR DESCRIPTION
**Pull request by PeterBee97**
### Description of the feature or fix
Optimize helium asm code
- Blend rgb565 without conversion: Blending function is now the same as `lv_color_16_16_mix`
- Remove unnecessary color reload: color fill should be faster for all format
Now 16bpp color fill is 1 instruction per loop (besides letp) as it should be, and 2 for opaque image BLIT-ting.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by XuNeo — DISMISSED** [review]

**Comment by GorgonMeducer** [comment]
This Helium assembly code use GAS macro which cannot be well supported in LLVM and AC6.
Would you please do the following changes to improve the portability?

- `.ifc` is needed to compare strings.
- Clang doesn't support `.func` and `.endfunc` the docs say that this is only relevant for stabs format debugging so these can probably be removed.
- Clang doesn't support the alternate `&` concatenation operator, it needs to be `\()` instead.

For now, the Helium assembly you added cannot be used with either LLVM or Arm Compiler 6, we would detect the compiler and disable the assembly accordingly.

Once you solved the compatibility issue, we can allow it work in LLVM and AC6.

Please take the following code as example:

```asm
.macro blender src_bpp, dst_bpp, mask, opa, mode
nop
.endm

.macro export name, src_bpp, dst_bpp, mask, opa, mode
.thumb_func
.global \name
\name\():
    blender     src_bpp, dst_bpp, mask, opa, mode
.endm

.macro export_set src, dst, src_bpp, dst_bpp, mode
.ifc \src,color
    export lv_\()src\()_blend_to_\()dst\()_helium, src_bpp, dst_bpp, 0, 0, mode
.else
nop
.endif
.endm

```

**Comment by kisvegabor** [comment]
Thank you, I've tried out the changes. 

With RGB565 now it's faster, but has exactly the same speed as the SW renderer. 

In XRGB8888 format it's very slow, I saw about 5 FPS. :slightly_frowning_face:

**Comment by PeterBee97** [comment]
Abandoned altmacro mode and now it can be compiled by clang. Also did some optimizations to 32bpp load & store. Would you look at this again? @kisvegabor @GorgonMeducer

**Comment by kisvegabor** [comment]
@PeterBee97 With the latest code there is no compiler error, but the Clang hangs after compiling a lot of files. So I cannot verify the changes. :slightly_frowning_face: 

Once it's assembly, for performance measurement I can use any compiler, right?

**Comment by kisvegabor** [comment]
After ten minutes it continued compiling and prints a loooooot of error like these:
image

Does it say anyhing to you?

**Comment by PeterBee97** [comment]
The error is with the previous version, and with the latest change there should be no more "&" which could cause clang to output too many errors and hang. I have modified them according to GorgonMeducers's advice. Could you please pull the latest change again? @kisvegabor

**Comment by kisvegabor** [comment]
Sorry for the late feedback.

The current version compiles well with LLVM. With RGB565 the performance is the same as with SW render, but with XRGB8888 Helium is ~50% slower. 

In your tests have you measured faster rendering?

**Comment by PeterBee97** [comment]
> In your tests have you measured faster rendering?

Sorry I do not have suitable hardware at hand. I am considering the RT-Thread vision board which just came out featuring the same Renesas Cortex-M85 MCU. Maybe we can merge this PR and continue to optimize later?

**Review by FASTSHIFT — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
I agree to merge it as it contains important updates to compile under LLVM.
Thank you for the fixes so far. Please let us know if you could test it on your end.

**Pull request merged**
