### PR TITLE
fix(libinput): include types.h

### PR DESCRIPTION
**Pull request by liamHowatt**
Fixes https://github.com/lvgl/lvgl/pull/6869#issuecomment-2379804162

Include lv_types.h

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — APPROVED** [review]

**Review by kissa96 — APPROVED** [review]
LGTM

**Comment by mverch67** [comment]
It still doesn't seem to work:

```
In file included from .pio/libdeps/native-tft-debug/lvgl/src/lvgl_private.h:48,
                 from lib/device-ui/source/TFTView_320x240.cpp:16:
.pio/libdeps/native-tft-debug/lvgl/src/drivers/libinput/lv_libinput_private.h:45:25: error: field ‘points’ has incomplete type ‘lv_libinput_event_t [32]’
   45 |     lv_libinput_event_t points[LV_LIBINPUT_MAX_EVENTS]; /* Event buffer */
      |                         ^~~~~~
In file included from .pio/libdeps/native-tft-debug/lvgl/src/lv_init.h:17,
                 from .pio/libdeps/native-tft-debug/lvgl/lvgl.h:21,
                 from lib/device-ui/include/MeshtasticView.h:6,
                 from lib/device-ui/include/TFTView_320x240.h:3,
                 from lib/device-ui/source/TFTView_320x240.cpp:3:
.pio/libdeps/native-tft-debug/lvgl/src/misc/lv_types.h:294:16: note: forward declaration of ‘lv_libinput_event_t’ {aka ‘struct lv_libinput_event_t’}
  294 | typedef struct lv_libinput_event_t lv_libinput_event_t;
      |                ^~~~~~~~~~~~~~~~~~~
.pio/libdeps/native-tft-debug/lvgl/src/drivers/libinput/lv_libinput_private.h:46:25: error: field ‘slots’ has incomplete type ‘lv_libinput_event_t [2]’
   46 |     lv_libinput_event_t slots[2]; /* Realtime state of up to 2 fingers to handle multitouch */
      |                         ^~~~~
.pio/libdeps/native-tft-debug/lvgl/src/misc/lv_types.h:294:16: note: forward declaration of ‘lv_libinput_event_t’ {aka ‘struct lv_libinput_event_t’}
  294 | typedef struct lv_libinput_event_t lv_libinput_event_t;
      |                ^~~~~~~~~~~~~~~~~~~
.pio/libdeps/native-tft-debug/lvgl/src/drivers/libinput/lv_libinput_private.h:54:25: error: field ‘last_event’ has incomplete type ‘lv_libinput_event_t’
   54 |     lv_libinput_event_t last_event; /* Report when no new events
      |                         ^~~~~~~~~~
.pio/libdeps/native-tft-debug/lvgl/src/misc/lv_types.h:294:16: note: forward declaration of ‘lv_libinput_event_t’ {aka ‘struct lv_libinput_event_t’}
  294 | typedef struct lv_libinput_event_t lv_libinput_event_t;
      |                ^~~~~~~~~~~~~~~~~~~
.pio/libdeps/native-tft-debug/lvgl/src/drivers/libinput/lv_libinput_private.h:65:14: error: field ‘xkb’ has incomplete type ‘lv_xkb_t’
   65 |     lv_xkb_t xkb;
      |              ^~~
.pio/libdeps/native-tft-debug/lvgl/src/misc/lv_types.h:292:16: note: forward declaration of ‘lv_xkb_t’ {aka ‘struct lv_xkb_t’}
  292 | typedef struct lv_xkb_t lv_xkb_t;
      |                ^~~~~~~~
```

**Comment by mverch67** [comment]
Ok, actually I just copied these changes of this PR into my code (based on branch 9.2.0 + PR6869). Maybe I should checkout master... let me do this ...

**Comment by mverch67** [comment]
OK, it compiles when using master, also without the changes above. I assume the below forward declarations in lv_types.h were still missing in version 9.2.0 that I tested before. Now all is good! Thanks!

```
typedef struct lv_xkb_t lv_xkb_t;
typedef struct lv_libinput_event_t lv_libinput_event_t;
typedef struct lv_libinput_t lv_libinput_t;
```

**Comment by liamHowatt** [comment]
> Now all is good!

Glad to hear!

I think this should be added anyways.

**Comment by kisvegabor** [comment]
As it's reported to be working, I close this issue.

**Pull request closed without merging**
