### PR TITLE
ci(tests): Build Unix port MicroPython submodules in parallel.

### PR DESCRIPTION
**Pull request by cmumford**
Added missing `-j <numcores>` when building MicroPython submodules.

### CODE REVIEW

**Comment by cmumford** [comment]
Looks like the CI step in which this is included drops from 51 sec. to 41 sec. Nothing massive, but I'll take it.

**Comment by embeddedt** [comment]
Have you seen a measurable performance improvement from this? I also thought of doing it in the past but [the target](https://github.com/lvgl/lv_micropython/blob/1fcd6e97f29f817a56237bf70d55edb159c8ccf6/py/mkrules.mk#L201-L205) doesn't look like it can be parallelized. I wonder if your 10 second improvement is caused by Actions being less loaded at this time of night.

**Comment by cmumford** [comment]
> Have you seen a measurable performance improvement from this? I also thought of doing it in the past but [the target](https://github.com/lvgl/lv_micropython/blob/1fcd6e97f29f817a56237bf70d55edb159c8ccf6/py/mkrules.mk#L201-L205) doesn't look like it can be parallelized.

Good point. Maybe the gain of 10 sec. was just a measurement error. We could either leave the `-j` where it won't do anything unless the make target improves, or I can delete it, and add a workflow comment to explain it's absence. What do you prefer?

**Comment by embeddedt** [comment]
I'd prefer removing it, only because upstream is not running it with `-j`, and I'd rather not deal with random CI failures that could result if they change the way it works behind the scenes.

**Comment by cmumford** [comment]
SGTM. I'll abandon this and add add a comment in another PR to prevent other devs from trying the same.

**Pull request closed without merging**
