### PR TITLE
fix(arc):color display error when color opa was used

### PR DESCRIPTION
**Pull request by guoweilkd**
### Description of the feature or fix

see #2668

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
It's a good idea but it can always happen that 2 anti aliased edges doesn't cover each other perfectly. 

Imagine this: 
- The arc has a pixel with 50% opacity on the edge. 
- The arc is black, the background is white so the result will be 0x808080. 
- If all calculation are accurate and the mask tells the the circle also has 50% opacity at the same point, now 0x808080 will be mixed with black resulting in 0x404040. However we expected pure black at the joint of the circle and the arc. 


I was also thinking about this issue earlier and find a different approach. Now the masks are "destructive". It means that they can only remove parts. But with a "builder" type we could build the back the circles.  What do you think?

**Comment by guoweilkd** [comment]
> But with a "builder" type we could build the back the circles
A good idea， Is there a specific release date for the function?

**Comment by kisvegabor** [comment]
Unfortunately I have no time to add it now, but I added it to my todo list for v8.2.
(I'm planning to release v8.1 next week.)

**Comment by embeddedt** [comment]
It sounds like this PR was ultimately not the best approach and it has conflicts; can it be closed?

**Comment by kisvegabor** [comment]
I think yes. I'm thinking about how to fix it whit the new draw architecture.

**Pull request closed without merging**
