### PR TITLE
build: Add install rule

### PR DESCRIPTION
**Pull request by rzr**
This can be help to install lvgl on systems,
for clients applications.

Relate-to: https://github.com/lvgl/lvgl/issues/2534
Signed-off-by: Philippe Coval <philippe.coval@astrolabe.coop>

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Won't it mess up hardware specific cases? E.g. `ESP_PLATFORM`, `ZEPHYR_BASE`, `MICROPY_DIR`.

**Comment by rzr** [comment]
I dont think so f other platforms are not using "make install" this will be ignored 
and if they do, then issue can be solved later or cmake should do it better than us.

We could make it more linux specific but it would add more noise.
I can surround by if linux if it help to get it merged

**Comment by kisvegabor** [comment]
To be honest I'm not an expert of CMake so can't really judge if it's ok or not.

@embeddedt, @xiaoxiang781216, @amirgon could you take a look?

**Comment by amirgon** [comment]
@rzr I'm not sure this works with ESP32 Micropython port.
Did you test it on this configuration?

**Comment by rzr** [comment]
No I didnt but if "make install" is not invoked it should not cause any harm, but if you want to make sure let's add if (UNIX) test

**Comment by amirgon** [comment]
> No I didnt but if "make install" is not invoked it should not cause any harm, but if you want to make sure let's add if (UNIX) test

I think it makes sense to ensure it doesn't break anything, even when "install" is not called.

@embeddedt @kisvegabor a CI test for Micropython ESP32 port could be useful since it relies on LVGL cmake script, if you think it is worth the extra time LVGL tests run.

**Comment by kisvegabor** [comment]
@amirgon I agree with both. 

@rzr Please, add an `if` for "install".

**Comment by rzr** [comment]
well I made a quick test with platformio (which invoke cmake) and I can confirm there is no regression,
but I can add an option to enable this part , like if unix if you want to make sure...

**Comment by kisvegabor** [comment]
> if unix if you want to make sure...

It'd be great, thank you. IMO it also improves readability.

**Comment by rzr** [comment]
I isolated the "if(install)" change

**Comment by kisvegabor** [comment]
Thank you, merging!

**Pull request merged**
