### PR TITLE
lv_roller_set_align and some minor bug fixes

### PR DESCRIPTION
**Pull request by aenchevich**

### CODE REVIEW

**Comment by aenchevich** [comment]
This needs a little more work... the strings inside the lv_roller->ddlist->label are properly aligned (Right Left or Center), however the label itself is always centered, i.e. if the width of the greatest string is < than the width of the roller there will be 2 equally sized margins on both sides of the label.

**Comment by kisvegabor** [comment]
I agree with @embeddedt It's clearer to have one PR with a lot of commits than a lot of PR with a few commits. So it's fine to improve the code here. Your code doesn't have to be perfect at first. 

I've just pushed a fix the align issue if the label is not wide enough.

**Comment by aenchevich** [comment]
Oh, ok ... thanks for pointing this out!

I just needed a way to stop this from merging until I am ready. I did not know that [WIP] would do it. Is it some standard github feature/convention or it's just something that was agreed on in this repo and I missed it somehow?

I think I am ready with it, so no point to add the [WIP] tag now... I will see if I can reopen it somehow or worst case scenario - will create a new one!  :)

**Comment by embeddedt** [comment]
@kisvegabor already reopened it for you, so don't worry. I think WIP is a standard convention among most open-source projects to say "don't merge, it's work-in-progress.

**Comment by embeddedt** [comment]
I noticed that you have removed the transparency check in `lv_refr.c`. Can you explain why this was necessary?

**Comment by kisvegabor** [comment]
@embeddedt 
I removed it because it checked `bopy.opa` (see: https://github.com/littlevgl/lvgl/commit/c5845869857b8edda207d31a47d8a6e3bf0d3d41) but it's not sure that the design function deals with `body` styles. For example, why not draw a label if it's parent's `body.opa == LV_OPA_TRANSP`?  I needed to fix it when used some complex animations and the labels were not drawn correctly.

**Comment by embeddedt** [comment]
@kisvegabor Ok, no problem then.

**Comment by embeddedt** [comment]
@aenchevich This appears stable on all themes so I am going to merge it.

Thanks for this feature!

**Comment by aenchevich** [comment]
Hi guys, thanks for the discussion and for merging the feature ... and sorry for my sometimes tardy responses.I work part time on things related to lvgl and when working on other projects don't always have the ability to check my emails...

**Comment by kisvegabor** [comment]
@BrianPugh I fixed it. Please test it.

**Comment by aenchevich** [comment]
Thank you Gabor!

**Comment by kisvegabor** [comment]
@aenchevich No problem and thank you for this improvement! :)

**Comment by BrianPugh** [comment]
Fixes my issues, thanks guys!

**Pull request merged**
