### PR TITLE
Fixing failure to invalidate indicator

### PR DESCRIPTION
**Pull request by paulpv**
Updating this branch to dev-6.1 and then adding tiny commit

### CODE REVIEW

**Comment by embeddedt** [comment]
I'll merge this one manually tomorrow (to keep the commit history clean).

**Review by embeddedt — APPROVED** [review]

**Comment by paulpv** [comment]
Thanks. Yes, it was a much uglier merge than I was expecting. :/

**Comment by kisvegabor** [comment]
Wow, even the comments other commits are included.

@paulpv Thank you for the fix. 
I suggest updating from the destination branch (`dev-6.1` in this case) before sending a PR to have a cleaner history.

**Comment by paulpv** [comment]
I did merge from dev-6.1.
The feat-cpicker branch is just that much behind.

**Comment by kisvegabor** [comment]
> The feat-cpicker branch is just that much behind.

Oh, true, really it causes the problem.

**Comment by embeddedt** [comment]
I've confirmed that this fixes the issue for me.

**Comment by kisvegabor** [comment]
Great, thank you!

**Pull request merged**
