### PR TITLE
Fix kconfig warnings

### PR DESCRIPTION
**Pull request by liebman**
quote string defaults for Kconfig values to eliminate warnings 

Building for `esp32` using `esp-idf` generates warnings when default string values are not quoted on `Kconfig`
```
warning: style: quotes recommended around default value for string symbol LV_MEM_CUSTOM_INCLUDE (defined at components/lvgl/Kconfig:112)
warning: style: quotes recommended around default value for string symbol LV_MEM_CUSTOM_ALLOC (defined at components/lvgl/Kconfig:118)
warning: style: quotes recommended around default value for string symbol LV_MEM_CUSTOM_FREE (defined at components/lvgl/Kconfig:124)
warning: style: quotes recommended around default value for string symbol LV_TICK_CUSTOM_INCLUDE (defined at components/lvgl/Kconfig:286)
```
Note that the default values for `LV_TICK_CUSTOM_SYS_TIME_EXPR` contains `(` and `)` and these should be
escaped with a `\` on Linux and MacOS, I did not change this as I can not test on Windows and don't know if that
would cause any issues.

### Chekpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
cc @Maldus512, @C47D could you comement on this?

**Comment by C47D** [comment]
Will test on in a couple of hours.

**Comment by Maldus512** [comment]
Now that I see it I seem to remember stumbling upon this warning, but at this moment I can't reproduce it.
Regardless I have no objections to this, default string values should indeed include quotes and I simply forgot to add them.

**Comment by C47D** [comment]
Saw those warnings yesterday, with this PR they are fixed.

**Comment by C47D** [comment]
@liebman Is this ready to merge? I think there's two items of the checkbox to be checked.

**Comment by liebman** [comment]
Yes, its ready, I don't think there is a need for documentation or changelog entries for this. Should I check them anyway?

**Comment by C47D** [comment]
I don't think so, let's wait for @kisvegabor comment.

**Comment by vanwinkeljan** [comment]
One general note on this change is that they will break the build if not passed as compile time macros as done for `esp-idf`

```
modules/lib/gui/lvgl/src/lv_misc/lv_mem.c: In function ‘lv_mem_alloc’:
zephyr/include/generated/autoconf.h:27:36: error: called object is not a function or function pointer
 #define CONFIG_LV_MEM_CUSTOM_ALLOC "k_malloc"
                                    ^~~~~~~~~~
modules/lib/gui/lvgl/src/lv_misc/../lv_conf_internal.h:241:33: note: in expansion of macro ‘CONFIG_LV_MEM_CUSTOM_ALLOC’
 #    define LV_MEM_CUSTOM_ALLOC CONFIG_LV_MEM_CUSTOM_ALLOC
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
modules/lib/gui/lvgl/src/lv_misc/lv_mem.c:193:13: note: in expansion of macro ‘LV_MEM_CUSTOM_ALLOC’
     alloc = LV_MEM_CUSTOM_ALLOC(size + sizeof(lv_mem_header_t));
             ^~~~~~~~~~~~~~~~~~~

```

edit: just for the record, I can perfectly live with the compile time macros but maybe it is better to error out in `lv_conf_internal.h:241` instead of using the sting later on as function

**Comment by kisvegabor** [comment]
You are more into Kconfig so maybe I'm telling nonsense thing but won't these options are really passed as strings now? And LVGL will see them as `"malloc"(size)`. Seemingly that's the source of @vanwinkeljan's issue too.

**Comment by vanwinkeljan** [comment]
> You are more into Kconfig so maybe I'm telling nonsense thing but won't these options are really passed as strings now? And LVGL will see them as "malloc"(size). Seemingly that's the source of @vanwinkeljan's issue too.

Yes that is the case, the options are passed as string but the solution of @Maldus512 (see PR #1961) to pass the options as compiler defines works perfectly. I used the same solution for the Zephyr integration (#1979) and it works as expected.

Note that incase the warnings are not fixed it will be a hard time to integrate with Zephyr as they handle any Kconfig warning as an error.

**Comment by liebman** [comment]
Regardless of being quoted in the `Kconfig` file or not, its still generated as a string.  Without quotes it generates a warning.

**Comment by C47D** [comment]
So #1979 needs this PR being merged? With this patch I no longer see the Kconfig warnings.

**Comment by vanwinkeljan** [comment]
> So #1979 needs this PR being merged?

Not PR #1979 on itself but LVGL will not build for Zephyr as long as these warnings are around.

> With this patch I no longer see the Kconfig warnings.

Same for me

**Comment by kisvegabor** [comment]
Is there any point to keep the current "string-like" options once they can't be "destringified"?

I think we would be better with a generic `LV_MEM_CUSTOM_STD` option that is mapped to `malloc`/`free` in `lv_conf_kconfig.h`.
What do you think?

**Comment by Maldus512** [comment]
> I think we would be better with a generic LV_MEM_CUSTOM_STD option that is mapped to malloc/free in lv_conf_kconfig.h.
What do you think?

You mean having only the two options of lvgl-managed memory or malloc/free instead of an arbitrary allocation/deallocation function pair? To me this sounds good, those are the only two solutions I've ever considered anyway.

**Comment by kisvegabor** [comment]
By default yes, but you can still set e.g. `LV_MEM_CUSTOM_ALLOC` to any value as @vanwinkeljan did [here](https://github.com/lvgl/lvgl/pull/1979/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR46).

Thinking about it again, I think only one config is required in Kconfig: `LV_MEM_CUSTOM`. It's because LVGL set the `LV_MEM_CUSTOM_ALLOC/FREE` to `malloc/free` if they are not set.

**Comment by vanwinkeljan** [comment]
@kisvegabor 
> By default yes, but you can still set e.g. LV_MEM_CUSTOM_ALLOC to any value as @vanwinkeljan did here.

Actually I'm using the Kconfig values there for free and alloc and in case of zephyr we have three possible free/allocation functions (k_malloc/k_free, malloc/free & lvgl_malloc/lvgl_free)

**Comment by kisvegabor** [comment]
So would the default `malloc`/`free` work as well? Or do you need to use the `k_` prefixed version?

**Comment by vanwinkeljan** [comment]
It will not work but I could revert back the solution I used before and set the defines `LV_MEM_CUSTOM_ALLOC/FREE` in a header file*.

But one of the advantages of of using Kconfig is that the user can overwrite it with a custom function only downside is that you need to pass it to the compiler as a compile time definition to remove the quotes.

edit: * example of header file https://github.com/zephyrproject-rtos/zephyr/blob/d727b2988302e0cf2114385d16e8be9c2043a232/lib/gui/lvgl/zephyr_lvgl_conf.h

**Comment by C47D** [comment]
I would change the way custom memory allocation works (if necessary) in another PR, to keep this one just to fix the warnings. But that's personal opinion only.

**Comment by kisvegabor** [comment]
@vanwinkeljan Got it now, thanks.


@C47D  Ok, let's merge this just to solve the warning and please open a new PR for the custom alloc.

**Pull request merged**
