### PR TITLE
update doc os: lv_time_handler to task_handler

### PR DESCRIPTION
**Pull request by rafaelcorsi**
`lv_task_handler` as the example code. 

- [x] Update the documentation

### CODE REVIEW

**Comment by embeddedt** [comment]
`lv_timer_handler` is the new name in v8+. `lv_task_handler` still exists but is just a legacy macro for those transitioning from v7.

**Comment by rafaelcorsi** [comment]
> `lv_timer_handler` is the new name in v8+. `lv_task_handler` still exists but is just a legacy macro for those transitioning from v7.

this appears in a few other places in the doc, I can review everything and update this PR if you think it's necessary.

https://github.com/lvgl/lvgl/blob/a7cfc0b9015a501860ce6456fa1aa80a83750480/docs/intro/index.md#lvgl-doesnt-start-randomly-crashes-or-nothing-is-drawn-on-the-display-what-can-be-the-problem

**Comment by embeddedt** [comment]
As far as I can tell, all the references on that page are using the correct (new) name already, unless I missed something?

**Comment by embeddedt** [comment]
I'm going to close this as I think the current docs are correct.

**Pull request closed without merging**
