### PR TITLE
Try to fix a label bug.

### PR DESCRIPTION
**Pull request by Polarix**
### Feature
- Add a interface for label, used for set a formated text with argument list.
 
### Fix
- Fix label text paint will overflow the border when long mode set to LV_LABEL_LONG_CLIP.

### CODE REVIEW

**Comment by kisvegabor** [comment]
> Fix label text paint will overflow the border when long mode set to LV_LABEL_LONG_CLIP.

Could you show a code snippet to reproduce this issue?

**Comment by Polarix** [comment]
> > Fix label text paint will overflow the border when long mode set to LV_LABEL_LONG_CLIP.
> 
> Could you show a code snippet to reproduce this issue?

OK，following is demo code.

```c
            lv_obj_t* label_obj = lv_label_create(s_container_panel);
            lv_obj_set_style_text_font(label_obj, &regular_24px, LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(label_obj, lv_color_black(), LV_STATE_DEFAULT);
            lv_label_set_text(label_obj, "Hello world!Hello world!");
            lv_obj_set_pos(label_obj, 5, 5);
            lv_obj_set_size(label_obj, 100, LV_SIZE_CONTENT);
            lv_label_set_long_mode(label_obj, LV_LABEL_LONG_CLIP);
            lv_obj_set_style_border_width(label_obj, 1, LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(label_obj, lv_color_black(), LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(label_obj, LV_OPA_100, LV_STATE_DEFAULT);
```
Without borders, this is really difficult to detect。

**Comment by kisvegabor** [comment]
Thank you!

I think I could fix the clipping issue like this:
```c
//lv_label.c, draw_main()
    if(label->long_mode == LV_LABEL_LONG_WRAP) {
        int32_t s = lv_obj_get_scroll_top(obj);
        lv_area_move(&txt_coords, 0, -s);
        txt_coords.y2 = obj->coords.y2;
    }
    /*Check LV_LABEL_LONG_CLIP too*/
    else if(label->long_mode == LV_LABEL_LONG_SCROLL || label->long_mode == LV_LABEL_LONG_SCROLL_CIRCULAR || label->long_mode == LV_LABEL_LONG_CLIP) {
        const lv_area_t clip_area_ori = layer->clip_area;
        layer->clip_area = txt_clip;
        lv_draw_label(layer, &label_draw_dsc, &txt_coords);
        layer->clip_area = clip_area_ori;
    }
    else {
        lv_draw_label(layer, &label_draw_dsc, &txt_coords);
    }

```

If you agree, could you modify the PR accordingly?

**Comment by lhdjply** [comment]
> Thank you!
> 
> I think I could fix the clipping issue like this:
> 
> ```c
> //lv_label.c, draw_main()
>     if(label->long_mode == LV_LABEL_LONG_WRAP) {
>         int32_t s = lv_obj_get_scroll_top(obj);
>         lv_area_move(&txt_coords, 0, -s);
>         txt_coords.y2 = obj->coords.y2;
>     }
>     /*Check LV_LABEL_LONG_CLIP too*/
>     else if(label->long_mode == LV_LABEL_LONG_SCROLL || label->long_mode == LV_LABEL_LONG_SCROLL_CIRCULAR || label->long_mode == LV_LABEL_LONG_CLIP) {
>         const lv_area_t clip_area_ori = layer->clip_area;
>         layer->clip_area = txt_clip;
>         lv_draw_label(layer, &label_draw_dsc, &txt_coords);
>         layer->clip_area = clip_area_ori;
>     }
>     else {
>         lv_draw_label(layer, &label_draw_dsc, &txt_coords);
>     }
> ```
> 
> If you agree, could you modify the PR accordingly?

this is version 8.3 ，is not master。
`lv_draw_label(layer,` &label_draw_dsc, &txt_coords);
The function is missing two parameters

**Comment by kisvegabor** [comment]
Yes, I really tested with `master`. However the idea is the same, just add the CLIP mode here:
```c
    else if(label->long_mode == LV_LABEL_LONG_SCROLL || label->long_mode == LV_LABEL_LONG_SCROLL_CIRCULAR || label->long_mode == LV_LABEL_LONG_CLIP) {

```

**Comment by Polarix** [comment]
> Yes, I really tested with `master`. However the idea is the same, just add the CLIP mode here:
> 
> ```c
>     if(label->long_mode == LV_LABEL_LONG_SCROLL || label->long_mode == LV_LABEL_LONG_SCROLL_CIRCULAR || label->long_mode == LV_LABEL_LONG_CLIP) {
> ```

And there is also the bug of overflow of the top and bottom border in LV_LABEL_LONG_WRAP mode.
Like this.
lvgl_bug-2

**Comment by kisvegabor** [comment]
Ahh, true! Just to see why it happens: In some cases the letters of italic fonts are out of their box. And if we set the `lv_label`'s size according the box sizes of the letters, parts of the last letter might be clipped. 

See 
image


So now we have a few pixels of extra draw area round the label. However it should be applied only horizontally in case of `WARP` mode. In other modes we should clip the text to the real widget size.  

What do you think?

**Comment by Polarix** [comment]
> Ahh, true! Just to see why it happens: In some cases the letters of italic fonts are out of their box. And if we set the `lv_label`'s size according the box sizes of the letters, parts of the last letter might be clipped.
> 
> See image
> 
> So now we have a few pixels of extra draw area round the label. However it should be applied only horizontally in case of `WARP` mode. In other modes we should clip the text to the real widget size.
> 
> What do you think?

But in my opinion，what ever, all of text paint should not overflow the border，so the clip area should not greater then border of the control。
According to my previous win32 development experience，MFC & wxWidgets both are like this.

Demo

**Comment by Polarix** [comment]
Append a shot with different bg color.
Demo2

**Comment by kisvegabor** [comment]
And do you solve the issue of clipped letters  in wxWidgets or Win32?

In LVGL we could say that the user should add some padding to the labels.

**Comment by Polarix** [comment]
> And do you solve the issue of clipped letters in wxWidgets or Win32?
> 
> In LVGL we could say that the user should add some padding to the labels.

No no no, I mean that's paint content cannot overflow the border in others GUI like QT or wxWidgets.
and in LVGL, set pading style cannot reduce the clip area。

I think that if text paint is allowed to overflow the control border, then overlap might be happening. like this.
lvgl_bug-3
But if overlaped control repaint, out of label control area content is not repaint, like this, after clicked, button will be repaint. but out of label content will be covered.
lvgl_bug-4

so, in my opinion, in any case, it makes no sense to draw control content outside of the control.

**Comment by kisvegabor** [comment]
I see, so what we can do is:
- set the text's clip are to the widget's coordinates 
- if the user needs a larger area around the text he can use padding. E.g.
image
```c
  lv_obj_t * label = lv_label_create(lv_scr_act());
  lv_obj_center(label);
  lv_obj_set_style_border_width(label, 1, 0);
  lv_obj_set_style_pad_all(label, 20, 0);
```

**Comment by Polarix** [comment]
> I see, so what we can do is:
> 
> * set the text's clip are to the widget's coordinates
> * if the user needs a larger area around the text he can use padding. E.g.
>   image
> 
> ```c
>   lv_obj_t * label = lv_label_create(lv_scr_act());
>   lv_obj_center(label);
>   lv_obj_set_style_border_width(label, 1, 0);
>   lv_obj_set_style_pad_all(label, 20, 0);
> ```

Yes, pad value might be useful, but it's not a panacea, I found this issue because I was try to make such a widget:
lvgl_bug-5
In this widget, multiple strings will be stored, when current string scrolling end, next string will scroll up to replace current string.
I try to set pad value to set text vertical center, but it shown like this.
so, I think the pad value might no improve when text-height/widget+pad is greater then label control height/widget.

**Comment by kisvegabor** [comment]
I mean applying padding on the label widget.

**Comment by kisvegabor** [comment]
I'll take care of this before releasing v9

**Comment by kisvegabor** [comment]
Not stale

**Comment by kisvegabor** [comment]
Closing this PR now. See https://github.com/lvgl/lvgl/pull/5381

**Pull request closed without merging**
