### PR TITLE
Add deinit function

### PR DESCRIPTION
**Pull request by amirgon**
deinit is needed to allow soft reset when gc is enabled. In such case, need to clear roots upon soft reset otherwise lvgl would hold pointers to invalid addresses. See #1316

### CODE REVIEW

**Comment by embeddedt** [comment]
I think `lv_deinit` should ideally work without memory leaks outside of MicroPython. Currently, I don't see where heap memory is explicitly freed (this is important if `LV_MEM_CUSTOM == 1`). What do you think?

**Comment by kisvegabor** [comment]
> I think lv_deinit should ideally work without memory leaks outside of MicroPython. Currently, I don't see where heap memory is explicitly freed (this is important if LV_MEM_CUSTOM == 1). What do you think?

I was also thinking about similar things. `lv_mem` can be easily reset by a `memset` but with `LV_MEM_CUSTOM` all allocated needs to be freed one by one. It includes:
- delete all objects
- delete drivers
- delete tasks
- delete animations
- free linked lists (task, animations, drivers)
- etc

As Micropython also uses `LV_MEM_CUSTOM` won't it be a problem?

**Comment by embeddedt** [comment]
> As Micropython also uses `LV_MEM_CUSTOM` won't it be a problem?

My guess is that MicroPython resets its heap on a soft reset, but we can't rely on everyone having that ability.

**Comment by amirgon** [comment]
@embeddedt @kisvegabor,
On soft reset all gc RAM is freed, and as a result all lvgl root pointers are invalid.
If we don't clear them, lvgl crashes.

This is not specific to Micropython, but to any case lvgl is used with garbage collection.  
If you want, we can put the memset in `#if LV_ENABLE_GC`.

This PR is not a full support for lvgl deallocation, but it is good enough for gc because all objects/drivers/... would be deallocated by gc automatically on soft reset.  
If we want we can always extend this to support other custom memory allocators, **but this PR is only a solution for #1316, not for the general case**.

**Comment by kisvegabor** [comment]
Fair enough. 
We can merge it if @embeddedt also agrees.

**Comment by embeddedt** [comment]
> This PR is not a full support for lvgl deallocation, but it is good enough for gc

In that case, we should add a note above `lv_deinit` explaining this. Otherwise, someone will use it, and wonder why not everything is actually being reset.

**Comment by amirgon** [comment]
> In that case, we should add a note above `lv_deinit` explaining this. Otherwise, someone will use it, and wonder why not everything is actually being reset.

If you want, we can put `lv_deinit` itself in `#if LV_ENABLE_GC` such that it would be available only when using gc.

**Comment by embeddedt** [comment]
That should work.

**Comment by kisvegabor** [comment]
Actually, with`LV_MEM_CUSTOM == 0` (probably the most common case) we can do a "real" deinit if `lv_mem` is also cleared, isn't it? See my commit above.

If so, only a note should be added like:
"If `LV_MEM_CUSTOM 1` you need to clean the heap manually."

What do you think?

**Comment by amirgon** [comment]
> Actually, with`LV_MEM_CUSTOM == 0` (probably the most common case) we can do a "real" deinit if `lv_mem` is also cleared, isn't it? See my commit above.

Good idea.

> If so, only a note should be added like:
> "If `LV_MEM_CUSTOM 1` you need to clean the heap manually."

Maybe worth adding an assert if someone tries to call deinit with `LV_MEM_CUSTOM == 1` and `LV_ENABLE_GC == 0`.

btw what are all the other commits that you added other than cb8bf4740636abab12b582ebfd32f51ff4878fbd? seem unrelated?

**Comment by kisvegabor** [comment]
> Maybe worth adding an assert if someone tries to call deinit with LV_MEM_CUSTOM == 1 and LV_ENABLE_GC == 0.

And/or a warning?

> btw what are all the other commits that you added other than cb8bf47? seem unrelated?

Accidentally I've pushed some `dev-7.0` commits to master and things messed up...
I've reset `master` and added the commits from another branch (`c64-test`).

It was stupid but I wonder how it hasn't happened earlier. Probably once I pulled `dev-7.0` to `master`, fixed something and pushed it.

**Comment by amirgon** [comment]
> > Maybe worth adding an assert if someone tries to call deinit with LV_MEM_CUSTOM == 1 and LV_ENABLE_GC == 0.
> 
> And/or a warning?

I think it should be either an error that stops execution, or simply put `deinit` inside `#if` such it wouldn't be available for someone who uses `LV_MEM_CUSTOM == 1` and `LV_ENABLE_GC == 0`

> Accidentally I've pushed some `dev-7.0` commits to master and things messed up...

:laughing: that must happen from time to time.

**Comment by kisvegabor** [comment]
> or simply put deinit inside #if such it wouldn't be available for someone who uses LV_MEM_CUSTOM == 1 and LV_ENABLE_GC == 0

It seems the most error-proof solution to me.

**Comment by amirgon** [comment]
> It seems the most error-proof solution to me.

66c100770338e5972f9677dc1487480829ae1b2b

**Comment by kisvegabor** [comment]
It's ok from my side.
@embeddedt ?

**Review by embeddedt — APPROVED** [review]
:+1:

**Comment by spierepf** [comment]
Thanks for fixing this. I really appreciate the effort. However, when I try to check out a fresh copy:

```
$ git clone --recurse-submodules https://github.com/littlevgl/lv_micropython.git
Cloning into 'lv_micropython'...
remote: Enumerating objects: 76715, done.
remote: Total 76715 (delta 0), reused 0 (delta 0), pack-reused 76715
Receiving objects: 100% (76715/76715), 53.05 MiB | 4.06 MiB/s, done.
Resolving deltas: 100% (55417/55417), done.
Submodule 'lib/asf4' (https://github.com/adafruit/asf4) registered for path 'lib/asf4'
Submodule 'lib/axtls' (https://github.com/pfalcon/axtls) registered for path 'lib/axtls'
Submodule 'lib/berkeley-db-1.xx' (https://github.com/pfalcon/berkeley-db-1.xx) registered for path 'lib/berkeley-db-1.xx'
Submodule 'lib/libffi' (https://github.com/atgreen/libffi) registered for path 'lib/libffi'
Submodule 'lib/lv_bindings' (https://github.com/littlevgl/lv_bindings.git) registered for path 'lib/lv_bindings'
Submodule 'lib/lwip' (https://git.savannah.gnu.org/r/lwip.git) registered for path 'lib/lwip'
Submodule 'lib/mbedtls' (https://github.com/ARMmbed/mbedtls.git) registered for path 'lib/mbedtls'
Submodule 'lib/mynewt-nimble' (https://github.com/apache/mynewt-nimble.git) registered for path 'lib/mynewt-nimble'
Submodule 'lib/nrfx' (https://github.com/NordicSemiconductor/nrfx.git) registered for path 'lib/nrfx'
Submodule 'lib/stm32lib' (https://github.com/micropython/stm32lib) registered for path 'lib/stm32lib'
Submodule 'lib/tinyusb' (https://github.com/hathach/tinyusb) registered for path 'lib/tinyusb'
Cloning into '/home/build/lv_micropython/lib/asf4'...
remote: Enumerating objects: 1520, done.        
remote: Total 1520 (delta 0), reused 0 (delta 0), pack-reused 1520        
Receiving objects: 100% (1520/1520), 1.75 MiB | 3.18 MiB/s, done.
Resolving deltas: 100% (928/928), done.
Cloning into '/home/build/lv_micropython/lib/axtls'...
remote: Enumerating objects: 1, done.        
remote: Counting objects: 100% (1/1), done.        
remote: Total 3191 (delta 0), reused 1 (delta 0), pack-reused 3190        
Receiving objects: 100% (3191/3191), 3.81 MiB | 3.69 MiB/s, done.
Resolving deltas: 100% (2342/2342), done.
Cloning into '/home/build/lv_micropython/lib/berkeley-db-1.xx'...
remote: Enumerating objects: 270, done.        
remote: Total 270 (delta 0), reused 0 (delta 0), pack-reused 270        
Receiving objects: 100% (270/270), 332.23 KiB | 2.09 MiB/s, done.
Resolving deltas: 100% (127/127), done.
Cloning into '/home/build/lv_micropython/lib/libffi'...
remote: Enumerating objects: 12491, done.        
remote: Total 12491 (delta 0), reused 0 (delta 0), pack-reused 12491        
Receiving objects: 100% (12491/12491), 7.37 MiB | 4.55 MiB/s, done.
Resolving deltas: 100% (7833/7833), done.
Cloning into '/home/build/lv_micropython/lib/lv_bindings'...
remote: Enumerating objects: 41, done.        
remote: Counting objects: 100% (41/41), done.        
remote: Compressing objects: 100% (31/31), done.        
remote: Total 1100 (delta 19), reused 26 (delta 10), pack-reused 1059        
Receiving objects: 100% (1100/1100), 1.14 MiB | 3.45 MiB/s, done.
Resolving deltas: 100% (649/649), done.
Cloning into '/home/build/lv_micropython/lib/lwip'...
remote: Counting objects: 53114, done.        
remote: Compressing objects: 100% (12606/12606), done.        
remote: Total 53114 (delta 40017), reused 52862 (delta 39850)        
Receiving objects: 100% (53114/53114), 10.17 MiB | 3.61 MiB/s, done.
Resolving deltas: 100% (40017/40017), done.
Cloning into '/home/build/lv_micropython/lib/mbedtls'...
remote: Enumerating objects: 11, done.        
remote: Counting objects: 100% (11/11), done.        
remote: Compressing objects: 100% (11/11), done.        
remote: Total 95218 (delta 2), reused 3 (delta 0), pack-reused 95207        
Receiving objects: 100% (95218/95218), 41.93 MiB | 3.91 MiB/s, done.
Resolving deltas: 100% (73629/73629), done.
Cloning into '/home/build/lv_micropython/lib/mynewt-nimble'...
remote: Enumerating objects: 124, done.        
remote: Counting objects: 100% (124/124), done.        
remote: Compressing objects: 100% (111/111), done.        
remote: Total 37081 (delta 70), reused 17 (delta 5), pack-reused 36957        
Receiving objects: 100% (37081/37081), 10.80 MiB | 3.56 MiB/s, done.
Resolving deltas: 100% (22269/22269), done.
Cloning into '/home/build/lv_micropython/lib/nrfx'...
remote: Enumerating objects: 1882, done.        
remote: Total 1882 (delta 0), reused 0 (delta 0), pack-reused 1882        
Receiving objects: 100% (1882/1882), 3.16 MiB | 4.00 MiB/s, done.
Resolving deltas: 100% (1478/1478), done.
Cloning into '/home/build/lv_micropython/lib/stm32lib'...
remote: Enumerating objects: 3191, done.        
remote: Total 3191 (delta 0), reused 0 (delta 0), pack-reused 3191        
Receiving objects: 100% (3191/3191), 10.42 MiB | 3.98 MiB/s, done.
Resolving deltas: 100% (2449/2449), done.
Cloning into '/home/build/lv_micropython/lib/tinyusb'...
remote: Enumerating objects: 385, done.        
remote: Counting objects: 100% (385/385), done.        
remote: Compressing objects: 100% (214/214), done.        
remote: Total 39260 (delta 208), reused 265 (delta 142), pack-reused 38875        
Receiving objects: 100% (39260/39260), 27.33 MiB | 3.91 MiB/s, done.
Resolving deltas: 100% (27312/27312), done.
Submodule path 'lib/asf4': checked out 'd270f79aa16dd8fd4ae3b6c14544283dcb992e9c'
Submodule path 'lib/axtls': checked out '43a6e6bd3bbc03dc501e16b89fba0ef042ed3ea0'
Submodule path 'lib/berkeley-db-1.xx': checked out '35aaec4418ad78628a3b935885dd189d41ce779b'
Submodule path 'lib/libffi': checked out 'e9de7e35f2339598b16cbb375f9992643ed81209'
Submodule path 'lib/lv_bindings': checked out 'edf14fde6986a3cf943d25beeb06f211e94ed32e'
Submodule 'driver/png/lodepng' (https://github.com/lvandeve/lodepng.git) registered for path 'lib/lv_bindings/driver/png/lodepng'
Submodule 'lvgl' (https://github.com/littlevgl/lvgl.git) registered for path 'lib/lv_bindings/lvgl'
Submodule 'micropython/pycparser' (https://github.com/eliben/pycparser.git) registered for path 'lib/lv_bindings/pycparser'
Cloning into '/home/build/lv_micropython/lib/lv_bindings/driver/png/lodepng'...
remote: Enumerating objects: 85, done.        
remote: Counting objects: 100% (85/85), done.        
remote: Compressing objects: 100% (58/58), done.        
remote: Total 722 (delta 50), reused 49 (delta 27), pack-reused 637        
Receiving objects: 100% (722/722), 1.04 MiB | 4.02 MiB/s, done.
Resolving deltas: 100% (479/479), done.
Cloning into '/home/build/lv_micropython/lib/lv_bindings/lvgl'...
remote: Enumerating objects: 28, done.        
remote: Counting objects: 100% (28/28), done.        
remote: Compressing objects: 100% (28/28), done.        
remote: Total 24676 (delta 8), reused 2 (delta 0), pack-reused 24648        
Receiving objects: 100% (24676/24676), 16.97 MiB | 3.96 MiB/s, done.
Resolving deltas: 100% (19701/19701), done.
Cloning into '/home/build/lv_micropython/lib/lv_bindings/pycparser'...
remote: Enumerating objects: 5, done.        
remote: Counting objects: 100% (5/5), done.        
remote: Compressing objects: 100% (5/5), done.        
remote: Total 2412 (delta 0), reused 1 (delta 0), pack-reused 2407        
Receiving objects: 100% (2412/2412), 1.07 MiB | 3.23 MiB/s, done.
Resolving deltas: 100% (1623/1623), done.
Submodule path 'lib/lv_bindings/driver/png/lodepng': checked out '2e541f53ebedf6ebae375a381ca2fd6d82b460bc'
error: Server does not allow request for unadvertised object bac66172ea89e3ed101548f893277b987afe58f5
Fetched in submodule path 'lib/lv_bindings/lvgl', but it did not contain bac66172ea89e3ed101548f893277b987afe58f5. Direct fetching of that commit failed.
Submodule path 'lib/lwip': checked out '159e31b689577dbf69cf0683bbaffbd71fa5ee10'
Submodule path 'lib/mbedtls': checked out '3f8d78411a26e833db18d9fbde0e2f0baeda87f0'
Submodule 'crypto' (https://github.com/ARMmbed/mbed-crypto) registered for path 'lib/mbedtls/crypto'
Cloning into '/home/build/lv_micropython/lib/mbedtls/crypto'...
remote: Enumerating objects: 10, done.        
remote: Counting objects: 100% (10/10), done.        
remote: Compressing objects: 100% (10/10), done.        
remote: Total 80514 (delta 3), reused 2 (delta 0), pack-reused 80504        
Receiving objects: 100% (80514/80514), 22.99 MiB | 4.06 MiB/s, done.
Resolving deltas: 100% (65106/65106), done.
Submodule path 'lib/mbedtls/crypto': checked out 'a78c958b17d75ddf63d8dd17255b6379dcbf259f'
Submodule path 'lib/mynewt-nimble': checked out '223714cb16c255cfa701929c0de6d7579bfd2cdd'
Submodule path 'lib/nrfx': checked out '7513fc9d5c10dc28b25bf2bb6ff0ba66cb2a3c3d'
Submodule path 'lib/stm32lib': checked out '668d7a9e54aea98f8fe8a858eac1d3daa80fa824'
Submodule path 'lib/tinyusb': checked out '393492823ce037a2e46d367d61fad1235859af2e'
Submodule 'hw/mcu/microchip/samd/asf4' (https://github.com/adafruit/asf4.git) registered for path 'lib/tinyusb/hw/mcu/microchip/samd/asf4'
Submodule 'hw/mcu/nordic/nrfx' (https://github.com/NordicSemiconductor/nrfx.git) registered for path 'lib/tinyusb/hw/mcu/nordic/nrfx'
Submodule 'hw/mcu/nxp/lpcopen' (https://github.com/hathach/lpcopen.git) registered for path 'lib/tinyusb/hw/mcu/nxp/lpcopen'
Submodule 'hw/mcu/st/stm32lib' (https://github.com/hathach/stm32lib.git) registered for path 'lib/tinyusb/hw/mcu/st/stm32lib'
Submodule 'tools/uf2' (https://github.com/microsoft/uf2.git) registered for path 'lib/tinyusb/tools/uf2'
Cloning into '/home/build/lv_micropython/lib/tinyusb/hw/mcu/microchip/samd/asf4'...
remote: Enumerating objects: 1520, done.        
remote: Total 1520 (delta 0), reused 0 (delta 0), pack-reused 1520        
Receiving objects: 100% (1520/1520), 1.75 MiB | 3.62 MiB/s, done.
Resolving deltas: 100% (928/928), done.
Cloning into '/home/build/lv_micropython/lib/tinyusb/hw/mcu/nordic/nrfx'...
remote: Enumerating objects: 1882, done.        
remote: Total 1882 (delta 0), reused 0 (delta 0), pack-reused 1882        
Receiving objects: 100% (1882/1882), 3.16 MiB | 4.34 MiB/s, done.
Resolving deltas: 100% (1478/1478), done.
Cloning into '/home/build/lv_micropython/lib/tinyusb/hw/mcu/nxp/lpcopen'...
remote: Enumerating objects: 1286, done.        
remote: Total 1286 (delta 0), reused 0 (delta 0), pack-reused 1286        
Receiving objects: 100% (1286/1286), 5.35 MiB | 3.84 MiB/s, done.
Resolving deltas: 100% (724/724), done.
Cloning into '/home/build/lv_micropython/lib/tinyusb/hw/mcu/st/stm32lib'...
remote: Enumerating objects: 2362, done.        
remote: Total 2362 (delta 0), reused 0 (delta 0), pack-reused 2362        
Receiving objects: 100% (2362/2362), 8.53 MiB | 3.89 MiB/s, done.
Resolving deltas: 100% (1853/1853), done.
Cloning into '/home/build/lv_micropython/lib/tinyusb/tools/uf2'...
remote: Enumerating objects: 12, done.        
remote: Counting objects: 100% (12/12), done.        
remote: Compressing objects: 100% (12/12), done.        
remote: Total 380 (delta 2), reused 9 (delta 0), pack-reused 368        
Receiving objects: 100% (380/380), 110.91 KiB | 1.44 MiB/s, done.
Resolving deltas: 100% (193/193), done.
Submodule path 'lib/tinyusb/hw/mcu/microchip/samd/asf4': checked out '82fe3aa05bc3b9f4956ee775c748a3885443f66b'
Submodule path 'lib/tinyusb/hw/mcu/nordic/nrfx': checked out '9d68726e41c321f1772c187bd12d82f5b13104f1'
Submodule path 'lib/tinyusb/hw/mcu/nxp/lpcopen': checked out '06b4c2e509147924b66ace90f6be5ebe599af45c'
Submodule path 'lib/tinyusb/hw/mcu/st/stm32lib': checked out '1dabc2df8ed1acaf0c483b58d757ba72e8b42090'
Submodule path 'lib/tinyusb/tools/uf2': checked out '19615407727073e36d81bf239c52108ba92e7660'
Submodule 'hidapi' (https://github.com/signal11/hidapi) registered for path 'lib/tinyusb/tools/uf2/hidapi'
Cloning into '/home/build/lv_micropython/lib/tinyusb/tools/uf2/hidapi'...
remote: Enumerating objects: 2006, done.        
remote: Total 2006 (delta 0), reused 0 (delta 0), pack-reused 2006        
Receiving objects: 100% (2006/2006), 2.73 MiB | 4.03 MiB/s, done.
Resolving deltas: 100% (1172/1172), done.
Submodule path 'lib/tinyusb/tools/uf2/hidapi': checked out 'a6a622ffb680c55da0de787ff93b80280498330f'
Failed to recurse into submodule path 'lib/lv_bindings'
```
The dangers of git submodules I guess. :/

**Comment by kisvegabor** [comment]
@amirgon on `dev-7.0` I got this error:
```
/lv_misc/lv_gc.c:10:
In function ‘memset’,
    inlined from ‘lv_gc_clear_roots’ at /home/kisvegabor/projects/littlevgl/eclipse-workspace/pc_simulator_sdl_eclipse/lvgl/tests/../src/lv_misc/lv_gc.c:49:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:71:10: error: ‘__builtin___memset_chk’ writing 16 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
   return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I've traced that it's because of `f(lv_mem_buf_t, _lv_mem_buf[LV_MEM_BUF_MAX_NUM])`. In `LV_CLEAR_ROOT` it's expanded to 
`memset(&_lv_mem_buf[LV_MEM_BUF_MAX_NUM], 0, sizeof(_lv_mem_buf[LV_MEM_BUF_MAX_NUM]))` which is not correct.

Should we add another list for arrays?

**Comment by amirgon** [comment]
> Should we add another list for arrays?

@kisvegabor I think this can be handled in the same list of root pointers with some preprocessor tricks.  
I'll look into it in the evening.

**Comment by amirgon** [comment]
> @kisvegabor I think this can be handled in the same list of root pointers with some preprocessor tricks.
> I'll look into it in the evening.

@kisvegabor Another option is to use typedef. Could be nicer than preprocessor tricks.
See #1333

**Comment by kisvegabor** [comment]
Merged, thank you!

**Pull request merged**
