### PR TITLE
Add ability to recolor btnm button labels

### PR DESCRIPTION
**Pull request by embeddedt**
Example use case: changing the color of a save button when there are changes that need to be saved.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Nice! 
I've just fixed some conflicts. 

This feature would be useful `lv_kb`, and `lv_mbox` too. What do you think?

**Comment by embeddedt** [comment]
@kisvegabor Implementing it for `lv_mbox` is simple since the user provides the button map. For `lv_kb` it might be harder since the map is internal. How would I handle that?

**Comment by kisvegabor** [comment]
@embeddedt 
Good point, it's not so practical in the case of `lv_kb.  Then add it only to `lv_mbox`, ok?

**Comment by embeddedt** [comment]
@kisvegabor Just added it!

**Comment by kisvegabor** [comment]
Awesome! Thank you!
I think it's ready to merge. Do you agree?

**Comment by embeddedt** [comment]
@kisvegabor Yes! Thanks for the review!

**Comment by kisvegabor** [comment]
I've just deleted the feature branch.

**Pull request merged**
