### PR TITLE
fix(group): fix get_indev issue

### PR DESCRIPTION
**Pull request by mvladic**
Currently, `get_indev` returns a first POINTER indev **regardless of the given group**. Here is the description of this function:

"Find an indev preferably with POINTER type (because it's the most generic) that **uses the given group**."

The consequence of this is that the function `lv_group_focus_obj' does not work; and the first widget in the group is not focused (LV_STATE_FOCUS_KEY) by default if ENCODER or KEYBOARD is used. Both are working correctly in version 8.4.

### CODE REVIEW

**Comment by mvladic** [comment]
Because of this bug, the functions `lv_group_focus_next` and `lv_group_focus_prev` also doesn't work. Maybe someone should check this and confirm.

**Comment by mvladic** [comment]
One test fails. But, if this test expects that FOCUS_KEY state **is not** enabled then it is obvious while it fails because now it will be enabled which is expected in my opinion.

**Comment by kisvegabor** [comment]
It makes perfect sense to use consider only the indevs if the given group. Could you update the screenshot in the test too?

**Comment by mvladic** [comment]
> Could you update the screenshot in the test too?

Done.

**Comment by mvladic** [comment]
Some remark related to this which I think are important. 

- This fix solves multiple issues. The most important is that `lv_group_focus_obj` didn't work.

- But, I believe not everybody will be happy with this change. For example, if you have both pointer and encoder inputs, maybe you don't want focus by default to the first object of the encoder group, because you consider pointer as your primary interface. 

So, only when user starts to use encoder you want to see focused object visual indicator. But, right now, without this change,  when you move encoder, for example to the RIGHT, it will not focus to the first object, but second.

Maybe, auto focus to the first object shouldn't be default. Or, it should be a way for the group to enable/disable this feature.

For the reference, here is the code that focus the first object added to the group and this can't be easily turned off:

image

**Comment by mvladic** [comment]
After further investigation I found out that in issue #4052 the [decision](https://github.com/lvgl/lvgl/issues/4052#issuecomment-1502897210) was made to not focus by default. And here is the [commit](https://github.com/lvgl/lvgl/commit/d6cc2ff76f69bb7bb3f145da70a822c7fab3670e) which made the change.

So, I think this PR should be put on hold for now.

**Comment by kisvegabor** [comment]
True. Let's close it for now.

**Pull request closed without merging**
