### PR TITLE
enhance the function of break_chars

### PR DESCRIPTION
**Pull request by guoweilkd**
### Description of the feature or fix

PR for #2324

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Review by embeddedt — COMMENTED** [review]
Maybe it's better to remove `LV_TXT_BREAK_CHARS` entirely and put the value in `str` like you did in your issue example. I find it confusing as a reader when there are two macros which appear to do the same thing.

Adding an error message to `lv_txt.h` when `LV_TXT_BREAK_CHARS` is defined is good enough, in my opinion; users are expected to update their configuration file when moving between releases.

```c
#ifdef LV_TXT_BREAK_CHARS
#error LV_TXT_BREAK_CHARS has been replaced by LV_LETTER_IS_BREAK_CHARS. Update your config file.
#endif
```

It also simplifies `_lv_txt_is_break_char`.

**Comment by kisvegabor** [comment]
I'd simply add `if ((letter >= 0x4E00 && letter <= 0x9FA5)) return true;` to `_lv_txt_is_break_char`. Altough I don't know the Chiease language but from your comment it seems it's common to break on any character. 

So is this customization really required?

The `(letter >= 0xFF00 && letter <= 0xFFFF)` range [contains arabic characters](https://www.ling.upenn.edu/courses/Spring_2003/ling538/UnicodeRanges.html) too so I think the range needs to be narrowed.
`

**Comment by guoweilkd** [comment]
Yes, it's more concise. 
users can configure punctuation in `LV_TXT_BREAK_CHARS` macro.(eg:`#define LV_TXT_BREAK_CHARS " ,.;:-_\uFF01\uFF0C\uFF1A\uFF1B"`). so, I deleted the statements( `letter >= 0xFF00 && letter <= 0xFFFF`).

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
Merged, thank you very much!

**Pull request merged**
