### PR TITLE
fix(imgbtn) imgbtn display incorrect when the coordinate is negative

### PR DESCRIPTION
**Pull request by Hotakus**
- [x] function name spelling error
- [x] fix imgbtn display incorrect when the coordinate is negative  

Snipaste_2021-08-27_18-04-48 Snipaste_2021-08-27_18-08-22

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thanks for fixing this typo.

How can I reproduce the issue shown on the image?

**Comment by Hotakus** [comment]
> Thanks for fixing this typo.
> 
> How can I reproduce the issue shown on the image?

Use the "lv_example_imgbtn_1.c", add the code👇  
```c
lv_obj_set_width(imgbtn1, 86);
lv_obj_align(imgbtn1, LV_ALIGN_LEFT_MID, -50, 0);
```
If the "X" is negative, this problem will reproduce

**Comment by Hotakus** [comment]
I think it's ok now @kisvegabor

**Comment by kisvegabor** [comment]
Looks good to me too, thanks.

**Pull request merged**
