### PR TITLE
Various fix for gc module

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

See the commit message.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Since many global variable aren't optional and removed in v8, I rebase https://github.com/lvgl/lvgl/pull/2088 from master to dev branch. Please take a look, @kisvegabor and @amirgon .

**Comment by amirgon** [comment]
@xiaoxiang781216 I can see that you [removed `LV_DISPATCH_COND`](https://github.com/lvgl/lvgl/commit/db75d316bfc43ab4e02e7a314b7f5a35a26f5441) and returned `cache_temp`. 

I liked your idea of conditioning gc-roots and removing unnecessary ones according to compile-time configuration.
Don't you see enough value in it?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 I can see that you [removed `LV_DISPATCH_COND`](https://github.com/lvgl/lvgl/commit/db75d316bfc43ab4e02e7a314b7f5a35a26f5441) and returned `cache_temp`.
> 
> I liked your idea of conditioning gc-roots and removing unnecessary ones according to compile-time configuration.
> Don't you see enough value in it?

> @xiaoxiang781216 I can see that you [removed `LV_DISPATCH_COND`](https://github.com/lvgl/lvgl/commit/db75d316bfc43ab4e02e7a314b7f5a35a26f5441) and returned `cache_temp`.
> 
> I liked your idea of conditioning gc-roots and removing unnecessary ones according to compile-time configuration.
> Don't you see enough value in it?

Yes, the idea is good, but it doesn't need with v8, because:

1. Many variables aren't optional now(e.g. _lv_drv_ll, _lv_anim_ll, _lv_group_ll, _lv_img_cache_array)
2. Many variables aren't used anymore(e.g. _lv_file_ll, _lv_theme_material_styles, _lv_theme_template_styles, _lv_theme_mono_styles, _lv_theme_empty_styles)

Only two variables() are still optional:

1. _lv_font_decompr_buf is guarded by LV_USE_FONT_COMPRESSED
2. _lv_draw_mask_list is guarded by LV_DRAW_COMPLEX

Do you still want to apply macro trick to these two variables?

**Comment by amirgon** [comment]
> Do you still want to apply macro trick to these two variables?

**Pro**:  Saves some RAM by compiling in only needed gc-roots, either for existing gc-roots or future gc-roots that would be added.
**Con**: C macro trick may be a little confusing for people not familiar with it.

I like it but I don't think it's a must. Let's hear other's opinion:

@kisvegabor @embeddedt  - How do you vote? Would you like to see [LV_DISPATCH_COND](https://github.com/lvgl/lvgl/commit/db75d316bfc43ab4e02e7a314b7f5a35a26f5441)  integrated?

**Comment by embeddedt** [comment]
I vote to keep `LV_DISPATCH_COND` even though the savings are minimal at the moment. There's a high chance it will be useful in the future.

**Comment by xiaoxiang781216** [comment]
Ok, I bring back the conditional dispatch, please take a look.

**Comment by amirgon** [comment]
https://github.com/lvgl/lvgl/blob/4c5b23d5ae29c04e0e185b4746f1ee2afe9082d7/src/lv_draw/lv_img_cache.c#L127-L128

@xiaoxiang781216 Now with conditional dispatch back, can we again remove `cache_temp` and use a conditional gc root directly?

**Comment by xiaoxiang781216** [comment]
> https://github.com/lvgl/lvgl/blob/4c5b23d5ae29c04e0e185b4746f1ee2afe9082d7/src/lv_draw/lv_img_cache.c#L127-L128
> 
> @xiaoxiang781216 Now with conditional dispatch back, can we again remove `cache_temp` and use a conditional gc root directly?

Yes, we can. But, I think the current approach is more simpler and cleaner.

**Comment by amirgon** [comment]
> Yes, we can. But, I think the current approach is more simpler and cleaner.

We are comparing this:

```c
#if LV_IMG_CACHE_DEF_SIZE == 0
    static lv_img_cache_entry_t cache_temp;
#endif
...
#else
    cached_src = &cache_temp;
    LV_GC_ROOT(_lv_img_cache_array) = cached_src;
#endif
```

to this:
```c
#else
    cached_src = &LV_GC_ROOT(_lv_img_cache_entry);
#endif
```
Where `_lv_img_cache_entry` is a new LV_DISPATCH_COND in place of `_lv_img_cache_array`.  

The pros of removing `cache_temp` are:
- Removing a static variable
- Removing an assignment to that variable

@xiaoxiang781216 What are the cons? Could you explain how this approach is less clean and less simple than keeping `cache_temp`? What am I missing here?

**Comment by xiaoxiang781216** [comment]
Done, @amirgon

**Comment by kisvegabor** [comment]
Merged, thank you!

**Pull request merged**
