### PR TITLE
Dev 5.3 Micropython bindings

### PR DESCRIPTION
**Pull request by amirgon**

### CODE REVIEW

**Comment by embeddedt** [comment]
@kisvegabor Looks like a squash merge would be best here. Otherwise there are going to be a lot of commits in the history.

**Comment by amirgon** [comment]
@embeddedt squash merge loses history.  
I tried to explain in every commit message **what** I did and **why** I did it. This is especially important for bug fixes (and there are quite a few there), where I explained what was the bug and how it was fixed. It's also important to see the commit as a whole including all the files affected.  

Why is it important to you to "save" a few commits? Are you willing to lose valuable history for that?  
It's worth noting that most of my commits are to my Micropython Binding code and not to lvgl sources, so looking at history of specific lvgl sources will not show as many commits.

**Review by amirgon — COMMENTED** [review]
@kisvegabor you would need to fix the makefile on lv_mpy project if you move Micropython files.

**Comment by kisvegabor** [comment]
@amirgon Thank you very much! Ok, I'll fix makefiles  we merge it.

However I can compile it:
```
lvgl/lv_bindings/lv_mpy/pycparser/utils/internal/constptr.c:3:10: error: assignment of read-only location ‘*arg’
```

Seems reasonable because this the content of the file:
```c
void foo(char * const * arg) {
  arg += 1;
  (*arg) += 1;
}

void foo2(char ** const arg) {
  arg += 1;
  (*arg) += 1;
}
```

Have I missed something when moved the project?

Regarding the commit history, I agree with @amirgon. The commit messages are clear. I like to see the curve of the development.

**Comment by amirgon** [comment]
> Have I missed something when moved the project?

@kisvegabor I'm not sure. I've noticed you updated pycparser version. Could this be related?
Last night before I sent the PR I tested it on my [lv_mpy fork](https://github.com/amirgon/lv_mpy). You could try cloning it again, see if it's working for you and what's the difference between it and your fork.

**Comment by amirgon** [comment]
@kisvegabor I actually never tried to compile pycparser examples. On Micropython you have to specify explicitly the .c files you want to compile, so I don't see why someone would "accidentally" compile pycparser.  
Could you explain why not keep it where it is and just avoid compiling it? All we need is to allow `gen_mpy.py` import it.

**Comment by kisvegabor** [comment]
If you just use lvgl (not to generate mpy bindings but to develop a GUI) the source of pycparser will be in lvgl.
Let's say you develop your GUI in Eclipse, it will automatically generate the makefile for all C files in the project (including pycparser). Which means it will try to comply pycparser too with lvgl.

**Comment by amirgon** [comment]
> Let's say you develop your GUI in Eclipse, it will automatically generate the makefile for all C files in the project (including pycparser)

@kisvegabor Then we also have a problem with `lv_mpy_example.c`. It's not supposed to be compiled and may fail compilation if `lv_conf.h` is different than what it was when `lv_mpy_example.c` was generated.  

Are you sure this is the default behavior in Eclipse - build whatever .c file it finds in whatever subdirectory?  
This sounds strange. There could be multiple reasons **not** to compile all .c files. Some of them may only be tests or examples, some of them may not be useful for the platform you are building for etc. Building all whatever .c files you can find doesn't sounds like a very robust approach.

**Comment by kisvegabor** [comment]
@amirgon I'm sure that this is the default behavior not only in Eclipse but in the majority of the IDEs. I work this way all the time. Just create a C file, write something in it and build. You can exclude some folders somehow from the build but that is different every IDE and needs extra steps.

@embeddedt Can you confirm it?

**Comment by kisvegabor** [comment]
@amirgon 
> Not in MSVC. There you have to explicitly add a file to a "project" in order for it to compile, which is in my opinion a more sane approach than compiling any file on the disk.

In Eclipse-based IDEs, you can press F5 to refresh the files from the file system. The other solution is to add links to the folders (or maybe for files) one by one but is hidden deeply in the project properties.  

>  Move the entire lv_bindings to a new repo with lvgl sub module. 

So it would be a new repo for all the bindings? I don't expect that we will have more than 5 bindings in the long term (Mpy, Python, Lua?, Rust?) so it's still reasonable to keep them in one place.

I created the repo here: https://github.com/littlevgl/lv_bindings

**Comment by amirgon** [comment]
> So it would be a new repo for all the bindings? I don't expect that we will have more than 5 bindings in the long term (Mpy, Python, Lua?, Rust?) so it's still reasonable to keep them in one place.

@kisvegabor We can start with one repo. You can always split it in the future. Having at least Python and Micropython in the same repo makes sense, not sure what other bindings are on the way. Anyone started working on some other bindings?

> I created the repo here: https://github.com/littlevgl/lv_bindings

Ok. You are going to move all the commit history as well, right?

**Comment by kisvegabor** [comment]
> @kisvegabor We can start with one repo. You can always split it in the future. Having at least Python and Micropython in the same repo makes sense, not sure what other bindings are on the way. 

Ok, I agree.

> Anyone started working on some other bindings?

I don't know, but I found the Python binding accidentally too. So who knows :)

> Ok. You are going to move all the commit history as well, right?

My view is to completely remove the `lv_binding` folder and move its content to the new repo. In the `lvgl` repo it will mean only a new commit on top of these above with "move lv_bindings to a separate repo". I don't know how to "split" the history to lvgl related and mpy related parts.

**Comment by amirgon** [comment]
> My view is to completely remove the `lv_binding` folder and move its content to the new repo. In the `lvgl` repo it will mean only a new commit on top of these above with "move lv_bindings to a separate repo". I don't know how to "split" the history to lvgl related and mpy related parts.

@kisvegabor I think it's important **to keep the commit history**, for the reasons I mentioned above as a response to @embeddedt.  
A quick google search returned [this](https://stosb.com/blog/retaining-history-when-moving-files-across-repositories-in-git/), for example, for how to do it.

**Comment by kisvegabor** [comment]
@amirgon 
Wow, nice! It'd be a great solution. Will you try it?

**Comment by amirgon** [comment]
@kisvegabor Ok, I'll give it a try.

**Comment by embeddedt** [comment]
@kisvegabor Yes, it's default behavior to compile everything found in the sub directory. You can exclude files though.

@amirgon When squash merging we can retain the history inside the one commit message. We would lose access to individual changes though. I think @kisvegabor should decide, it's his project.

**Comment by kisvegabor** [comment]
I vote for leaving the history. 

The main reason is to show the volume of the work. For example, I often add commits like these: 
- `lv_canvas: fix typo`
- `lv_canvas: resolve warnings`
- `lv_canvas: minor updates`

These 3 commits might change only 5 lines of code. It wouldn't be fair to have only one commit for a huge update like this.

**Comment by embeddedt** [comment]
@kisvegabor That's true. Let's do it that way then.

**Comment by amirgon** [comment]
Splitting the repos caused git history rewrite.
I'm going to try to rebase my changes.

**Comment by kisvegabor** [comment]
It seems good to me now. lvgl is compiling in Eclipse too and the history seems good as well.

**Comment by amirgon** [comment]
@kisvegabor Could you `git pull` my [`lv_bindings/dev5.3`](https://github.com/amirgon/lv_bindings/tree/dev-5.3)  ? I can't send you a pull request since GitHub complains that "littlevgl:master and amirgon:dev-5.3 are entirely different commit histories."

**Comment by kisvegabor** [comment]
@amirgon Done.
The history is fine too: https://github.com/littlevgl/lv_bindings/commits/master/micropython/gen_mpy.py

**Comment by amirgon** [comment]
@kisvegabor Nice.
Now you can update the lv_binding module on [lv_mpy PR](https://github.com/kisvegabor/lv_mpy/pull/2). lv_mpy should work now with lb_binding, I fixed the Makefile there.

**Comment by kisvegabor** [comment]
Merged!

**Comment by kisvegabor** [comment]
> I think that at some point you would want to change the submodules to point at your fork and not at my fork. (this and this)

Yes. I merged the `lvgl` updates to `dev-5.3`.
I'm planning to move [lv_mpy](https://github.com/kisvegabor/lv_mpy) to `littlevgl` and change the submodules.
Is it okay for you if I move it now?

**Comment by amirgon** [comment]
> Is it okay for you if I move it now?

@kisvegabor Sure, just please make sure you move it with all the history.

**Comment by kisvegabor** [comment]
GitHub has a `move` feature, I hope it works well.

**Comment by kisvegabor** [comment]
Seems good: https://github.com/littlevgl/lv_mpy/commits/master

**Pull request merged**
