### PR TITLE
Repair infinite loop in label refresh.

### PR DESCRIPTION
**Pull request by iDalink**
When find back `dot` character postion, move `byte_id` to previous character index, not subtract current character length. 

Thus, it will broken `byte_id` ,  makes it point to UTF8 sequence middle, so it will stuck at `_lv_txt_encoded_size`.

The following condition is used to reappear the issue.
1、`_lv_txt_encoded_size` founded index for `dot` named 'index'.
2、It need additional character to store 'dot' character.
3、The character behind 'index' is short than character length before `index`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you!
Could you add a line about the fix in `CHANGELOG.md`?

**Comment by iDalink** [comment]
> Thank you!
> Could you add a line about the fix in `CHANGELOG.md`?

Sure. Should I submit another merge request for CHANGELOG.md ?

**Comment by kisvegabor** [comment]
It's fine if you push a commit here.

**Comment by iDalink** [comment]
A new commit was pushed ,  contains two modifications.

**Comment by iDalink** [comment]
> It's fine if you push a commit here.

A new commit was pushed , contains two modifications.

**Comment by kisvegabor** [comment]
Thank you!

**Pull request merged**
