### PR TITLE
feat(spangroup): add span position getting behaviour for spangroup

### PR DESCRIPTION
**Pull request by W-Mai**
### Description of the feature or fix

Get the span's coords in the spangroup.
Before calling this function, please make sure that the layout of span group has been updated.

```plaintext
+--------+
|Heading +--->------------------+
|  Pos   |   |     Heading      |
+--------+---+------------------+
|                               |
|                               |
|                               |
|            Middle   +--------+|
|                     |Trailing||
|                   +-|  Pos   ||
|                   | +--------+|
+-------------------v-----------+
|     Trailing      |
+-------------------+
```

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
What is the use case for having this functions?

**Comment by W-Mai** [comment]
When span has the ability to obtain coordinates, it can add events to span and realize the hyperlink ability in spangroup.

I'm doing this.

**Comment by W-Mai** [comment]
cc @FASTSHIFT @XuNeo

**Comment by kisvegabor** [comment]
I don't get it. :slightly_frowning_face: What is the "hyperlink ability"?

**Comment by liamHowatt** [comment]
If I understand correctly, W-Mai's example use case is to compare the coords of a click with the coords of a span and react accordingly. A span could be a hyperlink and clicking it could be detected using this new feature.

**Comment by kisvegabor** [comment]
Got it! But shouldn't it be a more generic feature? Similar to getting the [clicked table cell](https://github.com/lvgl/lvgl/blob/master/src/widgets/table/lv_table.h#L219)? We could have a `lv_span_t * lv_spangroup_get_span_from_point(spangroup, &p)`. 

What do you think?

**Comment by W-Mai** [comment]
- #5679 

I think to do this in this way, you can jump by subscribing to the event, which is more elegant. 😁

**Comment by kisvegabor** [comment]
Closing in favor of https://github.com/lvgl/lvgl/pull/6579

**Pull request closed without merging**
