### PR TITLE
add some useful function in the list

### PR DESCRIPTION
**Pull request by fallstool**
Hi，add some funcitons , when user click the list, they can know the index of the list and can remove it form list.
```c
bool lv_list_remove(const lv_obj_t * list, uint32_t index);
int32_t lv_list_get_btn_index(const lv_obj_t * list, const lv_obj_t * btn);
uint32_t lv_list_get_size(const lv_obj_t * list);
```
example:
```c
static lv_res_t list_clicked(lv_obj_t * btn)
{
  int size = lv_list_get_size(list1);
  int index = lv_list_get_btn_index(list1, btn);
  lv_list_remove(list1, index);
  size = lv_list_get_size(list1);
  return LV_RES_OK;
}
```

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Looks great and it worked for me!

@turoksama What was not working?

@fallstool 
1. You can use ` ```c` `code` ` ``` ` to add syntax highlight for a block of code. I added it in your comment
2. You should return `LV_RES_INV` because the button is deleted in `list_clicked`
3. You don't have to create a new Pull request if you add updates. Just push your changes and they will appear in the PR.
4. Great work, thank you! :)

**Comment by fallstool** [comment]
Hi:
@kisvegabor OK,  thank you, I am freshman with the github.

**Comment by turoksama** [comment]
Hi,
Well, it works while in its own click-action, i think it looks like: when we touch/select an element in the list, it will be then deleted.
But, when i use another standalone button "Delete" to delete an element from a list with toggle-enabled, and it won't work:
```
lv_btn_set_toggle(list_btn, true);
```
and codes in action function of the "Delete" button look like this:
```
lv_obj_t bs=lv_list_get_btn_selected(list);
int32_t idx = lv_list_get_btn_index(list, bs);
bool sc = lv_list_remove(list, idx);
```
it looks logical to achieve that goal, but it's not.
When i trace down into it, lv_list_get_btn_selected doesn't return that selected button as it is, and idx returns -1, failed. It means that lv_list_get_btn_selected can't find the selected button.
So i have to share a global variable to get that selected button object in list callback by using:
```
bs = lv_obj_get_parent(lv_list_get_btn_label(list));
```
Well, it works then.
I appreciate for your code very much, hooray.
Thanks!

**Comment by kisvegabor** [comment]
@turoksama `lv_list_get_btn_selected` can be used if the list is added to a `group` and you are navigating in it with buttons. I updated the comment of this function to make it clearer.  

@fallstool No worries :)
I've just** merged the updates into the `dev-5.3` branch**. After I pushed the merged version, GitHub didn't allow me to change the PR's destination branch to `dev-5.3` therefore the PR seems not merged. (It's really not merged to master but merged to `dev-5.3`) Sorry, for that.
And thank you for the improvement! :)

**Pull request closed without merging**
