### PR TITLE
fix(arc): arc pressing bounds detection

### LINKED ISSUE #5870: reverse mode for lv_arc
### LVGL version

V8.3.11

### What happened?

Touch handling in reverse arc mode does not seem to work correctly.

Setting any value through code is okay, but when touching it shows odd behaviour.

Video taken from SLS, but behaviour is same on real display.

https://github.com/lvgl/lvgl/assets/148654555/fd0a70cd-0d05-4d4b-a916-04a314f3a125

 

### How to reproduce?

just use arc in reverse mode and touch

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

Fixes #5870

### 1

Fix an issue where the start and end angle of the arc are not processed correctly if the start angle is smaller than the end angle (and the end angle was <=360 when it was set with the setter).

This is the whole fix
```diff
diff --git a/src/widgets/arc/lv_arc.c b/src/widgets/arc/lv_arc.c
index 6d4383971..aa9349a56 100644
--- a/src/widgets/arc/lv_arc.c
+++ b/src/widgets/arc/lv_arc.c
@@ -937,12 +937,12 @@ static bool lv_arc_angle_within_bg_bounds(lv_obj_t * obj, const lv_value_precise
     lv_value_precise_t smaller_angle = 0;
     lv_value_precise_t bigger_angle = 0;
 
     /* Determine which background angle is smaller and bigger */
     if(arc->bg_angle_start < arc->bg_angle_end) {
-        bigger_angle = arc->bg_angle_end;
-        smaller_angle = arc->bg_angle_start;
+        bigger_angle = arc->bg_angle_end - arc->bg_angle_start;
+        smaller_angle = 0;
     }
     else {
         bigger_angle = (360 - arc->bg_angle_start) + arc->bg_angle_end;
         smaller_angle = 0;
     }
```

It works because the `angle` parameter in that function is relative to `arc->bg_angle_start`. The `else` branch already did the correct thing. I think the `else` was casually fixed by 84c8cf8

### 2

I simplified the rest of the function given that `smaller_angle` is always 0 and all the parameters are non-negative.

@C47D if you can catch anything I oversimplified please comment.

### 3

I fixed the "big jump prevention logic" which seemed to be misbehaving in master.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by C47D** [comment]
Hi @liamHowatt , thanks for taking care of this while I was away.

It's also good to remove complex logic, all looks good to me.

**Review by C47D — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
Fantastic, thank you Liam!

**Review by W-Mai — APPROVED** [review]

**Comment by W-Mai** [comment]
iShot_2024-05-08_14 19 16

I think there may still be some minor problems here. In this case, it will be expected that the knob will get stuck at the boundary instead of going back.

```cpp
void lv_example_arc_1(void)
{
    lv_obj_t * label = lv_label_create(lv_screen_active());

    /*Create an Arc*/
    lv_obj_t * arc = lv_arc_create(lv_screen_active());
    lv_obj_set_size(arc, 150, 150);
    lv_arc_set_rotation(arc, 135);
    lv_arc_set_bg_angles(arc, 0, 359);
    lv_arc_set_value(arc, 10);
    lv_obj_center(arc);
    lv_obj_add_event_cb(arc, value_changed_event_cb, LV_EVENT_VALUE_CHANGED, label);

    /*Manually update the label for the first time*/
    lv_obj_send_event(arc, LV_EVENT_VALUE_CHANGED, NULL);
}
```

**Review by FASTSHIFT — APPROVED** [review]

**Comment by liamHowatt** [comment]
Thanks for trying it @W-Mai! Yup! I was able to fix the problem you found but not without affecting other good behavior. Let me see.

No one merge this yet.

**Comment by kisvegabor** [comment]
> No one merge this yet.

Ups, please open a new PR if you find a good solution. :sweat_smile:

**Pull request merged**
