### PR TITLE
feat(hal): add refr_finish_cb to the display driver

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

Related discussion: https://github.com/lvgl/lvgl/issues/3457 https://github.com/lvgl/lvgl/pull/3461

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
Execute action after refresh finish event:
```c
static lv_ll_t refr_async_ll;

typedef struct {
    lv_async_cb_t cb;
    void* user_data;
} refr_async_info_t;

static void on_refr_finish(lv_disp_drv_t* disp_drv)
{
    if (_lv_ll_is_empty(&refr_async_ll)) {
        return;
    }

    refr_async_info_t* info;
    _LV_LL_READ(&refr_async_ll, info)
    {
        info->cb(info->user_data);
    }
    _lv_ll_clear(&refr_async_ll);
}

static void refr_async_init(void)
{
    lv_disp_t* disp = lv_disp_get_default();
    if (!disp) {
        return;
    }

    disp->driver->refr_finish_cb = on_refr_finish;

    _lv_ll_init(&refr_async_ll, sizeof(refr_async_info_t));
}

static void refr_async_call(lv_async_cb_t async_xcb, void* user_data)
{
    refr_async_info_t* info = _lv_ll_ins_tail(&refr_async_ll);
    info->cb = async_xcb;
    info->user_data = user_data;
}

static void on_anim_async_ready(void* user_data)
{
    /* Do some time-consuming operations, such as loading resources */
    usleep(500 * 1000);
    LV_LOG_USER("OK");
}

static void on_anim_ready(lv_anim_t* a)
{
    LV_LOG_USER("a = %p", a);
    refr_async_call(on_anim_async_ready, NULL);
}

void anim_test(void)
{
    refr_async_init();
    lv_obj_clear_flag(lv_scr_act(), LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t* ui_root = lv_obj_create(lv_scr_act());
    lv_obj_set_size(ui_root, LV_HOR_RES, LV_VER_RES);
    lv_obj_set_style_bg_color(ui_root, lv_palette_main(LV_PALETTE_BLUE), 0);

    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, ui_root);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_values(&a, LV_VER_RES, 0);
    lv_anim_set_time(&a, 1000);
    lv_anim_set_delay(&a, 2000);
    lv_anim_set_ready_cb(&a, on_anim_ready);
    lv_anim_start(&a);
}
```

**Comment by kisvegabor** [comment]
I think we should go for the `drv->event_cb()` implementation.

**Comment by FASTSHIFT** [comment]
> I think we should go for the `drv->event_cb()` implementation.

Is this `drv->event_cb()` method more suitable for v9? For v8.x version, it is best to ensure that the driver interface is consistent

**Comment by kisvegabor** [comment]
But we are already working v9 and there won't be new v8 minor versions (only bugfixes).

**Comment by FASTSHIFT** [comment]
> But we are already working v9 and there won't be new v8 minor versions (only bugfixes).

OK

**Pull request closed without merging**
