### PR TITLE
feat(style): add skew style

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

skew style description: https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/skew.

The implementation of skew style effect relies on PR: https://github.com/lvgl/lvgl/pull/4883

Just pass the skew parameter into the layer matrix:
```c
int32_t skew_x = lv_obj_get_style_transform_skew_x(obj, 0);
int32_t skew_y = lv_obj_get_style_transform_skew_y(obj, 0);
lv_matrix_skew(&layer->matrix, skew_x * 0.1f, skew_y * 0.1f);
```

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [x] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [x] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [x] Use typed pointers instead of `void *` pointers
- [x] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [x] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [x] Widget members function must start with `lv_<module_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [x] `struct`s should be used via an API and not modified directly via their elements.
- [x] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [x] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [x] Arguments must be named in H files too.
- [x] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
Can we add the `lv_value_precise_t` member to `lv_style_value_t`?
```c
typedef union {
    int32_t num;         /**< Number integer number (opacity, enums, booleans or "normal" numbers)*/
    lv_value_precise_t num_precise;
    const void * ptr;    /**< Constant pointers  (font, cone text, etc)*/
    lv_color_t color;    /**< Colors*/
} lv_style_value_t;

```
This can completely solve the problem of loss of precision in style transmission.

**Comment by kisvegabor** [comment]
> Can we add the lv_value_precise_t member to lv_style_value_t?

Absolutely!

**Comment by FASTSHIFT** [comment]
@kisvegabor

**Comment by FASTSHIFT** [comment]
@kisvegabor 
The additional skew style porp (maximum ID 128 -> 130) will cause the shift in the following code to exceed 32 bits.
```c
void lv_obj_set_local_style_prop(lv_obj_t * obj, lv_style_prop_t prop, lv_style_value_t value,
                                 lv_style_selector_t selector)
{
    lv_style_t * style = get_local_style(obj, selector);
    if(selector == LV_PART_MAIN && lv_style_prop_has_flag(prop, LV_STYLE_PROP_FLAG_TRANSFORM)) {
        lv_obj_invalidate(obj);
    }

    lv_style_set_prop(style, prop, value);

#if LV_OBJ_STYLE_CACHE
    if(lv_obj_style_get_selector_part(selector) == LV_PART_MAIN) {
        obj->style_main_prop_is_set |= (uint32_t)1 << (prop >> 2);
    }
    else {
        obj->style_other_prop_is_set |= (uint32_t)1 << (prop >> 2);
    }
#endif

    lv_obj_refresh_style(obj, selector, prop);
}
```
CI Report:
```bash
home/runner/work/lvgl/lvgl/src/core/lv_obj_style.c:470:52: runtime error: shift exponent 32 is too large for 32-bit type 'unsigned int'
  /home/runner/work/lvgl/lvgl/src/core/lv_obj_style.c:397:47: runtime error: shift exponent 32 is too large for 32-bit type 'unsigned int'
  =================================================================
  ==30976==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0188b1b8 at pc 0x001dbe88 bp 0x40fff04c sp 0x40fff03c
  WRITE of size 4 at 0x0188b1b8 thread T0
      #0 0x1dbe84 in grid_align /home/runner/work/lvgl/lvgl/src/layouts/grid/lv_grid.c:639
      #1 0x1d0d60 in calc /home/runner/work/lvgl/lvgl/src/layouts/grid/lv_grid.c:247
      #2 0x1cf3e4 in grid_update /home/runner/work/lvgl/lvgl/src/layouts/grid/lv_grid.c:187
      #3 0x1dda6c in _lv_layout_apply /home/runner/work/lvgl/lvgl/src/layouts/lv_layout.c:73
      #4 0x973d8 in layout_update_core /home/runner/work/lvgl/lvgl/src/core/lv_obj_pos.c:1107
      #5 0x970f4 in layout_update_core /home/runner/work/lvgl/lvgl/src/core/lv_obj_pos.c:1098
      #6 0x970f4 in layout_update_core /home/runner/work/lvgl/lvgl/src/core/lv_obj_pos.c:1098
      #7 0x970f4 in layout_update_core /home/runner/work/lvgl/lvgl/src/core/lv_obj_pos.c:1098
      #8 0x970f4 in layout_update_core /home/runner/work/lvgl/lvgl/src/core/lv_obj_pos.c:1098
      #9 0x970f4 in layout_update_core /home/runner/work/lvgl/lvgl/src/core/lv_obj_pos.c:1098
      #10 0x8571c in lv_obj_update_layout /home/runner/work/lvgl/lvgl/src/core/lv_obj_pos.c:302
      #11 0x35b00c in lv_chart_get_first_point_center_offset /home/runner/work/lvgl/lvgl/src/widgets/chart/lv_chart.c:594
      #12 0x29060 in analytics_create /home/runner/work/lvgl/lvgl/demos/widgets/lv_demo_widgets.c:652
      #13 0x240ac in lv_demo_widgets /home/runner/work/lvgl/lvgl/demos/widgets/lv_demo_widgets.c:213
      #14 0x13940 in test_demo_widgets /home/runner/work/lvgl/lvgl/tests/src/test_cases/test_demo_widgets.c:13
      #15 0x1411c in run_test /home/runner/work/lvgl/lvgl/tests/build_test_defheap/test_demo_widgets_Runner.c:78
      #16 0x14374 in main /home/runner/work/lvgl/lvgl/tests/build_test_defheap/test_demo_widgets_Runner.c:95
      #17 0x3f1a373c in __libc_start_main (/lib/arm-linux-gnueabihf/libc.so.6+0x1773c)
  
  0x0188b1b8 is located 0 bytes to the right of global variable 'lv_global' defined in '/home/runner/work/lvgl/lvgl/src/lv_init.c:57:17' (0x188af20) of size 664
  0x0188b1b8 is located 40 bytes to the left of global variable '__gcov0.lv_deinit' defined in '<built-in>' (0x188b1e0) of size 240
  SUMMARY: AddressSanitizer: global-buffer-overflow /home/runner/work/lvgl/lvgl/src/layouts/grid/lv_grid.c:639 in grid_align
  Shadow bytes around the buggy address:
    0x203115e0: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
    0x203115f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x20311600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x20311610: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x20311620: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  =>0x20311630: 00 00 00 00 00 00 00[f9]f9 f9 f9 f9 00 00 00 00
    0x20311640: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x20311650: 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9
    0x20311660: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x20311670: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    0x20311680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  Shadow byte legend (one shadow byte represents 8 application bytes):
    Addressable:           00
    Partially addressable: 01 02 03 04 05 06 07 
    Heap left redzone:       fa
    Freed heap region:       fd
    Stack left redzone:      f1
    Stack mid redzone:       f2
    Stack right redzone:     f3
    Stack after return:      f5
    Stack use after scope:   f8
    Global redzone:          f9
    Global init order:       f6
    Poisoned by user:        f7
    Container overflow:      fc
    Array cookie:            ac
    Intra object redzone:    bb
    ASan internal:           fe
    Left alloca redzone:     ca
    Right alloca redzone:    cb
    Shadow gap:              cc
  ==30976==ABORTING
```

**Comment by kisvegabor** [comment]
Now each 4 property has a bit so we can have 4 props x 32 bit = 128 properties. We are really running out of style properties so I suggest updating to 8 props x 32 bit = 256 properties.

**Comment by FASTSHIFT** [comment]
> Now each 4 property has a bit so we can have 4 props x 32 bit = 128 properties. We are really running out of style properties so I suggest updating to 8 props x 32 bit = 256 properties.

Do you mean to calculate it this way?
`#define STYLE_PROP_SHIFTED(prop) ((uint32_t)1 << ((prop) >> 3))`

**Comment by kisvegabor** [comment]
Exactly! After that all 256 properties will be covered.

**Comment by kisvegabor** [comment]
I think this is the first configuration which is not supported by the SW render. Please add to its [evaluate_cb](https://github.com/lvgl/lvgl/blob/master/src/draw/sw/lv_draw_sw.c#L204)  to not take the draw task if skew is used.

**Comment by FASTSHIFT** [comment]
> I think this is the first configuration which is not supported by the SW render. Please add to its [evaluate_cb](https://github.com/lvgl/lvgl/blob/master/src/draw/sw/lv_draw_sw.c#L204) to not take the draw task if skew is used.

It seems that the skew parameter cannot be obtained in `evaluate_cb`. I suggest following the original process (invalid redrawing does not matter). We can implement the skew effect in software rendering later.

**Comment by kisvegabor** [comment]
I mean something like
```c

    if(task->type == LV_DRAW_TASK_TYPE_IMAGE) {
        lv_draw_image_dsc_t * draw_dsc = task->draw_dsc;
        if(draw_dsc->skew_x != 0) return 0;
    }
```

**Comment by FASTSHIFT** [comment]
> I mean something like
> 
> ```c
>     if(task->type == LV_DRAW_TASK_TYPE_IMAGE) {
>         lv_draw_image_dsc_t * draw_dsc = task->draw_dsc;
>         if(draw_dsc->skew_x != 0) return 0;
>     }
> ```

Got it, done.

**Pull request merged**
