### PR TITLE
Porting @AloyseTech's color picker from lvgl v5 to v6

### PR DESCRIPTION
**Pull request by paulpv**
Currently I can compile and run the code in an Arduino test project, but I see no UI.
(My project can show "Hello LittlevGL" text, so the setup seems fine).
I am new to lvgl so don't yet know how to use a desktop simulator, but I have been programming for 30 years and I should be able to figure it out as needed.
```
void setup() {
  Serial.begin(115200);
  Serial.println("setup: littlevgl cpicker test");

  //...

  lv_init();

  lv_disp_buf_init(&disp_buf, buf_1, buf_2, LV_HOR_RES_MAX * 10);
  
  lv_disp_drv_t disp_drv;
  lv_disp_drv_init(&disp_drv);  
  disp_drv.hor_res = displayWidth;
  disp_drv.ver_res = displayHeight;
  disp_drv.flush_cb = my_disp_flush;
  disp_drv.buffer = &disp_buf;
  lv_disp_drv_register(&disp_drv);

  lv_indev_drv_t indev_drv;
  lv_indev_drv_init(&indev_drv);
  indev_drv.type = LV_INDEV_TYPE_POINTER;
  indev_drv.read_cb = my_input_read;
  lv_indev_drv_register(&indev_drv);
  
  tick.attach_ms(LVGL_TICK_PERIOD, lv_tick_handler);

  //lv_obj_t *label = lv_label_create(lv_scr_act(), NULL);
  //lv_label_set_text(label, "Hello LittlevGL v6.x");
  //lv_obj_align(label, NULL, LV_ALIGN_CENTER, 0, 0);

  lv_obj_t *colorPicker = lv_cpicker_create(lv_scr_act(), NULL);
  lv_obj_align(colorPicker, NULL, LV_ALIGN_CENTER, 0, 0);
}

void loop() {
  //...
  lv_task_handler();
  delay(5);
  //...
}
```

### CODE REVIEW

**Comment by paulpv** [comment]
I won't mark this as Ready For Review until I can at least get it working.
I may need some help/advice on how to best test the code.
I have forked lv_examples and am attempting to add a lv_test_cpicker, but am stumbling getting it to run in Arduino (which I don't expect the tests are designed for).
Currently I am just creating the objx directly and attempting to show and poke it and get a reaction.

**Comment by paulpv** [comment]
Including @AloyseTech if he wants to chime in.

**Comment by embeddedt** [comment]
As far as I recall, it was a bit picky about how you initialized it. Maybe try something like this (from #565):

```c
    const uint32_t pickerSize = 200;
    lv_obj_t * scr = lv_scr_act();

    static lv_style_t style;
    lv_style_copy(&style, &lv_style_plain);
    style.line.color = lv_color_hsv_to_rgb(0, 100, 100);
    style.line.width = pickerSize/5;
    style.body.padding.inner = 8;

    static lv_style_t indicStyle;
    lv_style_copy(&indicStyle, &lv_style_plain);
    indicStyle.body.main_color = LV_COLOR_WHITE;
    indicStyle.body.grad_color = indicStyle.body.main_color;
    indicStyle.body.opa = LV_OPA_80;

    lv_obj_t * picker = lv_cpicker_create(scr, NULL);
    lv_cpicker_set_style(picker, LV_CPICKER_STYLE_MAIN, &style);
    lv_cpicker_set_style(picker, LV_CPICKER_STYLE_IND, &indicStyle);
    lv_obj_set_size(picker, pickerSize, pickerSize);
    lv_obj_align(picker, NULL, LV_ALIGN_CENTER, 0, 0);
    lv_scr_load(scr);
```

**Comment by paulpv** [comment]
FYI, I'm just doin this on the side (who isn't?), so I'll get to this when I get to this; no rush (other than when I actually get the time to work on it! :))

**Comment by paulpv** [comment]
Coded creation per your suggestion from original PR.
Still not showing anything.

I think where I am confused now is w/ that the v5 code seems to be based off of `lv_objx_template`, but I **think** `lv_objx_templ` seems to be obsolete in v6.

v5 lv_cpicker_create calls `lv_obj_set_signal_func` and `lv_obj_set_design_func`, but v6 never shows that being used by anything other than `lv_objx_templ`.

Similar story w/ `ancestor_signal` and `ancestor_design`.

I am new to this lib and not familar w/ what seems like the v5 template.
Are `lv_obj_set_signal_func` and `lv_obj_set_design_func` require to init the v5 objx?
Looking to see how other controls are initialized...

**Comment by embeddedt** [comment]
`lv_objx_template` is not obsolete. See https://github.com/littlevgl/lvgl/blob/master/src/lv_objx/lv_objx_templ.c.

**Comment by paulpv** [comment]
FYI, looks like in `lv_objx_templ.c`, `lv_signal_func_t` should be renamed `lv_signal_cb_t`, and `lv_design_func_t` to `lv_design_cb_t`

**Comment by paulpv** [comment]
Progress! I am able to get the center dot to draw [but oddly, red].
Next I suspect the triangle drawing calls need to be migrated better.

**Comment by paulpv** [comment]
"Accidentally" hit "Ready For Review" to test if it would let me enter text; it didn't, so here we are in review.
**Not** actually ready for review yet!

The UI draws OK now, but events still aren't hooked up.
I'll work on that tonight/tomorrow.

**Comment by embeddedt** [comment]
> Not actually ready for review yet!

No problem. It's really too bad that you can't go back to a draft once it's "ready for review".

**Comment by paulpv** [comment]
This is ready for review/testing.
Note that I don't know this code very well, so if there are "existing" bugs @AloyseTech might be better to fix them.

**Comment by paulpv** [comment]
Again, my Arduino test app is at:
https://github.com/paulpv/lv_examples/blob/master/lv_tests/lv_test_objx/lv_test_cpicker/lv_test_cpicker.ino

Sorry, I am totally not set up to test this on any other environments. :/

**Comment by paulpv** [comment]
Video of it in action:
<a href="http://www.youtube.com/watch?feature=player_embedded&v=l_1NwwVqQzk" target="_blank">IMAGE ALT TEXT HERE</a>
It is very slow.
I will be trying some tricks the the display driver to speed it up, but do you have any obvious suggestions?

**Comment by paulpv** [comment]
In the above video, notice the first draw starting at 7 seconds and ending at 9 seconds.
If I entirely `#if false` all of the cpicker code and just print the title, it still takes about 2 seconds to paint the screen. :/
I am hard initializing my ILI9341 SPI to 40000000 Hz.
Arduino sketch has been updated.

**Comment by embeddedt** [comment]
@paulpv I'll test it on my STM32 later (where it was previously fast in 5.3). If it acts the same as it used to there then the performance issue is not related to the color picker itself.

**Comment by kisvegabor** [comment]
@paulpv 
> I will be trying some tricks the the display driver to speed it up, but do you have any obvious suggestions?

Using [display.writePixels](https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_SPITFT.h#L209) should speed up drawing.

**Comment by AloyseTech** [comment]
If you use the TinyPICO you could take a look at the ESP32 port/driver maybe?

**Comment by paulpv** [comment]
Performance problem solved.
Even the display's base graphics test was slow.
Unbeknownst to me I was using the Software SPI (SWSPI) mode of the Adafruit ILI9341 driver.
I switched to Hardware SPI (HWSPI) mode and both the graphics test and the lvgl test app are much faster.

**Comment by paulpv** [comment]
display.writePixels implemented.
Display looks good and **seems** a little faster.

Is there an easy way to add a FPS overlay, or is that not really relevant here?

**Comment by embeddedt** [comment]
> Is there an easy way to add a FPS overlay, or is that not really relevant here?

Not particularly. Just use the benchmark from `lv_examples` and add a color picker to it somewhere. Then you can check rendering speed, which is the closest unit we have to FPS.

**Comment by paulpv** [comment]
Oh, I haven't even tried the Rect version of the control yet. :/

**Comment by paulpv** [comment]
FYI:
With cpicker:  ~3.6 screen redraws per second
Without cpicker: ~21.8 screen redraws per second

**Comment by embeddedt** [comment]
> With cpicker: ~3.6 screen redraws per second

Ouch. I think this would be pretty visible to the human eye (especially on slower chips). It's probably worth looking into why it's so slow.

**Comment by paulpv** [comment]
I'm new to lvgl and its capabilities, but I would think that the control triangles could be generated only at the moment the mode is set (implying at creation too) and then persist as a [hopefully faster to draw?] static background image that the cursor control is then drawn over.
If the mode is changed that is probably an acceptable time for a small FPS hit to calculate the control's new mode's image using the current values.
Theory only...and I currently have little to no idea how to implement that.

The "FPS" still seems very usable to me, but I am running an ESP32.

**Comment by embeddedt** [comment]
> persist as a [hopefully faster to draw?] static background image that the cursor control is then drawn over.

The usual solution that the other objects use is to respect the `mask` that gets passed to the `design` function. Not sure if the color picker does that or not. With the other objects, the `mask` is passed all the way into the drawing functions like `lv_draw_rect`, etc. which then skip calculations of areas outside the mask.

If you know, how fast is it with the rectangular version?

**Comment by paulpv** [comment]
Rectangle is a bit messed up.
I'll work on it "soon".

**Comment by kisvegabor** [comment]
Drawing hundreds of triangles/arcs will be very slow anyway. Probably the rectangle like color picker would be a better direction. Less fancy but should be much faster. Unfortunately, I don't remember how the rectangle version looked like in @AloyseTech 's implementation but IMO something like in [Paint](https://www.howtogeek.com/wp-content/uploads/2008/06/image8.png.pagespeed.ce.VrLpYz6vEI.png) could be good direction (rectangle + slider for brightness). Or three sliders for Hue, Saturation, and Value?

**Comment by embeddedt** [comment]
> Drawing hundreds of triangles/arcs will be very slow anyway. Probably the rectangle like color picker would be a better direction. Less fancy but should be much faster.

I think we should allow both options (if it doesn't increase the code size). I still need to test the round version but in the past on STM32 the speed was very reasonable.

> Or three sliders for Hue, Saturation, and Value?

You mean something like the way I did the image recoloring example?

**Comment by AloyseTech** [comment]
To speed up the circular version you can play with the quantization factor. The higher the QF, the faster the rendering. The color wheel is made with 360/QF triangles for Hue (100 for Saturation and Value). If QF is too high, the wheel will lok like a polygon and will have less color gradient displayed (the center preview color will display the 360 or 100 value though.

**Comment by paulpv** [comment]
Yes, a more practical UI may be to have 3 sliders.
That said, and I mean this as a compliment, @AloyseTech's control (which I have seen similar in other places) is beautiful overkill.
Perhaps this control would be best as a stand-alone 3rd party control and not a first-class citizen of lvgl?

**Comment by embeddedt** [comment]
With the default QF setting (1) this is definitely much slower than how I remember it being back in December.

I adjusted the QF to 4 and gave it another try. It had much better performance. I will see how high I can make the QF without much visual difference. (I feel like I'm adjusting the quality setting on a JPEG before I export it.)

**Comment by embeddedt** [comment]
I was trying to run the benchmark and get some objective data, but in the process... LittlevGL seems to have lost the ability to properly handle text at the moment (font is not rendering or being measured). Investigation continues...

**Comment by embeddedt** [comment]
@kisvegabor Any ideas as to why all text rendering stopped functioning for me on `dev-6.1` HEAD? An older version of `dev-6.1` or the `master` branch both seem to work fine. Do I need to change something else?

----------------------------------------

Here's the raw benchmark results for STM32F746-Discovery (custom port, not the SW4STM32 one):
```
* Screen load without color picker:     34  ms
* Screen load with color picker, QF 16: 77  ms
* Screen load with color picker, QF  8: 98  ms
* Screen load with color picker, QF  4: 130 ms
* Screen load with color picker, QF  3: 152 ms
* Screen load with color picker: QF  2: 200 ms
* Screen load with color picker, QF  1: 340 ms
```

Keep in mind I ran these with minimal system load (only the overhead of an operating system). A real application would have more widgets.

**Comment by embeddedt** [comment]
[Here are the results in chart format.](https://docs.google.com/spreadsheets/d/1DmNQH3t3roNKHEjirLEcxeUMDVXDYI5SmSQrxxfzMCc/edit?usp=sharing)

It looks the best options for a default QF would be 2, 3, or 4. Beyond that there is minimal performance gain, and the widget does not look very good.

In my opinion, a QF of 3 gives the best balance between performance and looks.

**Comment by paulpv** [comment]
Yes, 3 looks good. 4 has recurring artifacts.
Still haven't touched the broken Rectangle code yet.

Any opinions on whether this is worthy of being a 1st class control or if this PR should be abandoned and this code become a 3rd party repo of its own?
I am assuming the latter is possible, but I suppose it is **possible** it is too tightly integrated, but it seems fairly separable to my naive self.

**Comment by embeddedt** [comment]
> Any opinions on whether this is worthy of being a 1st class control or if this PR should be abandoned and this code become a 3rd party repo of its own?

I think it's fine to merge it, like I said above. No one is forced to use it, and I think it is performant enough for most cases. :smiley:

**Comment by paulpv** [comment]
> I think it's fine to merge it, like I said above. No one is forced to use it.

Understood, but the owners of this project might feel forced to maintain it. :/

**Comment by embeddedt** [comment]
> the owners of this project might feel forced to maintain it.

As one of the owners, I can say that I wouldn't feel forced at all. :wink:

This kind of widget looks good in screenshots/demos/etc. (especially if it were to be animated), so I would be happy to keep it working.

**Comment by kisvegabor** [comment]
I agree to merge this widget, but the code needs to be cleaned up.

@embeddedt 
> As one of the owners, I can say that I wouldn't feel forced at all.

Actually we are forced to maintain it. If somebody reports a bug in it we should fix it. And to do so the widget should be clean, easy to understand and well commented. For example `lv_cpicker_disc_design` is 400 lines long. It should be cleaned up and broken into smaller functions to make it easier to digest. If we don't use the rectangle mode then the related code should be removed. 

@paulpv 
Don't misunderstand me, any contribution is highly appreciated, however, unfortunately, I already had bad experiences when I needed to almost completely rewrite other's widgets to make them work correctly. That's why I force to merge clean and easy to maintain code.

**Comment by embeddedt** [comment]
> but the code needs to be cleaned up.

Fair enough. 

> It should be cleaned up and broken into smaller functions to make it easier to digest.

Yes; I agree.

**Comment by paulpv** [comment]
I'll still attempt to fix the Rectangle version.
Perhaps I could just comment it out until it is fixed?

Since this is not my original code, I'll query: Who would be the best person to clean this code up?
I'm gonna predict you'll say me. :P

**Comment by embeddedt** [comment]
> I'll query: Who would be the best person to clean this code up?
I'm gonna predict you'll say me. :P

You are good at predicting. :wink:

Seriously, though, in my opinion, you are probably the most familiar with that code and therefore the best candidate for the task. But let's wait and see what @kisvegabor says.

**Comment by kisvegabor** [comment]
> Seriously, though, in my opinion, you are probably the most familiar with that code and therefore the best candidate for the task. But let's wait and see what @kisvegabor says.

It'd be great if @paulpv could make the initial clean up (too long functions, comments etc). After that, I'd happily review it and make some fine-tuning (API, further simplification, optimization etc.).

**Comment by paulpv** [comment]
Will do as I am trying to get Rect working.
I suppose were all volunteers here. Three toddler or less kids slow down my contributions a lot. I will get to it "soon".

**Comment by embeddedt** [comment]
Interesting: https://forum.littlevgl.com/t/color-picker-widget/727

**Comment by paulpv** [comment]
Update: I made good progress on updating the code and fixing the two issues I found with the Rect version.
What follows is by no means a criticism of @AloyseTech's good and hard work; it is just intended as a statement of fact.
It looks like from @AloyseTech last push that his Rect code was **mostly** a copy and paste of the Disc code, and the Rect code still contained use of ATAN and outer and inner radii, as well as todo comments saying to use the rect of the gradient and preview of the control.
Most of that is implemented now, as well as a breaking down the code in to smaller functions.
It still may be a day or two before it is ready for review again.
I'll get it done, but it's probably safe to say that the only one in a rush for this to be done is me. :)

**Comment by paulpv** [comment]
I'm a bit stuck. :/
I have a [sub] branch where I broke down the code a bit...but I ended up breaking something along the way.
So, I backtracked and started to just fix the functionality issues that I found along the way.
So, keep in mind that my request below is for the original non-broken down code (that I still intend to break down, but only **after** all known issues are working).

All of the issues I found seem to be fixed now...
...except for the Rect's "optimized" invalidation of only the "LINE" indicator. :/
The Disk "Circle", "Line", and "In" indicators seem to invalidate just fine.
The Rect "Circle", and "In" indicators seem to invalidate just fine.
Only the Rect "Line" indicator isn't invalidating...nor is it even letting me select the left ~1/4 values...but again things work fine for all other indicators.

I must be missing some obvious simple bug in my code, or in how lvgl invalidation works.

Are any of you in a position to run this [non-cleaned up] code and look at how the Rect is invalidating and spotting whatever obvious issue I am missing?
I'll keep banging on this, but any help would be appreciated.

Thanks!

**Comment by kisvegabor** [comment]
@paulpv 
I'd look into it. Can you send a coded snippet to reproduce the issue?

**Comment by paulpv** [comment]
Code from my test sketch at https://github.com/paulpv/lv_examples/blob/master/lv_tests/lv_test_objx/lv_test_cpicker/lv_test_cpicker.ino
The RECT LINE behaves weird; all the others seem fine.
The code is almost all the same between them, only real difference is the drawing, and I privately hard-coded that and it seems to draw just fine. :/
```
    static lv_style_t styleMain;
    lv_style_copy(&styleMain, &lv_style_plain);
    styleMain.line.width = pickerSize * 0.2;

    static lv_style_t styleIndicator;
    lv_style_copy(&styleIndicator, &lv_style_plain);
    styleIndicator.body.main_color = LV_COLOR_WHITE;
    styleIndicator.body.grad_color = styleIndicator.body.main_color;
    styleIndicator.body.opa = LV_OPA_80;

    lv_obj_t * scr = lv_disp_get_scr_act(disp);

    colorPicker = lv_cpicker_create(scr, NULL);
#if false
    lv_obj_set_size(colorPicker, pickerSize, pickerSize);
    lv_cpicker_set_type(colorPicker, LV_CPICKER_TYPE_DISC);
    lv_cpicker_set_indicator_type(colorPicker, LV_CPICKER_INDICATOR_LINE);
#else
    lv_obj_set_size(colorPicker, pickerSize, pickerSize / 2);
    lv_cpicker_set_type(colorPicker, LV_CPICKER_TYPE_RECT);
    lv_cpicker_set_indicator_type(colorPicker, LV_CPICKER_INDICATOR_LINE);
#endif
    lv_obj_align(colorPicker, NULL, LV_ALIGN_CENTER, 0, 0);
    lv_cpicker_set_style(colorPicker, LV_CPICKER_STYLE_MAIN, &styleMain);
    lv_cpicker_set_style(colorPicker, LV_CPICKER_STYLE_INDICATOR, &styleIndicator);
```

**Comment by paulpv** [comment]
FYI, the following combos seem to work fine:
```
LV_CPICKER_TYPE_DISC  + LV_CPICKER_INDICATOR_LINE
LV_CPICKER_TYPE_DISC  + LV_CPICKER_INDICATOR_CIRCLE
LV_CPICKER_TYPE_DISC  + LV_CPICKER_INDICATOR_IN
LV_CPICKER_TYPE_RECT  + LV_CPICKER_INDICATOR_CIRCLE
LV_CPICKER_TYPE_RECT  + LV_CPICKER_INDICATOR_IN
```

Only `LV_CPICKER_TYPE_RECT  + LV_CPICKER_INDICATOR_LINE` seems to not work. :/

the LV_CPICKER_TYPE_RECT signal code doesn't care about the indicator type, so it works for 2 of the 3 indicators, and drawing **seems** to work for all 3 indicators, but hooking together input signaling and drawing doesn't work only for RECT LINE. :/

I'll still bang away at it.

**Comment by paulpv** [comment]
Here is a video of the drawing bug:
<a href="http://www.youtube.com/watch?feature=player_embedded&v=4HxBW4xpQb0" target="_blank">IMAGE ALT TEXT HERE</a>

Here is the Line drawing code (the Circle and In code draw and accept [the same] input just fine):
(circa https://github.com/littlevgl/lvgl/pull/1196/files#diff-377eaf57e58ece914765518d2b0618d7R1077)
```
            lv_point_t p1, p2;
            p1.x = ext->rect_gradient_area.x1 + ind_pos;
            p1.y = ext->rect_gradient_area.y1;
            p2.x = p1.x;
            p2.y = ext->rect_gradient_area.y2;

            lv_draw_line(&p1, &p2, mask, ext->indicator.style, opa_scale);
```

I have no idea what is causing that odd "black hole" of a triangle to not redraw.

**Comment by paulpv** [comment]
Better video showing all 3 modes in action and only one not working as expected:
<a href="http://www.youtube.com/watch?feature=player_embedded&v=F9GxiDoPoCI" target="_blank">IMAGE ALT TEXT HERE</a>

**Comment by paulpv** [comment]
I'm moving on w/ the cleanup, which will result in cleaner code that hopefully magically fixes the problem...

**Comment by kisvegabor** [comment]
Thank you for the code and the videos. I've found the issue and pushed a fix.

[Here](https://github.com/littlevgl/lvgl/pull/1196/commits/8dcb1ff21c7c6138198a7673dcf5172229c5d104#diff-377eaf57e58ece914765518d2b0618d7L1901) X was used as Y.

**Comment by paulpv** [comment]
Hallelujah for code reviews! I knew it had to be something simple!
Thanks!
Onward and upward...

**Comment by kisvegabor** [comment]
I'm thinking about color indicator in rectangle mode. 
IMO it's not what user always want. 
What about removing it and let the user to monitor the current color and do what he wants with it?

**Comment by paulpv** [comment]
> I'm thinking about color indicator in rectangle mode.
> IMO it's not what user always want.
> What about removing it and let the user to monitor the current color and do what he wants with it?

For this PR I plan to stick with the spirit of @AloyseTech's original idea.
The functionality is welcome to be tweaked, but my opinion is to save changes like you recommend for future PRs.

**Comment by kisvegabor** [comment]
> The functionality is welcome to be tweaked, but my opinion is to save changes like you recommend for future PRs.

Okay. 

I've got email notification about this [commit](https://github.com/paulpv/lvgl/commit/9b0aa097d3dea93d4aa74edb27d7b9329807fb7c) but can't see here now. What happened? What was the problem with the fonts?

**Comment by paulpv** [comment]
The 4 robot fonts don't compile with their first `#include "lvgl/lvgl.h"` line.

You had just merged 6.1 but I assumed my branch was off caused all 4 roboto files showed up in the PR.
I erroneously deleted them on my branch and pushed.
I immediately realized my error and rather than correctly simply commit a revert of my changes I probably erroneously reset my branch to before my deleting the fonts and then forced a push.
Bad me, but it was just on my branch so hopefully no harm done.

I still have to have my local roboto font files change their first line to `#include "../../lvgl.h"` in order to get them to compile.

FYI: I've made great progress on the cleanup and am almost done.

**Comment by paulpv** [comment]
OK, please review!
Please pay specific attention to function parameters, and if any of them should be const or * or something else more appropriate.

Please also feel free to refactor the code more as you see fit and that meets your standards.
I read them and think I am close, but I am probably not 100% on.

I'm also not able to set to color color value at app setup time and have it display as the set value.
I have a hunch that the code needs to wait until after LVGL is finished initializing before I can set the value and have it display correctly.
Might this hunch be correct, and is this normal, and how to do it?

I also plan to take another pass and reduce the number of `trigo` calls by saving a calculated value and using it multiple times, instead of re-calculating the exact same values multiple times.
That may or may not happen in this PR.

**Comment by paulpv** [comment]
Again, a stand-alone test app can be seen here.
https://github.com/paulpv/lv_examples/blob/master/lv_tests/lv_test_objx/lv_test_cpicker/lv_test_cpicker.ino

I didn't figure out how to run tests so that I can write ones for this control.

**Comment by embeddedt** [comment]
> Might this hunch be correct, and is this normal, and how to do it?

Anything that gets called after `lv_init` should work properly. `lv_init` is not asynchronous.

**Comment by paulpv** [comment]
Funny, after all the `cleanup`, consolidating a ton of duplicated code, I ended up saving less than 100 lines! :/
Before: Before...
After: After...

**Comment by kisvegabor** [comment]
@paulpv 
Awesome, thank you! I'll immerse in it next week!

> Please also feel free to refactor the code more as you see fit and that meets your standards.
I read them and think I am close, but I am probably not 100% on.

Look good at first look! 

>  I ended up saving less than 100 lines! :/

I'm sure you do much more if you take the new function prototypes and extra comments into account. :wink: 

As I'm mentioned [here](https://github.com/littlevgl/lvgl/pull/1196#issuecomment-535363716) I'm not sure all the current features are really required. We should end up with a lean and flexible object. It'd easier to review/refactor if I could reshape these things at once. I suggest merging the current state into a `feat-cpicker` branch. This way the current version would be already in lvgl and it can be used as a base of further improvements. What do you think?

**Comment by paulpv** [comment]
@kisvegabor do whatever makes the most sense for the project! You want to create the `feat-cpicker` branch, or should I? I'll default to just following your lead.

**Comment by kisvegabor** [comment]
I've created it because write access is required to create new branches. 

So I've merged the current state to `feat-cpicker` and I'll start ot work on it next week.

Thank you very much @paulpv and @AloyseTech!

**Comment by paulpv** [comment]
Thanks!

There seems to be a bug w/ setting the color with lv_color_t, where it computes hsv but then only sets h.
Simple fix, but I'm trying to wrap my head around how 565 color works in lvgl and why I don't get the results I expect when I call `lv_cpicker_set_color(colorPicker, LV_COLOR_MAGENTA);`

I am also experimenting with replacing:
```
typedef struct {
    uint16_t hue;
    uint8_t saturation;
    uint8_t value;
...
    uint16_t prev_hue;
    uint8_t prev_saturation;
    uint8_t prev_value;
...
} lv_cpicker_ext_t;
```
with
```
typedef struct {
    lv_color_hsv_t hsv;
...
    lv_color_hsv_t prev_hsv;
...
} lv_cpicker_ext_t;
```

Finally, once fully stabilized and merged to production I may consider adding logic to better interop w/ FastLED (https://github.com/FastLED/FastLED/wiki/FastLED-HSV-Colors), but if that doesn't make any sense to be in LVGL then I can always make it a stand alone-repo.

**Comment by kisvegabor** [comment]
> There seems to be a bug w/ setting the color with lv_color_t, where it computes hsv but then only sets h.
Simple fix, but I'm trying to wrap my head around how 565 color works in lvgl and why I don't get the results I expect when I call lv_cpicker_set_color(colorPicker, LV_COLOR_MAGENTA);

Fell free to send PR to `feat-cpicker` if you have a fix.

> Finally, once fully stabilized and merged to production I may consider adding logic to better interop w/ FastLED (https://github.com/FastLED/FastLED/wiki/FastLED-HSV-Colors), but if that doesn't make any sense to be in LVGL then I can always make it a stand alone-repo.

That's impressive! We can update [lv_color_hsc_to_rgb](https://github.com/littlevgl/lvgl/blob/master/src/lv_misc/lv_color.c#L46) to work with these corrected curves.

**Comment by paulpv** [comment]
Heads Up: The setting and getting of the color components does seem to me to be wonky.
To control starts off set to Greenish, even though it resets to Red just fine.
Setting a color doesn't display as set.
And I'm still wrapping my head around 565 colors.
Obviously this shouldn't be merged with production until any issue here is resolved. I'll be looking in to it when I get time, but if you see the same issue and see a fix please make it so!

**Pull request merged**
