### PR TITLE
fix(kconfig) add LV_ATTRIBUTE_MEM_ALIGN, LV_ATTRIBUTE_LARGE_CONST and LV_SYSMON_GET_IDLE configs

### PR DESCRIPTION
**Pull request by cosmindanielradu19**
add LV_ATTRIBUTE_MEM_ALIGN default value

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by liamHowatt — COMMENTED** [review]
Hmm the only risk is that not all compilers support `__attribute__` directives. That being said, in the real world many projects using Kconfig will be building with a compiler that supports it.

**Comment by kisvegabor** [comment]
It's really not a platform independent portable change. :slightly_frowning_face: 
Adding it as a suggestion in the `help` can help a little, but it's not a perfect solution for sure.

**Comment by nicusorcitu** [comment]
There are also another configs which are missing from Kconfig:
```
+                config LV_ATTRIBUTE_LARGE_CONST
+                        string "Attribute to mark large constant arrays for example font's bitmaps"
+                        default ""

```
```
+                config LV_SYSMON_GET_IDLE
+                        string "Get the idle percentage. E.g. uint32_t my_get_idle(void)"
+                       depends on LV_USE_SYSMON
+                        default "lv_timer_get_idle"
```

**Comment by cosmindanielradu19** [comment]
> There are also another configs which are missing from Kconfig:
> 
> ```
> +                config LV_ATTRIBUTE_LARGE_CONST
> +                        string "Attribute to mark large constant arrays for example font's bitmaps"
> +                        default ""
> ```
> 
> ```
> +                config LV_SYSMON_GET_IDLE
> +                        string "Get the idle percentage. E.g. uint32_t my_get_idle(void)"
> +                       depends on LV_USE_SYSMON
> +                        default "lv_timer_get_idle"
> ```

@kisvegabor is it ok to add those two configs as they are stated by @nicusorcitu, and replace the default value to empty string for LV_ATTRIBUTE_MEM_ALIGN ?

**Comment by cosmindanielradu19** [comment]
> It's really not a platform independent portable change. 🙁 Adding it as a suggestion in the `help` can help a little, but it's not a perfect solution for sure.

Ok, then I will change the default value to an empty string, and move the current default to help

Shall we also add the configs that @nicusorcitu mentioned above?

**Comment by kisvegabor** [comment]
> Shall we also add the configs that @nicusorcitu mentioned above?

Yes, please.

**Review by liamHowatt — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
Great! Thank you!

**Comment by tore-espressif** [comment]
@kisvegabor this last-minute change broke v9.2.1 on ESPs ... https://github.com/lvgl/lvgl/issues/7154 :(

**Comment by cosmindanielradu19** [comment]
@kisvegabor as long as those configs broke the ESP build, and the fact that they are compiler dependent, I would suggest adding a `lv_compiler.h` file that should contain all the `COMPILER SETTINGS` from kconfig. The defines can remain only in the new header, and can be removed from both `lv_conf.h` and `kconfig` file.

E.g. 

```c
/**
 * @file lv_compiler.h
 * Configuration file for LVGL based on the compiler
 */

#ifndef LV_COMPILER_H
#define LV_COMPILER_H

#ifdef __GNUC__
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN __attribute__((aligned(LV_ATTRIBUTE_MEM_ALIGN_SIZE)))
#define LV_ATTRIBUTE_LARGE_CONST __attribute__((section("DataQuickAccess"))) 
#else
#define CONFIG_LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_LARGE_CONST
#endif

#endif /*LV_COMPILER_H*/

```

**Comment by kisvegabor** [comment]
Ahhhh! Damn it. 

I wonder how it passed through as we have an ESP-IDF CI test running for MicroPython. 

Anyway, it makes sense that these `LV_ATTRIBUTE`s cannot be supported in Kconfig, as Kconfig will export these as strings. @nicusorcitu @cosmindanielradu19 I wonder how and in which environment did it wok for you.


---

I think we should revert this commit and release v9.2.2 ASAP.  I've pushed the revert to the `release/v9.2` branch. Please try it out.

**Comment by cosmindanielradu19** [comment]
> Anyway, it makes sense that these `LV_ATTRIBUTE`s cannot be supported in Kconfig, as Kconfig will export these as strings. @nicusorcitu @cosmindanielradu19 I wonder how and in which environment did it wok for you.

In our case, it worked with [west](https://docs.zephyrproject.org/latest/develop/west/index.html). If the default value was needed, instead of "", the config was empty (the default value was interpreted as no character).

**Pull request merged**
