### PR TITLE
Add lvgl interface target for micropython

### PR DESCRIPTION
**Pull request by eudoxos**
The CMake interface target for micropython is now working. Non-micropython builds are not affected.

### CODE REVIEW

**Comment by amirgon** [comment]
So this assumes Micropython-ESP32 migrates to usermod right?
In current state this change would break the ESP32 port.

**Comment by eudoxos** [comment]
> So this assumes Micropython-ESP32 migrates to usermod right?

Quite on the contrary, EPS32 and Zephyr should not be affected in the slightest.

I wanted to add indentation to `CMakeLists.txt` to make that clear but found it too intrusive. It is like this:

```cmake
if(ESP_PLATFORM)
# ... [unintended]
elseif(ZEPHYR_BASE)
# ... [unintended]
else()
    # [here is where my changes start]
    # ... 
    if(MICROPY_DIR)
        # ...
    else(MICROPY_DIR)
        # ...
    endif(MICROPY_DIR)
endif()
```

**Comment by amirgon** [comment]
> Quite on the contrary, EPS32 and Zephyr should not be affected in the slightest.

Got it. Thanks for the clarification!

**Comment by kisvegabor** [comment]
I can't judge if these changes are correct, so please let me know if it's ready to merge.

**Comment by amirgon** [comment]
> I can't judge if these changes are correct, so please let me know if it's ready to merge.

Looks good to me, although I can't test this since it's RPi specific change.

**Comment by kisvegabor** [comment]
Thank you, merging.

**Pull request merged**
