### PR TITLE
fix(Makefile) compilation errors

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
Compiler warning:
```bash
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/benchmark/lv_demo_benchmark.c: In function ‘scene_next_task_cb’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/benchmark/lv_demo_benchmark.c:694:38: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
  694 |         lv_label_set_text_fmt(title, "%"LV_PRId32"/%d: %s%s", scene_act * 2 + (opa_mode ? 1 : 0), (sizeof(scenes) / sizeof(scene_dsc_t) * 2) - 2,  scenes[scene_act].name, opa_mode ? " + opa" : "");
      |                                      ^~~                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                   |
      |                                                                                                   long unsigned int
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/benchmark/lv_demo_benchmark.c:694:53: note: format string is defined here
  694 |         lv_label_set_text_fmt(title, "%"LV_PRId32"/%d: %s%s", scene_act * 2 + (opa_mode ? 1 : 0), (sizeof(scenes) / sizeof(scene_dsc_t) * 2) - 2,  scenes[scene_act].name, opa_mode ? " + opa" : "");
      |                                                    ~^
      |                                                     |
      |                                                     int
      |                                                    %ld
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/benchmark/lv_demo_benchmark.c: In function ‘arc_create’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/benchmark/lv_demo_benchmark.c:965:33: warning: cast between incompatible function types from ‘void (*)(lv_obj_t *, uint16_t)’ {aka ‘void (*)(struct _lv_obj_t *, short unsigned int)’} to ‘void (*)(void *, int32_t)’ {aka ‘void (*)(void *, int)’} [-Wcast-function-type]
  965 |         lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t) lv_arc_set_end_angle);
      |                                 ^
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/benchmark/lv_demo_benchmark.c: In function ‘fall_anim’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/benchmark/lv_demo_benchmark.c:986:29: warning: cast between incompatible function types from ‘void (*)(struct _lv_obj_t *, lv_coord_t)’ {aka ‘void (*)(struct _lv_obj_t *, short int)’} to ‘void (*)(void *, int32_t)’ {aka ‘void (*)(void *, int)’} [-Wcast-function-type]
  986 |     lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t) lv_obj_set_y);
      |                             ^
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/stress/lv_demo_stress.c: In function ‘obj_test_task_cb’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/stress/lv_demo_stress.c:55:13: warning: stack usage is 2784 bytes [-Wstack-usage=]
   55 | static void obj_test_task_cb(lv_timer_t * tmr)
      |             ^~~~~~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.c: In function ‘msgbox_create’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.c:169:5: warning: "LV_EX_MOUSEWHEEL" is not defined, evaluates to 0 [-Wundef]
  169 | #if LV_EX_MOUSEWHEEL
      |     ^~~~~~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c: In function ‘spectrum_draw_event_cb’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:836:29: warning: passing argument 1 of ‘lv_draw_polygon’ from incompatible pointer type [-Wincompatible-pointer-types]
  836 |             lv_draw_polygon(poly, 4, clip_area, &draw_dsc);
      |                             ^~~~
      |                             |
      |                             lv_point_t * {aka struct <anonymous> *}
In file included from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw.h:27,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal_disp.h:21,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../lvgl.h:33,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../lv_demos.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:9:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw_triangle.h:30:46: note: expected ‘struct _lv_draw_ctx_t *’ but argument is of type ‘lv_point_t *’ {aka ‘struct <anonymous> *’}
   30 | void lv_draw_polygon(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * draw_dsc, const lv_point_t points[],
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:836:35: warning: passing argument 2 of ‘lv_draw_polygon’ makes pointer from integer without a cast [-Wint-conversion]
  836 |             lv_draw_polygon(poly, 4, clip_area, &draw_dsc);
      |                                   ^
      |                                   |
      |                                   int
In file included from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw.h:27,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal_disp.h:21,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../lvgl.h:33,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../lv_demos.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:9:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw_triangle.h:30:83: note: expected ‘const lv_draw_rect_dsc_t *’ {aka ‘const struct <anonymous> *’} but argument is of type ‘int’
   30 | void lv_draw_polygon(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * draw_dsc, const lv_point_t points[],
      |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:836:38: warning: passing argument 3 of ‘lv_draw_polygon’ from incompatible pointer type [-Wincompatible-pointer-types]
  836 |             lv_draw_polygon(poly, 4, clip_area, &draw_dsc);
      |                                      ^~~~~~~~~
      |                                      |
      |                                      const lv_area_t * {aka const struct <anonymous> *}
In file included from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw.h:27,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal_disp.h:21,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../lvgl.h:33,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../lv_demos.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:9:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw_triangle.h:30:110: note: expected ‘const lv_point_t *’ {aka ‘const struct <anonymous> *’} but argument is of type ‘const lv_area_t *’ {aka ‘const struct <anonymous> *’}
   30 | void lv_draw_polygon(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * draw_dsc, const lv_point_t points[],
      |                                                                                             ~~~~~~~~~~~~~~~~~^~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:836:49: warning: passing argument 4 of ‘lv_draw_polygon’ makes integer from pointer without a cast [-Wint-conversion]
  836 |             lv_draw_polygon(poly, 4, clip_area, &draw_dsc);
      |                                                 ^~~~~~~~~
      |                                                 |
      |                                                 lv_draw_rect_dsc_t * {aka struct <anonymous> *}
In file included from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw.h:27,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal_disp.h:21,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../lvgl.h:33,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../lv_demos.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:9:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw_triangle.h:31:31: note: expected ‘uint16_t’ {aka ‘short unsigned int’} but argument is of type ‘lv_draw_rect_dsc_t *’ {aka ‘struct <anonymous> *’}
   31 |                      uint16_t point_cnt);
      |                      ~~~~~~~~~^~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:842:29: warning: passing argument 1 of ‘lv_draw_polygon’ from incompatible pointer type [-Wincompatible-pointer-types]
  842 |             lv_draw_polygon(poly, 4, clip_area, &draw_dsc);
      |                             ^~~~
      |                             |
      |                             lv_point_t * {aka struct <anonymous> *}
In file included from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw.h:27,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal_disp.h:21,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../lvgl.h:33,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../lv_demos.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:9:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw_triangle.h:30:46: note: expected ‘struct _lv_draw_ctx_t *’ but argument is of type ‘lv_point_t *’ {aka ‘struct <anonymous> *’}
   30 | void lv_draw_polygon(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * draw_dsc, const lv_point_t points[],
      |                      ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:842:35: warning: passing argument 2 of ‘lv_draw_polygon’ makes pointer from integer without a cast [-Wint-conversion]
  842 |             lv_draw_polygon(poly, 4, clip_area, &draw_dsc);
      |                                   ^
      |                                   |
      |                                   int
In file included from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw.h:27,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal_disp.h:21,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../lvgl.h:33,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../lv_demos.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:9:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw_triangle.h:30:83: note: expected ‘const lv_draw_rect_dsc_t *’ {aka ‘const struct <anonymous> *’} but argument is of type ‘int’
   30 | void lv_draw_polygon(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * draw_dsc, const lv_point_t points[],
      |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:842:38: warning: passing argument 3 of ‘lv_draw_polygon’ from incompatible pointer type [-Wincompatible-pointer-types]
  842 |             lv_draw_polygon(poly, 4, clip_area, &draw_dsc);
      |                                      ^~~~~~~~~
      |                                      |
      |                                      const lv_area_t * {aka const struct <anonymous> *}
In file included from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw.h:27,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal_disp.h:21,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../lvgl.h:33,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../lv_demos.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:9:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw_triangle.h:30:110: note: expected ‘const lv_point_t *’ {aka ‘const struct <anonymous> *’} but argument is of type ‘const lv_area_t *’ {aka ‘const struct <anonymous> *’}
   30 | void lv_draw_polygon(struct _lv_draw_ctx_t * draw_ctx, const lv_draw_rect_dsc_t * draw_dsc, const lv_point_t points[],
      |                                                                                             ~~~~~~~~~~~~~~~~~^~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:842:49: warning: passing argument 4 of ‘lv_draw_polygon’ makes integer from pointer without a cast [-Wint-conversion]
  842 |             lv_draw_polygon(poly, 4, clip_area, &draw_dsc);
      |                                                 ^~~~~~~~~
      |                                                 |
      |                                                 lv_draw_rect_dsc_t * {aka struct <anonymous> *}
In file included from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw.h:27,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal_disp.h:21,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/lv_hal.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../lvgl.h:33,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../lv_demos.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.h:16,
                 from /home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/lv_demo_music_main.c:9:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/demos/music/../../src/hal/../draw/lv_draw_triangle.h:31:31: note: expected ‘uint16_t’ {aka ‘short unsigned int’} but argument is of type ‘lv_draw_rect_dsc_t *’ {aka ‘struct <anonymous> *’}
   31 |                      uint16_t point_cnt);
      |                      ~~~~~~~~~^~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/msgbox/lv_example_msgbox_1.c: In function ‘event_cb’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/msgbox/lv_example_msgbox_1.c:6:16: warning: unused variable ‘obj’ [-Wunused-variable]
    6 |     lv_obj_t * obj = lv_event_get_current_target(e);
      |                ^~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/switch/lv_example_switch_1.c: In function ‘event_handler’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/switch/lv_example_switch_1.c:7:16: warning: unused variable ‘obj’ [-Wunused-variable]
    7 |     lv_obj_t * obj = lv_event_get_target(e);
      |                ^~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/textarea/lv_example_textarea_1.c: In function ‘textarea_event_handler’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/textarea/lv_example_textarea_1.c:6:16: warning: unused variable ‘ta’ [-Wunused-variable]
    6 |     lv_obj_t * ta = lv_event_get_target(e);
      |                ^~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/checkbox/lv_example_checkbox_1.c: In function ‘event_handler’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/checkbox/lv_example_checkbox_1.c:10:22: warning: unused variable ‘state’ [-Wunused-variable]
   10 |         const char * state = lv_obj_get_state(obj) & LV_STATE_CHECKED ? "Checked" : "Unchecked";
      |                      ^~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/checkbox/lv_example_checkbox_1.c:9:22: warning: unused variable ‘txt’ [-Wunused-variable]
    9 |         const char * txt = lv_checkbox_get_text(obj);
      |                      ^~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_1.c: In function ‘event_handler’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_1.c:10:22: warning: unused variable ‘txt’ [-Wunused-variable]
   10 |         const char * txt = lv_btnmatrix_get_btn_text(obj, id);
      |                      ^~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/win/lv_example_win_1.c: In function ‘event_handler’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/win/lv_example_win_1.c:7:16: warning: unused variable ‘obj’ [-Wunused-variable]
    7 |     lv_obj_t * obj = lv_event_get_target(e);
      |                ^~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/list/lv_example_list_1.c: In function ‘event_handler’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/examples/widgets/list/lv_example_list_1.c:8:16: warning: unused variable ‘obj’ [-Wunused-variable]
    8 |     lv_obj_t * obj = lv_event_get_target(e);
      |                ^~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/extra/widgets/meter/lv_meter.c: In function ‘lv_meter_event’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/extra/widgets/meter/lv_meter.c:289:13: warning: stack usage might be 2064 bytes [-Wstack-usage=]
  289 | static void lv_meter_event(const lv_obj_class_t * class_p, lv_event_t * e)
      |             ^~~~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/core/lv_indev.c:54:5: warning: "LV_LOG_TRACE_INDEV" is not defined, evaluates to 0 [-Wundef]
   54 | #if LV_LOG_TRACE_INDEV
      |     ^~~~~~~~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/core/lv_obj.c: In function ‘lv_init’:
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/core/lv_obj.c:171:5: warning: "LV_LOG_LEVEL" is not defined, evaluates to 0 [-Wundef]
  171 | #if LV_LOG_LEVEL == LV_LOG_LEVEL_TRACE
      |     ^~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/core/lv_event.c:42:5: warning: "LV_LOG_TRACE_EVENT" is not defined, evaluates to 0 [-Wundef]
   42 | #if LV_LOG_TRACE_EVENT
      |     ^~~~~~~~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/core/lv_refr.c:87:5: warning: "LV_LOG_TRACE_DISP_REFR" is not defined, evaluates to 0 [-Wundef]
   87 | #if LV_LOG_TRACE_DISP_REFR
      |     ^~~~~~~~~~~~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/hal/lv_hal_indev.c:41:5: warning: "LV_LOG_TRACE_INDEV" is not defined, evaluates to 0 [-Wundef]
   41 | #if LV_LOG_TRACE_INDEV
      |     ^~~~~~~~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/misc/lv_anim.c:46:5: warning: "LV_LOG_TRACE_ANIM" is not defined, evaluates to 0 [-Wundef]
   46 | #if LV_LOG_TRACE_ANIM
      |     ^~~~~~~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/misc/lv_mem.c:65:5: warning: "LV_LOG_TRACE_MEM" is not defined, evaluates to 0 [-Wundef]
   65 | #if LV_LOG_TRACE_MEM
      |     ^~~~~~~~~~~~~~~~
/home/vifextech/workpath/misc/lv_sim_eclipse_sdl/lvgl/src/misc/lv_timer.c:42:5: warning: "LV_LOG_TRACE_TIMER" is not defined, evaluates to 0 [-Wundef]
   42 | #if LV_LOG_TRACE_TIMER
      |     ^~~~~~~~~~~~~~~~~~
```

**Review by embeddedt — APPROVED** [review]

**Comment by FASTSHIFT** [comment]
`LV_LOG_TRACE_XXX` should be defined as 0 when `LV_USE_LOG` is defined as 0 to avoid warning.

**Comment by FASTSHIFT** [comment]
> `LV_LOG_TRACE_XXX` should be defined as 0 when `LV_USE_LOG` is defined as 0 to avoid warning.

I fixed this problem in this pr.

**Comment by kisvegabor** [comment]
> LV_LOG_TRACE_XXX should be defined as 0 when LV_USE_LOG is defined as 0 to avoid warning.

I'd rather add these new definitions to the end of `lv_conf_internal.h` (generated by `lv_conf_internal_gen.py`) to keep `lv_conf.h` simpler.

**Comment by FASTSHIFT** [comment]
> > LV_LOG_TRACE_XXX should be defined as 0 when LV_USE_LOG is defined as 0 to avoid warning.
> 
> I'd rather add these new definitions to the end of `lv_conf_internal.h` (generated by `lv_conf_internal_gen.py`) to keep `lv_conf.h` simpler.

Okay, I removed the related changes, can you update `lv_conf_internal_gen.py`？

**Comment by kisvegabor** [comment]
> Okay, I removed the related changes, can you update lv_conf_internal_gen.py？

Done here 305284c2b

Merging, thanks!

**Pull request merged**
