### PR TITLE
first periodic mistake at lv_task_set_period

### PR DESCRIPTION
**Pull request by ogunduz**
Hi,
When we set the period, because of the 'task->last_run' isn't updated we can't know and contol the first period time.

### CODE REVIEW

**Comment by embeddedt** [comment]
This would change the existing behavior slightly. With this change, when `lv_task_set_period` is called, it implicitly calls `lv_task_reset` as well.

**Comment by kisvegabor** [comment]
@embeddedt In which cases can it change the existing behavior? As I see, now the time of the next call is non-deterministic so people can't expect anything on that.

**Comment by embeddedt** [comment]
@kisvegabor This isn't a perfect real-life example, but I think it illustrates my general concern. Let's say we create two tasks:

* Task A runs every two seconds.
* Task B runs every second.

Assume for the purposes of this example that tasks take near-zero time to execute.

Suppose Task A runs to completion. One second later, Task B will run, and half of Task A's waiting time will have expired.

In Task B, we change Task A's period to **3** seconds (instead of 2).

With the prior behavior, 1 second has already passed since Task A last ran, so 2 seconds later, Task A will run.

With the new behavior, the timer will be reset, so it will be 3 seconds before Task A runs.

This probably won't be an issue for the majority of users. However, for someone who heavily relies on the order and timing in which tasks are run, this would change their application's behavior.

**Comment by seyyah** [comment]
> This probably won't be an issue for the majority of users. However, for someone who heavily relies on the order and timing in which tasks are run, this would change their application's behavior.

I agree with you @embeddedt

**Comment by kisvegabor** [comment]
Hm, really there are corner cases when the user might count on the current behavior.

@ogunduz What about manually calling `lv_task_rest()` or `lv_task_ready()` after `lv_task_set_period` to explicitly tell what should happen?

**Comment by ogunduz** [comment]
@kisvegabor It is also can do with calling  `lv_task_rest()`, but I expected that when I call the `lv_task_set_period()`, the next task should be perform after t ms.

**Comment by embeddedt** [comment]
I think, for both compatibility and flexibility reasons, it would be better to have people explicitly call `lv_task_reset` if they want the behavior @ogunduz was expecting.

We could put the change in `dev-6.1`, but that just delays the surprise for the users out there who rely on the current timing.

**Comment by kisvegabor** [comment]
> I think, for both compatibility and flexibility reasons, it would be better to have people explicitly call lv_task_reset if they want the behavior @ogunduz was expecting.

I agree.

**Comment by embeddedt** [comment]
Is adding a note to the documentation about this behavior and closing the PR acceptable for you, @ogunduz?

**Pull request closed without merging**
