### PR TITLE
Fix #1795: ensure switch/bar visual state matches logical state

### LINKED ISSUE #1795: lv_switch visual state does not match logical state
**Describe the bug**

When clicking the switch repeatedly, the state does not correspond to the visual appearance.

**To Reproduce**

Please provide a small, independent code sample that can be used to reproduce the issue. Ideally, this should work in the PC simulator unless the problem is specific to one platform.

**Expected behaviour**

**Screenshots**
Screenshot (31)

**Additional context**

### PR DESCRIPTION
**Pull request by embeddedt**
@HX2003 @hedyhefty If you could also test this fix that would be great.

Closes #1795.

### CODE REVIEW

**Review by kisvegabor — APPROVED** [review]
Thank you!
Let's wait for the feedback of @HX2003 @hedyhefty too.

**Comment by HX2003** [comment]
Looks good to me. Thanks.

**Comment by kisvegabor** [comment]
@embeddedt It can be merged if you wish.

**Comment by embeddedt** [comment]
Thanks for the feedback.

**Pull request merged**
