### PR TITLE
feat(anim): high fidelity animations

### PR DESCRIPTION
**Pull request by andresovela**
### High fidelity animations

I added a flag to enable animations that are updated on the moment the animated value changes, rather than on the refresh period.

The motivation for this change is that I accidentally ran into the worst case scenario for an animation, and the animation looks very jittery.

See [forum post](https://forum.lvgl.io/t/lvgl-not-refreshing-the-display-at-set-frame-rate/10633/1) for context.

#### Example:

- I have the refresh period set to 30 ms.
- By mere coincidence I set up an animation which would change a value every 31 ms.

----------------------------------
Before this PR:

```
                   Update-
 Update            skipped             Update
   ├──────────────────┼───────────────────┤
  0 ms              30 ms               60 ms
```

The update at 30 ms is skipped because the value hasn't changed. The animation timer is then rescheduled to run after the refresh period has passed again.

----------------------------------
After this PR:
```
 Update              Update              Update
   ├───────────────────┼───────────────────┤
  0 ms               31 ms               62 ms
```

The update at 30 ms does not happen either because the value hasn't changed, but the animation timer is rescheduled to run 1 ms after in order to update the animated value in time.

----------------------------------

#### Drawbacks
- This forces other active animations to run early as well.
- The implementation is wasteful in the sense that future values are calculated for every millisecond before the next refresh period. This could be computationally intensive if the `path_cb` function is complex, or if the refresh period is too long.

#### Pros
- Fixes jittery animations that have no way to be fixed with the current APIs.
- This change is opt-in and has pretty much no impact if not used.

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).

### CODE REVIEW

**Comment by andresovela** [comment]
I think I figured out how to prevent other non-hifi animations from running early when executing a hifi animation.

**Comment by kisvegabor** [comment]
Very interesting! Thank you for the PR.

I see the motivation behind this feature, but I'd like to understand something. The display refresh timer is also refreshed  e.g in every 30 ms. So it shouldn't matter how many times you update the animations between the calls of the display refresh timer, it will redraw only the last value.

So I wonder if we could do something simpler, like ensuring that the animation handler always runs before display refreshing. Could you try simply adding `lv_anim_refr_now(NULL)` [here](https://github.com/lvgl/lvgl/blob/5a0176fc9b3430f78570f5d62443ad513bca3f60/src/core/lv_refr.c#L396)?

Does it make any difference?

**Comment by andresovela** [comment]
That won't help. As you said, after 30 ms, no matter how many times you call `lv_anim_refr_now()`, it will recalculate the same unchanged values. `lv_anim_refr_now()` would need to be called just 1 ms later (in the case of the example in the description) for a new value to be yielded, which is what this PR essentially does.

**Comment by kisvegabor** [comment]
I'm not sure about it but can't we solve the problem in a simpler way with a rounding or so? If the period is 30ms and the value didn't change, let's see if it will change in the next half period (so at +15ms) and if so use that value.

What do you think?

**Comment by andresovela** [comment]
It's a compromise that could be made, but I don't think that fixes the problem. In the case of the example, that setup would end up refreshing the display as follows:
```
                   Update-             Update-
 Update            skipped    Update   skipped    Update
   ├──────────────────┼─────────┼─────────┼─────────┤
  0 ms              30 ms     45 ms     60 ms     75 ms
```
- It updates at 0 ms when it starts
- The update at 30 ms is skipped because the value changes at 31 ms
- We notice that it would change within the next half-period, so we schedule an update in 15 ms
- The animation is updated at 45 ms
- The update at 60 ms is skipped because the value changes at 62 ms
- We notice that it would change within the next half-period, so we schedule an update in 15 ms
- The animation is updated at 75 ms

And so on and so on

**Comment by andresovela** [comment]
I just tried it: the jittering is drastically reduced, but still there. It's a compromise that could be made.

We could make it an enum instead of a boolean and let the user decide what to do. Something like

```
/** Can be used to adjust the refresh period of a slow animation that does not update
 *  its values on every refresh period.
 *  Normal:   updates only on refresh period
 *  Balanced: updates within half a refresh period if the value is changing within that period
 *  Accurate: updates as soon as the animated value changes*/
typedef enum {
    LV_ANIM_REFRESH_MODE_NORMAL,
    LV_ANIM_REFRESH_MODE_BALANCED,
    LV_ANIM_REFRESH_MODE_ACCURATE,
} lv_anim_refresh_mode_t;

/**
 * Sets the refresh mode of the animation.
 * @param a             pointer to an initialized `lv_anim_t` variable
 * @param refresh_mode  refresh mode
 */
static inline void lv_anim_set_refresh_mode(lv_anim_t * a, lv_anim_refresh_mode_t refresh_mode)
{
    a->refresh_mode = refresh_mode;
}
```

What do you think?

**Comment by kisvegabor** [comment]
Hm, I think I still don't entirely understand the issue. I'd like to add this extra calculation if really needed. I understand that won't bother if it's not used, but it's still need to be maintained, documented, we will get questions about it, etc.

So let's have this example aniamtion:
```
time: value
0ms:   0
31ms:  1
62ms:  2
93ms:  3
104ms: 4
```

My rounding proposal should do this:
```
0ms:   0
30ms:  1 (no value change, but at 45ms it changes so use that value)
60ms:  2 (no value change, but at 75ms it changes so use that value)
90ms:  3 (no value change, but at 105ms it changes so use that value)
120ms: 4 (no value change, but at 135ms it changes so use that value)
```

How is the result of your algorithm different from it?

**Comment by andresovela** [comment]
As mentioned, your rounding proposal does reduce jittering drastically, but it still stutters a bit:

```
Frame | Refr Period | This PR | Rounding |
-----------------------------------------|
   0  |      0 ms   |    0 ms |    0 ms  | 
   1  |     30 ms   |   31 ms |   45 ms  | Stutter here: 45 ms between frames
   2  |     60 ms   |   62 ms |   75 ms  |
   3  |     90 ms   |   93 ms |  105 ms  |
   4  |    120 ms   |  124 ms |  135 ms  |
   5  |    150 ms   |  155 ms |  165 ms  |
   6  |    180 ms   |  186 ms |  195 ms  |
   7  |    210 ms   |  217 ms |  225 ms  |
   8  |    240 ms   |  248 ms |  255 ms  |
   9  |    270 ms   |  279 ms |  285 ms  |
  10  |    300 ms   |  310 ms |  315 ms  |
  11  |    330 ms   |  341 ms |  345 ms  |
  12  |    360 ms   |  372 ms |  375 ms  |
  13  |    390 ms   |  403 ms |  405 ms  |
  14  |    420 ms   |  434 ms |  435 ms  |
  15  |    450 ms   |  465 ms |  465 ms  |
  16  |    480 ms   |  496 ms |  495 ms  |
  17  |    510 ms   |  527 ms |  525 ms  |
  18  |    540 ms   |  558 ms |  555 ms  |
  19  |    570 ms   |  589 ms |  585 ms  |
  20  |    600 ms   |  620 ms |  615 ms  |
  21  |    630 ms   |  651 ms |  645 ms  |
  22  |    660 ms   |  682 ms |  675 ms  |
  23  |    690 ms   |  713 ms |  705 ms  |
  24  |    720 ms   |  744 ms |  735 ms  |
  25  |    750 ms   |  775 ms |  765 ms  |
  26  |    780 ms   |  806 ms |  795 ms  |
  27  |    810 ms   |  837 ms |  825 ms  |
  28  |    840 ms   |  868 ms |  855 ms  |
  29  |    870 ms   |  899 ms |  885 ms  |
  30  |    900 ms   |  930 ms |  900 ms  | Stutter here: 15 ms between frames
  31  |    930 ms   |  961 ms |  945 ms  | Stutter here: 45 ms between frames
  32  |    960 ms   |  992 ms |  975 ms  |
  33  |    990 ms   | 1023 ms | 1005 ms  |
  34  |   1020 ms   | 1054 ms | 1035 ms  |
  35  |   1050 ms   | 1085 ms | 1065 ms  |
  36  |   1080 ms   | 1116 ms | 1095 ms  |
  37  |   1110 ms   | 1147 ms | 1125 ms  |
  38  |   1140 ms   | 1178 ms | 1155 ms  |
  39  |   1170 ms   | 1209 ms | 1185 ms  |
  40  |   1200 ms   | 1240 ms | 1215 ms  |
  41  |   1230 ms   | 1271 ms | 1245 ms  |
  42  |   1260 ms   | 1302 ms | 1275 ms  |
  43  |   1290 ms   | 1333 ms | 1305 ms  |
  44  |   1320 ms   | 1364 ms | 1335 ms  |
  45  |   1350 ms   | 1395 ms | 1365 ms  |
  46  |   1380 ms   | 1426 ms | 1395 ms  |
  47  |   1410 ms   | 1457 ms | 1425 ms  |
  48  |   1440 ms   | 1488 ms | 1455 ms  |
  49  |   1470 ms   | 1519 ms | 1485 ms  |
  50  |   1500 ms   | 1550 ms | 1515 ms  |
  51  |   1530 ms   | 1581 ms | 1545 ms  |
  52  |   1560 ms   | 1612 ms | 1575 ms  |
  53  |   1590 ms   | 1643 ms | 1605 ms  |
  54  |   1620 ms   | 1674 ms | 1635 ms  |
  55  |   1650 ms   | 1705 ms | 1665 ms  |
  56  |   1680 ms   | 1736 ms | 1695 ms  |
  57  |   1710 ms   | 1767 ms | 1725 ms  |
  58  |   1740 ms   | 1798 ms | 1755 ms  |
  59  |   1770 ms   | 1829 ms | 1785 ms  |
  60  |   1800 ms   | 1860 ms | 1800 ms  | Stutter here: 15 ms between frames
  61  |   1830 ms   | 1891 ms | 1845 ms  | Stutter here: 45 ms between frames
  62  |   1860 ms   | 1922 ms | 1875 ms  |
```

Of course, the stuttering depends on the animation timing, the refresh period, etc. At least in this case, the stuttering with rounding is still visible to me.

**Comment by kisvegabor** [comment]
```
Frame | Refr Period | This PR | Rounding |
-----------------------------------------|
  30  |    900 ms   |  930 ms |  900 ms  | Stutter here: 15 ms between frames
  31  |    930 ms   |  961 ms |  945 ms  | Stutter here: 45 ms between frames
```

At 30  "This PR" uses the 930 ms "state" which should be used only on the next frame. So it will be one frame earlier and this off by one issue is accumulated. At the very end it's already off by two:
```
  60  |   1800 ms   | 1860 ms | 1800 ms  | Stutter here: 15 ms between frames
  61  |   1830 ms   | 1891 ms | 1845 ms  | Stutter here: 45 ms between frames
  62  |   1860 ms   | 1922 ms | 1875 ms  |
```

At 60 it runs what should only happen at 62.

I'd rather use the rounding approach as it's simpler and the timing is more accurate. Having a small jittering in very special cases is an acceptable trade off IMO.

**Comment by andresovela** [comment]
I realized I made a mistake by adding a column for the refresh period. What I should have added is the time in which each frame is rendered with the current code on the `main` branch:

```
Frame | Current code | This PR | Rounding |
------------------------------------------|
   0  |      0 ms    |    0 ms |    0 ms  |
   1  |     60 ms    |   31 ms |   45 ms  |
   2  |    120 ms    |   62 ms |   75 ms  |
   3  |    180 ms    |   93 ms |  105 ms  |
   4  |    240 ms    |  124 ms |  135 ms  |
   5  |    300 ms    |  155 ms |  165 ms  |
   6  |    360 ms    |  186 ms |  195 ms  |
   7  |    420 ms    |  217 ms |  225 ms  |
   8  |    480 ms    |  248 ms |  255 ms  |
   9  |    540 ms    |  279 ms |  285 ms  |
  10  |    600 ms    |  310 ms |  315 ms  |
  11  |    660 ms    |  341 ms |  345 ms  |
  12  |    720 ms    |  372 ms |  375 ms  |
  13  |    780 ms    |  403 ms |  405 ms  |
  14  |    840 ms    |  434 ms |  435 ms  |
  15  |    900 ms    |  465 ms |  465 ms  |
  16  |    930 ms    |  496 ms |  495 ms  |
  17  |    990 ms    |  527 ms |  525 ms  |
  18  |   1050 ms    |  558 ms |  555 ms  |
  19  |   1110 ms    |  589 ms |  585 ms  |
  20  |   1170 ms    |  620 ms |  615 ms  |
  21  |   1230 ms    |  651 ms |  645 ms  |
  22  |   1290 ms    |  682 ms |  675 ms  |
  23  |   1350 ms    |  713 ms |  705 ms  |
  24  |   1410 ms    |  744 ms |  735 ms  |
  25  |   1470 ms    |  775 ms |  765 ms  |
  26  |   1530 ms    |  806 ms |  795 ms  |
  27  |   1590 ms    |  837 ms |  825 ms  |
  28  |   1650 ms    |  868 ms |  855 ms  |
  29  |   1710 ms    |  899 ms |  885 ms  |
  30  |   1770 ms    |  930 ms |  900 ms  |
  31  |   1830 ms    |  961 ms |  945 ms  |
  32  |   1860 ms    |  992 ms |  975 ms  |
  33  |   1920 ms    | 1023 ms | 1005 ms  |
  34  |   1980 ms    | 1054 ms | 1035 ms  |
  35  |   2040 ms    | 1085 ms | 1065 ms  |
  36  |   2100 ms    | 1116 ms | 1095 ms  |
  37  |   2160 ms    | 1147 ms | 1125 ms  |
  38  |   2220 ms    | 1178 ms | 1155 ms  |
  39  |   2280 ms    | 1209 ms | 1185 ms  |
  40  |   2340 ms    | 1240 ms | 1215 ms  |
  41  |   2400 ms    | 1271 ms | 1245 ms  |
  42  |   2460 ms    | 1302 ms | 1275 ms  |
  43  |   2520 ms    | 1333 ms | 1305 ms  |
  44  |   2580 ms    | 1364 ms | 1335 ms  |
  45  |   2640 ms    | 1395 ms | 1365 ms  |
  46  |   2700 ms    | 1426 ms | 1395 ms  |
  47  |   2760 ms    | 1457 ms | 1425 ms  |
  48  |   2790 ms    | 1488 ms | 1455 ms  |
  49  |   2850 ms    | 1519 ms | 1485 ms  |
  50  |   2910 ms    | 1550 ms | 1515 ms  |
  51  |   2970 ms    | 1581 ms | 1545 ms  |
  52  |   3030 ms    | 1612 ms | 1575 ms  |
  53  |   3090 ms    | 1643 ms | 1605 ms  |
  54  |   3150 ms    | 1674 ms | 1635 ms  |
  55  |   3210 ms    | 1705 ms | 1665 ms  |
  56  |   3270 ms    | 1736 ms | 1695 ms  |
  57  |   3330 ms    | 1767 ms | 1725 ms  |
  58  |   3390 ms    | 1798 ms | 1755 ms  |
  59  |   3450 ms    | 1829 ms | 1785 ms  |
  60  |   3510 ms    | 1860 ms | 1800 ms  |
  61  |   3570 ms    | 1891 ms | 1845 ms  |
  62  |   3630 ms    | 1922 ms | 1875 ms  |
```

> At 30 "This PR" uses the 930 ms "state" which should be used only on the next frame. So it will be one frame earlier and this off by one issue is accumulated. At the very end it's already off by two.

I hope this table above illustrates the issue better than the one in the previous comment. There's nothing off about the timings in this PR. The ones with something off are the other two columns.

The way I see it, if I as a user have set aside enough resources to be able to refresh my display every 30 ms, I'd expect to be able to play an animation that needs to be refreshed every 31/32/33... ms without any hiccups.

That is what this PR does. It makes it so that if you have an animation that does not update on every refresh period, that animation is updated at the time it needs, rather than waiting until the next refresh step to update it. I hope that makes it clearer.

**Comment by kisvegabor** [comment]
In "Current code" the step is 60 in your table. 

It's still not entirely clear in my mind. Ideally it should work well out of the box without any user configs or consideration. Based on your tables started to calculate a concrete example. 

Let's say the animation's value is changing from 0 to 25 in 775 ms, so change 1 in every 31 ms.

### Ideally
```
Frame | Time     | Value |
-------------------------|
   0  | 0 ms     |   0   |
   1  | 31 ms    |   1   |
   2  | 62 ms    |   2   |
   3  | 93 ms    |   3   |
   4  | 124 ms   |   4   |
   5  | 155 ms   |   5   |
   6  | 186 ms   |   6   |
   7  | 217 ms   |   7   |
   8  | 248 ms   |   8   |
   9  | 279 ms   |   9   |
  10  | 310 ms   |   10   |
  11  | 341 ms   |   11   |
  12  | 372 ms   |   12   |
  13  | 403 ms   |   13   |
  14  | 434 ms   |   14   |
  15  | 465 ms   |   15   |
  16  | 496 ms   |   16   |
  17  | 527 ms   |   17   |
  18  | 558 ms   |   18   |
  19  | 589 ms   |   19   |
  20  | 620 ms   |   20   |
  21  | 651 ms   |   21   |
  22  | 682 ms   |   22   |
  23  | 713 ms   |   23   |
  24  | 744 ms   |   24   |
  25  | 775 ms   |   25   |
```

Our time step is 30 instead of 31 but still want the values changing as evenly as possible.

### Current
Super ugly jitter around frame 10 and 20. In total there were 5 jittering frames. 
```
Frame | Assumed Time | Value |
-------------------------|
   0  | 0 ms     |   0   |
   1  | 30 ms    |   0   |   # Jitter, two 0
   2  | 60 ms    |   1   |
   3  | 90 ms    |   2   |
   4  | 120 ms   |   3   |
   5  | 150 ms   |   4   |
   6  | 180 ms   |   5   |
   7  | 210 ms   |   6   |
   8  | 250 ms   |   7   |
   9  | 280 ms   |   8   |
  10  | 310 ms   |  10   | # Jitter, 9 skipped
  11  | 340 ms   |  10   | # Jitter, two 10
  12  | 370 ms   |  11   |
  13  | 400 ms   |  12   |
  14  | 430 ms   |  13   |
  15  | 460 ms   |  14   |
  16  | 490 ms   |  15   |
  17  | 520 ms   |  16   |
  18  | 560 ms   |  17   |
  19  | 590 ms   |  18   |
  20  | 620 ms   |  20   | # Jitter, 19 skipped
  21  | 650 ms   |  20   | # Jitter, two 20
  22  | 680 ms   |  21   |
  23  | 710 ms   |  22   |
  24  | 740 ms   |  23   |
  25  | 770 ms   |  24   |
  26  | 775 ms   |  25   | # Out of time, use the end value directly
```

### Rounding
There is only one jitter.
```
Frame | Assumed Time | Value |
-------------------------|
   0  | 0 ms     |   0   |
   1  | 45 ms    |   1   |   # No change on 30, use 45
   2  | 75 ms    |   2   |   # No change on 60, use 75
   3  | 105 ms   |   3   |
   4  | 135 ms   |   4   |
   5  | 165 ms   |   5   |
   6  | 195 ms   |   6   |
   7  | 225 ms   |   7   |
   8  | 255 ms   |   8   |
   9  | 285 ms   |   9   |
  10  | 315 ms   |  10   | 
  11  | 345 ms   |  11   | 
  12  | 375 ms   |  12   |
  13  | 405 ms   |  13   |
  14  | 435 ms   |  14   |
  15  | 465 ms   |  15   | # Important point: the rounded time is the same as the ideal
  16  | 480 ms   |  15   | # Jitter: There is no change either on 480 or 495 (the error is larger then 15, so we can't round up that  much)
  17  | 510 ms   |  16   | # No rounding, 510 already means a change 
  18  | 540 ms   |  17   | 
  19  | 570 ms   |  18   |
  20  | 600 ms   |  19   | 
  21  | 650 ms   |  20   | 
  22  | 680 ms   |  21   |
  23  | 710 ms   |  22   |
  24  | 740 ms   |  23   |
  25  | 770 ms   |  24   | 
  26  | 775 ms   |  25   | # Out of time, use the end value directly
```

Please add the numbers of your version for this example in this format so that we can clearly see the difference.

**Pull request closed without merging**
