### PR TITLE
fix(lv_hal_indev): update lv_indev_drv_update to free the read_timer

### PR DESCRIPTION
**Pull request by geert-KLA-BE**
The read timer was not freed and recreated. The display was also not checked to be NULL.

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Looks good, thanks. 
Just please run code-format.py from the scripts folder.

**Comment by geert-KLA-BE** [comment]
Is it possible to run this on windows? Since that is my dev. environment.

**Comment by kisvegabor** [comment]
Yes, astyle can be installed on Windows too, but it seems you managed to run it :slightly_smiling_face: 

Thank you, merging.

**Comment by geert-KLA-BE** [comment]
I did it manually still :).
You are welcome.

**Comment by embeddedt** [comment]
I suppose I could have lvgl-bot open a PR to the contributor's fork with the diff applied... but that could get spammy if they keep making commits and it opens a new PR for each one.

**Comment by kisvegabor** [comment]
Can't the bot just push a "format" commit? We squash the commits of PRs anyway so it won't ass any noise.

**Comment by embeddedt** [comment]
I suppose it could... but:

* I'm not sure I like the idea of pushing to contributors' repositories without them expecting it, especially for those who just use their `master` branch instead of making a dedicated branch for the change.
* If they don't force push, there could end up being multiple `style(format) fix formatting` commits every time they apply a review comment, if the formatting is incorrect again. It would clutter the commit history for those who split their PR into incremental commits. Although, they end up having to make a commit like that manually, so perhaps this point is moot.

**Comment by kisvegabor** [comment]
I think it's true for both points that either the contributor or the bot needs to add the "format" commit. It's really might look intrusive to make the bot commit directly to the master branch but IMO it's an acceptable discomfort. In the end, the PR will the squashed anyway so when he updates again the history will be clean again.

**Comment by embeddedt** [comment]
I had another idea: how about pushing the commit if the contributor writes "@lvgl-bot format"? It's less intrusive and still very intuitive. We can add a note about it in the PR checklist template.

**Comment by kisvegabor** [comment]
Ohh, it would be amazing!

**Pull request merged**
