### PR TITLE
Break long words immediately if word is longer than wrap width.

### PR DESCRIPTION
**Pull request by BrianPugh**
This changes the break logic for words that are longer than the container width.

For example (assuming default break characters):

Old logic:
```
+----------------------+
|This is an example of |
|a sentence containing |
|the word              |
|supercalifragilisticex|
|pialidocious          |
+----------------------+
```
New Logic:
```
+----------------------+
|This is an example of |
|a sentence containing |
|the word supercalifrag|
|ilisticexpialidocious |
+----------------------+
```

I've only ran the new logic through a few naive tests, so please give it a try. The code is mostly the same as before, it just looks ahead for the next line break and sees if the width is greater than the `max_width` specified.

Downsides: `lv_txt_get_next_line()` is now a little bit more expensive since it has to look further into the string.

### CODE REVIEW

**Comment by BrianPugh** [comment]
writing up more elegant (and efficient code) right now to mitigate downsides.

**Comment by BrianPugh** [comment]
Ok, I'm actually a bit stumped now. My code isn't working exaclty as expected because of spaces between characters. Currently, it seems the text wrapping code does not account for this (`lv_font_get_width()` is only the width of the glyph). Unfortunately, character spacing is part of styles and not passed to these functions.

I think i have my other bugs figured out (not yet commited), but this is sort of stumping. @kisvegabor what do you think the best way to proceed?

**Comment by BrianPugh** [comment]
Ok I was just tired last night, didn't see that `letter_space` was passed in. This is now ready to merge. I made it as efficient as possible.

How this is currently slower or more resource hungry than the old implementation:

-  Requires one additional variable `w_since_last_break` during string transversal that is *only* updated upon break character. Minimal Overhead.

- Continues transversing string after `max_width` has been reached until a break character is found or `max_width` since the last break character has been reached. For typical use case, this is only a few extra characters.

Overall there is a very minimal performance penalty.

**Comment by BrianPugh** [comment]
Additional checks could be put in to set a minimum length for the first breakpoint (like 4 characters). Do we want to do this?

**Comment by embeddedt** [comment]
@BrianPugh 

> Additional checks could be put in to set a minimum length for the first breakpoint (like 4 characters). Do we want to do this?

What would the memory/performance impact of those additional checks be?

**Comment by BrianPugh** [comment]
Performance impact would be near 0. I'll add some more code this evening. I think a reasonable cutoff would be 3. This is to just avoid something that looks like:
```
+----------------------+
|This is an example of |
|a sentence containing |
|the word filllllerrr s|
|upercalifragilisticexp|
|ialidocious           |
+----------------------+
```
If set to 3, it would look like:
```
+----------------------+
|This is an example of |
|a sentence containing |
|the word filllllerr   |
|supercalifragilisticex|
|pialidocious          |
+----------------------+
```
With the following being the first instance of a break:
```
+----------------------+
|This is an example of |
|a sentence containing |
|the word filllller sup|
|ercalifragilisticexpia|
|lidocious             |
+----------------------+
```

**Comment by embeddedt** [comment]
@BrianPugh I see no problem with adding it then; looks great!

**Comment by BrianPugh** [comment]
Added the feature described [above](https://github.com/littlevgl/lvgl/pull/703#issuecomment-451576773)

Currently the length is defined as 3, mimicking the bottom example of above.

Ready to merge on my end.

**Review by embeddedt — APPROVED** [review]
:+1:

**Comment by kisvegabor** [comment]
Sorry for not responding so far. I can immerse into it on the weekend to see how it works.

**Comment by kisvegabor** [comment]
Sorry for the noise in commits. 

I think I found a more simple way to achieve this. Or have I missed something?
See: https://github.com/littlevgl/lvgl/pull/703/commits/f6a46578fdcef47059e68ee436659dcffabdc7a5

**Comment by kisvegabor** [comment]
I see! It's really something different. I removed my last commit and tested it with `lv_test_kb_1()` and found a minor issue. The last character is out of the box.
 
txt_len

**Comment by BrianPugh** [comment]
alright, investigating this, the PR commits look all sort of messed up, so I'm going to rebranch off of ab1a9b41e6b0428a89dbe94648d6dfb2ab37441d in hopes of cleaning this up.

**Pull request closed without merging**
