### PR TITLE
add some difference precision and Change sin table to intger

### PR DESCRIPTION
**Pull request by Leo2442926161**
add some difference precision and Change sin table to intger

### CODE REVIEW

**Comment by kisvegabor** [comment]
What is the unit of `angle` in `lv_trigo_sinByLeo`? 0.1 degree?

**Comment by Leo2442926161** [comment]
the angle must  be amplified 10 fold before pass to lv_trigo_sinByLeo

**Comment by kisvegabor** [comment]
It'd be more consistent to expect the angles according to the resolution. So 
- 1 deg. resolution: for 32 deg. pass 32 deg. 
- 1/2 deg. resolution: for 32 deg. pass 64 deg. 

There can be a define like `LV_TRIGO_UPSCALE  1  or 2 or 3 or 4` and then `lv_trigo_sin(32 << LV_TRIGO_UPSCALE)`

One more thing: to save space please only the 1/4 of the sin wave (0..90 degree) and mirror this part for other degrees. The original implementation worked like this.

I've just realized that this improvement will be required for image rotation too because it also requires more precise trigonometrical functions.

**Comment by Leo2442926161** [comment]
> It'd be more consistent to expect the angles according to the resolution. So
> 
> * 1 deg. resolution: for 32 deg. pass 32 deg.
> * 1/2 deg. resolution: for 32 deg. pass 64 deg.
> 
> There can be a define like `LV_TRIGO_UPSCALE 1 or 2 or 3 or 4` and then `lv_trigo_sin(32 << LV_TRIGO_UPSCALE)`

**sorry, I don't get it.**


> One more thing: to save space please only the 1/4 of the sin wave (0..90 degree) and mirror this part for other degrees. The original implementation worked like this.

**>But it will running fast if you don't save spae, thanks anyway,  I add a macro that contorl the 
operate, like below picture:**

image

**Comment by embeddedt** [comment]
@Leo2442926161 I think you need to do more than just clip the array size. You also have to add code that will mirror the values properly for other degrees.

**Comment by kisvegabor** [comment]
> There can be a define like `LV_TRIGO_UPSCALE 1 or 2 or 3 or 4` and then `lv_trigo_sin(32 << LV_TRIGO_UPSCALE)`

I mean instead of `* 10` we can use the same upsacle ratio as the extra precision of the `sin` table. So if you have 1/2 degreee precision in `sin` you can pass the degree to `lv_math_sin()` in 1/2 degree unit too. For example in case of 1/2 degree precision `lv_trigo_sin(15)` means `sin(7.5°)`




> I think you need to do more than just clip the array size. You also have to add code that will mirror the values properly for other degrees.

@Leo2442926161 Have a look at this https://github.com/littlevgl/lvgl/blob/master/lv_misc/lv_math.c#L114

**Comment by Leo2442926161** [comment]
> @Leo2442926161 I think you need to do more than just clip the array size. You also have to add code that will mirror the values properly for other degrees.

 **I did**

**Comment by Leo2442926161** [comment]
> > There can be a define like `LV_TRIGO_UPSCALE 1 or 2 or 3 or 4` and then `lv_trigo_sin(32 << LV_TRIGO_UPSCALE)`
> 
> I mean instead of `* 10` we can use the same upsacle ratio as the extra precision of the `sin` table. So if you have 1/2 degreee precision in `sin` you can pass the degree to `lv_math_sin()` in 1/2 degree unit too. For example in case of 1/2 degree precision `lv_trigo_sin(15)` means `sin(7.5°)`
> 
> > I think you need to do more than just clip the array size. You also have to add code that will mirror the values properly for other degrees.
> 
> @Leo2442926161 Have a look at this https://github.com/littlevgl/lvgl/blob/master/lv_misc/lv_math.c#L114

Maybe I know what you mean,  the reason why the degree amplified 10 fold, because we use integer calculate,  For example in case of 1/2 degree precision `lv_trigo_sin(15)` means `sin(7°)`, but if the degree was amplified 10 fold, the lv_trigo_sin(150) will be result in sin(75).

**Comment by kisvegabor** [comment]
> Maybe I know what you mean, the reason why the degree amplified 10 fold, because we use integer calculate, For example in case of 1/2 degree precision `lv_trigo_sin(15)` means `sin(7°)`, but if the degree was amplified 10 fold, the lv_trigo_sin(150) will be result in sin(75).

The "10 folds" approach is also reasonable but `lv_trigo_sin` is not for the user directly. So we should choose the less user-friendly but faster way.   
 Using `LV_TRIGO_UPSCALE` you can consider a circle to `360 << LV_TRIGO_UPSCALE`  degrees and divide it into equal parts in `gauge` drawer. This way no extra conversion is required.

**Pull request closed without merging**
