### PR TITLE
feat(freetype): add outline output to support draw vector font

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

1. Reconstruct the freetype porting architecture and divide different cache types into image, sbit, and outline for separate management.
2. Implement font outline output and adapt to GPU with vector rendering.
3. Add face_id reference counting to fix cache waste problem.
4. Re-adjust the optimal default value of freetype cache, eliminating the need for secondary configuration.
5. Add lv_rb, lv_lru_rb data structures to manage cache.

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [x] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [x] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [x] Use typed pointers instead of `void *` pointers
- [x] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [x] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [x] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [x] `struct`s should be used via an API and not modified directly via their elements.
- [x] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [x] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [x] Arguments must be named in H files too.
- [x] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Looks interesting! I haven't checked the freetype part yet, but I would like to discuss the cache part first. Ideally we should have central cache manager in LVGL. (`lv_lru` vs `lv_cache`). 

Would it be possible to `lv_cache`? if not, how shall we improve it? 

My vision if for v9 we should remove `lv_lru` and keep only `lv_cache`.

**Comment by FASTSHIFT** [comment]
> Looks interesting! I haven't checked the freetype part yet, but I would like to discuss the cache part first. Ideally we should have central cache manager in LVGL. (`lv_lru` vs `lv_cache`).
> 
> Would it be possible to `lv_cache`? if not, how shall we improve it?
> 
> My vision if for v9 we should remove `lv_lru` and keep only `lv_cache`.

Unified cache interface is a direction. We can implement replaceable cache search and clear algorithm backends, such as aging algorithm or LRU algorithm. cc @W-Mai

**Comment by W-Mai** [comment]
Different modules may use different cache strategies. The current cache manager seems to be able to use only one cache strategy globally. I prefer each module to use its own cache manager. We can use different internal cache policies, but expose the same search interface.

I think the design of lv_lru_rb is quite reasonable.

```cpp
lv_lru_rb_t * lv_lru_rb_create(size_t node_size, size_t max_size, lv_lru_rb_compare_cb_t compare_cb,
                               lv_lru_rb_alloc_cb_t alloc_cb, lv_lru_rb_free_cb_t free_cb);
void lv_lru_rb_destroy(lv_lru_rb_t * lru, void * user_data);
void * lv_lru_rb_get(lv_lru_rb_t * lru, const void * key, void * user_data);
void lv_lru_rb_reset(lv_lru_rb_t * lru, const void * key, void * user_data);
void lv_lru_rb_clear(lv_lru_rb_t * lru, void * user_data);
void lv_lru_rb_set_max_size(lv_lru_rb_t * lru, size_t max_size, void * user_data);
size_t lv_lru_rb_get_max_size(lv_lru_rb_t * lru, void * user_data);
size_t lv_lru_rb_get_size(lv_lru_rb_t * lru, void * user_data);
size_t lv_lru_rb_get_free_size(lv_lru_rb_t * lru, void * user_data);
void lv_lru_rb_set_compare_cb(lv_lru_rb_t * lru, lv_lru_rb_compare_cb_t compare_cb, void * user_data);
void lv_lru_rb_set_alloc_cb(lv_lru_rb_t * lru, lv_lru_rb_alloc_cb_t alloc_cb, void * user_data);
void lv_lru_rb_set_free_cb(lv_lru_rb_t * lru, lv_lru_rb_free_cb_t free_cb, void * user_data);
```

It contains hook of the allocation release of cache nodes and the compare, as well as the built-in efficient search algorithm.

**Comment by kisvegabor** [comment]
So the cache shouldn't be a single global entity, but more dynamic and each module can create it's own cache pool with it's own strategies. 

What modules can we identify now, which might use there own caching? I have these in mind:
- Image decoding: one module for all images?
- FreeType and TinyTTF: are fonts the same module or is it two separate caches?
- vector caching?
- later: widget caching
- later: texture caching for OpenGL or SDL

**Comment by W-Mai** [comment]
> So the cache shouldn't be a single global entity, but more dynamic and each module can create it's own cache pool with it's own strategies.
> 
> What modules can we identify now, which might use there own caching? I have these in mind:
> 
> * Image decoding: one module for all images?
> * FreeType and TinyTTF: are fonts the same module or is it two separate caches?
> * vector caching?
> * later: widget caching
> * later: texture caching for OpenGL or SDL

Great!

I think this is all I can and can't think of.

My answer for each question is `true`😁

As for freetype and tinyttf, at present, the `two` should be more suitable, because `freetype` and `tinyttf` may use different context information to generate glyph information.

**Comment by kisvegabor** [comment]
So we should come up with a cache manager which is not global but can work with multiple "cache objects". I think we can and should do it. Mixing the PNG image cache (large buffers) with TinyTTF cache (small buffers) are really messy and unpredictable.

However, I hope we can find a single built-in cache manager policy which can serve all the use cases well. I'm absolutely open to use the rb tree for that.

**Comment by FASTSHIFT** [comment]
Not stale.

**Comment by W-Mai** [comment]
https://github.com/lvgl/lvgl/pull/4585
https://github.com/lvgl/lvgl/pull/4670

How about merging these three prs first? They have been hanging here for a long time, and I have commented on the design of the new cache in [ISSUE](https://github.com/lvgl/lvgl/issues/4835). I think we can merge these codes first, and then provide a new pr to adapt the existing code.

If it doesn't fit, the changes to these prs will be very bad (lot/huge/awful) in the future.

@kisvegabor  What do you think?

**Comment by kisvegabor** [comment]
Thank you!

**Comment by kisvegabor** [comment]
Thanks!

**Pull request merged**
