### PR TITLE
feat(property): allow to get property from specified class

### PR DESCRIPTION
**Pull request by XuNeo**
### Description of the feature or fix

So we can have fine control of where the property can come from.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Please add at least one basic test for it. 

What is the actual use case for this feature?

**Comment by XuNeo** [comment]
I have explained in this issue https://github.com/XuNeo/luavgl/issues/61
Not sure if this is the best solution. The property value only support limited types, while LVGL sometimes uses more than one parameters for setter, makes it difficult to support in property API.


I'll add a test for it.

**Comment by kisvegabor** [comment]
I see! However align in not a single property but just a helper to set 3 properties at once:
- align
- x
- y

Ideally the API should be so clean that all setters have only a single parameter. Anything other than that shouldn't be considered a basic setter, but a helper. 
I know we are not quite there, but should go into that direction.

**Review by FASTSHIFT — APPROVED** [review]

**Comment by XuNeo** [comment]
> I know we are not quite there, but should go into that direction.

Yes. I agree.

The flexibility introduced in this PR allows the bindings to override the default property API, which is useful for handling more complex scenarios.

**Comment by XuNeo** [comment]
Merged in https://github.com/lvgl/lvgl/pull/6697
Close this one.

**Pull request closed without merging**
