### PR TITLE
added MP versions of tiny_ttf examples

### PR DESCRIPTION
**Pull request by uraich**
### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation
added MP versions of tiny_ttf example

### CODE REVIEW

**Comment by uraich** [comment]
Need to enable LV_USE_TINY_TTF and LV_TINY_TTF_FILE_SUPPORT and re-create lv_bindings

**Comment by amirgon** [comment]
@embeddedt could you try to restart the CI here?  
These failures should be fixed by https://github.com/lvgl/lvgl/pull/3716 and https://github.com/lvgl/lv_micropython/pull/61.

**Comment by amirgon** [comment]
> These failures should be fixed by #3716 and [lvgl/lv_micropython#61](https://github.com/lvgl/lv_micropython/pull/61).

Probably needs to be rebased.

**Comment by kisvegabor** [comment]
@codewitch-honey-crisis is just added cache support for tiny_ttf and GC root is not required anymore. I restarted the test.

**Comment by amirgon** [comment]
Please rebase this branch on latest LVGL

**Comment by kisvegabor** [comment]
Rebased

**Comment by amirgon** [comment]
@uraich why did you close it?  
Was it already merged in some other PR?

**Comment by uraich** [comment]
@amirgon I thought it was merged but I should check. Maybe I better reopen it for the moment.

**Comment by kisvegabor** [comment]
Based on [this comment](https://github.com/lvgl/lvgl/issues/3535#issuecomment-1292451714) I merge it.

**Pull request merged**
