### PR TITLE
fix: conflict ALIGN

### PR DESCRIPTION
**Pull request by mysterywolf**
### Description of the feature or fix

ALIGN is a common name, so that easily conflict with other components

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
cc @X-Ryl669

**Comment by X-Ryl669** [comment]
Sorry I've missed this one. I'll change the macro name in that case so it doesn't pollute.

**Comment by kisvegabor** [comment]
@X-Ryl669 So will you send an other PR?

**Comment by X-Ryl669** [comment]
I'll include it in #3294 if you don't mind. It's only few lines here.

**Comment by kisvegabor** [comment]
Ok, for me.

**Comment by mysterywolf** [comment]
Thank you. I will close this PR.

**Comment by kisvegabor** [comment]
I merge this PR as temporary fix to the problem.

**Comment by mysterywolf** [comment]
Thank you

**Pull request merged**
