### PR TITLE
fix(roller): remove redundant logic in draw selected

### LINKED ISSUE #6070: LV Roller text is not centered.
### LVGL version

9.1.0

### What happened?

image

It was fixed here:
https://github.com/lvgl/lvgl/commit/708272c37cacc190e327373f1972dadccbf137e9

However in the LVGL 9.1.0 version it points to LV_PART_MAIN instead of LV_PART_SELECTED as in the issue 3 years ago.
I'm not sure whats the right fix but i leave all the data i can.

With that changed sometimes it looks ok, other times no:
image

### How to reproduce?

https://github.com/lvgl/lvgl/blob/af642572aabbb7a882b7926d78e62c04b967df9c/examples/widgets/roller/lv_example_roller_2.c

Even in the examples is looking wrong.

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

Fixes #6070

See issues #6070 and #6066 for why this logic is redundant.

This is a master branch PR. I also opened a v8.4 PR  #6082

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you Liam! 

Please add `fixes #6070, #6066` in your first comment to let GitHub automatically close the issues when the PR is merged.

Please also add some simple screen shot tests to be sure that this bug won't come bask again.

**Comment by liamHowatt** [comment]
While creating the test, I found out that this is not the fix. I tried a few different things but I'm having some difficulties getting something to work for all `MAIN`/`SELECTED` font height ratios. You can see this line I added seems to work for the large `SELETED` font test case on the right in the image but not the `MAIN`==`SELECTED` font size on the left. I feel like I'd have to rewrite it to grasp everything going on in these few lines of code.

https://github.com/lvgl/lvgl/blob/f708a39094638082afa3e2b3830c1fcd548c4468/src/widgets/roller/lv_roller.c#L487

**Comment by kisvegabor** [comment]
I think I could fix it. Could you try with this patch (applied on `master`)?

The `//CHECK THIS` lines are the important one. The rest is just minor refactoring. 
```diff
diff --git a/src/widgets/roller/lv_roller.c b/src/widgets/roller/lv_roller.c
index 4941ff312..ba3f1e0d6 100644
--- a/src/widgets/roller/lv_roller.c
+++ b/src/widgets/roller/lv_roller.c
@@ -321,11 +321,10 @@ static void lv_roller_event(const lv_obj_class_t * class_p, lv_event_t * e)
         lv_indev_t * indev = lv_indev_active();
         lv_point_t p;
         lv_indev_get_vect(indev, &p);
-
         transform_vect_recursive(obj, &p);
         if(p.y) {
             lv_obj_t * label = get_label(obj);
-            lv_obj_set_y(label, lv_obj_get_y(label) + p.y);
+            lv_obj_set_y(label, lv_obj_get_y_aligned(label) + p.y);
             roller->moved = 1;
         }
     }
@@ -463,25 +462,29 @@ static void draw_main(lv_event_t * e)
             lv_obj_t * label = get_label(obj);
 
             /*Get the size of the "selected text"*/
-            lv_point_t res_p;
-            lv_text_get_size(&res_p, lv_label_get_text(label), label_dsc.font, label_dsc.letter_space, label_dsc.line_space,
+            lv_point_t label_sel_size;
+            lv_text_get_size(&label_sel_size, lv_label_get_text(label), label_dsc.font, label_dsc.letter_space, label_dsc.line_space,
                              lv_obj_get_width(obj), LV_TEXT_FLAG_EXPAND);
 
             /*Move the selected label proportionally with the background label*/
             int32_t roller_h = lv_obj_get_height(obj);
             int32_t label_y_prop = label->coords.y1 - (roller_h / 2 +
                                                        obj->coords.y1); /*label offset from the middle line of the roller*/
-            label_y_prop = (label_y_prop * 16384) / lv_obj_get_height(
-                               label); /*Proportional position from the middle line (upscaled by << 14)*/
+
+            /*Proportional position from the middle line (upscaled by << 14)*/
+            label_y_prop = (label_y_prop << 14) / lv_obj_get_height(label);
 
             /*Apply a correction with different line heights*/
             const lv_font_t * normal_label_font = lv_obj_get_style_text_font(obj, LV_PART_MAIN);
-            int32_t corr = (label_dsc.font->line_height - normal_label_font->line_height) / 2;
+
+            /*We don't want the selected label start and end exactly where the normal label is as
+             *a larger font won't centered on selected area.*/
+            int32_t corr = (label_dsc.font->line_height - normal_label_font->line_height) / 4; //CHECK THIS
 
             /*Apply the proportional position to the selected text*/
-            res_p.y -= corr;
+            label_sel_size.y -= 2 * corr;  //CHECK THIS
             int32_t label_sel_y = roller_h / 2 + obj->coords.y1;
-            label_sel_y += (label_y_prop * res_p.y) >> 14;
+            label_sel_y += (label_sel_size.y * label_y_prop) >> 14;
             label_sel_y -= corr;
 
             int32_t bwidth = lv_obj_get_style_border_width(obj, LV_PART_MAIN);
@@ -493,7 +496,7 @@ static void draw_main(lv_event_t * e)
             label_sel_area.x1 = obj->coords.x1 + pleft + bwidth;
             label_sel_area.y1 = label_sel_y;
             label_sel_area.x2 = obj->coords.x2 - pright - bwidth;
-            label_sel_area.y2 = label_sel_area.y1 + res_p.y;
+            label_sel_area.y2 = label_sel_area.y1 + label_sel_size.y;
 
             label_dsc.flag |= LV_TEXT_FLAG_EXPAND;
             const lv_area_t clip_area_ori = layer->_clip_area;
@@ -514,7 +517,6 @@ static void draw_label(lv_event_t * e)
     lv_draw_label_dsc_t label_draw_dsc;
     lv_draw_label_dsc_init(&label_draw_dsc);
     lv_obj_init_draw_label_dsc(roller, LV_PART_MAIN, &label_draw_dsc);
-
     lv_layer_t * layer = lv_event_get_layer(e);
 
     /*If the roller has shadow or outline it has some ext. draw size
@@ -533,7 +535,8 @@ static void draw_label(lv_event_t * e)
     clip2.y1 = label_obj->coords.y1;
     clip2.x2 = label_obj->coords.x2;
     clip2.y2 = sel_area.y1;
-    if(_lv_area_intersect(&clip2, &layer->_clip_area, &clip2)) {
+    if(_lv_area_intersect(&clip2, &layer->_clip_area, &clip2))
+    {
         const lv_area_t clip_area_ori2 = layer->_clip_area;
         layer->_clip_area = clip2;
         label_draw_dsc.text = lv_label_get_text(label_obj);
```

**Comment by liamHowatt** [comment]
It's very close. But still faces some of the same problems. I did try rewriting it but I ended up re-inventing everything that's already there, including `corr` :slightly_smiling_face:, and then I wasn't sure what was missing from getting the final behavior just right. The commit is your changes and the test finished. My "rewrite" is not helpful so I didn't push it. Can you try this example to seek out the leftover discrepancy?

```c
static void timer_cb(lv_timer_t * tim)
{
    lv_obj_t * r = lv_timer_get_user_data(tim);
    if (lv_roller_get_selected(r) == 0) {
        lv_roller_set_selected(r, lv_roller_get_option_count(r) - 1, LV_ANIM_OFF);
    }
    else {
        lv_roller_set_selected(r, 0, LV_ANIM_OFF);
    }
}

static void roller_testing(void)
{
    {
        const char * opts = "0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg\n0@Tg";
        lv_obj_t * r;

        r = lv_roller_create(lv_screen_active());
        lv_obj_set_pos(r, 20, 20);
        lv_roller_set_options(r, opts, LV_ROLLER_MODE_NORMAL);
        lv_obj_set_style_text_font(r, &lv_font_montserrat_8, LV_PART_MAIN);
        lv_obj_set_style_text_font(r, &lv_font_montserrat_36, LV_PART_SELECTED);
        lv_timer_create(timer_cb, 200, r);

        /* this one is okay while the other ones are not */
        r = lv_roller_create(lv_screen_active());
        lv_obj_set_pos(r, 200, 20);
        lv_roller_set_options(r, opts, LV_ROLLER_MODE_NORMAL);
        lv_obj_set_style_text_font(r, &lv_font_montserrat_16, LV_PART_MAIN);
        lv_obj_set_style_text_font(r, &lv_font_montserrat_24, LV_PART_SELECTED);
        lv_timer_create(timer_cb, 200, r);
    }

    /* the below example is BigWhite0's from #6066 */
    {
        static lv_style_t style_sel;
        lv_style_init(&style_sel);
        lv_style_set_text_font(&style_sel, &lv_font_montserrat_22);

        lv_obj_t * r;
        const char * opts = "1\n1\n1\n1\n1\n1\n1\n1\n1\n1";

        r = lv_roller_create(lv_scr_act());
        lv_obj_set_style_text_font(r, &lv_font_montserrat_12, LV_PART_MAIN);
        lv_obj_set_style_text_font(r, &lv_font_montserrat_30, LV_PART_SELECTED);
        lv_roller_set_options(r, opts, LV_ROLLER_MODE_NORMAL);
        lv_obj_set_width(r, 80);
        lv_obj_add_style(r, &style_sel, LV_PART_SELECTED);
        lv_obj_set_style_text_align(r, LV_TEXT_ALIGN_RIGHT, 0);
        // lv_roller_set_selected(r, 8, LV_ANIM_ON);
        lv_obj_set_pos(r, 350, 20);
        lv_obj_set_style_bg_opa(r, LV_OPA_100, LV_PART_MAIN);
        lv_obj_set_style_bg_color(r, lv_color_hex(0xffff00), LV_PART_MAIN);
        lv_obj_set_style_text_line_space(r, 0, LV_PART_MAIN);
        lv_roller_set_visible_row_count(r, 3);

        lv_timer_create(timer_cb, 200, r);
    }
}
```

**Comment by kisvegabor** [comment]
Huh, I think (hope) I could fix it. 

The problem was that when option 0 was selected `label_y_prop` was not `0` but `0.005`. It happened because `label_y_prop` was calculated from the y1 coordinate of the label but we were interested in the middle of the first option. The `0.005` expressed that not the top of the first option is at the middle of the roller, but the middle of the first option,  so there is a half line offset.

So after some error and trial, by subtracting a few things here and there now it's perfectly steady. :relieved:  

Now `label_y_prop` is set in the 0..1 range, which is more straightforward.

**Comment by liamHowatt** [comment]
Fantastic :tada:

**Review by kisvegabor — APPROVED** [review]

**Review by PGNetHun — APPROVED** [review]

**Pull request merged**
