### PR TITLE
Non constant declaration

### PR DESCRIPTION
**Pull request by Zaltora**
I got an error when compilation. I fix the compilation problem but a proper way to initialize this variable is maybe needed. maybe in lv_init ?
You can fix it and close this pull request.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thank you!

What kind of error do you get? I didn't got any error for this.

**Comment by Zaltora** [comment]
```
/opt/esp-dev/esp-open-rtos/lvgl/lvgl/lv_draw/lv_draw_rbasic.c:31:1: error: initializer element is not constant
 static lv_color_t letter_bg_color = LV_COLOR_WHITE;
```

**Comment by Zaltora** [comment]
It is related to this:

```c
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
#if LV_COLOR_DEPTH == 1
#define LV_COLOR_MAKE(r8, g8, b8) ((lv_color_t){(b8 >> 7 | g8 >> 7 | r8 >> 7)})
#elif LV_COLOR_DEPTH == 8
#define LV_COLOR_MAKE(r8, g8, b8) ((lv_color_t){{b8 >> 6, g8 >> 5, r8 >> 5}})
#elif LV_COLOR_DEPTH == 16
#define LV_COLOR_MAKE(r8, g8, b8) ((lv_color_t){{b8 >> 3, g8 >> 2, r8 >> 3}})
#elif LV_COLOR_DEPTH == 24
#define LV_COLOR_MAKE(r8, g8, b8) ((lv_color_t){{b8, g8, r8, 0xff}})            /*Fix 0xff alpha*/
#endif
#else
#if LV_COLOR_DEPTH == 1
#define LV_COLOR_MAKE(r8, g8, b8) ((lv_color_t){(r8 >> 7 | g8 >> 7 | b8 >> 7)})
#elif LV_COLOR_DEPTH == 8
#define LV_COLOR_MAKE(r8, g8, b8) ((lv_color_t){{r8 >> 6, g8 >> 5, b8 >> 5}})
#elif LV_COLOR_DEPTH == 16
#define LV_COLOR_MAKE(r8, g8, b8) ((lv_color_t){{r8 >> 3, g8 >> 2, b8 >> 3}})
#elif LV_COLOR_DEPTH == 24
#define LV_COLOR_MAKE(r8, g8, b8) ((lv_color_t){{0xff, r8, g8, b8}})            /*Fix 0xff alpha*/
#endif
#endif
```
I use  LV_COLOR_DEPTH == 1.

**Comment by kisvegabor** [comment]
Strange, the initializer is a constant. Anyway I merge this to beta. Maybe other will experience it too.

Thank you!

**Comment by Zaltora** [comment]
No problem if this variable is not initialized somewhere ?
It is maybe a gcc bug.

**Comment by kisvegabor** [comment]
It will be initialized when used. So it's fine if we leave it uninitialized here.

**Pull request merged**
