### PR TITLE
changes `lv_lru_free_t` function pointer typedef 

### PR DESCRIPTION
**Pull request by kdschlosser**
changes `lv_lru_free_t` function pointer typedef  to conform to the way the rest of the function pointer typedefs are in LVGL.

The only thing I did not do which you can let me know if it should be done is to change the name of the function pointer to `lv_lru_free_cb_t` so it aligns with the rest of the API

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you! 

> The only thing I did not do which you can let me know if it should be done is to change the name of the function pointer to lv_lru_free_cb_t so it aligns with the rest of the API

Yeah, please add the `_cb` suffix too.

**Comment by kdschlosser** [comment]
done!

**Comment by kisvegabor** [comment]
Merging, thank you!

**Comment by kdschlosser** [comment]
no worries m8

**Pull request merged**
