### PR TITLE
lv_sw_toggle()

### PR DESCRIPTION
**Pull request by BrianPugh**
Function that just toggles the state of a `lv_sw`.

### CODE REVIEW

**Comment by embeddedt** [comment]
@BrianPugh I'm being a little picky but maybe there should be lv_sw_toggle_anim as well for consistency. I can add it tomorrow.

**Comment by BrianPugh** [comment]
I can add it right now, give me a moment.

**Comment by BrianPugh** [comment]
Added! I actually needed that for my project; didn't realize I had to call the anim function; was wondering why my switch animations were not working!

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thank you!

**Pull request merged**
