### PR TITLE
feat(libs): add libjpeg-turbo decoder

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

Added [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo) port to support full JPEG specification.

image

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [x] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [x] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [x] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [x] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [x] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [x] Use typed pointers instead of `void *` pointers
- [x] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [x] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [x] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [x] `struct`s should be used via an API and not modified directly via their elements.
- [x] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [x] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [x] Arguments must be named in H files too.
- [x] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you!

Same here as with libjpg:
- rename LV_USE_JPG and and `lv_jpg_*` to `lv_tjpgd_` (can be done in an other PR)
- add  basic docs page 
- add  at least one screenshot test

**Comment by FASTSHIFT** [comment]
>  rename LV_USE_JPG and and `lv_jpg_*` to `lv_tjpgd_` (can be done in an other PR)

Done https://github.com/lvgl/lvgl/pull/4573

**Comment by FASTSHIFT** [comment]
@kisvegabor 
Can we reuse the PNG/JPEG sample program? Because there is no difference using on the app.

**Comment by FASTSHIFT** [comment]
`LV_USE_JPG` and `LV_USE_JPEG_TURBO` will be enabled at the same time in the testcase. Both of them can decode jpeg files. How to ensure that both can be tested?

**Comment by kisvegabor** [comment]
> Can we reuse PNG/JPEG example? Because there is no difference using on the app.

To match the examples with the exact library, please duplicate the examples. So let's have separate `lv_example_tjpgd_1()` and `lv_example_libjpeg_turbo_1()`

>  LV_USE_JPG and LV_USE_JPEG_TURBO will be enabled at the same time in the testcase. Both of them can decode jpeg files. How to ensure that both can be tested? Use a separate configuration file?

Good question. What about adding a `lv_tjpgd_deinit` and `lv_libjpg_deinit` which would call `lv_image_decoder_delete()`. So in the tests we can remove the other decoder and leave only the being tested one. At the end of test we should add back the removed decoder.

Having an `lv_image_decoder_get_next()` (similar to `lv_indev_get_next()`) would be useful in `lv_<decoder>_deinit()` to avoid storing the pointer of the created decoder.

What do you think?

**Comment by FASTSHIFT** [comment]
> To match the examples with the exact library, please duplicate the examples. So let's have separate lv_example_tjpgd_1() and lv_example_libjpeg_turbo_1()

Done.

> Having an lv_image_decoder_get_next() (similar to lv_indev_get_next()) would be useful in lv_<decoder>_deinit() to avoid storing the pointer of the created decoder.

We may need to rethink the current single-chain decoder framework. We can consider adding some additional string description information when registering the decoder, so that string matching can be used for deletion when deleting. If you use lv_libjpeg_uninit or lv_tjpgd_uninit, the testcase is like this:
```c
void test_tjpgd_1(void)
{
    lv_libjpeg_uninit();

    create_images();

    XXX
}
```
Does it feel weird? It is obviously tjpgd but it calls a deinitialization function of libjpeg, which is very inconvenient to expand. If you use string method:
```c
void test_tjpgd_1(void)
{
    lv_image_decoder_remove("jpg");
    lv_tjpgd_init();

    create_images();

    XXX
}
```
it is more intuitive and ensures that the decoder chain is clean.

**Comment by kisvegabor** [comment]
> lv_image_decoder_remove("jpg");

Would it remove both JPG decoders?

**Comment by FASTSHIFT** [comment]
> > lv_image_decoder_remove("jpg");
> 
> Would it remove both JPG decoders?

Yes, It will remove all codecs for jpg.

**Comment by kisvegabor** [comment]
I think in normal use case removing decoders is not required, so I wouldn't introduce a more complex API with names for it.  I would rather accept that the tests are a little but more ugly.

**Comment by FASTSHIFT** [comment]
> I think in normal use case removing decoders is not required, so I wouldn't introduce a more complex API with names for it. I would rather accept that the tests are a little bit more ugly.

OK, Let’s merge these PRs first:
https://github.com/lvgl/lvgl/pull/4577
https://github.com/lvgl/lvgl/pull/4581

**Comment by kisvegabor** [comment]
Looks good! Probably ou need to rebase it on master to fix the CI error.

**Comment by FASTSHIFT** [comment]
The armv6 platform does not seem to support libjpeg-turbo?

```sh
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindJPEG.cmake:100 (find_package_handle_standard_args)
  CMakeLists.txt:180 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/runner/work/lvgl/lvgl/tests/build_test_sysheap/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/home/runner/work/lvgl/lvgl/tests/main.py", line 180, in <module>
    build_tests(options_name, build_type, args.clean)
  File "/home/runner/work/lvgl/lvgl/tests/main.py", line 87, in build_tests
    subprocess.check_call(['cmake', '-DCMAKE_BUILD_TYPE=%s' % build_type,
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Debug', '-DOPTIONS_TEST_SYSHEAP=1', '..']' returned non-zero exit status 1.
Error: The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2.1.1/src/run-on-arch.sh' failed with exit code 1
```

**Comment by kisvegabor** [comment]
I think the problem is that the `install-prerequisites.sh` is not running on these ARM tests. 
This is the AMD part:
 https://github.com/lvgl/lvgl/blob/7a306da303814423f0475751c0377011b488a236/.github/workflows/ccpp.yml#L35-L36

I think we need to add this install part here:
https://github.com/lvgl/lvgl/blob/7a306da303814423f0475751c0377011b488a236/.github/workflows/ccpp.yml#L58

I'm not sure if it should be added before or after the `Setup cache` section. Could you try it out?

@embeddedt Could you confirm where we need to add `install-prerequisites.sh`? (you find all the relevant information in this comment)

**Comment by kisvegabor** [comment]
Thank you @embeddedt, the Ci is passing now.

@FASTSHIFT The PR looks good to me. Are there anything else missing?

**Comment by FASTSHIFT** [comment]
> Thank you @embeddedt, the Ci is passing now.
> 
> @FASTSHIFT The PR looks good to me. Are there anything else missing?

Nothing else :)

**Comment by kisvegabor** [comment]
Merged, thank you! :slightly_smiling_face:

**Pull request merged**
