### PR TITLE
feat(refr): implement the monitor component

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

- [x] Implemented a common monitor widget.
- [x] Rearranged the creation process and global variables of monitor in `lv_refr`.
- [x] The new frame rate statistics method displays the frame counter and rendering time separately (because in the case of using the VSYNC signal to trigger the rendering, it is not accurate to use the rendering time to calculate the frame rate).
- [x] Support to use LOG to print the frame rate (because rendering the monitor component also takes extra time).

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [x] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [x] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [x] Use typed pointers instead of `void *` pointers
- [x] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [x] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [x] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [x] `struct`s should be used via an API and not modified directly via their elements.
- [x] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [x] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [x] Arguments must be named in H files too.
- [x] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
I like the idea in general but I think it'd make more sense to add into the `others` folder,  and also move the `perf` and `mem` callbacks there to make the `lv_refr.c` cleaner.

It's slightly related, but I think showing the last WARNING and ERROR log messages would be also useful. Maybe we could use the same generic `monitor` to to display the last message. The problem is that it can't show the asserts, as LVGL will stop there. Maybe switching to a character mode in case of an assert ? I'm not sure... Anyway, it's an other topic. :slightly_smiling_face:

**Comment by FASTSHIFT** [comment]
@kisvegabor 
All features have been completed. 
I implemented a frame rate printing function(enable the `LV_USE_PERF_MONITOR_LOG_MDOE`), what do you think?

**Comment by kisvegabor** [comment]
It looks good! I merge it, thank you!

**Comment by kisvegabor** [comment]
Just one thing: we should find a different name for this component. In a UI library the word "monitor" can be easily misunderstood and it conflicts with a former `LV_USE_MONITOR` (SDL window)  component from `lv_drivers`.

To be honest I don't have any good name ideas. Do you have any?

**Comment by FASTSHIFT** [comment]
These are some of the names ChatGPT suggested:

1. PerformanceTracker
2. MetricsCollector
3. ResourceMonitor
4. EfficiencyObserver
5. Speedometer
6. HealthCheck
7. OptimizationInspector
8. CapacityWatcher
9. UtilizationAnalyzer
10. WorkloadProfiler

What about `lv_metrics`?

**Pull request merged**
