### PR TITLE
fix(gc): Iterate the root variables only when they are really used

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

And move cache_temp to gc.h for track the usage.

### Checkpoints
- [X] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@amirgon and @kisvegabor this is the follow up PR for https://github.com/lvgl/lvgl/pull/2081. Please take a look.

**Comment by amirgon** [comment]
Looks good! 👍 
Thanks @xiaoxiang781216 !

**Comment by kisvegabor** [comment]
Wow, that's smart! But IMO a little bit hard to read and debug.

I think allocating a single entry if caching is disabled is simpler but if you both like the current implementation, it's ok for me too.

**Comment by amirgon** [comment]
What happened here?
Why was this closed?

**Comment by xiaoxiang781216** [comment]
I move the change to here: https://github.com/lvgl/lvgl/pull/2102

**Pull request closed without merging**
