### PR TITLE
added x-axis label and x/y axis tick marks with labels, all optional

### PR DESCRIPTION
**Pull request by gjohnson0720**

### CODE REVIEW

**Comment by embeddedt** [comment]
It looks like this code is not driven by a preprocessor macro. Did I miss something?

**Comment by embeddedt** [comment]
@gjohnson0720 Since it "drags in" `sprintf`, you might want to use a macro. However, @kisvegabor  should probably make the final decision.

**Review by embeddedt — DISMISSED** [review]

**Comment by embeddedt** [comment]
Please disregard the approval message; I was trying to get GitHub to stop telling me there were new changes.

**Comment by kisvegabor** [comment]
Hi,

I agree with @embeddedt . We should avoid the use of `sprintf` because it means ~30 kB extra program size which might be important using small systems.

**Comment by kisvegabor** [comment]
I tested the new feature. First of all great work, thank you very much! :+1: 

I used this code to test: 

```c
lv_obj_t * chart1 = lv_chart_create(lv_scr_act(), NULL);
lv_obj_set_size(chart1, 300, 200);
lv_obj_align(chart1, NULL, LV_ALIGN_CENTER, 0, 0);
lv_chart_set_point_count(chart1, 6);
lv_chart_set_div_line_count(chart1, 0, 0);

lv_chart_series_t * dl1_1 = lv_chart_add_series(chart1, LV_COLOR_RED);
dl1_1->points[0] = 0;
dl1_1->points[1] = 25;
dl1_1->points[2] = 0;
dl1_1->points[3] = 50;
dl1_1->points[4] = 0;
dl1_1->points[5] = 75;

/*x axis settings: works well*/
//lv_chart_set_x_ticks(chart1, 4, 100, 200, true, "sec");
//lv_chart_set_x_label(chart1, "Time");

/*y axis settings */
lv_chart_set_y_ticks(chart1, 5, 10, 20, true, "V"); /*Range is not working properly*/
//lv_chart_set_y_label(chart1, "Voltage");        /*Not implemented*/
```

And got this for x:
image

And this for y:
image

1. It seems the range should be [10;20] but it's [2;10]. 
2. For y axis the start and end values not starts at the corner (like they do in case of x). I understand that x and y scale units can overlap eachother on the bottom left corner.
3. To avoide the overlap in the corners what about adding the values outside of the chart?
4. `lv_chart_set_y_label` is not implemented yet. Do you plan to add it as well?
5. In the code I saw lines like `char txt[11 + LV_MATH_MAX(strlens(ext->x_axis.units), strlens(ext->y_axis.units))];` where I don't understand `11` can you explain it  a comment or add define for integers like this?

**Comment by embeddedt** [comment]
@gjohnson0720 It has been 20 days and there was no activity here. Are you still working on this pull request?

**Comment by gjohnson0720** [comment]
Sorry, things have gotten busy and I don't have the time to put in the improvements you guys suggested.  How should I resolve the open PR?

**Pull request closed without merging**
