### PR TITLE
feat(image_decoder): add stride warning

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

Using width to calculate stride will lead to very difficult consistency problems. 
We should remind users to set the correct stride information in the decoder.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by XuNeo — DISMISSED** [review]

**Comment by FASTSHIFT** [comment]
We need to update all image resources inside lvgl, otherwise a large number of warning logs will be generated.

**Comment by kisvegabor** [comment]
For the current demos I suggest adding the stride by hand. It might be complicated to generate the images automatically due to special cases like 
- Set special color format
- We might want to convert one image assets in multiple formats.

**Comment by kisvegabor** [comment]
> We need to update all image resources inside lvgl, otherwise a large number of warning logs will be generated.

Due to this IMO we shall update the strides in the PR too.

**Review by PGNetHun — DISMISSED** [review]

**Comment by kisvegabor** [comment]
What about this?
> We need to update all image resources inside lvgl, otherwise a large number of warning logs will be generated.

**Comment by FASTSHIFT** [comment]
> What about this?
> 
> > We need to update all image resources inside lvgl, otherwise a large number of warning logs will be generated.

I used a script to automate the resource changes: https://github.com/lvgl/lvgl/pull/5653

**Comment by FASTSHIFT** [comment]
Considering that the decoder has not been fully adapted, first reduce the LOG output level.

**Review by PGNetHun — APPROVED** [review]

**Pull request merged**
