### PR TITLE
Break long words immediately if word is longer than wrap width 2

### PR DESCRIPTION
**Pull request by BrianPugh**
Continued discussion of #703 ; separate PR because the original PR commit history got mangled.

Fixed the last character getting cut off in the `lv_test_kb_1()`.

I also added the functionality for long words (but still shorter than the display width, i.e. a single break will definitely solve the word-wrap issue) to break in a prettier place. Best to explain via example:
```
+----------------------+
|This is a test aaabbbc| // words >=12 long are broken
|ccddd                 |
+----------------------+
+----------------------+
|This is test aaabbbcc | // broken early to leave a
|cddd                  | // minimum of 4 trailing letters
+----------------------+

+----------------------+
|This is test123456 aaa| // 3 leading letters is fine
|bbbcccddd             | 
+----------------------+

+----------------------+
|This is test1234567   | // <3 leading letters is not
|aaabbbcccddd          | // this is a >=12 word that is < line_w
+----------------------+
```

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you very much Brian!

I've tested it an still the experience  issue:
txt_len


It seems an extra character is added to the line.

**Comment by BrianPugh** [comment]
Alright, this should fix that last bug. 🤞

**Comment by kisvegabor** [comment]
The bug seems to be fixed! :clap: 

But something is still not perfect :( Look the `j` characters:

kb

**Comment by BrianPugh** [comment]
Thats (more or less) expected behavior, it only looks strange because of the live editing. Here the "j" word hits the 12-character length, so it breaks to have the minimum 4 characters on the next line. As you add more characters, it pushes available characters into the available space in the previous line. Currently there's no real good way to avoid that. A potential solution is to have a special control character at the end of a "live editing" text box indicating a different break rule for the preivous word.

**Comment by kisvegabor** [comment]
Ahh, I see.
I think it would be clearer to see what's going on without the `minimum 4 characters` feature. So IMO it's better to have one character in the next line then break too early. 

I like the other two features:
- deal with only >= 12 characters long words
- break only if at least 3 characters remain in the original line

**Comment by BrianPugh** [comment]
I just fixed an off-by-one error (the post-number of characters was defined as 3, but was breaking at 4;). I also just disabled the post-number of characters by setting `LV_TXT_LINE_BREAK_LONG_POST_MIN_LEN` to 0. Do you think we could expose these in `lv_conf.h`? Different languages/users might have different requirements. For example, in my project I would prefer to have `LV_TXT_LINE_BREAK_LONG_POST_MIN_LEN` set to 4.

**Comment by embeddedt** [comment]
@BrianPugh I think leaving it as a configuration setting is fine, but we should add a note saying that those weird wrapping effects might happen.

**Comment by BrianPugh** [comment]
Should I update the PR to move these defines into `lv_conf.h`? Also if they should be renamed at all.

**Comment by kisvegabor** [comment]
@BrianPugh 
If `LV_TXT_LINE_BREAK_LONG_POST_MIN_LEN    0` is working well then it's fine!

Yes, please move these defines to `lv_conf_templ.h`. The names are fine! :+1:

**Comment by BrianPugh** [comment]
Moved them over, should be good to merge

**Comment by BrianPugh** [comment]
There are longer macros in `lv_conf.h`, but I could get rid of the `_len` suffix on each of them if you want.

**Comment by embeddedt** [comment]
@BrianPugh You don't need the `#ifndef` clauses in `lv_txt.c`; I think it's assumed the user will adjust `lv_conf.h` when they update.

**Comment by BrianPugh** [comment]
I just added them because people might be lazy about updating their `lv_conf.h`, if we don't do this anywhere else in the library or its confusing, i can remove them.

**Comment by kisvegabor** [comment]
I also feel that these defines a little bit long but can't imagine a shorter version. So I think we can leave it.

In `v5.3` [lv_conf_checker.h](https://github.com/littlevgl/lvgl/blob/dev-5.3/lv_conf_checker.h) is introduced which is generated from `lv_conf_templ.h` and has `#ifndef` for every defines. It's included at the end of `lv_conf.h`. However, on a minor version update, the library should work even without updating `lv_conf.h`. So I planned to remove the `#ifndef`s from the `c` files in `v6.0` where the user need to update `lv_conf.h` which uses `lv_conf_checker.h`.

**Comment by kisvegabor** [comment]
So, ready to merge?

**Comment by BrianPugh** [comment]
yup! ready to merge!

**Comment by kisvegabor** [comment]
Great! Thank you very much!

**Comment by BrianPugh** [comment]
Just a random thought: Setting LV_TXT_LINE_BREAK_LONG_POST_MIN_LEN to 0 might cause a warning/error in some compilers because I'm comparing an unsigned number to be less than it. A default value of 1 should achieve the same thing as 0 without the warnings. I'm away from my dev computer so I cannot test it right now.

**Comment by kisvegabor** [comment]
I've tested with `1` default value and it worked the same as with `0`. So I changed the default value to `1`. Thank you!

**Comment by kisvegabor** [comment]
@BrianPugh 
I found this case of word wrapping:
image

If I understood well, the word "visszaallitani" shouldn't be wrapped. 

It looks like this if I disable this feature by increasing the limits:
image

EDIT:
Ignore it, sorry, I got it. The old behavior was in my mind when the word was wrapped if it doesn't fit into a whole line.

**Comment by BrianPugh** [comment]
Even though this is intended behavior, maybe at some point we should make this configurable during runtime (just convert the define macros to variables and make setters/getters). I wrote up the word wrapping primarily with left-justified text in mind. In your example, the 2nd image looks better. Maybe in center-justified text the 12-letter limit should be disabled.

**Comment by kisvegabor** [comment]
As I was thinking about it, as a user wouldn't expect to not wrap this word. To original approach (wrap long words if longer than a whole line) seems more reasonable to me. 

I can imagine a new `LV_TXT_FLAG_...` to enable/disable this feature.

**Pull request merged**
