### PR TITLE
feat(anim): add the function of getting global animation refresher timer

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Two questions:
1. What is the real-life use case behind this feature?
2. What about `lv_anim_set/get_timer_period`?

**Comment by FASTSHIFT** [comment]
> Two questions:
> 
> 1. What is the real-life use case behind this feature?
> 2. What about `lv_anim_set/get_timer_period`?

If I want to reduce the power consumption of the device, I can use this API to reduce the overall animation frame rate and reduce the number of redraws.

**Comment by kisvegabor** [comment]
Got it. Seems fair. 

API-wise we can consider  `lv_timer_t * lv_anim_get_timer(void)` too. It gives the highest flexibility. And it's similar to `_lv_disp_get_refr_timer(disp)`. What do you think?

**Comment by FASTSHIFT** [comment]
> Got it. Seems fair.
> 
> API-wise we can consider `lv_timer_t * lv_anim_get_timer(void)` too. It gives the highest flexibility. And it's similar to `_lv_disp_get_refr_timer(disp)`. What do you think?

I agree with this.

**Comment by kisvegabor** [comment]
Thank you!

**Pull request merged**
