### PR TITLE
V9.2.1 prepare

### PR DESCRIPTION
**Pull request by kisvegabor**
Cherry-pick all `fix` commits from `master`.

These 2 is not added yet:
- 559618d9d It might not work well
- c0af741b4 There was a conflicts that I haven't resolved yet

@nicusorcitu will add more fixes before the release of v9.2.1, but I suggest merging this PR as soon as possible to have at least these commits in place.

cc @liamHowatt @XuNeo @FASTSHIFT @faxe1008 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by nicusorcitu** [comment]
Hi @kisvegabor
We opened the PR with the extra changes for 9.2.1. Please include these as well: https://github.com/lvgl/lvgl/pull/6979

**Comment by nicusorcitu** [comment]
@cosmindanielradu19

**Comment by kisvegabor** [comment]
@FASTSHIFT c0af741 seems like a complex VG-Lite relate one. Could you advise on that. Just `git cherry-pick c0af741` in this PR and you will see a not trivial conflict.

**Comment by FASTSHIFT** [comment]
> @FASTSHIFT [c0af741](https://github.com/lvgl/lvgl/commit/c0af741b45154f9a6a39919991b90188f9c51a0f) seems like a complex VG-Lite relate one. Could you advise on that. Just `git cherry-pick c0af741` in this PR and you will see a not trivial conflict.

```bash
git cherry-pick 3db31e4 0c8e772 c0af741
git add .
git cherry-pick --continue
```

Please don't forget this PR: https://github.com/lvgl/lvgl/pull/6758

**Comment by nicusorcitu** [comment]
Please cherry-pick also the commit https://github.com/lvgl/lvgl/commit/dfd77c80f5d49b5eaa138363b7e0a2ecd1d44999

**Comment by cederom** [comment]
Hello @kisvegabor we are testing Nuttx 12.7.0-RC0 right now and users report broken display with 9.1 (https://github.com/apache/nuttx/issues/13825). Are there known problems in this area that were fixed in 9.2 / 9.2.1 should we wait with the release? :-)

**Comment by XuNeo** [comment]
Need to update version number too.

**Comment by nicusorcitu** [comment]
Hi @kisvegabor when do you plan to merge the changes? We would like to test the whole 9.2.1 before releasing to be sure nothing else is broken in these commits.
So I suggest 2 options:
1. You merge this PR then we will rebase ours https://github.com/lvgl/lvgl/pull/6979 then will validate one again.
2. You can cherry-pick the commits from our PR https://github.com/lvgl/lvgl/pull/6979 and merge them directly here and we can validate this PR directly.

Which option is better for you?

**Comment by kisvegabor** [comment]
@FASTSHIFT @nicusorcitu 
These are merged:
- 3db31e4 
- 0c8e772 
- c0af741  
- 57f7255  
- 2c021b6

>  You merge this PR then we will rebase ours Release/nxp patches for LVGL v9.2 #6979 then will validate one again.

I'd prefer this option. @liamHowatt will review it today.

**Comment by kisvegabor** [comment]
@FASTSHIFT @XuNeo @liamHowatt 
If it looks good please approve it so that we can merge it asap.

**Comment by kisvegabor** [comment]
@cederom I just comment on the issue at NuttX.

**Review by XuNeo — APPROVED** [review]
Build pass with no warnings on multiple nuttx targets.

**Review by liamHowatt — COMMENTED** [review]
Maybe it's time to add CI to pull requests targeting `release/v9.*` branches. Currently it's this: https://github.com/lvgl/lvgl/blob/8d47460580c6e17ff800aaac2dbbb11c3520cc44/.github/workflows/ccpp.yml#L3-L7

These would not be caught by the CI but mentioning them anyways:

The VG Lite tests needs to have two images updated and I see an integer overflow message.

This ref image can be deleted: https://github.com/kisvegabor/lvgl_upstream/blob/00a8b4f7ed8c4c8de8fa2272041ba52daa4cd506/tests/ref_imgs/libs/freetype_1.lp32.png

**Review by FASTSHIFT — APPROVED** [review]

**Comment by kisvegabor** [comment]
@liamHowatt Good idea! I merge this one now. Could you open a new PR for the points you mentioned?

**Comment by kisvegabor** [comment]
@faxe1008 Please confirm if we are good for Zephyr too.

**Comment by XuNeo** [comment]
Hi @kisvegabor 

When do you plan to create release of v9.2.1?

https://github.com/apache/nuttx-apps/pull/2592 will need it to merge. 
I tested again with latest release/v9.2, and it's good. :)

**Comment by cederom** [comment]
All display related issues are now fixed on NuttX we are waiting for v9.2.1 LVG release so we can include it in NuttX 12.7.0 release, thank you everyone involved!! :-)

**Comment by faxe1008** [comment]
I ran the basic tests today with 9.2.1 and did not face compilation issues. Will do some more in depth testing with PXP tomorrow.

**Comment by nicusorcitu** [comment]
Please run the PXP tests after merging the PR https://github.com/lvgl/lvgl/pull/6979

**Comment by kisvegabor** [comment]
https://github.com/lvgl/lvgl/pull/6979 is merged

**Comment by kisvegabor** [comment]
Can you bisect which commit introduced the problem? Fortunately it's visible on the first scene to.

**Comment by nicusorcitu** [comment]
@cristian-stoica can you please try it out the last branch and do a git bisect? Thank you.

**Comment by cosmindanielradu19** [comment]
> Can you bisect which commit introduced the problem? Fortunately it's visible on the first scene to.
> 
> I'm sure yes, just asking: have you set -O3 in both cases?

Hi @kisvegabor , I've managed to find the issue. It comes from #6803. 

I've done a comparison of release/9.2 branch with and without commit 53c846f4a, and it seems that without it, the performance is fine.

image

**Comment by liamHowatt** [comment]
Let's cross off [this](https://github.com/lvgl/lvgl/pull/6803#issuecomment-2362726676) as a potential cause of the degradation. Is it unrelated?

**Comment by nicusorcitu** [comment]
My question is why do we need recursive locks? This change https://github.com/lvgl/lvgl/commit/53c846f4acee1f5a2fc8532799c279238f2df230 impact the performance.

If someone takes recursively the same mutex, maybe there is a problem on that application. We need to fix the performance regression.

**Comment by kisvegabor** [comment]
So far I couldn't reproduce the performance regression. I've tried with a Renesas board and measured the exact same performance with and without FreeRTOS. We will try with an ST board on Monday too. 

We started to use recursive mutexes based on the request of @espzav (Espressif). The use case is the following: We have added [`lv_lock` and `lv_unlock`](https://github.com/lvgl/lvgl/blob/master/src/osal/lv_os.c#L45-L59). It is a generic interface to lock LVGL when LVGL functions are called from other threads.  However, when the application is complex, and the user's function calls are deeply nested it can happen that `lv_lock` will be called multiple times. For example `my_screen_load` calls `lv_lock` and calls `my_card_create` too, which also locks LVGL as a card can be created at any time too. Or maybe these functions are called from an event where LVGL is already locked (`lv_timer_handler` automatically locks the LVGL).  

It seems the recursive mutex handling is only a [very thin layer](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/5f3bab1a3242640c6e031d9cfb1be756bd76fb3c/queue.c#L815-L855) around the normal mutex handling which doesn't explain why it is so much slower.   

Is there anything special in your FreeRTOS or its config?

**Comment by kisvegabor** [comment]
> While we put everything in SRAM (internal memory) the impact can not be seen.

How slow this RAM is? Maybe it's very slow because of caching? E g. even when a byte is changed the whole cache line is read and written. 

 In freeRTOS it seems it's only about incrementing and decrementing a single int to keep track of the nested gives and takes. 

(Although freeRTOS is in internal RAM we haven't seen any changes on ST either)

**Comment by XuNeo** [comment]
Hi @kisvegabor 
Would you consider release v9.2.1 and fix the performance issue in next patch version update?

**Comment by nicusorcitu** [comment]
@kisvegabor I would remove the commit https://github.com/lvgl/lvgl/commit/53c846f4acee1f5a2fc8532799c279238f2df230 from 9.2.1 as this is also a new feature - not a bugfix. Next we have to figure out on master branch why the recursive lock introduce this performance drop.

**Comment by kisvegabor** [comment]
It's hard to decide which option is better, but finally I reverted it [here](https://github.com/lvgl/lvgl/commit/7d5cb8385e49285bfd8359b83f07cdb5104aba1b). Let's investigate the performance issue in `master`.

Please do a final test. If all looks good, I'll release v9.2.1 tomorrow.

**Pull request merged**
