### PR TITLE
fix(demos): remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by MouriNaruto**
Help us review this PR! Anyone can [approve it or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### Description of the feature or fix

When I using MSVC to compile an UEFI application project with LVGL v9, I found at least we can remove some unnecessary dependencies for "demos/lv_demos.c".

It looks the "io.h" header was included in "demos/lv_demos.c" for the scenario of "unistd.h" not available (https://github.com/lvgl/lvgl/pull/4718), but in later development, it looks this source file remove the "unistd.h" dependency (https://github.com/lvgl/lvgl/pull/4759). So, I think it can safely remove and test compiling the VS project and it’s OK.

Also, I don't think "strcmp" should be used directly due to the existance of "lv_strcmp". So, the dependency of "stdio.h" and "stdlib.h" can also be removed. There are lots of similar issues in LVGL mainline. But I know it's not practical to make all components dependent on the LVGL standard library. I think it's wise to let LVGL to have a minimal portable free-standing core exclude platform support but with demos and examples will make embedded, IoT and bare-metal developers happy.

I create an issue to detail talk about my idea and suggestion the minimal portable free-standing core: https://github.com/lvgl/lvgl/issues/5391

### Checkpoints
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)

Kenji Mouri

### CODE REVIEW

**Review by FASTSHIFT — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thank you! 

@PGNetHun the CI fails here because the now logging is enabled in Micropython. So can we add an command line option to Micropython  to disable lvgl's logging.

What do you think?

**Comment by XuNeo** [comment]
> to disable lvgl's logging.

See https://github.com/lvgl/lv_binding_micropython/pull/320

**Review by C47D — APPROVED** [review]

**Comment by kisvegabor** [comment]
The CI should pass now, please rebase on `master`.

**Review by kisvegabor — APPROVED** [review]

**Comment by MouriNaruto** [comment]
@kisvegabor 

done for rebasing

Kenji Mouri

**Comment by kisvegabor** [comment]
Thank you!

**Pull request merged**
