### PR TITLE
fix(textarea): fix placeholder text cannot be centered

### PR DESCRIPTION
**Pull request by anheiqq**
Fixes https://github.com/lvgl/lvgl/issues/6833

### CODE REVIEW

**Review by kissa96 — APPROVED** [review]
LGTM

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thanks! 

@kissa96 Also thank you for the reviews! :rocket:

**Review by liamHowatt — APPROVED** [review]
Nice. I see it's targeting the `release/v9.2` branch. Maybe there could be a PR after for `master` too.

**Comment by kisvegabor** [comment]
I've just noticed that it was merged to `release/v9.2` so cherry picked it to `master` here: https://github.com/lvgl/lvgl/pull/6917

**Pull request merged**
