### PR TITLE
get the top most child from a parent by a point pointer

### PR DESCRIPTION
**Pull request by TridentTD**
Get the top most child from a parent by a point pointer.

### CODE REVIEW

**Review by embeddedt — COMMENTED** [review]
Can this and [`indev_search_obj`](https://github.com/littlevgl/lvgl/blob/4037a68cccf9704297dabad67de7f41ed07ebe34/src/lv_core/lv_indev.c#L992-L1048) be unified into one function, to prevent code duplication? It seems to me that everything using `indev_search_obj` just needs to be changed to use this function and pass `&proc->types.pointer.act_point` as the second argument.

**Comment by kisvegabor** [comment]
> Can this and indev_search_obj be unified into one function

I agree. It should be possible and desirable :slightly_smiling_face:

**Comment by TridentTD** [comment]
@embeddt
OK, just  unified from  `indev_search_obj(...)` to `lv_indev_search_obj(lv_obj_t* obj, lv_point_t*point)` 

---------------
@embeddt @kisvegabor
BTW, sorry for the mis-copy lv_indev.h/.c from dev-7.0 ,
now it return to master with unified `lv_indev_search_obj`.

**Comment by kisvegabor** [comment]
Looks good to me, thank you!
We can merge if @embeddedt reviews it.

**Comment by embeddedt** [comment]
Thanks! Merged to `dev-7.0`.

**Pull request merged**
