### PR TITLE
perf(bin_decoder): improve the decoding performance of a8

### PR DESCRIPTION
**Pull request by W-Mai**
1. Variable `A8` should not enter cache. Entering cache in the past will cause unexpected errors when the memory address is the same.

2. Reduce decoder_data allocation and release

3. Reduce `decoded draw_buf` allocation and release

image

and it will reduce the `get_decoder_data` allocation and this draw buf allocation below

image

cc @XuNeo 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
In general, why A8 is special? Why only A8 can be used directly and A4 not?

**Comment by W-Mai** [comment]
> In general, why A8 is special? Why only A8 can be used directly and A4 not?

Because A1/2/4 needs bin decoder to decode them to A8 format and cached, but A8 can be draw directly. 

In fact, A8 hasn't done anything before I modified it. it just assigned it a new cache buf, then copied the old A8 image into it and returned the new A8 buf.

**Comment by XuNeo** [comment]
> Entering cache in the past will cause unexpected errors when the memory address is the same.

What is the issue?

**Comment by W-Mai** [comment]
> > Entering cache in the past will cause unexpected errors when the memory address is the same.
> 
> What is the issue?

I encountered a problem. When I didn't open asan and used tlsf heap to allocate mem, because there was no other (or alloc but free quickly balanced) heap allocation behavior between the two drawing characters, the assigned draw buf was still the same address when drawing the next character. This causes the cache to hit, resulting in the use of draw buf used in the previous drawing character when drawing image. As a result, it leads to drawing problems.

**Comment by kisvegabor** [comment]
> Because A1/2/4 needs bin decoder to decode them to A8 format and cached, but A8 can be draw directly.

I can't fully oversee the problem, but what bothers me is that for GPUs A1/2/4/8 are the same. Maybe it's irrelevant. 


> This causes the cache to hit, resulting in the use of draw buf used in the previous drawing character when drawing image. As a result, it leads to drawing problems.

It seems like a more generic issue than only A8. (This is my last work day this year, so I cannot immerse in it now.)

**Comment by W-Mai** [comment]
> > Because A1/2/4 needs bin decoder to decode them to A8 format and cached, but A8 can be draw directly.
> 
> I can't fully oversee the problem, but what bothers me is that for GPUs A1/2/4/8 are the same. Maybe it's irrelevant.

But LVGL will decoded A1/2/4 to A8 here and push the decoded A8 image into cache here:

https://github.com/lvgl/lvgl/blob/cdaaeb81dc3e1f9023749d1a79c5c7970cad10c1/src/libs/bin_decoder/lv_bin_decoder.c#L866-L894

But in fact, A8 doesn't to be decoded again, it doesn't need to run this process.

The current code's behavior with A8 is just to create a new buff and copy the original A8 data into it, which is an unnecessary process

**Review by kisvegabor — APPROVED** [review]
Finally understood, sorry for being so slow. I got tired by the end if the year :smile:

**Review by uLipe — APPROVED** [review]

**Pull request merged**
