### PR TITLE
ci(ref_imgs): make the CI fail if there not all ref. images are added

### PR DESCRIPTION
**Pull request by kisvegabor**
A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
It works:
image

I add that removed

**Comment by FASTSHIFT** [comment]
Nice!

**Comment by FASTSHIFT** [comment]
There are indeed quite a few missing images. Users' local tests are usually not in 32-bit environments. Can we download these images from 32-bit environments on CI?
```bash
?? tests/ref_imgs/draw/vector_draw_lines.lp32.png
?? tests/ref_imgs/draw/vector_draw_shapes.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_0.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_1.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_10.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_2.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_3.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_4.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_5.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_6.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_7.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_8.lp32.png
?? tests/ref_imgs/libs/font_stress/snapshot_9.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_com_1.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_com_2.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_com_3.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_com_4.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_com_5.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_com_6.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_com_7.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_com_8.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_group_1.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_group_2.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_group_3.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_group_4.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_0.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_1.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_10.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_11.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_[12](https://github.com/lvgl/lvgl/actions/runs/11364264054/job/31609943142?pr=7086#step:9:13).lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_2.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_3.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_4.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_5.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_6.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_7.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_8.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_image_9.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_1.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_10.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_11.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_2.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_3.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_4.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_5.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_6.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_7.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_8.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_shapes_9.lp[32](https://github.com/lvgl/lvgl/actions/runs/11364264054/job/31609943142?pr=7086#step:9:33).png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_text_1.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_text_2.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_viewport_1.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_viewport_2.lp32.png
?? tests/ref_imgs_vg_lite/draw/svg_draw_svg_viewport_3.lp32.png
?? tests/ref_imgs_vg_lite/draw/vector_draw_lines.lp32.png
?? tests/ref_imgs_vg_lite/draw/vector_draw_shapes.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_0.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_1.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_10.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_2.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_3.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_4.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_5.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_6.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_7.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_8.lp32.png
?? tests/ref_imgs_vg_lite/libs/font_stress/snapshot_9.lp32.png
?? tests/ref_imgs_vg_lite/libs/freetype_1.lp32.png
```

**Comment by kisvegabor** [comment]
CI failed, files are downloaded and added. Let's see if it passes now.

**Review by FASTSHIFT — APPROVED** [review]

**Review by XuNeo — APPROVED** [review]

**Pull request merged**
