### PR TITLE
test(txt): add new test cases for arabic string

### PR DESCRIPTION
**Pull request by DennisSHCheung**
Created a test to challenge Arabic conjunction calculation

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
@cmumford It seems build tests try to compile the test cases too. I think it should be avoided because the tests are written for a specific build config. Do you agree with that?

**Comment by cmumford** [comment]
@kisvegabor yes, all tests are built and run for each PR. I think this test is maybe missing a header file as this looks like `"src/misc/lv_txt.h"` needs to be included.  Can you add more info on what you're suggesting?

**Comment by kisvegabor** [comment]
I mean now we have ["build tests"](https://github.com/lvgl/lvgl/blob/a2e4dfdce21a990d03e72a1128566ebc7110fb3d/tests/CMakeLists.txt#L219-L228) for various configs and ["unit tests"](https://github.com/lvgl/lvgl/blob/a2e4dfdce21a990d03e72a1128566ebc7110fb3d/tests/CMakeLists.txt#L229-L231) with a specific (everything is enabled) config.

I think the problem in this case is that the new test in the PR uses a function (`_lv_txt_ap_proc`) that is disabled in some "build test". Therefore it'd be important to build the unit tests only with `OPTIONS_TEST` as the unit tests might contain function calls that might not be available in "build tests".

**Comment by embeddedt** [comment]
Isn't it easier to just wrap the entire function declaration in `LV_USE_ARABIC_PERSIAN_CHARS`?

**Comment by kisvegabor** [comment]
> Isn't it easier to just wrap the entire function declaration in LV_USE_ARABIC_PERSIAN_CHARS?

Good idea!

**Comment by DennisSHCheung** [comment]
Sorry what needs to be done for _lv_txt_ap_proc to be enabled?

**Comment by kisvegabor** [comment]
> Sorry what needs to be done for _lv_txt_ap_proc to be enabled?

We run CI tests with different `lv_conf.h` settings to see LVGL can be built with these different settings. But in not all cases we have `LV_USE_ARABIC_PERSIAN_CHARS` is enabled. 

So please wrap the test into an
```c
#if LV_BUILD_TEST
#include "../lvgl.h"

#if LV_USE_ARABIC_PERSIAN_CHARS


...


#endif  /*#if LV_USE_ARABIC_PERSIAN_CHARS*/
#endif /*#if LV_BUILD_TEST*/
```

**Comment by DennisSHCheung** [comment]
After doing what you mentioned, the error didn't go away

Running with ./tests/main.py test:
image

Running with ./tests/main.py build:
image
which I assume is because like you said that LV_USE_ARABIC_PERSIAN_CHARS is not always enabled

Any suggestions?

**Comment by kisvegabor** [comment]
Hi,

Sorry for the late reply. I've just pushed a commit to make it build, but the test itself failed for me locally.
```
./src/test_cases/test_txt_ap.c:24:test_txt_ap_proc_detect_invalid_conjuction_with_fatha:FAIL: Expected -17 Was 1604
```

**Comment by DennisSHCheung** [comment]
Thanks for making it to build. Yes, I made it intentionally to fail to see if it could actually build.

**Comment by kisvegabor** [comment]
Okay, great! :slightly_smiling_face: 

I needed to push an other fix.

**Pull request closed without merging**
