### PR TITLE
refactor(driver): rename dev to drivers + Arduino update

### PR DESCRIPTION
**Pull request by kisvegabor**
Help us review this PR! Anyone can [approve it or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### Description of the feature or fix

`drivers` is a better name than `dev`. `dev` can mean "device" or "development" too.

### Checkpoints
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
How about calling it `port` or `porting`?

**Comment by kisvegabor** [comment]
`driver` feels more intuitive for me. In the `porting` folder I would expect architecture or operating system related things. 

What do you think @XuNeo @GorgonMeducer @PGNetHun @C47D ?

**Comment by PGNetHun** [comment]
I agree with @kisvegabor :
`porting` means for me code files (not just drivers, but OS/platform-specific files) for a specific platform.
The folder name `drivers` better describes what it contains: code files that controls HW parts (display, input devices, etc). Mostly platform-independent drivers, and not different ports/platforms.

**Review by PGNetHun — APPROVED** [review]

**Comment by XuNeo** [comment]
How about `hal` compared to `osal`?

**Comment by kisvegabor** [comment]
SDL or `/dev/fb` are not typical HALs in my opinion.

**Comment by PGNetHun** [comment]
> How about `hal` compared to `osal`?

HAL (Hardware Abstraction Layer) is just a unified API interface for device drivers, so it does not include implementations (drivers itself).
I still stick to the name **drivers** to store the implementations of display & HID controllers.

**Review by XuNeo — APPROVED** [review]
`drivers` sounds reasonable to lvgl. I agree then. It's originally called `lv_drivers` after all.
https://github.com/lvgl/lv_drivers

**Review by FASTSHIFT — APPROVED** [review]

**Comment by kisvegabor** [comment]
> drivers sounds reasonable to lvgl. I agree then. It's originally called lv_drivers after all.

True!

Thank you, guys!

**Pull request merged**
