### PR TITLE
fix(flex): LV_FLEX_ALIGN_SPACE_BETWEEN align single item left

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

In response to #5792

The CSS equivalent of `LV_FLEX_ALIGN_SPACE_BETWEEN` places single items at the start, not the center. The current LVGL docs of this enum agree with this. See #5792.

Change the behavior of `LV_FLEX_ALIGN_SPACE_BETWEEN` to match docs and CSS equivalent.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by PGNetHun — COMMENTED** [review]
Could you please add a new test case?
Reference: https://github.com/lvgl/lvgl/blob/master/tests/src/test_cases/test_margin_flex.c

**Comment by liamHowatt** [comment]
@PGNetHun what do you think of this?

**Review by PGNetHun — APPROVED** [review]

**Comment by PGNetHun** [comment]
> @PGNetHun what do you think of this?

Simple, yet great test!

**Review by kisvegabor — APPROVED** [review]
Thank you, Liam!

**Comment by liamHowatt** [comment]
> Simple, yet great test!

Thanks! I wanted to test a good amount of permutations while not adding too many new assets. It occurred to me too late that I could have simply put multiple permutations in one screenshot. Should I do that or has that ship sailed?

**Comment by kisvegabor** [comment]
Let's leave the tests as they are. When https://github.com/lvgl/lvgl/issues/5938 will be implemented we will have much more tests anyway.

**Pull request merged**
