### PR TITLE
fix(demo): lv_demo_widgets update scale3 needle and label pos on resize

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

See #6217 for GIFs.

This should not close the issue yet.

Update the scale 3 needle and label position in lv_demo_widgets on resize. Automatic alignment does not work because the scale obj is a rectangle while the visual scale center is square, so a size change event callback was added to recalculate the needle and label's position.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by C47D — APPROVED** [review]
Thanks for the explanation and fix @liamHowatt

**Review by kisvegabor — APPROVED** [review]
Tested and works well! Thank you!

**Comment by C47D** [comment]
Do we need another revision?

**Comment by kisvegabor** [comment]
> Do we need another revision?

How do you mean it?

**Review by C47D — APPROVED** [review]

**Comment by C47D** [comment]
Mmmm there's a missing revision/approval, even when it had 2 already. I just sent another approval and it stays the same. Maybe is the phone github app having issues.

**Review by FASTSHIFT — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
