### PR TITLE
CI - Build Micropython with LVGL submodule

### PR DESCRIPTION
**Pull request by amirgon**

### CODE REVIEW

**Comment by amirgon** [comment]
The new "Build Micropython with LVGL submodule" check fails, but I'm not sure why.
I suspect this is because the yml script of the test itself is not merged yet.
The problem is related to this part:
```
... change dir to lvgl submodule ...
git fetch
git checkout $GITHUB_SHA

fatal: reference is not a tree: 8a0038595401dde0d41759030148b31ce5fbe9c8
```

The `$GITHUB_SHA` is supposed to be the LVGL commit hash that is being considered in the PR, but it seems that it's wrong. The right value should have been 539cd2e88c32413a73f561c3b7031fd7587a3f71 which is the last commit of this PR.

I suspect (but not completely sure) that after merging this PR this problem would disappear.
I'm doing the same thing (almost the same yml script!) on https://github.com/lvgl/lv_binding_micropython and over there it works just fine.

**Comment by kisvegabor** [comment]
I merge this to see what happens.

**Comment by kisvegabor** [comment]
You were right, it works after merge!
` Run advanced_demo` gave this message, but this error is not important I suppsose:
```
Run echo "import gc,utime; utime.sleep(5); gc.collect(); utime.sleep(5)" |  ports/unix/micropython -i lib/lv_bindings/examples/advanced_demo.py
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
MicroPython v1.9.4-2896-g0eef5f888-dirty on 2020-09-05; linux version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import gc,utime; utime.sleep(5); gc.collect(); utime.sleep(5)
687
>>> 
```
See https://github.com/lvgl/lvgl/runs/1075404440

**Comment by amirgon** [comment]
That's great! Thanks.

> ` Run advanced_demo` gave this message, but this error is not important I suppsose

You can ignore the XDG_RUNTIME_DIR error. It's there because the CI VM is not configured with a display,  but we still use SDL.

**Pull request merged**
