### PR TITLE
Add LZ4 compressed binary image support

### PR DESCRIPTION
**Pull request by XuNeo**
### Description of the feature or fix

LZ4 has higher compression ratio compared to RLE, but also slower decompress speed.
There's no perf data for now.

Depends on PR #4870, #4871, #4872

### Checkpoints
- [ ] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<module_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
What is the advantage of LZ4 over PNG?

**Comment by lhdjply** [comment]
Can the relevant functions inside be replaced with functions from stdlib? For example, replacing **memset** with **lv_memset** and **memcpy** with **lv_memcpy.**

**Comment by XuNeo** [comment]
> What is the advantage of LZ4 over PNG?

Let's answer the question about compress image with LZ4 here.

I planned to add more png files to test, but the simple cogwheel already makes it very clear.
The first three rows are most important to compare. 
So PNG is really small, but not too impressive compared with `LZ4`. But `PNG` decode speed is much worse.
RLE is really fast, but also not that good on compression. RLE only performs better on repetitive pixels.

| Compression  | File            | Time (ms) | File Size(byte) |
|--------------|-----------------|-----------|--------|
| png          | png             | 182       | 14145  |
| lz4          | ARGB8888.bin    | 50        | 18971  |
| rle          | ARGB8888.bin    | 20        | 30596  |
| uncompressed | ARGB8888.bin    | 2         | 40012  |
| lz4          | A1.bin          | 32        | 863    |
| lz4          | A2.bin          | 35        | 1353   |
| lz4          | A4.bin          | 42        | 2079   |
| lz4          | A8.bin          | 21        | 3768   |
| lz4          | I1.bin          | 11        | 849    |
| lz4          | I2.bin          | 13        | 1845   |
| lz4          | I4.bin          | 18        | 3511   |
| lz4          | I8.bin          | 20        | 7486   |
| lz4          | RGB565A8.bin    | 50        | 11734  |
| lz4          | RGB565.bin      | 31        | 8174   |
| lz4          | RGB888.bin      | 37        | 16000  |
| lz4          | XRGB8888.bin    | 51        | 17977  |
| rle          | A1.bin          | 30        | 1615   |
| rle          | A2.bin          | 29        | 2776   |
| rle          | A4.bin          | 33        | 3538   |
| rle          | A8.bin          | 7         | 6233   |
| rle          | I1.bin          | 9         | 1646   |
| rle          | I2.bin          | 10        | 3246   |
| rle          | I4.bin          | 12        | 4374   |
| rle          | I8.bin          | 13        | 8834   |
| rle          | RGB565A8.bin    | 17        | 25298  |
| rle          | RGB565.bin      | 13        | 17132  |
| rle          | RGB888.bin      | 15        | 25851  |
| rle          | XRGB8888.bin    | 21        | 29876  |
| uncompressed | A1.bin          | 28        | 1612   |
| uncompressed | A2.bin          | 29        | 3212   |
| uncompressed | A4.bin          | 28        | 6412   |
| uncompressed | A8.bin          | 2         | 11212  |
| uncompressed | I1.bin          | 9         | 1620   |
| uncompressed | I2.bin          | 8         | 3228   |
| uncompressed | I4.bin          | 8         | 6476   |
| uncompressed | I8.bin          | 8         | 12236  |
| uncompressed | RGB565A8.bin    | 2         | 31212  |
| uncompressed | RGB565.bin      | 2         | 20812  |
| uncompressed | RGB888.bin      | 2         | 30412  |
| uncompressed | XRGB8888.bin    | 3         | 40012  |

**Comment by kisvegabor** [comment]
Thank you, these lines show very well that these formats really have different characteristics: 
image

I'm convinced and I'm all in!

**Comment by XuNeo** [comment]
Depends on https://github.com/lvgl/lvgl/pull/4870

**Pull request merged**
