### PR TITLE
Fix lv_deinit lv_init crash or hang

### LINKED ISSUE #2809: lv_deinit() -> lv_init() causes crash lv_style_get_prop_inlined
### Perform all steps below and tick them with [x]
- [ X] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ X] Update lvgl to the latest version
- [ X] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

For our project on an embedded board we need to be able to completly reinitialize lvgl into a known state.
To do this we try to use lv_deinit() and later on initialize everything again as first (using lv_init(), ...). 
When we do this we get a crash with a nullptr in lv_style_get_prop_inlined.
`    if(style->is_const) {
        const lv_style_const_prop_t * const_prop;
        for(const_prop = style->v_p.const_props; const_prop->prop != LV_STYLE_PROP_INV; const_prop++) {
`
Unhandled exception thrown: read access violation.
const_prop was nullptr.

### To Reproduce

I have used the modified lv_port_windows.
 
```c

struct lvgl_handle_t
{
    lv_disp_drv_t                   disp_drv;
    lv_disp_draw_buf_t              disp_buf;
    lv_indev_drv_t                  indev_drv;
    lv_indev_drv_t                  kb_drv;
    lv_indev_drv_t                  enc_drv;
    std::array<lv_color_t, 65536>*  raw_disp_buf_p;
    lv_group_t* volatile            g_DefaultGroup;


    lvgl_handle_t()
    {
        raw_disp_buf_p = new std::array<lv_color_t, 65536>();
    }

    ~lvgl_handle_t()
    {
        delete raw_disp_buf_p;
    }
};

static lvgl_handle_t* current_handle_p{ nullptr };
void lvgl_set_current_handle( lvgl_handle_t* handle_p )
{
    current_handle_p = handle_p;
}

lvgl_handle_t* lvgl_get_current_handle()
{
    return current_handle_p;
}

bool LvglWindowsInitialize(
    _In_ HINSTANCE hInstance,
    _In_ int nShowCmd,
    _In_opt_ LPCWSTR DefaultFontName)
{
    ::LvglWindowsGdiFontInitialize(DefaultFontName);

    HICON IconHandle = ::LoadIconW(
        ::GetModuleHandleW(nullptr),
        MAKEINTRESOURCE(IDI_LVGL));

    WNDCLASSEXW WindowClass;

    WindowClass.cbSize = sizeof(WNDCLASSEXW);

    WindowClass.style = 0;
    WindowClass.lpfnWndProc = ::WndProc;
    WindowClass.cbClsExtra = 0;
    WindowClass.cbWndExtra = 0;
    WindowClass.hInstance = hInstance;
    WindowClass.hIcon = IconHandle;
    WindowClass.hCursor = ::LoadCursorW(nullptr, IDC_ARROW);
    WindowClass.hbrBackground = reinterpret_cast<HBRUSH>(COLOR_WINDOW + 1);
    WindowClass.lpszMenuName = nullptr;
    WindowClass.lpszClassName = L"lv_port_windows";
    WindowClass.hIconSm = IconHandle;

    if (!::RegisterClassExW(&WindowClass))
    {
        return false;
    }
    g_InstanceHandle = hInstance;

    g_WindowHandle = ::CreateWindowExW(
        WS_EX_CLIENTEDGE,
        WindowClass.lpszClassName,
        L"LVGL ported to Windows Desktop",
        WS_OVERLAPPEDWINDOW,
        CW_USEDEFAULT,
        0,
        CW_USEDEFAULT,
        0,
        nullptr,
        nullptr,
        hInstance,
        nullptr);

    if (!g_WindowHandle)
    {
        return false;
    }

    ::LvglRegisterTouchWindow(g_WindowHandle, 0);

    Mile::EnableChildWindowDpiMessage(g_WindowHandle);
    g_WindowDPI = ::LvglGetDpiForWindow(g_WindowHandle);

    ::ShowWindow(g_WindowHandle, nShowCmd);
    ::UpdateWindow(g_WindowHandle);
   
    return true;
}

void lvgl_initialize(lvgl_handle_t& handle)
{
    lv_disp_drv_init(&handle.disp_drv);
    lv_disp_draw_buf_init(
        &handle.disp_buf,
        handle.raw_disp_buf_p->data(),
        nullptr,
        65536
    );
    handle.disp_drv.hor_res = static_cast<lv_coord_t>(g_WindowWidth);
    handle.disp_drv.ver_res = static_cast<lv_coord_t>(g_WindowHeight);
    handle.disp_drv.flush_cb = LvglDisplayDriverFlushCallback;
    handle.disp_drv.draw_buf = &handle.disp_buf;
    handle.disp_drv.dpi = g_WindowDPI;
    lv_disp_drv_register(&handle.disp_drv);

    handle.g_DefaultGroup = lv_group_create();
    lv_group_set_default(handle.g_DefaultGroup);

    lv_indev_drv_init(&handle.indev_drv);
    handle.indev_drv.type = LV_INDEV_TYPE_POINTER;
    handle.indev_drv.read_cb = LvglMouseDriverReadCallback;
    lv_indev_set_group(
        lv_indev_drv_register(&handle.indev_drv),
        handle.g_DefaultGroup);

    lv_indev_drv_init(&handle.kb_drv);
    handle.kb_drv.type = LV_INDEV_TYPE_KEYPAD;
    handle.kb_drv.read_cb = LvglKeyboardDriverReadCallback;
    lv_indev_set_group(
        lv_indev_drv_register(&handle.kb_drv),
        handle.g_DefaultGroup);

    lv_indev_drv_init(&handle.enc_drv);
    handle.enc_drv.type = LV_INDEV_TYPE_ENCODER;
    handle.enc_drv.read_cb = ::LvglMousewheelDriverReadCallback;
    lv_indev_set_group(
        lv_indev_drv_register(&handle.enc_drv),
        handle.g_DefaultGroup);
}

int WINAPI wWinMain(
    _In_ HINSTANCE hInstance,
    _In_opt_ HINSTANCE hPrevInstance,
    _In_ LPWSTR lpCmdLine,
    _In_ int nShowCmd)
{
    UNREFERENCED_PARAMETER(hPrevInstance);
    UNREFERENCED_PARAMETER(lpCmdLine);

    if (!LvglWindowsInitialize(
        hInstance,
        nShowCmd,
        nullptr))
    {
        return -1;
    }

    while(1)
    {
        lv_init();
        {
            lvgl_handle_t lv_handle{};
            lvgl_initialize( lv_handle );
            lvgl_set_current_handle( &lv_handle );
            //lv_demo_widgets();
            //lv_demo_keypad_encoder();
            //lv_demo_benchmark();
            auto thrd = std::thread( LvglTaskSchedulerLoop );
            Sleep( 10000 );
            g_WindowQuitSignal = true;
            thrd.join();
            lvgl_set_current_handle( nullptr );
        } // Destroys the handle & frees buffer memory
        lv_deinit();
    }
    return ::LvglWindowsLoop();
}
```

### Expected behavior

The display restarts again correctly. No crashes.

### PR DESCRIPTION
**Pull request by geert-KLA-BE**
### Description of the feature or fix
#2809

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by geert-KLA-BE** [comment]
Not sure what the error is of lv_conf_internal.h
When squash & merging the commit messages should be cleaned up.

**Comment by kisvegabor** [comment]
Thank you very much, merging!

**Comment by mysterywolf** [comment]
Hi @geert-KLA-BE  would you re-test this PR. When I use the latest code, I found that there is an problem:
image

When I revert this PR, this problem is gone.

**Comment by mysterywolf** [comment]
This PR also causes the hardware platform assert failure.

**Comment by xennex22** [comment]
It creates a new label every time it is called.  It will run out of resources.  Did you try the fix I made here?
https://github.com/xennex22/lvgl/blob/f2a490c1afb340d3e5a5e312a681dd55033d51b7/src/core/lv_refr.c

**Comment by kisvegabor** [comment]
I've just pushed a fix.

**Comment by geert-KLA-BE** [comment]
Thanks for including the fix. Was in holiday so was not able to respond the past weeks.

**Pull request merged**
