### PR TITLE
fix duplicate locals shadowing each other (compiler warning)

### PR DESCRIPTION
**Pull request by aenchevich**

### CODE REVIEW

**Comment by C47D** [comment]
Sorry to bother but, what C standard is lvgl written in? I think some of those shadowed variables can be avoided with the following syntax (available since C99 iirc):

```c
for(uint32_t i = line_end - 1; i > 0; i--) {
    // ...
}
```

**Comment by kisvegabor** [comment]
@aenchevich  Thank your for pointing this out!

@C47D C99 iirc? I never heard about it and didn't find anything useful in google. Can you link some info?

**Comment by C47D** [comment]
Hi @aenchevich and @kisvegabor:
> The C standard is "C99" and iirc in Carlos' message is "if i recall correctly" :)

@kisvegabor I meant that :)

> However, in the case of an embedded library, such as LittlevGL, which supports many platforms and new are added constantly, I think it is most important to find the common denominator which satisfies all the variants. It seems that C99 is a good starting point but this may change in the future and, IMO, maintaining the usability and portability of the lib is more important than sticking to standards.

I don't know what version of gcc/clang the lvgl users are using but the most recent versions of those toolchains defaults to C99/C11, maybe we can know for sure making a poll asking about the compiler version people use.

> Regarding "for(uint32_t i ..."
In this particular case, adding these inner-loop locals would not add any real benefit in terms of performance or code size (being loop counters they are probably implemented via a register anyway). Benefits in therms of code readability are also doubtful (several variables with the same name hardly make the code more easy to understand).
So reusing the function-local 'i' here is fine, IMO.
The only thing I missed is that the 'i' which I left is a uint32_t - probably not necessary, because it is used to store results of text size calculations (in pixels) and the type used for this in lvgl is
typedef int16_t lv_coord_t;
So the 'i' that I left (line 279) should be changed to lv_coord_t. And I totally missed this, so thank you all for this discussion :)

Thank you and @kisvegabor, this library is becoming better every day :).

**Comment by kisvegabor** [comment]
Firs of all **iirc**: Upps, I didn't know it... yet... :D

I looked it up and declaring variables in a loop is really possible sience C99. I've just learnt an other new thing :)

However, compilers for embedded systems are way less standard then toolchanis for PC. For example in [this issue](https://github.com/littlevgl/lvgl/issues/306) it turned out that the compiler not initialized the global variables to zero. So I agree with @aenchevich in  "maintaining the usability and portability of the lib is more important than sticking to standards.". I think we risk more than we can win on it.

**Comment by aenchevich** [comment]
Ok, then, since this is not merged yet, I will add the lv_coord_t type change to my branch and submit again?

Btw I think it is a good long-term project to try and ask all the maintainers of specific hardware in lv_boards to compile the code with C99?

**Comment by kisvegabor** [comment]
> Ok, then, since this is not merged yet, I will add the lv_coord_t type change to my branch and submit again?

Ok, thank you!

> Btw I think it is a good long-term project to try and ask all the maintainers of specific hardware in lv_boards to compile the code with C99?

In the practice, there are no dedicated maintainers for the projects. People just give feedback if something is not working.

**Comment by aenchevich** [comment]
Ok this is ready for merge now.
 - - - -
@kisvegabor:  Regarding C99 - I am not sure what is the best course of action here. At present the project does not specify that any particular C standard should be used... so in theory people could write new code in any standard.. which is not very good.

IMO, based on the fact that I compiled lvgl, lv_drivers and lv_examples for C99 and it worked, it would be ok to set the C standard for the project to C99. If anything breaks on some non-mainstream compiler we could work it out. 

IIRC  [;)] - you are using multi-byte characters (unicode, wide characters, <wchar.h>, <wctype.h>)  in lvgl? If yes, then it's almost certain that the standard you are using was already C99, because the wide chars were introduced in C95 but C95 is not very widely used so it's most likely C99... I hope this makes sense...  :)

**Comment by kisvegabor** [comment]
I merged the updates, thank you! :)

There is no specified C standard fro LittelvGL. C89 doesn't support a lot of things (e.g. declaration of variables in the middle of the functions) but according to [this thread](https://stackoverflow.com/questions/3783762/ansi-c-vs-other-c-standards) Microsoft Visual Studio is not compatible with C99.

I'm not an expert in the standards but it seems a little bit messy to me. LittelvGL can be compiled in Visual Studio (by turning off the use of Variable Length Arrays) but LittelvGL is not compatible with C89.

**Pull request merged**
