### PR TITLE
Missing scroll bar modifier in tab

### PR DESCRIPTION
**Pull request by Wielebny666**

### CODE REVIEW

**Comment by Wielebny666** [comment]
I don't know why this happens :-(

**Comment by kisvegabor** [comment]
> I don't know why this happens :-(

Could you elaborate on this? :slightly_smiling_face:

**Comment by Wielebny666** [comment]
Now is Ok, but when i make new pull request, github add new commits to previous request :-( 
I dont know what i make wrong.

**Comment by kisvegabor** [comment]
If you add commits to your branch form where you have created a pull request GitHub will add the commits to the pull request.

To create a new PR you should creat a new branch too.

Can we merge it?

**Comment by Wielebny666** [comment]
OK. Yes you can.

**Comment by kisvegabor** [comment]
Okay, merged!

Now, if you can create a new PR fro master too.

**Pull request merged**
