### PR TITLE
Change signal function for lv_calendar.

### PR DESCRIPTION
**Pull request by embig71**
Change signal function for lv_calendar. Click on middle part of calendar header generate year select/change event. Use at application level as:
```c
/* lv_calendar event handler */
static void calendar_cb (lv_obj_t * obj, lv_event_t event) {
    if (event == LV_EVENT_CLICKED) {
        if (lv_calendar_get_year_pressed (obj)) {
            /* Add code for current year change/select here*/
        }
    }
}
```

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]
I will merge it to `dev-7.1` when it's created.

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
@embig71 
Could you sign the CLA to merge this PR?

**Comment by ali-rostami** [comment]
Hi 
@embig71 is it finished or not? If it is, would you please sign the CLA. thanks.

**Comment by embeddedt** [comment]
@embig71 We've changed our policy to no longer require a CLA. Instead a Developer's Certificate of Origin is used.

I don't know how to trigger the bot to comment on this PR but you can read the information [here](https://github.com/lvgl/lvgl/pull/1646#issuecomment-655464075). Could you reply to acknowledge that you understand this, so that this PR can be merged?

**Comment by embeddedt** [comment]
Unfortunately, I will have to close this PR due to lack of activity for almost 2 months.  :slightly_frowning_face:

**Pull request closed without merging**
