### PR TITLE
fix(draw): use image area to check if decoded image usable 

### LINKED ISSUE #4838: test barcode won't work with get_area_cb
While debugging CI issue when `LV_BIN_DECODER_RAM_LOAD` is set to `0`.

The issue is when using get_area_cb, decoder_dsc->img_data becomes not NULL after `img_decode_and_draw`, the next time it's called from `img_draw_tiled`,  It now thinks whole image is available(line 256) because `decoder_dsc->img_data` is not NULL.

https://github.com/lvgl/lvgl/blob/423c288070ccfb90977529aae425b72419733c77/src/draw/sw/lv_draw_sw_img.c#L256-L285

I currently hacked the code to mark `img_data` as NULL, so to continue debug CI test fail issues.

### Perform all steps below and tick them with [x]
- [ ] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [ ] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### PR DESCRIPTION
**Pull request by XuNeo**
### Description of the feature or fix
Fix #4838
When using get_area_cb, need to detect if the decoded image is ready to be used again(normally no).

> I thought `_lv_area_is_in` should be used to check decoded image fully covers the area to draw, but test show area to draw may larger than image. 
> 
> Thus use `_lv_area_intersect` instead.
> 

Now I have firstly intersect areas with full image, and then check if area to draw is inside decoded image area.

### Checkpoints
- [ ] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<module_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
It depends on #4833, right?

**Comment by XuNeo** [comment]
Yes. Only with `draw_buf` for decoded image, we can get info of decoded image.
Could you please review if the method works? Why the area to draw could be larger than image itself?

**Comment by kisvegabor** [comment]
Can you send a code snippet in which the are to draw is really larger than the image area?

**Comment by XuNeo** [comment]
The barcode could be used to reproduce it. Do change `LV_BIN_DECODER_RAM_LOAD` to `0` to test it.

Comment out this line 274 https://github.com/lvgl/lvgl/commit/43937935c7c84c72a287959d1ed6be0fd9b7f609#diff-242f305692436f289db7b3cdda6298157b9ab35835506b88b28a86b1524051abR274
and you will see logs to report area not ready.


```c

void test_barcode_normal(void)
{
    lv_obj_t * barcode = lv_barcode_create(lv_scr_act());
    lv_obj_center(barcode);

    lv_color_t dark_color = lv_color_black();
    lv_color_t light_color = lv_color_white();
    uint16_t scale = 2;

    lv_barcode_set_dark_color(barcode, dark_color);
    lv_barcode_set_light_color(barcode, light_color);
    lv_barcode_set_scale(barcode, scale);

    lv_result_t res;
    lv_image_dsc_t * image_dsc;
    lv_barcode_set_direction(barcode, LV_DIR_HOR);
    res = lv_barcode_update(barcode, "https://lvgl.io");
    image_dsc = lv_canvas_get_image(barcode);

    lv_obj_set_size(barcode, image_dsc->header.w, 50);

    lv_barcode_set_direction(barcode, LV_DIR_VER);
    res = lv_barcode_update(barcode, "https://lvgl.io");

    image_dsc = lv_canvas_get_image(barcode);

    lv_obj_set_size(barcode, 50, image_dsc->header.h);

}
```

**Comment by XuNeo** [comment]
> The barcode with `LV_COLOR_DEPTH 32` and `LV_BIN_DECODER_RAM_LOAD 0` looks like this:

Could you try with `LV_BIN_DECODER_RAM_LOAD` to 1? 
The issue is fixed on my local and will push once the draw buffer things merged. And then we can enable it on CI.

**Comment by kisvegabor** [comment]
It works well on my end too.

**Comment by XuNeo** [comment]
> Comment out this line 274 [4393793#diff-242f305692436f289db7b3cdda6298157b9ab35835506b88b28a86b1524051abR274](https://github.com/lvgl/lvgl/commit/43937935c7c84c72a287959d1ed6be0fd9b7f609#diff-242f305692436f289db7b3cdda6298157b9ab35835506b88b28a86b1524051abR274)
> and you will see logs to report area not ready.

Hi Gabor, 
This PR has made it to work by clipping the area to the whole image area and then compare if it's inside decoded image area.
You need to comment out above code to see the error.

**Comment by kisvegabor** [comment]
I've commented out 
image

Enabled `LV_BIN_DECODER_RAM_LOAD 1` but I can't see any error. 

The areas look good, and clipped when I move the cursor on the bar code.

I can't see and logged errors either.

Exactly for what issue shall I look for?

**Comment by XuNeo** [comment]
> Enabled `LV_BIN_DECODER_RAM_LOAD 1` but I can't see any error.

That's really interesting. I'm not sure which commit has fixed it.

However, now with online latest code + this PR, I can now reproduce the issue steadily with `LV_BIN_DECODER_RAM_LOAD` configured to 0.

```bash
[Warn]  (0.020, +20)     lv_image_set_src: failed to get image info: 0x60e000000a50 lv_image.c:174
[User]  (0.021, +1)      img_decode_and_draw: area not ready lv_draw_sw_img.c:285
[User]  (0.021, +0)      img_decode_and_draw: area not ready lv_draw_sw_img.c:285
[User]  (0.021, +0)      img_decode_and_draw: area not ready lv_draw_sw_img.c:285
[User]  (0.021, +0)      img_decode_and_draw: area not ready lv_draw_sw_img.c:285
[User]  (0.021, +0)      img_decode_and_draw: area not ready lv_draw_sw_img.c:285
```

**Comment by kisvegabor** [comment]
I've tested it an I think this is what happens:

Let's we have a 100x1 image, which is tiled to get a 100x20 image. For the sake of simplicity lets say the image is at 0;0. 

Now we invalidate the (50;10)(60;15) area. So we need to decode x=50..60 and draw it 6 times (y=10..15).  In the first run it's correctly detected that the image is not decoded yet, so that 11 pixel (x=50..60) are decoded. However in the next run [here](https://github.com/lvgl/lvgl/commit/43937935c7c84c72a287959d1ed6be0fd9b7f609#diff-242f305692436f289db7b3cdda6298157b9ab35835506b88b28a86b1524051abR267-R272) it's assumed that the whole image was decoded which is not true. 

So we need to keep `relative_decoded_area` accross calls of `img_decode_and_draw`. Maybe saving it in `decoder_dsc`?

**Comment by kisvegabor** [comment]
Is it already resolved by some other PRs?

**Comment by XuNeo** [comment]
It's still ongoing. Will go back too it in following days.

**Comment by kisvegabor** [comment]
Shall we pin this issue?

**Comment by XuNeo** [comment]
No need, I shall dig into it right now.

**Comment by XuNeo** [comment]
Hi @kisvegabor 
The code is working. I store the decoded image area between decoder open and close. Please help to review it.

**Review by kisvegabor — APPROVED** [review]
I think that's what we needed!

**Comment by XuNeo** [comment]
Cool.
The next thing is to add option `LV_BIN_DECODER_RAM_LOAD = 0`in CI to make sure it always works.
Could you do that?

**Comment by kisvegabor** [comment]
I've opened #5396 to discuss what kind of test configs are required.

**Pull request merged**
