### PR TITLE
Nema fix arc issue and update library (do not squash)

### LINKED ISSUE #7276: [NemaGFX] Spinner animation rotates strangley
### LVGL version

current master branch

### What happened?

We use code from https://docs.lvgl.io/master/widgets/spinner.html to define the spinner, a completely default implementation.

The animation looks like this when LV_USE_NEMA_GFX is 1, no OS enabled:

bug

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by liamHowatt**
Fixes #7276

Fix #7276:

- Shift arc angles for Nema to draw arcs correctly.

Update the Nema library:

- lv_draw_nema_gfx now accepts arc draw tasks with non-rounded ends.
- Contents of guards added in #7245 will now be compiled
  - `NEMA_TSC6AP` is now defined.
  - `NEMA_BLOP_RECOLOR` is now defined

cc @MarkIoanAmat

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by MarkIoanAmat — APPROVED** [review]
Great job @liamHowatt, thank you.

**Review by KlemenDEV — APPROVED** [review]
I can confirm this fixes the issue reported in #7276

**Review by kisvegabor — APPROVED** [review]

**Review by XuNeo — APPROVED** [review]

**Comment by williams-one** [comment]
Hello, I've been testing the last version of master and it seems to me that the update of the library has broken the drawing of a bar (see the darker blue triangle at the right end of the bar)

image

Up to the previous commit [fix(NemaGFX): arc angles](https://github.com/lvgl/lvgl/pull/7307/commits/539d7294656e72147e7abe4dc204db5934e78db6) the drawing was fine

**Comment by KlemenDEV** [comment]
@williams-one, it would probably make sense to open new issue for this, so they can keep track of it correctly

**Comment by williams-one** [comment]
@KlemenDEV Thanks for the suggestion.  I opened a new issue here https://github.com/lvgl/lvgl/issues/7337

**Pull request merged**
