### PR TITLE
Error in lv_list_get_style function

### PR DESCRIPTION
**Pull request by CrogST**
SB and SCRL styles were mixed up. Let me now if it is ok.

### CODE REVIEW

**Comment by embeddedt** [comment]
@CrogST This does looks like a legitimate issue to me, is there a reason why it was closed?

**Comment by CrogST** [comment]
Thanks. I think it was already merged.

**Comment by embeddedt** [comment]
@CrogST I merged the fix and applied it to dev-6.0 as well: https://github.com/littlevgl/lvgl/commit/bd15b805db64d228368443047d680fbf5be909de

Thank you for the report and the fix!

**Comment by kisvegabor** [comment]
Thank you for the fixes!

**Pull request merged**
