### PR TITLE
chore(cmsis-pack): monthly catch-up

### PR DESCRIPTION
**Pull request by GorgonMeducer**
### Description of the feature or fix

Catchup with the main branch. 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by FASTSHIFT — APPROVED** [review]

**Review by FASTSHIFT — DISMISSED** [review]

**Review by kisvegabor — DISMISSED** [review]

**Comment by kisvegabor** [comment]
Thank you!

**Comment by GorgonMeducer** [comment]
I have just added some new arm-2d APIs to further accelerate LVGL8. 
Ready to merge. Thank you.
@kisvegabor 

Happy golden week. @FASTSHIFT

**Review by FASTSHIFT — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]

**Comment by eagl1** [comment]
Should I replace `lv_conf_cmsis.h` I have with this one ?

Because when I compile the code in Arduino IDE using ESP32 I get this error:

```
Arduino: 1.8.19 (Windows 10), Board: "ESP32 Dev Module, Disabled, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, Core 1, Core 1, None, Disabled"

In file included from E:\projects_electronics_programming\tft\esp32_3248s035\tft_espi_using_cyd_klipper\ui_utils.cpp:7:

e:\programs_files\arduino\libraries\lvgl\env_support\cmsis-pack\lv_conf_cmsis.h:13:10: fatal error: RTE_Components.h: No such file or directory

 #include "RTE_Components.h"

          ^~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1

Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
```

What is `RTE_Components.h` is used for in the first place ? and do I need it ?

**Comment by kisvegabor** [comment]
It's strange because by default `lv_conf_cmsis.h` shouldn't be included anywhere.
Do you includ by accident somewhere?

**Comment by eagl1** [comment]
OK, first of all, the main reason is that I'm trying to program the esp32 capacitive display:

image

So the demos came with it don't work and there are many issues considering the update of lvgl, and I read the issues of running the demos/examples and I should copy them to src folder and I've been working on this for days.

Then I found this project,

[https://github.com/suchmememanyskill/CYD-Klipper](url)

it uses lvgl, but I must compile it on platformio which doesn't work on my machine, I don't know why. And I tried to run the project on vs code, but I faced more issues.

Then I found this `lv_port_esp32` support, and now I'm trying to know how to use it.

**Comment by eagl1** [comment]
I think it's better to open a new issue.

**Comment by eagl1** [comment]
The LVGL is working with no issues on ESP-IDF. Also, there's ready template examples for perihperals including lcd, rgb and oled dispalys.

**Pull request merged**
