### PR TITLE
perf(span): optimize span render performance up by 50%

### PR DESCRIPTION
**Pull request by W-Mai**
It is easy to notice that if you process a snippet each time, you can skip the first step, directly add a complete string to the drawing queue, and draw a piece of text in groups.

image

But there is a one-to-more relationship between span and snippet, which causes drawing a snippet, which may only be part of drawing span. However, c-string does not have the concept of slicing, and only half of the string cannot be intercepted for drawing without copying. So the following transformations were made:
image
image

All APIs mainly related to text drawing and calculation support the calculation and drawing of a given length of text. In this way, you can accurately control how much should be drawn at a time. In addition, the text style drawing, which previously needed to be processed separately within the spangroup, has also been uniformly replaced by the style drawing ability in draw label, which not only ensures the consistency of the code, but also reduces the call of the code.

image

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by lizhaoming634** [comment]
Good job!

**Comment by W-Mai** [comment]
There are some errors about the pictures generated by vglite, which need to be generated from a new one.

**Comment by W-Mai** [comment]
CI Problem has been fixed

**Review by kisvegabor — COMMENTED** [review]
It makes sens and it looks and sounds good! 

There is only one thing that I'm thinking about: in `lv_text_get_next_line` len=0 could also mean to process 0 bytes. Therefore I vote for using `UINT32_MAX` if there is no limit. A define like `#define LV_TEXT_LEN_MAX UINT32_MAX` can be added too.

**Review by kisvegabor — APPROVED** [review]
Looks good, thank you!

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
