### PR TITLE
feat(draw): improve acceleration for LV_IMG_CF_ALPHA_8BIT

### PR DESCRIPTION
**Pull request by GorgonMeducer**
### Description of the feature or fix

Alpha-only of LV_IMG_CF_ALPHA_8BIT can be further accelerated. 

The original method is to 
a. read alpha256 image line by line and put alpha into mask_buf and fill src_buf with `dsc->colour`.
b. call `lv_draw_sw_blend_basic()` and treat it as a normal `LV_IMG_CF_TRUE_COLOR` image

The new method bypasses the line by line reading and calls `lv_draw_sw_blend_basic()` directly, i.e. treats it as filling-colour-with-a-mask.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
I added a fix to allow partial redrawing (there was a typo in LVGL) and also allowed setting the color of A8 images like this:
```
    lv_obj_set_style_img_recolor(img1, lv_color_hex3(0xf00), 0);
    lv_obj_set_style_img_recolor_opa(img1, LV_OPA_COVER, 0);
```

**Comment by GorgonMeducer** [comment]
@kisvegabor Cool. I know my original patch isn't the right way to do that, but I hesitate to change the 

```c
mask += mask_stride * (dsc->mask_area->y1 - blend_area.y1) + (dsc->mask_area->x1 - blend_area.x1);
``` 

This is my patch (it is just a workaround but not the right method). Your fix is the right one. 

```c
        /* apply offset */
        clipped_coords.x1 += clipped_coords.x1 - coords->x1;
        clipped_coords.y1 += clipped_coords.y1 - coords->y1;
```

Cool! 

After you merge this PR, I need to update #3340 accordingly.

**Comment by kisvegabor** [comment]
Great, merging.

**Comment by GorgonMeducer** [comment]
Thank you. Let me update the lv_gpu_arm2d accordingly.

**Pull request merged**
