### PR TITLE
Move LV_GC_INCLUDE to the common place(gc.h) 

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

Avoid the inclusion duplicate in many source files

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@embeddedt @kisvegabor this PR nee work with: https://github.com/lvgl/lv_micropython/pull/23

**Comment by kisvegabor** [comment]
cc @amirgon

**Comment by amirgon** [comment]
@xiaoxiang781216 Thank you for this contribution!
I think there are conflicting files, please try to rebase.

@kisvegabor - Approved.
I've merged https://github.com/lvgl/lv_micropython/pull/23 so "Build Micropython with LVGL submodule" should pass after this PR is merged and LVGL submodule is updated on lv_micropython_binding and lv_micropython.

**Comment by xiaoxiang781216** [comment]
@amirgon @kisvegabor the build pass now, thanks for help.

**Comment by kisvegabor** [comment]
Thank you @xiaoxiang781216 and @amirgon.

Merging!

**Pull request merged**
