### PR TITLE
chore: run pre-commit in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
### Description of the feature or fix

Was #4687

### CODE REVIEW

**Comment by szepeviktor** [comment]
@kisvegabor It does work.

**Comment by szepeviktor** [comment]
[off] YAML Specs suggest this "non-compact" formatting.
https://github.com/szepeviktor/lvgl/blob/yaml-specs/.pre-commit-config.yaml

https://yaml.org/spec/1.2.2/#21-collections / "Example 2.4 Sequence of Mappings"

**Comment by kisvegabor** [comment]
I think it doesn't find `astyle`'s config file. See [here](https://github.com/lvgl/lvgl/blob/master/scripts/code-format.cfg).

**Comment by szepeviktor** [comment]
> Trim Trailing Whitespace.................................................Failed
> - hook id: trailing-whitespace
> - exit code: 1
> - files were modified by this hook

I think this hook cause the changes
https://github.com/pre-commit/pre-commit-hooks/blob/main/pre_commit_hooks/trailing_whitespace_fixer.py

Could you please run it locally?

**Comment by szepeviktor** [comment]
Code formatting said this.

> Formatting source files..................................................Failed
> - hook id: format-source
> - duration: 9.31s
> - files were modified by this hook
> 
> Formatted  demos/multilang/assets/fonts/font_multilang_large.c
> Formatted  demos/music/assets/spectrum_3.h
> Formatted  tests/unity/unity_internals.h
> Formatted  demos/benchmark/assets/lv_font_benchmark_montserrat_28_compr_az.c.c
> Formatted  demos/music/assets/spectrum_1.h
> Formatted  demos/benchmark/assets/lv_font_benchmark_montserrat_16_compr_az.c.c
> Formatted  demos/music/assets/spectrum_2.h
> Formatted  tests/src/test_assets/font_3_bin.c
> Formatted  demos/multilang/assets/fonts/font_multilang_small.c
> Formatted  demos/benchmark/assets/lv_font_benchmark_montserrat_12_compr_az.c.c
> Formatted  tests/src/test_assets/font_2_bin.c
> Formatted  tests/src/test_assets/font_1_bin.c
> Formatted  tests/unity/unity.c

**Comment by kisvegabor** [comment]
> Could you please run it locally?

It haven't changed anything :slightly_frowning_face: 

> Formatted tests/unity/unity_internals.h

It should have been excluded by [this](https://github.com/lvgl/lvgl/blob/master/scripts/code-format.cfg#L43).

**Comment by szepeviktor** [comment]
> > Could you please run it locally?
> 
> It haven't changed anything 🙁

Do you have locally this line?
```
Trim Trailing Whitespace.................................................(something)
```

**Comment by kisvegabor** [comment]
Sorry for the delay.

If I comment something when nothing was changed, I get this:
image

**Comment by szepeviktor** [comment]
I see!

On your machine not all file are checked!
Try  `pre-commit run --all-files`

**Comment by kisvegabor** [comment]
It really modified a lot of files, but we have excluded several files mainly because they are 3rd party libs that we would like to use "as it is" as much as possible.

**Comment by szepeviktor** [comment]
All right.
Please decide what to do now.

**Comment by kisvegabor** [comment]
Please use [code-format.cfg](https://github.com/lvgl/lvgl/blob/master/scripts/code-format.cfg) and [.typos.toml]( https://github.com/lvgl/lvgl/blob/master/.typos.toml) in the CI too. 

It will ensure that the CI does the same thing as a the local pre-commit hook.

**Comment by szepeviktor** [comment]
Whet to do with trailing space?

https://github.com/lvgl/lvgl/blob/605379ab3cb8fe5983f463ad5297cb0cef75e773/.pre-commit-config.yaml#L7

**Comment by szepeviktor** [comment]
> By default, this action runs **all the hooks against all the files**.

https://github.com/pre-commit/action#using-this-action-with-custom-invocations

**Comment by szepeviktor** [comment]
Testing pre-commit hook with the last commit ...

✔️ `Trim Trailing Whitespace.................................................Passed`

❌ `Formatting source files..................................................Failed`

Modifies these files. These files are not excluded in [code-format.cfg](https://github.com/lvgl/lvgl/blob/master/scripts/code-format.cfg)
```
Formatted  demos/benchmark/assets/lv_font_benchmark_montserrat_12_compr_az.c.c
Formatted  demos/benchmark/assets/lv_font_benchmark_montserrat_16_compr_az.c.c
Formatted  demos/benchmark/assets/lv_font_benchmark_montserrat_28_compr_az.c.c
Formatted  demos/multilang/assets/fonts/font_multilang_large.c
Formatted  demos/multilang/assets/fonts/font_multilang_small.c
Formatted  demos/music/assets/spectrum_1.h
Formatted  demos/music/assets/spectrum_2.h
Formatted  demos/music/assets/spectrum_3.h
Formatted  src/core/lv_obj_style_gen.c
Formatted  src/core/lv_obj_style_gen.h
Formatted  tests/src/test_assets/font_1_bin.c
Formatted  tests/src/test_assets/font_2_bin.c
Formatted  tests/src/test_assets/font_3_bin.c
Formatted  tests/unity/unity.c
Formatted  tests/unity/unity_internals.h
```

**Comment by szepeviktor** [comment]
Something is very wrong here.
`code-format.py` expects `scripts/` to be the current directory which is not the case when pre-commit is running.

**Comment by szepeviktor** [comment]
And I think `"../src/*.c,*.h"` in code-format.py matches

`../src/*.c` AND `*.h`
not `../src/*.c` AND `../src/*.h`

**Comment by kisvegabor** [comment]
What do you see if you run 
```
cd scripts
./code-format.py
```
?

I see that the files you have mentioned are no excluded but for me they are not updates either.

**Comment by szepeviktor** [comment]
Because that Python script does not process the whole repo/every file.
But pre-commit in CI does process every file!

**Comment by kisvegabor** [comment]
In a PR we have added a new lib to `src/libs` and typos updated it although this folder was excluded [here](https://github.com/lvgl/lvgl/blob/master/.typos.toml#L6). I had no better idea than excluding the folder in `.pre-commit-config.yaml` like [this](https://github.com/lvgl/lvgl/pull/4691/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R37-R40) and now it works. 

So I wonder if the issue we see here is related to exluding folder is not working as expected in the `.typos.toml`?

**Comment by szepeviktor** [comment]
> and typos updated it although this folder was excluded [here](https://github.com/lvgl/lvgl/blob/master/.typos.toml#L6)

When pre-commit adds files on the command line to typos, typos will not use it's ignore list.
There is a pre-commit option not to do that.

**Comment by kisvegabor** [comment]
Shouldn't we use that config option to have more consistent behavior?

**Comment by szepeviktor** [comment]
Here it is
https://pre-commit.com/#hooks-pass_filenames
```
pass_filenames: false
```

**Comment by szepeviktor** [comment]
Please decide whether every fixable thing should be fixed or not.

**Comment by kisvegabor** [comment]
To make the CI and a the local run compatible I would like to run all of these only on the changed files.

**Comment by szepeviktor** [comment]
Thank you for your answer.

I let you implement that.

**Comment by szepeviktor** [comment]
Viktor cleans up every byte, even old bytes!

**Pull request closed without merging**
