### PR TITLE
fix(fsdrv/fatfs): support FF_DIR and FATFS_DIR typedef in ff.h

### LINKED ISSUE #6078: Compilation error for FATFS
### LVGL version

v9.1.0

### What happened?

Enabled LV_USE_FS_FATFS in lv_conf,h and got the following error:
.pio/libdeps/esp32-s3-devkitc-1/lvgl/src/libs/fsdrv/lv_fs_fatfs.c:228:5: error: unknown type name 'DIR'; did you mean 'DDR'?

### How to reproduce?

#define LV_USE_FS_FATFS 1
#if LV_USE_FS_FATFS
    #define LV_FS_FATFS_LETTER 'F'     /*Set an upper cased letter on which the drive will accessible (e.g. 'A')*/
    #define LV_FS_FATFS_CACHE_SIZE 0    /*>0 to cache this number of bytes in lv_fs_read()*/
#endif

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

Fixes #6078

See the issue for more details.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Can't we add the defines below `#include "ff.h"` to be sure that the new names won't mess up anything in `ff.h`?

**Comment by liamHowatt** [comment]
Manipulating the contents of ff.h is the point of putting the defines before the include. To convey that I should `undef` it right after the include.

Ideally we'd detect what the platform has renamed `DIR` to and put the define after the header.

Or something like this pseudocode:
```c
#incude "ff.h"

#if (defined(ESP32) && !defined(ARDUINO)) || defined(ESP_IDF)
#define DIR FF_DIR
#elif defined(MBED_MAJOR_VERSION)
#define DIR FATFS_DIR
#endif

**Comment by liamHowatt** [comment]
Actually, IIRC Mbed users would not use lv_fs_fatfs. They'd use lv_fs_stdio which maps to Mbed's own FATFS adapter. So maybe we can ignore FATFS_DIR and only worry about FF_DIR. But the problem still stands, how to we conditionally define DIR as FF_DIR when on ESP IDF?

**Comment by kisvegabor** [comment]
Still don't get it. ESP's `"ff.h"` is working internally, and the problem is that it defines `FF_DIR` but we use `DIR` in `lv_fs_fatfs.c`. Is that correct? 

If so, all we need to do in `lv_fs_fatfs.c` is telling  that `FF_DIR` also means `DIR` by adding `#define FF_DIR DIR` after `ff.h`.

**Comment by liamHowatt** [comment]
> `"ff.h"` is working internally, and the problem is that it defines FF_DIR but we use DIR in lv_fs_fatfs.c. Is that correct?

Correct.

> If so, all we need to do in `lv_fs_fatfs.c` is telling that `FF_DIR` also means `DIR` by adding `#define FF_DIR DIR` after `ff.h`.

I'm afraid `#define FF_DIR DIR` won't work. That define would mean replace any instance of the token `FF_DIR` with `DIR` after this define. There are no more `FF_DIR` tokens _after_ the include of `"ff.h"` was already done. Look at what worked for @brandon-kim https://github.com/lvgl/lvgl/issues/6078#issuecomment-2063024388. They did `#define DIR FF_DIR` which replaces all `DIR` in `lv_fs_fatfs.c` with `FF_DIR` to match how `"ff.h"` has defined it. That works only if the `"ff.h"` uses `FF_DIR`. If it used `DIR`, we don't want that define.

So my idea was to manipulate the names inside `"ff.h"` to be `DIR` in case they're not.

**Comment by kisvegabor** [comment]
> I'm afraid #define FF_DIR DIR won't work.

Oh, sorry, you are right. It should be `#define DIR FF_DIR` after `#include "ff.h"`. If there is no objection let's use it not affect `ff.h` by any means.

**Comment by liamHowatt** [comment]
Ah but you see, if they're using the variant of `"ff.h"` that defines the directory type as `DIR` (i.e. Arduino), then that `#define` would change all the `DIR` in `lv_fs_fatfs.c` to be `FF_DIR` which is incompatible with that variant of `"ff.h"`.

**Comment by kisvegabor** [comment]
I mean adding the define with a guard. Sorry for being vague. So
```c
#include "ff.h"
#ifdef ESP_PLATFORM
#define DIR FF_DIR
#endif
```

Can it work?

**Comment by liamHowatt** [comment]
So there is a preprocessor define for ESP. I think that is the best solution. [Reference](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#preprocessor-definitions)

@mgaman @brandon-kim @anujdeshpande thanks for helping. Would someone be able to validate the solution in their ESP IDF environment?

**Comment by adcr8iv** [comment]
> Would someone be able to validate the solution in their ESP IDF environment?

Tested - works as expected @liamHowatt

**Comment by anujdeshpande** [comment]
Tested - works as expected [@liamHowatt](https://github.com/liamHowatt)

**Review by kisvegabor — APPROVED** [review]
Thank you all! :+1:

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
