### PR TITLE
docs: fix build error

### PR DESCRIPTION
**Pull request by kisvegabor**
Help us review this PR! Anyone can [approve it or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### Description of the feature or fix

Fixes https://github.com/lvgl/lvgl/actions/runs/7570722825/job/20616649888

As the docs is not build in CI on PRs and the examples for the docs are not built locally either it's hard to test these issues...

### Checkpoints
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)

### CODE REVIEW

**Comment by lhdjply** [comment]
This error occurs in #5367.
Why can CI pass when there is an error?

**Comment by kisvegabor** [comment]
As the docs is not build in CI on PRs and the examples for the docs are not built locally either it's hard to test these issues...

**Review by PGNetHun — APPROVED** [review]

**Comment by kisvegabor** [comment]
> But in https://github.com/lvgl/lvgl/pull/5378,CI can again indicate this problem

I can't see these warnings now.

**Comment by lhdjply** [comment]
> I can't see these warnings now.

I read it wrong. It's #5380 

Screenshot_20240118_221634_com huawei browser

**Review by lhdjply — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
