### PR TITLE
add fade mask example for roller obj

### PR DESCRIPTION
**Pull request by guoweilkd**
### Description of the feature or fix

add fade mask example for roller obj。

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by guoweilkd** [comment]
how to include `lv_draw.h`？

**Comment by embeddedt** [comment]
It's already included. The issue is that the tests try to build LVGL in both drawing modes `LV_DRAW_COMPLEX == 0` and `LV_DRAW_COMPLEX == 1`. In the former, masks are unavailable.

The simplest solution is probably to just add `&& LV_DRAW_COMPLEX` to [this line](https://github.com/lvgl/lvgl/blob/a5d6cc4a908f588d00d482263bb2eb369e34b283/examples/widgets/roller/lv_example_roller_3.c#L2).

EDIT: OTOH, @kisvegabor just added `lv_draw.h` to `lvgl.h` so maybe it really was missing. I think the above mentioned problem still exists.

**Comment by kisvegabor** [comment]
Yes, I've just added `lv_draw.h` to `lvgl.h` but `LV_DRAW_COMPLEX` really should be tested with `#if LV_USE_ROLLER && LV_BUILD_EXAMPLES`.

**Comment by kisvegabor** [comment]
Thank you!
The MicroPYthon build fails due to an unrelated reason.

**Pull request merged**
