### PR TITLE
chore(env_support/cmake): add `LV_LINK_LIBRARIES` to `custom.cmake`

### LINKED ISSUE #6957: lvgl via CMake FetchContent + SDL does not allow for linking SDL to lvgl
### LVGL version

0daebca18b2e7d4c51d5b53e7f2a60df634850f2

### What happened?

I'm trying to set up a project using lvgl via FetchContent and SDL.

The problem is that lvgl's CMake doesn't seem to provide a way to link SDL to `lvgl::lvgl` target when using it via `FetchContent`.

If I don't link SDL, I get a build error:

```
FAILED: _deps/lvgl-build/CMakeFiles/lvgl.dir/src/drivers/sdl/lv_sdl_keyboard.c.o 
/usr/bin/cc -DLV_CONF_INCLUDE_SIMPLE -DLV_CONF_PATH=platforms/sdl3/lv_conf.h -DLV_LVGL_H_INCLUDE_SIMPLE -isystem build/_deps/lvgl-src -isystem platforms/sdl3 -isystem build/_deps/lvgl-build -g -MD -MT _deps/lvgl-build/CMakeFiles/lvgl.dir/src/drivers/sdl/lv_sdl_keyboard.c.o -MF _deps/lvgl-build/CMakeFiles/lvgl.dir/src/drivers/sdl/lv_sdl_keyboard.c.o.d -o _deps/lvgl-build/CMakeFiles/lvgl.dir/src/drivers/sdl/lv_sdl_keyboard.c.o -c build/_deps/lvgl-src/src/drivers/sdl/lv_sdl_keyboard.c
In file included from build/_deps/lvgl-src/src/drivers/sdl/../../display/../misc/../lv_conf_internal.h:54,
                 from build/_deps/lvgl-src/src/drivers/sdl/../../display/../misc/lv_types.h:16,
                 from build/_deps/lvgl-src/src/drivers/sdl/../../display/lv_display.h:16,
                 from build/_deps/lvgl-src/src/drivers/sdl/lv_sdl_window.h:17,
                 from build/_deps/lvgl-src/src/drivers/sdl/lv_sdl_keyboard.h:16,
                 from build/_deps/lvgl-src/src/drivers/sdl/lv_sdl_keyboard.c:9:
platforms/sdl3/lv_conf.h:1041:37: fatal error: SDL3/SDL.h: No such file or directory
 1041 |     #define LV_SDL_INCLUDE_PATH     <SDL3/SDL.h>
```

If I try to link SDL to lvgl like this:

```cmake
target_link_libraries(lvgl::lvgl PRIVATE SDL3::SDL3)
```

Then I get the following error:

```cmake
CMake Error at platforms/sdl3/CMakeLists.txt:5 (target_link_libraries):
  Cannot specify link libraries for target "lvgl::lvgl" which is not built by
  this project.
```

This error is expected, one can't modify targets imported via FetchContent after all.
lvgl currently provides no ways to customize the libraries linked to it.

Adding a variable for this to https://github.com/lvgl/lvgl/blob/master/env_support/cmake/custom.cmake is probably the way to fix this (e.g. `LV_LINK_LIBRARIES` that the user can then set up before FetchContent).
Is this the right place to report this issue?

### How to reproduce?

Create a CMake project following this guide: https://docs.lvgl.io/8.2/get-started/cmake.html

Then, in `lv_conf.h`, `#define LV_USE_SDL 1`

### PR DESCRIPTION
**Pull request by glebm**
Allow the user to specify custom libraries to link to LVGL when used via `FetchContent`.
For example, this allows for specifying the SDL library when using `LV_USE_SDL`.

Fixes #6957

Example of using these new variables for linking with SDL2 and using a defconfig-based config file:
https://github.com/glebm/lvgl-cmake-example

### CODE REVIEW

**Comment by kisvegabor** [comment]
I understand the problem, and although I'm so good with CMake it seems like a flexible solution.  This updates shall be  mentioned in the [docs](https://github.com/lvgl/lvgl) too. 

If feel like our current CMake docs could use a little but of extra care in general. Now it's too heavy on `CMakePresets` but in should be only an option. A correct description for the variables can passed/used is also missing. Some examples for complex use cases like `FetchContent` would be amazing too.

If you had a little bit of extra time and interest to improve our CMake docs I'm sure that a good amount of developer would praise your name. :pray: :blush:

**Comment by glebm** [comment]
I'd be happy to publish an example repo once this is merged.

So far, I've achieved the following in a private repo:
1. `defconfig`-based lvgl configuration, using python's kconfiglib to generate the header file.
2. SDL2 support entirely via `FetchContent`-based lvgl.

The docs are still in flux as CMake integration is still being worked out.

Is anything blocking the merge of this?

**Comment by glebm** [comment]
Here is an example project (currently points to my fork of lvgl because it needs this PR):

https://github.com/glebm/lvgl-cmake-example

**Comment by glebm** [comment]
I'm starting to think that a better long-term approach for would be to do both the SDL2 linking and `defconfig` support entirely within lvgl itself. If you agree, I can try to implement it.

**Comment by glebm** [comment]
After implementing support directly in #6973 and #6974, I do think it's a much better approach.

**Pull request closed without merging**
