### PR TITLE
chore(ci): add informational Codecov status checks

### PR DESCRIPTION
**Pull request by thomasrockhu-codecov**
### Description of the feature or fix

Hi, Tom from Codecov here. I noticed that you were using Codecov but weren't actually getting any notifications on pull requests. I figured it would be useful to get some idea if code being changed is being tested, but also not blocking CI/merging. Let me know if this makes sense or if we can do something that would be helpful.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi Tom,

Thanks for opening the PR. 

We have disabled notifications because the coverage is still quite low. We were planning to enable them once we have good (~90%) coverage. 

cc @embeddedt

**Comment by kisvegabor** [comment]
I'd like to wait with enabling coverage report until all core functionalities get unit tests. After that it will be reasonable to ask for tests too in PRs.

**Comment by embeddedt** [comment]
I agree, otherwise every contribution will likely be accompanied by the Codecov action reporting reduced coverage. If I understand correctly, once it's enabled, it requires any PR to have the same or increased coverage compared to the base branch.

**Comment by embeddedt** [comment]
Let's wait for some more tests to be added as @kisvegabor suggested and then we can merge this.

**Pull request closed without merging**
