### PR TITLE
fix(transparency): call flush callback before clearing framebuffer

### PR DESCRIPTION
**Pull request by ambecker**
### Description of the feature or fix

I use a SoC taht supports different, independent graphical layers.
These layers will be alpha-blenden by the hardware of the SoC and therefor I need a OSD Layer with support of transparency.

After following the documentation I received a fully transparent LVGL Framebuffer without any content although the framebuffer was filled before. Debugging showed me that the active Framebuffer is filled with zeroes **BEFORE** the flush callback was called.

After changing this order, my framebuffer was fine.

I did **not** check all other options or combination of options for possible side-effects of my change, because I am not that deep in LVGL that I could overlook all Feature.

I created the PullRequest for master branch although I use Release 8.3.1.
I was not sure if it is still possible to contribute to 8.3.x.
If yes I would really appreciate if this could be merged to 8.3.x as well.

### CODE REVIEW

**Comment by kisvegabor** [comment]
This part really seems messed up a little bit.  Please try it out with this patch 
[a.patch.zip](https://github.com/lvgl/lvgl/files/9436005/a.patch.zip).


From what I could test on PC it works well.

**Comment by ambecker** [comment]
I tried your patch and it works very well for me.  :-)

**Comment by kisvegabor** [comment]
Great! I fixed in the `release/v8.3` branch. This part will be changed in master soon so I haven't cherry-picked this change yet.

**Comment by ambecker** [comment]
Thanks a lot for your great support.
LVGL works really great for me. :-)

**Comment by kisvegabor** [comment]
Happy to hear that :slightly_smiling_face:

**Pull request closed without merging**
