### PR TITLE
Rework default font initialisation so they can be excluded from the build.

### PR DESCRIPTION
**Pull request by hydra**
most of the changes involve moving some built-in font code and initialization to their own compilation units (files).

### CODE REVIEW

**Comment by hydra** [comment]
what's not obvious from this PR is that the `lv_fonts.c/.h` files now can be compiled without the default fonts being present on the file system. (I deleted them to check!), i.e:

```On branch custom-default-font
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    lv_misc/lv_fonts/lv_font_dejavu_10.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_10_cyrillic.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_10_latin_sup.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_20.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_20_cyrillic.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_20_latin_sup.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_30.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_30_cyrillic.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_30_latin_sup.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_40.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_40_cyrillic.c
        deleted:    lv_misc/lv_fonts/lv_font_dejavu_40_latin_sup.c
        deleted:    lv_misc/lv_fonts/lv_font_symbol_10.c
        deleted:    lv_misc/lv_fonts/lv_font_symbol_20.c
        deleted:    lv_misc/lv_fonts/lv_font_symbol_30.c
        deleted:    lv_misc/lv_fonts/lv_font_symbol_40.c
```

**Comment by hydra** [comment]
My lv_conf.h file looks like this:

```
/*==================
 *    FONT USAGE
 *===================*/

/* More info about fonts: https://littlevgl.com/basics#fonts */

#define USE_CUSTOM_DEFAULT_FONT            1 /* 0: use built-in font, 1: use custom font */

#if USE_CUSTOM_DEFAULT_FONT != 0
/* If you use custom fonts then remember to add your custom font using lv_font_add(&YourFont_Size); */

#define USE_DEFAULT_FONTS                  0 /* 0: Do not use any built-in fonts */
#define USE_TOPAZPLUS_A1200_8              0
#define USE_TOPAZPLUS_A1200_10             4

#define LV_FONT_CUSTOM_DECLARE \
    LV_FONT_DECLARE(TopazPlus_a1200_8) \
    LV_FONT_DECLARE(TopazPlus_a1200_10)

#define LV_FONT_DEFAULT                    &TopazPlus_a1200_10

#else
#define USE_DEFAULT_FONTS                  1 /* 1: Enable each default font as required below */
#define LV_FONT_DEFAULT                    &lv_font_dejavu_20     /*Always set a default font from the built-in fonts*/
#endif

#if USE_DEFAULT_FONTS != 0
/* To enable a built-in font use 1,2,4 or 8 values
 * which will determine the bit-per-pixel */
#define USE_LV_FONT_DEJAVU_10              0
#define USE_LV_FONT_DEJAVU_10_LATIN_SUP    0
#define USE_LV_FONT_DEJAVU_10_CYRILLIC     0
#define USE_LV_FONT_SYMBOL_10              0

#define USE_LV_FONT_DEJAVU_20              4
#define USE_LV_FONT_DEJAVU_20_LATIN_SUP    0
#define USE_LV_FONT_DEJAVU_20_CYRILLIC     0
#define USE_LV_FONT_SYMBOL_20              4

#define USE_LV_FONT_DEJAVU_30              0
#define USE_LV_FONT_DEJAVU_30_LATIN_SUP    0
#define USE_LV_FONT_DEJAVU_30_CYRILLIC     0
#define USE_LV_FONT_SYMBOL_30              0

#define USE_LV_FONT_DEJAVU_40              0
#define USE_LV_FONT_DEJAVU_40_LATIN_SUP    0
#define USE_LV_FONT_DEJAVU_40_CYRILLIC     0
#define USE_LV_FONT_SYMBOL_40              0
#endif
```

**Comment by hydra** [comment]
PR updated as per discussion in #291 
Examples above edited.

**Comment by kisvegabor** [comment]
Thank you!

I have 2 questions:
1. What is the advantage of moving the default font initialization to lv_default_font.c?
2. What is the advantage of using `USE_CUSTOM_DEFAULT_FONT`? As I see the user have the opportunity to disable all built in fonts by setting `USE_LV_FONT_...` to `0`

**Comment by hydra** [comment]
1. its a dependency improvement.  the font code doesnt need and shouldnt care about the list of fonts that are used.  the compilation dependency is correct now.  it was pointing the wrong way when the font utility code made the decision.  its the responsibilty of application to make the decision of which fonts to use.

**Comment by kisvegabor** [comment]
I agree, thank you!

And what about point 2? "What is the advantage of using USE_CUSTOM_DEFAULT_FONT? "
It seems to me clearer:
```c

/* More info about fonts: https://littlevgl.com/basics#fonts
 * To enable a built-in font use 1,2,4 or 8 values
 * which will determine the bit-per-pixel (0 to disable the font)*/
#define USE_LV_FONT_DEJAVU_10              0
#define USE_LV_FONT_DEJAVU_10_LATIN_SUP    0
#define USE_LV_FONT_DEJAVU_10_CYRILLIC     0
#define USE_LV_FONT_SYMBOL_10              0

#define USE_LV_FONT_DEJAVU_20              0
#define USE_LV_FONT_DEJAVU_20_LATIN_SUP    0
#define USE_LV_FONT_DEJAVU_20_CYRILLIC     0
#define USE_LV_FONT_SYMBOL_20              0

#define USE_LV_FONT_DEJAVU_30              0
#define USE_LV_FONT_DEJAVU_30_LATIN_SUP    0
#define USE_LV_FONT_DEJAVU_30_CYRILLIC     0
#define USE_LV_FONT_SYMBOL_30              0

#define USE_LV_FONT_DEJAVU_40              0
#define USE_LV_FONT_DEJAVU_40_LATIN_SUP    0
#define USE_LV_FONT_DEJAVU_40_CYRILLIC     0
#define USE_LV_FONT_SYMBOL_40              0

#define LV_FONT_CUSTOM_DECLARE             LV_FONT_DECLARE(synch) \
					   LV_FONT_DECLARE(uniscii) \

#define LV_FONT_DEFAULT        &synch     /*Always set a default font from the built-in fonts*/
```

**Comment by hydra** [comment]
sorry, didn't have to answer point 2 yesterday, here goes:

It's only used in the lv_conf.h, I added it so that it was easy to see how the other related settings are used. 

actually, now I look at the code I see a couple of issues, I will add another commit to the branch to fix it.

Feel free to clean that up to your liking before merging the branch or let me know if you'd like me to change anything.

**Comment by kisvegabor** [comment]
Because of the "multi-level" `#if`-s I rather feel confusing and harder to read your suggested lv_conf_templ.h. So I would prefer "plain" version (as in my example above). Maybe a comment to leave  `LV_FONT_CUSTOM_DECLARE` blank if no custom fonts, and and example how to add more custom fonts are used would be useful.

Would you like to update the PR this way?

**Comment by kisvegabor** [comment]
Based on your suggestion I moved the initialization of built-in fonts to a different file (lv_font_builin.c/h) and added  `LV_FONT_CUSTOM_DECLARE` to lv_conf_templ.h

Finally, I let to the user to disable the built-in fonts one-by-one if they are not required at all. 
I found easier to implement these changes myself instead of merging the pull request and modify it. I hope you don't mind. 

Thank you for point out these issues.

**Comment by hydra** [comment]
no problem, glad to be of help.

**Comment by TheGrovesy** [comment]
Im looking at adding custom fonts too so its nice to see this recent work. Do you have any more idea when the next stable release will be? Keep up the good work.

**Pull request closed without merging**
