### PR TITLE
updated several lvgl Python examples to synchronize with changes in t…

### PR DESCRIPTION
**Pull request by uraich**
…he C code

### Description of the feature or fix

Updated several Python examples to synchronize with changes in the C examples

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you, Uli.

Let me know if I can merge it.

**Comment by uraich** [comment]
Hi Gabor,
I think these modifications are ready and can be merged. 
Did you check lv_example_canvas_1.c which does not work any more? 
When trying to build the C examples with lv_port_pc_eclipse using the latest master I get plenty of warnings that lvgl master is currently unstable and this error:
image
Being able to compare to the C code would be helpful to correct the missing Python examples (lv_example_label_4 and the above canvas example)

**Comment by amirgon** [comment]
@uraich does `lv_example_snapshot_1.py` work correctly?
I think it uses an obsolete enum `CF`:

https://github.com/lvgl/lvgl/blob/7854d5504636c1261d0ac1f18d9ed427ebcd3b32/examples/others/snapshot/lv_example_snapshot_1.py#L33

https://github.com/lvgl/lvgl/issues/4011 inidcates that "LV_IMG_CF_... was removed and was replaced by LV_COLOR_FORMAT_..."

**Comment by uraich** [comment]
@amirgon: You are of course right! In fact I only went through the examples mentioned  by @kdschlosser in issue #3945 and since this example was not mentioned, I did not see the problem.
I will update the PR.
There is another problem, which has to do with the font files: When I see:
#if LV_FONT_MONTSERRAT_20
I try to dynamically load the font file. I should however also check if the font file is available. This will also be corrected.

**Comment by kdschlosser** [comment]
Sorry about this being such a HUGE headache to get done. I think over time changes were made and updating the examples got put on the back burner and forgotten about.

**Comment by uraich** [comment]
@kdschlosser : Unfortunately I am not able to permanently follow all the changes to lvgl and therefore these types of problems tend to accumulate. There is no reason to be sorry. Quite on the contrary: It was much easier for me to follow your error reports than to go to each example and check it myself.

**Comment by kdschlosser** [comment]
I am more then happy to go through the examples from time to time to check for functionality and give suggestions if any new examples are added.

I know the reports I gave were not the greatest and I am sure that I did miss some things. I was just trying to show some of the errors.

I have a couple of questions 

Does the simulator support autocomplete. It seems like it does for things that have already been typed out in a script but would it be able to if a stub file was provided to it for LVGL?

How come LVGL is not built with all of the fonts? why is there a need to dynamically load some of them?

**Comment by uraich** [comment]
Font file tend to be rather big and resources on micro-controllers can be sparse.

**Comment by kdschlosser** [comment]
I get that. but in the simulator this problem doesn't exist. It would make it easier if the user could access all fonts as if it was compiled with it because that is what they would do when they built it to run locally.

I am thinking of the simulator being able to be used for more than just the examples. They could use it to develop with and be able to see the changes made without having to compile/upload to the MCU to see changes.

**Comment by uraich** [comment]
@kdschlosser : You are right, but I was only talking about the standard distribution of lv_micropython and the examples that can be run online. If you need a lv_micropython version with all fonts enabled, you can easily create this, enabling all fonts in lv_conf.h and rebuilding the interpreter.

**Comment by kdschlosser** [comment]
I am talking about in the online simulator that is already compiled for javascript.

**Comment by amirgon** [comment]
> I am talking about in the online simulator that is already compiled for javascript.

Currently the online simulator uses the same `lv_conf.h` as the unix port.  
It's possible to build it with a different `lv_conf.h` that includes the original one and overrides some parameters, but that would be another configuration file to maintain.  
If you need this, feel free to open a PR and we'll consider it.

**Comment by uraich** [comment]
@amirgon : I am seeing strange effects on the event examples. When running lv_example_event_1 with emscripten on the lvgl doc page I see this:
image
If I do a copy/paste and run the same program on my lv_micropython it runs just fine.
When I run lv_example_event_3, the scollbar first does not show up. 
image
Scrolling however works and the scrollbar appears when starting to scroll:
image
When setting the container size to 290,200 as done in the C code, only 2 buttons per row appear.

**Comment by amirgon** [comment]
> When running lv_example_event_1 with emscripten on the lvgl doc page I see this:

The online simulator is based on the main branch of lv_micropython, which is not yet aligned with latest changes.  
Until I merge the arch/drivers branch into master I think it's best to rely on local lv_micropython unix port.
LVGL automatic tests are based on arch/drivers lv_micropython branch, so they are expected to pass on LVGL master branch.

> When I run lv_example_event_3, the scollbar first does not show up.
> When setting the container size to 290,200 as done in the C code, only 2 buttons per row appear.

I don't know how this can be related to the bindings. I would assume the same would happen on the C example when using the same screen size and fonts.

**Comment by uraich** [comment]
After @kisvegabor has adapted lv_port_pc_eclipse as well as lv_example_label_4.c, I was able to get lv_example_label_4.py working. 
This is the last missing update from @kdschlosser 's list of problems I know of.
Only problems of the Python port have been addressed and not problems that already exist in the C code.
@kisvegabor : The horizontal container size in lv_example_event_3.c should be increased from 290 to 320.

**Comment by kisvegabor** [comment]
> The horizontal container size in lv_example_event_3.c should be increased from 290 to 320.

@uraich I've rather changed the size of the buttons to 70. See 28d4bff44

**Comment by kisvegabor** [comment]
Thank you very much @uraich.

I merge it now. If new issues come up let open a new issue or PR.

**Pull request merged**
