### PR TITLE
fix(benchmark): improve the benchmark

### PR DESCRIPTION
**Pull request by kisvegabor**
### Description of the feature or fix

- Ensure that at least one image/arc/etc is added
- Measure the  flush wait time too

Please test and review it in as many cases as possible. Is it looks good and the reported data is consistent, I'll migrate the same idea to v8. 

@nicusorcitu @zjanosy @KamranAghlami  @espzav

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by PGNetHun — DISMISSED** [review]

**Comment by espzav** [comment]
For me, it is same for v9.0.0 and this PR. I have problem stucked here:


```
I (1065) main_task: Returned from app_main()
E (47233) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
E (47233) task_wdt:  - IDLE0 (CPU 0)
E (47233) task_wdt: Tasks currently running:
E (47233) task_wdt: CPU 0: LVGL task
E (47233) task_wdt: CPU 1: IDLE1
E (47233) task_wdt: Print CPU 0 (current core) backtrace


Backtrace: 0x4203AB56:0x3FC9C560 0x4037C2ED:0x3FC9C590 0x42016BC0:0x3FCB9350 0x42015B87:0x3FCB9370 0x420162A9:0x3FCB93A0 0x420224FA:0x3FCB9430 0x42022655:0x3FCB9460 0x4200E23C:0x3FCB9480
0x4203ab56: task_wdt_timeout_handling at C:/WORK/GIT/esp-idf_GitLab/components/esp_system/task_wdt/task_wdt.c:434
 (inlined by) task_wdt_isr at C:/WORK/GIT/esp-idf_GitLab/components/esp_system/task_wdt/task_wdt.c:507

0x4037c2ed: _xt_lowint1 at C:/WORK/GIT/esp-idf_GitLab/components/xtensa/xtensa_vectors.S:1240

0x42016bc0: lv_draw_dispatch at C:/WORK/GIT/esp-bsp-01/examples/display_lvgl_demos/components/lvgl__lvgl/src/draw/lv_draw.c:165

0x42015b87: draw_buf_flush at C:/WORK/GIT/esp-bsp-01/examples/display_lvgl_demos/components/lvgl__lvgl/src/core/lv_refr.c:1001
 (inlined by) refr_area_part at C:/WORK/GIT/esp-bsp-01/examples/display_lvgl_demos/components/lvgl__lvgl/src/core/lv_refr.c:724

0x420162a9: refr_area at C:/WORK/GIT/esp-bsp-01/examples/display_lvgl_demos/components/lvgl__lvgl/src/core/lv_refr.c:650
 (inlined by) refr_invalid_areas at C:/WORK/GIT/esp-bsp-01/examples/display_lvgl_demos/components/lvgl__lvgl/src/core/lv_refr.c:566
 (inlined by) _lv_display_refr_timer at C:/WORK/GIT/esp-bsp-01/examples/display_lvgl_demos/components/lvgl__lvgl/src/core/lv_refr.c:374

0x420224fa: lv_timer_exec at C:/WORK/GIT/esp-bsp-01/examples/display_lvgl_demos/components/lvgl__lvgl/src/misc/lv_timer.c:300 (discriminator 2)
 (inlined by) lv_timer_handler at C:/WORK/GIT/esp-bsp-01/examples/display_lvgl_demos/components/lvgl__lvgl/src/misc/lv_timer.c:105 (discriminator 2)

0x42022655: lv_timer_handler at C:/WORK/GIT/esp-bsp-01/examples/display_lvgl_demos/components/lvgl__lvgl/src/misc/lv_timer.c:71

0x4200e23c: lvgl_port_task at C:/WORK/GIT/esp-bsp-01/components/esp_lvgl_port/src/lvgl9/esp_lvgl_port.c:154
```

**Comment by espzav** [comment]
The next thing that I discovered is: When I used `lv_demo_music()` and the FPS monitor is disabled (in default), on the last view is "text" instead of FPS value. I didn't see any warning or something like that.

**Comment by kisvegabor** [comment]
I've added an important fix to correctly calculate the flush time

@espzav For the stuck at opa layered, please increase LV_MEM_SIZE

I'll look into the music player demo

**Review by PGNetHun — APPROVED** [review]

**Comment by kisvegabor** [comment]
I merge it now, and will beckport the changes to v8 today.

**Comment by PGNetHun** [comment]
oh, missing `flush_cnt`

**Comment by espzav** [comment]
> For the stuck at opa layered, please increase LV_MEM_SIZE

Thank you. I had 48 KB. Now, I have 100 KB and it is working.

**Comment by kisvegabor** [comment]
> oh, missing flush_cnt:

Ouch, fixed in  #5597.

**Comment by nicusorcitu** [comment]
@cristian-stoica

**Pull request merged**
