### PR TITLE
fix(format): run code-format.sh

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Checkpoints
- [X] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
I think we should do some automation on it. 
@embeddedt could you add an action similar to the `lv_conf_internal.h` checker? It'd throw an error if `git diff` is not empty after running the formatter.

We need to run it manually once, but now it breaks all the open PR. I'm checking them now and merge as much as possible. 

Probably `code-format.sh` should be rather `code-format.py` for cross-platform compatibility.

**Comment by xiaoxiang781216** [comment]
> I think we should do some automation on it. @embeddedt could you add an action similar to the `lv_conf_internal.h` checker? It'd throw an error if `git diff` is not empty after running the formatter.
> 

Good idea.

> We need to run it manually once, but now it breaks all the open PR. I'm checking them now and merge as much as possible.
>

After this patch, only some 3rd party files still contain the style warning:
```
        modified:   src/extra/libs/gif/gifdec.c
        modified:   src/extra/libs/gif/gifdec.h
        modified:   src/extra/libs/png/lodepng.c
        modified:   src/extra/libs/png/lodepng.h
        modified:   src/extra/libs/qrcode/qrcodegen.c
        modified:   src/extra/libs/qrcode/qrcodegen.h
        modified:   src/extra/libs/sjpg/tjpgd.c
        modified:   src/extra/libs/sjpg/tjpgd.h
        modified:   src/extra/libs/sjpg/tjpgdcnf.h
```
I left these files to make the future upgrade easier.

> Probably `code-format.sh` should be rather `code-format.py` for cross-platform compatibility.

Yes.

**Comment by kisvegabor** [comment]
> After this patch, only some 3rd party files still contain the style warning:

What do you mean by "style warning"?

**Comment by xiaoxiang781216** [comment]
> > After this patch, only some 3rd party files still contain the style warning:
> 
> What do you mean by "style warning"?

code-format.sh will change these files, because I exclude these files from PR.

**Comment by kisvegabor** [comment]
I see. But as these are 3rd party files they should be never formatted.  So we should exclude them in `code-format.cfg`. What do you think?

**Comment by xiaoxiang781216** [comment]
Yes, I think so. That's why I left them untouch.

**Comment by xiaoxiang781216** [comment]
> I see. But as these are 3rd party files they should be never formatted. So we should exclude them in `code-format.cfg`. What do you think?

Done.

**Comment by xiaoxiang781216** [comment]
After this patch get merged, we can add a new ci check to ensure there is no coding style violation.

**Comment by kisvegabor** [comment]
Great, thanks!

**Comment by embeddedt** [comment]
I've added a CI check. It will pass as long as the formatting matches `astyle`'s and will print the diff in the log otherwise.

**Comment by kisvegabor** [comment]
Perfect, thanks!

**Pull request merged**
