### PR TITLE
chore(porting): Add code helper to clip the display buffer

### PR DESCRIPTION
**Pull request by GorgonMeducer**
Help us review this PR! Anyone can [approve it or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### Description of the feature or fix

To follow the discussion in #5090 

### Checkpoints
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)

### CODE REVIEW

**Comment by kisvegabor** [comment]
@XuNeo Can't we use/have a `lv_draw_buf_` to readjust the stride of a buffer in place?

If not I suggest having a helper in `lv_draw_sw.c` similar to `lv_draw_sw_rgb565_swap()`.

**Comment by GorgonMeducer** [comment]
> If not I suggest having a helper in lv_draw_sw.c similar to lv_draw_sw_rgb565_swap().

Adding a helper is also a good idea.

**Comment by GorgonMeducer** [comment]
@kisvegabor @XuNeo 
Any updates about this?

**Comment by XuNeo** [comment]
> @XuNeo Can't we use/have a `lv_draw_buf_` to readjust the stride of a buffer in place?

Current `lv_draw_buf_adjust_stride` will create a new draw buf, we can change it to only adjust in place and return error if not possible to do so. The caller then need to decide to create a new draw buf and do draw buffer copy instead(with expected stride set).

**Comment by XuNeo** [comment]
@kisvegabor I think flush_cb should be update too to use draw_buf instead of pixel_map, which also affects porting code.

After that, https://github.com/lvgl/lv_binding_micropython/pull/311 also needs attention.

**Comment by kisvegabor** [comment]
> I think flush_cb should be update too to use draw_buf instead of pixel_map, which also affects porting code.

I'm not entirely sure about it. I think the simplicity of the `flush_cb` is a great value.  

In the rare cases when advanced users need to take care of stride, they can get it from the width of the area. The color format stored in the display. But it"s required only for the 1% of the users (I guess) and wouldn't make the API more complicated for the 99%.

**Comment by GorgonMeducer** [comment]
> But it"s required only for the 1% of the users (I guess) and wouldn't make the API more complicated for the 99%.

When people use GPUs that have alignment requirements and LCDs with window mode, we have to handle this.
So, how many devices would have GPU and LCD with window mode at same time? It is definitely more than 1%. I would bet at least 33%.

**Comment by GorgonMeducer** [comment]
> True, however if there is a GPU probably there is an LCD controller periphery too. And we can integrate it into LVGL. (Actually it's part of LVGL's deal with the vendors that we will add their LCD controllers).

That's why I say 33%.  LTDC requires a lot of pins, but LCDs with window mode are usually very cheap (so many people would use them) and only need a few pins for SPI. 

I just need a solution for this scenario.  Should we add a helper? (similar to rgb565_swap)

**Comment by XuNeo** [comment]
`flush_cb(draw_buf, area)` won't make things more complicated. They can deal with it as usual simply by `pixel_map = draw_buf->data` because the stride must be the simpler case.

Otherwise, for partial update mode with GPU support, `draw_buf` is a must.

**Comment by kisvegabor** [comment]
> flush_cb(draw_buf, area) won't make things more complicated. They can deal with it as usual simply by pixel_map = draw_buf->data because the stride must be the simpler case.

I feel this redundant as both `draw_buf` and `area` contains the width and height.

> Otherwise, for partial update mode with GPU support, draw_buf is a must.

Can't we convert the width of the area to stride?

**Comment by GorgonMeducer** [comment]
> Can't we convert the width of the area to stride?

LCD driver needs the width but not stride to set the window. We also know that stride can be bigger than width * pixel size

**Comment by kisvegabor** [comment]
I mean:
```c
int32_t w = lv_area_get_width(area);
int32_t stride = lv_draw_buf_width_to_stride(w, lv_display_get_color_format(display))
```

**Comment by GorgonMeducer** [comment]
> However I don't thinks this should be done before calling flush_cb. Better leaving it to driver to make decision.

No problem. I also think it is the developers' work to use the helper in their driver.

**Comment by kisvegabor** [comment]
The questions is what to do with the parameters of `flush_cb`. I'll comment about it in https://github.com/lvgl/lvgl/issues/5273

**Comment by XuNeo** [comment]
> Will you introduce this helper, i.e. `lv_draw_buf_adjust_stride_in_place ` ?

I plan to modify the behavior of `lv_draw_buf_adjust_stride` to do in place. Create a new draw buffer secretly in this API is not good. Better for user to manually create the new buffer when stride adjust fails.

@kisvegabor Hi Gabor, do you agree?

**Comment by kisvegabor** [comment]
> I plan to modify the behavior of lv_draw_buf_adjust_stride to do in place. Create a new draw buffer secretly in this API is not good. Better for user to manually create the new buffer when stride adjust fails.

I perfectly agree.

**Comment by GorgonMeducer** [comment]
Do we have any update for this? Any helper? solution ?
@XuNeo @kisvegabor

**Comment by kisvegabor** [comment]
I consider `lv_draw_buf_adjust_stride` an internal API, so we can added after the release.

**Comment by GorgonMeducer** [comment]
OK, no problem.

**Pull request closed without merging**
