### PR TITLE
fix(cmake) fix install

### LINKED ISSUE #6478: custom.cmake cannot install lvgl.pc
### LVGL version

v8.4

### What happened?

When I issue sudo make install on raspberry pi I get the error 
`CMake Error at _deps/lvgl-build/cmake_install.cmake:70 (file):
  file INSTALL cannot find "/home/pi/sdrberry/build/lvgl.pc": No such file or
  directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
`
I don't use this file and also don't know why it is necessary, can it be removed? Or issue fixed. Because cmake will stop and don't install the application.

### How to reproduce?
In CMakeList.txt I fetch lvgl with 
`FetchContent_Declare(lvgl GIT_REPOSITORY  https://github.com/lvgl/lvgl.git GIT_TAG v8.4.0)`
Install with:
`sudo make install`

### PR DESCRIPTION
**Pull request by kisvegabor**
Fixes #6478
Needs to be back ported to v8

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by liamHowatt — APPROVED** [review]

**Review by XuNeo — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thanks for reporting it! 

Adding `CMAKE_INSTALL_PREFIX` solved this issue for one of your customers:
```
cmake .  -DLV_CONF_PATH=/path/to/lv_conf.h

cmake --install . --prefix=some/path/
```

```
-- Install configuration: ""
-- Installing: /usr/local/include/lvgl//src
CMake Error at cmake_install.cmake:54 (file):
  file INSTALL cannot make directory "/usr/local/include/lvgl//src": No such
  file or directory.
  ```

I'm not a CMake expert, so if you have any ideas to resolve this and your issue too, it's be highly appreciated :slightly_smiling_face:

**Comment by tobiasjakobi-compleo** [comment]
I've seen the issue report, but @paulh002 only mentions that changing `LVGL_ROOT_DIR` to `CMAKE_BINARY_DIR` works for him. He never mentioned that `CMAKE_INSTALL_PREFIX` should be manipulated. And it doesn't make any sense at all. This is a CMake variable, which CMake either figures out automatically for you, or which you pass via CLI arguments. Hardcoding this here means that your install prefix always is the current working directory.

**Comment by kisvegabor** [comment]
It was reported by someone else, I've just fixed the 2 in the same PR. 
I asked the that person to join the discussion so that we can figure out something together.

**Comment by 2mooar** [comment]
@tobiasjakobi-compleo Could you please tell me YOCTO version and especially which cmake version are you using. For me it looks like cmake bug, should normally override CMAKE_INSTAL_PREFIX, here: https://cmake.org/cmake/help/v3.30/variable/CMAKE_INSTALL_PREFIX.html 

But somehow if CMAKE_INSTALL_PREFIX is not set to any value, --prefix does not work in our build system with cmake 3.22.

**Comment by tobiasjakobi-compleo** [comment]
We are using Yocto Kirkstone, which comes with CMake v3.22.3 -- does this answer your question?

**Comment by Salahaldeen-altous** [comment]
Hi @tobiasjakobi-compleo 

can you please share with me your lvgl yocto receipe? 
https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-graphics/lvgl/lvgl_9.1.0.bb?h=master

**Comment by tobiasjakobi-compleo** [comment]
This is the recipe we are using.
[lvgl_bb.zip](https://github.com/user-attachments/files/17326992/lvgl_bb.zip)

**Comment by Salahaldeen-altous** [comment]
Hi @tobiasjakobi-compleo 
thanks for providing the recipe but it seems to me a custom recipe and I am missing the patches (files folder inside the recipe)

`WARNING: lvgl-9.3.0+20240918-r0 do_fetch: Failed to fetch URL file://0001-CMake-add-library-version-information.patch, attempting MIRRORS if available
ERROR: lvgl-9.3.0+20240918-r0 do_fetch: Fetcher failure: Unable to find file file://0001-CMake-add-library-version-information.patch anywhere. The paths that were searched were:
`

**Comment by tobiasjakobi-compleo** [comment]
@Salahaldeen-altous Why do you need the patches? I'm not sure what you're trying to accomplish here. If you're just interested in a build, you can just ignore the patches and supply your own config.

**Comment by Salahaldeen-altous** [comment]
Hi @tobiasjakobi-compleo 
I have trying to figure our why the new fix break your yocto build which you have mention above!! I have seen one patch named (0004-CMake-remove-override-of-install-prefix.patch), do you have added this only to fix this problem?

**Comment by tobiasjakobi-compleo** [comment]
> Hi @tobiasjakobi-compleo I have trying to figure our why the new fix break your yocto build which you have mention above!! I have seen one patch named (0004-CMake-remove-override-of-install-prefix.patch), do you have added this only to fix this problem?

I see. I have uploaded the complete directory: 
[lvgl_recipe_complete.zip](https://github.com/user-attachments/files/17342540/lvgl_recipe_complete.zip)

Any yes, we have partially reverted the fix to make our build working again.

The other patches are:
- adding version information for the shared lib
- correctly link the .so against FreeType
- a NEON asm fix (currently available as PR here: https://github.com/lvgl/lvgl/pull/6887)
- some trivial fix in the libpng load concerning deprecated LVGL API

`ccs-build-config` is also a patch, and results (when combining it with the template) in the LVGL build config.

So nothing too fancy here I guess..

**Comment by kisvegabor** [comment]
@etag4048 will look into his issue. He is way better qualified for CMake and Yocto than me :slightly_smiling_face:

**Comment by etag4048** [comment]
Hello  @tobiasjakobi-compleo I am trying to replicate your issue, could you please provide the logfile of the failed task. Also on what task does it fail  ``do_install`` or ``do_package``  ?

**Pull request merged**
