### PR TITLE
LVGL.lvgl.1.0.12-alpha : Refactor CMSIS PDSC file

### PR DESCRIPTION
**Pull request by bbkarim**
- Removed bundle as not needed (remove extra level LVGL_LVGL...)
- Reworked components to get more granulated sub-groups
- Fixed missing hearder files issues
- Include only selected headerfiles by CMSIS pack configuration
- Clean-up LVGL-Essential files
- Add more widgets
- Add more demos
- Updated GPU STM32-DMA2D to support STM32U5xx
- Remove compilation warnings
- CMSIS pack tested OK with STM32CubeMX
- Tested Sub-groups are : Essential + GPU STM32-DMA2D + Txtra Themes

Signed-off-by: Karim BEN BELGACEM <ben.belgacem.karim@gmail.com>

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
Thank you for this contribution. 
I see a lot of changes, and not all of them are strongly connected with the lvgl cmsis-pack. 

@kisvegabor  my personal opinion is, maybe @bbkarim can divide those changes into multiple PRs, and each of them concentrates on one thing. Most importantly, we can review and discuss them one by one.

**Comment by GorgonMeducer** [comment]
I see you have removed the bundle. Appears to you, maybe it is:

- Not necessary
- Looks silly

But changing this structure will force all existing cmsis-pack users to reconfigure the RTE. Trust me, most users don't know how to do it, and tons of complaints will come to me as the maintainer of the cmsis-pack folder. 

The truth is 90% of developers in China are getting starting to use cmsis-pack and don't know how to deal with RTE if there are any conflicts caused by changing any pack structure in RTE.

image
The red parts belong to the old LVGL cmsis-pack and the new one is marked as Graphics.
Here you use Graphics to replace LVGL (the organisation/company name) and remove the product name lvgl, I think no one would know it is LVGL. It is a trade mark. 


Please, please do not remove the bundle, as many people will suffer from this change and find the existing project fails with the latest version of lvgl-cmsis-pack. If they ask me what's the benefits of removing the bundle, I don't know.

The benefit of keeping the bundle is:

- All components by default share the same LVGL version (unless you specifically add one for that component)
- There is compatible with existing projects.

**Comment by GorgonMeducer** [comment]
I have tried to compile the project:

https://github.com/lvgl/lv_port_an547_cm55_sim

with the following RTE configuration

image

I see 32 errors:

```
ui/ui.c(6): warning: In file included from...
./ui/ui.h(14): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling ui.c...
ui/ui_events.c(6): warning: In file included from...
./ui/ui.h(14): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling ui_events.c...
main.c(29): error: 'demos/lv_demos.h' file not found
#include "demos/lv_demos.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
compiling main.c...
ui/ui_font_Number.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling ui_font_Number.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_dejavu_16_persian_hebrew.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_dejavu_16_persian_hebrew.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_10.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_10.c...
ui/ui_helpers.c(6): warning: In file included from...
./ui/ui_helpers.h(10): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling ui_helpers.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_12_subpx.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_12_subpx.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_12.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_12.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_14.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_14.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_16.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_16.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_18.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_18.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_20.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_20.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_22.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_22.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_24.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_24.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_26.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_26.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_28.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_28.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_28_compressed.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_28_compressed.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_30.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_30.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_34.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_34.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_32.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_32.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_36.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_36.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_40.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_40.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_38.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_38.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_42.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_42.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_44.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_44.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_48.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_48.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_46.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_46.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_montserrat_8.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_montserrat_8.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_simsun_16_cjk.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_simsun_16_cjk.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_unscii_16.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_unscii_16.c...
C:/Users/gabriel/AppData/Local/Arm/Packs/LVGL/lvgl/1.0.12-alpha/src/font/lv_font_unscii_8.c(8): warning: In file included from...
./RTE/Graphics\lvgl.h(24): error: 'src/misc/lv_log.h' file not found
#include "src/misc/lv_log.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
compiling lv_font_unscii_8.c...
".\Objects\lv_template.axf" - 32 Error(s), 0 Warning(s).
```

**Comment by kisvegabor** [comment]
@GorgonMeducer To be straight, I'm not a CMSIS pack user and can't comment much about what would be the best direction or where to divide this PR into smaller chunks. So feel free to recommend  what would be the best way to discuss the proposed changes. 

> The red parts belong to the old LVGL cmsis-pack and the new one is marked as Graphics.
Here you use Graphics to replace LVGL (the organisation/company name) and remove the product name lvgl, I think no one would know it is LVGL. It is a trade mark.

I'd really like to keep the name "LVGL" explicitly. Maybe I'm missing something but how could people know that "Graphics" is LVGL, TouchGFX, or EmWin? Any of these could be graphics.

**Comment by kisvegabor** [comment]
What I can tell though that really there are a lot of changes here. So let's approach this update differently. 

@bbkarim please open an issue with the problems you see and we can figure out solutions for them.

**Comment by GorgonMeducer** [comment]
Thank you, @kisvegabor.
@bbkarim Would you please at least send separated PRs (without changing the pdsc structure, i.e. remove the bundle), i.e.

- A dedicated PR for adding support for STM32U5xx
      - You can add new conditions inside this PR
- A dedicated PR for adding more widgets and demos

For those changes in `lvgl.h` and `lv_config_cmsis.h`. Please send dedicated PRs so we can discuss the problems you observed and the solution you proposed.

Thank you.

**Comment by bbkarim** [comment]
Hi @GorgonMeducer,

Honestly I wasn't expecting that behavior with MDK-ARM. I'm also surprised that LVGL was replaced by Graphics.

I agree with you and with @kisvegabor, I should split the PR into different PRs and open an issue for the cmsis-pack topics.

**Comment by kisvegabor** [comment]
> I agree with you and with @kisvegabor, I should split the PR into different PRs and open an issue for the cmsis-pack topics.

Great, thank you :slightly_smiling_face:

**Comment by bbkarim** [comment]
Hi @kisvegabor and @GorgonMeducer,

Please do not merge this now, I'm reviewing the cmsis-pack structure and making some updates on top of this.
I'll then, start a new issue discussion for that and link this PR to it.

Best Regards,
Karim

**Comment by kisvegabor** [comment]
Sounds great!

**Comment by GorgonMeducer** [comment]
Please close this PR as we had a dedicated discussion #3857 
@kisvegabor

**Pull request closed without merging**
