### PR TITLE
Work in progress: Update Kconfig to match LVGLv8 options

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Update Kconfig, marked as draft because it's not finished yet.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by C47D** [comment]
Should `LV_USE_THEME_DEFAULT` and `LV_USE_THEME_BASIC` be to 1 by default? I should guess only one of them should be enabled by default.

Also, in the layout section there's no description for both options, it would help me to add the description in the Kconfig options.

The Kconfig changed a lot, it would be nice that if a option is removed/added into `lv_conf_template` then the Kconfig file should be updated accordingly.

**Comment by C47D** [comment]
Is `LV_DISP_ROT_MAX_BUF` be in KBs?

**Comment by embeddedt** [comment]
It is currently in bytes.

**Comment by C47D** [comment]
@kisvegabor based on the new `lv_conf_template` is safe to remove the `LV_FONT_DEFAULT_SMALL`, `LV_FONT_DEFAULT_NORMAL`, `LV_FONT_DEFAULT_SUBTITLE` and `LV_FONT_DEFAULT_TITLE` options from the Kconfig? And add the `LV_FONT_DEFAULT ` option?

There are still few options to update (and others to remove), I will do so tomorrow, or if someone want to continue please let me know.

**Comment by C47D** [comment]
@xiaoxiang781216 I think most of the symbols are updated, there are some that are not possible to use in the Kconfig menu. The only missing thing is 

> @kisvegabor based on the new lv_conf_template is safe to remove the LV_FONT_DEFAULT_SMALL, LV_FONT_DEFAULT_NORMAL, LV_FONT_DEFAULT_SUBTITLE and LV_FONT_DEFAULT_TITLE options from the Kconfig? And add the LV_FONT_DEFAULT option?

I haven't had the change to test it in the `lv_port_esp32` project tho.

**Comment by FASTSHIFT** [comment]
Some function macro replacement using string type will cause compilation failure, such as LV_MEM_CUSTOM_ALLOC, LV_MEM_CUSTOM_FREE, LV_TICK_CUSTOM_SYS_TIME_EXPR, etc.

**Comment by C47D** [comment]
Sorry I don't follow, what do you mean by turning those options on?

**Comment by C47D** [comment]
I see now, if I remember correctly those options were added as strings because the symbols were used in the `CMakeLists.txt` file.

**EDIT**
I will update this comment with a list of options not available on the Kconfig file.

**Comment by C47D** [comment]
Remindme: Update `lv_kconf_conf` with new options.

Here's the list of missing options on the Kconfig file:
- `LV_MEM_CUSTOM_ALLOC`
- `LV_MEM_CUSTOM_FREE`
- `LV_MEM_CUSTOM_REALLOC`
- `LV_TICK_CUSTOM_INCLUDE`
- `LV_TICK_CUSTOM_SYS_TIME_EXPR`
- `LV_ASSERT_HANDLER_INCLUDE`
- `LV_ASSERT_HANDLER`
- `LV_SPRINTF_INCLUDE`
- `lv_snprintf`
- `lv_vsnprintf`
- `LV_ENABLE_GC`
- `LV_GC_INCLUDE`
- `LV_ATTRIBUTE_TICK_INC`
- `LV_ATTRIBUTE_TIMER_HANDLER`
- `LV_ATTRIBUTE_FLUSH_READY`
- `LV_ATTRIBUTE_MEM_ALIGN_SIZE`
- `LV_ATTRIBUTE_MEM_ALIGN`
- `LV_ATTRIBUTE_LARGE_CONST`
- `LV_ATTRIBUTE_LARGE_RAM_ARRAY`
- `LV_ATTRIBUTE_FAST_MEM`
- `LV_ATTRIBUTE_DMA`
- `LV_EXPORT_CONST_INT`
- `LV_FONT_CUSTOM_DECLARE`
- `LV_CALENDAR_DEFAULT_DAY_NAMES`
- `LV_CALENDAR_DEFAULT_MONTH_NAMES`

**Comment by C47D** [comment]
I consider this is now ready for review, I haven't been able to setup a project to test it, so if anyone can help me with that it would be great.

Any improvement please let me know.

@kisvegabor Are we also going to update the `CMakeLists.txt`? The `LV_MEM_CUSTOM_ALLOC`, `LV_MEM_CUSTOM_FREE` and `LV_TICK_CUSTOM_SYS_TIME_EXPR` symbols are no longer available.

**Comment by xiaoxiang781216** [comment]
We are using Kconfig, @FASTSHIFT will give the feedback tomorrow, @C47D thanks for your quick update.

**Comment by FASTSHIFT** [comment]
@C47D 
A syntax error was found on line 564 of Kconfig, where it should be "help".
screenshot

**Comment by C47D** [comment]
@FASTSHIFT Sorry about that, fixed in 92206e1

**Comment by FASTSHIFT** [comment]
@C47D 
When the "LV_COLOR_CHROMA_KEY" option is enabled, errors will be reported when compiling. 
screenshot_6

screenshot_8
On line 85 of "lv_conf_internal.h",
screenshot_7

Here needs to be changed to:
```C
/*Images pixels with this color will not be drawn if they are  chroma keyed)*/
#ifndef LV_COLOR_CHROMA_KEY
#  ifdef CONFIG_LV_COLOR_CHROMA_KEY
#    define LV_COLOR_CHROMA_KEY     lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY)
#  else
#    define  LV_COLOR_CHROMA_KEY    lv_color_hex(0x00ff00)         /*pure green*/
#  endif
#endif
```

**Comment by kisvegabor** [comment]
> When the "LV_COLOR_CHROMA_KEY" option is enabled, errors will be reported when compiling.

@C47D 
Can we apply the trick of using `CONFIG_LV_COLOR_CHROMA_KEY_HEX` and manually adding
```c
#define CONFIG_LV_COLOR_CHROMA_KEY lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY_HEX);
```

**Comment by C47D** [comment]
@FASTSHIFT Can you try this patch?
```diff
diff --git a/Kconfig b/Kconfig
index fd2e2e34..3d965482 100644
--- a/Kconfig
+++ b/Kconfig
@@ -53,7 +53,7 @@ menu "LVGL configuration"
                 Requires `LV_COLOR_DEPTH = 32` colors and the screen's `bg_opa` should be set to
                 non LV_OPA_COVER value

-        config LV_COLOR_CHROMA_KEY
+        config LV_COLOR_CHROMA_KEY_HEX
             hex "Images pixels with this color will not be drawn (if they are chroma keyed)."
             depends on LV_COLOR_SCREEN_TRANSP
             range 0x000000 0xFFFFFF
diff --git a/src/lv_conf_kconfig.h b/src/lv_conf_kconfig.h
index 4a6a4661..ccdd2b94 100644
--- a/src/lv_conf_kconfig.h
+++ b/src/lv_conf_kconfig.h
@@ -36,14 +36,14 @@ extern "C" {
 #endif

 /*******************
- * LV COLOR TRANSP
+ * LV COLOR CHROMA KEY
  *******************/

-#ifndef LV_COLOR_TRANSP
-#if defined (CONFIG_LV_COLOR_TRANSP_HEX)
-#define CONFIG_LV_COLOR_TRANSP    lv_color_hex(CONFIG_LV_COLOR_TRANSP_HEX)
+#ifndef LV_COLOR_CHROMA_KEY
+#if defined (CONFIG_LV_COLOR_CHROMA_KEY_HEX)
+#define CONFIG_LV_COLOR_CHROMA_KEY  lv_color_hex(CONFIG_LV_COLOR_CHROMA_KEY_HEX)
 #else
-#define CONFIG_LV_COLOR_TRANSP    LV_COLOR_LIME
+#define CONFIG_LV_COLOR_CHROMA_KEY  lv_color_hex(0x00ff00)  /* pure green */
 #endif
 #endif
```

**Comment by C47D** [comment]
I've tested f807613 in the `lv_port_esp32` project and the compilation error seems to be solved, I don't have any display with me to test it tho.

**Comment by FASTSHIFT** [comment]
I have tested in the project and found no problems #

> 我已经在项目中测试了[f807613](https://github.com/lvgl/lvgl/commit/f807613b43900d2008445af1ba497f724889eb56)，并且[似乎](https://github.com/lvgl/lvgl/commit/f807613b43900d2008445af1ba497f724889eb56)`lv_port_esp32`解决了编译错误，我没有任何显示器可以测试。

**Comment by FASTSHIFT** [comment]
> I've tested [f807613](https://github.com/lvgl/lvgl/commit/f807613b43900d2008445af1ba497f724889eb56) in the `lv_port_esp32` project and the compilation error seems to be solved, I don't have any display with me to test it tho.

I also tested in my project, no problem was found.

**Comment by kisvegabor** [comment]
Great!
I suggest merging it and sending smaller PRs if something comes up.

**Comment by C47D** [comment]
Nice, ready to merge then.

**Comment by kisvegabor** [comment]
Thank you very much!

Merging!

**Pull request merged**
