### PR TITLE
feat(draw_label): Support simultaneous text selection and recolor

### PR DESCRIPTION
**Pull request by C47D**
Handles #7055 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by C47D** [comment]
I've logged some variables after finding the logical text position, to note, there's a double space after `the  colored`

This is the test code
```c
  lv_text_decor_t decor = LV_TEXT_DECOR_NONE;
  lv_color_t color = lv_palette_main(LV_PALETTE_BLUE);
  lv_color_t sel_bg_color = lv_palette_lighten(LV_PALETTE_RED, 4);
  lv_color_t sel_color = lv_palette_darken(LV_PALETTE_RED, 4);

  lv_obj_t * label = lv_label_create(lv_screen_active());
  lv_label_set_recolor(label, true);
  lv_label_set_text(label, "Hi, Testing the #00ff00 colored labels.#");
  lv_obj_set_style_text_decor(label, decor, 0);
  lv_obj_set_style_text_color(label, color, 0);
  lv_obj_set_style_text_opa(label, LV_OPA_COVER, 0);
  lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_LEFT, 0);
  lv_obj_set_style_bg_color(label, sel_bg_color, LV_PART_SELECTED);
  lv_obj_set_style_text_color(label, sel_color, LV_PART_SELECTED);
  lv_label_set_text_selection_start(label, 10);
  lv_label_set_text_selection_end(label, 25);
```

The output
```console
[User]	(0.239, +239)	 lv_draw_label_iterate_characters: Char H. Logical pos: 1. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char i. Logical pos: 2. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char ,. Logical pos: 3. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 4. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char T. Logical pos: 5. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char e. Logical pos: 6. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char s. Logical pos: 7. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char t. Logical pos: 8. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char i. Logical pos: 9. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char n. Logical pos: 10. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char g. Logical pos: 11. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 12. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char t. Logical pos: 13. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char h. Logical pos: 14. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char e. Logical pos: 15. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 16. Par strat: 0 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 24. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char c. Logical pos: 25. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char o. Logical pos: 26. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char l. Logical pos: 27. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char o. Logical pos: 28. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char r. Logical pos: 29. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char e. Logical pos: 30. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char d. Logical pos: 31. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 32. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char l. Logical pos: 33. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char a. Logical pos: 34. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char b. Logical pos: 35. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char e. Logical pos: 36. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char l. Logical pos: 37. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char s. Logical pos: 38. Par strat: 17 lv_draw_label.c:362
[User]	(0.239, +0)	 lv_draw_label_iterate_characters: Char .. Logical pos: 39. Par strat: 17 lv_draw_label.c:362
```

**Comment by C47D** [comment]
With this patch it looks better:

```diff
diff --git a/src/draw/lv_draw_label.c b/src/draw/lv_draw_label.c
index 886da693b..4550a731a 100644
--- a/src/draw/lv_draw_label.c
+++ b/src/draw/lv_draw_label.c
@@ -359,6 +359,12 @@ void lv_draw_label_iterate_characters(lv_draw_unit_t * draw_unit, const lv_draw_
 #endif
             }
 
+            if(cmd_state == CMD_STATE_IN) {
+                logical_char_pos = logical_char_pos - (LABEL_RECOLOR_PAR_LENGTH + 1);
+            }
+
+            LV_LOG_USER("Char %c. Logical pos: %d. Par strat: %d", letter, logical_char_pos, recolor_command_start_index);
+
             letter_w = lv_font_get_glyph_width(font, letter, letter_next);
 
             /*Always set the bg_coordinates for placeholder drawing*/
```

This is the output
image

The log output is:
```console
[User]	(0.147, +147)	 lv_draw_label_iterate_characters: Char H. Logical pos: 1. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char i. Logical pos: 2. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char ,. Logical pos: 3. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 4. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char T. Logical pos: 5. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char e. Logical pos: 6. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char s. Logical pos: 7. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char t. Logical pos: 8. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char i. Logical pos: 9. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char n. Logical pos: 10. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char g. Logical pos: 11. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 12. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char t. Logical pos: 13. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char h. Logical pos: 14. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char e. Logical pos: 15. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 16. Par strat: 0 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 17. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char c. Logical pos: 18. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char o. Logical pos: 19. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char l. Logical pos: 20. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char o. Logical pos: 21. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char r. Logical pos: 22. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char e. Logical pos: 23. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char d. Logical pos: 24. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char  . Logical pos: 25. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char l. Logical pos: 26. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char a. Logical pos: 27. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char b. Logical pos: 28. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char e. Logical pos: 29. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char l. Logical pos: 30. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char s. Logical pos: 31. Par strat: 17 lv_draw_label.c:366
[User]	(0.147, +0)	 lv_draw_label_iterate_characters: Char .. Logical pos: 32. Par strat: 17 lv_draw_label.c:366
```

**Comment by C47D** [comment]
Issues to fix:
1. Eliminate the double space (aka ' ' ) between `the` and `colored`

**Comment by C47D** [comment]
@kisvegabor This is the current output with the test code from above
image

**Comment by kisvegabor** [comment]
Hi Carlos,

I haven't immersed in the implantation details yet, but the screenshot looks great! 

It seems now the selection has higher precedence which is -  in my opinion - the better solution.

**Comment by C47D** [comment]
> Hi Carlos,
> 
> I haven't immersed in the implantation details yet, but the screenshot looks great!
> 
> It seems now the selection has higher precedence which is - in my opinion - the better solution.

Yes, currently the selection have higher precedence than the recolor command.
I will add a render test and then it is ready to be merged.

**Comment by kisvegabor** [comment]
Don't forget to upload the new reference image :wink:

**Comment by C47D** [comment]
> Don't forget to upload the new reference image 😉

I did, it's the new file uploaded in the lastest commit.

**Review by kissa96 — APPROVED** [review]

**Comment by kisvegabor** [comment]
This image is [missing](https://github.com/lvgl/lvgl/actions/runs/11489400700/job/31978117432#step:9:21): ` tests/ref_imgs_vg_lite/draw/label_selection_and_recolor.png`

You can download the missing image at the bottom of [this page](https://github.com/lvgl/lvgl/actions/runs/11489400700?pr=7116). 

Probably the the VG-Lite tests weren't running for you.

**Comment by C47D** [comment]
> This image is [missing](https://github.com/lvgl/lvgl/actions/runs/11489400700/job/31978117432#step:9:21): ` tests/ref_imgs_vg_lite/draw/label_selection_and_recolor.png`
> 
> You can download the missing image at the bottom of [this page](https://github.com/lvgl/lvgl/actions/runs/11489400700?pr=7116).
> 
> Probably the the VG-Lite tests weren't running for you.

Thanks, I didn't noticed it was the VG_Lite image :smile:

**Review by kisvegabor — APPROVED** [review]

**Review by XuNeo — APPROVED** [review]

**Pull request merged**
