### PR TITLE
Hooks for SPIFFS

### PR DESCRIPTION
**Pull request by arferdz**
Please add SPIFFS support in littlevgl’s File system.

### CODE REVIEW

**Comment by embeddedt** [comment]
Were you intending to comment on another issue? This pull request is just merging one of our branches into another one.

**Comment by embeddedt** [comment]
When I said "pull requests are welcome", I didn't mean opening a blank pull request. :slightly_smiling_face:  I meant contributions to add SPIFFS support are welcome.

**Comment by arferdz** [comment]
I honestly dont know what i am doing.  :D This is new teritory for me.  

Ar. Ferdz Reyes

**Comment by embeddedt** [comment]
> I honestly dont know what i am doing.

No problem!

**Comment by kisvegabor** [comment]
Please take a look for this guide about sending pull request: https://blog.littlevgl.com/2018-12-06/contributing#how-can-i-send-fixes-and-improvements

You need to use `lv_fs_if` repo instead of `lvgl` to send PRs there.

**Pull request closed without merging**
