### PR TITLE
lv_list: check actual object type instead of relying on signal handler

### LINKED ISSUE #1010: Replacing the signal function on buttons in a list breaks lv_list_get_next_btn
If buttons are created in a list, and the signal function for the buttons are replaced, then lv_list_get_next_btn will not find the buttons with the overridden signal function.

lv_list_get_next_btn uses the address of the signal function as a sanity check to see if the object is really a button. Might need a different way to check?

### PR DESCRIPTION
**Pull request by embeddedt**
Fixes #1010.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Looks perfect, thank you!

**Comment by kisvegabor** [comment]
Upps, I've just realized the conditions in the `while` loops were wrong. See: https://github.com/littlevgl/lvgl/commit/6a3c7d2b95ede01f646d2402eaf61a3d25337b3a

It should iterate until finding a btn/label/img so skip the other types.

**Comment by embeddedt** [comment]
@kisvegabor My bad. Sorry about that!

**Comment by kisvegabor** [comment]
No problem :+1:

**Pull request merged**
