### PR TITLE
optimization enum/struct

### PR DESCRIPTION
**Pull request by Zaltora**
Change how enum declaration are done to put the possibility to set the memory size.

TODO:
-Test if everything work well. Review.
-Rename some internal struct variable ?
-Struct padding optimization with new enum declaration ?

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you very much! You've done it very a thoroughly!

I reviewed the changes and made a few updates. Do you agree with them?
https://github.com/littlevgl/lvgl/commit/839757e6c88f23d79f0cb9a2bc0d93a568683036

**Comment by Zaltora** [comment]
Yes, i fixed some of them too, you are faster :)

A suggestion:
If some people are interested by speed optimization and not the memory optimization, maybe it can be good to add custom lvgl variable. E.G:
```c
typedef uint8_t  lv_u8_t 
typedef uint16_t lv_u16_t 
typedef int8_t   lv_i8_t 
typedef int16_t  lv_i16_t 
```
It will allow to put faster variables like "int".
No need to do it if no demand on it

**Comment by kisvegabor** [comment]
Great! :)

About the int typedefs: 
For simplicity, I'd suggest having only an `lv_int_t` typedef. It should be at least `int16_t` and can be used when just a not to too big and not too specific variable is required. E.g. in `for loops`, counting things,  etc. What do you think?

**Comment by Zaltora** [comment]
Yes, can be good. Specific variable for intensive operation on them.
See this : [signed/unsigned](https://stackoverflow.com/questions/5201489/signed-vs-unsigned-operations-in-c)  useful information.
`typedef int_fast16_t  lv_int_t`
PS: fast mean that the minimum will be 16 bit but higher if possible.

**Comment by kisvegabor** [comment]
Interesting read! According to this `lv_uint_t` and `lv_int_t` seems more suitabel.

**Pull request merged**
