### PR TITLE
add offset feature to img object

### PR DESCRIPTION
**Pull request by ali-rostami**

### CODE REVIEW

**Comment by embeddedt** [comment]
@kisvegabor Please review.

**Comment by kisvegabor** [comment]
Thank you @ali-rostami!

It looks good!

Just two things:
1. `void lv_img_set_offset(lv_obj_t *img, lv_coord_t x_offset, lv_coord_t y_offset)` would be easier to use for the user.
2. Please add `lv_img_get_offset_x` and `lv_img_get_offset_y` functions too.

**Comment by ali-rostami** [comment]
so how is it now?

**Comment by kisvegabor** [comment]
Thanks for the update!

> 2. Please add lv_img_get_offset_x and lv_img_get_offset_y functions too.

So please add these functions too.

**Comment by ali-rostami** [comment]
Yourwelcom.
I wrote them too.
Sorry didn't mention them.

**Comment by kisvegabor** [comment]
I don't see new commits? Have you pushed it?

**Comment by ali-rostami** [comment]
I didn't push them with a separate commit. they are added with the last commit.
 these 2 functions are defined below ```lv_img_set_offset```.
Am I missed anything? I mean, should I commit them separately?

**Comment by kisvegabor** [comment]
> Please add lv_img_get_offset_x and lv_img_get_offset_y functions too.

> I didn't push them with a separate commit. they are added with the last commit.
these 2 functions are defined below lv_img_set_offset.

I meant the `GET` functions :)

I've pushed a minor fix to invalidate the image when the offset changes.

**Comment by ali-rostami** [comment]
Oops, my mistake. 
OK, I will add them soon.

**Comment by ali-rostami** [comment]
Added.
So Is there anything more?

**Comment by kisvegabor** [comment]
Merged, thank you very much! :+1: 

I've tested like this:
img_offset

**Comment by embeddedt** [comment]
@kisvegabor @ali-rostami Looks good!

> I meant the GET functions :)

Wow, even I didn't notice that you said get instead of set.

**Comment by seyyah** [comment]
Very good effect :clap:

**Comment by kisvegabor** [comment]
> Wow, even I didn't notice that you said get instead of set.

I really should emphasize it more. I'll next time!

**Pull request merged**
