### PR TITLE
Dev 6.0 fixes

### PR DESCRIPTION
**Pull request by amirgon**
- Fixed gc related issues
- Commented out functions which are declared but not defined.

### CODE REVIEW

**Comment by embeddedt** [comment]
@kisvegabor should review the undefined functions. Other than that it looks fine to me.

**Comment by kisvegabor** [comment]
@amirgon 
Thank you!  These function can be removed. Could you do it?

**Comment by amirgon** [comment]
@kisvegabor removed the functions on a9f807a

**Comment by kisvegabor** [comment]
Great, thank you!

**Pull request merged**
