### PR TITLE
feat(docs):  batch 5 of proofread/edited docs

### PR DESCRIPTION
**Pull request by vwheeler63**
cc:  @kisvegabor 

- canvas.rst
- image.rst
- imagebutton.rst
- keyboard.rst
- label.rst
- led.rst
- line.rst
- list.rst
- lottie.rst

Most of these edits are to correct grammar and clarify meaning.  There are corrections in a few cases (e.g. outdated function names, previous copy/paste casualties [i.e. someone pasted, but forgot to edit], incomplete sentences, etc.).

Edited `.html` versions of these documents can be found here:

   http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/details/widgets/index.html

Note:  these intentionally do not include the normal translation links and API-page links.  Those links are added dynamically during the docs-build process, and they are not part of any changes made herein.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.  Done.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.  n/a
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.  n/a
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).  n/a
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).  n/a since no code was changed.
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.  Done.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.  Done.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — APPROVED** [review]
It's amazing Vic!

**Comment by vwheeler63** [comment]
> It's amazing Vic!

Knowing what a *catalyst* good documentation is for any product, I am fully expecting a "new era" for LVGL to be beginning as we speak!  It will probably never be perfect, but we are taking some MAJOR steps in that direction!  😃

**Comment by vwheeler63** [comment]
@kisvegabor @liamHowatt Hi, Liam!  Would you mind having a look at this?  It's 1 of 2 PRs that are outstanding.

**Review by liamHowatt — APPROVED** [review]
Great! I wish this was the version I read the first time I used LVGL.

**Comment by vwheeler63** [comment]
> Great! I wish this was the version I read the first time I used LVGL.

cc:  @kisvegabor  (More feedback.  😄 )

@liamHowatt , I first started to dig deeply into learning LVGL about 16 months ago in a firmware project I wrote from the ground up, and I am doing this project with Gábor as exactly that:  helping to form the documentation I wished I had had at that time.  The proofreading on the Widgets is particularly detailed for some of them, because I am having to dig into the C code to clarify some things, and when I do, I clarify them in the documentation as well.  Scale Widget (in the batch-6 PR) is one of those.  It's got a couple of new sections now.  😉  Anyway, thank you for mentioning the above.  It gives me "energy".  😄

**Comment by kisvegabor** [comment]
> Great! I wish this was the version I read the first time I used LVGL.

Fantastic! :star_struck:

**Pull request merged**
