### PR TITLE
fix(docs):  fix broken links in ./lvgl/README.md

### PR DESCRIPTION
**Pull request by vwheeler63**
Fixes links in ./lvgl/README.md that were broken from PR #7136.

cc:  @kisvegabor 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.  Done.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.  n/a
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.  n/a
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).  n/a
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).  n/a
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.  Done.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.  Done.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kissa96 — APPROVED** [review]

**Comment by kisvegabor** [comment]
Can we fix it with Sphinx redirect so that the old links will work too?

**Comment by vwheeler63** [comment]
> Can we fix it with Sphinx redirect so that the old links will work too?

I'm on it.

**Comment by vwheeler63** [comment]
Hi, Gábor! ( @kisvegabor )

I am ready with the links that were in `./lvgl/README.md`.  I also realized we changed 2 paths after I had made modifications to the translated READMEs as well, plus I realized that these do not go through Sphinx, so I re-translated the 2 :ref: links I put in them back to fully-spelled-out URLs.

I added just that subset of changes into the `redirects` dictionary in `conf.py`.

And it is making me wonder if I need to make a file-rename map, since my need to remember where things went has come up many times now....

**Comment by vwheeler63** [comment]
Hi, Gábor!  ( @kisvegabor )

Because thinking through where documents moved has now come across my plate so many times (including the modifications to `conf.py` herein), I made a map of where the files went.  I was thinking of adding it to the `./docs/` directory, but in reality, it will only be needed for a little while during any adjustments.  (I have an editor that made this easy.)  I suspect quite a few people will want to refer to this, but wanted to pass it by you to get your thoughts on it (i.e. who would need it and how it should be presented).  Now that I have it, I can easily change its format to something more suitable.

Kind regards,
Vic

```
Doc-File Disposition Map
========================

+------------------------------------------------+------------------------------------------------------------------+
| Previous File Relative to ./docs/              | New File Relative to ./docs/                                     |
| ===============================================+==================================================================+
|                                                |                                                                  |
| New Files:                                     |                                                                  |
| ----------                                     |                                                                  |
|                                                | details/base-widget/index.rst                                    |
|                                                | details/base-widget/styles/index.rst                             |
|                                                | details/index.rst                                                |
|                                                | intro/add-lvgl-to-your-project/building_lvgl.rst                 |
|                                                | intro/add-lvgl-to-your-project/configuration.rst                 |
|                                                | intro/add-lvgl-to-your-project/getting_lvgl.rst                  |
|                                                | intro/add-lvgl-to-your-project/other_platforms.rst               |
|                                                | intro/index.rst                                                  |
|                                                |                                                                  |
| Files that Stayed in Same Location:            |                                                                  |
| -----------------------------------            |                                                                  |
| CHANGELOG.rst                                  | CHANGELOG.rst                                                    |
| CODING_STYLE.rst                               | CODING_STYLE.rst                                                 |
| CONTRIBUTING.rst                               | CONTRIBUTING.rst                                                 |
| index.rst                                      | index.rst                                                        |
| README_jp.rst                                  | README_jp.rst                                                    |
| README_pt_BR.rst                               | README_pt_BR.rst                                                 |
| README_zh.rst                                  | README_zh.rst                                                    |
| ROADMAP.rst                                    | ROADMAP.rst                                                      |
|                                                |                                                                  |
|                                                |                                                                  |
| Files Removed:                                 |                                                                  |
| --------------                                 |                                                                  |
| get-started/index.rst                          | removed                                                          |
| overview/display.rst                           | combined into details/main-components/display.rst                |
| overview/obj.rst                               | combined into details/base-widget/obj.rst                                      |
| porting/indev.rst                              | combined into details/main-components/indev.rst                  |
| porting/sleep.rst                              | combined into intro/add-lvgl-to-your-project/threading.rst       |
| porting/tick.rst                               | combined into intro/add-lvgl-to-your-project/connecting_lvgl.rst |
|                                                |                                                                  |
|                                                |                                                                  |
| Files Renamed:                                 |                                                                  |
| --------------                                 |                                                                  |
| get-started/quick-overview.rst                 | intro/basics.rst                                                 |
| intro/index.rst                                | intro/introduction.rst                                           |
| overview/renderers/pxp.rst                     | details/integration/renderers/nxp_pxp.rst                        |
| overview/renderers/vglite.rst                  | details/integration/renderers/nxp_vglite_gpu.rst                 |
| overview/style-props.rst                       | details/base-widget/styles/style-properties.rst                  |
| porting/os.rst                                 | intro/add-lvgl-to-your-project/threading.rst                     |
| porting/project.rst                            | intro/add-lvgl-to-your-project/connecting_lvgl.rst               |
|                                                |                                                                  |
|                                                |                                                                  |
| Files Moved:                                   |                                                                  |
| ------------                                   |                                                                  |
| integration/bindings/api_json.rst              | details/integration/bindings/api_json.rst                        |
| integration/bindings/cpp.rst                   | details/integration/bindings/cpp.rst                             |
| integration/bindings/index.rst                 | details/integration/bindings/index.rst                           |
| integration/bindings/javascript.rst            | details/integration/bindings/javascript.rst                      |
| integration/bindings/micropython.rst           | details/integration/bindings/micropython.rst                     |
| integration/bindings/pikascript.rst            | details/integration/bindings/pikascript.rst                      |
| integration/building/cmake.rst                 | details/integration/building/cmake.rst                           |
| integration/building/index.rst                 | details/integration/building/index.rst                           |
| integration/building/make.rst                  | details/integration/building/make.rst                            |
| integration/chip/arm.rst                       | details/integration/chip/arm.rst                                 |
| integration/chip/espressif.rst                 | details/integration/chip/espressif.rst                           |
| integration/chip/index.rst                     | details/integration/chip/index.rst                               |
| integration/chip/nxp.rst                       | details/integration/chip/nxp.rst                                 |
| integration/chip/renesas.rst                   | details/integration/chip/renesas.rst                             |
| integration/chip/stm32.rst                     | details/integration/chip/stm32.rst                               |
| integration/driver/display/fbdev.rst           | details/integration/driver/display/fbdev.rst                     |
| integration/driver/display/gen_mipi.rst        | details/integration/driver/display/gen_mipi.rst                  |
| integration/driver/display/ili9341.rst         | details/integration/driver/display/ili9341.rst                   |
| integration/driver/display/index.rst           | details/integration/driver/display/index.rst                     |
| integration/driver/display/lcd_stm32_guide.rst | details/integration/driver/display/lcd_stm32_guide.rst           |
| integration/driver/display/renesas_glcdc.rst   | details/integration/driver/display/renesas_glcdc.rst             |
| integration/driver/display/st7735.rst          | details/integration/driver/display/st7735.rst                    |
| integration/driver/display/st7789.rst          | details/integration/driver/display/st7789.rst                    |
| integration/driver/display/st7796.rst          | details/integration/driver/display/st7796.rst                    |
| integration/driver/display/st_ltdc.rst         | details/integration/driver/display/st_ltdc.rst                   |
| integration/driver/index.rst                   | details/integration/driver/index.rst                             |
| integration/driver/libinput.rst                | details/integration/driver/libinput.rst                          |
| integration/driver/opengles.rst                | details/integration/driver/opengles.rst                          |
| integration/driver/touchpad/evdev.rst          | details/integration/driver/touchpad/evdev.rst                    |
| integration/driver/touchpad/ft6x36.rst         | details/integration/driver/touchpad/ft6x36.rst                   |
| integration/driver/touchpad/index.rst          | details/integration/driver/touchpad/index.rst                    |
| integration/driver/wayland.rst                 | details/integration/driver/wayland.rst                           |
| integration/driver/windows.rst                 | details/integration/driver/windows.rst                           |
| integration/driver/X11.rst                     | details/integration/driver/X11.rst                               |
| integration/framework/arduino.rst              | details/integration/framework/arduino.rst                        |
| integration/framework/index.rst                | details/integration/framework/index.rst                          |
| integration/framework/platformio.rst           | details/integration/framework/platformio.rst                     |
| integration/framework/tasmota-berry.rst        | details/integration/framework/tasmota-berry.rst                  |
| integration/ide/index.rst                      | details/integration/ide/index.rst                                |
| integration/ide/mdk.rst                        | details/integration/ide/mdk.rst                                  |
| integration/ide/pc-simulator.rst               | details/integration/ide/pc-simulator.rst                         |
| integration/index.rst                          | details/integration/index.rst                                    |
| integration/os/freertos.rst                    | details/integration/os/freertos.rst                              |
| integration/os/index.rst                       | details/integration/os/index.rst                                 |
| integration/os/mqx.rst                         | details/integration/os/mqx.rst                                   |
| integration/os/nuttx.rst                       | details/integration/os/nuttx.rst                                 |
| integration/os/px5.rst                         | details/integration/os/px5.rst                                   |
| integration/os/qnx.rst                         | details/integration/os/qnx.rst                                   |
| integration/os/rt-thread.rst                   | details/integration/os/rt-thread.rst                             |
| integration/os/yocto/core_components.rst       | details/integration/os/yocto/core_components.rst                 |
| integration/os/yocto/index.rst                 | details/integration/os/yocto/index.rst                           |
| integration/os/yocto/lvgl_recipe.rst           | details/integration/os/yocto/lvgl_recipe.rst                     |
| integration/os/yocto/terms_and_variables.rst   | details/integration/os/yocto/terms_and_variables.rst             |
| integration/os/zephyr.rst                      | details/integration/os/zephyr.rst                                |
| layouts/flex.rst                               | details/base-widget/layouts/flex.rst                             |
| layouts/grid.rst                               | details/base-widget/layouts/grid.rst                             |
| layouts/index.rst                              | details/base-widget/layouts/index.rst                            |
| libs/arduino_esp_littlefs.rst                  | details/libs/arduino_esp_littlefs.rst                            |
| libs/arduino_sd.rst                            | details/libs/arduino_sd.rst                                      |
| libs/barcode.rst                               | details/libs/barcode.rst                                         |
| libs/bmp.rst                                   | details/libs/bmp.rst                                             |
| libs/ffmpeg.rst                                | details/libs/ffmpeg.rst                                          |
| libs/freetype.rst                              | details/libs/freetype.rst                                        |
| libs/fs.rst                                    | details/libs/fs.rst                                              |
| libs/gif.rst                                   | details/libs/gif.rst                                             |
| libs/index.rst                                 | details/libs/index.rst                                           |
| libs/lfs.rst                                   | details/libs/lfs.rst                                             |
| libs/libjpeg_turbo.rst                         | details/libs/libjpeg_turbo.rst                                   |
| libs/libpng.rst                                | details/libs/libpng.rst                                          |
| libs/lodepng.rst                               | details/libs/lodepng.rst                                         |
| libs/qrcode.rst                                | details/libs/qrcode.rst                                          |
| libs/rle.rst                                   | details/libs/rle.rst                                             |
| libs/rlottie.rst                               | details/libs/rlottie.rst                                         |
| libs/svg.rst                                   | details/libs/svg.rst                                             |
| libs/tiny_ttf.rst                              | details/libs/tiny_ttf.rst                                        |
| libs/tjpgd.rst                                 | details/libs/tjpgd.rst                                           |
| others/file_explorer.rst                       | details/other-components/file_explorer.rst                       |
| others/font_manager.rst                        | details/other-components/font_manager.rst                        |
| others/fragment.rst                            | details/other-components/fragment.rst                            |
| others/gridnav.rst                             | details/other-components/gridnav.rst                             |
| others/ime_pinyin.rst                          | details/other-components/ime_pinyin.rst                          |
| others/imgfont.rst                             | details/other-components/imgfont.rst                             |
| others/index.rst                               | details/other-components/index.rst                               |
| others/monkey.rst                              | details/other-components/monkey.rst                              |
| others/obj_id.rst                              | details/other-components/obj_id.rst                              |
| others/obj_property.rst                        | details/other-components/obj_property.rst                        |
| others/observer.rst                            | details/other-components/observer.rst                            |
| others/snapshot.rst                            | details/other-components/snapshot.rst                            |
| overview/animations.rst                        | details/main-components/animation.rst                            |
| overview/color.rst                             | details/main-components/color.rst                                |
| overview/coord.rst                             | details/base-widget/coord.rst                                    |
| overview/debugging/gdb_plugin.rst              | details/debugging/gdb_plugin.rst                                 |
| overview/debugging/index.rst                   | details/debugging/index.rst                                      |
| overview/debugging/log.rst                     | details/debugging/log.rst                                        |
| overview/debugging/profiler.rst                | details/debugging/profiler.rst                                   |
| overview/debugging/vg_lite_tvg.rst             | details/debugging/vg_lite_tvg.rst                                |
| overview/event.rst                             | details/base-widget/event.rst                                    |
| overview/font.rst                              | details/main-components/font.rst                                 |
| overview/fs.rst                                | details/main-components/fs.rst                                   |
| overview/image.rst                             | details/main-components/image.rst                                |
| overview/indev.rst                             | details/main-components/indev.rst                                |
| overview/index.rst                             | details/main-components/index.rst                                |
| overview/layer.rst                             | details/base-widget/layer.rst                                    |
| overview/new_widget.rst                        | details/widgets/new_widget.rst                                   |
| overview/renderers/arm2d.rst                   | details/integration/renderers/arm2d.rst                          |
| overview/renderers/index.rst                   | details/integration/renderers/index.rst                          |
| overview/renderers/nema_gfx.rst                | details/integration/renderers/nema_gfx.rst                       |
| overview/renderers/sdl.rst                     | details/integration/renderers/sdl.rst                            |
| overview/renderers/stm32_dma2d.rst             | details/integration/renderers/stm32_dma2d.rst                    |
| overview/renderers/sw.rst                      | details/integration/renderers/sw.rst                             |
| overview/renderers/vg_lite.rst                 | details/integration/renderers/vg_lite.rst                        |
| overview/scroll.rst                            | details/base-widget/scroll.rst                                   |
| overview/style.rst                             | details/base-widget/styles/style.rst                             |
| overview/timer.rst                             | details/main-components/timer.rst                                |
| porting/display.rst                            | details/main-components/display.rst                              |
| porting/draw.rst                               | details/main-components/draw.rst                                 |
| porting/index.rst                              | intro/add-lvgl-to-your-project/index.rst                         |
| porting/timer_handler.rst                      | intro/add-lvgl-to-your-project/timer_handler.rst                 |
| widgets/animimg.rst                            | details/widgets/animimg.rst                                      |
| widgets/arc.rst                                | details/widgets/arc.rst                                          |
| widgets/bar.rst                                | details/widgets/bar.rst                                          |
| widgets/button.rst                             | details/widgets/button.rst                                       |
| widgets/buttonmatrix.rst                       | details/widgets/buttonmatrix.rst                                 |
| widgets/calendar.rst                           | details/widgets/calendar.rst                                     |
| widgets/canvas.rst                             | details/widgets/canvas.rst                                       |
| widgets/chart.rst                              | details/widgets/chart.rst                                        |
| widgets/checkbox.rst                           | details/widgets/checkbox.rst                                     |
| widgets/dropdown.rst                           | details/widgets/dropdown.rst                                     |
| widgets/image.rst                              | details/widgets/image.rst                                        |
| widgets/imagebutton.rst                        | details/widgets/imagebutton.rst                                  |
| widgets/index.rst                              | details/widgets/index.rst                                        |
| widgets/keyboard.rst                           | details/widgets/keyboard.rst                                     |
| widgets/label.rst                              | details/widgets/label.rst                                        |
| widgets/led.rst                                | details/widgets/led.rst                                          |
| widgets/line.rst                               | details/widgets/line.rst                                         |
| widgets/list.rst                               | details/widgets/list.rst                                         |
| widgets/lottie.rst                             | details/widgets/lottie.rst                                       |
| widgets/menu.rst                               | details/widgets/menu.rst                                         |
| widgets/msgbox.rst                             | details/widgets/msgbox.rst                                       |
| widgets/obj.rst                                | details/base-widget/obj.rst                                      |
| widgets/roller.rst                             | details/widgets/roller.rst                                       |
| widgets/scale.rst                              | details/widgets/scale.rst                                        |
| widgets/slider.rst                             | details/widgets/slider.rst                                       |
| widgets/span.rst                               | details/widgets/span.rst                                         |
| widgets/spinbox.rst                            | details/widgets/spinbox.rst                                      |
| widgets/spinner.rst                            | details/widgets/spinner.rst                                      |
| widgets/switch.rst                             | details/widgets/switch.rst                                       |
| widgets/table.rst                              | details/widgets/table.rst                                        |
| widgets/tabview.rst                            | details/widgets/tabview.rst                                      |
| widgets/textarea.rst                           | details/widgets/textarea.rst                                     |
| widgets/tileview.rst                           | details/widgets/tileview.rst                                     |
| widgets/win.rst                                | details/widgets/win.rst                                          |
+------------------------------------------------+------------------------------------------------------------------+

-end-
```

**Comment by vwheeler63** [comment]
@kisvegabor 

Also, now that I have this in list form, in theory, all of the MOVED files could be put into the `redirects` dictionary.  That would be 165 `.html` files generated -- all representing the old website, but redirecting to the new page.

This seems a bit far, but it is doable, and would not take long.  Let me know.

Kind regards,
Vic

**Comment by kisvegabor** [comment]
Wow, there are a lot links to fix. Can we make use of [wildcards](https://documatt.com/sphinx-reredirects/usage.html#redirect-existing-documents)?

**Comment by vwheeler63** [comment]
> Wow, there are a lot links to fix. Can we make use of [wildcards](https://documatt.com/sphinx-reredirects/usage.html#redirect-existing-documents)?

Sadly no, but I have generated a test.  You can see it on my demo website.  So you can now try any link that used to go to a docs page before and it will redirect to the appropriate HTML file.  Example:

http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/details/base-widget/layouts/flex.html

Kind regards,
Vic

**Comment by vwheeler63** [comment]
@kisvegabor 

and...

http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/layouts/flex.html
http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/integration/chip/stm32.html
http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/integration/driver/display/st7735.html
http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/others/observer.html

**Review by kisvegabor — DISMISSED** [review]
Thank you Vic! 
I've tested a few links and they worked well! I'll announce the reorganized docs when when it's merged.

**Comment by vwheeler63** [comment]
> Thank you Vic! I've tested a few links and they worked well! I'll announce the reorganized docs when when it's merged.

Perfect!!

**Comment by vwheeler63** [comment]
@kisvegabor P.S.  Don't forget PR #7144.  Reason:  it adds a lot of documentation quality to styles, flex, and grid!  They read so much better!

**Comment by vwheeler63** [comment]
@kisvegabor P.P.S. Sorry to invalidate your approval above, but I had not yet added in the rest of the redirects -- which WAS already showing and present in the "[demo web site](http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/)".  The redirects that were previously present are unchanged, just more was added (what you tested on line in the links above).

**Review by kisvegabor — APPROVED** [review]
Perfect, thank you!

**Review by FASTSHIFT — APPROVED** [review]

**Comment by vwheeler63** [comment]
> Perfect, thank you!

By the way, the new redirects dictionary in `conf.py` is programmatically generated so I have no doubt it's 100%.  With 165 redirects (actually 164 -- I removed 1 where there was already a legitimate `index.html` -- I didn't want to leave any room for human error.  And all addresses are relative.  I hand-tested probably 30 of them and are 100%.

Thank you, @FASTSHIFT !  You merged this as I was typing this message!

Kind regards,
Vic

**Pull request merged**
