### PR TITLE
chore(draw): fix typo

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

From the discussion: https://github.com/lvgl/lvgl/issues/4342#issuecomment-1699134058, the larger the preference_score value, the slower the rendering.

### Checkpoints
- [ ] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<module_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
The smaller the value of `preference_score`, the stronger the performance. I feel that this design is a bit confusing. Consider defining a `SCORE_MAX=255` to represent the strongest rendering performance? instead of 0.

**Comment by kisvegabor** [comment]
My idea was to give a meaning to the score relative to the SW render but in the practice we won't have so many draw units and there won't be a big competition. Instead we will define what we want in an exact way, and not only based on performance but power consumption, freeing up the CPU, etc.

So I agree to make it work the opposite way. 

An other note: I've realized that we don't need to store the preferred score in `draw_task` but we can do something like:
```c
        /*Let the draw units assign the draw task*/
        uint8_t score = 100;
        t->preferred_draw_unit_id = 0;
        lv_draw_unit_t * u = info->unit_head;
        while(u) {
            if(u->evaluate_cb) u->evaluate_cb(u, t, &score);
            u = u->next;
        }
```

If you agree, could you update the PR accordingly?

**Comment by FASTSHIFT** [comment]
> My idea was to give a meaning to the score relative to the SW render but in the practice we won't have so many draw units and there won't be a big competition. Instead we will define what we want in an exact way, and not only based on performance but power consumption, freeing up the CPU, etc.
> 
> So I agree to make it work the opposite way.

No problem, I will send PR.

> 
> An other note: I've realized that we don't need to store the preferred score in `draw_task` but we can do something like:
> 
> ```c
>         /*Let the draw units assign the draw task*/
>         uint8_t score = 100;
>         t->preferred_draw_unit_id = 0;
>         lv_draw_unit_t * u = info->unit_head;
>         while(u) {
>             if(u->evaluate_cb) u->evaluate_cb(u, t, &score);
>             u = u->next;
>         }
> ```
> 

I think it is more appropriate to keep the preference score in `lv_draw_task_t`, because considering that more parameters may need to be expanded in the future, the public interface can be modified as little as possible.

**Comment by FASTSHIFT** [comment]
> > My idea was to give a meaning to the score relative to the SW render but in the practice we won't have so many draw units and there won't be a big competition. Instead we will define what we want in an exact way, and not only based on performance but power consumption, freeing up the CPU, etc.
> > So I agree to make it work the opposite way.
> 
> No problem, I will send PR.
> 
> > An other note: I've realized that we don't need to store the preferred score in `draw_task` but we can do something like:
> > ```c
> >         /*Let the draw units assign the draw task*/
> >         uint8_t score = 100;
> >         t->preferred_draw_unit_id = 0;
> >         lv_draw_unit_t * u = info->unit_head;
> >         while(u) {
> >             if(u->evaluate_cb) u->evaluate_cb(u, t, &score);
> >             u = u->next;
> >         }
> > ```
> 
> I think it is more appropriate to keep the preference score in `lv_draw_task_t`, because considering that more parameters may need to be expanded in the future, the public interface can be modified as little as possible.

**Comment by kisvegabor** [comment]
> I think it is more appropriate to keep the preference score in lv_draw_task_t, because considering that more parameters may need to be expanded in the future, the public interface can be modified as little as possible

Good point! What about having
```c
typedef struct
{
  uint8_t score;
}lv_draw_evaluate_data_t;
```

It would keep the door open for changes without API break, yet we don't have to store it in draw tasks.

**Comment by FASTSHIFT** [comment]
I still think it is better to put it in `lv_draw_task_t`, because `lv_draw_task_t` runs through the context of the entire drawing task process, which is very convenient for debugging. I also prefer simple parameter passing.

**Comment by kisvegabor** [comment]
Ok, 1 byte  of extra data/draw task shouldn't hurt much. :slightly_smiling_face:

**Pull request merged**
