### PR TITLE
fix bug : memory leak when set LV_TABVIEW_TAB_POS_RIGHT

### PR DESCRIPTION
**Pull request by incity**
### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]
Looks good to me.

**Comment by kisvegabor** [comment]
Thanks.

I think not freeing odd-th elements of the array in case of POS_RIGHT/LEFT is safer because for any strange reason the user might add a `"\n"` tab to a  POS_TOP tabview too.

**Comment by embeddedt** [comment]
I agree with @kisvegabor.

**Comment by kisvegabor** [comment]
ping @incity

**Comment by kisvegabor** [comment]
I've fixed it here and in v8 (152dffcc) too.

**Pull request closed without merging**
