### PR TITLE
Kconfig: Handle LV_SPRINTF_DISABLE_FLOAT

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Handles LV_SPRINTF_DISABLE_FLOAT when using Kconfig, see #1987

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by C47D** [comment]
Should I squash the commits on my end or can you do it?

**Comment by embeddedt** [comment]
I can do it (GitHub allows multiple types of merging). Is this the only option where this problem would happen, or can it happen anywhere where "on" is the default setting? Wondering about `LV_ANTIALIAS`, etc.

**Comment by C47D** [comment]
It's the only option I have checked, because of the issue related to it, I can check other configuration options as well.

I was thinking on the name of this configuration, maybe call it ENABLE (and set it to 0 by default) instead of DISABLE, but we can discuss about in the future.

**Comment by embeddedt** [comment]
> I was thinking on the name of this configuration, maybe call it ENABLE (and set it to 0 by default) instead of DISABLE, but we can discuss about in the future.

Good idea; it's better for us to be consistent. Right now 1 means enable on some configs and disable on others. v8 would be a good opportunity to fix this issue. We can keep full backwards compatibility by checking for the presence of the old define.

**Comment by C47D** [comment]
We can try identify all the configurations to be changed in v8 and open an issue for that.

**Comment by C47D** [comment]
Ready to merge, tested in https://github.com/lvgl/lvgl/issues/1987#issuecomment-753594079

**Comment by kisvegabor** [comment]
Merging, thank you!

**Comment by kisvegabor** [comment]
I needed to apply a [fix](https://github.com/lvgl/lvgl/commit/998ad66c84258e5638ef5e3669934a481c3615f6) when not used with Kconfig.

In [lv_conf_internal.h](https://github.com/lvgl/lvgl/blob/998ad66c84258e5638ef5e3669934a481c3615f6/src/lv_conf_internal.h#L20-L48) `lv_conf_kconfig.h` is included before `lv_conf.h` In `lv_conf_kconfig.h` ` LV_SPRINTF_DISABLE_FLOAT` is defined therefore in [lv_conf.h](https://github.com/lvgl/lvgl/blob/998ad66c84258e5638ef5e3669934a481c3615f6/lv_conf_template.h#L540) it's redefined.

**Pull request merged**
