### PR TITLE
ci: use ubuntu-22.04 instead of ubuntu-latest

### PR DESCRIPTION
**Pull request by kisvegabor**
### Description of the feature or fix

Related to https://github.com/lvgl/lvgl/pull/5878#discussion_r1527148235

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
The CI doesn't want to queue some of the actions. I don't know if it's just a temporal issue, or related to ubuntu 24.04 somehow.

**Comment by kdschlosser** [comment]
@kisvegabor 

Ubuntu 24.04 is not available on github actions using `runs-on: ubuntu-24.04` It is only available using `runs-on: ubuntu-latest` from what I have found. I can find reference to 22.04 being available by specifying the version.

Maybe we should go and ask the folks over at SDL how come they don't release a higher version of SDL2 to the package index for Ubuntu. the version of SDL that is available for 22.04 is over 2 years old. I am not sure why there is only the one release available for Ubuntu 22.04.. I am going to open an issue over there and ask that question because frankly it seems rather crazy to do that considering Ubuntu 24.04 hasn't even been released yet The beta is being released in April 11th

**Comment by kdschlosser** [comment]
well I just got stone walled by the people over at SDL. They say it is the responsibility of the people that maintain Ubuntu to update the packages. Which is not the case and I know that. I am guessing that they are not the people that put the package in the Ubuntu index in the first place.

But they did give me this link.

https://github.com/libsdl-org/setup-sdl

That can be used to compile SDL2 using github actions

**Comment by kisvegabor** [comment]
It's working with Ubuntu 22.04. I recommend using it until Ubuntu 24.04 is released. What do yo think?

**Review by XuNeo — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]

**Comment by kdschlosser** [comment]
OK I am going to mess about with #5878 and get the merge conflicts sorted out.

Would you like me to add double buffering support (in a separate PR)???

**Pull request merged**
