### PR TITLE
Unit tests for Animation Image widget

### PR DESCRIPTION
**Pull request by pablojr**
Added a set of test cases for the Animation Image widget.
Based on the example for that widget.
Asserts are simple because widget has not getters and I didn´t like to check by directly accessing internal details (which might change in the future).

Code coverage
               | Exec | Total | Coverage
Lines            39 | 39     | 100.0%
Branches        0 |      0 |          -%

### CODE REVIEW

**Comment by kisvegabor** [comment]
It's really not well testable in it's current state. Would you mind adding some getters?

**Comment by pablojr** [comment]
@kisvegabor yes, I'll add the getters although I'll be away from keyboard for a week or so. Thanks

**Comment by kisvegabor** [comment]
No problem, thank you!

**Comment by kisvegabor** [comment]
Not stale

**Comment by pablojr** [comment]
@kisvegabor thank you for removing tag. Not stale indeed, but I didn´t provide an updated PR so far :-)
The thing is that looking at the code it looks like I need to add some getters to lv_anim and lv_img as well so the specific getters at lv_animimg can work fine without going into internals or implementation details.
I'll try to speed things up. Thanks.

**Comment by kisvegabor** [comment]
> The thing is that looking at the code it looks like I need to add some getters to lv_anim and lv_img as well so the specific getters at lv_animimg can work fine without going into internals or implementation details.

I suggest focusing on the `lv_anim` related parts now and add `lv_animimg_get_...` functions which can use `anim->...` hidden inside.

**Comment by pablojr** [comment]
@kisvegabor I am sorry I didn't check that you had force-pushed my change for the getters before doing a cherry-pick for such change into my local branch.
Do you want to abandon/remove this PR?
I can create another new PR so the final merge is more straightforward if you like.
Please let me know

**Comment by kisvegabor** [comment]
> I am sorry I didn't check that you had force-pushed my change for the getters before doing a cherry-pick for such change into my local branch.

Honestly, I don't know what have happened and how these commits are ralated to this PR.

> Do you want to abandon/remove this PR?
I can create another new PR so the final merge is more straightforward if you like.

Why can't we merge it as it is?

**Comment by pablojr** [comment]
> Honestly, I don't know what have happened and how these commits are ralated to this PR.
OK

> Why can't we merge it as it is?

I guess you can. I hope git will be smart enough to check that my cherry-pick and  PR #3773 are the same change.

**Comment by kisvegabor** [comment]
The changed files looked good. I think it should be alright. Please send the 50 USD expense on [opencollective.com](https://opencollective.com/) .

**Pull request merged**
