### PR TITLE
Improve LittlevGL power efficiency

### PR DESCRIPTION
**Pull request by embeddedt**
This is a draft PR to enable easy viewing of the changes being made.

Discussion: https://forum.littlevgl.com/t/rfc-reduce-cpu-usage-when-idle/1340

### CODE REVIEW

**Comment by embeddedt** [comment]
@kisvegabor The method I am using to suspend the tasks involves switching a task's priority while it is the active, running task. Is this properly handled by `lv_task_handler` right now or do I need to add special logic to deal with the changing linked list (like `anim_list_changed`)?

**Comment by kisvegabor** [comment]
Look's good at first glance but 2 things are not clear:
- Animations and rendering can be suspended but indev read still runs, doesn't it?
- Is the goal to sleep e.g. 100 ms if the return value of `lv_task_handler > 100`?

**Comment by embeddedt** [comment]
> Animations and rendering can be suspended but indev read still runs, doesn't it?

I haven't added input device suspension yet, but that will also be available. I wrote a little blurb here: https://forum.littlevgl.com/t/rfc-reduce-cpu-usage-when-idle/1340/5?u=embeddedt.

> Is the goal to sleep e.g. 100 ms if the return value of lv_task_handler > 100?

You sleep for whatever the return value of `lv_task_handler` is. If it returns `LV_NO_TASK_READY` then you should sleep until any external stimulus arrives (input or some other interrupt).

**Comment by kisvegabor** [comment]
I've [answered](https://forum.littlevgl.com/t/rfc-reduce-cpu-usage-when-idle/1340/5) in the Forum. Let's continue there.

**Comment by embeddedt** [comment]
Still working on it; not stale.

**Comment by kisvegabor** [comment]
I like this feature in principle so it can be merged for my part. 

Is there anything else to add?

**Comment by embeddedt** [comment]
It seems to me that this is safe to merge in its current state. I can always come back later to address input devices.

I'd just like to know whether [what I mentioned above](https://github.com/littlevgl/lvgl/pull/1309#issuecomment-56433218) could be an issue in the long run? It seems to me that it might not be very easy to debug if anything weird does happen.

**Comment by kisvegabor** [comment]
> The method I am using to suspend the tasks involves switching a task's priority while it is the active, running task. Is this properly handled by lv_task_handler right now or do I need to add special logic to deal with the changing linked list (like anim_list_changed)?

That's corect, `anim_list_changed = true` is really required in `lv_task_set_prio`.

**Comment by embeddedt** [comment]
I've added it.

**Comment by kisvegabor** [comment]
Looks good, thank you very much!
I haven't tested it yet but we can merge it to `dev-7.0`.

I'm thinking about we can start to write tests as the new features come but I'll will write about it in more detail the related issue soon.

**Comment by nacyzhouw** [comment]
hi,
   Is indev read still runs without suspended ? I see the discusstion  has memtioned using the TP interrupt, but it seems be not Implemented now?

**Comment by embeddedt** [comment]
I haven't finished implementing full support for non-polling input devices yet.

**Pull request merged**
