### PR TITLE
Add lvgl/src to include path to avoid using ../../ everywhere

### PR DESCRIPTION
**Pull request by XuNeo**
### Description of the feature or fix

Now the include path looks much more cleaner.
And we can see clearly which module the header belongs to.

```c
#include "display/lv_display.h"
#include "display/lv_display_private.h"
#include "misc/lv_color.h"
#include "stdlib/lv_string.h"
#include "core/lv_global.h"
```

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<module_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
It would be really great, but unfortunately we cannot do that. Mainly because for Arduino libraries we can't set any compiler flags.  :slightly_frowning_face:

**Comment by XuNeo** [comment]
> It would be really great, but unfortunately we cannot do that. Mainly because for Arduino libraries we can't set any compiler flags. 🙁

How I can check it? Could you point to a doc of building on arduino?

Micropython binding with lvgl master branch complains on my local setup. Do you know which version that CI uses? 
```bash

../../lib/lv_bindings/lv_conf.h:322:26: error: implicit declaration of function ‘MP_STATE_VM’ [-Werror=implicit-function-declaration]
  322 |     #define LV_GC_INIT() MP_STATE_VM(lvgl_root_pointers) =  m_new0(lvgl_root_pointers_t, 1)
      |                          ^~~~~~~~~~~
../../lib/lv_bindings/lvgl/src/lv_init.c:115:5: note: in expansion of macro ‘LV_GC_INIT’
  115 |     LV_GC_INIT();
      |     ^~~~~~~~~~
CC ../../lib/lv_bindings/lvgl/src/widgets/roller/lv_roller.c
../../lib/lv_bindings/lv_conf.h:322:38: error: ‘lvgl_root_pointers’ undeclared (first use in this function)
  322 |     #define LV_GC_INIT() MP_STATE_VM(lvgl_root_pointers) =  m_new0(lvgl_root_pointers_t, 1)
      |                                      ^~~~~~~~~~~~~~~~~~
../../lib/lv_bindings/lvgl/src/lv_init.c:115:5: note: in expansion of macro ‘LV_GC_INIT’
  115 |     LV_GC_INIT();
      |     ^~~~~~~~~~
../../lib/lv_bindings/lv_conf.h:322:38: note: each undeclared identifier is reported only once for each function it appears in
  322 |     #define LV_GC_INIT() MP_STATE_VM(lvgl_root_pointers) =  m_new0(lvgl_root_pointers_t, 1)
      |                                      ^~~~~~~~~~~~~~~~~~
../../lib/lv_bindings/lvgl/src/lv_init.c:115:5: note: in expansion of macro ‘LV_GC_INIT’
  115 |     LV_GC_INIT();
      |     ^~~~~~~~~~
../../lib/lv_bindings/lv_conf.h:322:61: error: implicit declaration of function ‘m_new0’ [-Werror=implicit-function-declaration]
  322 |     #define LV_GC_INIT() MP_STATE_VM(lvgl_root_pointers) =  m_new0(lvgl_root_pointers_t, 1)
      |                                                             ^~~~~~
../../lib/lv_bindings/lvgl/src/lv_init.c:115:5: note: in expansion of macro ‘LV_GC_INIT’
  115 |     LV_GC_INIT();
      |     ^~~~~~~~~~
CC ../../lib/lv_bindings/lvgl/src/widgets/bar/lv_bar.c
../../lib/lv_bindings/lv_conf.h:322:68: error: ‘lvgl_root_pointers_t’ undeclared (first use in this function)
  322 |     #define LV_GC_INIT() MP_STATE_VM(lvgl_root_pointers) =  m_new0(lvgl_root_pointers_t, 1)
```

**Comment by kisvegabor** [comment]
For MicroPython you should use the `feat/multi-instance` branch in both the `lv_micropython` and `lv_binging_micropython` repos.

**Comment by XuNeo** [comment]
Hi Gabor,
I have tried arduino with master branch and this PR. It compiles OK when only use #include <lvgl.h>.
For v8.3, there's a standalone lv_example library for arduino, what do you plan on v9?

I also tried using symbolic link locally and arduino can find it successfully. But it's forbidden by arduino.

image

**Comment by kisvegabor** [comment]
> For v8.3, there's a standalone lv_example library for arduino, what do you plan on v9?

Actually it's for v7. Since v8 we have both the examples and demos in lvgl.  See [here](https://docs.lvgl.io/8.3/get-started/platforms/arduino.html#use-the-examples-and-demos)

---

To be honest I'm not 100% sure about this change. Now LVGL is fully compiler configuration free. You can just drop it into any environment  and compile the C files. That's it. Even thought it's a simple config I don't know what kind of problems will it cause for library managers like:
-  Arduino (it seems ok)
- PlatformIO
- Espressif
- RT-Thread

I think Arduino is the simplest of any of these, but I'm really not sure at this point. 

What is the added value in the end? Nicer includes in the internal `src` files? We don't modify these too often, so I would rather leave with them, instead of introducing the the need for compiler config.

**Comment by XuNeo** [comment]
> Actually it's for v7. Since v8 we have both the examples and demos in lvgl. See [here](https://docs.lvgl.io/8.3/get-started/platforms/arduino.html#use-the-examples-and-demos)

Get it. So it's still a work around.



> Now LVGL is fully compiler configuration free.

But it's not.  Check [this commit of](https://github.com/lvgl/lvgl/pull/4806/commits/93aad0b7246de1a8441a61ea1eccf86fa25117f6) where `lvgl/src` path is added along side `lvgl/`. You can see multiple setting for both Cmake and Makefile to set the including path. 
If you prefer to add only one include path which currently is `lvgl/`, then I think we can change it to `lvgl/src`, naming `LVGL_SRC_ROOT`. And move `demos/` `examples/` to `src/`. From the usage of arduino, it's clear that `demos` and `examples` are now part of `lvgl`'s main source code.

So it's just another shot pain but makes code looks much cleaner and now we can understand which module are we including based on folder structure. I'm happy to investigate further about `PlatformIO` `Espressif` `RT-Thread` but respect your decision.

**Comment by XuNeo** [comment]
I have successfully adapted the code for ESP32, Unix, and RP2 in MicroPython. However, this requires an additional include path to preprocessing step for the headers. The original `lvgl/lvgl.h` does not require any compiler settings adjustments.

After thorough consideration, I have been unable to find a more efficient solution, so I've decided to close this Pull Request.

**Comment by kisvegabor** [comment]
Thank you for the investigation anyway!

**Pull request closed without merging**
