### PR TITLE
calendar: add option to start week on Monday

### PR DESCRIPTION
**Pull request by diegoherranz**
Using define LV_CALENDAR_WEEK_STARTS_MONDAY.
Using a define it's not possible to change this configuration on the fly,
but it was the simplest approach and it doesn't change the API at all.

Thanks!

### CODE REVIEW

**Comment by diegoherranz** [comment]
The build reports:

```
/home/runner/work/lvgl/lvgl/tests/../../lvgl/src/lv_widgets/lv_calendar.c:60:5: error: "LV_CALENDAR_WEEK_STARTS_MONDAY" is not defined, evaluates to 0 [-Werror=undef]
```
I guess that should be explicitly defined as 0? Where?

Thanks!

**Comment by embeddedt** [comment]
It should be added to `lv_conf_template.h`. Then, I think you will also need to run `scripts/lv_conf_checker.py` to regenerate `lv_conf_checker.h`.

**Comment by diegoherranz** [comment]
Added to `lv_conf_template.h` and regenerated `lv_conf_internal.h`
Please note that there are a few more changes to `lv_conf_internal.h` that showed up when I regenerated it, but I haven't included those here.

Thanks!

**Review by embeddedt — APPROVED** [review]

**Comment by embeddedt** [comment]
Thanks! It should be released with 7.2.

**Pull request merged**
