### PR TITLE
lv_chart: Use circular buffer to avoid memcopy for every new data point

### PR DESCRIPTION
**Pull request by kaythe**
This pull request contains the implementation suggested in issue #594.

This makes the cost of adding a data point independent of array size.
Changing the array size is more complicated, but that will most likely
happen a lot less than adding a data point.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,
I've just tested your update and added some fixes.

Please, verify if it still worked with your test case.

**Comment by kaythe** [comment]
I've tested it and it works fine.

I noticed that most of those fixes are in places I didn't know about because I was basing it on master and not dev-5.3. For future reference: Should I use dev-5.3 for pull requests or stay on master?

**Comment by kisvegabor** [comment]
Great! Thank you! :)

Yes, the new feature always goes to the current `dev-x.y` branch. Only bugfixes are merged to `master` directly.

**Comment by kaythe** [comment]
Okay, I'll keep that in mind.

**Pull request merged**
