### PR TITLE
feat(vg_lite_tvg): add vg_lite_set_scissor function support

### PR DESCRIPTION
**Pull request by FASTSHIFT**
Use thorvg's viewport function to simulate the GPU scissor function.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
FYI, the CI is failing.

**Comment by FASTSHIFT** [comment]
> FYI, the CI is failing.

Yeah, it's a known problem. It's still under investigation.

**Comment by FASTSHIFT** [comment]
> FYI, the CI is failing.

Fixed. The problem is that you should remove the bonding box setting for path itself when using scissor clipping.

**Review by XuNeo — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
:+1:

**Comment by FASTSHIFT** [comment]
> This PR will cause [#6845](https://github.com/lvgl/lvgl/pull/6845) failure, thorvg draw pipeline infinite loop

Fix here: https://github.com/lvgl/lvgl/pull/7037

**Pull request merged**
