### PR TITLE
Add conditional macro LV_USE_GROUP to more GROUP related singles:

### PR DESCRIPTION
**Pull request by liangyongxiang**
[Related discussions](https://forum.lvgl.io/t/signal-function-handles-group-related-signals-when-lv-use-group-is-disabled/2562/3)

### CODE REVIEW

**Comment by liangyongxiang** [comment]
Also, do we need to fix this issue in V6?

**Comment by embeddedt** [comment]
I think we should leave v6 alone, as this is more of a feature than a bugfix.

**Review by embeddedt — APPROVED** [review]
@kisvegabor Should this be merged to `master` or `dev`?

**Comment by kisvegabor** [comment]
@liangyongxiang 
Thank you!

@embeddedt 
We still have ~ 1 week to release v7.2 so if there are any issues it should turn out. Do you agree?

**Comment by embeddedt** [comment]
@kisvegabor Do you mean 7.1, not 7.2? The latest release right now is 7.0.2... are we skipping a minor version?

I guess there's no issue with merging it straight to `master` since the CI tests will probably catch any build failures anyways.

**Comment by kisvegabor** [comment]
I meant v7.1, sorry :slightly_smiling_face:

**Pull request merged**
