### PR TITLE
feat(text): handle Combining Diacritical Marks range when typesetting

### LINKED ISSUE #7090: Combining Diacritical Marks do not render properly
### LVGL version

v8.4.0

### What happened?

I would like to render the test phrase "B̶̹̌e̷̘͝ ̵͙̀N̴̹̂o̷̻͛t̴̰̎ ̵̱̓Ą̶͒f̶̳̕r̵̿ͅa̴̧͝ì̷̬d̵̩́", but instead, LVGL's label widget displays:
image

Each combining mark is rendered as a missing character. If a combining mark is missing from the font, could we instead skip drawing it?

### How to reproduce?

Render "B̶̹̌e̷̘͝ ̵͙̀N̴̹̂o̷̻͛t̴̰̎ ̵̱̓Ą̶͒f̶̳̕r̵̿ͅa̴̧͝ì̷̬d̵̩́"

### PR DESCRIPTION
**Pull request by kisvegabor**
fixes #7090

cc @bryghtlabs-richard 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by bryghtlabs-richard — APPROVED** [review]
This looks good to me.

**Comment by kisvegabor** [comment]
I was thinking about this issue and as it's doesn't work for both lower and upper case letters and doesn't work for [Devanagari](https://en.wikipedia.org/wiki/Devanagari) I wouldn't merge it.  

For CDM you there is a single unicode character for each combination and it can be used instead.  What do you think?

**Comment by bryghtlabs-richard** [comment]
I just got back from out of town last week.

>For CDM there is a single unicode character for each combination and it can be used instead. What do you think?

Sorry, I'm not sure I understand. Do you mean using pre-composed NFC form characters instead of NFD characters with the base character + CDM? Sadly, we need to handle user-specified input here. Though if you prefer to require applications to normalize their strings to NFC form before displaying, that would be fine if we added it to the LVGL documentation.

Separately, normalizing to NFD and handling CDMs correctly can make the fonts smaller overall, as the total number of glyphs in the font is smaller.

**Comment by kisvegabor** [comment]
No worries! :slightly_smiling_face: 

Yes, I mean normalizing the text to NFC before sending it to LVGL. My problem is that we can't display both upper and lower cased latter correctly, so I wouldn't add a half working "solution".

**Comment by bryghtlabs-richard** [comment]
That works for me, but we should update the documentation to reflect that.

Maybe "LVGL supports most UTF-8 encoded Unicode characters. Combining diacritical marks must be pre-composed in NFC form"

Eventual support for NFD is still welcome as it will cut down the font sizes for us.

**Pull request closed without merging**
