### PR TITLE
Add reference to RIOT OS LittlevGL Package in README

### PR DESCRIPTION
**Pull request by OkiStuff**
### Description of the feature or fix
Add a reference to the LVGL Package included in RIOT OS

### CODE REVIEW

**Comment by kisvegabor** [comment]
Good to know, thank you. :relaxed: 

Note that, LittlevGL was renamed to LVGL couple of years ago. Would mind updating your docs to use the LVGL name instead of LittlevGL?  

EDIT:
I assumed that you are associated with Riot OS. Really this is the case? :slightly_smiling_face:

**Comment by OkiStuff** [comment]
I'm not heavily associated with Riot OS but a friend of mine is, so I wanted to help them out a bit. I'll make a PR to the Riot OS docs to update the name. Thanks :)

**Comment by kisvegabor** [comment]
Cool, thank you! :slightly_smiling_face:

**Comment by OkiStuff** [comment]
Leaving a comment to say that the PR to change LittlevGL to LVGL in the docs has been merged. Apologies for how long it took.

**Comment by kisvegabor** [comment]
No problem, thank you for letting us know!

**Pull request merged**
