### PR TITLE
Add CmakeLists.txt

### PR DESCRIPTION
**Pull request by C47D**
To make LVGL an ESP-IDF v4.x component it needs an CMakeLists.txt file, we check for ESP_PLATFORM to add the necessary commands.

### CODE REVIEW

**Review by kisvegabor — APPROVED** [review]
Looks good!

**Review by embeddedt — COMMENTED** [review]
Can it output an error if someone tries to build it outside of ESP-IDF so they know that it's not a generic CMake file?

**Comment by C47D** [comment]
Yes, it can, what error message do you have in mind?

**Comment by kisvegabor** [comment]
Maybe an "Unknown platform" is none of the "if"s matches? (Of course only ESP for now)

**Comment by C47D** [comment]
Done!, please let me know if 8134044 solves it.

**Review by embeddedt — APPROVED** [review]

**Comment by C47D** [comment]
8134044 isn't listed on the dev branch. Does it take a while to do so?

**Comment by embeddedt** [comment]
I squash merged (so all the changes are in one commit).

**Comment by C47D** [comment]
Cool, thanks!

**Pull request merged**
