### PR TITLE
fix(chart,ticks): change line chart ticks

### PR DESCRIPTION
**Pull request by CMoranMINTL**
### Description of the feature or fix

Change amount of tick marks for the chart widget to be equal to amount of data points if chart is of type LV_CHART_TYPE_LINE. Reference discussion can be found in this forum [post](https://forum.lvgl.io/t/line-graph-x-axis-tick-labels/10821).

### Checkpoints
- [ ] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by pete-pjb** [comment]
A note for @kisvegabor, hope you are well! Long time no speak. 😃  I have been working with @CMoranMINTL on this pull request and thought you might like to see if you want to back port it.

Thank you for your contribution @CMoranMINTL .

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
Hi @CMoranMINTL and @pete-pjb,

If I understood correctly, the problem is that the ticks always end on a major tick, but in some cases should end on minor tick. Is this correct?

In v9, I was planning to unify and reconsider how the "tick APIs".  Now we need to set the number of major ticks and the number of minors between them. This way it's not possible to create ticks like:
```
| , , , , | , , , , | , ,
```

I think a more flexible solution would be to specify the total number of ticks (12 in the above example) and a step count for majors (5 in the example). In the chart example from the forum it'd be `tick_count = 50`, `nth_major = 2`. 

What do you think? I know that it's a larger change though.

**Comment by pete-pjb** [comment]
Hi @kisvegabor ,

I think that approach works well, it is probably simpler for the user too.

Kind Regards,

Pete

**Comment by CMoranMINTL** [comment]
Hi @kisvegabor ,

You are understanding the problem correctly. I also agree the proposed v9 solution would be a more eloquent way to accomplish this.

**Comment by kisvegabor** [comment]
>  I also agree the proposed v9 solution would be a more eloquent way to accomplish this.

Happy to hear that :slightly_smiling_face:

Are you interested in making some experiments with it?

**Comment by CMoranMINTL** [comment]
> Are you interested in making some experiments with it?

I am interested for sure, but I'm currently only using LVGL for my day job and I'm unsure how much time I'd be able to dedicate to it. Perhaps, in the future, if I use LVGL for a personal project I may have more time for it, for now I will have to say no.

**Comment by kisvegabor** [comment]
No problem, I perfectly understand. 

Anyway, I leave this issue open for while. In the hope that someone picks it up.

**Comment by C47D** [comment]
Hi @kisvegabor , what would be a good api name for those operations?

> I think a more flexible solution would be to specify the total number of ticks (12 in the above example) and a step count for majors (5 in the example). In the chart example from the forum it'd be tick_count = 50, nth_major = 2.

**Comment by C47D** [comment]
With less than 50 ticks it works as expected, e.g. 5
imagen

imagen
or 25
imagen

With 50 it does this:
imagen

Funny I can see the tick value string with the correct value:
imagen

The updates are in https://github.com/C47D/lvgl/tree/chart_ticks_test

**Comment by C47D** [comment]
Fixed the issue by disabling the `lv_obj_add_event_cb(ui.chart, draw_tick_marks_cb, LV_EVENT_DRAW_PART_BEGIN, NULL);` code from the forum example code

imagen

**Comment by C47D** [comment]
Here's the output with the following configuration code, the x axis is configured to set a major tick every 5 ticks.

```c
static void update_data_points(lv_event_t* e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t* obj = lv_event_get_target(e);

    if (code != LV_EVENT_VALUE_CHANGED)
    {
        return;
    }

    char dropdown_str[4] = { '\0' };
    lv_coord_t major_count = 0;
    lv_coord_t minor_count = 0;

    lv_dropdown_get_selected_str(obj, dropdown_str, 4);
    data_point_count = (uint16_t) strtod(dropdown_str, NULL);

    LV_LOG_USER("Data point count %d", data_point_count);

    lv_chart_set_point_count(ui.chart, data_point_count);
    lv_chart_set_axis_tick_count(ui.chart, LV_CHART_AXIS_PRIMARY_X, data_point_count);
    lv_chart_set_axis_tick_nth_major(ui.chart, LV_CHART_AXIS_PRIMARY_X, 5);
}
```

imagen

imagen

**Comment by kisvegabor** [comment]
Hi Carlos,

I think ultimately we should go for a `scale` widget as I described [here](https://github.com/lvgl/lvgl/issues/4043#issuecomment-1464386802). It could be widely used for the existing widgets and for any custom purpose. What do you think about it?

**Comment by C47D** [comment]
So instead of using ticks and labels in the chart we should use a scale instead? It would be really useful for re-usability, but I'm worried about time, I can work here in small batches of time.

I would do it like this, let me know if you agree:
- Land this update once is ready
- Create scale widget (this two can be done in parallel)
- Incrementally use it in other widgets

**Comment by kisvegabor** [comment]
> Land this update once is ready

I find the currently proposed solution (in the PR now) not general enough, but if it will be replaced by the scale widget in v9, I'm ok with it as a temporal solution.

**Comment by C47D** [comment]
Well, I think the original issue was solved with this PR (without my changes) and a custom draw callback. So maybe we can merge it and later use the new widget.

**Comment by kisvegabor** [comment]
Okay, merging. Thanks!

**Pull request merged**
