### PR TITLE
docs: fix references, lists, texts

### PR DESCRIPTION
**Pull request by PGNetHun**
Help us review this PR! Anyone can [approve it or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### Description of the feature or fix

- Fix document references
- Fix lists
- Fix some Sphinx domains
- Fix some text formattings
- Fix some Notes
- Update copyright year to 2024

### Checkpoints
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)

### CODE REVIEW

**Comment by PGNetHun** [comment]
This PR is the second package of documentation update. (Previous: https://github.com/lvgl/lvgl/pull/5138 )

**Comment by PGNetHun** [comment]
@kdschlosser , @kisvegabor 
It seems the previously added section targets (example: `.. _lv_image:`) conflict with the source code targets, so I want to change again these in the `lvgl/docs/widgets` folder. 

Example: https://github.com/lvgl/lvgl/blob/master/docs/widgets/image.rst?plain=1#L1 


What do you suggest?  

Should I simply:
1. remove `lv_` prefix:  `.. _lv_image:` -> `.. _image:`
2. or replace `lv_` to `widget_` prefix:  `.. _lv_image:` -> `.. _widget_image:`

**Comment by kdschlosser** [comment]
I think we should add that automatic reference generator for Sphinx. How the references gets done would be :ref:`path\to\file: header label`. I actually like this because you actually know where the reference is pointing to when you look at the REsT files.

**Comment by PGNetHun** [comment]
> I think we should add that automatic reference generator for Sphinx. How the references gets done would be :ref:`path\to\file: header label`. I actually like this because you actually know where the reference is pointing to when you look at the REsT files.

What do you suggest?

In this PR there are other changes/fixes also, not only reference fixes.

**Comment by kisvegabor** [comment]
I think we can consider the references fixed in the PR a good temporary solution and we should move to automatic  reference generator.

**Comment by kdschlosser** [comment]
going automatic is going to add references for headers that don't already have references. so the changes made here can stay how they are and nothing needs to be changed. Once I get the automatic references added we can optionally remove these at a later point in time if we want to. What will need to be done is there will need to be changes made for the ones that don't exist but there are links in the documentation. Those links will need to be updated to point to the automatically generated references. This will not be that hard to do because the current links contain the information that is needed. we should be able to write a simple script to handle changing those.


This is a reference to a section in the same document.
\`below \<#color-format\>\`\_\_

This is a reference to another document
\`File system \</overview/file-system\>\`\_\_

and this is a reference to a section in another document
\`BLAH \</overview/file-system/#section\>\`\_\_

changing those references to read

:ref:\`path/to/document:section\` 

shouldn't be that hard to do.

**Comment by kisvegabor** [comment]
Okay, clear! I merge this one now, and let's continue with the reference/link update.

**Review by kisvegabor — APPROVED** [review]

**Comment by kdschlosser** [comment]
yessir will do.

I will get to work on implementing that.

**Comment by kdschlosser** [comment]
OK so I have the list of generated  reference names. If someone wants to edit all of the :ref: directives and use the names seen in this list that would be most helpful.


<details>
  <summary>Click me</summary>
  
```
        changelog:changelog
        changelog:others
        changelog:v8.3
        changelog:v9.0.0
        
        
        coding_style:coding guide
        coding_style:coding style
        coding_style:comments
        coding_style:file template
        coding_style:formatting
        coding_style:hooks
        coding_style:naming conventions
        coding_style:pre-commit
        coding_style:skipping hooks
        coding_style:testing hooks
        
        
        contributing:contributing
        contributing:developer certification of origin (dco)
        contributing:introduction
        contributing:pull request
        contributing:ways to contribute
        
        
        examples:animations
        examples:events
        examples:examples
        examples:get started
        examples:layouts
        examples:scrolling
        examples:styles
        examples:widgets
        
        
        get-started/index:get started
        
        
        get-started/quick-overview:a button with a label and react on click event
        get-started/quick-overview:a very simple
        get-started/quick-overview:add lvgl into your project
        get-started/quick-overview:create a slider and write its value on a label
        get-started/quick-overview:create styles from scratch for buttons
        get-started/quick-overview:examples
        get-started/quick-overview:get started in a simulator
        get-started/quick-overview:learn the basics
        get-started/quick-overview:micropython
        get-started/quick-overview:quick overview
        
        integration/bindings/index:bindings

        integration/bindings/cpp:cpp
        
        integration/bindings/javascript:animation
        integration/bindings/javascript:building
        integration/bindings/javascript:components
        integration/bindings/javascript:demo
        integration/bindings/javascript:features
        integration/bindings/javascript:font
        integration/bindings/javascript:javascript
        integration/bindings/javascript:style
        integration/bindings/javascript:table of contents
        integration/bindings/javascript:thanks
        
        integration/bindings/micropython:how can i use it?
        integration/bindings/micropython:micropython
        integration/bindings/micropython:so what does it look like?
        integration/bindings/micropython:the micropython binding is auto generated!
        integration/bindings/micropython:what is micropython?
        integration/bindings/micropython:where can i find more information?
        integration/bindings/micropython:why micropython + lvgl?
        
        integration/bindings/pikascript:how can i use it?
        integration/bindings/pikascript:how does it work?
        integration/bindings/pikascript:pikascript
        integration/bindings/pikascript:so how does it look like?
        integration/bindings/pikascript:what is pikascript ?
        integration/bindings/pikascript:why pikascript + lvgl ?
        
        integration/chip/espressif:espressif (esp32 chip series)
        integration/chip/espressif:lvgl demo project for esp32
        integration/chip/espressif:using lvgl in your esp-idf project
        integration/chip/espressif:using lvgl_esp32_drivers in esp-idf project
        
        integration/chip/index:chip vendors
        
        integration/chip/nxp:creating new project with lvgl
        integration/chip/nxp:hw acceleration for nxp imx rt platforms
        integration/chip/nxp:nxp
        
        integration/chip/stm32:bare metal example
        integration/chip/stm32:freertos example
        integration/chip/stm32:including lvgl in a project
        integration/chip/stm32:stm32
        
        
        
        integration/driver/index:drivers

        integration/driver/display/index:display
        integration/driver/display/ili9341:ili9341
        
        integration/driver/touchpad/ft6x36:ft6x36
        integration/driver/touchpad/index:touchpad
        
        integration/driver/x11:configure x11 driver
        integration/driver/x11:overview
        integration/driver/x11:prerequisites
        integration/driver/x11:usage
        integration/driver/x11:x11 display/inputs driver
        
        
        integration/framework/index:frameworks

        integration/framework/arduino:arduino
        integration/framework/arduino:configure lvgl
        integration/framework/arduino:debugging and logging
        integration/framework/arduino:get the lvgl arduino library
        integration/framework/arduino:initialize and run lvgl
        integration/framework/arduino:set up drivers
        integration/framework/arduino:use the examples and demos
        
        integration/framework/platformio:platformio
        
        integration/framework/tasmota-berry:how can i use it?
        integration/framework/tasmota-berry:so what does it look like?
        integration/framework/tasmota-berry:tasmota and berry
        integration/framework/tasmota-berry:what is berry?
        integration/framework/tasmota-berry:what is tasmota?
        integration/framework/tasmota-berry:where can i find more information?
        integration/framework/tasmota-berry:why lvgl + tasmota + berry?
        
        
        integration/index:integration and drivers

        integration/ide/index:ides
        integration/ide/mdk:mdk
        integration/ide/pc-simulator:select an ide
        integration/ide/pc-simulator:set-up eclipse cdt
        integration/ide/pc-simulator:simulator on pc
        
        integration/os/index:(rt)os

        integration/os/freertos:freertos
        
        integration/os/nuttx:how to get started with nuttx and lvgl?
        integration/os/nuttx:nuttx rtos
        integration/os/nuttx:what is nuttx?
        integration/os/nuttx:where can i find more information?
        integration/os/nuttx:why nuttx + lvgl?
        
        integration/os/px5:px5 rtos
        
        integration/os/rt-thread:how to run lvgl on rt-thread?
        integration/os/rt-thread:rt-thread rtos
        integration/os/rt-thread:what is rt-thread?
        
        integration/os/zephyr:how to run lvgl on zephyr?
        integration/os/zephyr:leveraging zephyr features
        integration/os/zephyr:what is zephyr?
        integration/os/zephyr:where can i find more information?
        integration/os/zephyr:zephyr
        
        
        intro/index:faq
        intro/index:introduction
        intro/index:key features
        intro/index:license
        intro/index:release policy
        intro/index:repository layout
        intro/index:requirements
        
        
        
        layouts/index:layouts

        layouts/flex:example
        layouts/flex:flex
        layouts/flex:other features
        layouts/flex:overview
        layouts/flex:simple interface
        layouts/flex:style interface
        layouts/flex:terms
        
        layouts/grid:example
        layouts/grid:grid
        layouts/grid:other features
        layouts/grid:overview
        layouts/grid:simple interface
        layouts/grid:style interface
        layouts/grid:terms


        
        libs/index:3rd party libraries

        libs/barcode:barcode
        libs/barcode:create a barcode
        libs/barcode:example
        libs/barcode:notes
        libs/barcode:usage
        
        libs/bmp:bmp decoder
        libs/bmp:example
        libs/bmp:limitations
        libs/bmp:open a bmp image from file
        
        libs/ffmpeg:add ffmpeg to your project
        libs/ffmpeg:decode image
        libs/ffmpeg:decode video
        libs/ffmpeg:example
        libs/ffmpeg:ffmpeg support
        libs/ffmpeg:install ffmpeg
        libs/ffmpeg:usage
        
        libs/freetype:add freetype to your project
        libs/freetype:example
        libs/freetype:freetype support
        libs/freetype:learn more
        libs/freetype:open a front with freetype
        libs/freetype:usage
        
        libs/fs:file system interfaces
        libs/fs:usage
        
        libs/gif:convert gif files to c array
        libs/gif:example
        libs/gif:gif decoder
        libs/gif:memory requirements
        libs/gif:open a gif image from file and variable
        libs/gif:use gif images from file
        
        libs/libjpeg_turbo:add libjpeg-turbo to your project
        libs/libjpeg_turbo:example
        libs/libjpeg_turbo:install
        libs/libjpeg_turbo:libjpeg-turbo decoder
        libs/libjpeg_turbo:load a jpg image
        libs/libjpeg_turbo:usage
        
        libs/libpng:add libpng to your project
        libs/libpng:example
        libs/libpng:install
        libs/libpng:libpng decoder
        libs/libpng:open a png image from file
        libs/libpng:usage
        
        libs/lodepng:compress png files
        libs/lodepng:example
        libs/lodepng:lodepng decoder
        libs/lodepng:open a png image from file and variable
        
        libs/qrcode:create a qr code
        libs/qrcode:example
        libs/qrcode:notes
        libs/qrcode:qr code
        libs/qrcode:usage
        
        libs/rle:benefits
        libs/rle:generate rle compressed binary images
        libs/rle:rle compress
        libs/rle:theory
        libs/rle:usage
        
        libs/rlottie:build rlottie
        libs/rlottie:controlling animations
        libs/rlottie:esp-idf example
        libs/rlottie:example
        libs/rlottie:getting animations
        libs/rlottie:load a lottie animation from a file
        libs/rlottie:load a lottie animation from raw data
        libs/rlottie:lottie player
        libs/rlottie:usage
        
        libs/tiny_ttf:change font size with tiny_ttf
        libs/tiny_ttf:example
        libs/tiny_ttf:load a font with tiny_ttf from file
        libs/tiny_ttf:open a font with tiny ttf from data array
        libs/tiny_ttf:tiny ttf font engine
        libs/tiny_ttf:usage
        
        libs/tjpgd:converter
        libs/tjpgd:example
        libs/tjpgd:load a jpg image
        libs/tjpgd:overview
        libs/tjpgd:tiny jpeg decompressor (tjpgdec)
        libs/tjpgd:usage
        
        
        
        others/index:others

        others/file_explorer:control file explorer
        others/file_explorer:custom sort
        others/file_explorer:events
        others/file_explorer:example
        others/file_explorer:file explorer
        others/file_explorer:simple file explorer
        others/file_explorer:usage
        
        others/fragment:basic fragment usage
        others/fragment:example
        others/fragment:fragment
        others/fragment:stack navigation example
        others/fragment:usage
        
        others/gridnav:basic grid navigation
        others/gridnav:example
        others/gridnav:focusable objects
        others/gridnav:grid navigation
        others/gridnav:grid navigation on a list
        others/gridnav:nested grid navigations
        others/gridnav:simple navigation on a list widget
        others/gridnav:usage
        
        others/ime_pinyin:custom dictionary
        others/ime_pinyin:example
        others/ime_pinyin:modes
        others/ime_pinyin:pinyin ime
        others/ime_pinyin:usage
        
        others/imgfont:example
        others/imgfont:image font
        others/imgfont:usage
        others/imgfont:use emojis in a text.

        others/monkey:button monkey example
        others/monkey:encoder monkey example
        others/monkey:example
        others/monkey:monkey
        others/monkey:touchpad monkey example
        others/monkey:usage
        
        others/obj_id:obj id
        others/obj_id:usage
        others/obj_property:a step further
        others/obj_property:usage
        others/obj_property:widget property
        
        others/observer:example
        others/observer:observer
        others/observer:overview
        others/observer:subject
        others/observer:subject groups
        others/observer:widget binding
        
        others/snapshot:example
        others/snapshot:simple snapshot example
        others/snapshot:snapshot
        others/snapshot:usage
        
        
        
        overview/index:overview

        overview/animations:animation path
        overview/animations:animations
        overview/animations:create an animation
        overview/animations:delete animations
        overview/animations:examples
        overview/animations:speed vs time
        overview/animations:timeline
        
        overview/color:colors
        overview/color:creating colors
        overview/color:opacity
        
        overview/coord:examples
        overview/coord:layout
        overview/coord:overview
        overview/coord:position
        overview/coord:positions, sizes, and layouts
        overview/coord:size
        overview/coord:transformation
        overview/coord:translation
        overview/coord:using styles
        
        overview/display:displays
        overview/display:features of displays
        overview/display:multiple display support
        overview/display:screens
        
        overview/draw:drawing
        overview/draw:hook drawing
        overview/draw:masking
        overview/draw:mechanism of screen refreshing
        
        overview/event:add events to a widget
        overview/event:event bubbling
        overview/event:event codes
        overview/event:events
        overview/event:examples
        overview/event:fields of lv_event_t
        overview/event:remove event(s) from widgets
        overview/event:sending events
        
        overview/font:add a new font
        overview/font:add a new font engine
        overview/font:add new symbols
        overview/font:built-in fonts
        overview/font:fonts
        overview/font:load a font at run-time
        overview/font:load a font from a memory buffer at run-time
        overview/font:special features
        overview/font:unicode support
        overview/font:use font fallback
        
        overview/fs:adding a driver
        overview/fs:file system
        overview/fs:ready to use drivers
        overview/fs:usage example
        overview/fs:use drives for images
        
        overview/image:add and use images
        overview/image:color formats
        overview/image:image caching
        overview/image:image decoder
        overview/image:images
        overview/image:store images
        
        overview/indev:input devices
        overview/indev:keypad and encoder
        overview/indev:pointers
        
        overview/layer:bottom layers
        overview/layer:change order
        overview/layer:layers
        overview/layer:order of creation
        overview/layer:top and sys layers
        
        overview/new_widget:new widget
        
        overview/obj:attributes
        overview/obj:objects
        overview/obj:parts
        overview/obj:screens
        overview/obj:snapshot
        overview/obj:states
        overview/obj:working mechanisms
        
        overview/profiler:add measurement point
        overview/profiler:custom profiler implementation
        overview/profiler:faq
        overview/profiler:introduction
        overview/profiler:profiler
        overview/profiler:usage
        
        overview/renderers/arm2d:arm-2d gpu
        overview/renderers/arm2d:design considerations
        overview/renderers/arm2d:examples
        overview/renderers/arm2d:how to use
        overview/renderers/index:renderers and gpus
        overview/renderers/pxp:nxp pxp gpu
        overview/renderers/sdl:sdl renderer
        overview/renderers/stm32_dma2d:dma2d gpu
        overview/renderers/sw:software renderer
        overview/renderers/vglite:nxp vglite gpu
        
        overview/scroll:basic example
        overview/scroll:examples
        overview/scroll:features of scrolling
        overview/scroll:overview
        overview/scroll:scroll
        overview/scroll:scroll manually
        overview/scroll:self size
        
        overview/style-props:arc
        overview/style-props:background
        overview/style-props:border
        overview/style-props:image
        overview/style-props:line
        overview/style-props:margin
        overview/style-props:miscellaneous
        overview/style-props:outline
        overview/style-props:padding
        overview/style-props:shadow
        overview/style-props:size and position
        overview/style-props:style properties
        overview/style-props:text
        
        overview/style:add and remove styles to a widget
        overview/style:cascading styles
        overview/style:color filter
        overview/style:examples
        overview/style:inheritance
        overview/style:initialize styles and set/get properties
        overview/style:local styles
        overview/style:opacity, blend modes and transformations
        overview/style:parts
        overview/style:properties
        overview/style:states
        overview/style:styles
        overview/style:themes
        overview/style:transitions
        
        overview/timer:asynchronous calls
        overview/timer:create a timer
        overview/timer:enable and disable
        overview/timer:measure idle time
        overview/timer:pause and resume
        overview/timer:ready and reset
        overview/timer:repeat count
        overview/timer:set parameters
        overview/timer:timer handler resume callback
        overview/timer:timers


        
        porting/index:porting

        porting/display:advanced options
        porting/display:basic setup
        porting/display:display interface
        porting/display:events
        porting/display:further reading
        
        porting/draw:custom gpu
        porting/draw:overview
        porting/draw:references
        
        porting/indev:further reading
        porting/indev:input device interface
        porting/indev:other features
        porting/indev:types of input devices
        
        porting/log:add logs
        porting/log:log level
        porting/log:logging
        porting/log:printing logs
        
        porting/os:interrupts
        porting/os:operating system and interrupts
        porting/os:tasks and threads
        
        porting/project:add lvgl to your project
        porting/project:configuration file
        porting/project:get the library
        porting/project:initialization
        porting/project:set up a project
        
        porting/sleep:sleep management
        
        porting/tick:tick interface
        
        porting/timer_handler:timer handler
        
        
        
        roadmap:ideas
        roadmap:planned in general
        roadmap:roadmap
        roadmap:v9
        
        
        
        widgets/index:widgets

        widgets/animimg:animation image (lv_animimg)
        widgets/animimg:events
        widgets/animimg:example
        widgets/animimg:keys
        widgets/animimg:overview
        widgets/animimg:parts and styles
        widgets/animimg:usage
        
        widgets/arc:arc (lv_arc)
        widgets/arc:events
        widgets/arc:example
        widgets/arc:keys
        widgets/arc:overview
        widgets/arc:parts and styles
        widgets/arc:usage
        
        widgets/bar:bar (lv_bar)
        widgets/bar:events
        widgets/bar:example
        widgets/bar:keys
        widgets/bar:overview
        widgets/bar:parts and styles
        widgets/bar:usage
        
        widgets/button:button (lv_button)
        widgets/button:events
        widgets/button:example
        widgets/button:keys
        widgets/button:overview
        widgets/button:parts and styles
        widgets/button:usage
        
        widgets/buttonmatrix:button matrix (lv_buttonmatrix)
        widgets/buttonmatrix:events
        widgets/buttonmatrix:example
        widgets/buttonmatrix:keys
        widgets/buttonmatrix:overview
        widgets/buttonmatrix:parts and styles
        widgets/buttonmatrix:usage
        
        widgets/calendar:calendar (lv_calendar)
        widgets/calendar:events
        widgets/calendar:example
        widgets/calendar:headers
        widgets/calendar:keys
        widgets/calendar:overview
        widgets/calendar:parts and styles
        widgets/calendar:usage
        
        widgets/canvas:canvas (lv_canvas)
        widgets/canvas:events
        widgets/canvas:example
        widgets/canvas:keys
        widgets/canvas:overview
        widgets/canvas:parts and styles
        widgets/canvas:usage
        
        widgets/chart:chart (lv_chart)
        widgets/chart:events
        widgets/chart:example
        widgets/chart:keys
        widgets/chart:overview
        widgets/chart:parts and styles
        widgets/chart:usage
        
        widgets/checkbox:checkbox (lv_checkbox)
        widgets/checkbox:events
        widgets/checkbox:example
        widgets/checkbox:keys
        widgets/checkbox:overview
        widgets/checkbox:parts and styles
        widgets/checkbox:usage
        
        widgets/dropdown:drop-down list (lv_dropdown)
        widgets/dropdown:events
        widgets/dropdown:example
        widgets/dropdown:keys
        widgets/dropdown:options
        widgets/dropdown:overview
        widgets/dropdown:parts and styles
        widgets/dropdown:usage
        
        widgets/image:events
        widgets/image:example
        widgets/image:image (lv_image)
        widgets/image:keys
        widgets/image:overview
        widgets/image:parts and styles
        widgets/image:usage
        
        widgets/imagebutton:events
        widgets/imagebutton:example
        widgets/imagebutton:image button (lv_imagebutton)
        widgets/imagebutton:keys
        widgets/imagebutton:overview
        widgets/imagebutton:parts and styles
        widgets/imagebutton:usage
        
        widgets/keyboard:events
        widgets/keyboard:example
        widgets/keyboard:keyboard (lv_keyboard)
        widgets/keyboard:keys
        widgets/keyboard:overview
        widgets/keyboard:parts and styles
        widgets/keyboard:usage
        
        widgets/label:events
        widgets/label:example
        widgets/label:keys
        widgets/label:label (lv_label)
        widgets/label:overview
        widgets/label:parts and styles
        widgets/label:usage
        
        widgets/led:events
        widgets/led:example
        widgets/led:keys
        widgets/led:led (lv_led)
        widgets/led:overview
        widgets/led:parts and styles
        widgets/led:usage
        
        widgets/line:events
        widgets/line:example
        widgets/line:keys
        widgets/line:line (lv_line)
        widgets/line:overview
        widgets/line:parts and styles
        widgets/line:usage
        
        widgets/list:events
        widgets/list:example
        widgets/list:keys
        widgets/list:list (lv_list)
        widgets/list:overview
        widgets/list:parts and styles
        widgets/list:usage
        
        widgets/menu:events
        widgets/menu:example
        widgets/menu:keys
        widgets/menu:menu (lv_menu)
        widgets/menu:overview
        widgets/menu:parts and styles
        widgets/menu:usage
        
        widgets/msgbox:events
        widgets/msgbox:example
        widgets/msgbox:keys
        widgets/msgbox:message box (lv_msgbox)
        widgets/msgbox:overview
        widgets/msgbox:parts and styles
        widgets/msgbox:usage
        
        widgets/obj:base object (lv_obj)
        widgets/obj:events
        widgets/obj:example
        widgets/obj:keys
        widgets/obj:overview
        
        widgets/roller:events
        widgets/roller:example
        widgets/roller:keys
        widgets/roller:overview
        widgets/roller:parts and styles
        widgets/roller:roller (lv_roller)
        widgets/roller:usage
        
        widgets/scale:events
        widgets/scale:example
        widgets/scale:keys
        widgets/scale:overview
        widgets/scale:parts and styles
        widgets/scale:scale (lv_scale)
        widgets/scale:usage
        
        widgets/slider:events
        widgets/slider:example
        widgets/slider:keys
        widgets/slider:overview
        widgets/slider:parts and styles
        widgets/slider:slider (lv_slider)
        widgets/slider:usage
        
        widgets/span:events
        widgets/span:example
        widgets/span:keys
        widgets/span:overview
        widgets/span:parts and styles
        widgets/span:span (lv_span)
        widgets/span:usage
        
        widgets/spinbox:events
        widgets/spinbox:example
        widgets/spinbox:keys
        widgets/spinbox:overview
        widgets/spinbox:parts and styles
        widgets/spinbox:spinbox (lv_spinbox)
        
        widgets/spinner:events
        widgets/spinner:example
        widgets/spinner:keys
        widgets/spinner:overview
        widgets/spinner:parts and styles
        widgets/spinner:spinner (lv_spinner)
        widgets/spinner:usage
        
        widgets/switch:events
        widgets/switch:example
        widgets/switch:keys
        widgets/switch:overview
        widgets/switch:parts and styles
        widgets/switch:switch (lv_switch)
        widgets/switch:usage
        
        widgets/table:events
        widgets/table:example
        widgets/table:keys
        widgets/table:overview
        widgets/table:parts and styles
        widgets/table:table (lv_table)
        widgets/table:usage
        
        widgets/tabview:events
        widgets/tabview:example
        widgets/tabview:keys
        widgets/tabview:overview
        widgets/tabview:parts and styles
        widgets/tabview:tabview (lv_tabview)
        widgets/tabview:usage
        
        widgets/textarea:events
        widgets/textarea:example
        widgets/textarea:keys
        widgets/textarea:overview
        widgets/textarea:parts and styles
        widgets/textarea:text area (lv_textarea)
        widgets/textarea:usage
        
        widgets/tileview:events
        widgets/tileview:example
        widgets/tileview:keys
        widgets/tileview:overview
        widgets/tileview:parts and styles
        widgets/tileview:tile view (lv_tileview)
        widgets/tileview:usage
        
        widgets/win:events
        widgets/win:example
        widgets/win:get the parts
        widgets/win:keys
        widgets/win:overview
        widgets/win:parts and styles
        widgets/win:usage
        widgets/win:window (lv_win)
```

</details>

**Comment by PGNetHun** [comment]
Thanks!

I will start the **widgets** and **overview** references, but only next week Monday-Tuesday.

**Comment by kdschlosser** [comment]
It's going to be  pretty pain staking process to scroll down each file one at a time and look for the links that are needed. I know it's a big kick in the ass but I ended up having to remove all of the references you put in. I am really sorry for that. too many thing banging heads with each other. The automatic only works up to a point and then it falls on its face. I am going to have to go in manually and add the reference declarations in. I was only able to have it progress down 2 levels of sections because the automatic portion of it started to have a bit of an issue.

I have also worked out a bunch of the errors already. I am going to do a PR for those and the addition of the reference declarations.

**Comment by PGNetHun** [comment]
Great!
Please mention me in that PR, so I can check that.

**Comment by kdschlosser** [comment]
OK I updated the list of references. This is the absolute last time I am changing them. Everything wasn't in that last list and when I put everything in using the automatic thing I ended up with name collisions again. 

There are no name collisions in this list. I can either add all of the directives now or I can have them added when the docs are compiled. I can add a command line switch that will not compile the docs but it will spit out the directives to stdout so that it can be used to add new references. The naming is pretty simple to understand.

it's the file path without the file extension followed by an additional "/" and then the section title. At the end there is a marker of [0-0]

what this marker means is [section-level] How the sections are counted up is when a level drops. This is done so the names cannot overlap.

The levels are defined as follows.

```
=====
LEVEL 1
=====

######
LEVEL 2
######

********
LEVEL 3
********

LEVEL 4
=====

LEVEL 5
--------

LEVEL 5
********

LEVEL 6
^^^^^

LEVEL 6
~~~~~

LEVEL 7
"""""""""
```

That is not an accident that I repeated some of the levels. This is because they are interchangeable. With sphinx documentation you can mess up the levels. You cannot have an index file that has a level 2 section at the top and then include a file that has a level 1 section at the top. It will pitch a fit if you do that. That's because of how it creates the TOC tree. included files are expected to be a child so the level used for the heading must be lower than the parent. 

The reason why the automatic thing didn't work was because it didn't deal with having more than one section being named the same in the same file. This is allowed in Sphinx so long as it is  not on the same level and in the same section but if you don't use a way to mark them when making the references you end up with a duplicate reference.

**Comment by kdschlosser** [comment]
OK so I updated all of the documentation in #2516 All of the `:ref:` directives have been updated. The old style markdown internal links need to be located and changed. That is all that is left to o for the references portion. There are a ton of other things that need to be fixed and most of those need to get corrected in the LVGL header files. There are a lot of corrections I made in that PR as well as I came across the problems.

**Pull request merged**
