### PR TITLE
fix(template) prototype error

### PR DESCRIPTION
**Pull request by Hotakus**

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@Hotakus can you squash the change into one patch?

**Comment by Hotakus** [comment]
> @Hotakus can you squash the change into one patch?

Sorry, I had tested, I can't do it, it was commited already , maybe the "squash and merge" option can do it

**Comment by kisvegabor** [comment]
> Sorry, I had tested, I can't do it, it was commited already , maybe the "squash and merge" option can do it

I can confirm it, I usually use this option. It even allows to edit the final commit message.

image

**Comment by xiaoxiang781216** [comment]
Ok.

**Pull request merged**
