### PR TITLE
fix(mem): ALIGN_MASK should equal 0x3 on 32bit platform

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

minor fix

### Checkpoints
- [X] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by embeddedt** [comment]
According to the `malloc` [manpage](https://man7.org/linux/man-pages/man3/realloc.3.html):

> The `malloc()` and `calloc()` functions return a pointer to the allocated memory, which is suitably aligned for any built-in type.

Since `long long` on most/all platforms is a 64-bit integer, I believe this means that `malloc` has to always return a pointer with 8-byte alignment.

I don't know if LVGL's allocator has to follow `malloc` semantics exactly, but it is convenient for compatibility.

**Comment by xiaoxiang781216** [comment]
> According to the `malloc` [manpage](https://man7.org/linux/man-pages/man3/realloc.3.html):
> 
> > The `malloc()` and `calloc()` functions return a pointer to the allocated memory, which is suitably aligned for any built-in type.
> 
> Since `long long` on most/all platforms is a 64-bit integer, I believe this means that `malloc` has to always return a pointer with 8-byte alignment.
> 
> I don't know if LVGL's allocator has to follow `malloc` semantics exactly, but it is convenient for compatibility.

The alignment of TLSF is 4bytes on 32bit platform:
https://github.com/lvgl/lvgl/blob/master/src/misc/lv_tlsf.c#L232-L238
Since lvgl allocator is built on top of TLSF, even we keep ALIGN_MASK as 0x7, the allocated memory still align on 4bytes.

**Comment by embeddedt** [comment]
Ah, okay. In that case, I agree with this change.

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
I think it was just a typo. 
Thank for the fix.

**Pull request merged**
