### PR TITLE
Update Kconfig to LVGL V8

### LINKED ISSUE #2163: LVGL v8 Update Kconfig
### Introduce the problem
Kconfig haven't been updated with the added/removed configuration options of LVGL v8

### Examples and cases
This is relevant for Kconfig based toolchains

### Suggested solution
Get a list of added and removed options to update the Kconfig file

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Updates the Kconfig file with LVGL v8 configuration options. Fixes #2163 

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi Carlos,

I've update Kconfig for v8 however I couldn't test it. :slightly_frowning_face: 

I think the menu gorups and options are fine but surely there are some syntax errors.

**Comment by xiaoxiang781216** [comment]
@kisvegabor could you remove the unrelated patch from PR to simplify the review?

**Comment by C47D** [comment]
It isn't complete yet, I had been having very busy weeks at work and couldn't work more on this.

**Comment by C47D** [comment]
@kisvegabor @xiaoxiang781216 I've opened #2170 to keep the Kconfig files updates only there, we can close this request.

**Comment by xiaoxiang781216** [comment]
Ok, let close this PR, now.

**Pull request closed without merging**
