### PR TITLE
add sin difference precision to lv_math and change integer operation to float

### PR DESCRIPTION
**Pull request by Leo2442926161**

### CODE REVIEW

**Comment by turoksama** [comment]
It is not a good idea to use float with low performance mcu.

**Comment by embeddedt** [comment]
@Leo2442926161 Floating-point operations are not permitted in core LittlevGL code.

**Review by embeddedt — CHANGES_REQUESTED** [review]
Floating-point shouldn't be used in core LittlevGL code.

**Comment by kisvegabor** [comment]
Besides avoiding floats we can reduce the memory usage by storing only one-quarter of the sin wave. (as in the original implementation)

**Comment by Leo2442926161** [comment]
@kisvegabor @embeddedt @turoksama  I think The result is not perfect Even I use float operation,   that is a test a program for @kisvegabor , you can see the result by difference precision.

I can change the float table to integer If your are think the result is good

**Comment by kisvegabor** [comment]
@Leo2442926161 I see. 
I suggest making the sine tables ready with integer values (having more precision is a good idea) and I will try my best to make the most out of the `lmeter`. After that, we can add the `offset` attribute too.

**Comment by Leo2442926161** [comment]
@kisvegabor please view the new PR

**Pull request closed without merging**
