### PR TITLE
[lv_indev] Handle click on disabled objects

### LINKED ISSUE #3860: Click on disabled lv object triggers a click event on the lv object behind
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [ ] Update lvgl to the latest version (used: 8.3.3 - not master)
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

Hi, 

currently I am working on a little lvgl-based UI project. (I have to really praise lvgl for being a great UI framework, thanks so much!) In my project I want to use disabled buttons. Unfortunately, I have experienced a somewhat quirky behavior: clicks on disabled lv objects will travel through them and cause a click event in the object below.

What I did specifically is:
- Create a lv_obj screen
- Make the lv_obj clickable and implement an event handler for the screen's click event
- Add a child button to the screen
- Implement an event handler for the child's click event
- Add state LV_STATE_DISABLED to the button
- Run the simulator
- Click the button
- Event handler of the screen is executed

### To Reproduce

I have updated the button counter example to illustrate the behavior I am observing:
```python
##### startup script #####

#!/opt/bin/lv_micropython -i

import lvgl as lv
import display_driver

##### main script #####

class CounterBtn():
    def __init__(self):
        self.cnt = 0
        self.cnt2 = 0
        #
        # Create a button with a label and react on click event.
        #

        bg_obj = lv.obj(lv.scr_act())
        bg_obj.add_event_cb(self.bg_event_cb, lv.EVENT.ALL, None)  # Assign a callback to the button
        bg_lbl = lv.label(bg_obj)                                    # Add a label to the button

        btn = lv.btn(bg_obj)                               # Add a button the current screen
        btn.set_pos(10, 10)                                      # Set its position
        btn.set_size(120, 50)                                    # Set its size
        btn.align(lv.ALIGN.CENTER,0,0)
        btn.add_event_cb(self.btn_event_cb, lv.EVENT.ALL, None)  # Assign a callback to the button

        label = lv.label(btn)                                    # Add a label to the button
        label.set_text("Button")                                 # Set the labels text
        label.center()

        btn.add_state(lv.STATE.DISABLED)
        btn.has_state(lv.STATE.DISABLED)
        self.btn = btn

    def btn_event_cb(self,evt):
        code = evt.get_code()
        btn = evt.get_target()
        if code == lv.EVENT.CLICKED:
            self.cnt += 1

        # Get the first child of the button which is the label and change its text
        label = btn.get_child(0)
        label.set_text("Clicked Button: " + str(self.cnt))

    def bg_event_cb(self,evt):
        code = evt.get_code()
        btn = evt.get_target()
        if code == lv.EVENT.CLICKED:
            self.cnt2 += 1

        # Get the first child of the button which is the label and change its text
        label = btn.get_child(0)
        label.set_text("Clicked BG: " + str(self.cnt2))


counterBtn = CounterBtn()
```

I debugged my application and found that the problems stems from the "object hit testing":
- `lv_indev_search_obj(lv_disp_get_layer_top(disp), &proc->types.pointer.act_point);` (I used objects on the top layer)
  -  https://github.com/lvgl/lvgl/blob/v8.3.3/src/core/lv_indev.c#L830
- `bool hit_test_ok = lv_obj_hit_test(obj, &p_trans);`
  - https://github.com/lvgl/lvgl/blob/v8.3.3/src/core/lv_indev.c#L310
- `if(lv_obj_has_state(obj, LV_STATE_DISABLED)) return false;`
  - https://github.com/lvgl/lvgl/blob/v8.3.3/src/core/lv_obj_pos.c#L956

### Expected behavior

The high-level behavior I am expecting is that clicking a disabled button dismisses the click event and does not the background.
On the implementation level I expect the lv_indev_search_obj and the lv_obj_hit_test function to regard disabled objects and return without sending a click event.

### Screenshots or video

n/a

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Fixes #3860 

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by C47D** [comment]
My test procedure was (using lv_port_pc_eclipse):

1. Set the `LV_STATE_DISABLED` state on the `btn` and click over it, this should not execute the `bg_obj` event callback. Works as expected, `Cnt2` variable is not incremented on button clicks.
[Screencast from 11-09-23 18:51:52.webm](https://github.com/lvgl/lvgl/assets/11037705/5de15bce-408f-4b54-bdb1-f249b224e488)

2. Do not set `LV_STATE_DISABLED` state on the `btn`, click on the button, this should execute the `btn` event callback but not the `bg_obj` one. Works as expected, `Cnt` variable gets incremented each click on the button.
[Screencast from 11-09-23 18:50:51.webm](https://github.com/lvgl/lvgl/assets/11037705/87cfd4a6-9df8-4592-afc8-d91ccd7b6da2)

Here's the code in case you want to try it out.

```c
unsigned char cnt = 0;
unsigned char cnt2 = 0;
lv_indev_t * mouse = NULL;

lv_obj_t * bg_obj;
lv_obj_t * btn;
lv_obj_t * bg_lbl;
lv_obj_t * label;
lv_obj_t * screen;

void bg_event_cb(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t * btn_tmp = lv_event_get_target(e);

	if (LV_EVENT_CLICKED == code) {
		cnt2 += 1U;
	}

	lv_obj_t * label_tmp = lv_obj_get_child(btn_tmp, 0);
	LV_LOG_USER("Cnt2: %d", cnt2);
}

void btn_event_cb(lv_event_t * e)
{
	lv_event_code_t code = lv_event_get_code(e);
	lv_obj_t * btn_tmp = lv_event_get_target(e);

	if (LV_EVENT_CLICKED == code) {
		cnt += 1U;
	}

	lv_obj_t * label_tmp = lv_obj_get_child(btn_tmp, 0);
	LV_LOG_USER("Cnt: %d", cnt);
}

int main()
{
  screen = lv_scr_act();
  bg_obj = lv_obj_create(screen);
  lv_obj_add_event(bg_obj, bg_event_cb, LV_EVENT_ALL, NULL);
  bg_lbl = lv_label_create(bg_obj);

  btn = lv_btn_create(bg_obj);

  lv_obj_set_pos(btn, 10, 10);
  lv_obj_set_size(btn, 120, 50);
  lv_obj_align(btn, LV_ALIGN_CENTER, 0, 0);
  lv_obj_add_event(btn, btn_event_cb, LV_EVENT_ALL, NULL);

  label = lv_label_create(btn);
  lv_label_set_text(label, "Button");
  lv_obj_center(label);

  lv_obj_add_state(btn, LV_STATE_DISABLED); // Comment this line to remove the LV_STATE_DISABLED state

  /* ... */
}

```

**Comment by kisvegabor** [comment]
What if we remove `if(lv_obj_has_state(obj, LV_STATE_DISABLED)) return false;` from `lv_obj_hit_test()`. This way the disabled  will be found and we just need add the `if(!disabled)` statements before sending the CLICK related events.

**Comment by C47D** [comment]
> What if we remove `if(lv_obj_has_state(obj, LV_STATE_DISABLED)) return false;` from `lv_obj_hit_test()`. This way the disabled will be found and we just need add the `if(!disabled)` statements before sending the CLICK related events.

Just tested it and it works as the other suggestion, should we avoid sending only the `LV_EVENT_CLICKED` or also `LV_EVENT_SHORT_CLICKED`?

**Comment by C47D** [comment]
@kisvegabor If possible help me check this change with button and encoder indev, I have no hw available at the moment.

**Comment by kisvegabor** [comment]
Sorry I forgot to answer it:
> Just tested it and it works as the other suggestion, should we avoid sending only the LV_EVENT_CLICKED or also LV_EVENT_SHORT_CLICKED?

We should discard all touch related events, including CLICKED, SHORT_CLICKED, RELEASED, PRESSED, LONG_PRESSED, etc.

> Can you help me check this change with button and encoder indev, I have no hw available at the moment.

Sure, I can test it on my notebook with SDL keyboard and mouse wheel drivers.

**Comment by C47D** [comment]
Hi @kisvegabor, please let me know if inhibiting all those events is enough

**Comment by kisvegabor** [comment]
Looks good, thank you! We can improve it later if something is still missing.

**Comment by C47D** [comment]
Thanks, I've set the PR as ready to be merged!

**Comment by kisvegabor** [comment]
Merged, thank you!

**Pull request merged**
