### PR TITLE
feat(textarea): add a read-only mode for textarea

### PR DESCRIPTION
**Pull request by hellototoro**
### Description of the feature or fix
feat(textarea): add a read-only mode for textarea

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Can't we do the same with `lv_obj_add_state(ta, LV_STATE_DISABLED)`?

**Comment by hellototoro** [comment]
Hi,
If using lv_obj_add_state to replace that, the text area object will not respond to the key events. And the object's color is grey.
Add a read-only mode for the text area not only to display chars normally but also to respond to a key event.
For example, I just want to display a text file, but I don't want to edit it. And the text area object can receive a key event such as ESC.
lv_obj_add_state
read-only mode

**Comment by kisvegabor** [comment]
I see. 

> For example, I just want to display a text file, but I don't want to edit it. And the text area object can receive a key event such as ESC.

In this case why don't you create a simple `lv_label` on an `lv_obj` parent?

**Comment by hellototoro** [comment]
Well, you are right. But should don't the text area has a read-only mode? We can switch between read-write and read-only mode. I think this is useful.

**Comment by kisvegabor** [comment]
I still can't see for what the read-only a text area can be used for where an `lv_label` can't be used. Can you mention some examples?

**Comment by hellototoro** [comment]
Ok, maybe that is redundant.

**Pull request closed without merging**
