### PR TITLE
[v6.0] add an option to define hard coded resolution

### PR DESCRIPTION
**Pull request by amirgon**

### CODE REVIEW

**Comment by embeddedt** [comment]
More functionality is needed than this I think. Why is this necessary?

**Comment by amirgon** [comment]
@embeddedt 
I'm working on fixes and adjustments for the ESP32 drivers on `lv_micropython`  for v6.0 (https://github.com/littlevgl/lv_binding_micropython/issues/28).
Currently the driver still assumes resolution is fixed. I'll fix this in the future, but for the meantime I would like to be able to define resolution hard coded, so the existing code could work.

> More functionality is needed than this I think. Why is this necessary?

The project builds fine for me, after defining resolution from the outside.  
What else is needed?

**Comment by kisvegabor** [comment]
@amirgon 
So do you need the resolution as a constant number?

**Comment by amirgon** [comment]
> So do you need the resolution as a constant number?

@kisvegabor I would like to keep this option open. 
I need this only temporarily, to allow existing display drivers work on v6.0 until I change them to support dynamic resolution.  
On the longer term I would like to allow building lv_micropython once, and decide on runtime which driver to load and what is the screen resolution (as we discussed in the past).

**Comment by kisvegabor** [comment]
> I would like to keep this option open.
I need this only temporarily, to allow existing display drivers work on v6.0 until I change them to support dynamic resolution.

As I see it doesn't harm anything, so why not. @embeddedt?

**Comment by embeddedt** [comment]
@amirgon Are you still setting the [resolution inside the `lv_disp_drv_t` structure](https://github.com/littlevgl/lvgl/blob/fda41d62a1b9a31a5eb62d29b33ece45391cfff3/src/lv_hal/lv_hal_disp.h#L56-L64)? If so, this should work fine.

**Comment by amirgon** [comment]
> @amirgon Are you still setting the [resolution inside the `lv_disp_drv_t` structure](https://github.com/littlevgl/lvgl/blob/fda41d62a1b9a31a5eb62d29b33ece45391cfff3/src/lv_hal/lv_hal_disp.h#L56-L64)? If so, this should work fine.

@embeddedt Yes, this is actually [done in Python code](https://github.com/littlevgl/lv_binding_micropython/blob/9baf96be8a2d58bf6f54b2c50807643e30a04fb2/examples/example1.py#L19-L20), not in the display driver code.

**Comment by embeddedt** [comment]
@amirgon Great, I've merged this!

**Pull request merged**
