### PR TITLE
fix(thorvg): fix windows build break

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

In response to #5946

Error when building thorvg on Windows. Defined functions were being marked with `__declspec(dllimport)`.

https://github.com/lvgl/lvgl/blob/fea8a97f5f6f415236d23c02c19af844475e044a/src/libs/thorvg/thorvg_capi.h#L35-L40

This fix tries to leave the thorvg header untouched except for defining `TVG_BUILD` at the top so it's easier to update thorvg from the upstream. https://github.com/lvgl/lvgl/pull/4691#discussion_r1375604134

Would have been found by the eventual Windows CI #5904

Also remove duplicate guard.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by C47D — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
Having a Windows build test would be really great..  (https://github.com/lvgl/lvgl/issues/5904)

@liamHowatt do you feel the power to add a Windows build test to the CI?

**Comment by liamHowatt** [comment]
> @liamHowatt do you feel the power to add a Windows build test to the CI?

After some brief exploration I think I have the power to do it. It was easy enough to use the `windows-latest` runner. It comes with MinGW GCC and the chocolatey package manager and many more things we can use to make it happen.

Here's everything that comes with the windows runner: https://github.com/actions/runner-images/blob/win22/20240322.1/images/windows/Windows2022-Readme.md#msys2

My branch is https://github.com/liamHowatt/lvgl/tree/feat/windows-ci

**Comment by liamHowatt** [comment]
Oh, hang on, I'll verify MinGW GCC treats everything the same as MSVC. I know that MinGW GCC defines `_WIN32`. But I'll need to see about #5873. No matter either way. Visual Studio is also installed in the runner.

**Comment by kisvegabor** [comment]
I think MSVC is the real issue and focus on that.

**Review by XuNeo — APPROVED** [review]

**Comment by liamHowatt** [comment]
See [my comment in the Windows CI build issue](https://github.com/lvgl/lvgl/issues/5904#issuecomment-2034706710) and the [PR that builds on Windows with GCC for now](https://github.com/lvgl/lvgl/pull/6015).

**Pull request merged**
