### PR TITLE
fix(arc): Handle click outside background angle range

### LINKED ISSUE #4576: Arc : clickable area outside of the draw
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

With a partial arc (120°), when I click outside of these 120° but still in the ring, it changes the value.
which can be a big issue when it controls volume for example and it put it at 100% :(

### To Reproduce

```
// Volume
  lv_obj_t *volume_label = lv_label_create(lv_scr_act());
  lv_label_set_text(volume_label, "Value");

  /*Create Volume Arc*/
  volume_arc = lv_arc_create(lv_scr_act());
  lv_obj_set_size(volume_arc, 225, 225);
  // lv_arc_set_rotation(volume_arc, 135);
  lv_arc_set_rotation(volume_arc, 210);
  lv_obj_set_style_arc_width(volume_arc, 5, LV_PART_MAIN); // Changes background arc width
  lv_obj_set_style_arc_width(volume_arc, 6, LV_PART_INDICATOR); // Changes set part width 
  // lv_arc_set_bg_angles(volume_arc, 0, 270);
  lv_arc_set_bg_angles(volume_arc, 0, 120);
  lv_arc_set_value(volume_arc, 10);
  lv_obj_remove_style(volume_arc, NULL, LV_PART_KNOB);   /*Be sure the knob is not displayed*/
  lv_obj_center(volume_arc);
  lv_obj_add_event_cb(volume_arc, value_changed_event_cb, LV_EVENT_VALUE_CHANGED, volume_label);
```
and
```
static void value_changed_event_cb(lv_event_t * e)
{
    lv_obj_t * arc = lv_event_get_target(e);
    lv_obj_t * label = (lv_obj_t *)lv_event_get_user_data(e);

    lv_label_set_text_fmt(label, "%d%%", lv_arc_get_value(arc));
}
```

### Expected behavior

I would expect it change only when I click on the drown part of the arc, not on the full ring
### Screenshots or video

None

thanks in advance for your help

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Fixes #4576 

### Checkpoints
- [ ] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by C47D** [comment]
I see this other not expected behavior with the current implementation, when `value` is close to the `bg_angle_end` and we click near the `bg_angle_start` the value is incremented, I was expecting to see it decrementing (moving towards `bg_angle_start`)

[Screencast from 23-09-23 17:03:05.webm](https://github.com/lvgl/lvgl/assets/11037705/a7e9fb13-b84c-43ef-838f-4f69b1b1eb9f)

What do you think @kisvegabor

**Comment by C47D** [comment]
Another one, notice how after `value` reaches `bg_angle_end`/ max value it doesn't get updated anymore,

[Screencast from 23-09-23 17:23:31.webm](https://github.com/lvgl/lvgl/assets/11037705/0353ea69-1fe1-42f4-bf6b-fbd394477f9d)

**Comment by C47D** [comment]
@kisvegabor The first implementation of the original issue is done, let me know if you want to check the other two issues (see previous comments and videos)

**Comment by kisvegabor** [comment]
Thank you Carlos. It would be great if you could take a look at the other 2 issues too. 

Adding unit test for these issues would be amazing as well to be sure we won't have them later again during refactoring.

**Comment by C47D** [comment]
Can we solve those issues in another PR?

**Comment by kisvegabor** [comment]
We can use this one for all.

**Comment by kisvegabor** [comment]
Hi,

It doesn't seem to  work for me:
```
    lv_obj_t * arc = lv_arc_create(lv_scr_act());
    lv_obj_set_size(arc, 350, 350);
    lv_arc_set_rotation(arc, 135);
    lv_arc_set_value(arc, 10);
    lv_obj_center(arc);
```
arc

Even if I click far from the ends, it start to move toward  `bg_end`.

**Comment by C47D** [comment]
Hi,
You will need to click in the 'invisible' part of the background arc. I was able to reproduce the issue of clicking near the start angle and value going to the end angle, I'll work on it later today.

**Comment by C47D** [comment]
> Hi,
> 
> It doesn't seem to work for me:
> 
> ```
>     lv_obj_t * arc = lv_arc_create(lv_scr_act());
>     lv_obj_set_size(arc, 350, 350);
>     lv_arc_set_rotation(arc, 135);
>     lv_arc_set_value(arc, 10);
>     lv_obj_center(arc);
> ```
> 
> arc [ arc ](https://user-images.githubusercontent.com/7599318/270640519-bba0cecd-45ae-4cf8-b662-32e59beeb9b5.gif) [ ](https://user-images.githubusercontent.com/7599318/270640519-bba0cecd-45ae-4cf8-b662-32e59beeb9b5.gif)
> 
> Even if I click far from the ends, it start to move toward `bg_end`.

The issue is that by default the background end angle is bigger than background start angle, and the fix relies in the opposite.

**Comment by C47D** [comment]
This is the current behavior with the fixes, what do you think @kisvegabor ?

[Screencast from 27-09-23 22:00:29.webm](https://github.com/lvgl/lvgl/assets/11037705/5e5c8d8c-a32d-4a0f-9312-de0cdae3f489)

**Comment by kisvegabor** [comment]
It looks good, I just found a minor issue. When I'm pressing the arc on the end, and slide to the start (or the opposite), sometimes it jumps immediately.

arc1

**Comment by C47D** [comment]
> It looks good, I just found a minor issue. When I'm pressing the arc on the end, and slide to the start (or the opposite), sometimes it jumps immediately.
> 
> arc1 [ arc1 ](https://user-images.githubusercontent.com/7599318/271206493-9055004f-1e3b-4530-a480-e722b5098640.gif) [ ](https://user-images.githubusercontent.com/7599318/271206493-9055004f-1e3b-4530-a480-e722b5098640.gif)

I think the arc prevents jumps when the angle delta is bigger than 280, maybe this is smaller? I will check the delta when that happened.

**Comment by kisvegabor** [comment]
Thanks!

> Are you releasing the mouse when doing the movement or is it kept clicked?

Nope, I was pressing in the whole gif.

**Comment by C47D** [comment]
Thanks for the additional info @kisvegabor , I'm noticing it happens when `min_close` changes from 0 to 1 and the delta angle is bigger than 280 and the click was outside, see the bottom part of the screenshot. The same happens when `min_close` changes from 1 to 0.

image

**Comment by C47D** [comment]
@kisvegabor I think it's fixed now, what do you think? In the first half of the video I did multiple clicks, on the second half I didn't released the click when moving from start to end angles

[Screencast from 02-10-23 21:03:56.webm](https://github.com/lvgl/lvgl/assets/11037705/b10965a0-98b5-4c03-b621-931f3391574a)

**Comment by kisvegabor** [comment]
Looks very nice! Could you add a unit test for that? Just the very same thing as you did in the video.

**Comment by C47D** [comment]
> Looks very nice! Could you add a unit test for that? Just the very same thing as you did in the video.

Sure

**Comment by C47D** [comment]
Hi, I've noticed an issue when dealing with small arcs, while trying to create the test case for this changes. Still investigating the issue. :smile

**Comment by kisvegabor** [comment]
It's confirmed again that writing tests is useful :slightly_smiling_face:

**Comment by kisvegabor** [comment]
The failing CI was my fault and it's already fixed in `master`.

**Comment by kisvegabor** [comment]
Thank you Carlos! It's really nice that this issues was finally fixed. :+1:

**Comment by spilz87** [comment]
hello

I tried the fix, but it seems it doesn't work for me :(
It still reacts when I click on the invisible part of the arc.

**Comment by kisvegabor** [comment]
Hey,

Could you send a video about the issue?

**Comment by spilz87** [comment]
My mistake, I updated the library on older version.
sorry for that

**Comment by kisvegabor** [comment]
Huh, great! :slightly_smiling_face:

**Pull request merged**
