### PR TITLE
refactor(font): refactor font glyph data acquire method

### PR DESCRIPTION
**Pull request by W-Mai**
### Description of the feature or fix

Refactor font glyph data acquire method

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Without seeing clear benefits, I think it's the same case that I have described [here](https://github.com/lvgl/lvgl/pull/5888#issuecomment-2002007406).

**Comment by W-Mai** [comment]
> Without seeing clear benefits, I think it's the same case that I have described [here](https://github.com/lvgl/lvgl/pull/5888#issuecomment-2002007406).

This modification will not affect the generation of font code. It will not cause code blocking elsewhere.

The main improvement point of this patch is that the `glyph index` needed to call the relevant API again. In fact, when the first time to `get glyph dsc`, the `glyph index` has been obtained, so the next step is to `get bitmap`. At that time, it can use the previously obtained `glyph index`, which reduces the acquisition of `glyph index` and reduces the consumption of time. So there is a gain.

At the same time, the callback function of the previous `get bitmap` essentially does not need the unicode param. This change will also optimize the code to make the code clearer.

**Comment by kisvegabor** [comment]
Ah, I see it now. Very nice! :slightly_smiling_face: 
Have you measured the performance change?

**Review by kisvegabor — APPROVED** [review]

**Comment by W-Mai** [comment]
> Ah, I see it now. Very nice! 🙂 Have you measured the performance change?

Aha, not yet. I want to do it, but I don't have much time to deal with it. Theoretically, time is optimized. Maybe we can ask the community for help to test this performance problem, and you can refer to what I did in this issue. #5901 

I think we need to compare the performance differences of default fonts, tinyttf, image fonts, and freetype fonts.

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
