### PR TITLE
Long txt wrapping refactor

### PR DESCRIPTION
**Pull request by BrianPugh**
Refactor of the long word wrapping system to be more maintainable. Please test, but i believe everything is working as intended.

Should probably squash the commits on merge.

### CODE REVIEW

**Comment by embeddedt** [comment]
@BrianPugh FYI `lv_conf_checker.h` is autogenerated (and mentions it at the top) so you don't need to update that. But it's fine for this PR.

**Comment by BrianPugh** [comment]
@embeddedt oops, thanks! noted

**Review by embeddedt — APPROVED** [review]
@kisvegabor We should squash merge this one.

**Comment by kisvegabor** [comment]
Thank you @BrianPugh, much readable now.

I tried the `demo` example but there is an unexpected line break in the "Got it" text.
image

Could you have a look at it?

**Comment by BrianPugh** [comment]
Investigating now. For some reason, this `get_line` is being called twice, once with the correct width (364), and once with the incorrect width (39). This is using some additional print statements and default lv_conf resolution (480,320).

```
(280): FULL_TEXT (len 6) "Got it"
Original max_width 364
Word is 3 long: "Got" and 29 px wide. Remaining width: 335
Word is 1 long: " " and 4 px wide. Remaining width: 331
Word is 2 long: "it" and 9 px wide. Remaining width: 322
returning null ptr


(280): FULL_TEXT (len 6) "Got it"
Original max_width 39
Word is 3 long: "Got" and 29 px wide. Remaining width: 10
Word is 1 long: " " and 4 px wide. Remaining width: 6
break index 0. cur_w: 9, max_width: 6
Word is 0 long: "" and 0 px wide. Remaining width: 6


(280): FULL_TEXT (len 2) "it"
Original max_width 39
Word is 2 long: "it" and 9 px wide. Remaining width: 30
returning null ptr
```

**Comment by BrianPugh** [comment]
so what i think is happening is that  (most probably) my new functions are slightly incorrectly calculating word width when compared to some other function that's used for the tight style layout. In the "Got it" example, I compute it to be 3 pixels wider than it should be.

**Comment by BrianPugh** [comment]
@kisvegabor should be fixed now. Problem was how I was handling the width computation of break characters.

**Comment by kisvegabor** [comment]
Working well now! Thank you!

**Comment by BrianPugh** [comment]
@kisvegabor I just noticed that there seems to be an off-by-one error when checking number of characters on the subsequent line (breaking at 4 instead of 3 if 3 is specified); I think I fixed it on my branch, but I want to do more testing this evening. After thats done, I'll make another PR.

**Comment by embeddedt** [comment]
I suggest that we hold off on merging this feature into 6.0 and postpone to 6.1. It seems that it is not stable enough with the new font system yet, and we are supposed to be releasing a stable version this week.

**Comment by BrianPugh** [comment]
I feel like with the change in #1119 that this code is stable, but text transversal is, of course, crucial to the library. I can't find any more failures with the new code, but it is new code, so it hasn't been as well tested as the old code.

**Comment by kisvegabor** [comment]
I'm also afraid a little bit if it breaks something.

I'll create the `dev-6.1` branch immediately after v6.0 is released and we can add this update there.
Fixes of v6.0 will be merged to `dev-6.1` too so it should be safe to use it.

Do you agree?

**Comment by embeddedt** [comment]
> Do you agree?

Sounds good. Should I revert the merge then?

**Comment by kisvegabor** [comment]
Yes, please.

**Comment by embeddedt** [comment]
@kisvegabor Reverted. I can't compile test it for a few hours but hopefully it still compiles. :wink:

**Comment by kisvegabor** [comment]
@embeddedt I've tested it and it works. Thank you!

**Pull request merged**
