### PR TITLE
fix(freetype): fix build break when disable LV_USE_FS_MEMFS

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

```bash
lvgl/src/libs/freetype/lv_freetype.c: In function ‘lv_freetype_req_face_id’:
lvgl/src/libs/freetype/lv_freetype.c:363:8: error: ‘LV_FS_MEMFS_LETTER’ undeclared (first use in this function); did you mean ‘LV_FS_POSIX_LETTER’?
  363 |     if(LV_FS_MEMFS_LETTER == pathname[0]) {
      |        ^~~~~~~~~~~~~~~~~~
      |        LV_FS_POSIX_LETTER
```

cc @hpfaz 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Can we add a test for that? The [Ubuntu font](https://github.com/lvgl/lvgl/blob/master/examples/libs/tiny_ttf/ubuntu_font.c) can be used.

**Review by C47D — APPROVED** [review]

**Comment by FASTSHIFT** [comment]
> Can we add a test for that? The [Ubuntu font](https://github.com/lvgl/lvgl/blob/master/examples/libs/tiny_ttf/ubuntu_font.c) can be used.

I noticed that freetype installed using lib mode may not work with memfs because freetype will use C stdio directly to access files directly and will not use lv_fs.
If `LV_FREETYPE_USE_LVGL_PORT` is enabled, since lvgl and freetype will call each other's functions, we need to download the freetype source code and compile it together with the lvgl source code, which may be difficult in CI deployment.

I recommend merging this PR first to resolve compilation error issues.

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
Okkay!

**Comment by hpfaz** [comment]
@FASTSHIFT sorry for the late reply and thank you for the fix. I'll make sure to perform more thorough tests next time.

**Pull request merged**
