### PR TITLE
Add CodeQL Workflow for Code Security Analysis

### PR DESCRIPTION
**Pull request by b4yuan**
# Summary

This pull request introduces a CodeQL workflow to enhance the security analysis of this repository.

# What is CodeQL

CodeQL is a static analysis tool that helps identify and mitigate security vulnerabilities. It is primarily intra-function but does provide some support for inter-function analysis. By integrating CodeQL into a GitHub Actions workflow, it can proactively identify and address potential issues before they become security threats.

For more information on CodeQL and how to interpret its results, refer to the GitHub documentation and the CodeQL documentation (https://codeql.github.com/ and https://codeql.github.com/docs/).

# What this PR does

We added a new CodeQL workflow file (.github/workflows/codeql.yml) that
- Runs on every pull request (functionality to run on every push to main branches is included as a comment for convenience).
- Runs daily.
- Excludes queries with a high false positive rate or low-severity findings.
- Does not display results for git submodules, focusing only on our own codebase.

## Validation

To validate the functionality of this workflow, we have run several test scans on the codebase and reviewed the results. The workflow successfully compiles the project, identifies issues, and provides actionable insights while reducing noise by excluding certain queries and third-party code.

## Using the workflow results

If this pull request is merged, the CodeQL workflow will be automatically run on every push to the main branch and on every pull request to the main branch. To view the results of these code scans, follow these steps:
1. Under the repository name, click on the Security tab.
2. In the left sidebar, click Code scanning alerts.

# Is this a good idea?

We are researchers at Purdue University in the USA. We are studying the potential benefits and costs of using CodeQL on open-source repositories of embedded software.

We wrote up a report of our findings so far. The TL;DR is “CodeQL outperforms the other freely-available static analysis tools, with fairly low false positive rates and lots of real defects”. You can read about the report here: https://arxiv.org/abs/2310.00205

# Review of engineering hazards

License: see the license at https://github.com/github/codeql-cli-binaries/blob/main/LICENSE.md: 

```
Here's what you may also do with the Software, but only with an Open Source Codebase and subject to the License Restrictions provisions below:

Perform analysis on the Open Source Codebase.

If the Open Source Codebase is hosted and maintained on GitHub.com, generate CodeQL databases for or during automated analysis, CI, or CD.
```

False positives: We find that around 20% of errors are false positives, but that these FPs are polarized and only a few rules contribute to most FPs. We find that the top rules contributing to FPs are: cpp/uninitialized-local, cpp/missing-check-scanf, cpp/suspicious-pointer-scaling, cpp/unbounded-write, cpp/constant-comparison, and cpp/inconsistent-null-check. Adding a filter to filter out certain rules that contribute to a high FP rate can be done simply in the workflow file.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thank you much for opening this PR. I've checked the [result of GitHub CI](https://github.com/lvgl/lvgl/actions/runs/6674643373/job/18141714590?pr=4721) but it seems there is an error in  `.github/workflows/codeql-buildscript.sh`.

**Comment by b4yuan** [comment]
@kisvegabor Thanks for the catch. Looks like there have been some updates since we last built it. I've gone ahead and updated the built script, and CodeQL is working fine now. (The workflow fails due to CodeQL finding an error)

Let me know your thoughts!

**Comment by kisvegabor** [comment]
Thank you for the update! 

I've checked the result and it seems pretty useful! However the artifact was a JSON file with 65,000 lines which is quite hard to read and use. It seems to me the interesting part for us is only the `"results"` array, which is only 5,000 lines.

So I wonder if it would be possible to extract the results into more concise, human readable way? For example:
```json
{
    "results": [
        {
            "file": "src/misc/lv_event.c",
            "issues": [
                {
                    "region": "line 54, column 5-19",
                    "message": "A stack address which arrived via a [parameter](1) may be assigned to a non-local variable."
                },
                {
                    "region": "line 64, column 15-27",
                    "message": "A stack address which arrived via a [parameter](1) may be assigned to a non-local variable."
                }
            ]
        },
        {
            "file": "src/misc/lv_area.c",
            "issues": [...]
        }
    ]
}
```

**Comment by b4yuan** [comment]
@kisvegabor Yes! The `Upload to CodeQL Results to code scanning` step uploads the results in a streamlined human readable format under Code Scanning in the Security tab of this repository. 
image
From here, you can also dismiss certain bugs for different reasons:
image

**Comment by kisvegabor** [comment]
Looks really great! 

Am I correct to assume, that I need to merge the PR first to see the result on the Security tab? If so, probably I can merge it to a new branch, hammer out the issues, and merge to master.

**Comment by kisvegabor** [comment]
I was messing up with merging a little bit, but finally it's merged to the `codeql` branch I rally see the results on the Security tab. I'll review it in detail.

Thank you!

**Pull request merged**
