### PR TITLE
fix(arc) format code

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

Fix code indentation of `lv_arc`.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
@kisvegabor 
I tried to run `scripts/code-format.sh`. It seems that many files have been changed. Do I need to make uniform changes?

**Comment by kisvegabor** [comment]
> I tried to run scripts/code-format.sh. It seems that many files have been changed. Do I need to make uniform changes?

It wasn't run for a while. Maybe we should have a CI action to run PRs and merges to master automatically and push the changes.
@embeddedt What do you think?

**Comment by embeddedt** [comment]
As far as I know, the standard way of handling this is to have a linting check which rejects new PRs/commits if the formatting is done incorrectly. Usually this can be done by running the formatter on the changed files and comparing the outputs to the original files. If the formatting is correct, the two files should be same.

I'll see if I can set something like this up in the coming days.

**Comment by kisvegabor** [comment]
At first look automatic formatting seems easier to use. I'm afraid rejecting PRs would make contributions more difficult.

**Comment by embeddedt** [comment]
There are two potential issues with automatic formatting:

* The formatter has to be capable of not reformatting its own output. I haven't seen it happen that often, but there are times where I've run a formatter and it keeps finding issues with the file every time.
* It creates extra commits in the Git history just for formatting, instead of the existing commits already being properly formatted.

Another option could be to try and have @lvgl-bot push formatting commits to PR branches, which would alleviate the second issue, since we squash PRs when merging anyways.

**Comment by kisvegabor** [comment]
If it's rejected the PRs could it create a meaningful output (or patch) to show the required changes?

**Comment by embeddedt** [comment]
I haven't checked, but I think that should be possible. You are referring to markers like [this](https://github.com/lvgl/lvgl/pull/2401/files#diff-ee48b60c5e9b9e7fb56d45e6f758d69fcc9c6e9b2c0b83843043267c54dba7ccR138), right?

**Comment by kisvegabor** [comment]
I meant only a `format.patch` to show the problematic lines and simply can be downloaded and applied. 

The marker you have shown would be also great but I think not mandatory.  But there should be a simple way to fix all formatting issues at once instead of error and trial while the CI accepts it.

**Comment by embeddedt** [comment]
I haven't seen any project on GitHub pull this off before, but what if the bot posted the diff as a review comment with GitHub's suggested changes feature? In that case, the patch could be applied without even needing to download it.

**Comment by kisvegabor** [comment]
It's a good idea, but if there are many formatting issues it could be cumbersome to accept the suggestions one by one. 
Anyway, I think it could be very well usable in the vast majority of the cases.

**Comment by FASTSHIFT** [comment]
@kisvegabor  
Does this PR still need to be merged?

**Comment by kisvegabor** [comment]
@embeddedt Shall we open a new issue for the code formatter CI?

**Comment by embeddedt** [comment]
Yes; I'm somewhat busy at the moment, but I do intend to set something up when I am able. In the meantime, I suppose we could just run `scripts/code-format.sh` on `master` manually after merging PRs.

**Comment by kisvegabor** [comment]
> but I do intend to set something up when I am able.

Great! 

I've just run `code-format.sh` and pushed it. Let's do it manually more frequently than in the previous months :slightly_smiling_face:

**Pull request closed without merging**
