### PR TITLE
feat(vg_lite): draw border with side attribute support

### PR DESCRIPTION
**Pull request by liujp-arch**
### Description of the feature or fix

vg_lite add draw border side attribute

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by FASTSHIFT — DISMISSED** [review]

**Comment by FASTSHIFT** [comment]
@XuNeo 

This `outlen` is not checked against `decompressed->data_size`, there is a risk of out of bounds, please pay attention.
image

CI report:
```bash
=================================================================
==8749==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf447c8d3 at pc 0xf7831eea bp 0xf595ed08 sp 0xf595e8d8
WRITE of size 8 at 0xf447c8d3 thread T1
    #0 0xf7831ee9 in __interceptor_memcpy ../../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:827
    #1 0x5769e8b9 in lv_memcpy /home/runner/work/lvgl/lvgl/src/stdlib/clib/lv_string_clib.c:40
    #2 0x57a4fb6e in lv_rle_decompress /home/runner/work/lvgl/lvgl/src/libs/rle/lv_rle.c:68
    #3 0x57926c52 in decompress_image /home/runner/work/lvgl/lvgl/src/libs/bin_decoder/lv_bin_decoder.c:1104
    #4 0x57924d32 in decode_compressed /home/runner/work/lvgl/lvgl/src/libs/bin_decoder/lv_bin_decoder.c:961
    #5 0x579166a3 in lv_bin_decoder_open /home/runner/work/lvgl/lvgl/src/libs/bin_decoder/lv_bin_decoder.c:218
    #6 0x575c328b in lv_image_decoder_open /home/runner/work/lvgl/lvgl/src/draw/lv_image_decoder.c:124
    #7 0x575a6d51 in _lv_draw_image_normal_helper /home/runner/work/lvgl/lvgl/src/draw/lv_draw_image.c:159
    #8 0x578c3682 in lv_draw_sw_image /home/runner/work/lvgl/lvgl/src/draw/sw/lv_draw_sw_img.c:164
    #9 0x5788b916 in execute_drawing /home/runner/work/lvgl/lvgl/src/draw/sw/lv_draw_sw.c:444
    #10 0x57889255 in execute_drawing_unit /home/runner/work/lvgl/lvgl/src/draw/sw/lv_draw_sw.c:309
    #11 0x5788ad83 in render_thread_cb /home/runner/work/lvgl/lvgl/src/draw/sw/lv_draw_sw.c:416
    #12 0x5769767b in generic_callback /home/runner/work/lvgl/lvgl/src/osal/lv_pthread.c:162
    #13 0xf7854546 in asan_thread_start ../../../../../src/libsanitizer/asan/asan_interceptors.cpp:207
    #14 0xf6a86c00  (/usr/lib/i386-linux-gnu/libc.so.6+0x86c00)
    #15 0xf6b2372b  (/usr/lib/i386-linux-gnu/libc.so.6+0x12372b)

0xf447c8d3 is located 0 bytes to the right of 18131-byte region [0xf4478200,0xf447c8d3)
allocated by thread T1 here:
    #0 0xf78b5da3 in __interceptor_malloc ../../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x5769e362 in lv_malloc_core /home/runner/work/lvgl/lvgl/src/stdlib/clib/lv_mem_core_clib.c:64
    #2 0x5769f4a3 in lv_malloc /home/runner/work/lvgl/lvgl/src/stdlib/lv_mem.c:70
    #3 0x575a26be in buf_malloc /home/runner/work/lvgl/lvgl/src/draw/lv_draw_buf.c:550
    #4 0x575a2962 in draw_buf_malloc /home/runner/work/lvgl/lvgl/src/draw/lv_draw_buf.c:580
    #5 0x5759cad2 in lv_draw_buf_create_user /home/runner/work/lvgl/lvgl/src/draw/lv_draw_buf.c:283
    #6 0x57926717 in decompress_image /home/runner/work/lvgl/lvgl/src/libs/bin_decoder/lv_bin_decoder.c:1083
    #7 0x57924d32 in decode_compressed /home/runner/work/lvgl/lvgl/src/libs/bin_decoder/lv_bin_decoder.c:961
    #8 0x579166a3 in lv_bin_decoder_open /home/runner/work/lvgl/lvgl/src/libs/bin_decoder/lv_bin_decoder.c:218
    #9 0x575c328b in lv_image_decoder_open /home/runner/work/lvgl/lvgl/src/draw/lv_image_decoder.c:124
    #10 0x575a6d51 in _lv_draw_image_normal_helper /home/runner/work/lvgl/lvgl/src/draw/lv_draw_image.c:159
    #11 0x578c3682 in lv_draw_sw_image /home/runner/work/lvgl/lvgl/src/draw/sw/lv_draw_sw_img.c:164
    #12 0x5788b916 in execute_drawing /home/runner/work/lvgl/lvgl/src/draw/sw/lv_draw_sw.c:444
    #13 0x57889255 in execute_drawing_unit /home/runner/work/lvgl/lvgl/src/draw/sw/lv_draw_sw.c:309
    #14 0x5788ad83 in render_thread_cb /home/runner/work/lvgl/lvgl/src/draw/sw/lv_draw_sw.c:416
    #15 0x5769767b in generic_callback /home/runner/work/lvgl/lvgl/src/osal/lv_pthread.c:162
    #16 0xf7854546 in asan_thread_start ../../../../../src/libsanitizer/asan/asan_interceptors.cpp:207
    #17 0xf6b2372b  (/usr/lib/i386-linux-gnu/libc.so.6+0x12372b)

Thread T1 created by T0 here:
    #0 0xf78545da in __interceptor_pthread_create ../../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x576961a3 in lv_thread_init /home/runner/work/lvgl/lvgl/src/osal/lv_pthread.c:50
    #2 0x5788729c in lv_draw_sw_init /home/runner/work/lvgl/lvgl/src/draw/sw/lv_draw_sw.c:152
    #3 0x5762d0a7 in lv_init /home/runner/work/lvgl/lvgl/src/lv_init.c:180
    #4 0x574c32a4 in lv_test_init /home/runner/work/lvgl/lvgl/tests/src/lv_test_init.c:21
    #5 0x574c28a8 in suiteSetUp /home/runner/work/lvgl/lvgl/tests/build_test_sysheap/test_image_formats_Runner.c:29
    #6 0x574c30dc in main /home/runner/work/lvgl/lvgl/tests/build_test_sysheap/test_image_formats_Runner.c:85
    #7 0xf6a21518  (/usr/lib/i386-linux-gnu/libc.so.6+0x21518)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:827 in __interceptor_memcpy
Shadow bytes around the buggy address:
  0x3e88f8c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e88f8d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e88f8e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e88f8f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3e88f900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x3e88f910: 00 00 00 00 00 00 00 00 00 00[03]fa fa fa fa fa
  0x3e88f920: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e88f930: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e88f940: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e88f950: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e88f960: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==8749==ABORTING
```

**Comment by kisvegabor** [comment]
@FASTSHIFT 
It's great that you have found the problem. It's reported time-to-time by the CI.

**Comment by XuNeo** [comment]
> This `outlen` is not checked against `decompressed->data_size`, there is a risk of out of bounds, please pay attention.

Yes, it's a risk. But the `.rle` files used by CI should always have legal  `data_size` set. Anyway, let's add a safe guard here.

**Comment by kisvegabor** [comment]
> Anyway, let's add a safe guard here.

Could you push a fix in thisPR?

**Comment by kisvegabor** [comment]
Please review the reference images. There are a few incorrect one.

**Comment by FASTSHIFT** [comment]
> Please review the reference images. There are a few incorrect one.

Yes, VG-Lite emulator rendering RGB565 and RGB888 format still have some problems, because ThorVG only supports ARGB8888 color format, because it needs to support software rendering fallback, so before and after each rendering need to convert and copy lvgl framebuffer. There are still some issues with this synchronization process that are being investigated.

**Review by kisvegabor — APPROVED** [review]
We shall add a few pages of docs for some new features (ThorVG rendering, draw_buf, caching, vector fonts, etc), but for now - to not delay this PR - I approve it and we can open follow up PRs if needed.

**Comment by FASTSHIFT** [comment]
Let's continue from here: https://github.com/lvgl/lvgl/pull/6796

**Pull request closed without merging**
