### PR TITLE
fix(comment): remove the space after /* and before */

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

Change the comment only.

### Checkpoints
- [X] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
I suppose you have formatted the comments with a script or search and replace. 

Could you rebase them on `master`?

**Comment by xiaoxiang781216** [comment]
> I suppose you have formatted the comments with a script or search and replace.
> 
> Could you rebase them on `master`?

Done, but I rebase on dev branch. Why need master?

**Comment by xiaoxiang781216** [comment]
github don't support change the merge branch after PR is created, I will create a new PR against master soon.

**Comment by xiaoxiang781216** [comment]
replaced by https://github.com/lvgl/lvgl/pull/2146, let's close this one.

**Pull request closed without merging**
