### PR TITLE
doc(benchmark): update out of date README

### PR DESCRIPTION
**Pull request by GorgonMeducer**
### Description of the feature or fix

The README.md is out of date in some descriptions. 

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thanks. Once this is touched, could you fix it in the other demo READMEs too?

**Comment by GorgonMeducer** [comment]
> Thanks. Once this is touched, could you fix it in the other demo READMEs too?

Let me check, no problem.

**Comment by GorgonMeducer** [comment]
@kisvegabor done. Please review it. Thank you,.

**Comment by embeddedt** [comment]
Thanks!

**Pull request merged**
