### PR TITLE
fix(tiny_ttf):re-initialize cache contents when cleared

### PR DESCRIPTION
**Pull request by sirius506**
### Description of the feature or fix

`ttf_cache_clear()` didn't clear cache contents properly and it prevents `lv_tiny_ttf_set_size()` works correctly.

### Checkpoints
- [ ] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [X] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you! 

The CI fails because the `ubuntu_font.h` is included twice (in the 1st and the 3rd example too) and therefore the variable in it is created twice.  Could you change this `h` file into a `c` file and just declare the variable in the 1st and 3rd example as `extern const uint8_t ubuntu_font[]`?

**Comment by sirius506** [comment]
Thanks for your help. I made suggested changes.

Since I don't have MP build/test environment, I hope someone else add `lv_example_tiny_ttf_3.py`.

**Comment by kisvegabor** [comment]
Amazing, thank you! 

@uraich do you have time to add this example for MicroPython?

**Comment by uraich** [comment]
Trying to get the C version to run:
First I had to add the math library to CMakeLists.txt of lvgl:
target_link_libraries(lvgl PRIVATE m)
Then I had to adapt lv_conf.h enabling LV_USE_TINY_TTF  and  LV_USE_MSG
After that lv_example_tiny_ttf_3 compiles but I get:
image
when trying to run it.

**Comment by sirius506** [comment]
Yes, example needs LV_USE_TINY_TTF and LV_USE_MSG enabled. I also enabled LV_USE_SDL2 to make it run on my MacOS machine.

I'll try to setup Linux machine in next week for further testing.

**Comment by uraich** [comment]
The problem appears in:  lv_tiny_ttf_set_size(font, *v)
When I comment this line, it does not crash, but of course the font size is not changed either

**Comment by sirius506** [comment]
@uraich , yes I've tried to fix `lv_tiny_ttf_set_size()` in this PR #4426, but it looks there are some hidden bugs.

I have prepared Ubuntu 22.04.3 environment and tested the example, but It runs successfully. For your reference, my test program code can be found at https://github.com/sirius506/Tiny_TTF_Test.git .

It looks your lv_conf.h contains `#define LV_USE_STDLIB_MALLOC  LV_STDLIB_CLIB`. Could you please try to change it to `LV_STDLIB_BUILTIN`?

**Comment by uraich** [comment]
Thanks! You were right that it is a problem in lv:conf.h. However it is not the LV_USE_STDLIB_MALLOC option.
So @kisvegabor : we can use LV_STDLIB_CLIB!
The problem was that in my lv_conf.h LV_DRAW_BUF_ALIGN was set to 32, which it did not like. When setting it to 4 as in your lv_conf.h things work fine.

**Comment by kisvegabor** [comment]
> we can use LV_STDLIB_CLIB!

Only for C development to catch issues in C LVGL. For MP you still need `LV_STDLIB_MICROPYTHON`.

> The problem was that in my lv_conf.h LV_DRAW_BUF_ALIGN was set to 32, which it did not like. When setting it to 4 as in your lv_conf.h things work fine.

Locally I'm also using `LV_DRAW_BUF_ALIGN`. I don't know what could be the problem.

**Comment by uraich** [comment]
MicroPython version of lv_example_tiny_ttf_3.py:
image
Will try to prepare a PR tomorrow

**Pull request merged**
