### PR TITLE
feat(disp): add a temporary disable invalidation interface

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

Related discussion https://github.com/lvgl/lvgl/issues/3305

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
@kisvegabor 
Do you mean to modify like this?

**Comment by kisvegabor** [comment]
Yes, I just pushed a few minor changes. 

Before this patch image transformation invalidated these areas:
before

And now:
after

Do you agree with my changes?

**Comment by FASTSHIFT** [comment]
It looks like the drawable area is reduced a lot, I agree with this.

**Comment by kisvegabor** [comment]
Merged, thank you!

**Pull request merged**
