### PR TITLE
fixes documentation versioning.

### PR DESCRIPTION
**Pull request by kdschlosser**
the documentation build process needs to have the major.minor version not major.minor.path

### CODE REVIEW

**Comment by kdschlosser** [comment]
did it fix the problem?

**Comment by kdschlosser** [comment]
it looks as tho it did. I am going to have to see why some of the information is not populated in the API section. could be simply because there is no documentation keyed in

**Comment by kisvegabor** [comment]
The examples are working indeed, thank you for this fix!
However the link of the blue buttons are still not correct :slightly_frowning_face: 
image

**Comment by kdschlosser** [comment]
I will have a look at it and see what is going on with them. No worries. I will get it sorted

**Pull request merged**
