### PR TITLE
Unit tests for label widget

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

What the title says

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by C47D** [comment]
Is it me or there's a missing `strcpy` at the end of this block when `LV_USE_ARABIC_PERSIAN_CHARS` is set to 0? Just after the realllocation on line 107

https://github.com/lvgl/lvgl/blob/2461ac0758eae69a94ee60a9be50d3de882ced09/src/widgets/label/lv_label.c#L85-L112

---
How does `lv_label_get_letter_pos` return the point when text is not aligned to the left?

**Comment by C47D** [comment]
In `lv_label_refr_text` there's two calls to `lv_anim_set_exec_cb(&a, set_ofs_x_anim);` when `LV_USE_BIDI` is set to 0. Is this expected?

See last line of `else` and one line after `endif`

https://github.com/lvgl/lvgl/blob/2461ac0758eae69a94ee60a9be50d3de882ced09/src/widgets/label/lv_label.c#L948-L959

**Comment by C47D** [comment]
@kisvegabor There are some methods that aren't tested directly by unit tests, but covered trough other tests, I'll add tests for those in the week.

**Comment by C47D** [comment]
I've ran [ravioli](https://github.com/ElectronVector/ravioli) and got this output:

```console
$ ravioli -f src/widgets/label/lv_label.c
<bunch of globals>
-------------------------------------------------------------------------------
Functions                                                            complexity
-------------------------------------------------------------------------------
src/widgets/label/lv_label.c:860
    lv_label_refr_text                                                      42
src/widgets/label/lv_label.c:273
    lv_label_get_letter_pos                                                 21
src/widgets/label/lv_label.c:384
    lv_label_get_letter_on                                                  19
src/widgets/label/lv_label.c:756
    draw_main                                                               19
src/widgets/label/lv_label.c:498
    lv_label_is_char_under_pos                                              12
src/widgets/label/lv_label.c:703
    lv_label_event                                                          11
src/widgets/label/lv_label.c:91
    lv_label_set_text                                                        8
src/widgets/label/lv_label.c:180
    lv_label_set_long_mode                                                   6
src/widgets/label/lv_label.c:162
    lv_label_set_text_static                                                 4
src/widgets/label/lv_label.c:607
    lv_label_ins_text                                                        4
src/widgets/label/lv_label.c:1137
    lv_label_revert_dots                                                     4
src/widgets/label/lv_label.c:1168
    lv_label_set_dot_tmp                                                     3
src/widgets/label/lv_label.c:1214
    lv_label_dot_tmp_free                                                    3
src/widgets/label/lv_label.c:1260
    get_label_flags                                                          3
src/widgets/label/lv_label.c:1271
    calculate_x_coordinate                                                   3
src/widgets/label/lv_label.c:206
    lv_label_set_recolor                                                     2
src/widgets/label/lv_label.c:635
    lv_label_cut_text                                                        2
src/widgets/label/lv_label.c:693
    lv_label_destructor                                                      2
src/widgets/label/lv_label.c:1198
    lv_label_get_dot_tmp                                                     2
src/widgets/label/lv_label.c:79
    lv_label_create                                                          1
src/widgets/label/lv_label.c:219
    lv_label_set_text_sel_start                                              1
src/widgets/label/lv_label.c:233
    lv_label_set_text_sel_end                                                1
src/widgets/label/lv_label.c:251
    lv_label_get_text                                                        1
src/widgets/label/lv_label.c:258
    lv_label_get_long_mode                                                   1
src/widgets/label/lv_label.c:265
    lv_label_get_recolor                                                     1
src/widgets/label/lv_label.c:577
    lv_label_get_text_selection_start                                        1
src/widgets/label/lv_label.c:590
    lv_label_get_text_selection_end                                          1
src/widgets/label/lv_label.c:657
    lv_label_constructor                                                     1
src/widgets/label/lv_label.c:1225
    set_ofs_x_anim                                                           1
src/widgets/label/lv_label.c:1232
    set_ofs_y_anim                                                           1
src/widgets/label/lv_label.c:1239
    get_text_length                                                          1
src/widgets/label/lv_label.c:1251
    copy_text_to_label                                                       1
```

So maybe adding tests to more complex functions and then refactor them might be a good idea, what do you think?

[lv_label_ravioli.txt](https://github.com/lvgl/lvgl/files/9248044/lv_label_ravioli.txt)

**Comment by kisvegabor** [comment]
I'm sorry,  somehow I didn't see your first comment...
> Is it me or there's a missing strcpy at the end of this block when LV_USE_ARABIC_PERSIAN_CHARS is set to 0? Just after the realllocation on line 107

It's [here](https://github.com/lvgl/lvgl/blob/2461ac0758eae69a94ee60a9be50d3de882ced09/src/widgets/label/lv_label.c#L137).

> How does lv_label_get_letter_pos return the point when text is not aligned to the left?

Some offset is added to the x coordinate [here](https://github.com/lvgl/lvgl/blob/2461ac0758eae69a94ee60a9be50d3de882ced09/src/widgets/label/lv_label.c#L297-L306) and [here](https://github.com/lvgl/lvgl/blob/2461ac0758eae69a94ee60a9be50d3de882ced09/src/widgets/label/lv_label.c#L380-L391).

> In lv_label_refr_text there's two calls to lv_anim_set_exec_cb(&a, set_ofs_x_anim); when LV_USE_BIDI is set to 0. Is this expected?

Nope, it's by mistake. 

> There are some methods that aren't tested directly by unit tests, but covered trough other tests, I'll add tests for those in the week.

No problem with that. Testing indirectly is fine as well.

**Comment by C47D** [comment]
> I'm sorry, somehow I didn't see your first comment...

No problem, I've added the fix for `lv_label_refr_txt`. Here we are so far:
imagen

All of the selection related functions are not tested yet...

---
Any idea on why the Micropython step isn't passing?

**Comment by C47D** [comment]
I haven't been able to figure out how to text the uncovered parts of the code, maybe some tips would be cool. Change the file extension of attached file to html to see the latest report.

Is there a chance to rename the text selection interfaces? setters and getters are not similar.

Ready to be reviewed @kisvegabor @embeddedt , suggestions very welcome

[index.src_widgets_label_lv_label.c.txt](https://github.com/lvgl/lvgl/files/9313832/index.src_widgets_label_lv_label.c.txt)

**Comment by kisvegabor** [comment]
The remaining parts are really hard to test. It's now on 86.5% and the label widget is one of the most complex ones. So I'd say it's fine.

> Is there a chance to rename the text selection interfaces? setters and getters are not similar.


Definitely! In v9 we can do it. Please go rename it using `selection`.

**Comment by C47D** [comment]
Fixed formatting error and opened #3573 to keep track of the suggested interface rename

**Comment by kisvegabor** [comment]
Thank you, Carlos. Looks good, I merge it.

Please send an expense at [Open collective](https://opencollective.com/lvgl) about 50 USD.

**Pull request merged**
