### PR TITLE
feat(version): add LV_VERSION_AT_LEAST

### PR DESCRIPTION
**Pull request by mysterywolf**
Checks if the current version is at least the specified x.y.z version.

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
The worst case assumption is that anything can change in major versions so we can't rely on compatibility among major versions. We are improving it though by adding less and less breaking changes, but I wonder what is the use case for this macro.

**Comment by mysterywolf** [comment]
rt-thread CI detect there is a commit changed font size of the demo recently, but our board still use old font size configuration. I want to use this macro to identify the version.  or any good suggestions?

Like:

if LVGL_VERSION > v9.2.0
use new font size config
else
use old font size config

**Comment by mysterywolf** [comment]
Some RT-Thread BSPs have added LVGL as part of CI checking
https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32/stm32f407-rt-spark/.ci/attachconfig/online-packages/multimedia/lvgl
https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32/stm32l475-atk-pandora/.ci/attachconfig/lvgl
https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32/stm32f469-st-disco/.ci/attachconfig/lvgl

**Comment by kisvegabor** [comment]
I see. 

SDL uses `SDL_VERSION_ATLEAST` which a good name IMO.

Are you sure about the relation symbols. I think it should be:
```c
#define LV_VERSION_AT_LEAST(x,y,z) 
(x > LVGL_VERSION_MAJOR || 
(x == LVGL_VERSION_MAJOR && (y > LVGL_VERSION_MINOR ||  
                            (y == LVGL_VERSION_MINOR && z >= LVGL_VERSION_PATCH))))

```

**Comment by mysterywolf** [comment]
Good suggestion! Let me revise it.

**Comment by mysterywolf** [comment]
@kisvegabor Could you take a look. I have updated the PR. Thanks for your robot😁

**Review by kissa96 — APPROVED** [review]
Awesome feature! But could you surround the operators with parenthases?

**Comment by kisvegabor** [comment]
> Thanks for your robot😁

😊


So `LV_VERSION_CHECK` requires the same major version, while `LV_VERSION_AT_LEAST` requires at least the given major version. If you agree, could you highlight this difference in a comment?

**Comment by mysterywolf** [comment]
Yes I have added

**Review by liamHowatt — CHANGES_REQUESTED** [review]
The logic is inverted. See this test case.

```c
#define LVGL_VERSION_MAJOR 9
#define LVGL_VERSION_MINOR 3
#define LVGL_VERSION_PATCH 0

#define LV_VERSION_AT_LEAST(x,y,z) (x > LVGL_VERSION_MAJOR || (x == LVGL_VERSION_MAJOR && (y > LVGL_VERSION_MINOR || (y == LVGL_VERSION_MINOR && z >= LVGL_VERSION_PATCH))))

#if LV_VERSION_AT_LEAST(8, 0, 0)
// ok
#else
#error
#endif
```

**Comment by kisvegabor** [comment]
Ahhhh, that's true. `LV_VERSION_AT_LEAST(8, 0, 0)` should be true, but now it's evaluated to false.

**Pull request closed without merging**
