### PR TITLE
use margin in the header part of calendar.

### PR DESCRIPTION
**Pull request by ali-rostami**
Hi
As I discussed [here](https://forum.lvgl.io/t/increase-the-header-part-of-calendar/3028), I think it's a good idea to use the top margin for setting the distance between the header and the top of the calendar and bottom margin for the header and the start of day names part. 
Padding can also be used for increasing the colorful part of the header.
So now we can have a calendar like this:
calendar

`
lv_obj_set_style_local_clip_corner(calendar_date, LV_CALENDAR_PART_BG, LV_STATE_DEFAULT, true);
		lv_obj_set_style_local_clip_corner(calendar_date, LV_CALENDAR_PART_BG, LV_STATE_FOCUSED, true);
		lv_obj_set_style_local_text_color(calendar_date, LV_CALENDAR_PART_DATE, LV_STATE_DISABLED, LV_COLOR_GRAY);
		lv_obj_set_style_local_margin_top(calendar_date, LV_CALENDAR_PART_HEADER, LV_STATE_DEFAULT, 0);
		lv_obj_set_style_local_margin_bottom(calendar_date, LV_CALENDAR_PART_HEADER, LV_STATE_DEFAULT, 10);
		lv_obj_set_style_local_pad_ver(calendar_date, LV_CALENDAR_PART_HEADER, LV_STATE_DEFAULT, 20);
		lv_obj_set_style_local_bg_color(calendar_date, LV_CALENDAR_PART_HEADER, LV_STATE_DEFAULT, lv_color_hex3(0xddd));
		lv_obj_set_style_local_bg_opa(calendar_date, LV_CALENDAR_PART_HEADER, LV_STATE_DEFAULT, LV_OPA_COVER);
`

### CODE REVIEW

**Comment by kisvegabor** [comment]
Good idea! With the current themes will it work it look like before by default?

**Comment by ali-rostami** [comment]
> Good idea! With the current themes will it work it look like before by default?

No, I didn't change the theme, I think it's better to add some bottom margin. to make it like the above picture. what do you think?

**Comment by kisvegabor** [comment]
I'm ok with that. The goal is to look like as it was. Can you add this compatibility changes on themes?

**Comment by ali-rostami** [comment]
Not sure how much you like the edit I made, but now the default calendar should be displayed as before.

**Comment by kisvegabor** [comment]
Looks good, however, the same needs to be applied to the `mono` theme too. Can you still do this?
I'll update the docs meanwhile.

**Comment by ali-rostami** [comment]
> Looks good, however, the same needs to be applied to the `mono` theme too. Can you still do this?

Yeah, No problem.
In the mono `calendar_init` version, there is no using of  `lv_style_set_pad_top/bottom`. Not sure, but seems that we don't need to do anything here. Am I right?

> I'll update the docs meanwhile.

Thanks 🙏

**Comment by kisvegabor** [comment]
Looking into the mono theme it seems it's really good as it is. 

I merged it to `dev` and updated the [docs](https://github.com/lvgl/docs/commit/493e1a8969ed1f17341f83091f5ad7da25a54f07).

Thank you!

**Comment by ali-rostami** [comment]
Thanks

**Pull request merged**
