### PR TITLE
feat(arm-2d): improve the performance and reduce the memory footprint

### PR DESCRIPTION
**Pull request by GorgonMeducer**
To catch up with new features in arm-2d v1.2.0, it is possible to improve the performance of arm-2d acceleration for LVGL and to reduce the SRAM footprint simultaneously. 

The polish work had been applied to v9.2.0, and now it is time for v8.4.x

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
I have run the code-format.py in the v8.4.0 script folder, it should pass. 
It appears that the CI uses a different format than the one used in v8.4.0

**Comment by GorgonMeducer** [comment]
@kisvegabor Do you have time to check this? Thank you.

**Review by uLipe — APPROVED** [review]
LGTM, it seems the CI failure is not related to this PR.

**Comment by GorgonMeducer** [comment]
Thank you for verifying this. @uLipe

**Comment by uLipe** [comment]
@kisvegabor do you have any idea on what is happening on the CI on this test? It seems for me the image is not available anymore.

**Comment by GorgonMeducer** [comment]
Any update? @kisvegabor

**Comment by kisvegabor** [comment]
Sorry, for the delay. The CI really seems like an independent issue. Something went wrong with caching.  Merging it now, and Ill try to fix it independently.

**Review by kisvegabor — APPROVED** [review]

**Comment by GorgonMeducer** [comment]
Thank you very much @kisvegabor

**Pull request merged**
