### PR TITLE
arch(cmsis-pack): implement check_pack.sh script

### PR DESCRIPTION
**Pull request by bbkarim**
### Description of the feature or fix

  * Check the pdsc file for missing files
  * Check the pdsc file for missing defines

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
Can you please add a readme for : 

a. The purpose / the function of this script 
b. How to use

Thanks

**Comment by bbkarim** [comment]
> Can you please add a readme for :
> 
> a. The purpose / the function of this script b. How to use
> 
> Thanks

Hello @GorgonMeducer 

This script is located in the cmsis-pack folder near to the gen_pack.sh script. I can't add a specific readme file for it.

However, I did the same like what is inside the gen_pack.sh script, I added a header section to the new script describing its purpose and prerequisites.

```
#!/bin/bash
# Version: 1.0.0
# Date: 2023-01-05
# This bash script check the content of the CMSIS Software Pack:
#
# Pre-requisites:
# - bash shell (for Windows: install git for Windows)
```

If you agree I can add one more section about the parameters to adjust when needed. something about the **PACK_EXCLUDED_DIRS**, the **PACK_EXCLUDED_FILES** and the **PACK_EXCLUDED_DEFINES**

**Comment by bbkarim** [comment]
I propose the below header section:

```
#!/bin/bash
# Version: 1.0.0
# Date: 2023-01-05
# This bash script check the content of the CMSIS Software Pack:
# * The script will start by checking for missing files inside the PDSC file
#   - File extensions are: *.c, *.h, *.md, *.png and *.gif
#   - PACK_EXCLUDED_DIRS is used to ignore directories from the search
#   - PACK_EXCLUDED_FILES is used to ignore specific files from the search
#   - results/ignored_files.txt will be generated for ignored files
#   - results/missing_files.txt will be generated for missing files
#
# * Then it will check for missing defines inside the PDSC file
#   - Defines are starting with 'LV_USE_'
#   - PACK_EXCLUDED_DEFINES is used to ignore specific defines from the search
#   - results/ignored_defines.txt will be generated for ignored defines
#   - results/missing_defines.txt will be generated for missing defines
#
# Missing files and defines need to be either implemented inside the PDSC or added
# to the EXCLUDED arrays
#
# Pre-requisites:
# - bash shell (for Windows: install git for Windows)
```
@GorgonMeducer  please let me know if it is fine.

**Comment by GorgonMeducer** [comment]
The header section is fine. You can also add a me file called: HowToCheckPDSC.md and put a step by step guidance for both windows users and Linux users.

**Comment by bbkarim** [comment]
> The header section is fine. You can also add a me file called: HowToCheckPDSC.md and put a step by step guidance for both windows users and Linux users.

The script does not require parameters, it is simple and does not need a document. If I'll add a me file then it will be more or less the same like the header section with two lines more explaining what is compared to what...

**Comment by GorgonMeducer** [comment]
OK, that's fine.

**Pull request closed without merging**
