### PR TITLE
clangd: IWYU pragmas for proper auto-import

### PR DESCRIPTION
**Pull request by voltangle**
### Description of the feature or fix

This PR adds `// IWYU pragma: private, include <lvgl/lvgl.h">` statements all over internal header files that are re-exported by `lvgl.h`. This allows `clangd` to properly auto-import a correct, `<lvgl/lvgl.h>` header, instead of an internal one.

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [x] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [x] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [x] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [x] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [x] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [x] Use typed pointers instead of `void *` pointers
- [x] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [x] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [x] Widget members function must start with `lv_<module_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [x] `struct`s should be used via an API and not modified directly via their elements.
- [x] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [x] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [x] Arguments must be named in H files too.
- [x] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

> This allows clangd to properly auto-import a correct, <lvgl/lvgl.h> header, instead of an internal one.

Could you tell in more detail what the exact problem is that this PR solves?

**Comment by ggoraa** [comment]
> Could you tell in more detail what the exact problem is that this PR solves?

Definitely!

You see, I'm using `clangd` as an LSP, and it has a feature - auto-include, like a lot of other LSPs. But, when I actually use it, instead of importing the "umbrella" header `<lvgl/lvgl.h>`, it imports an internal one, from `src`, which is definitely not ideal.

Here's a video demonstration:

https://github.com/lvgl/lvgl/assets/61655029/06114108-5268-4ace-8112-24cc73620621

**Comment by kisvegabor** [comment]
I see thank you. Do you what is the policy of clangs when it decides which header to choose?

I'm just asking because it would be great to make it work out of the box.

Besides I wonder if it would be enough to add the comment only to `lvgl.h`. Regular users should need only it.

**Comment by ggoraa** [comment]
https://clangd.llvm.org/design/include-cleaner#umbrella-headers

**Comment by XuNeo** [comment]
I haven't had the opportunity to utilize this feature yet. Is there a way to circumvent the need to alter each private header?

Would it be feasible to only make modifications to lvgl.h to designate the headers as export? For reference, [see the documentation on IWYU pragmas](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-export)

**Comment by XuNeo** [comment]
I haven't had the opportunity to utilize this feature yet. Is there a way to circumvent the need to alter each private header?

Would it be feasible to only make modifications to lvgl.h to designate the headers as export? For reference, [see the documentation on IWYU pragmas](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-export)

**Comment by ggoraa** [comment]
Yeah, no, sadly it doesn't work with `clangd`
only the "redirect" comments do
shouldn't be a neovim problem, because it's all handled by `clangd` itself

**Comment by XuNeo** [comment]
I still haven't the chance to try it. Today I saw a file in `skia` repo to include directives for IWYU that we can do the same.

See explains here. https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md

> Include mappings support a special wildcard syntax for the first entry:
> 
> { include: ["@<internal/.*>", "private", "<public>", "public"] }

See files from skia. https://github.com/google/skia/blob/main/toolchain/linux_trampolines/IWYU_mapping.imp

From the video you provides, we can map all includes starting with `src/` to `lvgl/lvgl.h`
> { include: ["@<src/.*>", "private", "<lvgl/lvgl.h>", "public"] }

**Comment by ggoraa** [comment]
I hate this bot, honestly

**Comment by ggoraa** [comment]
I hate this bot, honestly
@kisvegabor can you reopen this please? And why do you guys even have this "close when stale" bot?) Imo it's useless, and usually just gets in the way

**Comment by kisvegabor** [comment]
Reopened. 

> And why do you guys even have this "close when stale" bot?)

Else we would have a lot of abandoned open issues and it would be hard to filter out the active relevant ones.  If an issue was important we can pin it or reopen it. For example in case of this issue I assumed that no one has time or interest to continue the investigation.

**Pull request closed without merging**
