### PR TITLE
arc initial unit tests

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

What the title says, if you need me to add any special test please let me know 😸 

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by C47D** [comment]
`test_arc_should_truncate_to_min_range_when_new_value_is_inferior` fails because the expected `min_value` after creation is 1 (from the [docs](https://docs.lvgl.io/master/widgets/core/arc.html#value-and-range)), not 0. Please let me know if this is not the case.

There are some refactor opportunities that could be done in `lv_arc.c`, but achieving a high ~~100%~~ test coverage before hand would be very useful. That way we have a test harness that would let us know if we break something (a test) with the refactor, what do you think @kisvegabor @embeddedt? 

@cmumford Thanks for adding coverage report, it does look very nice 😸 , I need to research how to 'visualize' the coverage info in the source files within WSL tho.
imagen

**Comment by kisvegabor** [comment]
> test_arc_should_truncate_to_min_range_when_new_value_is_inferior fails because the expected min_value after creation is 1 (from the docs), not 0. Please let me know if this is not the case.


The docs was incorrect. I've [updated it](https://github.com/lvgl/lvgl/commit/2a9b9e6e1119db8294fdc63d93548fe06e2b6aa2) to say 0..100.

> There are some refactor opportunities that could be done in lv_arc.c

Can you mention some of these opportunities?

**Comment by C47D** [comment]
If you have more tests ideas please let me know. How can I trigger `lv_arc_event`? That function has almost no coverage.

> The docs was incorrect. I've updated it to say 0..100.

Thanks, I've updated the test accordingly

> Can you mention some of these opportunities?

It's just a cleanup on the `value_update` function, but having it covered with tests we're now able to change it and have immediate feedback to refactor it.

```diff
diff --git a/src/widgets/lv_arc.c b/src/widgets/lv_arc.c
index 4df3dc015..0cc1446f0 100644
--- a/src/widgets/lv_arc.c
+++ b/src/widgets/lv_arc.c
@@ -816,26 +816,24 @@ static void value_update(lv_obj_t * obj)
     /*If the value is still not set to any value do not update*/
     if(arc->value == VALUE_UNSET) return;

-    int16_t bg_midpoint, range_midpoint, bg_end = arc->bg_angle_end;
-    if(arc->bg_angle_end < arc->bg_angle_start) bg_end = arc->bg_angle_end + 360;
+    int16_t bg_end = arc->bg_angle_end;
+    if(arc->bg_angle_end < arc->bg_angle_start) bg_end += 360;

     int16_t angle;
     switch(arc->type) {
-        case LV_ARC_MODE_SYMMETRICAL:
-            bg_midpoint = (arc->bg_angle_start + bg_end) / 2;
-            range_midpoint = (int32_t)(arc->min_value + arc->max_value) / 2;
+        case LV_ARC_MODE_SYMMETRICAL: {
+            int16_t bg_midpoint = (arc->bg_angle_start + bg_end) / 2;
+            int16_t range_midpoint = (int16_t)(arc->min_value + arc->max_value) / 2;

             if(arc->value < range_midpoint) {
                 angle = lv_map(arc->value, arc->min_value, range_midpoint, arc->bg_angle_start, bg_midpoint);
-                lv_arc_set_start_angle(obj, angle);
-                lv_arc_set_end_angle(obj, bg_midpoint);
+                lv_arc_set_angles(obj, angle, bg_midpoint);
             }
             else {
                 angle = lv_map(arc->value, range_midpoint, arc->max_value, bg_midpoint, bg_end);
-                lv_arc_set_start_angle(obj, bg_midpoint);
-                lv_arc_set_end_angle(obj, angle);
+                lv_arc_set_angles(obj, bg_midpoint, angle);
             }
-            break;
+        }   break;
         case LV_ARC_MODE_REVERSE:
             angle = lv_map(arc->value, arc->min_value, arc->max_value, arc->bg_angle_start, bg_end);
             lv_arc_set_angles(obj, angle, arc->bg_angle_end);
```

**Comment by C47D** [comment]
So this is the current coverage on the `value_update` function:
imagen

With the following patch (a.k.a. refactor) we keep the same coverage and tests passing (some castings still needed tho).
```diff
diff --git a/src/widgets/lv_arc.c b/src/widgets/lv_arc.c
index 4df3dc015..ba01739f2 100644
--- a/src/widgets/lv_arc.c
+++ b/src/widgets/lv_arc.c
@@ -816,38 +816,45 @@ static void value_update(lv_obj_t * obj)
     /*If the value is still not set to any value do not update*/
     if(arc->value == VALUE_UNSET) return;
 
-    int16_t bg_midpoint, range_midpoint, bg_end = arc->bg_angle_end;
-    if(arc->bg_angle_end < arc->bg_angle_start) bg_end = arc->bg_angle_end + 360;
+    int16_t bg_end = arc->bg_angle_end;
+    if(arc->bg_angle_end < arc->bg_angle_start) bg_end += 360;
+
+    int16_t angle = 0;
+    uint16_t new_start_angle = 0;
+    uint16_t new_end_angle = 0;
 
-    int16_t angle;
     switch(arc->type) {
-        case LV_ARC_MODE_SYMMETRICAL:
-            bg_midpoint = (arc->bg_angle_start + bg_end) / 2;
-            range_midpoint = (int32_t)(arc->min_value + arc->max_value) / 2;
+        case LV_ARC_MODE_SYMMETRICAL: {
+            int16_t bg_midpoint = (arc->bg_angle_start + bg_end) / 2;
+            int16_t range_midpoint = (int16_t)(arc->min_value + arc->max_value) / 2;
 
             if(arc->value < range_midpoint) {
-                angle = lv_map(arc->value, arc->min_value, range_midpoint, arc->bg_angle_start, bg_midpoint);
-                lv_arc_set_start_angle(obj, angle);
-                lv_arc_set_end_angle(obj, bg_midpoint);
+                angle = (int16_t) lv_map(arc->value, arc->min_value, range_midpoint, arc->bg_angle_start, bg_midpoint);
+                new_start_angle = angle;
+                new_end_angle = bg_midpoint;
             }
             else {
-                angle = lv_map(arc->value, range_midpoint, arc->max_value, bg_midpoint, bg_end);
-                lv_arc_set_start_angle(obj, bg_midpoint);
-                lv_arc_set_end_angle(obj, angle);
+                angle = (int16_t) lv_map(arc->value, range_midpoint, arc->max_value, bg_midpoint, bg_end);
+                new_start_angle = bg_midpoint;
+                new_end_angle = angle;
             }
-            break;
+        }   break;
         case LV_ARC_MODE_REVERSE:
-            angle = lv_map(arc->value, arc->min_value, arc->max_value, arc->bg_angle_start, bg_end);
-            lv_arc_set_angles(obj, angle, arc->bg_angle_end);
+            angle = (int16_t) lv_map(arc->value, arc->min_value, arc->max_value, arc->bg_angle_start, bg_end);
+            new_start_angle = angle;
+            new_end_angle = arc->bg_angle_end;
             break;
         case LV_ARC_MODE_NORMAL:
-            angle = lv_map(arc->value, arc->min_value, arc->max_value, arc->bg_angle_start, bg_end);
-            lv_arc_set_angles(obj, arc->bg_angle_start, angle);
+            angle = (int16_t) lv_map(arc->value, arc->min_value, arc->max_value, arc->bg_angle_start, bg_end);
+            new_start_angle = arc->bg_angle_start;
+            new_end_angle = angle;
             break;
         default:
             LV_LOG_WARN("Invalid mode: %d", arc->type);
             return;
     }
+
+    lv_arc_set_angles(obj, new_start_angle, new_end_angle);
     arc->last_angle = angle; /*Cache angle for slew rate limiting*/
 }
```

**Comment by C47D** [comment]
**OFFTOPIC**
Why is the API documented in both header and source file? It seems like the docs are being generated with the latter, and in the picture the docs are wrong.
imagen

in the source file:
imagen

in the header file:
imagen

**Comment by C47D** [comment]
> How can I trigger lv_arc_event? That function has almost no coverage.

I left that function without tests on purpose.

**Comment by kisvegabor** [comment]
> OFFTOPIC
Why is the API documented in both header and source file? It seems like the docs are being generated with the latter, and in the picture the docs are wrong.

API comments should be only in the headers and a lot of files are already updated but still not all. I've pushed a commit to fix it case of the arc. 

> How can I trigger lv_arc_event? That function has almost no coverage.

The functions from `lv_test_indev.c` should help to send pressing, release and key events. A rendering test can help to trigger draw related events.

**Comment by C47D** [comment]
> The functions from lv_test_indev.c should help to send pressing, release and key events. A rendering test can help to trigger draw related events.

I tried to trigger the `VALUE_CHANGED` event but I wasn't able to do so. I will try again later.

**Comment by C47D** [comment]
Can we merge this and keep the event test for later?

**Comment by kisvegabor** [comment]
> Can we merge this and keep the event test for later?

Sure, every bit of test is a treasure. :slightly_smiling_face: 

Thank you very much!

**Pull request merged**
