### PR TITLE
fix(kconfig): Do not set LV_CONF_SKIP by default

### PR DESCRIPTION
**Pull request by faxe1008**
Due to the way that Kconfig symbols work, this can not be turned off if it is defaulted to true.

### Description of the feature or fix

While rebasing the Zephyr integration I encountered the issue that the `lv_conf.h` that is used to point to the `malloc_core` etc. functions is not included correctly in the respective headers. Investigating the issue shows that since this symbol is defined with `default y` I can not turn it  off from my "third party" code. Having an unconditional `default y` in Kconfig essentially always enables the option since it can not be turned of. This should be avoided.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
For custom memory allocation functions, you only need to implement `lv_malloc_core(size_t size)` externally and configure `LV_USE_CUSTOM_MALLOC` to y in menuconfig. Why do we need `lv_conf.h`?

**Comment by faxe1008** [comment]
I need to set `LV_STDLIB_INCLUDE` because otherwise the lv_malloc_core symbol can not be found. Also I need to set a custom OSAL implementation. I thought that this was the purpose of `lv_conf.h` in the first place?

**Comment by kisvegabor** [comment]
I see the problem, however if we disable `LV_CONF_SKIP` by default, all platforms need to add at least an empty `lv_conf.h` file.

Can we workaround it by making it a `choice` similar to [LV_COLOR_DEPTH](https://github.com/lvgl/lvgl/blob/master/Kconfig#L16-L40)?

Having a Zephyr stdlib and OSAL interface built-in to LVGL would also solve the issue! :slightly_smiling_face:  See [RT-Thread](https://github.com/lvgl/lvgl/tree/master/src/stdlib/rtthread) as an example.

**Comment by faxe1008** [comment]
> I see the problem, however if we disable `LV_CONF_SKIP` by default, all platforms need to add at least an empty `lv_conf.h` file.
> 
> Can we workaround it by making it a `choice` similar to [LV_COLOR_DEPTH](https://github.com/lvgl/lvgl/blob/master/Kconfig#L16-L40)?
> 
> Having a Zephyr stdlib and OSAL interface built-in to LVGL would also solve the issue! 🙂 See [RT-Thread](https://github.com/lvgl/lvgl/tree/master/src/stdlib/rtthread) as an example.

Unfortunately this will not work with a choice sybol either. Roughly speaking this is the build process on Zephyr side:
```
1. Parse LVGLs Kconfig file
2. Parse the Kconfig file of Zephyr: Here we have additional options regarding memory management, additional shells etc.
3. Parse the users overlay file and overwrite
```
Overwriting any defaulted value in step 2. does not work as for any Kconfig symbol with a default value the first occurence of the declaration will determine the value (which is set in step 1 by LVGLs Kconfig). 

You can in theory overwrite this in the overlay file which can be provided by the user. But its kind of odd to push this responsibility to the user to enable a config that "configures the build" and needs to be unset every time no matter the project really.

Anyways if you are not ok with removing the default I found a solution that works and should not break any other users of Kconfig:
```
diff --git a/src/lv_conf_internal.h b/src/lv_conf_internal.h
index 2c1986092..6336284eb 100644
--- a/src/lv_conf_internal.h
+++ b/src/lv_conf_internal.h
@@ -47,7 +47,7 @@
 #endif

 /*If lv_conf.h is not skipped include it*/
-#ifndef LV_CONF_SKIP
+#if !defined(LV_CONF_SKIP) || defined(LV_CONF_PATH)
     #ifdef LV_CONF_PATH                           /*If there is a path defined for lv_conf.h use it*/
         #define __LV_TO_STR_AUX(x) #x
         #define __LV_TO_STR(x) __LV_TO_STR_AUX(x)
```

Effectively assume that the conf should not be skipped if `LV_CONF_PATH` has a value. Since `LV_CONF_PATH` is not controlled via Kconfig Zephyr can simply use a preprocessor define for this. If you think about it, it also makes sense semantically since why would you set this macro if you do not intend to use an "outside" lv_conf.h?

What do you think @kisvegabor ?

**Review by kisvegabor — APPROVED** [review]
Great!

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
