### PR TITLE
Add custom RLE decoder

### PR DESCRIPTION
**Pull request by XuNeo**
### Add custom RLE decoder support

The RLE file is directly generated from LVGL standard bin file using script rle_compress.py.
On firmware, RLE file is decompressed before passing to LVGL standard builtin decoder.

The compression ration is depent on image content. Below statistics come from a watch project show RLE compression is usefull.

The `CompressRation` in below image is actually `space saving ration`, and most of images can save >70% space .

output

This custom RLE file format works closely with LVGL bin file, and greatly improve decoder speed. It's ready to use upon decompress. The decompress function is also optimized for `indexed8` color format, which is the most commonly used one for simple icons.

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by W-Mai** [comment]
LGTM

**Comment by kisvegabor** [comment]
Thank you, it look good! Does it support a specific RLE standard?


Let's wait until the parallel rendering branch is merged, as it will overwrite a lot of things. I'm already fixing the MicroPython examples.

**Comment by XuNeo** [comment]
> Thank you, it look good! Does it support a specific RLE standard?

This one is not compliant with any standard, just to keep it simple as lvgl `bin` file.
I think we can add a decoder for files like `tga` if standard is needed.


> Let's wait until the parallel rendering branch is merged, as it will overwrite a lot of things. I'm already fixing the MicroPython examples.

I see that is on going so I tend to merge to release/v8.3. If it's not appropriate, let's wait until master branch is ready.

**Comment by kisvegabor** [comment]
We add only bugfixes and no new features to v8.3, but I've just merged `feat/parallel-rendering` to `master` so let's target master with this change. 

A lot of things were changed in the organization of rendering, so let me know if you have any questions.

**Comment by XuNeo** [comment]
Not stale. Need to rebase to master branch.

**Comment by kisvegabor** [comment]
Not stale.

**Comment by XuNeo** [comment]
I'll update the patch when image header structure and builtin bin image decoder on master branch is settled.

**Comment by XuNeo** [comment]
Currently working on lvgl builtin image decoder enhancement. Will come back to RLE when it's finished. Expect to start the work 2'nd week of October.

**Comment by XuNeo** [comment]
Not stale

**Comment by XuNeo** [comment]
Need to add some tests. Will do it this week.

**Comment by XuNeo** [comment]
Hi @kisvegabor , 
Could you help to review the code? I have added test case. Thank you.

**Comment by kisvegabor** [comment]
Hi @XuNeo,

I've looked into from a high level point of view without trying to understand the details of RLE decoding. It looks really great! 

Just 2 notes:
1. It seems the cache is not used. Is it intentional?
2. Please add a docs page where the logic of the custom RLE decoding is explained.

**Comment by XuNeo** [comment]
> 1. It seems the cache is not used. Is it intentional?

Yes, I'm still not sure how it relates to build-in bin image decoder. So, I left it for another patch.

> 2. Please add a docs page where the logic of the custom RLE decoding is explained.

Done

**Comment by kisvegabor** [comment]
> Yes, I'm still not sure how it relates to build-in bin image decoder. So, I left it for another patch.

I see. It would be really great if we could make any image cached one-by-one even with the built-in decoder.

I'll merge it, but just thinking aloud: 
There are 2 cases:
- Cache the decoded image: we can have a flag in the `lv_image_header_t` to tell if it should be cached. And if so, the built in decoder handles the caching. Useful for RLE, or any bin image stored e.g. in an SD card.
- Cache the compressed image: I'm not sure if it makes sense. E.g. cache the compressed PNG image because it's slow to read to fast to decode? I think this scenario doesn't need to be handled. 

What do you tink?

**Pull request merged**
