### PR TITLE
fix(label): do not add DOT when the width of label is enough

### PR DESCRIPTION
**Pull request by xaowang96**
### Description of the feature or fix

When the width of the label is enough, there is no need to add DOT at the end of its text.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Can you add an example to reproduce the issue this PR solves?

**Comment by xaowang96** [comment]
Here is the code and running results.

```C
void lvgl_test(void)
{
    lv_obj_t* screen = lv_scr_act();
    lv_obj_set_style_bg_color(screen, lv_color_black(), 0);

    lv_obj_t* text = lv_label_create(screen);
    lv_label_set_long_mode(text, LV_LABEL_LONG_DOT);
    lv_label_set_text(text, "Hello World");
    lv_obj_set_size(text, 400, 30);
    lv_obj_set_style_text_color(text, lv_color_white(), 0);
    lv_obj_set_style_text_font(text, &lv_font_montserrat_28, 0);
    lv_obj_set_style_text_align(text, LV_TEXT_ALIGN_LEFT, 0);
    lv_obj_center(text);

    lv_obj_set_style_border_color(text, lv_color_hex(0xFF0000), 0);
    lv_obj_set_style_border_width(text, 1, 0);
    lv_obj_set_style_border_opa(text, LV_OPA_100, 0);
}
```
截屏2021-12-17 上午11 17 24

 But if the height of the label is enough, the performance is different.

```C
lv_obj_set_size(text, 400, 40);
```

截屏2021-12-17 上午11 21 07

**Comment by xaowang96** [comment]
> Can you add an example to reproduce the issue this PR solves?

The comment above reproduced the problem.

**Comment by kisvegabor** [comment]
There dots because the height of the object is too small, and LVGL things that the text can't fit vertically to the object and adds dots to indicate the missing lines. 

It's more visible with:
```c
    lv_label_set_text(text, "Hello World 1\n"
                             "Hello World 2\n"
                             "Hello World 3\n"
                             "Hello World 4\n");
     lv_obj_set_size(text, 300, 65);
```

**Comment by xaowang96** [comment]
> There dots because the height of the object is too small, and LVGL things that the text can't fit vertically to the object and adds dots to indicate the missing lines.
> 
> It's more visible with:
> 
> ```c
>     lv_label_set_text(text, "Hello World 1\n"
>                              "Hello World 2\n"
>                              "Hello World 3\n"
>                              "Hello World 4\n");
>      lv_obj_set_size(text, 300, 65);
> ```

This is correct for multiple lines of text, but if there is only one line of text, it may be better to show the complete text as much as possible.

**Comment by kisvegabor** [comment]
I agree and pushed a commit to make it behave like this.

**Pull request closed without merging**
