### PR TITLE
Add lv example list 2

### PR DESCRIPTION
**Pull request by Karijn**
### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by Karijn** [comment]
in the c example all command buttons are removed from the group using
    lv_group_remove_obj(btn);

    btn = lv_list_add_btn(list2, LV_SYMBOL_SHUFFLE, "Shuffle");
    lv_obj_add_event_cb(btn, event_handler_swap, LV_EVENT_ALL, NULL);
    lv_group_remove_obj(btn);

i couldn't find a MP version of lv_group_remove_obj()

**Comment by amirgon** [comment]
> i couldn't find a MP version of lv_group_remove_obj()

Did you try `lv.group_remove_obj(btn)`?

It's not a member of  `lv.group_t` since `lv_group_remove_obj` doesn't receive `lv_group_t*` as its first argument. I think it could be nicer if it did.

**Comment by kisvegabor** [comment]
Looks good to me. Is it ready to merge?

**Comment by Karijn** [comment]
as far as i know, its ready and complete

**Comment by kisvegabor** [comment]
Merging then, thank you! :slightly_smiling_face:

**Pull request merged**
