### PR TITLE
fix(arc): add missing private include

### PR DESCRIPTION
**Pull request by Pavi92**
include of ../../core/lv_obj_private.h was missing

### CODE REVIEW

**Comment by kisvegabor** [comment]
I wonder how could the CI compile it then? @liamHowatt could you take a deeper look?

**Comment by Pavi92** [comment]
I think its because of the include order in lv_arc.c 

lv_obj_private.h is included before lv_arc_private.h and therefore lv_obj_t is known.

**Comment by Pavi92** [comment]
> I wonder how could the CI compile it then? @liamHowatt could you take a deeper look?
I think its because of the include order in lv_arc.c

lv_obj_private.h is included before lv_arc_private.h and therefore lv_obj_t is known.

But when includig lv_arc.h in a user source file then the definition of lv_obj_t is not known because the include is missing in lv_arc_private.h

**Review by liamHowatt — DISMISSED** [review]
Yes, that should be the cause. Thank you. I think it would be a good idea to:

1. All lv_x.c files with an lv_x_private.h should have the lv_x_private.h as the first include.
2. After building with the changes from 1, all the issues like the one you found should be revealed in the build errors.

I will do it after this PR, or you are welcome to do it in this PR but only if you want to.

<hr>

Also, for your change, I think the new include you added should go after `#include "lv_arc.h"` but it's not critical.

**Comment by liamHowatt** [comment]
Wow, thanks for doing it!

After your changes, it was confirmed by the build system that widgets other than `arc` also had the missing `lv_obj_private.h` so I added all of those.

There was also a nasty circular dependency issue with `lv_draw.h`. It's because `lv_draw.h` includes `lv_draw_*.h` which include `lv_draw.h`.

Thank you very much!

@kisvegabor, you can see what I did in my commit to fix the circular dependency. Do you think it'd be better to have a `lv_draw_all.h` which includes all the draw primitive headers? Similar to `lv_types.h`.

**Comment by Pavi92** [comment]
You're welcome

**Review by kisvegabor — COMMENTED** [review]
I think it's fine as it is. It's unlikely that we add new draw task types in the near future. 

Thank you for both of you! 🙂

**Review by kisvegabor — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
