### PR TITLE
Improve preload animation

### PR DESCRIPTION
**Pull request by AloyseTech**
Hi,

This is a proposition for improving the animation of the lv_preload object : 

Current animation : 
lv_preload-anim_current

Improved animation : 
lv_preload-anim_improvement

Let me know if I should make additional change.

### CODE REVIEW

**Comment by embeddedt** [comment]
Can you add an option to enable or disable this? Otherwise it looks really good!

**Comment by AloyseTech** [comment]
What's better, a define or an API function to set the animation style ? I don't know if the API can be done without too much modification since the animation pointer are not saved (are they even destroyed when the object is deleted?).

**Comment by kisvegabor** [comment]
I prefer the API. It's possible that the user wants preloaders with different animations and if later `lv_preload` will be an ancestor a new object type the API will provide more control.

I've just noticed that I left these lines in `lv_preload.h`: https://github.com/littlevgl/lvgl/blob/dev-5.3/lv_objx/lv_preload.h#L45 My intention was to add an API too but finally, I didn't use this enum. IMO using an enum is quite flexible and extendable to select the desired animation type/behavior. 

Yes, the animations are destroyed in `lv_obj_del`.

You can delete the animations without having their pointer:
- `lv_anim_del(preload, NULL)` delete all animation of `preload`
- `lv_anim_del(preload, lv_obj_set_x)` delete the animation of `preload` which uses `lv_obj_set_x`

**Comment by AloyseTech** [comment]
I've added the getter/Setter api for the animation type. I'm using the previously unused enum.

**Comment by kisvegabor** [comment]
Merged, thank you very much!

I've just added `LV_PRELOAD_DEF_ANIM` to `lv_conf_templ.h`

**Pull request merged**
