### PR TITLE
feat(vg_lite): reduce unnecessary path quality settings

### PR DESCRIPTION
**Pull request by FASTSHIFT**
Set the default path quality to HIGH to avoid aliasing. The current rendering speed bottleneck is no longer GPU.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
>  The current rendering speed bottleneck is no longer GPU.

Is it memory, CPU, or LVGL overhead now?

**Comment by kisvegabor** [comment]
cc @uLipe

**Comment by FASTSHIFT** [comment]
> > The current rendering speed bottleneck is no longer GPU.
> 
> Is it memory, CPU, or LVGL overhead now?

Currently, in our application scenario, the CPU is the performance bottleneck. Using the [GPU idle flush](Currently, in our application scenario, the CPU is the performance bottleneck, especially when the component complexity is high.
Using the GPU idle flush mechanism can make the GPU and CPU run in parallel.) mechanism can make the GPU and CPU run in parallel.

**Review by XuNeo — APPROVED** [review]
Can we keep it as a configuration option in case we need it later.

**Review by uLipe — COMMENTED** [review]
I like the idea, but as @XuNeo mentioned, this option could be a choice that can be selected in the lv_conf.h at build time, please notice using high quality paths tends to increase the current consumption which is not desired for some battery powered applications, so I think users might wanted this option could be selectable at least in build time to avoid them to go into the LVGL source tree and modify it by themselves,.

**Comment by FASTSHIFT** [comment]
> Can we keep it as a configuration option in case we need it later.

I would like to consider introducing configuration items only when there is a clear demand. Currently, image quality has a higher priority.

**Comment by FASTSHIFT** [comment]
The current modification does not affect the current rendering efficiency, because the previous drawing layer (such as draw arc, draw letter) code will actively set the quality to high. This modification only sets the default rendering quality to high, so that the drawing layer code can be less.

**Review by liamHowatt — APPROVED** [review]
Are you sure `path->base.quality` isn't uninitialized in some cases?

**Comment by FASTSHIFT** [comment]
> Are you sure `path->base.quality` isn't uninitialized in some cases?

Yes, path creation and destruction are unified interfaces.

**Pull request merged**
