### PR TITLE
Adds macro to lv_obj_style_gen.h

### PR DESCRIPTION
**Pull request by kdschlosser**
A macro was missing that would stop a compiler from defining function bodies more than once.

### CODE REVIEW

**Comment by kdschlosser** [comment]
I added the following to the script as well.

```python
HEADING = f'''
/*
 **********************************************************************
 *                            DO NOT EDIT
 * This file is automatically generated by "{os.path.split(__file__)[-1]}
 **********************************************************************
 */

'''
```

I will put that at the top of 
lv_obj_style_gen.h
lv_obj_style_gen.c
lv_style_gen.c
lv_style_gen.h

I also added the same kind of macros to lv_style_gen.h in the auto generation script and also manually in the file.

**Comment by kisvegabor** [comment]
Thank you, makes sense!


Please run [style_api_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/style_api_gen.py) and push the changes to see the generated files :slightly_smiling_face:

**Comment by kdschlosser** [comment]
OK you should be all set sir.

**Comment by kisvegabor** [comment]
All looks good! Thank you., Kevin.

**Comment by kdschlosser** [comment]
no worries m8

**Pull request merged**
