### PR TITLE
Dev 6.1 Minor fixes

### PR DESCRIPTION
**Pull request by pete-pjb**
Dev 6.1 Minor fixes

lv_draw_arc.c -> line 218
Removed unsed fast_atan2() function which appears to have been moved to lv_math.c as lv_atan2() function.

lv_font_heb_16.c -> line 1
Fixed inconsistent include path.

lv_label.c -> line 734
Added (char*) cast to const char* variable 'txt' to silence compiler warning when LV_USE_BIDI is disabled.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thanks @pete-pjb !

It seems the whole `lv_draw_arc.c` is changed due to [white space changes](https://github.com/littlevgl/lvgl/pull/1263/files#diff-c09138a28ebcbd1aae75aee0118d4d1f). However, I don't see what type of whitespaces have changed. Line ending? Tab/space?

**Comment by pete-pjb** [comment]
Hmmm,

It might have been due to me editing files outside of eclipse in wordpad... Sorry!

Would you like me to redo changes and resubmit using eclipse editor?

**Comment by embeddedt** [comment]
I'm guessing that @pete-pjb's editor automatically reformatted the whole file.

Probably the easiest solution is to merge the pull request into a temporary branch, rerun `clang-format`, and then squash merge the temporary branch into `dev-6.1`.

If you want to see the changes without whitespace: https://github.com/littlevgl/lvgl/pull/1263/files?utf8=%E2%9C%93&diff=unified&w=1

**Comment by pete-pjb** [comment]
I will close this pull request and submit a new one to make life easier. I will use eclipse to edit the files this time, I have also spotted another issue which I will add to the new pull request.

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
> I will close this pull request and submit a new one to make life easier.

Okay, thanks!

**Pull request closed without merging**
