### PR TITLE
Add spinbox object

### PR DESCRIPTION
**Pull request by AloyseTech**
This PR is for creating a new object type : lv_spinbox. It can be used to enter numeral value (int or float) and display numeral value as well in a given range. Each digit is editable.

This is a work in progress and I'm happy to discuss about this idea here.

Exemple : 
lv_spinbox

Test code : 
```C
lv_obj_t * spinbox;

static lv_res_t btnmAction(lv_obj_t * btnm, const char *txt)
{
	if(strncmp(txt, "<", 1) == 0)
		lv_spinbox_step_previous(spinbox);
	else if(strncmp(txt, ">", 1) == 0)
		lv_spinbox_step_next(spinbox);

	return LV_RES_OK;
}


static void focusStyleMode(lv_style_t * style)
{
	style->text.color = LV_COLOR_ORANGE;
}

static void editStyleMode(lv_style_t * style)
{
	style->text.color = LV_COLOR_LIME;
}

void testSpinBox()
{
	lv_obj_t * screen = lv_scr_act();

	static lv_style_t screenStyle;
	lv_style_copy(&screenStyle, &lv_style_plain);
	screenStyle.body.radius = 0;
	screenStyle.body.padding.hor = 0;
	screenStyle.body.padding.ver = 0;
	screenStyle.body.padding.inner = 0;
	screenStyle.body.border.width = 0;
	screenStyle.body.shadow.width = 0;
	screenStyle.body.main_color = LV_COLOR_MAKE(0x56,0x56,0x56);
	screenStyle.body.grad_color = LV_COLOR_MAKE(0x44,0x44,0x44);
	lv_obj_set_style(screen, &screenStyle);

	static lv_style_t spinBoxStyle;
	lv_style_copy(&spinBoxStyle, &lv_style_pretty_color);
	spinBoxStyle.text.font = &code_new_roman_digit_bold_80;//&dejavu_bold_80;
	spinBoxStyle.text.color = LV_COLOR_MAKE(0xF0, 0xF0, 0xF0);
	spinBoxStyle.body.border.width = 0;
	spinBoxStyle.body.padding.ver = 0;
	spinBoxStyle.body.padding.hor = 0;
	spinBoxStyle.body.padding.inner = 0;
	spinBoxStyle.body.empty = true;

	static lv_style_t spinBoxCursorStyle;
	lv_style_copy(&spinBoxCursorStyle, &spinBoxStyle);
	spinBoxCursorStyle.text.color = LV_COLOR_YELLOW;

	spinbox = lv_spinbox_create(screen, NULL);
	lv_spinbox_set_style(spinbox, LV_SPINBOX_STYLE_BG, &spinBoxStyle);
	lv_spinbox_set_style(spinbox, LV_SPINBOX_STYLE_CURSOR, &spinBoxCursorStyle);
	lv_obj_set_size(spinbox, LV_HOR_RES, 80);
	lv_obj_align(spinbox, NULL, LV_ALIGN_IN_TOP_LEFT, 4, 0);

	lv_obj_t * label = lv_label_create(screen, NULL);
	lv_obj_align(label, spinbox, LV_ALIGN_OUT_BOTTOM_LEFT, 0, 0);
	lv_label_set_text(label, "^^^ This is a spinbox ^^^\n"
							 "Orange means focused\n"
							 "Green means edition\n"
							 "Yellow shows active digit\n"
							 "Encoder set digit value\n"
							 "Encoder click switch digit");

	lv_obj_set_size(label, LV_HOR_RES, 140);
	lv_label_set_style(label, &lv_style_pretty_color);
	lv_label_set_align(label, LV_LABEL_ALIGN_CENTER);

	lv_group_t * g = lv_group_create();
	lv_group_add_obj(g, spinbox);
	//lv_group_add_obj(g, ta);
	//lv_group_set_editing(g, true);
	lv_indev_set_group(encoder_indev, g);
	lv_group_set_style_mod_cb(g, focusStyleMode);
	lv_group_set_style_mod_edit_cb(g, editStyleMode);

	lv_obj_t * btnm = lv_btnm_create(screen, NULL);
	static const char * btnmText[] = {"\221SET", "\221<", "\221>", "\221DONE", ""};
	lv_btnm_set_map(btnm, btnmText);
	lv_obj_set_size(btnm, LV_HOR_RES, 20);
	lv_obj_align(btnm, screen, LV_ALIGN_IN_BOTTOM_LEFT, 0, 0);
	lv_btnm_set_action(btnm, btnmAction);

	lv_scr_load(screen);
}
```

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

I tested the new object and it worked fine! With this, you are the first in LittelvGL's community who created an entirely new object type! Congratulations! :tada: :tada: :tada: 

A few comments:
1. To keep LittlevGL small in code size `double` types are not used. I'd prefer to remove `..._double()` function to keep this advantages.
2. Instead of `//` comments `/*  */` should be used for consistency. (I replaced them)
3. Can you add `lv_spinbox_increment/decrement` API functions? It would mean a great interface for  `+` and `-` buttons if a touchpad is used.   
4. The API functions should be added to `lv_spinbox.h` with comments.
5. We moved the documentation from littlevgl.com to GitHub: https://github.com/littlevgl/lvgl/wiki Now it's everyone can edit and improve it. I'm sure that you can explain the best how your object works. So can you create the brief documentation of the Spinbox object?

**Comment by AloyseTech** [comment]
Hi,

I will remove the double precision feature and add the increment/deplement api.

Have you tested the spinbox with a keyboard? Did you find strange behavior?

I will also try to make the documentation page on the wiki.

**Comment by kisvegabor** [comment]
Hi,

Thank you for the update!
I checked the new code and added:
- Some formatting updates
- `lv_spinbox_set_step` API function
- `lv_spinbox_set/get_style` functions as inline, using `lv_ta_set/get_style`

I also made some tests with keyboard. The current way is perfect with an encoder, but IMO for a keyboard the following would be more usable:
- LEFT/RIGHT: left digit
- UP/DOWN: increment/decrement
- ENTER: call an action?

To achieve this we need to know the type of the triggering indev:
```c
lv_hal_indev_type_t indev_type = lv_indev_get_type(lv_indev_get_act());
```

And depending on the type different things can be done in `LV_SIGNAL_CONTROLL`.
What do you think?

**Comment by kisvegabor** [comment]
Maybe for keyboard an `ENTER` action and for encoder, a `value change` would be reasonable. But for consistency, I vote for the value change action.

**Comment by kisvegabor** [comment]
I've tested the new features and merged it into `dev-5.3`. Thank you very much!

Please, don't forget to deal with the documentation when you will have some time.

**Comment by AloyseTech** [comment]
Thanks. Yes I’ll work on it on the next days

**Pull request merged**
