### PR TITLE
lv_sys dir

### PR DESCRIPTION
**Pull request by aenchevich**
Adding lv_sys directory, providing an (operating-) system-dependent init framework and a generic POSIX system implementation of it. Adding in there:
 - a signals init and handling code for POSIX systems;
 - a set of debug/trace macros with a terminal-based implementation. Users could provide their own implementations of them (e.g. outputting to a remote system via syslog, etc.). The macros resolve to noop by default in release builds.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thank you very much!

I have a few questions/remarks:
1. I tried to include `<features.h>` to an STM32 project (arm gcc) and it didn't find it. Maybe it is not available in all compiler like e.g. `<stdint.h>`? I also found that people have some trouble with `<features.h>` using MinGW.
2. `debug.h` uses some "extra" features like variable argument list. Once I removed all stdlib functions (like sprintf) from LittlevGL to make possible to compile it in < 80 kB size. We should avoid the use of these features for the small size. (some embedded devices has < 256 kB flash)
3. Should the macros like `DBG_V` or `EXIT_ERR`  be placed inside the LittelvGL functions to give some info?  And can you mention some use cases where/how `lv_sys_posix_generic` could work?  (I have limit knowledge about signals and other other "deep" Linux things so forgive me is I don't see the trivial advantages of it :) )
4. With some guy we have talked about a better "debug interface" for LittlevGL. Our vision was to add an option to register a "debug print" callback which will be called by LittelvGL when something happens. 
And with some defines in lv_conf.h the "DEBUG_LEVEL" can be adjusted.

If I understood well it would be a great update for pc_simulator using the mentioned "debug print" interface. Although this interface is not implemented yet but there is no obstacle to do it.

**Comment by kisvegabor** [comment]
Finally, I added the basics of a log system. It is in the `dev-5.2` branch. I introduced it [here](https://github.com/littlevgl/lvgl/issues/82#issuecomment-403194456)

Of course, the log interface can be changed and extended but I would prefer something simple like this. 

My vision is:
1. Extends `lv_log` with some macros or functions if required to make it more flexible.
2. Move `lv_sys` (in any form) to the PC simulator and implement an example use of an advanced, high-level debug/log interface. (using lv_log)

What do you think?

**Comment by aenchevich** [comment]
My short answer is:  
a) moving lv_sys out of lvgl is a good decision but making it a part of pc_simulator is not; 
b) choosing tu use lv_sys+logging levels is probably equally good a decision as using my proposed lv_debug code so in the end the important thing is that now there is a working logging facility in LittlevgL;
c) lv_log IMO should be part of lv_sys.

A more detailed answer follows:
Regarding lv_log: I still think that the logging facilities available for the user depend on the system and hence the logging functions should be a part of lv_sys. How it is implemented is not really that important - I had some code which I know works so I suggested adding it. If lv_log is more suitable for this project then we use lv_log :)

Regarding lv_sys (and lv_log): I think that if the log system is intended to be incorporated permanently into the code and then enabled or disabled at compile time or even at run time via some mechanisms, then it is a dependency for all the other components. And then, it is probably a good decision for it to be in a separate repo, outside of lvgl. And since logging is system-dependent I think that lv_sys is a good place for it.

And I still think that lv_sys_init / deinit are needed as part of the LittlevgL application framework because they show (and even 'gently' force) the user to use a correct runtime flow and provide a common place certain calls which need to happen at given times. There fore pc_simulator should provide example how it is used, but the lv_sys code itself should not be limited to only pc_sim. It should be a separate repo available to the other submodules.

**Comment by kisvegabor** [comment]
> And since logging is system-dependent I think that lv_sys is a good place for it.

The important thing here is, LittlevGL is a graphics library and not an OS. So speaking about a logging system it's not a goal to use all the possible debug features of the under laying hardware/OS. You can handle the signals, hard faults, exceptions etc as you need depending on the possibilities of your system. My view about the `lv_log` to give information about the state of the graphics library.


lv_sys:
>  It should be a separate repo available to the other submodules.

In my opinion as it's hardware/OS/platform dependent so it should be implemented in the projects of [lv_borads](https://github.com/littlevgl/lv_boards) repo or in the PC simulator project.

**Comment by aenchevich** [comment]
Hi Gabor

As we both agreed that things like lv_sys and lv_log/lv_debug do not belong in lvgl I will close this pull request now :)

I also agree that "_LittlevGL is a graphics library and [..] it's not a goal to use all the possible debug features of the under laying hardware/OS. You can handle the signals, hard faults, exceptions etc as you need depending on the possibilities of your system_".

So really the only part of lv_sys that could be useful and universal to LittlevGL is the logging/debugging features. And that's how this whole lv_sys thing started actually.. I thought that we could have in LittlevGL something similar to DirectFB's DEBUG infrastructure, which can be enabled/disabled at compile time and at run-time via some switches and thus provide debugging/tracing features. Useful for development and debugging... not so useful for field software...

If in the future you decide that you need some repo for (Operating-)System-dependent initializations and functionality, then IMO its place should not be in pc_simulator nor in lv_boards but in a separate repo (like lv_drivers and lvgl).

Anyway, thanks for discussing, closing the issue now
:)

**Pull request closed without merging**
