### PR TITLE
Fix/compiler error on lv log warn msg

### PR DESCRIPTION
**Pull request by vwheeler63**
### Description of the feature or fix

fix(draw):  fix compiler error when LV_USE_LOG == 1

lv_draw_sw_letter() function had a LV_LOG_WARN() message that had syntax only legal when PRIX32 translates to a recognized string (sprintf format character "X").  However, the symbol PRIX32 is only implemented in the in the 'master' branch, not in 'release/v8.3' branch, causing PRIX32 to be an unrecognized symbol.

Handled by adding sprintf format character 'X' to end of string and removing PRIX32 symbol, simulating original intention in 'master' branch.

Note I thought it might be a courtesy to send this as a "fix/compiler_error_on_lv_log_warn_msg" branch from the "release/v8.3" branch in case that is more convenient to simply merge at a convenient point instead of going through possible conflicts.  Please let me know if that is not desired.

### CODE REVIEW

**Comment by vwheeler63** [comment]
I believe I have fixed the build error on the rp2 port now.

**Comment by kisvegabor** [comment]
Hi,

Thank you. We generate the change log automatically, so please remove it from the PR.

**Comment by C47D** [comment]
Not stale. @kisvegabor can we merge it and then I send the fix for the CI issue or should I cherry pick the commits and send them in a new PR?

**Comment by vwheeler63** [comment]
Ouch -- sorry I let this go so long.  (I'm new to PRs -- learning though.)  I think I made an error by wiping out this branch in my fork, so the branch I had this in has been wiped out.  My apologies.

**Comment by vwheeler63** [comment]
I see this issue has already been addressed by others.

**Pull request closed without merging**
