### PR TITLE
arch/cmsis pack enhancement

### PR DESCRIPTION
**Pull request by bbkarim**
### Description of the feature or fix

- LVGL 9.0.0-dev
- Refactor CMSIS PDSC file
  * Reworked components to get more granulated sub-groups
  * Renamed LVGL-Essential into LVGL-CORE Clean-up its files
  * Add missing hearder files
  * Include only selected headerfiles by CMSIS pack configuration
  * Clean-up LVGL-CORE files
  * Updated GPU STM32-DMA2D to support STM32U5xx
  * Remove compilation warnings
  * Add more widgets and demos

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
PLEASE do NOT mix patches about different topics into one PR.
This PR worths at least 7 separated small PRs. 


@kisvegabor

**Comment by GorgonMeducer** [comment]
> Renamed LVGL-Essential into LVGL-CORE Clean-up its files

Are there any special reason that the name 'LVGL-CORE' is better than 'LVGL-Essential'? 

When I first created the LVGL cmsis-pack, I choose this name. I know it is no better than core, but the same there is no special reason that core is better than essential. 

Suppose you have contributed some code to an opensource project and someone later rename it without practice reason, will you be comfortable? 

@kisvegabor sorry for disturbing, do we have any suggestions about similar situations when doing contribution?

**Comment by bbkarim** [comment]
> > Renamed LVGL-Essential into LVGL-CORE Clean-up its files
> 
> Are there any special reason that the name 'LVGL-CORE' is better than 'LVGL-Essential'?
> 
> When I first created the LVGL cmsis-pack, I choose this name. I know it is no better than core, but the same there is no special reason that core is better than essential.
> 
> Suppose you have contributed some code to an opensource project and someone later rename it without practice reason, will you be comfortable?
> 
@GorgonMeducer I'm sorry for that, I'll of course revert that if you're feeling uncomfortable.
I forgot to rise this change so we can discussed it together...

I renamed that into CORE because it is including the **src/core** files. But you're right, it is still including more files from **src/darw**, **src/font**, **src/hal** and **src/misc**
I'm wondering if we need to split that too into sub-groups so we can disable fonts for example...

> @kisvegabor sorry for disturbing, do we have any suggestions about similar situations when doing contribution?

**Comment by bbkarim** [comment]
I'm closing this.

Everything is now implemented is separated PR as needed.

Below PR are covering the same here but after first review done here:

- #3923 
- #3924 
- #3925 
- #3926 
- #3927 
- #3928 
- #3929 

Review will continue inside these PR.

**Pull request closed without merging**
