### PR TITLE
chore: introduce typos

### PR DESCRIPTION
**Pull request by szepeviktor**
### Description of the feature or fix

Run typos in a new workflow.

From https://github.com/lvgl/lvgl/pull/4684#issuecomment-1773992316

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thanks for the prompt action! :slightly_smiling_face: 

It just came to my mind that it'd would be great to have a simple script like `spellcheck.sh` or `spellcheck.py` that can be  run by the developers before pushing, so that they can find the issue locally. 

Is it something complicated add?

**Comment by szepeviktor** [comment]
> Is it something complicated add?

Tell them to type: `typos` :)
It is a single binary.

**Comment by szepeviktor** [comment]
But wait!
https://github.com/crate-ci/typos/blob/master/docs/pre-commit.md 👀

**Comment by szepeviktor** [comment]
You find the antidotes here for all problems I've ever met.
https://github.com/szepeviktor/byte-level-care/tree/master/.github/workflows

**Comment by kisvegabor** [comment]
We already have a [pre-commit-config.yaml](https://github.com/lvgl/lvgl/blob/master/.pre-commit-config.yaml) file, however when I added `typos`, made a typo in the source code, commit it, `typos` was installed automatically, but it also passed. 

Am I missing something?

**Comment by szepeviktor** [comment]
I have zero clue how pre-commit works internally. (mainly because I do not trust developer computers)
What is the output of the `typos` command after you've made a typo?

**Comment by kisvegabor** [comment]
> mainly because I do not trust developer computers

That's what a true devops expert says :smile: 

It turned out `valueasd` passes `typos` but it worked for `valeu`. 
So I've updated the precommit hook here: https://github.com/lvgl/lvgl/commit/8057f215b8e874664110858d7e77d61b518f527f

---

Just one question: am I correct to assume that this CI will simply fail on typos and one can check the log to see the actual issue?

**Comment by szepeviktor** [comment]
> It turned out `valueasd` passes

`typos` is working from a list of known typos. `valueStip` will be caught.
(does not catch unknown words)

> am I correct to assume that this CI will simply fail on typos and one can check the log to see the actual issue?

Yes.

> The commit will be aborted if there is a nonzero exit code.

You can use GitHub CLI on your machine to peak into GHA: https://cli.github.com/

**Comment by szepeviktor** [comment]
Closing in favor of running pre-commit.

**Pull request closed without merging**
