### PR TITLE
Try to fix the various issue found in animation module again

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

There are reports that https://github.com/lvgl/lvgl/pull/2063 make these regression:
https://github.com/lvgl/lvgl/issues/2066
https://github.com/lvgl/lvgl/issues/2070
The new PR should fix these issue.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@embeddedt could you try the new PR with simulator?

**Comment by embeddedt** [comment]
#2066 is still a problem. The button background doesn't change back properly.

**Comment by xiaoxiang781216** [comment]
@embeddedt I found the root cause:
https://github.com/lvgl/lvgl/pull/2073/commits/a248f6f9a1d8dc03ca5a572715adf035f0f7b838
Could you try again?

**Comment by embeddedt** [comment]
Looks like it works now; thank you for the fix!

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thank you!

I'm closing the related issues.

**Comment by xiaoxiang781216** [comment]
@kisvegabor can you merge this PR now?

**Comment by kisvegabor** [comment]
Upps, sometimes I forget to click the merge button :sweat_smile:

**Pull request merged**
