### PR TITLE
fix: the latest lvgl version of msinttypes in rt-thread caused compil…

### PR DESCRIPTION
**Pull request by hydevcode**
…ation errors

A clear and concise description of what the bug or new feature is.

Fixed an issue where the latest lvgl version of msinttypes in rt-thread caused compilation errors

微信图片_20240924140930

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by hydevcode** [comment]
@mysterywolf  @kurisaW 可以帮我看看，关于这个msinttypes头文件的问题，这样改可以吗

**Review by kisvegabor — DISMISSED** [review]

**Review by liamHowatt — DISMISSED** [review]

**Comment by mysterywolf** [comment]
I will review this PR, and once it is ready, I will mark it.

**Review by mysterywolf — APPROVED** [review]

**Comment by mysterywolf** [comment]
@kisvegabor ready to be merged thanks!

**Review by liamHowatt — APPROVED** [review]

**Comment by liamHowatt** [comment]
Fixes #6919

**Comment by mysterywolf** [comment]
@liamHowatt @kisvegabor This PR is ready, could you merge it? Thanks

**Review by kisvegabor — APPROVED** [review]

**Pull request merged**
