### PR TITLE
Handle USE_LV_ANIMATION being disabled in lv_page and lv_sw

### PR DESCRIPTION
**Pull request by embeddedt**

### CODE REVIEW

**Comment by kisvegabor** [comment]
I think following https://github.com/littlevgl/lv_examples/pull/16#issuecomment-445968460 would be cleaner. So with `USE_LV_ANIMATION == 0` animation related function should behave as if `anim_time` would be 0 i.e. animation would be disabled by the user.

Do you agree?

**Comment by embeddedt** [comment]
@kisvegabor Sounds good. I will make the adjustments tomorrow.

**Comment by embeddedt** [comment]
Pretty sure this is ready now.

**Comment by kisvegabor** [comment]
@embeddedt What about my earlier comment about this lines in `lv_sw_on/off_anim`? 

```c
#if USE_LV_ANIMATION
    if(lv_sw_get_anim_time(sw) > 0)lv_sw_anim_to_value(sw, LV_SWITCH_SLIDER_ANIM_MAX);
    else
#endif
	lv_slider_set_value(sw, LV_SWITCH_SLIDER_ANIM_MAX);
```

See my proposal here: [sw_anim.patch.zip](https://github.com/littlevgl/lvgl/files/2683408/sw_anim.patch.zip)

**Comment by embeddedt** [comment]
@kisvegabor Good point. I initially thought there was no point removing those lines but since the functions do nothing anyway, I will apply your patch.

**Comment by kisvegabor** [comment]
Great, thank you!

**Pull request merged**
