### PR TITLE
added example lv_example_anim_timeline_1.py

### PR DESCRIPTION
**Pull request by uraich**
### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation
Added the MPY equivalent of lv_example_anim_timeline_1.c

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you!

**Comment by amirgon** [comment]
@kisvegabor something is wrong with the docs on https://docs.lvgl.io/master/overview/animation.html#animation-timeline:

image

**Comment by kisvegabor** [comment]
I've just fixed it. Should work when the docs are rebuilt.

**Comment by kisvegabor** [comment]
Now it's working but the object size needs to be finetuned.

**Comment by amirgon** [comment]
Code appears now and MP simulator works, but preview looks wrong:

image

**Comment by kisvegabor** [comment]
I've fixed it.

**Comment by kisvegabor** [comment]
image

**Pull request merged**
