### PR TITLE
fix(label): The label setting for long clips will exceed the edges.

### PR DESCRIPTION
**Pull request by lhdjply**
### Description of the feature or fix

fix(label): The label setting for long clips will exceed the edges.

### test code
```c
void test_label(void)
{
  lv_obj_t *label1=lv_label_create(lv_screen_active());
  lv_label_set_long_mode(label1,LV_LABEL_LONG_WRAP);
  lv_label_set_text(label1,"123456789");
  lv_obj_set_size(label1,70,25);
  lv_obj_align(label1,LV_ALIGN_CENTER,0,-100);
  lv_obj_set_style_bg_color(label1,lv_palette_main(LV_PALETTE_BLUE), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(label1,LV_OPA_100, LV_PART_MAIN);

  lv_obj_t *label2=lv_label_create(lv_screen_active());
  lv_label_set_long_mode(label2,LV_LABEL_LONG_DOT);
  lv_label_set_text(label2,"123456789");
  lv_obj_set_size(label2,70,25);
  lv_obj_align(label2,LV_ALIGN_CENTER,0,-50);
  lv_obj_set_style_bg_color(label2,lv_palette_main(LV_PALETTE_BLUE), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(label2,LV_OPA_100, LV_PART_MAIN);

  lv_obj_t *label3=lv_label_create(lv_screen_active());
  lv_label_set_long_mode(label3,LV_LABEL_LONG_SCROLL);
  lv_label_set_text(label3,"123456789");
  lv_obj_set_size(label3,70,25);
  lv_obj_center(label3);
  lv_obj_set_style_bg_color(label3,lv_palette_main(LV_PALETTE_BLUE), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(label3,LV_OPA_100, LV_PART_MAIN);

  lv_obj_t *label4=lv_label_create(lv_screen_active());
  lv_label_set_long_mode(label4,LV_LABEL_LONG_SCROLL_CIRCULAR);
  lv_label_set_text(label4,"123456789");
  lv_obj_set_size(label4,70,25);
  lv_obj_align(label4,LV_ALIGN_CENTER,0,50);
  lv_obj_set_style_bg_color(label4,lv_palette_main(LV_PALETTE_BLUE), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(label4,LV_OPA_100, LV_PART_MAIN);

  lv_obj_t *label5=lv_label_create(lv_screen_active());
  lv_label_set_long_mode(label5,LV_LABEL_LONG_CLIP);
  lv_label_set_text(label5,"123456789");
  lv_obj_set_size(label5,70,25);
  lv_obj_align(label5,LV_ALIGN_CENTER,0,100);
  lv_obj_set_style_bg_color(label5,lv_palette_main(LV_PALETTE_BLUE), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(label5,LV_OPA_100, LV_PART_MAIN);
}
```
### fix before
屏幕截图 2024-02-19 173202
### fix after
屏幕截图 2024-02-19 173122
### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by XuNeo** [comment]
Hi, 
Are those changes to reference image necessary?

**Comment by lhdjply** [comment]
> Hi, Are those changes to reference image necessary?

This is the CI error request changed after running main.py. It should be that lv_label.c is used in these pictures, so the pictures have changed

**Comment by kisvegabor** [comment]
LVGL adds an extra draw area for the labels because some italic fonts are highly out of their box.  See 

image

If we clip the text to the widget are we clip these letters too if they are at beginning or end of a line. It's not that obvious but even "normal" fonts can overflow their boxes a little. That's why you see the differences in the reference images. 

As workaround I suggest:
- always use the widget coordinates for clipping vertically
- use the widget coordinates horizontally too in case of `LV_LABEL_LONG_CLIP`.

**Comment by lhdjply** [comment]
The difficulty feels a little high, temporarily turn off this pr

**Pull request closed without merging**
