### PR TITLE
fix(list) scroll list when button is focused using LV_KEY_NEXT/PREV

### LINKED ISSUE #2060: lv_list not scrolling with LV_KEY_PREV and LV_KEY_NEXT
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug

lv_list is not scrolling to the selected item when using LV_INDEV_TYPE_KEYPAD and LV_KEY_PREV and LV_KEY_NEXT.  Selection is off screen

### To Reproduce
```c
void demo(void)
{
    lv_group_t* g = lv_group_create();

    lv_indev_drv_t kb_drv;
    lv_indev_drv_init(&kb_drv);
    kb_drv.type = LV_INDEV_TYPE_KEYPAD;
    kb_drv.read_cb = keyboard_read;
    lv_indev_t * kb_indev = lv_indev_drv_register(&kb_drv);
    lv_indev_set_group(kb_indev, g);

    lv_obj_t* list = lv_list_create(lv_scr_act(), NULL);
    lv_obj_set_size(list, LV_HOR_RES, LV_VER_RES);

    char text[16];
    for (int i = 0; i < 26; i++) {
        sprintf(text, "Item %c", 'A' + i);
        lv_obj_t* list_btn = lv_list_add_btn(list, NULL, text);
        lv_group_add_obj(g, list_btn);
    }
}
```

### Expected behavior
Tabbing through the list should result in the list being scrolled, I.E. "Item I" being shown once it is selected.

A little off topic, but I think the way the arrow keys work with LV_INDEV_TYPE_KEYPAD is a little broken.  On screen keyboard cannot be used with such a setup.

### Screenshots or video
Screenshot at 2021-02-07 19-33-59

Even better, this repository has a simulator setup that shows the problem, using the Up/Down arrow keys:  `https://gitlab.jkent.net/odroid-go/golauncher`

Be sure to --recurse-submodules !

Just `cd` to simulator and `make run`

### PR DESCRIPTION
**Pull request by embeddedt**
### Description of the feature or fix

Fixes #2060

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by jkent** [comment]
I seem to be getting an intermittent crash now with this change.  Here is a backtrace:

```
(gdb) bt
#0  0x0000555555620f08 in work_mem_int ()
#1  0x00005555555765a9 in lv_obj_set_pos (
    obj=0x555555621420 <work_mem_int+6496>, x=-4096, y=-45)
    at ../components/lvgl/lvgl/src/lv_core/lv_obj.c:799
#2  0x0000555555576697 in lv_obj_set_y (
    obj=0x555555621420 <work_mem_int+6496>, y=-45)
    at ../components/lvgl/lvgl/src/lv_core/lv_obj.c:829
#3  0x000055555559a86b in anim_task (param=0x55555561fac8 <work_mem_int+8>)
    at ../components/lvgl/lvgl/src/lv_misc/lv_anim.c:477
#4  0x00005555555a1296 in lv_task_exec (task=0x55555561fac8 <work_mem_int+8>)
    at ../components/lvgl/lvgl/src/lv_misc/lv_task.c:386
#5  0x00005555555a0c80 in lv_task_handler ()
    at ../components/lvgl/lvgl/src/lv_misc/lv_task.c:121
#6  0x00005555555f970b in Gui::Task (pvParameters=0x0) at ../main/gui.cpp:77
#7  0x00005555555fb541 in main (argc=1, argv=0x7fffffffe0b8) at src/main.cpp:68
```

**Comment by embeddedt** [comment]
I've been thinking about this for a few days. I'm not sure how my change is causing your crash (which appears to be memory corruption). It seems more likely that the change in behavior has revealed another bug somewhere.

**Comment by jkent** [comment]
Okay.  I did run into an issue where I was running out of room with the lvgl memory allocator in my project.  It might be related to that.  I will test again within the next few days.

**Comment by jkent** [comment]
I did a test with a merge to master just now.  Seems to work okay!

**Review by kisvegabor — APPROVED** [review]
Looks good!

**Pull request merged**
