### PR TITLE
feat(lv_rb_t): add red black tree to lvgl

### PR DESCRIPTION
**Pull request by W-Mai**
### Description of the feature or fix

example:

```cpp
typedef struct {
    int key1;
    int key2;

    int value;
} my_rb_node;

lv_rb_compare_res_t rb_compare(const void* a, const void* b)
{
    my_rb_node* node_a = (my_rb_node*)a;
    my_rb_node* node_b = (my_rb_node*)b;

    if (node_a->key1 != node_b->key1) {
        return (node_a->key1 > node_b->key1)? 1 : -1;
    }

    if (node_a->key2 != node_b->key2) {
        return (node_a->key2 > node_b->key2)? 1 : -1;
    }

    return 0;
}

void rb_test()
{
    lv_rb_t rb;
    lv_rb_init(&rb, rb_compare, sizeof(my_rb_node));

    my_rb_node node1 = { 1, 1, 1 };
    my_rb_node node2 = { 1, 2, 2 };
    my_rb_node node3 = { 1, 3, 3 };
    my_rb_node node4 = { 1, 4, 4 };

    lv_rb_node_t* tmp_node;
    tmp_node = lv_rb_insert(&rb, &node1);
    memcpy(tmp_node->data, &node1, sizeof(my_rb_node));
    tmp_node = lv_rb_insert(&rb, &node2);
    memcpy(tmp_node->data, &node2, sizeof(my_rb_node));
    tmp_node = lv_rb_insert(&rb, &node3);
    memcpy(tmp_node->data, &node3, sizeof(my_rb_node));
    tmp_node = lv_rb_insert(&rb, &node4);
    memcpy(tmp_node->data, &node4, sizeof(my_rb_node));

    my_rb_node* node = (my_rb_node*)lv_rb_find(&rb, &node1)->data;
    printf("node1: %d\n", node->value);
    node = (my_rb_node*)lv_rb_find(&rb, &node2)->data;
    printf("node2: %d\n", node->value);
    node = (my_rb_node*)lv_rb_find(&rb, &node3)->data;
    printf("node3: %d\n", node->value);
    node = (my_rb_node*)lv_rb_find(&rb, &node4)->data;
    printf("node4: %d\n", node->value);

    // remove
    lv_rb_remove(&rb, &node1);
    lv_rb_remove(&rb, &node2);
    lv_rb_remove(&rb, &node3);
    lv_rb_remove(&rb, &node4);
}

```

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Where can we use it in LVGL?

**Comment by W-Mai** [comment]
Where rb acceleration can be used in lvgl:

1. The image cache can use multiple keys (color, path, blend, etc.) to quickly search for images that have been cached in the image cache.
2. Freetype font cache can also use multiple keys (size, unicode) for fast glyph data search

At present, the first two solutions use linear search. When the order of magnitude of the content is greater than 10, rb can show obvious search advantages.

**Comment by kisvegabor** [comment]
I see, thank you! 

Could you integrate into the cache to not just add  it on its own?

**Comment by W-Mai** [comment]
FASTSHIFT has pushed some commits using this lv_rb_lru cache manager which is base on this lv_rb module

https://github.com/lvgl/lvgl/pull/4670
https://github.com/lvgl/lvgl/pull/4669

**Comment by W-Mai** [comment]
not stale

**Comment by XuNeo** [comment]
Let's wait for Gabor to finalize cache for SDL texture and then come back to this PR.
As discussed with @W-Mai  after meeting, we may do need to support multiple cache backends since LRU, LFU etc. are targeted for specific use cases and could coexistent. 

RB tree or linear seach are just mehtods to store the cache entry, but cache aging algorithms are different.

**Comment by XuNeo** [comment]
As mentioned in https://github.com/lvgl/lvgl/pull/4669, we need to support multiple cache instances and multiple cache aging policy, together with cache entry storing methods.

**Comment by kisvegabor** [comment]
I see, these are really 2 different things. 

As I mentioned in our meeting in the cache entries we should  have a separate source (e.g. "myimage.png") and data (the data we actually cache) and we need to have an `lv_cache_invalidate_by_src(src, LV_CACHE_SRC_TYPE_POINTER/STRING);` function to invalidate all entries with the same source. 

So all cache instances need to be added into a linked list to allow traversing them in `lv_cache_invalidate_by_src`. 


So finally what modules should have their own cache instance?
- one for all images?
- one for all fonts?
- one for SDL and similar draw units?

**Comment by kisvegabor** [comment]
I've just pushed the SDL renderer. It's still limited but conceptually works. See the commit message. https://github.com/lvgl/lvgl/commit/2f3e8d40667d27bb9bb56778439787426cae3d9f

It contains the cache update too. Please take a look at [lv_cache.h](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_cache.h) and let me know if something not clear. The cache ended up being quite complicated so don't hesitate to ask :slightly_smiling_face:

**Pull request merged**
