### PR TITLE
Replace Arabic letters with UNICODE names

### PR DESCRIPTION
**Pull request by szepeviktor**
### Description of the feature or fix

Found some UNICODE characters in the source code and replace them with UNICODE code points/names.

https://www.compart.com/en/unicode/block/U+0600

### CODE REVIEW

**Comment by kisvegabor** [comment]
What issue does it solve?

**Comment by szepeviktor** [comment]
I cannot answer this question.
The Integrity workflow alerted me that there are not printable ASCII characters in that file.

**Comment by szepeviktor** [comment]
> What issue does it solve?

I usually generate issues to prevent problems. "Work for the future".

**Comment by kisvegabor** [comment]
Please send a PR to integrate your "Integrity workflow" so that we can better see what issues it solves.

**Comment by szepeviktor** [comment]
These are all the steps Integrity has.
The sole purpose is to have zero stray characters in the repository.
But people usually tolerate stray characters **and** bump into bugs!

Check file names
Check file permissions
Check for byte order mark (BOM)
Search for characters outside the printable ASCII range
Check EditorConfig configuration
Check adherence to EditorConfig
Look for TAB characters in the middle of the line 🐌
Look for multiple space characters in the middle of the line 🐌
Search for TODO-s and FIXME-s 🐌
Remove blank first lines and multiple blank lines 🐌
Search for conflict markers 🐌
Check for ignored files in the index 🐌
Check exported files

**Comment by kisvegabor** [comment]
Sounds great! Let's integrate it and see how it works in the practice.

**Comment by szepeviktor** [comment]
@kisvegabor Here are the results.
Please decide what I should do in the next PR.

1) file names outside `[-.0-9A-Z_a-z]`
```
FontAwesome5-Solid+Brands+Regular.woff
demo_render_image normal_opa_128.png
demo_render_image normal_opa_255.png
```

2) there are some RTL characters in the source code - like Arabic and Pinyin letters

3) astyle would like to kill duplicate blank lines 👉🏻  #4768
I had to run it 3 times not to produce new changes!!!

4) midline (stray) TAB characters (not at the beginning of the line)

5) `docs/flyers/LVGL-Chinese-Flyer.pdf` is recognized by git as a text file

6) 82 TODO-s waiting to become a GitHub issue

7) `tests/.gitignore` ignores .bin files but there are many committed
`tests/src/test_files/binimages/*.bin`

8) many development files are exported: `git archive HEAD` / GitHub ZIP

**Comment by kisvegabor** [comment]
> file names outside [-.0-9A-Z_a-z]+

I can fix these.

> there are some RTL characters in the source code - like Arabic letters

We will have many non ASCII characters in font files too. I think we should disable this check. 

> astyle would like to kill duplicate blank lines 

:+1: 

> midline (stray) TAB characters (not at the beginning of the line)

I guess we can replace those with space without any issues. 

> docs/flyers/LVGL-Chinese-Flyer.pdf is recognized by git as a text file

What can we do with that?

> 82 TODO-s waiting to become a GitHub issue

Let's ignore those for now.

> tests/.gitignore ignores .bin files but there are many committed
tests/src/test_files/binimages/*.bin

We should ignore bin file in a more local way. Let's remove it from `.gitignore` and add in folders on demand later.

> many development files are exported: git archive HEAD / GitHub ZIP

What does it mean exactly?

> pre-commit did a lot of changes, please see commits in https://github.com/lvgl/lvgl/pull/4768
pre-commit run --verbose --all-files --show-diff-on-failure
These "pre-commit" commits contain fixes from typos - I think false positives.

Can see alist of these changes only?

> typos is waiting to be configured/misspellings fixed (e.g. "collapted")

They need to be fixed for sure.

**Comment by szepeviktor** [comment]
It was nice to learn about Arabic letters.

**Pull request closed without merging**
