### PR TITLE
fix(font): load_glyph calculate the wrong size(one byte short) of last glyph

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

Fix the off by one bug

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@kisvegabor and @embeddedt, could you take a look, my change looks reasonable, but can't pass CI check:(.

**Comment by kisvegabor** [comment]
I'm not entirely sure but I think `glyph_length` is rather "glyph count" therefore there is an off by one issue.

**Comment by xiaoxiang781216** [comment]
> I'm not entirely sure but I think `glyph_length` is rather "glyph count" therefore there is an off by one issue.

Yes, there is off by one bug, I finally found why my change break the CI and fix it. Please take a look, @kisvegabor.

**Comment by kisvegabor** [comment]
Looks good, thank you!

**Pull request merged**
