### PR TITLE
lv_img_cache: fix buffer overrun

### PR DESCRIPTION
**Pull request by pabigot**
Reset the cache entry, not the pointer to the cache entry.

### CODE REVIEW

**Comment by embeddedt** [comment]
Nice catch! Merging.

**Comment by pabigot** [comment]
I can't really claim credit; pc_simulator_sdl_eclipse complained:
```
In file included from /usr/include/string.h:494:0,
                 from /mnt/devel/external/lvgl-pc_simulator_sdl_eclipse/lvgl/src/lv_draw/../lv_misc/lv_area.h:16,
                 from /mnt/devel/external/lvgl-pc_simulator_sdl_eclipse/lvgl/src/lv_draw/lv_img_decoder.h:25,
                 from /mnt/devel/external/lvgl-pc_simulator_sdl_eclipse/lvgl/src/lv_draw/lv_img_cache.h:16,
                 from /mnt/devel/external/lvgl-pc_simulator_sdl_eclipse/lvgl/src/lv_draw/lv_img_cache.c:9:
In function ‘memset’,
    inlined from ‘lv_img_cache_open’ at /mnt/devel/external/lvgl-pc_simulator_sdl_eclipse/lvgl/src/lv_draw/lv_img_cache.c:121:13:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:71:10: warning: ‘__builtin___memset_chk’ writing 72 bytes into a region of size 8 overflows the destination [-Wstringop-overflow=]
   return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by embeddedt** [comment]
I'll have to add that warning to my collection. :wink: Seems like it could come in handy sometime.

Thank you for the tip!

**Comment by pabigot** [comment]
You're welcome.  It probably came from `-Wall`; I built with the existing Makefile which seems to have some nice strictness to it---the only obvious thing to add would be `-Werror` so it couldn't scroll by and be missed.

**Comment by kisvegabor** [comment]
Strange, I've already fixed it in 135c119
It seems it was somehow overwritten.

Anyway, thank you for the fix!

**Pull request merged**
