### PR TITLE
Added tab button position LEFT and RIGHT

### PR DESCRIPTION
**Pull request by seyyah**
Example code part is

```c
lv_tabview_set_btns_pos(tv1, LV_TABVIEW_BTNS_POS_LEFT);
lv_tabview_set_btns_pos(tv1, LV_TABVIEW_BTNS_POS_RIGHT);
```

Detailed example is https://github.com/littlevgl/lv_examples/blob/dev-6.0/lv_tests/lv_test_objx/lv_test_tabview/lv_test_tabview.c#L123-L238 .

:warning: **Limitations**: It is not possible yet to switch tab button position from/to top/bottom from/to left/right at runtime.

## :camera: Screenshot
Demo: 

lv_test_tabview_2

## :link: References
1. Forum discussion topic: https://forum.littlevgl.com/viewtopic.php?f=12&t=83&p=726#p726
2. Another PR#897: Added tab button position left or right: https://github.com/littlevgl/lvgl/pull/897
3. Suggestion: Tab view - vertical tabs https://github.com/littlevgl/lvgl/issues/808
4. [Suggestion] adjust the btn position of tabview https://github.com/littlevgl/lvgl/issues/80
5. Add ability to change TabView Buttons Location https://github.com/littlevgl/lvgl/issues/147

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]

**Comment by embeddedt** [comment]
>  It is not possible yet to switch tab button position from/to top/bottom from/to left/right at runtime.

Is this limitation still true? When I look at the code I don't see any configuration option.

**Comment by seyyah** [comment]
> > It is not possible yet to switch tab button position from/to top/bottom from/to left/right at runtime.
> 
> Is this limitation still true? When I look at the code I don't see any configuration option.

Example scenerio: 

1. tabview created
2. button position is set LV_TABVIEW_BTNS_POS_TOP
3. add tabs
4. ERROR: when switch to LV_TABVIEW_BTNS_POS_LEFT or LV_TABVIEW_BTNS_POS_RIGHT button position, visual problem arises on the btnms

**Comment by embeddedt** [comment]
> ERROR: when switch to LV_TABVIEW_BTNS_POS_LEFT or LV_TABVIEW_BTNS_POS_RIGHT button position, visual problem arises on the btnms

That could be a problem. @kisvegabor, what's your opinion?

**Comment by seyyah** [comment]
The source of the problem is in L251-L268 of lv_tabview.c. I think we can solve by cleaning extra `\n` when switch from LV_TABVIEW_BTNS_POS_LEFT or LV_TABVIEW_BTNS_POS_RIGHT  to LV_TABVIEW_BTNS_POS_TOP or LV_TABVIEW_BTNS_POS_BOTTOM.

https://github.com/littlevgl/lvgl/pull/1027/files/a9036eb6b1e1c975f7157894e1f7f22e24f60784#diff-ae65b984e85966200aa843b9ecb17d51R251

**Comment by kisvegabor** [comment]
I noticed a bug which is visible on the screenshots too. With LEFT/RIGHT the width of the all pages except the first is screen sized and not reduced by `btns width`. I fixed it, see my last commit. (The rest of the commits are just to update to the latest `dev-6.0`)

> The source of the problem is in L251-L268 of lv_tabview.c. I think we can solve by cleaning extra \n when switch from LV_TABVIEW_BTNS_POS_LEFT or LV_TABVIEW_BTNS_POS_RIGHT to LV_TABVIEW_BTNS_POS_TOP or LV_TABVIEW_BTNS_POS_BOTTOM.

It clearly comes from here. However, I think we can live with this limitation if you don't have time to fix it.

**Comment by seyyah** [comment]
> I think we can live with this limitation if you don't have time to fix it.

@kisvegabor, it is not crucial bug.  So I add "fixme note" at the `lv_tabview.c`. We'll fix ASAP.

**Comment by kisvegabor** [comment]
@seyyah  Fine.

Form my side it's ready to merge. Do you still want to add something?

**Comment by seyyah** [comment]
No I don't want to add anything

**Comment by kisvegabor** [comment]
Okay, merged! Thank you very much!

**Comment by EvgeniiaDZ** [comment]
Hello! I have some question about tabview) How can I set it unclickable? The function lv_obj_set_click doesn't work.

**Comment by embeddedt** [comment]
@EvgeniiaDZ 
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

**Pull request merged**
