### PR TITLE
fix(v8) handle most compiler warnings

### PR DESCRIPTION
**Pull request by embeddedt**
### Description of the feature or fix

More warnings fixed!

I can now compile and run v8 on STM32.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by embeddedt** [comment]
Some notes:

* There are a lot of places where object value set functions are being casted to/from `lv_anim_exec_xcb_t`. I think this isn't safe to do without an extra veneer function, because `lv_anim_value_t` is `int16_t` and many of these functions accept `int32_t`. I fixed the ones I saw but this may be done in other places.
* Unnamed union/struct members are forbidden by ISO C. I added names to these and used find-and-replace to adjust the code base.
* The gauge widget is still in the codebase, but doesn't seem to compile properly anymore since it depends on linemeter. I assume this can be removed?

**Comment by kisvegabor** [comment]
Thank you! I've just removed the gauge widget (it's replaced by the more flexible meter)

**Comment by kisvegabor** [comment]
I wonder if changeing `lv_anim_value_t` to `int32_t` could help with `lv_anim_exec_xcb_t`.

**Comment by kisvegabor** [comment]
Thinking about it more using a larger type seems equally dangerous.

**Comment by embeddedt** [comment]
There are other issues with this style of cast. For example, `lv_bar_set_value` takes three parameters, one being whether to use animations or not. Casting it to `lv_anim_exec_xcb_t` means that only the first two parameters will get passed, and the third will have an undefined value.

I think the only reliable solution is to not cast object functions to `lv_anim_exec_xcb_t` at all and use helper functions instead.

**Comment by xiaoxiang781216** [comment]
> I wonder if changeing `lv_anim_value_t` to `int32_t` could help with `lv_anim_exec_xcb_t`.

Yes, int32_t is better choice for lv_anim_exec_xcb_t

**Comment by kisvegabor** [comment]
> I think the only reliable solution is to not cast object functions to lv_anim_exec_xcb_t at all and use helper functions instead.

I agree.

However now `lv_anim_value_t` is `lv_coord_t` which is usually `int16_t`. It limits the animations to `-32k..32k` values. So independently of the csting issue replacing `lv_anim_value_t` with a simple `int32_t` can be reasonable.

**Comment by embeddedt** [comment]
Sounds good.

**Comment by kisvegabor** [comment]
Done here: 757c18e4

**Pull request merged**
