### PR TITLE
Add Kconfig

### PR DESCRIPTION
**Pull request by C47D**
Lets add the first revision of the Kconfig file so others can review it!

I hope @embeddedt, @kisvegabor, @acassis, @puzrin, @vanwinkeljan, etc can take a look at it and discuss if it needs further editing, I've been testing this Kconfig file with the ESP-IDF framework.

I will make this a draft so we can mark it as ready after the review. This PR needs #1870 to be merged.

### CODE REVIEW

**Review by embeddedt — COMMENTED** [review]
When I read through this, I feel like it would make more sense (and take up less space) to make `LV_COLOR_TRANSP_HEX` user-accessible and get rid of the predefined color options. With the current setup you are basically forced to choose one of the built-in colors which doesn't feel right. I think the same thing applies to `LV_THEME_DEFAULT_<PRIMARY/SECONDARY>_COLOR`.

If someone wants to use one of the built-in colors they can always look it up in `lv_misc/lv_color.h`; you could add a comment mentioning that.

Just my two cents.

**Comment by kisvegabor** [comment]
I agree with @embeddedt. The [current pattent](https://github.com/lvgl/lvgl/blob/master/src/lv_conf_kconfig.h#L33-L37) allow hex color and it should be enough.

It just came to my mind that for Zephyr we have discussed an `LV_CONFIG_MINIMAL` option which turns off "everything" by default. 
E.g.
```
        config LV_USE_ANIMATION
            bool "Enable the Animations."
              default n if LV_CONFIG_MINIMAL
              default y if !LV_CONFIG_MINIMAL
```

I'm not sure whether the `if` is required for `default y` or not.

**Comment by Ouss4** [comment]
I think it'd be better to have one Kconfig per subfolder and have a top-level one sourcing all of them (and possibly adding other options). This will be easy to manage and extend.

**Comment by Ouss4** [comment]
I see now the concern.
Did you look into something similar to [this](https://github.com/apache/incubator-nuttx/blob/03e9f936d90c77037f28a30b58b717c7f389d71f/Kconfig#L8-L11)?
A variable can be defined from the user's Makefile to point to the correct "top-level" and then passed to kconfig* utils. (See [here](https://github.com/apache/incubator-nuttx/blob/03e9f936d90c77037f28a30b58b717c7f389d71f/tools/Makefile.unix#L61-L65)  and [here](https://github.com/apache/incubator-nuttx/blob/03e9f936d90c77037f28a30b58b717c7f389d71f/tools/Makefile.unix#L485-L504))
I don't know how much of a burden adding that variable could be on other projects, but from NuttX that shouldn't cause any issue.  At least none that I'm aware of.
I also remember that we had a [discussion](https://lists.apache.org/thread.html/r5b65661cf714e9dbcfa47367f28f6ba5124642d0a93d3239fe0e5e34%40%3Cdev.nuttx.apache.org%3E) about this several weeks ago.  Since LVGL is downloaded at build time, I see one awkward maneuver needed to be able to directly use the Kconfig file (but that should be needed only for the first build).
(This is actually not related to the current discussion but just a comment that occurred to me, which maybe belongs to NuttX's mailing list.)

**Comment by C47D** [comment]
@embeddedt Did you meant something like 0bf58c9? If so I will do the same for both PRIMARY and SECONDARY theme colors.

**Comment by C47D** [comment]
Hi @Ouss4,

Yes, but I don't remember if I was able to make it work, please correct me if I'm wrong but with:
```
config APPSDIR
	string
	option env="APPSDIR"
```

You're getting the value of APPSDIR environment variable and storing it into APPSDIR, which is an string.

---

I wasn't aware of that discussion thread, I will try to take a look at it this weekend, thanks for the link 😃

**Comment by acassis** [comment]
Hi @C47D, I also think that using a main Kconfig and "source" to other Kconfig in subfolder is a better approach and make maintenance easier. I can talk with ESP-IDF team here at Espressif to helps on it too. On NuttX side it will be easier, because currently NuttX already follow this strategy.

**Comment by Ouss4** [comment]
> Hi @Ouss4,
> 
> Yes, but I don't remember if I was able to make it work, please correct me if I'm wrong but with:
> 
> ```
> config APPSDIR
> 	string
> 	option env="APPSDIR"
> ```
> 
> You're getting the value of APPSDIR environment variable and storing it into APPSDIR, which is an string.
> 
> I wasn't aware of that discussion thread, I will try to take a look at it this weekend, thanks for the link

Yes that's what that one does.  Then using that variable the Kconfig is sourced: `source "$APPSDIR/Kconfig"`

@acassis I think we should revive the discussion in NuttX's mailing list to come to a solution on how this one would be integrated.

**Comment by C47D** [comment]
Hi,

Maybe we can do something like the Zephyr project,



Those files can be generated from the menus on the current Kconfig file.

@Ouss4 maybe the envvar can be named `LVGL_HOME` or something like that, what do you think?

**Comment by acassis** [comment]
Hi @Ouss4 yes I agree!

**Comment by C47D** [comment]
@acassis @Ouss4 When using ESP-IDF we include the following headers that contain the generated symbols:
```c
#if defined ESP_PLATFORM
#include "sdkconfig.h"
#include "esp_attr.h"
#endif
```

Is there a way to identify the NUTTX framework so we can do something similar for Nuttx?

**Comment by embeddedt** [comment]
I believe they define `__NuttX__`.

**Comment by Ouss4** [comment]
> @acassis @Ouss4 When using ESP-IDF we include the following headers that contain the generated symbols:
> 
> ```c
> #if defined ESP_PLATFORM
> #include "sdkconfig.h"
> #include "esp_attr.h"
> #endif
> ```
> 
> Is there a way to identify the NUTTX framework so we can do something similar for Nuttx?


> I believe they define `__NuttX__`.

Yes when building a custom toolchain using NuttX's buildroot or also some boards define it too in their Makefile.

But is there anything speficic for each project to do so?

From the NuttX side I'm still thinking on how to directly include the Kconfig file.

NuttX downloads a tar version at build time. But it's in the config phase, which comes before the build, where the Kconfigs are generated.

**Comment by vanwinkeljan** [comment]
@kisvegabor 
> I'm not sure whether the if is required for default y or not.

On the `LV_CONFIG_MINIMAL` there is no need to add the `default n` cases as by default KConfig useses `n`.
So it follows the same thinking as in `Zephyr`; keep the minimal set of configs by default and if I'm not mistaken this originates from the linux kernel to avoid a mess in the configs and potential config issues.

So only the `default y` cases needs to changed to `default y if !LV_CONFIG_MINIMAL`.

Maybe another approach here could be to disable everything by default (actually just remove the defaults) and provide a toplevel default config file?

@C47D 
`but I don't know how Kconfig files are used in other projects like Zephyr`

As far as I know the Kconfig files for modules `Zephyr` depends on are copied into `Zephyr` modules directory due to the fact that Kconfig should still work even if the modules are not present.

**Comment by kisvegabor** [comment]
@vanwinkeljan 
> So only the default y cases needs to changed to default y if !LV_CONFIG_MINIMAL.

Thanks for the explanation.

@C47D 
Seemingly it wouldn't make the Kconfig files much larger. Do you agree with adding it as @vanwinkeljan suggested?

**Comment by acassis** [comment]
Hi @C47D and @kisvegabor just to share here what we discussed at NuttX mailing list: for now we just need to use the Kconfig from LVGL "as it is" and confirm it still working. Nothing will be need to be changed from NuttX side or LVGL side.

**Comment by C47D** [comment]
@kisvegabor sure, what options or configuration must be enabled and which disabled by default?

@acassis Hi, I haven't take a look at the Nuttx repo, with this Kconfig file you no longer need to use the `lv_config.h` file, everything (or most of it) is handled in both `lv_config_internal.h` and `lv_config_kconfig.h` files. Is it possible for you to test this and maybe report issues, if any?

**Comment by C47D** [comment]
Just saw the thread over your mailing list, we need to add:

```c
#ifdef __NuttX__
#include <nuttx/config.h>
#endif
```

were needed.

**Comment by kisvegabor** [comment]
@C47D I've just marked the required configs with `LV_CONF_MINIMAL` and added an include for the NuttX header file (https://github.com/lvgl/lvgl/commit/f42afb1c52e4522a445239a4746d30903e355ace)

**Comment by C47D** [comment]
Thanks for fixing the typo I did. I think `lv_conf_internal` also needs the Nuttx header.

**Comment by kisvegabor** [comment]
`lv_conf_internal.h` [includes](https://github.com/lvgl/lvgl/blob/master/src/lv_conf_internal.h#L12) `lv_conf_kconfig.h` so it will get the platform specific headers.

**Comment by C47D** [comment]
You're right, totally missed that.

**Comment by protobits** [comment]
Thank you @kisvegabor 
That include line should be enough if we ship your Kconfig file ourselves. This way our configuration system works the same as now and avoids the issue of not being able to configure until the package is downloaded (which is currently dependant on enabling LVGL in the config).
For all this to work, we would need to have a single Kconfig file from LVGL, or at least a series of Kconfig files that sit on the same directory, so that they can easily be placed outside the source directory during configuration phase.

**Comment by C47D** [comment]
@v01d , hi, do you use Kconfiglib to handle your Kconfig files? If so we could use the rsource extension and place all the Kconfig files in the LVGL root directory.

**Comment by protobits** [comment]
No, we use standard kconfig tool

**Comment by kisvegabor** [comment]
It seems to me projects use Kconfig in slightly different ways, so I'm in favor of monolithic Kconfig for maximal compatibility even at the cost of maintainability.

**Comment by C47D** [comment]
@kisvegabor is `LV_CONF_MINIMAL` meant to be a Kconfig configuration option or something like an environment variable?

**Comment by kisvegabor** [comment]
Good question. 
It'd be nice to let the user to configure the default behavior this way in Kconfig. 
For Zephyr is it good if they patch default `LV_CONF_MINIMAL=n` to `y`? (@vanwinkeljan)

**Comment by vanwinkeljan** [comment]
@kisvegabor 
> For Zephyr is it good if they patch default LV_CONF_MINIMAL=n to y? (@vanwinkeljan)

No problem in setting an extra KConfig flag

@C47D 

I did assume that `LV_CONF_MINIMAL` would be just a regular KConfig flag

**Comment by C47D** [comment]
Me too, but would symbols update their defaults when `LV_CONF_MINIMAL` is enabled or disabled?

**Comment by embeddedt** [comment]
> would symbols update their defaults when `LV_CONF_MINIMAL` is enabled or disabled?

As far as I know, defaults are only used if you don't already have a (def)config. Once you've run a Kconfig tool and saved your changes, defaults are ignored (except for new options not already in your config file).

**Comment by C47D** [comment]
I've fixed some issues and tested this branch on my ESP32 project and it compiles successfully, I don't have the hardware available right now so the hardware test will be done later this week.

I didn't used the `LV_CONF_MINIMAL` option tho.

**Comment by C47D** [comment]
@kisvegabor When trying to add Unscii 16 to the build I've noticed that `lvgl.h` is not being included the same way as in Unscii 8, this makes the project fail to build, I did the following to fix it:

```diff
diff --git a/src/lv_font/lv_font_unscii_16.c b/src/lv_font/lv_font_unscii_16.c
index 1d48427f..7b3f6934 100644
--- a/src/lv_font/lv_font_unscii_16.c
+++ b/src/lv_font/lv_font_unscii_16.c
@@ -1,4 +1,4 @@
-#include "lvgl/lvgl.h"
+#include "../../lvgl.h"
```

**Comment by kisvegabor** [comment]
@C47D 
Thanks, fixed here: https://github.com/lvgl/lvgl/commit/380df4578e5e8d2cae52978d1e358f3504266169

**Comment by C47D** [comment]
I've been testing this with a couple of displays I got, and it's been working as expected, so I'm going to mark it as ready for review so others can test it as well. I hope there's not a lot to fix so we can merge it.

**Comment by kisvegabor** [comment]
Great! I merge it then.
After tomorrow's release dev will be merged to master.

**Comment by kisvegabor** [comment]
The Kconfig file is now in master and will be released in 2 weeks. 

@C47D, thank you very much for this great improvement!

@ValentiWorkLearning, @v01d Could you make some initial tests on Zephyr and NuttX?

**Comment by protobits** [comment]
Hi @kisvegabor 
I started testing integration of Kconfig in NuttX. I'm looking at lv_conf_internal.h and notice that some configurations that we had set are not exposed via Kconfig. For example: CONFIG_LV_MEM_CUSTOM (and all related ones). Shouldn't these be added as well?

**Comment by protobits** [comment]
Also, maybe it would be better to have the top-level configs (such as resolution, transparency, color) also under a submenu. I think it is a bit more organized that way.

**Comment by protobits** [comment]
Also, not sure if I'm being over cautious but since we will be shipping your Kconfig as part of our repo, maybe it is better to add a license header to the file.

**Comment by kisvegabor** [comment]
> For example: CONFIG_LV_MEM_CUSTOM (and all related ones). Shouldn't these be added as well?

@C47D Are there any reason why is it missing? I assume it's not possible to set a custom malloc/free function via Kconfig but I think automatically selecting the default `malloc`, `free` if  `LV_MEM_CUSTOM = 1` is still useful.

> Also, maybe it would be better to have the top-level configs (such as resolution, transparency, color) also under a submenu. I think it is a bit more organized that way.

I agree. Just to sure, I mean [these options](https://github.com/lvgl/lvgl/blob/522e975a4eaccd897dae6fa058b6795ea9fbb7c6/Kconfig#L15-L100)

> Also, not sure if I'm being over cautious but since we will be shipping your Kconfig as part of our repo, maybe it is better to add a license header to the file

Good idea.

**Comment by C47D** [comment]
I didn't added it because of there are multiple options possible, so I kept the configuration used on the ESP32 project.

**Comment by kisvegabor** [comment]
> I didn't added it because of there are multiple options possible, so I kept the configuration used on the ESP32 project.

Multiple options for which config?

**Comment by protobits** [comment]
Ah, I was assuming they could be set as string configs but once they are strings the cannot be "unstringified". So I guess the value for these macros should be defined by the user in some other user-supplied header, right?

**Comment by protobits** [comment]
> I agree. Just to sure, I mean [these options](https://github.com/lvgl/lvgl/blob/522e975a4eaccd897dae6fa058b6795ea9fbb7c6/Kconfig#L15-L100)
> 

Yeap

**Comment by protobits** [comment]
> @C47D Are there any reason why is it missing? I assume it's not possible to set a custom malloc/free function via Kconfig but I think automatically selecting the default `malloc`, `free` if `LV_MEM_CUSTOM = 1` is still useful.

If the defaults are for POSIX values, for NuttX that would already be enough. There are other more custom definitions though, as the tick interface (which we use to avoid the need to tick LVGL).

**Comment by C47D** [comment]
> Ah, I was assuming they could be set as string configs but once they are strings the cannot be "unstringified". So I guess the value for these macros should be defined by the user in some other user-supplied header, right?

Yep, you're right. You can add some Nuttx specific ones in the lv_conf_kconfig file, or in your project makefile.

**Comment by C47D** [comment]
> Ah, I was assuming they could be set as string configs but once they are strings the cannot be "unstringified". So I guess the value for these macros should be defined by the user in some other user-supplied header, right?

Yep, you're right. You can add some Nuttx specific ones in the lv_conf_kconfig file, or in your project makefile.

**Comment by protobits** [comment]
I'd rather not have to modify files that are shipped with LVGL, otherwise we have to maintain a patch. But if we can define it from the Makefile I think that could be OK.

**Comment by vanwinkeljan** [comment]
@C47D  @kisvegabor Update from the zephyr site.

I got the it working for both the sample and tests cases. I did bump in to a few issues, one of them I parked (setting Arabic/Persian config gives a warning, which is treated as an error, but did not yet figure out where it comes from).

For now I only had the chance in testing it on a simulation environment but the sample generates more or less the expect result.

Could you guys have a look at following two changes sets, as to me it looks like they are bugs on the lvgl side:
https://github.com/vanwinkeljan/lvgl/commit/c9586d0e48ee5c79e1ad0d56a9e4a09b0030627e
https://github.com/vanwinkeljan/lvgl/commit/2d45251516ba364395dc0c6370d313fef094d277

Something else that I observed is that for the minimal config the material theme is still the default and a montserrat font is used by default pushing the ROM size to 130KB.

And then one final thing also zephyr uses some custom includes as the KConfig options can not be used, as stated by @v01d, I did just set the macro defines in the zephyr specific configuration head include file:
https://github.com/vanwinkeljan/zephyr/blob/lvgl_kconfig/lib/gui/lvgl/zephyr_lvgl_conf.h

For reference the two repos with the changes: 
https://github.com/vanwinkeljan/lvgl/tree/lvgl_kconf
https://github.com/vanwinkeljan/zephyr/tree/lvgl_kconfig

**Comment by C47D** [comment]
Hi @vanwinkeljan, thanks for the feedback. The `LV_COLOR_TRANSP_HEX` one is missing `_HEX` at the end of the symbol in the Kconfig file, c9586d0 is actually a good fix, I was defining `LV_CONF_SKIP` at ESP-IDF project level, that's why maybe I missed that one.

Using `LV_CONF_MINIMAL` is a bit more annoying to fix, as far as I know if we want the symbols that are disabled by the `LV_CONF_MINIMAL` to be actualy disabled we would need to 'hide' the prompt of said symbols, if the users would like to edit them they need to disable `LV_CONF_MINIMAL`. I was thinking more on disable those options by default on Kconfig and lv_conf_template files.

**Comment by C47D** [comment]
@vanwinkeljan I've opened #1917 for the updates on Kconfig, `lv_conf_internal.h` is an autogenerated file, we I've updated the script that generate it. Can you take a look at it?

**Comment by vanwinkeljan** [comment]
@C47D 

> @vanwinkeljan I've opened #1917 for the updates on Kconfig, lv_conf_internal.h is an autogenerated file, we I've updated the script that generate it. Can you take a look at it?

Changes look good to me and they work as expected

> Using LV_CONF_MINIMAL is a bit more annoying to fix, as far as I know if we want the symbols that are disabled by the LV_CONF_MINIMAL to be actualy disabled we would need to 'hide' the prompt of said symbols, if the users would like to edit them they need to disable LV_CONF_MINIMAL. I was thinking more on disable those options by default on Kconfig and lv_conf_template files.

Actually `LV_CONF_MINIMAL` is doing a perfect job for me, it just changes the defaults so that you will get a minimal build (by default). Then the user can select only the components he needs (either through menuconfig or via a defconf file). So no need to hide the symbols (for me) or change the behaviour of `LV_CONF_MINIMAL`.

The only problem that I did encounter with `LV_CONF_MINIMAL` is that some configs did not select the "minimal" config.
See commit https://github.com/vanwinkeljan/lvgl/commit/23cb92722f55e02376d02942cb90709ee67ac8db with some "fixes" to reduce the build size. The net result is that the zephyr lvgl sample ROM size is reduced from 130k to 97k.

One remaining remark `LV_CONF_MINIMAL`, I'm wondering if `LV_CONF_MINIMAL` should not be hidden?
It looks to me that the defaults of all symbols are only set the first time Kconfig runs so changing the value of `LV_CONF_MINIMAL` afterwards has no effect.


Update: just for the record did a run with `LV_CONF_MINIMAL` on the zephyr sample and the ROM usage is 150K in that case

**Comment by C47D** [comment]
Let's continue in the other PR.

**Comment by amirgon** [comment]
I'm starting to look at ESP32 Micropython + LVGL with Cmake.
This will use LVGL as ESP32 component with `CMakeLists.txt`.

However, Micropython with LVGL does not use Kconfig and still rely on `lv_conf.h`.

https://github.com/lvgl/lvgl/blob/84163749ec7c2de9c865d51d2eb27802f9f12033/Kconfig#L13-L18

I need to set `LV_CONF_SKIP` to "No" when building LVGL but I want to do it without changing LVGL sources or Kconfig so I could keep using LVGL as a git submodule.
Is there a way to pass some compile time definition `-DSOMETHING` to prevent skipping `lv_conf.h`?

**Comment by kisvegabor** [comment]
I don't really understand. If you don't want to use `Kconfig` the commands in the Kconfig file have no effect.

**Comment by amirgon** [comment]
> I don't really understand. If you don't want to use `Kconfig` the commands in the Kconfig file have no effect.

That's not true.
The Kconfig defaults apply, and by default `LV_CONF_SKIP` is true.
So by default when building LVGL as ESP32 component, the configuration on `lv_conf.h` is ignored.

I need `lv_conf.h` to be used so I have the following options:

- Use Kconfig to change `LV_CONF_SKIP` to `No`. But it doesn't make sense to ask the users to do this extra configuration step on an internal git submodule (LVGL) when building lv_micropython. In Micropython the users are not supposed to configure anything with Kconfig (for now).
- Not use `CMakeLists.txt` on LVGL root at all. That would work but misses the point of using the same build rules everywhere  for building LVGL
- Some other way to disable `LV_CONF_SKIP` from an external build script?

One thing that I liked about `lv_conf.h` is the fact that definitions are not "defined" or "undefined". Instead, definitions are always defined, but defined as "1" or "0" to enable/disable them. This is useful for overriding them (passing `-D` in the compiler command line).  
Unfortunately, Kconfig seems to be working with the defined" / "undefined" scheme which makes it harder to override configuration from an external build script.

Or maybe I'm missing something here? That's why I asked  "Is there a way to pass some compile time definition `-DSOMETHING` to prevent skipping lv_conf.h?"

**Comment by kisvegabor** [comment]
> That's not true.
The Kconfig defaults apply, and by default LV_CONF_SKIP is true.
So by default when building LVGL as ESP32 component, the configuration on lv_conf.h is ignored.

Ah, you are right.

I think it's reasonable to provide an option to disable the use of Kconfig. Seemingly it's enough to change [this line](https://github.com/lvgl/lvgl/blob/84163749ec7c2de9c865d51d2eb27802f9f12033/src/lv_conf_internal.h#L14) like this:
```c
#ifndef LV_KCONFIG_IGNORE
#  include "lv_conf_kconfig.h"
#endif
```

**Comment by amirgon** [comment]
> ```c
> #ifndef LV_KCONFIG_IGNORE
> ```

It's good but not enough.

`CMakeLists.txt` assumes that `lv_conf` is in the search path and therefore sets `LV_CONF_INCLUDE_SIMPLE`.

https://github.com/lvgl/lvgl/blob/04990aefe55b36b97359a52543d36b604f26d83a/CMakeLists.txt#L9

This is incompatible with `lv_conf.h` that is found one directory upper than LVGL.

https://github.com/lvgl/lvgl/blob/04990aefe55b36b97359a52543d36b604f26d83a/src/lv_conf_internal.h#L37-L41

We can fix that on `lv_conf_internal.h` or on `CMakeLists.txt`.
What do you suggest?

**Comment by xiaoxiang781216** [comment]
@C47D v8 merged to master one week ago, do you have any plan to update Kconfig?

**Comment by C47D** [comment]
Hi @xiaoxiang781216, sorry I've been really busy with work, is there a list of added and/or removed configuration options? I will open a new issue for Kconfig update.

**Pull request merged**
