### PR TITLE
fix(draw): fix compiler error in lv_draw_sw_transform.c

### PR DESCRIPTION
**Pull request by vwheeler63**
Compiler issues error on lv_color_t initializer {0} not yet converted to new initializer format:  _LV_COLOR_ZERO_INITIALIZER in argb_and_rgb_aa() function.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Than you! However we generate the changelog with script before release. So could you render that file?

**Comment by C47D** [comment]
Not stale. @kisvegabor can we merge it and then I send the fix for the CI issue or should I cherry pick the commits and send them in a new PR?

**Comment by C47D** [comment]
@kisvegabor This can be closed once #4612 gets merged

**Comment by kisvegabor** [comment]
https://github.com/lvgl/lvgl/pull/4612 is merged so I close it.

**Pull request closed without merging**
