### PR TITLE
Visual Studio 2019 compile errors

### PR DESCRIPTION
**Pull request by kolotoff**
Using LVGL inside C++ code causes errors, the first is:
lv_color.h(616,12): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
The same problem described here: https://forum.lvgl.io/t/visual-studio-2019-compile-errors/1379/15
This fix tested with Microsoft Visual Studio 2019 16.6.5 and IAR 8.50.5

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
Hi,

Thanks for the PR.

It's a little bit cumbersome but I can't imagine a better solution either.

Only one thing: please `#undef LV_COLOR_MAKE_TYPE_HELPER` when not required anymore.

**Comment by kolotoff** [comment]
It's impossible to #undef LV_COLOR_MAKE_TYPE_HELPER, because a lot of color defines like LV_COLOR_WHITE contains the LV_COLOR_MAKE macro, and other translation units uses these color macros.

**Comment by kisvegabor** [comment]
Ah, that's true. In this case please add an `_` prefix (`_LV_COLOR_MAKE_TYPE_HELPER`) to make autocomplete less noisy.

**Comment by kolotoff** [comment]
Done

**Comment by kisvegabor** [comment]
Thank you!

**Comment by zhwxChaos** [comment]
@kisvegabor 
[This problem still exists on STM32](https://forum.lvgl.io/t/how-to-be-compatible-with-c-on-the-stm32-platform/3240/3)

I have updated lvgl to V7.5.0

**Pull request merged**
