### PR TITLE
fix(codespace): enable builtin OBJID feature

### PR DESCRIPTION
**Pull request by kisvegabor**
### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by XuNeo — DISMISSED** [review]
Is something wrong with ID_AUTO_ASSIGN?

**Comment by kisvegabor** [comment]
If enabled it fails with:
```
/bin/ld: ./lvgl/src/core/lv_obj.o: in function `lv_obj_constructor':
/home/kisvegabor/projects/lvgl/eclipse-workspace/lv_port_pc_eclipse/Debug/../lvgl/src/core/lv_obj.c:390: undefined reference to `lv_obj_assign_id'
/bin/ld: ./lvgl/src/core/lv_obj.o: in function `lv_obj_destructor':
/home/kisvegabor/projects/lvgl/eclipse-workspace/lv_port_pc_eclipse/Debug/../lvgl/src/core/lv_obj.c:427: undefined reference to `lv_obj_free_id'
collect2: error: ld returned 1 exit status
```

**Comment by XuNeo** [comment]
I see. Let's enable `LV_USE_OBJ_ID_BUILTIN` instead.

**Review by FASTSHIFT — DISMISSED** [review]

**Comment by kisvegabor** [comment]
> I see. Let's enable LV_USE_OBJ_ID_BUILTIN instead.

It also works, and it'd be really better this way so people can use this feature out of the box.

**Review by XuNeo — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
