### PR TITLE
Don't squash - fix various issues reported from Visual Studio

### PR DESCRIPTION
**Pull request by kisvegabor**
### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by FASTSHIFT — APPROVED** [review]

**Review by liamHowatt — APPROVED** [review]
I tried hard to find a flag for either MSVC or Linux GCC that would catch this. MSVC's `/W4` unfortunately does not give a warning which we can promote to an error. GCC seems to only warn `-Woverflow` if the bitfield is too small for the unsigned representation :confused:

**Comment by liamHowatt** [comment]
Let's not merge until @MouriNaruto's approval.

**Comment by MouriNaruto** [comment]
I have tested the fix for lv_draw_sw_mask_private.h and the issue has been fixed, it's OK to merge.

> I tried hard to find a flag for either MSVC or Linux GCC that would catch this. MSVC's /W4 unfortunately does not give a warning which we can promote to an error. GCC seems to only warn -Woverflow if the bitfield is too small for the unsigned representation 😕

I also tried to find that but failed.

But in my opinion, I think maybe use the uint*_t for bitfield is better. For example, here is the screenshot for showing how to use the enum in bitfield members properly in Microsoft's Windows Driver Kit 7.1.0's hvgdk.h.

image

Kenji Mouri

**Comment by kisvegabor** [comment]
Merged, thank you all!

**Comment by liamHowatt** [comment]
Work has been done over the last little while to make enum bitfields use the enum type wherever we'd been using uint*_t for docs generation I think. Other than docs and binding generation, there's nothing else I know of blocking the use of uint*_t for enum bitfields.

**Pull request merged**
