### PR TITLE
Added extra keyboard mode to enable caps-lock defined as

### PR DESCRIPTION
**Pull request by pete-pjb**
LV_KB_MODE_TEXT_UC

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]

**Comment by embeddedt** [comment]
Is there a reason why you closed this?

**Comment by pete-pjb** [comment]
Sorry finger trouble... :-)

**Comment by pete-pjb** [comment]
Open again now...

**Comment by pete-pjb** [comment]
Sorry I haven't ever done any of this before, hopefully I have done it correctly!

Cheers,

Pete

**Comment by kisvegabor** [comment]
> Sorry I haven't ever done any of this before, hopefully I have done it correctly!

Perfect, thank you! :slightly_smiling_face: 

I'm just thinking about `LV_KB_MODE_TEXT_UPPER` might be more intuitive. What do you think?

**Comment by pete-pjb** [comment]
> > Sorry I haven't ever done any of this before, hopefully I have done it correctly!
> 
> Perfect, thank you! 🙂
> 
> I'm just thinking about `LV_KB_MODE_TEXT_UPPER` might be more intuitive. What do you think?

Totally agree...  Have pushed change... :-)

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
Merged, thank you! :slightly_smiling_face:

**Pull request merged**
