### PR TITLE
fix(docbuild):  Fix @file commands and guard macros.

### PR DESCRIPTION
**Pull request by vwheeler63**
Fix `@file` commands and guard macros in the following directories:

1.  LVGL root
2. ./src/

and specifically (for now) excluding ./demos/ and ./examples/.

Addresses part of issue #6480.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — APPROVED** [review]
Thank you Victor! It's nice that these error will be caught by the CI soon. 

As @kdschlosser recommended we should use a pattern like `_LV_THEME_MONO_H` to filter out these symbols for Doxygen. But it's for an other PR.

**Comment by vwheeler63** [comment]
@kisvegabor Hi, Gabor!  Ready for re-review/approval/merging.

**Comment by kdschlosser** [comment]
I was actually thinking about it and because the include guard is supposed to be named identically to the header file it is guarding we don't really need to add any underscores. Either way is fine as long as it is done across the board...

All header files should have an include guard so I can test for that as well and fail the build if there is not one placed or it is named wrong. It's pretty easy to check for that during the documentation build.

**Comment by vwheeler63** [comment]
> Either way is fine as long as it is done across the board...

With PR #6689, they were made consistent.

**Comment by vwheeler63** [comment]
@kisvegabor Can @kdschlosser also approve these?  If so, we could speed up getting to the merging step we both need.  If so, aside from this one, is PR #6673, PR #6705, and (just to wrap it up) PR #6695.

**Comment by kdschlosser** [comment]
I did want to bring up the use of `@private` which is something that is not being used in LVGL. I am sure you already know what that is @vwheeler63 but it might be worth going over so @kisvegabor knows what it does. what do ya think?

**Review by liamHowatt — APPROVED** [review]

**Comment by kisvegabor** [comment]
Sorry, I'm fully into finalizing things for the PR. I immerse in the docs again next week after the release. :slightly_frowning_face: 

Until that it can be merged safely.

**Comment by vwheeler63** [comment]
> I immerse in the docs again next week after the release. 🙁
> 
> Until that it can be merged safely.

Understandable.  Thank you!

**Pull request merged**
