### PR TITLE
Update lv_hal_disp.c for monochromatic lcd

### PR DESCRIPTION
**Pull request by Wielebny666**
Need clean buffer after flush

### CODE REVIEW

**Comment by kisvegabor** [comment]
It shouldn't clean after it, because normally (if `LV_COLOR_SCREEN_TRANSP = 0`) lvgl will render all the pixels on the screen. So you will have a solid background that will overwrite the old content of the buffer. 

Your driver [here](https://github.com/littlevgl/lvgl/issues/1435#issue-596527080) looks correct because it clears the dark pixels. So probably you get wrong data from lvgl, which can happen if your screen's opacity is not `LV_OPA_COVER`. Is this the case?

**Comment by Wielebny666** [comment]
```	
	lv_obj_set_opa_scale_enable(lv_scr_act(), true);
	lv_obj_set_opa_scale(lv_scr_act(), LV_OPA_COVER);
```
Does not solve the problem

**Comment by kisvegabor** [comment]
Did #1439 solve it too?

**Comment by Wielebny666** [comment]
Yes,
lv_theme_mono_init() should check that display was initialized.

**Pull request closed without merging**
