### PR TITLE
lv_roller: Unit tests and cleanup

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Unit tests and cleanup for lv_roller widget.

Initial ravioli output:

```console
ravioli -f src/widgets/roller/lv_roller.c
-------------------------------------------------------------------------------
Globals                                                                        
-------------------------------------------------------------------------------
src/widgets/roller/lv_roller.c:0 sel_opt
src/widgets/roller/lv_roller.c:252 c
src/widgets/roller/lv_roller.c:203 line_space
src/widgets/roller/lv_roller.c:624 font_h
src/widgets/roller/lv_roller.c:625 h
src/widgets/roller/lv_roller.c:626 anim_time
src/widgets/roller/lv_roller.c:634 id
src/widgets/roller/lv_roller.c:635 sel_y1
src/widgets/roller/lv_roller.c:636 mid_y1
src/widgets/roller/lv_roller.c:638 new_y
src/widgets/roller/lv_roller.c:725 id
src/widgets/roller/lv_roller.c:726 res
src/widgets/roller/lv_roller.c:727 res
-------------------------------------------------------------------------------
Functions                                                            complexity
-------------------------------------------------------------------------------
src/widgets/roller/lv_roller.c:322
    lv_roller_event                                                         27
src/widgets/roller/lv_roller.c:657
    release_handler                                                         15
src/widgets/roller/lv_roller.c:602
    refr_position                                                            9
src/widgets/roller/lv_roller.c:237
    lv_roller_get_selected_str                                               8
src/widgets/roller/lv_roller.c:97
    lv_roller_set_options                                                    6
src/widgets/roller/lv_roller.c:425
    lv_roller_label_event                                                    6
src/widgets/roller/lv_roller.c:159
    lv_roller_set_selected                                                   5
src/widgets/roller/lv_roller.c:457
    draw_main                                                                4
src/widgets/roller/lv_roller.c:530
    draw_label                                                               4
src/widgets/roller/lv_roller.c:217
    lv_roller_get_selected                                                   2
src/widgets/roller/lv_roller.c:283
    lv_roller_get_option_cnt                                                 2
src/widgets/roller/lv_roller.c:734
    inf_normalize                                                            2
src/widgets/roller/lv_roller.c:768
    get_selected_label_width                                                 2
src/widgets/roller/lv_roller.c:79
    lv_roller_create                                                         1
src/widgets/roller/lv_roller.c:198
    lv_roller_set_visible_row_count                                          1
src/widgets/roller/lv_roller.c:270
    lv_roller_get_options                                                    1
src/widgets/roller/lv_roller.c:301
    lv_roller_constructor                                                    1
src/widgets/roller/lv_roller.c:578
    get_sel_area                                                             1
src/widgets/roller/lv_roller.c:762
    get_label                                                                1
src/widgets/roller/lv_roller.c:781
    scroll_anim_ready_cb                                                     1
src/widgets/roller/lv_roller.c:788
    set_y_anim                                                               1
```

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by C47D** [comment]
I've added most of the test cases. I wasn't able to reuse as much code as I wanted, but adding `const` and reducing variables scope was possible.

There's also some functions that doesn't get tested but we could add dummy tests to increase coverage, let me know if we should add those.

Current coverage
imagen

**Comment by kisvegabor** [comment]
Cool!

It'd be great to test that with infinite mode after the last option the first comes again.  (e.g. when pressing key down)

And a render test as usual would be also very useful with some custom styles. :slightly_smiling_face:

**Comment by C47D** [comment]
I'll check the rendering tests you've done in other widgets. I haven't done any.

I'll add the test for the infinite roller as well, thanks for the use case.

**Comment by C47D** [comment]
> It'd be great to test that with infinite mode after the last option the first comes again. (e.g. when pressing key down)

See [0813c78](https://github.com/lvgl/lvgl/pull/3660/commits/0813c78aef5ceaf17f679a4c527c0cb57914f443)

---

> And a render test as usual would be also very useful with some custom styles.

Any test case in particular?

**Comment by kisvegabor** [comment]
>> It'd be great to test that with infinite mode after the last option the first comes again. (e.g. when pressing key down)

> See [0813c78](https://github.com/lvgl/lvgl/pull/3660/commits/0813c78aef5ceaf17f679a4c527c0cb57914f443)

Looks good thanks!

> Any test case in particular?

I find this important to test:
```c
    static lv_style_t style_sel;
    lv_style_init(&style_sel);
    lv_style_set_text_font(&style_sel, &lv_font_montserrat_22);
    lv_style_set_bg_color(&style_sel, lv_color_hex3(0xf88));
    lv_style_set_border_width(&style_sel, 2);
    lv_style_set_border_color(&style_sel, lv_color_hex3(0xf00));

    lv_obj_add_style(roller, &style_sel, LV_PART_SELECTED);

```

**Comment by C47D** [comment]
@kisvegabor sorry for the delayed question. What should the test assert? Is it the rendering test only or some behavior?

**Comment by kisvegabor** [comment]
Here I mean only a rendering test. There are some internal mechanisms whose output is shown only during rendering.

**Comment by C47D** [comment]
@kisvegabor could you please help me updating the reference image? I haven't set the simulator just yet. I've also had to change the font to match the one available in the test suite.

**Comment by kisvegabor** [comment]
Added, let's see if it passes here too.

**Comment by C47D** [comment]
The issue was the font not being available in the 16bits build.

**Comment by kisvegabor** [comment]
From the report it seems mainly a "select an option by click" test is missing to achieve the target coverage.

**Comment by C47D** [comment]
on it

The reference image looks a bit estrange tho, it has a roller in the top left, is it expected?

**Comment by C47D** [comment]
@kisvegabor I think the image comparison test is failing and making those CI to fail. Is there a way to run those specific CI steps locally?

**Comment by kisvegabor** [comment]
Can you try [this](https://github.com/lvgl/lvgl/issues/2337#issuecomment-1254180137). Just delete the current image, and check the new auto-generated new one.

**Comment by C47D** [comment]
@kisvegabor that worked, great feature!!

**Comment by C47D** [comment]
Is there anything missing so it can be merged?

**Comment by kisvegabor** [comment]
Are we good with the coverage?

**Comment by C47D** [comment]
It currently has this coverage 
imagen

**Comment by kisvegabor** [comment]
The report says `release_handler` is still not executed. Could you also test it by using a click test on an option and see if really that option is selected?

**Comment by C47D** [comment]
I see it being executed, but not for `LV_INDEV_TYPE_POINTER` nor `LV_INDEV_TYPE_BUTTON`, I'll need to add the button one in the `lv_test_indev` files.

imagen

I'll add a test for the `LV_INDEV_TYPE_POINTER` one, what should we test in that case?

**Comment by kisvegabor** [comment]
It's strange as `lv_test_mouse_click_at` should use an `LV_INDEV_TYPE_POINTER` indev.

**Comment by C47D** [comment]
I've added a test for the `LV_INDEV_TYPE_POINTER` indev which checks the selected option after clicking in the roller.

Here's the current coverage:
imagen

**Comment by kisvegabor** [comment]
Amazing! Thanks you, merging!

**Pull request merged**
