### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by kdschlosser**
### Description of the feature or fix
Converts documentation to restructured text instead of markdown. This is done so Sphinx is able to be used to it's fullest potential. When using Markdown you are not have to access all of the sphinx primers and directives. This PR also generates a "clean" documentation build with no warnings or errors.. All of the requirements are able to be upgraded to the most current version without any issues. 

I also moved the building of the documentation to a temporary directory as well. The generated output ends up in the same place just the intermediate files created during the build are in the temporary directory.

The checkpoints don't really pertain to this update.

I do know that there is a merge conflict and I will get that sorted in the next day or so.

### CODE REVIEW

**Comment by kdschlosser** [comment]
I did want to mention. It might be worth while to do this. I have the ability to check and see if there are things that are not documented and I can cause a CI build to fail if the documentation is missing. This is a good way to make sure things get documented properly, well at least the API portion of it anyhow.

**Comment by kisvegabor** [comment]
Thank you very much!

> I have the ability to check and see if there are things that are not documented and I can cause a CI build to fail if the documentation is missing. 

It sounds great! However, I suggest proceeding in smaller steps. Re-implement the current functionality, make the CI pass, fix conflicts, etc and add the extra things in new PRs.

**Comment by kdschlosser** [comment]
> It sounds great! However, I suggest proceeding in smaller steps. Re-implement the current functionality, make the CI pass, fix conflicts, etc and add the extra things in new PRs.

I fully agree. Lets get this step done and the conversion finished up and then we can add new functionality in new PRs I thought it was worth mentioning to see if there was interest in doing it. It will help to keep things documented.

**Comment by kdschlosser** [comment]
Looks like there is a missing declaration `_lv_style_state_cmp_t`.

**Comment by kdschlosser** [comment]
I am also not sure why it is complaining about this.

```
typedef enum {
    LV_OBJ_FLAG_HIDDEN          = (1L << 0),  /**< Make the object hidden. (Like it wasn't there at all)*/
    LV_OBJ_FLAG_CLICKABLE       = (1L << 1),  /**< Make the object clickable by the input devices*/
    LV_OBJ_FLAG_CLICK_FOCUSABLE = (1L << 2),  /**< Add focused state to the object when clicked*/
    LV_OBJ_FLAG_CHECKABLE       = (1L << 3),  /**< Toggle checked state when the object is clicked*/
    LV_OBJ_FLAG_SCROLLABLE      = (1L << 4),  /**< Make the object scrollable*/
    LV_OBJ_FLAG_SCROLL_ELASTIC  = (1L << 5),  /**< Allow scrolling inside but with slower speed*/
    LV_OBJ_FLAG_SCROLL_MOMENTUM = (1L << 6),  /**< Make the object scroll further when "thrown"*/
    LV_OBJ_FLAG_SCROLL_ONE      = (1L << 7),  /**< Allow scrolling only one snappable children*/
    LV_OBJ_FLAG_SCROLL_CHAIN_HOR = (1L << 8), /**< Allow propagating the horizontal scroll to a parent*/
    LV_OBJ_FLAG_SCROLL_CHAIN_VER = (1L << 9), /**< Allow propagating the vertical scroll to a parent*/
    LV_OBJ_FLAG_SCROLL_CHAIN     = (LV_OBJ_FLAG_SCROLL_CHAIN_HOR | LV_OBJ_FLAG_SCROLL_CHAIN_VER),
    LV_OBJ_FLAG_SCROLL_ON_FOCUS = (1L << 10),  /**< Automatically scroll object to make it visible when focused*/
    LV_OBJ_FLAG_SCROLL_WITH_ARROW  = (1L << 11), /**< Allow scrolling the focused object with arrow keys*/
    LV_OBJ_FLAG_SNAPPABLE       = (1L << 12), /**< If scroll snap is enabled on the parent it can snap to this object*/
    LV_OBJ_FLAG_PRESS_LOCK      = (1L << 13), /**< Keep the object pressed even if the press slid from the object*/
    LV_OBJ_FLAG_EVENT_BUBBLE    = (1L << 14), /**< Propagate the events to the parent too*/
    LV_OBJ_FLAG_GESTURE_BUBBLE  = (1L << 15), /**< Propagate the gestures to the parent*/
    LV_OBJ_FLAG_ADV_HITTEST     = (1L << 16), /**< Allow performing more accurate hit (click) test. E.g. consider rounded corners.*/
    LV_OBJ_FLAG_IGNORE_LAYOUT   = (1L << 17), /**< Make the object position-able by the layouts*/
    LV_OBJ_FLAG_FLOATING        = (1L << 18), /**< Do not scroll the object when the parent scrolls and ignore layout*/
    LV_OBJ_FLAG_OVERFLOW_VISIBLE = (1L << 19), /**< Do not clip the children's content to the parent's boundary*/

    LV_OBJ_FLAG_LAYOUT_1        = (1L << 23), /**< Custom flag, free to use by layouts*/
    LV_OBJ_FLAG_LAYOUT_2        = (1L << 24), /**< Custom flag, free to use by layouts*/

    LV_OBJ_FLAG_WIDGET_1        = (1L << 25), /**< Custom flag, free to use by widget*/
    LV_OBJ_FLAG_WIDGET_2        = (1L << 26), /**< Custom flag, free to use by widget*/
    LV_OBJ_FLAG_USER_1          = (1L << 27), /**< Custom flag, free to use by user*/
    LV_OBJ_FLAG_USER_2          = (1L << 28), /**< Custom flag, free to use by user*/
    LV_OBJ_FLAG_USER_3          = (1L << 29), /**< Custom flag, free to use by user*/
    LV_OBJ_FLAG_USER_4          = (1L << 30), /**< Custom flag, free to use by user*/
#ifdef DOXYGEN
} lv_obj_flag_t;
#else
};
typedef uint32_t lv_obj_flag_t;
#endif /*DOXYGEN*/
```

This is done so the documentation links properly to the enum. This should only effect the documentation so I am not sure why the C compiler is getting upset by it.

Gotta think of a different way to go about it then. Might have to change it to something along these lines.

```
typedef enum _lv_obj_flag_t{
    LV_OBJ_FLAG_HIDDEN          = (1L << 0),  /**< Make the object hidden. (Like it wasn't there at all)*/
    LV_OBJ_FLAG_CLICKABLE       = (1L << 1),  /**< Make the object clickable by the input devices*/
    LV_OBJ_FLAG_CLICK_FOCUSABLE = (1L << 2),  /**< Add focused state to the object when clicked*/
    LV_OBJ_FLAG_CHECKABLE       = (1L << 3),  /**< Toggle checked state when the object is clicked*/
    LV_OBJ_FLAG_SCROLLABLE      = (1L << 4),  /**< Make the object scrollable*/
    LV_OBJ_FLAG_SCROLL_ELASTIC  = (1L << 5),  /**< Allow scrolling inside but with slower speed*/
    LV_OBJ_FLAG_SCROLL_MOMENTUM = (1L << 6),  /**< Make the object scroll further when "thrown"*/
    LV_OBJ_FLAG_SCROLL_ONE      = (1L << 7),  /**< Allow scrolling only one snappable children*/
    LV_OBJ_FLAG_SCROLL_CHAIN_HOR = (1L << 8), /**< Allow propagating the horizontal scroll to a parent*/
    LV_OBJ_FLAG_SCROLL_CHAIN_VER = (1L << 9), /**< Allow propagating the vertical scroll to a parent*/
    LV_OBJ_FLAG_SCROLL_CHAIN     = (LV_OBJ_FLAG_SCROLL_CHAIN_HOR | LV_OBJ_FLAG_SCROLL_CHAIN_VER),
    LV_OBJ_FLAG_SCROLL_ON_FOCUS = (1L << 10),  /**< Automatically scroll object to make it visible when focused*/
    LV_OBJ_FLAG_SCROLL_WITH_ARROW  = (1L << 11), /**< Allow scrolling the focused object with arrow keys*/
    LV_OBJ_FLAG_SNAPPABLE       = (1L << 12), /**< If scroll snap is enabled on the parent it can snap to this object*/
    LV_OBJ_FLAG_PRESS_LOCK      = (1L << 13), /**< Keep the object pressed even if the press slid from the object*/
    LV_OBJ_FLAG_EVENT_BUBBLE    = (1L << 14), /**< Propagate the events to the parent too*/
    LV_OBJ_FLAG_GESTURE_BUBBLE  = (1L << 15), /**< Propagate the gestures to the parent*/
    LV_OBJ_FLAG_ADV_HITTEST     = (1L << 16), /**< Allow performing more accurate hit (click) test. E.g. consider rounded corners.*/
    LV_OBJ_FLAG_IGNORE_LAYOUT   = (1L << 17), /**< Make the object position-able by the layouts*/
    LV_OBJ_FLAG_FLOATING        = (1L << 18), /**< Do not scroll the object when the parent scrolls and ignore layout*/
    LV_OBJ_FLAG_OVERFLOW_VISIBLE = (1L << 19), /**< Do not clip the children's content to the parent's boundary*/

    LV_OBJ_FLAG_LAYOUT_1        = (1L << 23), /**< Custom flag, free to use by layouts*/
    LV_OBJ_FLAG_LAYOUT_2        = (1L << 24), /**< Custom flag, free to use by layouts*/

    LV_OBJ_FLAG_WIDGET_1        = (1L << 25), /**< Custom flag, free to use by widget*/
    LV_OBJ_FLAG_WIDGET_2        = (1L << 26), /**< Custom flag, free to use by widget*/
    LV_OBJ_FLAG_USER_1          = (1L << 27), /**< Custom flag, free to use by user*/
    LV_OBJ_FLAG_USER_2          = (1L << 28), /**< Custom flag, free to use by user*/
    LV_OBJ_FLAG_USER_3          = (1L << 29), /**< Custom flag, free to use by user*/
    LV_OBJ_FLAG_USER_4          = (1L << 30), /**< Custom flag, free to use by user*/
};

#ifdef DOXYGEN
typedef _lv_obj_flag_t lv_obj_flag_t;
#else
typedef uint32_t lv_obj_flag_t;
#endif /*DOXYGEN*/
```

**Comment by kisvegabor** [comment]
> Gotta think of a different way to go about it then. Might have to change it to something along these lines.

It sounds better to me!

**Comment by kdschlosser** [comment]
I didn't want to name the enums unless it was OK with you. I wasn't sure if there was a reason why they were not named in the first place. if it isn't used it's not going to take up any memory when it's compiled right?

**Comment by kdschlosser** [comment]
This is only for the purpose of having the documentation link to the enumeration properly. When an enum is unnamed there is nothing to link to.

**Comment by kisvegabor** [comment]
> I wasn't sure if there was a reason why they were not named in the first place.

As you could see we use this technique in many places: `typedef uint32_t lv_obj_flag_t;`
It has 2 advantages:
- We can be sure about the size of enum and it doesn't depend on the compiler
- We can do this: `lv_some_enum_t value :3` if the `enum` has max 8 values


> This is only for the purpose of having the documentation link to the enumeration properly. When an enum is unnamed there is nothing to link to.

This `#ifdef DOXYGEN` thing is little bit hacky but I can't imagine a better solution either. Let's go with it for now and if we will have better idea, we can change it later.

**Comment by kdschlosser** [comment]
The macro is the official doxygen way of doing what I am doing. It's the way you manipulate the documentation output.

**Comment by kdschlosser** [comment]
I have my fingers crossed for this last time around. I hope I have all of the issues sorted out and this PR can get merged.

**Comment by neuschaefer** [comment]
Since any new unrelated changes to the current Markdown documentation has a chance of causing merge conflicts for this PR, I suspect a more incremental approach might help:

1. enable having both Markdown and ReStructedText files built with Sphinx, and convert a few files, in this PR
2. later, convert all Markdown files, solving merge conflicts as they appear
3. when there are no Markdown files left, remove Markdown support

**Comment by kisvegabor** [comment]
Why can't we merge it now? All conflicts are solved, we can use RST from now.

**Comment by neuschaefer** [comment]
> Why can't we merge it now? All conflicts are solved, we can use RST from now.

If that's the case and nothing else is blocking this PR, alright. (I didn't check how far along this PR is.)

**Comment by kisvegabor** [comment]
In this case, @kdschlosser, please confirm if I can hit the merge button. :slightly_smiling_face: 

It's hard to verify if there RST docs is really the same as the MD one, but if there is an regression we can easily update it.

**Comment by kdschlosser** [comment]
hit the button. if there is an issue it can always be undone or fixed. It's not like it's permanent.

I have done my best to keep changed to the docs up to now as they should be. I have even added that table that was added in the rt-thread doc.

**Comment by kdschlosser** [comment]
This PR had the single goal of making the documentation build error free. This is what it took to do that.

**Comment by kisvegabor** [comment]
Merged, thank you very much @kdschlosser :tada: :tada: :tada:

**Comment by kisvegabor** [comment]
We have this error: https://github.com/lvgl/lvgl/actions/runs/4819883973/jobs/8583660433

**Comment by kdschlosser** [comment]
ok, need to check the python version if that keyword was added or removed or changed to something else.

**Comment by kdschlosser** [comment]
funny thing is the docs for python don't mention anything about that argument being added at a specific release. Not sure when it was added.

https://docs.python.org/3/library/shutil.html#shutil.copytree

We can change the change the CI python version to 3.10. that should correct the problem.

**Comment by kdschlosser** [comment]
yup that keyword argument was added in 3.8.2

**Comment by kisvegabor** [comment]
I've bumped the Python version number to 3.10 but now it has a different error:
https://github.com/lvgl/lvgl/actions/runs/4822889402/jobs/8590683553

**Comment by kdschlosser** [comment]
for the time being change the build command so it has "skip_latex" in it. I didn't realize the PDF generation uses recommonmark which is what we are trying to get away from. I have to investigate why it is using it. More than likely I will be able to remove that dependency.

**Comment by kdschlosser** [comment]
scratch that. I just opened a PR that should fix the issue

**Pull request merged**
