### PR TITLE
reversing direction of lv_label's text anim

### PR DESCRIPTION
**Pull request by KamranAghlami**
### Capability of reversing text animation direction 

Greetings,
    I was trying to use lvgl in my project which includes displaying Persian text and noticed the direction which the text scrolls when 
    in long mode is LTR only, so I fixed it by switching start and end positions of the animation assigned to the scrolling job.
    I think this is a nice feature to have since lvgl supports bidi text and I was wondering if this is the right way to do it.
    I would love to hear back from you. Thanks.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

It's a good idea! 

However, I think the end and start position can be swapped automatically if the base dir is RTL. What do you think?

**Comment by KamranAghlami** [comment]
Hi, 

Sorry for the long absence, It's been a few busy days,

I agree, I would like to see it work that way, let me know if you like my implementation.

**Comment by kisvegabor** [comment]
Thank you! Your implementation looks great!

Please also add a line about it into the [CHANGELOG](https://github.com/lvgl/lvgl/blob/master/CHANGELOG.md).

**Comment by KamranAghlami** [comment]
Updated the changelog, tough it seems I shouldn't have updated my local repository before adding this change, now I see that Github is showing wrong number for "Files Changed", anyway let me know if this is problematic, I can close this PR and open a new one then.
Thanks.

**Comment by embeddedt** [comment]
I'm not sure why it's reporting all these changes. It's probably best to just open a new PR.

**Comment by KamranAghlami** [comment]
It's ok, I'm closing this one and opening a new PR. --> #2112

**Pull request closed without merging**
