### PR TITLE
fix(file_exploer): fix path issues when returning to open other folders after opening a certain folder

### LINKED ISSUE #7257: Issue with File Explorer: Unable to Open Folder
### LVGL version

master

### What happened?

see video

https://github.com/user-attachments/assets/f998de80-9c2d-4fca-b78b-42e37b851681

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by lhdjply**
fix #7257 

cc @liamHowatt 

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by liamHowatt — COMMENTED** [review]
Would you mind explaining briefly how this fixes the problem?

**Comment by lhdjply** [comment]
I don't now how to explain this. But I add the tests. You can see fix before and fix after.

image

**Review by liamHowatt — COMMENTED** [review]
I found the root cause.

This is an alternative way of solving the problem.

**don't apply this change, it's just to explain.**

```diff
diff --git a/src/others/file_explorer/lv_file_explorer.c b/src/others/file_explorer/lv_file_explorer.c
index 7a1e69752..078128ce4 100644
--- a/src/others/file_explorer/lv_file_explorer.c
+++ b/src/others/file_explorer/lv_file_explorer.c
@@ -625,6 +625,7 @@ static void show_dir(lv_obj_t * obj, const char * path)
     size_t current_path_len = lv_strlen(explorer->current_path);
     if((explorer->current_path[current_path_len - 1] != '/') && (current_path_len < LV_FILE_EXPLORER_PATH_MAX_LEN)) {
         *((explorer->current_path) + current_path_len) = '/';
+        if(current_path_len + 1 < LV_FILE_EXPLORER_PATH_MAX_LEN) *(explorer->current_path + (current_path_len + 1)) = '\0';
     }
 }

```

`strncpy` fixes it because it zeroes the rest of the destination. This was overlooked as a necessary step when I refactored some `strncpy`s to `strlcpy`s.

I think your solution is good. It's a rare case where `strncpy` is better suited than `strlcpy`. Nice work.

The test is good to have too. Could you please just correct the spelling of "folder" from "floder" and also group all the `*_row = i` logic together and it has my approval.

After merging I will close PR #7239.

**Comment by liamHowatt** [comment]
Also please move `tests/src/test_cases/test_file_explorer.c` to `tests/src/test_cases/widgets/test_file_explorer.c`.

**Comment by lhdjply** [comment]
> Could you please just correct the spelling of "folder" from "floder"

ok👌

> also group all the *_row = i logic together

How to group all? For example, the row of shm_row and user_row can be identified only after a folder is opened.

> Also please move tests/src/test_cases/test_file_explorer.c to tests/src/test_cases/widgets/test_file_explorer.c.

Do you think we could add a `tests/src/test_cases/others folder` and move it to this folder? If that's feasible, then we can start a new PR,Move all relevant tests to the `tests/src/test_cases/others` folder, e.g. `test_observer`, `test_snapshot`

**Comment by liamHowatt** [comment]
Regarding rows, I see now how they're nested and my suggestion makes no sense. Ignore.

Regarding widgets tests, I thought file explorer was a widgets for some reason but it's not, so the folder the test is in is now is correct.

**Comment by lhdjply** [comment]
> Regarding widgets tests, I thought file explorer was a widget for some reason but it's not, so the folder the test is in is now is correct.

So which do you think is better to keep the same or create a new "others" folder?

**Review by liamHowatt — APPROVED** [review]
> So which do you think is better to keep the same or create a new "others" folder?

Keep it the same.

**Review by kisvegabor — APPROVED** [review]

**Pull request merged**
