### PR TITLE
feat(menu): disable root back button on sub menus by default

### PR DESCRIPTION
**Pull request by conor-third**
See issue #6690

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thank you! 

It's a breaking change as now the back button never will be displayed on the main page. Is that correct?

**Comment by conor-third** [comment]
What about removing the cur_depth check so the root back button mode applies to all menus? It's probably not an ideal solution as setting the root back button mode should only apply to the root back button. Alternatively, I've adjusted my code to disable the back button on menu page loaded events. I'm happy to close this PR since this is a niche use case, let me know if you think otherwise.

**Comment by kisvegabor** [comment]
Using `LV_MENU_ROOT_BACK_BUTTON_ENABLED` for non-root menus is counterintuitive. 

To stay on the safe side, let's close this PR for now, but please add your workaround in a comment for future readers.

**Comment by conor-third** [comment]
As a workaround I register a callback with the root menu object:

`lv_obj_add_event_cb(root_menu, PageLoadedHandler, LV_EVENT_VALUE_CHANGED, root_menu);`

And in the callback:

`lv_obj_add_flag(root_menu->main_header_back_btn, LV_OBJ_FLAG_HIDDEN);`
`lv_obj_remove_flag(root_menu->main_header_back_btn, LV_OBJ_FLAG_CLICKABLE);`

Not an ideal solution as its called every time a page in the menu is loaded but it does the job.

**Comment by kisvegabor** [comment]
Thank you!

**Pull request closed without merging**
