### PR TITLE
feat(switch) add animation

### PR DESCRIPTION
**Pull request by kisvegabor**
### Description of the feature or fix

Add animation to the switch when toggled.

Created from @HX2003's [work](https://github.com/HX2003/lvgl/commit/5bfb7adc5fb3a4c0bc37e882d0a5eb58c11da411).

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by embeddedt** [comment]
Superseded by https://github.com/lvgl/lvgl/pull/2442, as we cannot push to external branches.

**Comment by kisvegabor** [comment]
What was the problem here? How do you mean "external branches"?

**Comment by embeddedt** [comment]
You opened the pull request from HX2003's fork, however, as HX2003 was not the person who opened the pull request, I cannot push any additional commits to their branch. GitHub only allows us to push to contributors' branches when they open a pull request themselves and leave the checkbox about maintainer edits checked.

**Comment by kisvegabor** [comment]
Ah, got it thanks.

**Pull request closed without merging**
