### PR TITLE
fix(docs):  stray space in style_api_gen.py and generated doc...

### PR DESCRIPTION
**Pull request by vwheeler63**
...keeps coming up.  This fixes both.

@kisvegabor @liamHowatt This seemed like a no-brainer -- obvious stray space in `/scripts/style_api_gen.py` and the document it generates.  Both are submitted herein.  As they change is tiny and obvious, I'm hoping this is quick to approve and merge.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.  Done.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.  n/a
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.  n/a
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).  n/a
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).  n/a
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.  Done.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.  n/a
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — APPROVED** [review]
Sorry that it takes long to merge these PRs. We have some internal things going on, and have less time for GitHub that we should have. :slightly_frowning_face:

**Comment by vwheeler63** [comment]
Since I know life is composed of many spheres of responsibility, I never felt any frustration about delays.  It's good to know you're there and reliable.  :-)

**Comment by vwheeler63** [comment]
> Sorry that it takes long to merge these PRs.

Since I know life is composed of many spheres of responsibility, I never felt any frustration about delays. It's good to know you're there and reliable. :-)

**Review by liamHowatt — APPROVED** [review]
Thanks!

**Pull request merged**
