### PR TITLE
Arch/cmsis pack/new lvgl9 bundle

### PR DESCRIPTION
**Pull request by bbkarim**
### Description of the feature or fix

  * Reworked components to get more granulated sub-groups
  * Add missing hearder files
  * Add more widgets and demos

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
Hi @bbkarim 

Good to see you have separated some of the patches into dedicated PRs. Really appreciate! 

I noticed you have put a lot of changes to lvgl.h. 

This will affect a lot of people and usually need more review. 

My suggestion is Revert it in this PR so it won't block this one (To be honest, a lot of contributor might have different opinions about changes of lvgl.h, I don't want this blocking this PR)

Updating `lv_conf.h` and `Kconf` for just cmsis-pack might raise concerns among a lot of people. Usually a packing method should avoid changing the library as long as it is possible (you might notice that I have limited all the cmsis-pack related content and changes inside the `env_support/cmsis-pack` folder, and we even created a cmsis-pack specific `lv_conf.h`, i.e. `lv_cmsis_conf.h` to avoid polluting the original `lv_conf_template.h`) I didn't say what you proposed was not good, but it might take some time. 

arch(lvgl): add the new lv_layouts.h header file 
This one has no direct relationship with cmsis-pack. 

Those are only my suggestions, if you want to wait other PRs been accepted before this PR, then I have no problem at all. We can wait. 

Let's forcus on the lvgl9 structural changes in this PR. I need to verify the new pack before giving you any feedback.

**Comment by GorgonMeducer** [comment]
For cmsis-pack verification, I am using this project : 

https://github.com/lvgl/lv_port_an547_cm55_sim

Please install the latest MDK and other cmsis-packs inside the cmsis-pack folder. 

For License, you can apply MDK Community License which gives you the full feature Arm Compiler 6. 

Our goal are: 

a. Existing RTE configuration that using the old LVGL::lvgl can work without any problem (no changes is needed)

b. When switching to the new LVGL::lvgl9 no user application code should be changed, changing the porting code is expected and acceptable. 

c. We should be able to run the Widgets demo and benchmark without changing lv_cmsis_conf.h (or lv_conf.h) - this is for the best out-of-box experience for those first time users

**Comment by GorgonMeducer** [comment]
I have a proposal, I can have minimal update to pdsc for taking this structural change without involving other patches. I will Mark you as the co-auther and put a reference to this PR. (You can update the new pdsc for other patches later)

By doing so, we can quickly introduce the new bundle in January monthly update. (according to the plan, the middle month cmsis-pack update will be made in 3 days)

**Comment by bbkarim** [comment]
> I have a proposal, I can have minimal update to pdsc for taking this structural change without involving other patches. I will Mark you as the co-auther and put a reference to this PR. (You can update the new pdsc for other patches later)
> 
> By doing so, we can quickly introduce the new bundle in January monthly update. (according to the plan, the middle month cmsis-pack update will be made in 3 days)

Hi @GorgonMeducer 

Had worked on that meanwhile...
I think by just adding the remaining header files included by the lvgl.h into the Essential sub-group, we will be able to build the examples.

I just added these header files ASAP and I succeeded building my port without any changes in the lvgl.h.

BTW: my port is a local STM32 using:
- NUCLEO-U575ZI-Q + X-NUCLEO-GFX02Z1 boards.
- STM32CubeMX 6.7.0
- X-CUBE-DISPLAY-2.1.0 SW Expansion pack (can be downloaded by STM32CubeMX)
- LVGL CMSIS pack

I'm building the official benchmark demo and testing it on that HW.

Please let me know if the new patch is fine so we can progress with it until we get other patches merged.

Thanks,
Karim

**Comment by GorgonMeducer** [comment]
@bbkarim You have added many header files that are not required. 
As @kisvegabor mentioned, only `lvgl.h` is required. Please remove them in the pdsc file.

image

If my understanding is correct, this is one of the beauties of the LVGL.

https://github.com/lvgl/lvgl/blob/2d974d5183fc6ebce6494e60ab2f1aa7a9d75f49/env_support/cmsis-pack/LVGL.lvgl.pdsc#L1024-L1318

**Comment by GorgonMeducer** [comment]
```
          <!-- <file category="preIncludeGlobal"   name="lv_conf_cmsis.h" attr="config" version="1.1.6"/> -->
          <file category="header"       name="lv_conf.h" attr="template" select="lv_conf template" version="1.1.6"/>
```

Use lv_conf.h as template doesn't work in MDK system for the following reason:

a. Users usually don't know they need to create a template after selecting the LVGL9 in RTE
b. After adding a template, the compilation still use the `lv_conf.h` inside the cmsis-pack rather than the created new header file in the project folder.


So no one can change anything in the `lv_conf.h`.

Please use my original solution, i.e. using attr="config", so a copy of lv_conf.h will be copied to RTE/LVGL folder and compilation will use it.

**Comment by GorgonMeducer** [comment]
Another problem:

Since we already decide to use template for porting display/indicator/file system then no need to add a dedicated component called porting:

image

In MDK system, we can already add those porting files as templates:

image

But the problem is, you only including header files as templates but not the source files:

image

Please correct this.

**Comment by GorgonMeducer** [comment]
I have created a fix. Please check it:

https://github.com/GorgonMeducer/lvgl/tree/LVGL9-fix

**Comment by GorgonMeducer** [comment]
Please set
```c
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
```

to 1, because widgets and benchmark require them. It is important to get a good out-of-box user experience.

**Comment by GorgonMeducer** [comment]
Please review and update the README.md to describe how we can get a `lv_conf_cmsis.h` from the `lv_conf_template.h`.

**Comment by bbkarim** [comment]
> @bbkarim You have added many header files that are not required. As @kisvegabor mentioned, only `lvgl.h` is required. Please remove them in the pdsc file.
> 
> image
> 
> If my understanding is correct, this is one of the beauties of the LVGL.
> 
> https://github.com/lvgl/lvgl/blob/2d974d5183fc6ebce6494e60ab2f1aa7a9d75f49/env_support/cmsis-pack/LVGL.lvgl.pdsc#L1024-L1318

@GorgonMeducer 
That's fine for Keil µVision Toolchain, all the dependencies will be linked to their origins and so you don't need to add header files. However it is not the case when using STM32CubeIDE or IAR Toolchains. I need to copy also header files to succeed building the stand-alone project I'm generating with STM32CubeMX.
Currently, it is not working for me with STM32CubeMX until I add these header files.
Please remove them from the the monthly release until I analyze that more. I need to find out a solution for STM32CubeIDE and IAR projects...

**Comment by GorgonMeducer** [comment]
@bbkarim To be honest, you are not the first person who uses IAR and STM32CubeMX environment; there must be something wrong with your configuration. Furthermore, if you check the code, you will find that all those header files are included layer by layer by their parent header files, so there is no need to add these header files manually.

I will wait until you find the reason, no hurry.

**Comment by GorgonMeducer** [comment]
> However it is not the case when using STM32CubeIDE or IAR Toolchains. I need to copy also header files to succeed building the stand-alone project I'm generating with STM32CubeMX.

If we do need to treat IAR specially, don't forget that cmsis-pack can detect the IAR, hence you can create a dedicated condition for IAR and apply this condition to some header files. 

I hope this helps.

**Comment by GorgonMeducer** [comment]
By the way, after discussed with @kisvegabor , we decided to: 
- stop monthly update for cmsis-pack
- only create cmsis-pack for new LVGL releases, e.g. v9.0 and v8.3.5
- cmsis-pack will share the same version number as the corresponding LVGL releases/patches

the v8.3.5 is a maintenance release, hence will not employ this new structure.
the v9.0 release will use this new LVGL::LVGL9 structure.

We have plenty of time, don't worry.

**Comment by bbkarim** [comment]
> > However it is not the case when using STM32CubeIDE or IAR Toolchains. I need to copy also header files to succeed building the stand-alone project I'm generating with STM32CubeMX.
> 
> If we do need to treat IAR specially, don't forget that cmsis-pack can detect the IAR, hence you can create a dedicated condition for IAR and apply this condition to some header files.
> 
> I hope this helps.

Hello @GorgonMeducer,

Actually my issue is not with the toolchain itself, it is with the generator (Keil or STM32CubeMX)
STM32CubeMX support three option to copy libraries into the generated project.

1. Copy all used libraries into the project folder
2. Copy only the necessary library files
3. Add necessary library files as reference in the toolchain project configuration file

If I select 3. then I do not need to have all the needed header files listed in the PDSC file the toolchain will include the lvgl/src folder from its original place (where it was installed)
However if I select 2. which is the recommended option to get stand-alone example's packages, then I'll need to have all required header files listed inside the PDSC file so that my generator (STM32CubeMX) will know what should be copied into the project folder.

Option 1. will copy everything and I think it could be the W/A till we conclude on the final solution here.

BTW: do you know if Keil also support such options ? (Copy files/libraries into the project folder) ??

Thanks,
Karim

**Comment by GorgonMeducer** [comment]
> BTW: do you know if Keil also support such options ? (Copy files/libraries into the project folder) ??

MDK only supports the option 3. 

The [open cmsis pack tool](https://github.com/Open-CMSIS-Pack/cmsis-toolbox) supports option 1. 

By the way, do you know IAR itself supports cmsis-pack and don't need the help from STM32CubeMX?

**Comment by bbkarim** [comment]
> Please set
> 
> ```c
> #define LV_FONT_MONTSERRAT_12 1
> #define LV_FONT_MONTSERRAT_14 1
> #define LV_FONT_MONTSERRAT_16 1
> ```
> 
> to 1, because widgets and benchmark require them. It is important to get a good out-of-box user experience.

OK, also MEM and PERF monitors are needed by benchmark.. I'll set them too
```c
#define LV_USE_PERF_MONITOR  1
#define LV_USE_MEM_MONITOR   1
```

**Comment by bbkarim** [comment]
> > BTW: do you know if Keil also support such options ? (Copy files/libraries into the project folder) ??
> 
> MDK only supports the option 3.
> 
Okay, so that's why we don't need to list the header files inside the PDSC.

> The [open cmsis pack tool](https://github.com/Open-CMSIS-Pack/cmsis-toolbox) supports option 1.
> 
This is something that I need to test and confirm, if this option will copy everything including header files too. If yes then we don't need to list them inside the PDSC.

> By the way, do you know IAR itself supports cmsis-pack and don't need the help from STM32CubeMX?
Yes, I'm aware about that, I'm also testing that with the new pack.

@GorgonMeducer please omit pushes I'm doing now until I find a conclude on the situation with STM32CubeMX. I'm just rebasing this PR and trying to enhance while progressing...

Thanks,
Karim

**Comment by bbkarim** [comment]
> By the way, after discussed with @kisvegabor , we decided to:
> 
> * stop monthly update for cmsis-pack
> * only create cmsis-pack for new LVGL releases, e.g. v9.0 and v8.3.5
> * cmsis-pack will share the same version number as the corresponding LVGL releases/patches
> 
> the v8.3.5 is a maintenance release, hence will not employ this new structure. the v9.0 release will use this new LVGL::LVGL9 structure.
> 
> We have plenty of time, don't worry.

Good news, I think also that keeping the release version the same among the devs will help to reduce the number of patch release. we can keep version="1.1.0-alpha" until we decide for a new version to be out, then remove '-alpha' and set it to version="1.1.0"

**Comment by GorgonMeducer** [comment]
> we can keep version="1.1.0-alpha" until we decide for a new version to be out, then remove '-alpha' and set it to version="1.1.0"

According to a recent suggestion from Arm, 
a. we should not use -alpha in the idx file, 
b. The cmsis-pack version should be the same as the LVGL version. 

So as I mentioned before, we will not use v1.1.0 anymore. 

I will have a review and let you know the result. I am taking vacation, this will take sometime, sorry.

**Comment by GorgonMeducer** [comment]
> OK, also MEM and PERF monitors are needed by benchmark.. I'll set them too

No, benchmark doesn't need them. But I am OK to keep these options on.

**Comment by GorgonMeducer** [comment]
> ```
> 
>           
> 
>           <file category="header"       name="lv_conf.h" attr="template" select="lv_conf template" version="1.1.6"/>
> 
> ```
> 
> 
> 
> Use lv_conf.h as template doesn't work in MDK system for the following reason:
> 
> 
> 
> a. Users usually don't know they need to create a template after selecting the LVGL9 in RTE
> 
> b. After adding a template, the compilation still use the `lv_conf.h` inside the cmsis-pack rather than the created new header file in the project folder.
> 
> 
> 
> 
> 
> So no one can change anything in the `lv_conf.h`.
> 
> 
> 
> Please use my original solution, i.e. using attr="config", so a copy of lv_conf.h will be copied to RTE/LVGL folder and compilation will use it.
> 
> 

Please also check this suggestion. 
The current pdsc doesn't work in MDK

**Comment by GorgonMeducer** [comment]
> Okay, so that's why we don't need to list the header files inside the PDSC.

Yes, so please remove those redundant header files.

**Comment by GorgonMeducer** [comment]
> @GorgonMeducer please omit pushes I'm doing now until I find a conclude on the situation with STM32CubeMX. I'm just rebasing this PR and trying to enhance while progressing...

Thank you very much. No hurry.

**Comment by bbkarim** [comment]
> > ```
> > 
> >           
> > 
> >           <file category="header"       name="lv_conf.h" attr="template" select="lv_conf template" version="1.1.6"/>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Use lv_conf.h as template doesn't work in MDK system for the following reason:
> > a. Users usually don't know they need to create a template after selecting the LVGL9 in RTE
> > b. After adding a template, the compilation still use the `lv_conf.h` inside the cmsis-pack rather than the created new header file in the project folder.
> > So no one can change anything in the `lv_conf.h`.
> > Please use my original solution, i.e. using attr="config", so a copy of lv_conf.h will be copied to RTE/LVGL folder and compilation will use it.
> 
> Please also check this suggestion. The current pdsc doesn't work in MDK

Hello @GorgonMeducer and @kisvegabor 

IMO, the lvgl pack shouldn't contain a lv_conf.h file, but a template of it. I'm not able to make the cmsis-pack making a copy of lv_conf_cmsis.h then rename it into lv_conf.h :-(
Your proposal will make the project directly including the lv_conf_cmsis.h which could be not clear for users.
From my side, I need investigate more how MDK is handling templates... I need that not only for the lv_conf.h but also for the porting templates.

Best Regards,
Karim

**Comment by GorgonMeducer** [comment]
> IMO, the lvgl pack shouldn't contain a lv_conf.h file, but a template of it. 

You have some misunderstanding about the 'attr=config'. When this is used, the file referred will be copied to a dedicated RTE folder in user project and this header file will be list in include search path and users can modify it. i.e attr='config' is designed for all configuration header files. lv_conf.h is a typical example. 


> I'm not able to make the cmsis-pack making a copy of lv_conf_cmsis.h then rename it into lv_conf.h :-( 

The pack_gen.sh has already done this work and the attr=config will do the rest of the work as mentioned above. 


> Your proposal will make the project directly including the lv_conf_cmsis.h which could be not clear for users.

I noticed that you have copy lv_conf_cmsis.h as lv_conf.h in gen_pack.sh, so we can use this lv_conf.h. 

I have used this one and created working cmsis-pack in the branch I showed you before. Please check it. 

https://github.com/GorgonMeducer/lvgl/tree/LVGL9-fix

image

image


> Your proposal will make the project directly including the lv_conf_cmsis.h which could be not clear for users.

That's not true. As shown above, I am using the lv_conf.h  

> From my side, I need investigate more how MDK is handling templates... I need that not only for the lv_conf.h but also for the porting templates.

Please note that, for how MDK handling templates, I have already given you a solution and explanation. If you have questions, please let me know.

**Comment by GorgonMeducer** [comment]
Since we already decide to use template for porting display/indicator/file system then NO need to add a dedicated component called porting:

image

In MDK system, we can already add those porting files as templates:

image

But the problem is, you only including header files as templates but not the source files:

image

Listing all source and header files of porting in Essential is sufficient : 

image

**Pull request closed without merging**
