### PR TITLE
fixed OOB while deleting CJK character in textarea

### PR DESCRIPTION
**Pull request by mariotaku**
### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Can you send a code snippet in which the original code wasn't working well?

**Comment by mariotaku** [comment]
@kisvegabor It can be produced in this way:
1. Send CJK 2 characters by `lv_indev_data_t.key`, that does not exist in font `lv_textarea` is currently using. 
2. Press backspace to delete characters in `lv_textarea`, until cursor reaches start
3. You will notice that placeholder still didn't appear
4. Press keyboard right for few times then press backspace
5. OOB in lv_txt.

Deleting CJK character should delete things in `char[]` by 3 bytes. Somehow, there is one left, causing `old_len < len`, then `pos` got integer overflow, causing illegal access to `txt`.

**Comment by mariotaku** [comment]
So I think there is root cause to this which needs to be fixed.

**Comment by mariotaku** [comment]
Oh I see! I think the root cause is a bug in my input driver. It sends 4 bytes instead of 3, causing this issue. Sorry. I think this can be closed.

**Pull request closed without merging**
