### PR TITLE
widgets: add a new widget animation image

### LINKED ISSUE #2090: How to support animation format(e.g. gif) through lv_img_decoder_t?
### Introduce the problem

lv_img_decoder_t doesn't have the fields or callback to provide the mutiple frame data, how to write a portable widget to show the animation?

### Examples and cases

Improve img widget so show the animation.

### Suggested solution

Add animation info(e.g. frame_rate, frame_number, loop) to lv_img_header_t or lv_img_decoder_dsc_t. Add new callback(switch the frame) in lv_img_decoder_t.

### PR DESCRIPTION
**Pull request by ZhaoQiang-b45475**
This widget could achieve animation effects by
constantly switching a series imgs.

Signed-off-by: Hui Song <hui.song_1@nxp.com>
Signed-off-by: Xiaolin He <xiaolin.he@nxp.com>

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thanks for the PR.
We are freezing v7 and new features should be added based on v8. 

We are still polishing and writing docs for v8 so, let's wait a little with this PR.

For v8 we have created a new repository, called [lv_components](https://github.com/lvgl/lv_components). This repo is meant to be a good place for community-created widgets.
 
See the summary of changes in v8 here:  https://github.com/lvgl/lvgl/blob/master/docs/ROADMAP.md#v8
I think these changes don't affect this widget hence moving to `lv_components` should be straightforward.

I'll let you know when v8 is ready to be tested. Probably 1-2 weeks.

**Comment by ZhaoQiang-b45475** [comment]
Got it, Thank you!

**Comment by ZhaoQiang-b45475** [comment]
Hi,
Is v8 available now? is there a guider showing how to use v8 including lv_component?

**Comment by kisvegabor** [comment]
We postponed v8 a little because decided to add some features. I can't say an exact date now, but I assume it will be released in February.

The docs for using `lv_components` will be also ready for the release of v8.

**Comment by kisvegabor** [comment]
Still working on v8. 
I'll write here we are ready to merge this.

**Comment by ZhaoQiang-b45475** [comment]
Hi kisvegabor,
Are v8 and lv_component ready now?

**Comment by kisvegabor** [comment]
Hi,

Meanwhile, we have made a little bit of simplification.  Instead of  `lv_components`, we created the [extra](https://github.com/lvgl/lvgl/tree/dev/src/extra)directory in the lvgl repo.

v8 is getting stable, and you can easily try it via the dev branch of [lv_sim_eclipse_sdl](https://github.com/lvgl/lv_sim_eclipse_sdl). 

So could you rebase your changes for the `extra` directory of lvgl?

**Comment by ZhaoQiang-b45475** [comment]
Hi,
as steps, 
1. I clone https://github.com/littlevgl/pc_simulator_sdl_eclipse.git 
2. install SDL..
3. checkout pc_simulator_sdl_eclipse to branch dev which including lvgl with v8
4. use cmake and make -j4 to build
meeting some compile issue, so I'd like to know if I use the correct branches for  pc_simulator_sdl_eclipse?
**the error log as below**:
_CMakeFiles/main.dir/lv_examples/src/lv_demo_widgets/lv_demo_widgets.c.o: In function `profile_create':
lv_demo_widgets.c:(.text+0xd21): undefined reference to `img_demo_widgets_avatar'_

**Comment by kisvegabor** [comment]
Now beta is officially out for testing. See here: https://github.com/lvgl/lvgl/issues/2144
The demo widget should work too.

**Comment by xiaoxiang781216** [comment]
Let's continue on the new PR: https://github.com/lvgl/lvgl/pull/2167

**Pull request closed without merging**
