### PR TITLE
Fixed include paths

### PR DESCRIPTION
**Pull request by jozba**
Signed-off-by: Jozef Bastek <jozef.bastek@nxp.com>

### CODE REVIEW

**Comment by jozba** [comment]
I need these changes in order to pass tests/build.py script. Is it working right now out of the box in dev branch?

**Comment by kisvegabor** [comment]
It works well for me. 

[LVGL_DIR](https://github.com/lvgl/lvgl/blob/master/tests/Makefile#L5) is set as an [include path](https://github.com/lvgl/lvgl/blob/master/tests/Makefile#L18). 

It seems somehow this path is not picked for you. Are you on windows? If so it might be a `/` or `\` issue. 

Does it help if you change `LVGL_DIR ?= ${shell pwd}/../..` to `LVGL_DIR ?= ${shell pwd}\..\..`?

**Comment by jozba** [comment]
Hi, 
I do the test on linux. I had problems with python on windows that were caused by weird handling of / and \\. 

I found the root cause of the issue. `LVGL_DIR ?= ${shell pwd}/../..` step out of project directory completely, and then the files expects include in `lvgl/lvgl.h` . However, my project folder is not called lvgl, it is lvgl-test-something. When I rename project folder to 'lvgl', build works. 

I think include paths should not depend on top-level project directory name. All references should stay "inside" the project folder, whatever name it has.

**Comment by jozba** [comment]
And probably that's the reason why CI build pass - does it checkout the code into folder called lvgl? Mentioned also [here](https://github.com/lvgl/lvgl/pull/1824#issuecomment-701504066)

**Comment by kisvegabor** [comment]
Ah, that explains it. It this case your fixes are quite appropriate.

I merge it, thank you!

**Comment by jozba** [comment]
I am further looking at the makefiles. It seems like another possible fix would be to change `LVGL_DIR_NAME ?= lvgl` to `LVGL_DIR_NAME ?= lvgl-test-something` in [here](https://github.com/lvgl/lvgl/blob/34e0fefeb3e41deb470a7a39685d0e23eeee60a3/tests/Makefile#L6). In this case, actually, it's a configuration problem on my side. The system is built in the way that jumps "out" of project dir and it enters it again via LVGL_DIR_NAME in [lvgl.mk](https://github.com/lvgl/lvgl/blob/34e0fefeb3e41deb470a7a39685d0e23eeee60a3/lvgl.mk#L1). I think the fix in PR is more appropriate, as the code is inside the repo. But in case of referencing to **external** project (e.g. lv examples), DIR_NAME should be configured properly.

**Comment by kisvegabor** [comment]
I agree that it's better to avoid hardcoded names so I think your solution is better then Makefiles "hacks".

**Pull request merged**
