### PR TITLE
fix: add missing lv_theme include

### PR DESCRIPTION
**Pull request by Johennes**
### Description of the feature or fix

I'm not sure if I'm doing something wrong but `master` currently doesn't compile for me without this include.

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [x] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [x] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [x] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [x] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [x] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [x] Use typed pointers instead of `void *` pointers
- [x] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [x] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [x] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [x] `struct`s should be used via an API and not modified directly via their elements.
- [x] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [x] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [x] Arguments must be named in H files too.
- [x] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
It complied for me and the CI also passes.
image

What is the exact error message?

**Comment by Johennes** [comment]
Here is the error:

```
[1/3] Compiling C object unl0kr.p/lvgl_src_core_lv_disp.c.o
FAILED: unl0kr.p/lvgl_src_core_lv_disp.c.o 
cc -Iunl0kr.p -I. -I.. -I../lvgl -I../lv_drivers -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -O0 -g '-DUL_VERSION="1.0.0"' -MD -MQ unl0kr.p/lvgl_src_core_lv_disp.c.o -MF unl0kr.p/lvgl_src_core_lv_disp.c.o.d -o unl0kr.p/lvgl_src_core_lv_disp.c.o -c ../lvgl/src/core/lv_disp.c
../lvgl/src/core/lv_disp.c:768:42: error: unknown type name ‘lv_theme_t’; did you mean ‘lv_timer_t’?
  768 | void lv_disp_set_theme(lv_disp_t * disp, lv_theme_t * th)
      |                                          ^~~~~~~~~~
      |                                          lv_timer_t
../lvgl/src/core/lv_disp.c:786:1: error: unknown type name ‘lv_theme_t’; did you mean ‘lv_timer_t’?
  786 | lv_theme_t * lv_disp_get_theme(lv_disp_t * disp)
      | ^~~~~~~~~~
      | lv_timer_t
../lvgl/src/core/lv_disp.c:786:14: error: conflicting types for ‘lv_disp_get_theme’; have ‘int *(lv_disp_t *)’ {aka ‘int *(struct _lv_disp_t *)’}
  786 | lv_theme_t * lv_disp_get_theme(lv_disp_t * disp)
      |              ^~~~~~~~~~~~~~~~~
In file included from ../lvgl/src/core/lv_disp.c:9:
../lvgl/src/core/lv_disp.h:472:22: note: previous declaration of ‘lv_disp_get_theme’ with type ‘struct _lv_theme_t *(lv_disp_t *)’ {aka ‘struct _lv_theme_t *(struct _lv_disp_t *)’}
  472 | struct _lv_theme_t * lv_disp_get_theme(lv_disp_t * disp);
      |                      ^~~~~~~~~~~~~~~~~
../lvgl/src/core/lv_disp.c: In function ‘lv_disp_get_theme’:
../lvgl/src/core/lv_disp.c:789:16: warning: returning ‘struct _lv_theme_t *’ from a function with incompatible return type ‘int *’ [-Wincompatible-pointer-types]
  789 |     return disp->theme;
      |            ~~~~^~~~~~~
[2/3] Compiling C object unl0kr.p/cursor.c.o
ninja: build stopped: subcommand failed.
```

**Comment by Johennes** [comment]
I think the problem is that I'm using `#define LV_USE_THEME_DEFAULT 0`. So this `include` isn't compiled in: 

```
#if LV_USE_THEME_DEFAULT
    #include "../themes/default/lv_theme_default.h"
#endif
```

When I remove the wrappign `#if` / `#endif`, it compiles fine without explicitly including `lv_theme.h`.

**Comment by kisvegabor** [comment]
You are right and disabling the default theme wasn't even tested in our CI.

I've just update the CI and fixed the include.

**Pull request closed without merging**
