### PR TITLE
Finalise chart function updates

### PR DESCRIPTION
**Pull request by pete-pjb**
Hi @kisvegabor,

I had to change the signal handler slightly to gain access to the full lv_chart_series_t structure please can you check to make sure I have done this correctly. 

Sorry about the CLA license please ignore it, it is caused by my poor office VPN connection...

Cheers,

Pete

### CODE REVIEW

**Comment by kisvegabor** [comment]
Looks good, thank you!

**Comment by kisvegabor** [comment]
I forget 2 things. Can you update the [docs](https://github.com/lvgl/docs/blob/latest/widgets/chart.md) and the CHANGELOG with new features?

**Comment by pete-pjb** [comment]
> I forget 2 things. Can you update the [docs](https://github.com/lvgl/docs/blob/latest/widgets/chart.md) and the CHANGELOG with new features?

Hi @kisvegabor,

I can do this no problem, but please excuse my ignorance, I haven't worked with any of this stuff before, is there a link you can provide where I can read about how you are doing things with the  documentation please? Once I know what to do I'll happily sort it out.

Thanks,

Pete

**Comment by pete-pjb** [comment]
@kisvegabor ,

I've had a look at it now and it looks like I can edit the files directly in my browser on Github, is this how you usually do things for docs?  Or should I fork the docs and submit a PR.

Cheers,

Pete

**Comment by kisvegabor** [comment]
Yesterday I updated the docs to make contribution clearer. 
Here is the relevant part: https://docs.lvgl.io/latest/en/html/contributing/index.html#add-features

**Comment by pete-pjb** [comment]
Hi @kisvegabor,

Thanks for the link.

I have updated the change log file directly on Github now.  If there's any problem with my update please let me know and I will fix it.

I will now merge this and close it thanks again for you patience while I am learning about Github.

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
Great! Thank you! :slightly_smiling_face:

**Pull request merged**
