### PR TITLE
Specific compiler attribute for tick

### PR DESCRIPTION
**Pull request by Zaltora**
Hi,
Your library is awesome, i will use it with esp8266/esp32 µC component.
I suggest to add inline and optional attribute to tick increment function.
It will allow to put this function into instruction RAM for architecture that support this.

I just discovered your library, i don't no if other function are used extensively. Can be useful to add option for them too. (like `lv_task_handler`)

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,
thank you for contributing! 
It a good idea to enable putting frequently called functions into RAM.
As you suggested, can you add this to lv_task_handler too?
And please put this options into the misc settings part of lv_conf_templ.h with /*Compiler  attributes*/ title.

**Comment by Zaltora** [comment]
I suppose the user is using once ` lv_task_handler` in a loop and can got `inline` too.

**Comment by kisvegabor** [comment]
Great, thank you!
Only one think: the function called `lv_task_handler` and the define `LV_ATTRIBUTE_TASK_HANDLE` without 'R' at the and.

**Comment by kisvegabor** [comment]
I just modified the base to `beta`. I will release a new v5.0.2 soon and it will contain your updates!
Thank you very much!

By the way if you are using LittelvGL on ESP8266 (I suppose with SPI to drive a TFT) you can shar your project in [lv_boards](https://github.com/littlevgl/lv_boards) repo!

**Comment by Zaltora** [comment]
My plans was to add directly "lvgl" as submodule to [esp-open-rtos](https://github.com/SuperHouse/esp-open-rtos). You got the same license. And it is the best GUI open source library i found.
I use SSD1306/ILI9341 screen, so i will try to add drivers to [lv_drivers](https://github.com/littlevgl/lv_drivers)
The project esp-open rtos will got example and i will see how work your repo [lv_boards](https://github.com/littlevgl/lv_boards/tree/master/linux_frame_buffer)  to add it.

**Comment by kisvegabor** [comment]
Awesome! If you have any questions I will kindly help!

**Pull request merged**
