### PR TITLE
chore(logo): update lvgl logo

### PR DESCRIPTION
**Pull request by lhdjply**
### Description of the feature or fix

chore(logo): update lvgl logo

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by lhdjply** [comment]
I want to update the [test_img_lvgl_logo.jpg](https://github.com/lvgl/lvgl/blob/master/tests/src/test_assets/test_img_lvgl_logo.jpg) file at the same time, but why does the image generated by test_tjpgd display abnormally.
Look at the picture below, the L display of LVGL is abnormal

## source file
test_img_lvgl_logo
## output file
jpg_1

**Comment by kisvegabor** [comment]
Could you update to new logos too?

**Comment by lhdjply** [comment]
@kisvegabor I have update,please see https://github.com/lhdjply/lvgl/blob/icon/tests/ref_imgs/libs/jpg_1.png

**Comment by lhdjply** [comment]
The image generated by parsing BMP with vg_lite is blank,https://github.com/lvgl/lvgl/blob/master/tests/ref_imgs_vg_lite/libs/bmp_1.png  @FASTSHIFT

**Comment by FASTSHIFT** [comment]
> The image generated by parsing BMP with vg_lite is blank, https://github.com/lvgl/lvgl/blob/master/tests/ref_imgs_vg_lite/libs/bmp_1.png @FASTSHIFT

You can temporarily ignore this error because the vg_lite porting layer currently does not support the `lv_image_decoder_get_area` drawing mode, which means that the decoder needs to fully decode the image into memory before it can be displayed.

**Comment by kisvegabor** [comment]
I've just pushed a fix the JPEG decoder

**Comment by lhdjply** [comment]
> I've just pushed a fix the JPEG decoder

Thanks 

image
How should this ci be fixed?

**Comment by lhdjply** [comment]
I have found the problem, I forgot to modify the file length in micropy.py. Now we can start preparing for the merger.

**Review by FASTSHIFT — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
It's massive! Thank you for the great work!

**Pull request merged**
