### PR TITLE
lv_preload.c Add feature to allow setting whether the animation is pl…

### PR DESCRIPTION
**Pull request by BrianPugh**
…ayed in forward/reverse. Changes the default spinner behavior from counterclockwise to clockwise.

Side comment: I see that `lv_anim_del` is commented out; is this going to cause issue?

### CODE REVIEW

**Comment by kisvegabor** [comment]
Very clean implementation, thank you! 

Could you please use the `DIR` and `ANIM` abbreviations?

I don't know why `lv_anim_del` is commented out. It should be enabled. Can you test it?

**Comment by BrianPugh** [comment]
Let's make `lv_anim_del` a separate PR/commit incase it causes issues. But in my short testing, uncommenting it had no ill effects.

If abbreviating to `dir` and `anim`, should we abbreviate `lv_set/get_animation_time` as well?

**Comment by kisvegabor** [comment]
> Let's make lv_anim_del a separate PR/commit incase it causes issues. But in my short testing, uncommenting it had no ill effects.

I'm almost certain that it will be fine to re-enable it. Let's open an issue if you face any related problems.

> If abbreviating to dir and anim, should we abbreviate lv_set/get_animation_time as well?

Yes, I think it's still easy to understand but much shorter. Do you agree?

**Comment by BrianPugh** [comment]
Alright, I uncommented `lv_anim_del` and I changed the abbreviations. Should be good to merge!

**Comment by kisvegabor** [comment]
Great, thank you!

**Pull request merged**
