### PR TITLE
fix(draw): fix rgb565 with LV_BLEND_MODE_MULTIPLY

### PR DESCRIPTION
**Pull request by JLJimmyH**
### Description of the feature or fix
Fix incorrect color blending for blue component in LV_BLEND_MODE_MULTIPLY

### CODE REVIEW

**Review by FASTSHIFT — DISMISSED** [review]

**Comment by FASTSHIFT** [comment]
Please rerun the [test](https://github.com/lvgl/lvgl/blob/master/tests/README.md) program to generate a new reference image.

**Comment by kisvegabor** [comment]
FYI, on Windows you can use WSL, but if you are facing any issues, just let u know, we can update the images, too.

**Comment by JLJimmyH** [comment]
Thank you, but I haven't set up the WSL environment on my Windows machine yet. I'm currently working on creating it, but it might take some time to complete.

**Review by FASTSHIFT — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
It seems you set up quite quickly :slightly_smiling_face:  

Thank you!

**Pull request merged**
