### PR TITLE
lv_misc: Add icons as fonts

### PR DESCRIPTION
**Pull request by ajaybhargav**
Using icons as font uses less space. Font size is 30px. Fonts can be used as text. All icons are defined in lv_misc/fonts/icons.h
e.g. for drive icon simply create a label; set font as ICON_FONT and text as ICON_DRIVE

Signed-off-by: Ajay Bhargav <contact@rickeyworld.info>

### CODE REVIEW

**Comment by kisvegabor** [comment]
Very good idea! However it needs some rework where  lv_img objects are used now, e.g. lv_win_add_ctrl_btn(), where an image can be added to the control button. It should be upgraded to accepts texts too.

**Comment by ajaybhargav** [comment]
yes I was coming to that. Since It makes it difficult when creating windows. This part only belongs to lv_misc which can be merged. lv_win can be updated later on.

**Comment by kisvegabor** [comment]
Maybe when the set file is not exists, then write the file name instead.

**Comment by kisvegabor** [comment]
Sorry for closing the issue, it was mistake :)
Ok, I will try it and merge if everything is fine.

**Comment by ajaybhargav** [comment]
or should I change the names to something like FONT_ICON_* so no confusion

**Comment by kisvegabor** [comment]
Could you generate these icons in a greater size too? I saw that it is 30px high but at least an other (e.g. 60px high) could be great.

**Comment by ajaybhargav** [comment]
Sure I will do that. Do you want to change names? ICON_ to FONT_ICON_?
ICON60_ for 60px icons?

**Comment by kisvegabor** [comment]
I think the name "ICON" is little bit confusing because it is already used by image icons.  Maybe the name "SYMBOL" could be better.  So FONT_SYMBOL_30, FONT_SYMBOL_60 etc. I will rename the current ICON to SYMBOL_30.

**Comment by ajaybhargav** [comment]
ok 👍

**Comment by kisvegabor** [comment]
Hi. 
I would like to release some changes including the symbols. I just would like to know shall I wait for the 60 px height symbols. If you can send them in this week I can add them in the next version!

**Comment by ajaybhargav** [comment]
Hi, Sure I will send you in this week. I just got tied up with some work. could not test gauge also. Will update you in few days :)

**Comment by kisvegabor** [comment]
Great, thanks! :)

**Review by kisvegabor — COMMENTED** [review]
Thank you very much! I will add them!

**Comment by ajaybhargav** [comment]
You could have merge this considering a contribution.

**Comment by kisvegabor** [comment]
Sorry for that, you are right. 
I forgot that the merge from here will be shown as contribution.
I merged!

**Comment by ajaybhargav** [comment]
Thanks! :)

**Comment by kisvegabor** [comment]
Hi!
I think adding audio related icons would be useful. The numbers ('0' - '9') still free. Can you add:
- play
- stop
- pause
- prev
- next
- speaker
- muted speaker
icons?

Or if you tell me how did you do that I can add them too. :)

If you have any suggestion on others icons I would hear them happily! :)

**Comment by ajaybhargav** [comment]
I will have to test lvgl latest version anyway :) I will add those icons no problem. 👍 
FYI, I use [font awesome](http://fontawesome.io/) to get icons.

I had something in my mind.. related to fonts. Coz if I want to add a font I have to make changes to the core files (which I dont like :)). I want original repo to stay clean. It would be great if there are procedure to register and unregister fonts etc... so noone has to make changes to core. This will also result in a clearner code. What you say?

**Comment by kisvegabor** [comment]
Great, thank you!
Now I'm planning to make a major release. I've done a lot of performance improvements and also added a LV_FONT_ANTIALIAS option. But I've noticed that the structure fileds and function names are not consistent everywhere so I've done some renames so far. You can find this changes in 'beta' .

You are right about the current way of adding fonts. I will think about that!

**Comment by ajaybhargav** [comment]
LV_FONT_ANTIALIAS was kind of needed :) I have seen you pushing lot of commits and I have gone through a few of them. I will be testing lvgl as soon as I get time ;)

The simplest way to do this is... having (linked) list of fonts once they get registered. Usually in embedded system I dont think anyone will unregister a font coz thats not gonna save space anyway. So having a simple add_font function with a single side linked list will do the job. This can be done for drivers (lcd and touchscreen) too, A simple hook function (pointer) if defined then call that function else choose from one of the pre defined drivers. 

My though of a library is to have a completely abstract code which can be updated anytime in future if needed without doing any hacks in it.

**Comment by kisvegabor** [comment]
Great! I'm waiting for your feedback!

You are right, only the font_add has to be realized. But I still don't know how to refer to a font? `font_add(FONT_ARIAL_20, &arial_20_dsc)` 
where FONT_ARIAL_20 is define in lv_conf.h? And then 
`font_dsc * font_get(FONT_ARIAL_20)`?

I try to keep the library abstract until it is possible. But sometimes it is time to update and change because too much thinks came and the code become messy.  I do API changes only in major versions, the minor updates are always backward compatible.

**Comment by ajaybhargav** [comment]
I will go through code once... and will share my findings. I will probably open a different thread for it.

**Comment by kisvegabor** [comment]
OK, thanks! I will inform you I've already figured out something.

**Comment by kisvegabor** [comment]
It you want to try the draw speed optimizations I suggest you this commit: https://github.com/littlevgl/lvgl/commit/7bb849f4eb69653806d1b6aaac61bedcee86634d

**Pull request merged**
