### PR TITLE
Various v8 compilation fixes

### PR DESCRIPTION
**Pull request by embeddedt**
### Description of the feature or fix

I'm trying to get v8 to compile with my project. The style system was producing a bunch of warnings and errors related to missing or unneeded casts. These have been fixed.

Additionally, I refactored the style generation script so that manual copy-pasting into header files is not needed.

More fixes will be added as I continue tackling the errors. :wink:

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Review by kisvegabor — APPROVED** [review]
Awesome, thank you!

Glad to hear that you are trying it out! 
Somehow I anticipated that even if I have no warnings others will have many. :laughing:

**Comment by embeddedt** [comment]
Any idea why this is happening? I looked through a few headers and the `extern C` opening and closing portions seemed to match.

```
lv_widgets/lv_img.h: At global scope:
lv_widgets/lv_img.h:191:1: error: expected declaration before '}' token
  191 | } /* extern "C" */
      | ^
In file included from lvgl/lvgl.h:53,
                 from app.cpp:16:
lv_widgets/lv_bar.h:155:1: error: expected declaration before '}' token
  155 | } /* extern "C" */
      | ^
In file included from app.cpp:16:
lvgl/lvgl.h:139:1: error: expected declaration before '}' token
  139 | }
      | ^
```

**Comment by kisvegabor** [comment]
I've checked that all `{` has its closing pair with:
```
> find -name "*.h" | xargs grep -s '} /\* extern "C" \*/' | wc -l
113
> find -name "*.h" | xargs grep -s 'extern "C" {' | wc -l
113
```

I've tried only with C so far but will try with C++ today as well.

**Comment by kisvegabor** [comment]
Huh, it took a few hours but I found it.
See 0d3a206f and c35b645c

**Comment by embeddedt** [comment]
Thanks! It's amazing how a misplaced `#endif` can cause a cascade of unrelated errors.

**Comment by kisvegabor** [comment]
I was also surprised why it caused so much trouble.

**Comment by kisvegabor** [comment]
Regarding the warnings: I know that the prototype of the examples is still not added to their header files.

**Comment by kisvegabor** [comment]
Can we merge this PR?

**Comment by kisvegabor** [comment]
I've just merged dev-v8 to dev so changed the base of the PR.

**Comment by embeddedt** [comment]
Sure; I'll just send a new one with more fixes if I need to.

**Comment by kisvegabor** [comment]
Great, thanks!

**Pull request merged**
