### PR TITLE
fix(draw_sw): wrong image buffer calculation

### LINKED ISSUE #7386: `test_image` Failing Intermittently in CI Tests
### LVGL version

v9.3

### Platform

Ubuntu Linux -- the CI test platform

### What happened?

In my last 10 or so pushes to PRs (new and existing), `test_image` runs as part of the CI test called `C/C++ CI / Build ESP IDF ESP32S3` as well as in `Run tests with 32bit build`, and it has been failing in about 25-40% of the cases.  When it fails, simply pushing a dummy commit causes it to run again, and in more than half the cases so far, it has succeeded the next time it runs, when the change in the commit was not related to what it tests.

Example:  I just pushed 3 commits to PR #7374 and the first 2 failed this test, and the 3rd succeeded, and the only changes were to documentation, not code.  Here is the result of the 3rd push so you can see evidence that the failures are intermittent.  This is costing production time to be wasted and it is likely more than my own.

image

I don't know what causes that, but I am intensely interested since it is interfering with production, plus I am very interested to know how it can be that a test is not *consistent* when running in a digital environment.

### How to reproduce?

Just push any commits to any PRs -- new or existing, and note that this test will fail in approximately the above % of cases.

### PR DESCRIPTION
**Pull request by XuNeo**
Fix #7386

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by FASTSHIFT — APPROVED** [review]

**Review by liamHowatt — APPROVED** [review]
Nice find

**Comment by pete-pjb** [comment]
@XuNeo,

Thank you for finding this!  I have spent quite some time thinking a flickering issue I was experiencing was down to my display driver and this was ultimately the answer! 

Kind Regards,

Pete

**Comment by kisvegabor** [comment]
Hi Pete,

Its great to hear from  you again. I'm happy that you are still actively using LVGL! :slightly_smiling_face:

**Comment by pete-pjb** [comment]
Hi Gabor, @kisvegabor 

Great to hear from you too! 🙂 I hope you and your family are well...  

I am very pleased to see your continued success and the continuing growth of LVGL.  The growth of the development community is excellent and going from strength to strength... It is all much deserved in my opinion. 🙂 👍 

Yes I am still actively using LVGL(As I am currently continuously developing I just check out the master branch daily) it's still the same, very long term project, I am working on.  At the beginning of the year I moved the hardware from 2 x Zynq 7000 devices to one single Zynq Ultrascale+ SOC and upgraded the display to full HD touch screen... This has consumed much time (hence my lack of contribution to LVGL recently 🙁) the Ultrascale+ is very much supported only for Linux by AMD(Xilinx) and I am unable to use Linux for various technical and licensing reasons in our project.  This has meant I have had to port my own AMP and SMP RTOS builds and write many drivers from scratch and it is an enormous amount of work, I have trouble remembering everything all the time.  Hopefully I will get to a point where I can get a full prototype into the field in the next 6 months and then hopefully I will get some time to do other things!

With Kindest Regards,

Pete

**Comment by kisvegabor** [comment]
Yes, we are doing too too. :slightly_smiling_face: 

It's pretty interesting and it really seems like a big work. Good luck with it! 

Please do let us know if you need any help for LVGL's side.

**Pull request merged**
