### PR TITLE
docs(espressif): Update Espressif's documentation with esp_lvgl_port

### PR DESCRIPTION
**Pull request by tore-espressif**
### Description of the feature or fix

* Update Espressif's documentation with esp_lvgl_port
* Also update demos section with updated links

**EDIT:** I can see that there is no CI check for documentation. How can I check that I did not break anything?

### CODE REVIEW

**Comment by tore-espressif** [comment]
cc @espzav @Indastri

**Comment by tore-espressif** [comment]
@kisvegabor This is the documentation update that we were talking about :)

**Review by kisvegabor — APPROVED** [review]
Thank you Tomas! It's exactly what I've imagined! 

cc @vwheeler63 @liamHowatt

**Comment by kisvegabor** [comment]
Fixes #6574

**Comment by kisvegabor** [comment]
These just came to my mind:
- Can we add a section (or a link) about optimizing performance?
- Shall we explain some basic ESP related setting for new projects, e.g. setting `LV_OS_FREERTOS`?

**Comment by kisvegabor** [comment]
I prefer proceeding in smaller steps. So let's merge it! Just waiting for one more review.

**Review by vwheeler63 — APPROVED** [review]
I approve as to grammar (nice work) and links are valid.  Having (yet) no experience with ESP32, I cannot vouch for anything specific to the ESP32, but otherwise it looks sound.

**Comment by tore-espressif** [comment]
> I approve as to grammar (nice work)

ChatGPT helped me out here :D

**Review by liamHowatt — APPROVED** [review]
Nice!

**Pull request merged**
