### PR TITLE
SDL2 Support for Gradients #3848

### PR DESCRIPTION
**Pull request by mariotaku**
### Description of the feature or fix

This PR adds gradient drawing support for #3848 .

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by mariotaku** [comment]
Right now, gradients with radius can't be rendered properly yet.

**Comment by kisvegabor** [comment]
Thanks! Let me know when I can merge it.

**Comment by mariotaku** [comment]
Great. I'll be trying to add gradient with radius support, then it will be ready to merge.

**Comment by mariotaku** [comment]
@kisvegabor This PR can be reviewed and merged. I'd also like to invite @LuWB to verify if this work.

**Comment by mariotaku** [comment]
After this gets merged, could you please cherry-pick it and add to master or `arch/driver` branch? I'll add SDL GPU support there.

**Comment by LuWB** [comment]
I replaced these three files to lvgl-r8.3.3:lv_draw_sdl_rect.c/lv_draw_sdl_rect.h/lv_draw_sdl_texture_cache.h.
lvgl works well.

**Comment by kisvegabor** [comment]
Thank you. The failing CI is not related. 

Do you plan to cherry pick it to `master`? I think it's not critical now as many changes will come to `master`  so the drawing layer in `master` can be updated in one step later.

**Comment by mariotaku** [comment]
Great. I'm a bit lost on which branch to work on (I'm now on `arch/driver` now though). Which branch do you think better fit this change?

**Comment by LuWB** [comment]
Agreed. After all, lvgl is mainly used in embedded devices.

**Comment by kisvegabor** [comment]
> Great. I'm a bit lost on which branch to work on (I'm now on arch/driver now though). Which branch do you think better fit this change?

Most of the refactoring will come in [feat/parallel-rendering](https://github.com/lvgl/lvgl/tree/feat/parallel-rendering) but it's in exploration state. I think the draw API will be much simpler. I'll let you know when it's more mature. Until that I think `arch/driver` is fine.

**Pull request merged**
