### PR TITLE
feat(tests): Include debug information in test runners

### LINKED ISSUE #2566: [unit testing] Test runners doesn't include debug information
### Perform all steps below and tick them with [x]
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Currently the test runners doesn't include debug information, so if you get a SEGFAULT while running your test, or simply you want to debug your test, you're forced to add debug information, it would be better if the runners include it, we are not currently testing performance.

See https://github.com/lvgl/lvgl/pull/2551 for more information

### To Reproduce
Load a test runner into gdb, it will tell you there's no debug information.

### Expected behavior
Test runners with debug information.

### Screenshots or video

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Fixes #2566 (based on https://github.com/lvgl/lvgl/pull/2551#issuecomment-919649607)

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]
Based on this being opened after https://github.com/lvgl/lvgl/pull/2551#issuecomment-920491844, I assume you did get the symbol information working locally?

**Comment by C47D** [comment]
I did using the file command, the output indicates the runners have debug information and the executable is not stripped.

But it would be good if someone else could confirm it.

**Comment by embeddedt** [comment]
I'll check it right now.

**Comment by embeddedt** [comment]
Sorry for the delay. I can see debug information on `build_tests/test_obj_tree` in GDB, so this looks good.

**Pull request merged**
