### PR TITLE
Fix(margins)

### PR DESCRIPTION
**Pull request by jusodi**
Prior to this fix, margins only worked for vertical layouts. This honours them for horizontal layouts.

### CODE REVIEW

**Comment by W-Mai** [comment]
please rebase your code, thanks

**Comment by kisvegabor** [comment]
Is it for LVGL v7?

**Comment by jusodi** [comment]
Yes
________________________________

**Comment by W-Mai** [comment]
> Please explain?
> […](#)
> ________________________________ From: Benign X ***@***.***> Sent: Thursday, September 21, 2023 02:02 To: lvgl/lvgl ***@***.***> Cc: Julian Mitchell ***@***.***>; Author ***@***.***> Subject: Re: [lvgl/lvgl] Fix(margins) (PR #4580) please rebase your code, thanks — Reply to this email directly, view it on GitHub<https://us-west-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL2x2Z2wvbHZnbC9wdWxsLzQ1ODAjaXNzdWVjb21tZW50LTE3MjkxNTY2MzI=&i=NWZjNjlmYTY3MGEzMTgwZTdiZjRmNmIw&t=eGhyeGJ0MXZ0OG1ySmJteFFYclg5aHRxMXVyeEFyUWxGQnI3SzBYZjJrdz0=&h=9a5453a854cb40c1978b82cbc163d39e&s=AVNPUEhUT0NFTkNSWVBUSVZ-CzEl059Ym1RlqwKl3ZhNfC-dR2N5IDL9CUAdMA_6tA>, or unsubscribe<https://us-west-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMvdW5zdWJzY3JpYmUtYXV0aC9BWDRWREpLSUFJRjNMNUNPS0IyRjRIM1gzUDdFSEFOQ05GU002QUFBQUFBNUFIVEIzWQ==&i=NWZjNjlmYTY3MGEzMTgwZTdiZjRmNmIw&t=RTlsYlltbXJLTDJPenNQelA4MWhPU3lzdCtiTzFWTXMyMzd2TEc2WE8rMD0=&h=9a5453a854cb40c1978b82cbc163d39e&s=AVNPUEhUT0NFTkNSWVBUSVZ-CzEl059Ym1RlqwKl3ZhNfC-dR2N5IDL9CUAdMA_6tA>. You are receiving this because you authored the thread.Message ID: ***@***.***>

your commit stream include many commit doesn't belongs to you, and it's recommended to make your upstream more clearly.

**Comment by kisvegabor** [comment]
I'm sorry, but v7 is quite old and we it already not supported. :slightly_frowning_face: 

I can't merge this feature, because it might cause issues in existing projects.

Anyway, thank you very much for your willingness to help.

**Pull request closed without merging**
