### PR TITLE
rename span interface

### PR DESCRIPTION
**Pull request by guoweilkd**
### Description of the feature or fix

for the reasion:#1763, rename span interface.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [x] Update the documentation

### CODE REVIEW

**Comment by amirgon** [comment]
https://github.com/lvgl/lvgl/blob/c6734e14566c7fe1f0007986ffa2ff3323685c44/src/extra/widgets/span/lv_span.c#L68

Should be static and GC root?

**Comment by kisvegabor** [comment]
It's only used locally in `lv_draw_span`  to save local variables. For me, it seems it doesn't need to be GC root as it has nothing to do with malloc.

**Comment by amirgon** [comment]
> It's only used locally in `lv_draw_span` to save local variables. For me, it seems it doesn't need to be GC root it has nothing to we malloc.

Ok, it's clear now.

Change looks good for Micropython, I vote for merging.

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
Merged!
Thanks.

**Pull request merged**
