### PR TITLE
refactor(style) store constant property IDs with a pointer instead of directly

### PR DESCRIPTION
**Pull request by embeddedt**
### Description of the feature or fix

Implements changes proposed in https://github.com/lvgl/lvgl/issues/3481#issuecomment-1186029239. There is no change to the public API surface.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Looks good! And thanks for adding a test too! :slightly_smiling_face:

**Comment by kisvegabor** [comment]
I'll update flex and grid.

**Comment by embeddedt** [comment]
If necessary we can prefix the added variables with `_` to prevent them from showing up in MicroPython. I'm putting this here as a reminder to check once it can be built again.

**Comment by kisvegabor** [comment]
It's good idea not only for Micropython but for auto completion in general too.

**Comment by embeddedt** [comment]
Added here: https://github.com/lvgl/lvgl/commit/ca8f0ab549aa087d0723f61e20c3405ce078e966

**Comment by kisvegabor** [comment]
Great! :+1:

**Pull request merged**
