### PR TITLE
fix(cmake-build): Fix example and demo build on esp-idf

### PR DESCRIPTION
**Pull request by wangyz1997**
### Description of the feature or fix

There are options in `Kconfig` files for users to choose whether to build examples and demos, and `esp-idf` supports `menuconfig`. However, when user enables example or demo to be built, they are actually not built, which is quite confusing. This PR fixes this issue.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Looks good. I'm just thinking about if it will cause any problem if we enable all the demos by default.  Will ESP ignore the demos (and their assets) during linking if their `*_create()` function is not called?

**Comment by wangyz1997** [comment]
Whether to include code under `demos` folder in the build depends on the new option `LV_BUILD_DEMOS`, which is turned off by default. I have the `LV_USE_DEMO_*` options turned on by default, and they depend on `LV_BUILD_DEMOS`, so when user turns on `LV_BUILD_DEMOS` option, all the `LV_USE_DEMO_*` options are turned on automatically , which I think will be convient.

**Comment by kisvegabor** [comment]
I mean if someone just enables `LV_BUILD_DEMOS` all the demos might require a some MBs of flash if the unused ones are not ignored by the linker. 

As the Kconfig file is used by several platforms I think it's safer to disable all the demos by default and let the users enable what they need.  Once someone is enabling `LV_BUILD_DEMOS` enabling specific demos too shouldn't be a big problem.

**Comment by wangyz1997** [comment]
OK, I'll do that.

**Comment by wangyz1997** [comment]
`Kconfig` file is left unchanged, `LV_BUILD_DEMOS` option is deleted and source file of each demo is added to the build seperately. Looking forward for your review.

**Comment by kisvegabor** [comment]
The only problem I see is that if we create a new demo we shouldn't forget to add it here too.

However, glob-ing the demo sources unconditionally would increase the build time (even if the files are empty due to `#if LV_USE_DEMO_...`s) . Anyway, we don't add demos every day so let's go with this solution. 

 Thank you!

**Pull request merged**
