### PR TITLE
fix(freertos): use xSemaphoreTakeRecursive

### PR DESCRIPTION
**Pull request by kisvegabor**
A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by FASTSHIFT — DISMISSED** [review]

**Comment by kisvegabor** [comment]
Don't merge yet. I still need to add something.

**Review by liamHowatt — COMMENTED** [review]
Look into `xSemaphoreGiveRecursive` to see if it applies here. I think it may.

**Comment by liamHowatt** [comment]
Fixes #6808

**Comment by kisvegabor** [comment]
Just added `xSemaphoreGiveRecursive` too. It's working my end, but @espzav please test it to make sure that it work well on ESP too.

**Review by kissa96 — APPROVED** [review]
LGTM

**Review by tore-espressif — APPROVED** [review]
Thanks!

**Comment by espzav** [comment]
I tested it now and it seems there is something more. I only changed this in LVGL port: 
image
and it is stucked somewhere. I will continue to find the place, where is the problem.

**Comment by espzav** [comment]
Sorry, my fault, there must be return true. Now it is working properly :-) LGTM

**Review by espzav — APPROVED** [review]

**Review by liamHowatt — APPROVED** [review]
I hope `xSemaphoreTakeFromISR` is compatible with recursive mutexes. It's not clear from the documentation. The mutexes are already recursive and there have been no issues so it may be fine.

**Comment by kisvegabor** [comment]
> I hope xSemaphoreTakeFromISR is compatible with recursive mutexes. It's not clear from the documentation. The mutexes are already recursive and there have been no issues so it may be fine.

`lv_lock()` uses `xSemaphoreTakeRecursive` so it can't be used from an interrupt anyway. So the users can't call LVGL functions from an interrupt. Even if they could, the "mutex taking" could not give back the control to the normal task to finish its job.

**Comment by liamHowatt** [comment]
I agree. Unrelated to this PR, I mainly meant that `lv_mutex_lock_isr` locks a mutex that was created with `xSemaphoreCreateRecursiveMutex`. I hope code that uses `lv_mutex_lock_isr` (nothing in LVGL uses it) will be ok.

**Comment by kisvegabor** [comment]
Good question. However as there is no `xSemaphoreTakeRecursiveFormISR` (both ISR and recursive) I also hope it's ok. :slightly_smiling_face:

**Comment by kisvegabor** [comment]
cc @XuNeo @FASTSHIFT could you take look at this issue?

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
