### PR TITLE
bugfix for fatfs freetype fps

### PR DESCRIPTION
**Pull request by ThunderDai**
1. when use freetype and fatfs for esp32, then will compilation failed
2. When calculating fps, direct shaping and discarding may result in a significant difference from the actual frame rate. Therefore, rounding should be used more reasonably

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
Can you submit a separate PR?

**Comment by ThunderDai** [comment]
> Can you submit a separate PR?

hi, do you means one PR just one commit?

**Comment by FASTSHIFT** [comment]
> > Can you submit a separate PR?
> 
> hi, do you means one PR just one commit?

Yes, it is recommended to split the PR for modifications to different modules, so that it is convenient to review and modify them separately.

**Comment by ThunderDai** [comment]
> > > Can you submit a separate PR?
> > 
> > 
> > hi, do you means one PR just one commit?
> 
> Yes, it is recommended to split the PR for modifications to different modules, so that it is convenient to review and modify them separately.

oh, thanks

**Comment by ThunderDai** [comment]
> > > Can you submit a separate PR?
> > 
> > 
> > hi, do you means one PR just one commit?
> 
> Yes, it is recommended to split the PR for modifications to different modules, so that it is convenient to review and modify them separately.

In fact, perhaps I should directly submit an issue? Because the problem I currently need to solve is relatively simple, and there shouldn't be many modifications

**Pull request closed without merging**
