### PR TITLE
feat(event): cache removed event

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

This modification is similar to https://github.com/lvgl/lvgl/pull/6592. Both add a mark to the deleted event. This PR marks the event slot as pending reuse. This solution should be the most efficient because it saves the overhead introduced by the `realloc` operation of `lv_array`, and the changes to the current code are minimal. The disadvantage is that the insertion order cannot be guaranteed, which may affect the current APP that relies on the order of event sending.
The design of https://github.com/lvgl/lvgl/pull/6592 is to mark the deleted events as pending deletion and clean them up uniformly after the events are sent. The advantage is that it will not affect the event order and can ensure forward compatibility. The disadvantage is that it is necessary to introduce additional member variables to record whether event_list has been deleted.
Which option do you prefer?

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by XuNeo** [comment]
> The disadvantage is that the insertion order cannot be guaranteed, which may affect the current APP that relies on the order of event sending

If there's application rely on this feature, can we provide a log to assist debug after this PR is merged?

**Comment by FASTSHIFT** [comment]
> > The disadvantage is that the insertion order cannot be guaranteed, which may affect the current APP that relies on the order of event sending
> 
> If there's application rely on this feature, can we provide a log to assist debug after this PR is merged?

Done

**Review by kisvegabor — CHANGES_REQUESTED** [review]
The order of events is very important and should be fully determined and reproducible. Otherwise it will cause very hard to debug anomalies. 


Is even removal so common in your use cases that it's worth optimizing for it?

**Comment by FASTSHIFT** [comment]
> The order of events is very important and should be fully determined and reproducible. Otherwise it will cause very hard to debug anomalies.
> 
> Is even removal so common in your use cases that it's worth optimizing for it?

There are no scenarios where events are frequently added or deleted.

**Comment by kisvegabor** [comment]
In this case I wouldn't risk adding events in a non-defined order.

**Comment by FASTSHIFT** [comment]
> In this case I wouldn't risk adding events in a non-defined order.

OK，let's continue here https://github.com/lvgl/lvgl/pull/6592.

**Pull request closed without merging**
