### PR TITLE
refactor(font): refactor release/get_glyph/image API names

### PR DESCRIPTION
**Pull request by W-Mai**
### Description of the feature or fix

Refactor font related API names

```cpp
get_glyph_dsc     -->   glyph_get_info
get_glyph_bitmap  -->   glyph_acquire_draw_data
release_glyph     -->   glyph_release_draw_data
```

Because the data obtained from the glyph of the font includes the path data of the vector font, the image source data of the image font and the bitmap font, it is more appropriate to call it `draw_data`.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
This change is hard to manage. We could add the new and old names to `lv_api_map_v9.h` but we should update the [font converter](https://github.com/lvgl/lv_font_conv) too. If the font converter will generate the new names, the latest version of the converter won't work with older LVGL versions (even from v9)

All things considered I think this extra issue isn't worth to resolve the minor inconsistency of "`bitmap` might mean `vector` data too". I suggest adding this update on a major release.

**Comment by kisvegabor** [comment]
@W-Mai What is your intention with this PR?

**Comment by W-Mai** [comment]
> @W-Mai What is your intention with this PR?

Make API names more uniform

**Comment by kisvegabor** [comment]
I mean is it still relevant? If so, could you comment on [this](https://github.com/lvgl/lvgl/pull/5888#issuecomment-2002007406)?

**Pull request closed without merging**
