### PR TITLE
docs: Fix link to example code in gen_mipi.rst

### PR DESCRIPTION
**Pull request by mutatrum**
Fix link to example code

### CODE REVIEW

**Comment by kissa96** [comment]
Why does it not work without blob/master?

**Comment by mutatrum** [comment]
Not sure why it doesn't work, it's just not there.

image

Not sure you want it to blob/master, or pin it on some version.

**Comment by kissa96** [comment]
@kisvegabor any input on this?

**Review by kisvegabor — DISMISSED** [review]
Looks good, thank you!

**Comment by kisvegabor** [comment]
> Why does it not work without blob/master?

This is how GitHub creates the links.

**Review by liamHowatt — DISMISSED** [review]

**Review by liamHowatt — APPROVED** [review]
I had to rebase to resolve a conflict

**Review by kisvegabor — APPROVED** [review]

**Pull request merged**
