### PR TITLE
fix(style): make the code generated by style_api_gen.py confirm the coding style

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

The generated code more confirm to the style guide.

### Checkpoints
- [X] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
dev branch can't pass CI?
```
lv_test_fonts/font_1.o lv_test_fonts/font_2.o lv_test_fonts/font_3.o ./lv_test_main.o
Error: /home/runner/work/lvgl/lvgl/tests/../../lvgl/src/lv_core/lv_indev.c:24:5: error: "LV_INDEV_DEF_DRAG_THROW" is not defined, evaluates to 0 [-Werror=undef]
   24 | #if LV_INDEV_DEF_DRAG_THROW <= 0
      |     ^~~~~~~~~~~~~~~~~~~~~~~
Error: /home/runner/work/lvgl/lvgl/tests/../../lvgl/src/lv_core/lv_indev.c:25:6: error: #warning is a GCC extension
   25 |     #warning "LV_INDEV_DRAG_THROW must be greater than 0"
      |      ^~~~~~~
Error: /home/runner/work/lvgl/lvgl/tests/../../lvgl/src/lv_core/lv_indev.c:25:6: error: #warning "LV_INDEV_DRAG_THROW must be greater than 0" [-Werror=cpp]
```

**Comment by embeddedt** [comment]
Dev is still being polished for testing so CI failures are expected for now (I think).

**Comment by kisvegabor** [comment]
Actually, I've intentionally chosen the "compact" form for these functions to reduce the number of lines in the files. 
My goal was to make them only one-liners, but it wasn't possible. 

Do you think it's worth writing these functions in multiple lines?

**Comment by embeddedt** [comment]
If they're autogenerated, I don't know if the line count matters. It's definitely easier to read with the new format.

**Comment by kisvegabor** [comment]
Alright, let's merge it.

Thank you!

**Pull request merged**
