### PR TITLE
fix(perf): perf monitor FPS

### LINKED ISSUE #6785: When updating the LVGL library from 9.1 to 9.2, the number of FPS decreased.
### LVGL version

v9.2.0

### What happened?

I tested the demo project in conjunction with FreeRTOS and noticed that in the new version, in the absence of animations, FPS drops to 6-10. If you add looping animation, the FPS rises to 40. As I understand it, this refers to part of the optimization, so as not to waste resources on rendering static objects. But now it is impossible to scroll through file system objects with such an FPS. Can you give advice on how to fix this bug?

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by liamHowatt**
The logic for pausing the timer was accidentally inverted. It should not pause the timer if the perf monitor is enabled. Always try to achieve target FPS while perf monitor is enabled.

Should fix #6785

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — DISMISSED** [review]

**Comment by kisvegabor** [comment]
Upps, thank you :sweat_smile:

**Review by XuNeo — DISMISSED** [review]

**Comment by XuNeo** [comment]
Looks like CI is failing, and no snapshot image in artifacts.

```

/home/runner/work/lvgl/lvgl/tests/src/test_cases/widgets/test_arc.c:218:test_arc_click_sustained_from_start_to_end_does_not_set_value_to_max:FAIL: Expected 1 Was 0
/home/runner/work/lvgl/lvgl/tests/src/test_cases/widgets/test_arc.c:275:test_two_overlapping_arcs_can_be_interacted_independently:FAIL: Expected 1 Was 0
```

**Comment by liamHowatt** [comment]
Thanks, the problem seems lightly nontrivial. It has to do with the test indev not releasing between test cases, but there is some external factor. Looking into it.

**Comment by liamHowatt** [comment]
I don't really understand why this fixes it or why it needed to be fixed only now. Oh well.

**Comment by kisvegabor** [comment]
Let's accept that we can't control everything. 😅

**Review by kisvegabor — APPROVED** [review]

**Review by XuNeo — APPROVED** [review]

**Comment by kisvegabor** [comment]
Great! It will be released v9.2.1 will be released early October.

**Pull request merged**
