### PR TITLE
feat(gpu): Update lv_gpu_arm2d with new features

### PR DESCRIPTION
**Pull request by GorgonMeducer**
### Description of the feature or fix

- [NEW] Provide acceleration for
    * Transform
    * Recolour
    * Chrome-Key

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
It looks like the code-format.py introduces new issues. 
Can anyone help to fix it?

**Comment by kisvegabor** [comment]
I can't see any reason why astyle misses to format it correctly. Maybe @embeddedt?

**Comment by xiaoxiang781216** [comment]
Remove the last `/* *INDENT-ON* */` could workaround the warning:
https://github.com/lvgl/lvgl/pull/3340/files#diff-1c1e4170e0eba2273f6de9b528e9e1b2da0afabbd9de3fba2f8dc15613ac28bcR1233
look like this special mark make astyle confuse.

**Comment by GorgonMeducer** [comment]
@kisvegabor any thoughts about this PR?
If possible, I'd like to include this PR in the LVGL monthly update (May alpha).

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Let merge your PR to unblock your release.

**Comment by kisvegabor** [comment]
Sorry, for the delay. Thanks @xiaoxiang781216

**Comment by GorgonMeducer** [comment]
@kisvegabor No problem. 
Thank you all the same.

**Pull request merged**
