### PR TITLE
lv_obj_count_children_recursive

### PR DESCRIPTION
**Pull request by BrianPugh**
Add functions for recursively getting the number of children. Also added a function for getting the length of a linked list. Useful for debugging/profiling. For example, you can get the number of objects on a screen by `lv_obj_count_children_recursive(lv_scr_act())`

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]

**Comment by BrianPugh** [comment]
Similarly, I am trying to think about a way to recursively get the cumulative number of bytes used by all `lv_obj_t` children. It'd be very similar to `lv_obj_count_children_recursive`, but also count the size of the `ext` structure for that object. Unfortunately, I don't see a quick/elegant way of knowing the type of `ext`. One solution could be a `LV_SIGNAL_GET_EXT_SIZE`, similar to how `LV_SIGNAL_GET_TYPE` works, but that requires quite a bit of effort. Any other ideas?

**Comment by embeddedt** [comment]
@BrianPugh If the builtin memory allocator was used, we could add an API for getting the size of an allocated chunk of memory with it's pointer, as that information is available. However, as far as I know, there is no portable POSIX API for determining the size of an allocated memory chunk returned by `malloc()`, using the pointer.

**Comment by embeddedt** [comment]
@BrianPugh In fact, for the builtin memory allocator, the API already exists: `lv_mem_get_size`.

**Comment by BrianPugh** [comment]
Just for debugging purposes, maybe it'd be useful to define a `static uint32_t lv_mem_used` in `lv_mem.c` with getter function. Any time there's a malloc/realloc/free, increase/decrease this value by the number of bytes. Unfortunately, this would only work using the internal allocator since there's no way of knowing how many bytes are freed. Any other clever ideas to help profile lvgl memory usage?

EDIT: basically what @embeddedt said right above me at the same time :P

EDIT2: I suppose just for memory profiling, I could toggle between my custom allocator and lvgl's to get this extra info.

**Comment by embeddedt** [comment]
@BrianPugh In many of my projects, I usually think of a cutoff value (i.e. 4K) and set up my debugging infrastructure in such a way that a breakpoint is triggered whenever allocation of that value or greater happens. It's not the most innovative solution, but it's helped me understand where large amounts of memory get allocated from.

> Unfortunately, this would only work using the internal allocator since there's no way of knowing how many bytes are freed.

Not necessarily. What if I implemented it like this?

```c
void *lv_mem_alloc(size_t size)
{
    size_t *ptr = malloc(size+sizeof(size_t));
    *ptr = size;
    return &ptr[1]; /* Address immediately after size_t */
}
```

I could undo that logic in the `lv_mem_free` button and find out the size. This is pretty much how the internal allocator keeps track of chunk sizes, but it could easily be added for custom allocation as well in this manner.

**Comment by BrianPugh** [comment]
I could program something like this if we think its a good idea. It should be enabled/disabled via `lv_conf.h` to save memory.

**Comment by embeddedt** [comment]
> something like this

I assume you are referring to my second idea? (`lv_mem_alloc` acting as a wrapper for `malloc`)

**Comment by BrianPugh** [comment]
@embeddedt yes, your second idea. And have an option to enable/disable in lv_conf.h to save the 4 bytes of overhead when mem_prof is not used.

**Comment by kisvegabor** [comment]
Regarding `lv_obj_count_children_recursive`, it looks good, thank you!

About memory profiling: `malloc` and `free` are not used directly in `lv_mem_alloc` but include the chunk's size too. Therefore `lv_mem_get_size` works with `LV_MEM_CUSTOM` too.

Have you seen [lv_mem_monitor](https://github.com/littlevgl/lvgl/blob/master/lv_misc/lv_mem.c#L318)? It tells a lot of info about the memory usage in general
```c
typedef struct
{
    uint32_t total_size;
    uint32_t free_cnt;
    uint32_t free_size;
    uint32_t free_biggest_size;
    uint32_t used_cnt;
    uint8_t used_pct;
    uint8_t frag_pct;
} lv_mem_monitor_t;
```

It would be difficult to get the memory usage recursively because you can get the size of `obj->ext_attr` but you can't see e.g. the label's text size which is allocated in `lv_label_ext_t`. So you don't see if an object has allocated something in its `ext_attr`.

**Comment by BrianPugh** [comment]
thanks for the tips @kisvegabor . If i write up some profiling code I'll check this stuff out and make another PR. As for now, I think we can just merge this.

**Comment by kisvegabor** [comment]
Merged, thank you!

**Pull request merged**
