### PR TITLE
Astyle

### PR DESCRIPTION
**Pull request by aenchevich**
Rules and instructions for using the open source 'astyle' tool for formatting the project source and header files in accordance with the project coding guidelines  (https://github.com/littlevgl/lvgl/blob/master/docs/CONTRIBUTING.md#styling-guide).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thank you very much, it's very useful!
I didn't know that there is such a simple and great tool.

I moved the astyle files to the docs folder and added you instruction (from the README) to CONTRINUTING.md

**Comment by kisvegabor** [comment]
Do you know an astyle options which keeps the opening curly brace inline by default but breaks it the expression (e.g if condition) is broken into multiple lines. For example:

Instead of: 
```c
if(a == 2 &&
   b == 3) {
    c = 4;
}
```
This:
```c
if(a == 2 &&
   b == 3) 
{
     c = 4;
}
```

I didn't found it in the [documentation](http://astyle.sourceforge.net/astyle.html) but maybe I just overlooked it

**Comment by BenQoo** [comment]
You could try the option `--max-code-length=#   / -xC#`
<http://astyle.sourceforge.net/astyle.html#_max-code-length>

**Comment by kisvegabor** [comment]
`--max-code-length` did't heleped, the brace remained in the same line.

I suppose `style=kr` is taken into account in this case as well.

**Pull request merged**
