### PR TITLE
fix(draw_line): fix the issue where dash_dap equals 1 and cannot display properly when the line is a horizontal line

### LINKED ISSUE #5029: Dash width and gap are rendered incorrectly on horizontal lines.
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [x] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

### Describe the bug
Horizontal lines with dash_width and dash_gap are not drawn correctly.

E.G. If dash_width = 1 and dash_gap = 1 then the result is a solid horizontal line instead of a dotted line.

Vertical lines are drawn correctly.

### To Reproduce
```c
  lv_style_t style;
  lv_style_init(&style);
  lv_style_set_line_width(&style, 1);
  lv_style_set_line_dash_width(&style, 1);
  lv_style_set_line_dash_gap(&style, 1);

  lv_point_t pts[2] = {{50, 50}, {250, 50}};

  lv_obj_t* line = lv_line_create(lv_scr_act());
  lv_obj_add_style(line, &style, LV_PART_MAIN);
  lv_line_set_points(line, pts, 2);
```

### Expected behavior
Dash settings should render correctly.

### Screenshots or video
dash_width = 1 and dash_gap = 1
Screenshot 2023-12-18 at 1 21 43 pm

dash_width = 2 and dash_gap = 2
Screenshot 2023-12-18 at 1 21 17 pm

The problem is in src/draw/sw/lv_draw_sw_line.c lines 171 - 172.
Should be:
```c
                        if(dash_cnt < dsc->dash_width) {
                            int16_t diff = dsc->dash_width - dash_cnt - 1;
```

### PR DESCRIPTION
**Pull request by lhdjply**
### Description of the feature or fix

fix #5029
fix(draw_line): fix the issue where dash_dap equals 1 and cannot display properly when the line is a horizontal line

### test code:
```c
void lv_line_dash_dap_test(void)
{
  static lv_point_precise_t line_points[2] = { {50, 50}, {250, 50} };

  lv_obj_t * line1;
  line1 = lv_line_create(lv_screen_active());
  lv_line_set_points(line1, line_points, 2);
  lv_obj_set_style_line_width(line1, 1, LV_PART_MAIN);
  lv_obj_set_style_line_dash_width(line1, 1, LV_PART_MAIN);
  lv_obj_set_style_line_dash_gap(line1, 1, LV_PART_MAIN);
}
```
### before fix

image

### after fix 
image

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by W-Mai — APPROVED** [review]

**Review by W-Mai — APPROVED** [review]

**Comment by kisvegabor** [comment]
Very nice, thank you! 

Could you add a test with various dash configurations on horizontal and vertical lines too?

**Comment by lhdjply** [comment]
Done

**Review by W-Mai — APPROVED** [review]
LGTM

**Review by kisvegabor — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
