### PR TITLE
30 times faster int to string implementation

### PR DESCRIPTION
**Pull request by muhammetasan**
I have compared performance of existing implementation and my implementation. My proposal runs up to 30 times faster in terms of clock cycle. I run tests from -1000000 to +10000000

### CODE REVIEW

**Review by embeddedt — CHANGES_REQUESTED** [review]
I try not to be picky about these kinds of things, but the replacement is indented with 2 spaces instead of 4. Could you fix that?

**Comment by muhammetasan** [comment]
@embeddedt  of course you should be picky about these to keep code beautiful.

**Comment by kisvegabor** [comment]
I tested and it worked well! Thank you!

I'm wondering a division is faster than multiple shifting.
On which platform have you tested it?

**Comment by embeddedt** [comment]
@kisvegabor I'm not an expert on instruction-level cycle counting, so this might be inaccurate information. But I would suspect that the reason for it being faster is that before, you were doing a lot of bit masking and comparing:

https://github.com/littlevgl/lvgl/blob/e3bbe0a4fd8d5f9f84a875d54fd35f7236156ade/lv_misc/lv_math.c#L71-L86

Now that's been replaced by one division operation.

```c
        char digit = num % 10;
```

I think that most processors will handle a single division faster than multiple bit operations.

**Comment by muhammetasan** [comment]
I have tested it stm32f4 and my linux pc.  As @embeddedt  explained too many branches inside you for loop makes it slower . Your implementation may be faster in very very large numbers where reaching to zero by dividing takes long time. But most of the cases division reaches zero faster.

**Comment by kisvegabor** [comment]
I see, thank you.

All seems good so I merged it!

I added it to the `dev-6.0` branch.

**Pull request merged**
