### PR TITLE
fix(arduino): allow including lvgl_private.h even if the examles and demos are in the src folder

### LINKED ISSUE #6778: cpp  fatal error: ../../src/themes/lv_theme_private.h: No such file or directory
### LVGL version

9.1.0 - 9.3.0

### What happened?

I am encountering an issue with the LVGL library:
```
fatal error: ../../src/themes/lv_theme_private.h: No such file or directory
    1 | #include "../../src/themes/lv_theme_private.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Compilation error: exit status 1
```
Everything is configured as explained in the LVGL documentation (including ```lv_conf.h``` and ```User_Setup.h```). After checking the directory, the file exists, and I have no clue what is wrong (I am a beginner, btw).

I am getting this error on both Windows and Arch Linux, so I suspect it might be an issue with the library itself.

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by kisvegabor**
fixes #6778

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by uLipe — COMMENTED** [review]
I know the way that Arduino IDE discover the things are somewhat odd (to not say other thing). But this kind of error indicates that some private definitions are being exported to the public LVGL interface.

My question is, is it intended by design? I would suppose that private definition file (header file, compile options) should be used only inside the library source files that need those definitions, and exporting private defintions to the public API seems like a scope / purpose violation of the lvgl_private file.

**Comment by kisvegabor** [comment]
"private" is maybe not the best term. Our intention was to separate what we consider public non-breaking API (suitable for most of the users) and the APIs for power users who are going very deep into LVGL. 

So the private headers provide access to the image decoder, advanced drawing, draw units, widget internal data structures, etc.

The API available via `lvgl.h` should be stable and don't really change. However other API can be modified as they are considered internal and/or for advanced user (which means less and more skilled people will use them).

**Review by liamHowatt — APPROVED** [review]
I think it could be ok. I see that the same is already done for `lvgl.h`. If that wasn't a disruptive change, this shouldn't be either.

**Comment by kisvegabor** [comment]
@liamHowatt I agree 🙂

**Review by FASTSHIFT — APPROVED** [review]

**Review by uLipe — APPROVED** [review]

**Pull request merged**
