### PR TITLE
fix(scroll): fix jumping on scroll end

### LINKED ISSUE #6357: Tabview scrolling issue
### LVGL version

v9.1

### What happened?

If you continue to scroll left when you have reached the last tab, you jump back to the second-to-last tab. Scrolling from the last to the second-to-last tab is always done without animation. This worked until version 9.0. 

### How to reproduce?

The error can be easily reproduced on, for example, LVGL's demo page.

### PR DESCRIPTION
**Pull request by kisvegabor**
fixes #6357

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by faruq-zhao — APPROVED** [review]

**Review by PGNetHun — DISMISSED** [review]

**Comment by niklasf** [comment]
Can also confirm this fixes the issue and tabview, and as expected also in tileview.

**Review by liamHowatt — DISMISSED** [review]
Tileview is fixed too.

Is [this](https://github.com/lvgl/lvgl/blob/6f67fe4d66457e4d758e0fa2bab71974d2dd0f3d/src/indev/lv_indev_scroll.c#L176) safe from the same issue? Where the sentinel `LV_COORD_MAX` should be `LV_COORD_MIN` in some case? It's hard to tell.

I tested `lv_example_scroll_2` and there seems to be flickering for less than a second and then it's fine. Seems harmless so approving. Since #6230. Fine before.

**Comment by kisvegabor** [comment]
Thank you for the thorough test @liamHowatt! I've fixed `lv_example_scroll_2` too.

**Review by liamHowatt — APPROVED** [review]
Nice!

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
