### PR TITLE
feat(CI): Windows MSVC and GCC build

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

See #5904 and #5978

Add a CI test for building on Windows. In particular, build the Windows-specific files from #5313.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Very nice! It would be great to reuse the CMake files for MSVC too, but if there is more Windows-ish way we can choose that too. 

@MouriNaruto could you take a look at the Windows driver related changes?

**Comment by liamHowatt** [comment]
Thanks for the feedback @MouriNaruto. In hindsight I see that those handlers should not be the header as you say. I originally did it to fix a CI warning.

https://github.com/liamHowatt/lvgl/actions/runs/8527506893/job/23359087388
```
Error: D:/a/lvgl/lvgl/src/drivers/windows/lv_windows_input.c:283:6: error: no previous prototype for 'lv_windows_pointer_device_window_message_handler' [-Werror=missing-prototypes]
  283 | bool lv_windows_pointer_device_window_message_handler(
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Generally it's good to only-declare-once. Recently we've been moving private cross-file declarations to `*_private.h` headers #5913. What do you think of my latest commit(s) as a potential compromise?

**Comment by kisvegabor** [comment]
If @MouriNaruto agrees with having `lv_windows_input_private.h`, please add it to `lvgl_private.h` too.

**Comment by MouriNaruto** [comment]
@kisvegabor I'm agree with having lv_windows_input_private.h.

**Review by XuNeo — DISMISSED** [review]
Nice work!

**Comment by MouriNaruto** [comment]
@liamHowatt  I think you should do some macro checks for GCC-specific progma to keep the MSVC compatibility.

Kenji Mouri

**Comment by kisvegabor** [comment]
Will you migrate to MSVC still in this PR?

**Comment by liamHowatt** [comment]
> I think you should do some macro checks for GCC-specific progma to keep the MSVC compatibility.

Yep, good idea.

> Will you migrate to MSVC still in this PR?

That wasn't the intent of this PR but yes I will. It is important.

**Comment by kisvegabor** [comment]
>> Will you migrate to MSVC still in this PR?

> That wasn't the intent of this PR but yes I will. It is important.

Yes, I think MinGW is not so interesting compared to MSVC.

**Comment by liamHowatt** [comment]
There is now an MSVC build workflow.

- Using `/W3` warning flag to enable all "production quality" warnings. Not using `/W4` because it gives too many Spectre vulnerability mitigation warnings.
- Manually set warning C4013 to be treated as an error. It is the "implicit function declaration" warning.
- The warnings from #5873 are being emitted.
- I cleaned up some concerning warnings but left most of them alone for after 5873 gets merged. There are a lot of integer conversion size/sign warnings as well as signed/unsigned comparison warnings. [build logs](https://productionresultssa11.blob.core.windows.net/actions-results/5bf2c72b-d95b-4da8-abe3-9c6230fb7b4f/workflow-job-run-d0854d3c-5d06-5143-594e-e39d149e1182/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-18T04%3A51%3A29Z&sig=JAP%2FK0c3%2BSi5YLOb1DusrdT%2Bj%2ByBeYfK2hl8IALAO8Y%3D&sp=r&spr=https&sr=b&st=2024-04-18T04%3A41%3A24Z&sv=2021-12-02)
- ASM disabled for MSVC in CMake

**Review by XuNeo — APPROVED** [review]

**Comment by kisvegabor** [comment]
Thank you! 

At some point it would be nice to lower the number of the remaining warnings, but at least now we know that LVGL builds on MSVC too! :tada:

**Review by kisvegabor — APPROVED** [review]

**Pull request merged**
