### PR TITLE
fix(NemaGFX): add missing text function parameter

### LINKED ISSUE #7391: lv_draw_nema_gfx_label does not compile (9.3.0.dev)
### LVGL version

9.3.0.dev

### Platform

GCC 13.3.1 on Windows

### What happened?

`lv_draw_nema_gfx_label` does not compile.

```
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:271:63: error: incompatible type for argument 6 of 'lv_text_get_next_line'
  271 |                                                            dsc->flag);
      |                                                            ~~~^~~~~~
      |                                                               |
      |                                                               lv_text_flag_t
```
```
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:270:38: error: too few arguments to function 'lv_text_get_next_line'
  270 |     uint32_t line_end = line_start + lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL,
      |                                      ^~~~~~~~~~~~~~~~~~~~~
```

It seems that [`lv_text_get_next_line()`](https://github.com/lvgl/lvgl/blob/a87a28bcd4e8b10a6e3e1eb3fb81b92a5c2d617a/src/misc/lv_text.c#L321) second `uint32_t len` arg is missing.

@liamHowatt 

### How to reproduce?

```
arm-none-eabi-gcc -std=gnu17 -c -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard --specs=nano.specs -mthumb -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MFBUILD/debug/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.d -MTBUILD/debug/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.o -O0 -g -I. -Ilvgl/libs/nema_gfx/include -Ilvgl/src/libs/thorvg -DDEBUG -DSTM32U5 -DSTM32U5G9xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DTX_SINGLE_MODE_NON_SECURE=1 -DTX_INCLUDE_USER_DEFINE_FILE -DFX_INCLUDE_USER_DEFINE_FILE -DUX_INCLUDE_USER_DEFINE_FILE -DTRACE_LEVEL=0 -DARM_MATH_DSP -DARM_MATH_LOOPUNROLL -DARM_TABLE_TWIDDLECOEF_Q15_1024 -DARM_TABLE_BITREVIDX_FXT_1024 -DARM_TABLE_TWIDDLECOEF_Q15_2048 -DARM_TABLE_BITREVIDX_FXT_2048 -DI2C_USE_DMA -DI2C_TRACE_LEVEL=0 -DSMB_TRACE_LEVEL=1 -include lv_conf.h -include lvgl/demos/lv_demos.h lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c -o BUILD/debug/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.o -IDrivers/CMSIS/Device/ST/STM32U5xx/Include -IDrivers/CMSIS/Include
Command failed: arm-none-eabi-gcc -std=gnu17 -c -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard --specs=nano.specs -mthumb -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MFBUILD/debug/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.d -MTBUILD/debug/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.o -O0 -g -I. -Ilvgl/libs/nema_gfx/include -Ilvgl/src/libs/thorvg -DDEBUG -DSTM32U5 -DSTM32U5G9xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DTX_SINGLE_MODE_NON_SECURE=1 -DTX_INCLUDE_USER_DEFINE_FILE -DFX_INCLUDE_USER_DEFINE_FILE -DUX_INCLUDE_USER_DEFINE_FILE -DTRACE_LEVEL=0 -DARM_MATH_DSP -DARM_MATH_LOOPUNROLL -DARM_TABLE_TWIDDLECOEF_Q15_1024 -DARM_TABLE_BITREVIDX_FXT_1024 -DARM_TABLE_TWIDDLECOEF_Q15_2048 -DARM_TABLE_BITREVIDX_FXT_2048 -DI2C_USE_DMA -DI2C_TRACE_LEVEL=0 -DSMB_TRACE_LEVEL=1 -include lv_conf.h -include lvgl/demos/lv_demos.h lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c -o BUILD/debug/lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.o -IDrivers/CMSIS/Device/ST/STM32U5xx/Include -IDrivers/CMSIS/Include
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c: In function '_draw_label_iterate_characters':
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:270:84: warning: passing argument 2 of 'lv_text_get_next_line' makes integer from pointer without a cast [-Wint-conversion]
  270 |     uint32_t line_end = line_start + lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL,
      |                                                                                    ^~~~
      |                                                                                    |
      |                                                                                    const lv_font_t * {aka const struct _lv_font_t *} 
In file included from lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:41:
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:45:59: note: expected 'uint32_t' {aka 'long unsigned int'} but argument is of type 'const lv_font_t *' {aka 'const struct _lv_font_t *'}
   45 | uint32_t lv_text_get_next_line(const char * txt, uint32_t len, const lv_font_t * font, int32_t letter_space,
      |                                                  ~~~~~~~~~^~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:270:93: warning: passing argument 3 of 'lv_text_get_next_line' makes pointer from integer without a cast [-Wint-conversion]
  270 |     uint32_t line_end = line_start + lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL,
      |                                                                                          ~~~^~~~~~~~~~~~~~
      |                                                                                             |
      |                                                                                             int32_t {aka long int}
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:45:82: note: expected 'const lv_font_t *' {aka 'const struct _lv_font_t *'} but argument is of type 'int32_t' {aka 'long int'}
   45 | uint32_t lv_text_get_next_line(const char * txt, uint32_t len, const lv_font_t * font, int32_t letter_space,
      |                                                                ~~~~~~~~~~~~~~~~~~^~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:270:112: warning: passing argument 5 of 'lv_text_get_next_line' makes integer from pointer without a cast [-Wint-conversion]
  270 |     uint32_t line_end = line_start + lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL,
      |                                                                                                                ^~~~
      |                                                                                                                |
      |                                                                                                                void *
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:46:40: note: expected 'int32_t' {aka 'long int'} but argument is of type 'void *'        
   46 |                                int32_t max_width, int32_t * used_width, lv_text_flag_t flag);
      |                                ~~~~~~~~^~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:271:63: error: incompatible type for argument 6 of 'lv_text_get_next_line'
  271 |                                                            dsc->flag);
      |                                                            ~~~^~~~~~
      |                                                               |
      |                                                               lv_text_flag_t
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:46:61: note: expected 'int32_t *' {aka 'long int *'} but argument is of type 'lv_text_flag_t'
   46 |                                int32_t max_width, int32_t * used_width, lv_text_flag_t flag);
      |                                                   ~~~~~~~~~~^~~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:270:38: error: too few arguments to function 'lv_text_get_next_line'
  270 |     uint32_t line_end = line_start + lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL,
      |                                      ^~~~~~~~~~~~~~~~~~~~~
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:45:10: note: declared here
   45 | uint32_t lv_text_get_next_line(const char * txt, uint32_t len, const lv_font_t * font, int32_t letter_space,
      |          ^~~~~~~~~~~~~~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:277:67: warning: passing argument 2 of 'lv_text_get_next_line' makes integer from pointer without a cast [-Wint-conversion]
  277 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                                                                   ^~~~
      |                                                                   |
      |                                                                   const lv_font_t * {aka const struct _lv_font_t *}
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:45:59: note: expected 'uint32_t' {aka 'long unsigned int'} but argument is of type 'const lv_font_t *' {aka 'const struct _lv_font_t *'}
   45 | uint32_t lv_text_get_next_line(const char * txt, uint32_t len, const lv_font_t * font, int32_t letter_space,
      |                                                  ~~~~~~~~~^~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:277:76: warning: passing argument 3 of 'lv_text_get_next_line' makes pointer from integer without a cast [-Wint-conversion]
  277 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                                                                         ~~~^~~~~~~~~~~~~~
      |                                                                            |
      |                                                                            int32_t {aka long int}
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:45:82: note: expected 'const lv_font_t *' {aka 'const struct _lv_font_t *'} but argument is of type 'int32_t' {aka 'long int'}
   45 | uint32_t lv_text_get_next_line(const char * txt, uint32_t len, const lv_font_t * font, int32_t letter_space,
      |                                                                ~~~~~~~~~~~~~~~~~~^~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:277:95: warning: passing argument 5 of 'lv_text_get_next_line' makes integer from pointer without a cast [-Wint-conversion]
  277 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                                                                                               ^~~~
      |                                                                                               |
      |                                                                                               void *
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:46:40: note: expected 'int32_t' {aka 'long int'} but argument is of type 'void *'        
   46 |                                int32_t max_width, int32_t * used_width, lv_text_flag_t flag);
      |                                ~~~~~~~~^~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:277:104: error: incompatible type for argument 6 of 'lv_text_get_next_line'
  277 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                                                                                                     ~~~^~~~~~
      |                                                                                                        |
      |                                                                                                        lv_text_flag_t
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:46:61: note: expected 'int32_t *' {aka 'long int *'} but argument is of type 'lv_text_flag_t'
   46 |                                int32_t max_width, int32_t * used_width, lv_text_flag_t flag);
      |                                                   ~~~~~~~~~~^~~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:277:21: error: too few arguments to function 'lv_text_get_next_line'
  277 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                     ^~~~~~~~~~~~~~~~~~~~~
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:45:10: note: declared here
   45 | uint32_t lv_text_get_next_line(const char * txt, uint32_t len, const lv_font_t * font, int32_t letter_space,
      |          ^~~~~~~~~~~~~~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:346:9: warning: implicit declaration of function '_lv_bidi_process_paragraph' [-Wimplicit-function-declaration]
  346 |         _lv_bidi_process_paragraph(dsc->text + line_start, bidi_txt, line_end - line_start, base_dir, NULL, 0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:357:37: warning: implicit declaration of function '_lv_bidi_get_logical_pos' [-Wimplicit-function-declaration]
  357 |                 logical_char_pos += _lv_bidi_get_logical_pos(bidi_txt, NULL, line_end - line_start, base_dir, t, NULL);
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:429:67: warning: passing argument 2 of 'lv_text_get_next_line' makes integer from pointer without a cast [-Wint-conversion]
  429 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                                                                   ^~~~
      |                                                                   |
      |                                                                   const lv_font_t * {aka const struct _lv_font_t *}
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:45:59: note: expected 'uint32_t' {aka 'long unsigned int'} but argument is of type 'const lv_font_t *' {aka 'const struct _lv_font_t *'}
   45 | uint32_t lv_text_get_next_line(const char * txt, uint32_t len, const lv_font_t * font, int32_t letter_space,
      |                                                  ~~~~~~~~~^~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:429:76: warning: passing argument 3 of 'lv_text_get_next_line' makes pointer from integer without a cast [-Wint-conversion]
  429 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                                                                         ~~~^~~~~~~~~~~~~~
      |                                                                            |
      |                                                                            int32_t {aka long int}
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:45:82: note: expected 'const lv_font_t *' {aka 'const struct _lv_font_t *'} but argument is of type 'int32_t' {aka 'long int'}
   45 | uint32_t lv_text_get_next_line(const char * txt, uint32_t len, const lv_font_t * font, int32_t letter_space,
      |                                                                ~~~~~~~~~~~~~~~~~~^~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:429:95: warning: passing argument 5 of 'lv_text_get_next_line' makes integer from pointer without a cast [-Wint-conversion]
  429 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                                                                                               ^~~~
      |                                                                                               |
      |                                                                                               void *
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:46:40: note: expected 'int32_t' {aka 'long int'} but argument is of type 'void *'        
   46 |                                int32_t max_width, int32_t * used_width, lv_text_flag_t flag);
      |                                ~~~~~~~~^~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:429:104: error: incompatible type for argument 6 of 'lv_text_get_next_line'
  429 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                                                                                                     ~~~^~~~~~
      |                                                                                                        |
      |                                                                                                        lv_text_flag_t
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:46:61: note: expected 'int32_t *' {aka 'long int *'} but argument is of type 'lv_text_flag_t'
   46 |                                int32_t max_width, int32_t * used_width, lv_text_flag_t flag);
      |                                                   ~~~~~~~~~~^~~~~~~~~~
lvgl/src/draw/nema_gfx/lv_draw_nema_gfx_label.c:429:21: error: too few arguments to function 'lv_text_get_next_line'
  429 |         line_end += lv_text_get_next_line(&dsc->text[line_start], font, dsc->letter_space, w, NULL, dsc->flag);
      |                     ^~~~~~~~~~~~~~~~~~~~~
lvgl/src/draw/nema_gfx/../../misc/lv_text_private.h:45:10: note: declared here
   45 | uint32_t lv_text_get_next_line(const char * txt, uint32_t len, const lv_font_t * font, int32_t letter_space,
      |          ^~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by liamHowatt**
Fixes #7391

cc @W-Mai

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by W-Mai — APPROVED** [review]

**Comment by W-Mai** [comment]
But I think there is a problem with `nema`'s implementation of draw label, and `nema` should not use this API, but instead write `draw_letter_cb` and use `lv_draw_label_iterate_characters` provided by `lvgl`, like `lv_draw_vg_lite_label.c` does, to draw the text.

**Comment by W-Mai** [comment]
```cpp
void lv_draw_vg_lite_label(lv_draw_unit_t * draw_unit, const lv_draw_label_dsc_t * dsc,
                           const lv_area_t * coords)
{
    LV_PROFILER_DRAW_BEGIN;
    lv_draw_label_iterate_characters(draw_unit, dsc, coords, draw_letter_cb);
    LV_PROFILER_DRAW_END;
}

/**********************
 *   STATIC FUNCTIONS
 **********************/

static void draw_letter_cb(lv_draw_unit_t * draw_unit, lv_draw_glyph_dsc_t * glyph_draw_dsc,
                           lv_draw_fill_dsc_t * fill_draw_dsc, const lv_area_t * fill_area)
{
    lv_draw_vg_lite_unit_t * u = (lv_draw_vg_lite_unit_t *)draw_unit;
    if(glyph_draw_dsc) {
        switch(glyph_draw_dsc->format) {
            case LV_FONT_GLYPH_FORMAT_A1:
            case LV_FONT_GLYPH_FORMAT_A2:
            case LV_FONT_GLYPH_FORMAT_A4:
            case LV_FONT_GLYPH_FORMAT_A8:
            case LV_FONT_GLYPH_FORMAT_A1_ALIGNED:
            case LV_FONT_GLYPH_FORMAT_A2_ALIGNED:
            case LV_FONT_GLYPH_FORMAT_A4_ALIGNED:
            case LV_FONT_GLYPH_FORMAT_A8_ALIGNED: {
                    glyph_draw_dsc->glyph_data = lv_font_get_glyph_bitmap(glyph_draw_dsc->g, glyph_draw_dsc->_draw_buf);
                    draw_letter_bitmap(u, glyph_draw_dsc);
                }
                break;

#if LV_USE_FREETYPE
```

**Comment by kisvegabor** [comment]
@W-Mai Very good point! I wonder how we missed it so far. :confused:

**Comment by MarkIoanAmat** [comment]
@W-Mai We are aware of the issues could caused by modifying public parts of the lvgl and we are looking for a workaround. Currently the latest PR solves any issue related to label drawing #7346 
@liamHowatt @kisvegabor

**Comment by kisvegabor** [comment]
We meant instead of [`_draw_label_iterate_characters`](https://github.com/lvgl/lvgl/pull/7346/files#diff-d23af2f6b43cdc91b0ccf22276209c83caf6d03241f93f516fc4d62f7a3a0b55L211-L212) the generic `lv_draw_label_iterate_characters` should be used like [this](https://github.com/lvgl/lvgl/blob/master/src/draw/sw/lv_draw_sw_letter.c#L54-L61).

**Review by uLipe — APPROVED** [review]
LGTM!

**Comment by tdjastrzebski** [comment]
@liamHowatt btw, which nema library has to be linked? `libnemagfx-float-abi-hard.a`?

**Comment by liamHowatt** [comment]
Yes, I agree that's likely the cause. What kind of device is it?

**Comment by tdjastrzebski** [comment]
STM32U5G9 MPU, custom board

**Comment by tdjastrzebski** [comment]
@liamHowatt, @kisvegabor I just got it working for the first time and the performance is just impressive!
Does it make sense to enable both `LV_USE_DRAW_DMA2D` and `LV_USE_NEMA_GFX` or it should be mutually exclusive?

Two initial thoughts:

I see that NEMA buffer size is hardcoded (LV_NEMA_GFX_MAX_RESX, LV_NEMA_GFX_MAX_RESY). I think it would make a lot of sense to follow the new pattern and use values set in lv_display_set_resolution() or lv_display_set_physical_resolution(). Why might someone NOT want to hardcode LCD resolution? Because this way just one binary image may be distributed and able to work with more than one LCD based on device config settings (e.g. eeprom stored).

GPU2D code assumes that `GPU2D_HandleTypeDef hgpu2d` is defined, it depends on STM32U5 HAL and CubeMX generated code. If it is going to stay this way than I think `#include "main.h"` (or some other common header like) could be used instead of `#include LV_DRAW_DMA2D_HAL_INCLUDE` - which makes static code analysis impossible without running preprocessor first. It seems convenient and flexible but using such approach is discouraged - I think for a good reason.

**Comment by tdjastrzebski** [comment]
@liamHowatt It would **probably** make sense to make sure the GPU2D buffer is in SRAM1. According to RMRM0456, Section 2.1 System Architecture, Figure 1 on page 130, access to the GPU2D SRAM via DCache2 and port M0 should be faster over SRAM1 when the "fast multiplexer" is used, although I don't know that for sure and I don't know how much faster it would be.

image

**Comment by liamHowatt** [comment]
> STM32U5G9 MPU, custom board

You should be able to use `LV_NEMA_HAL_STM32`. Is there some reason not to use it in your case?

> I just got it working for the first time and the performance is just impressive!

Awesome!

> Does it make sense to enable both `LV_USE_DRAW_DMA2D` and `LV_USE_NEMA_GFX` or it should be mutually exclusive?

I think you should be able to use both at the same time.

> I see that NEMA buffer size is hardcoded (LV_NEMA_GFX_MAX_RESX, LV_NEMA_GFX_MAX_RESY). I think it would make a lot of sense to follow the new pattern and use values set in lv_display_set_resolution() or lv_display_set_physical_resolution(). Why might someone NOT want to hardcode LCD resolution? Because this way just one binary image may be distributed and able to work with more than one LCD based on particular device config settings (e.g. permanently eeprom stored).

I see what you mean. Those constants actually do not set the display size. They define a maximum supported size. You can make a display that is smaller than those values. Those constants are used to know how much memory is needed for NemaVG's mask/stencil buffer. That buffer is used for an allocation pool. The buffer could be dynamically allocated. What could the API look like? Maybe:

```c
/* lv_draw_nema_gfx.h */
#define LV_NEMA_GFX_MASK_BUFFER_SIZE(max_x, max_y)       ((max_x * max_y) + 10240)
lv_draw_nema_gfx_set_mask_buffer(void * buf);

/* user code */
lv_draw_nema_gfx_set_mask_buffer(malloc(LV_NEMA_GFX_MASK_BUFFER_SIZE(640, 480));
```

> GPU2D code assumes that `GPU2D_HandleTypeDef hgpu2d` is defined, it depends on STM32U5 HAL and CubeMX generated code. If it is going to stay this way than I think `#include "main.h"` (or some other common header like lv_stm32.h) could be used instead of `#include LV_DRAW_DMA2D_HAL_INCLUDE` - which makes static code analysis impossible without running preprocessor first. It seems convenient and flexible but using such approach is discouraged - I think for a good reason. I think that also the required STM32 HAL header(s) could be just included with lv_conf.h.

You can set `LV_DRAW_DMA2D_HAL_INCLUDE` to `"main.h"`. If your IDE/analysis tools' paths are configured correctly, `lv_conf.h` will effect all source files with the values it defines. `lv_conf.h` is not using any magic. Running the preprocessor silently is something that any static analysis tool is required to do to cope with any C code that has `#include` or `#define`.

We've made an effort do decouple NemaGFX from ST because Think Silicon's Nema GPU API is not an ST-only API so we cannot use ST types, lest we unnecessarily limit targetable platforms.

> @liamHowatt It would **probably** make sense to make sure the GPU2D buffer is in SRAM1. Practically it may mean ability to specify linker script section name where GPU2D buffer should be placed, probably best located at 0x2000 0000. According to RMRM0456, Section 2.1 System Architecture, Figure 1 on page 130, access to the GPU2D SRAM via DCache2 and port M0 should be faster over SRAM1 when the "fast bus multiplexer" is used, although I don't know that for sure and I don't know how much faster it would be. Section 2.1.11 Bus matrix reads: _"This bus matrix features a fast bus multiplexer used to connect each master to a given slave without latency (see Figure 1). For the same master, other slaves undergo a latency of at least one cycle at each new access."_ Ofc, the above will be important when DCache2 is maintained. I am showing that enabling it now causes display glitches.

Continuing what I mentioned with a potential new mask buffer setter, you could do this:

```c
lv_draw_nema_gfx_set_mask_buffer((void *) 0x20000000);
```

Or, since the buffer is at an address known at compile-time, we could just add an option [here](https://github.com/lvgl/lvgl/blob/c9d35e1038060d07555903707da91e3ce49672f7/lv_conf_template.h#L212-L228) which is `LV_NEMA_GFX_VG_MASK_BUFFER_ADDRESS` which you would set to `0x20000000`.

@kisvegabor what do you think?

**Comment by tdjastrzebski** [comment]
1. GPU2D buffer size: maybe the best and 'programmer friendly' solution would be to set GPU2D buffer within `lv_display_set_resolution()` function. It would not allow for 'expert mode' settings and fixed buffer location but would allow for an easy start.

1. Fixed GPU2D buffer location and size could be considered 'expert mode' and defined in `lv_conf.h`, `LV_USE_NEMA_GFX` section. Such 'expert mode' definition would turn off GPU2D buffer allocation within `lv_display_set_resolution()`. Needless to say, if specified, address and buffer range need to be known at compile time so this memory range does not get used for anything else. Practically it implies use of custom linker script with dedicated memory section.

1. LV_DRAW_DMA2D_HAL_INCLUDE:
```C
#include ANY_DEFINED_VARIABLE // use of macro after #include is discouraged
```
Chat GPT nicely explains the matter.
What I suggested was replacing `#include LV_DRAW_DMA2D_HAL_INCLUDE` with `#include "main.h"` (or some other, non-ST/CubeIDE specific header) and getting rid of `#define LV_DRAW_DMA2D_HAL_INCLUDE "stm32h7xx_hal.h"`.

**Comment by liamHowatt** [comment]
Mmm okay. NemaGFX is a draw unit and it gets initialized before any displays are created. The NemaGFX draw unit would need to regularly check the size of the largest display and realloc the mask buffer. I wish there was an event emitted when a display was created. It would make it simpler. I'm not sure what memory to allocate the mask buffer from. I suppose the global LVGL allocator. User would need to be prepared for this large allocation to occur. I.e., it wouldn't be enough for them to have `LV_MEM_SIZE (128 * 1024U)`.

3: Ah I your analysis tool is having difficulty with `#include (macro)`. Oh sorry I missed that you were talking about DMA2D. Is the main issue that some tools don't support `#include (macro)`? This is done throughout LVGL. See all of the `#include LV_STDINT_INCLUDE`, etc.

> Not to mention that the latter name is ST specific - which is not inline with the intention of making NMEA GFX support generic.

`LV_NEMA_STM32_HAL_INCLUDE` is only included when `LV_USE_NEMA_HAL == LV_NEMA_HAL_STM32`.

**Comment by liamHowatt** [comment]
Reopening since we should make NemaGFX at least build for now, before https://github.com/lvgl/lvgl/pull/7346 is ready. cc @kisvegabor

**Comment by tdjastrzebski** [comment]
>  The NemaGFX draw unit would need to regularly check the size of the largest display and realloc the mask buffer.

Maybe some callback within `lv_display_set_resolution()` could be called? I do not how to go about it so I am just throwing ideas. However, I can imagine that additional mandatory config setting like this in lv_conf.h may cause issues to those who try to start using LVGL. Actually, I just experienced exactly that.

> #include ANY_PREPROCESSOR_MACRO

It is not about my [cppbuild](https://github.com/tdjastrzebski/cppbuild) tool or related to DMA2D at all. I can easily occasionally make the required change manually or start using CMake. It is just that it seems that such C/C++ programming practice is generally discouraged for good reasons.

**Comment by kisvegabor** [comment]
#7346 is merged so closing it.

**Pull request closed without merging**
