### PR TITLE
add lv_ll_ins_pos function

### PR DESCRIPTION
**Pull request by chenshijianworkgit**

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thank you very much! I like your updates! 
Just two things to mention:
1. lv_ll_ins_prev might be a more intuitive name for the new function
2. in lv_task_handler after a function is executed on a lower priority (e.g. MID) the higher priority functions should be checked again. I see that in your update and it's a very good idea! However after the higher priority tasks are executed the next MID priority task should be executed not the first again. Else the order of adding task would be a high effect on the same priority. The lastly added would be checked more times.

**Comment by chenshijianworkgit** [comment]
Hi,

You're welcome。

1.Yes, I also think lv_ll_ins_prev function name more intuitive
2.Polling task list will not take up a few CPU time, because lv_task_exec function will go to judge whether the time has been met. However, it can add a judge, if this is the highest priority of the task is not re-polling. But, this still can not be avoided, if it is the same priority and not the highest priority, it still needs to be polled from scratch.
   
while(1){
        endFlag = 1;
        LL_READ(lv_task_ll,tmp){
            if(true == lv_task_exec(tmp,tmp->prio)){
                if(tmp->prio != LV_TASK_PRIO_HIGHEST){
                    endFlag = 0;
                    break;
                }
            }
        }
        if(endFlag) {
            break;
        }
    }

**Comment by chenshijianworkgit** [comment]
You can also add a variable to record the highest priority registered task history, if the registered tasks are in the middle priority, then the highest priority is the middle history, delete the task to correct the highest priority in history, so Do not poll as long as the task is not equal to the highest priority in history, but doing so is more complicated.

**Comment by chenshijianworkgit** [comment]
If you feel that the task you created earlier is more important, you can modify the function that created the task to change the priority to less than or equal to less than it.

lv_task_create
....
if(tmp->prio < prio){    //change <= to <
    new_lv_task = lv_ll_ins_pos(&lv_task_ll, tmp);
    break;
}

**Comment by kisvegabor** [comment]
Hi,

I thought something different. Let's say we have 6 tasks: H1, H2, H3 with HIGH priority  and M1, M2, M3 with MID priority.
When we poll the list and M2 is executed then H1, H2, H3, M1 will be checked again. If meanwhile  M1 and M3 become ready then M1 it will be executed. If M1 do something long then it will be executed again and prevents M3 to run even they have the same priority.   

My idea is to register the *interrupted priority* and the *interrupter task*. When the polling starts again it should not call the tasks with *interrupted priority* before *interrupter task*.

**Comment by chenshijianworkgit** [comment]
Hi,

You are right, I did not consider this situation, just pushed an update on this issue, you see

**Comment by kisvegabor** [comment]
Hi

Thank you!
Can you explain the purpose of list shorting? I thought a "smart" `lv_task_create` function which puts the tasks into the right position according their priority is fine.

**Comment by chenshijianworkgit** [comment]
Your email was blocked, I just saw it.

Because the task was created prioritized when creating the task,。

you see, In lv_task_handler function, the implementation of the task added to another list.

so wait for the task to be reordered after execution.

**Comment by chenshijianworkgit** [comment]
In order to solve the situation you said above, I added a new linked list, the lv_task_handler function after the completion of a task will be the task added to the new list.

**Comment by chenshijianworkgit** [comment]
Lv_task_create function to create the task according to the order of priority high to low list, lv_task_handler function in order to avoid that you say, I will run the task added to a new list, when all tasks After running, then the new list of tasks in the order inserted into the original task list.

**Comment by chenshijianworkgit** [comment]
See lv_task_handler function to achieve：

while(1){
        endFlag = 1;
        LL_READ(lv_task_ll,tmp){
            if(true == lv_task_exec(tmp,tmp->prio)){
   
                /*1.Add a runned task to the new linked list*/
                lv_ll_chg_list(&lv_task_ll,&lv_task_runed_ll,tmp);
                endFlag = 0;
                break;
            }
        }
        if(endFlag) {
            break;
        }
    }
  
   //2. the new list of tasks in the order inserted into the original task list
    lv_ll_sort(&lv_task_ll,&lv_task_runed_ll,lv_ll_sort_func_task);

**Comment by kisvegabor** [comment]
I can't see where do you execute the task's in `lv_task_runed_ll` when a task is executed and higher priority ones need to be executed again. What have I missed?

Based on your great idea (in lv_task_create() insert the task according to their priority) I wrote my solution:
```c
/* Run all task from the highest to the lowest priority
 * If a lower priority task is executed check task again from the highest priority
 * but on the priority of executed tasks don't run tasks before the executed*/
lv_task_t * task_interruper = NULL;
lv_task_t * tmp;
while(1){
    LL_READ(lv_task_ll,tmp){

        /*Here is the interrupter task. Don't execute it again.*/
        if(tmp == task_interruper) {
            task_interruper = NULL;     /*From this point only task after the interrupter comes, so the interrupter is not interesting anymore*/
            continue;
        }

        /*Just try to run the tasks with highest priority.*/
        if(tmp->prio == LV_TASK_PRIO_HIGHEST) {
            lv_task_exec(tmp);
        }
        /*Tasks with higher priority then the interrupted shall be run in every case*/
        else if(task_interruper) {
            if(tmp->prio > task_interruper->prio) {
                if(lv_task_exec(tmp)) {
                    task_interruper = tmp;  /*Check all tasks again from the highest priority */
                    break;
                }
            }
        }
        /* It is no interrupter task or we already reached it earlier.
         * Just run the remaining tasks*/
        else {
            if(lv_task_exec(tmp)) {
                task_interruper = tmp;  /*Check all tasks again from the highest priority */
                break;
            }
        }
    }
}
```
In this approach we don't need to use lv_ll_sort which looks a little bit heavy. 
What do you think?

**Comment by chenshijianworkgit** [comment]
Hi,

This program is a bit of a problem，Without the end of a flag, then the above two cycles will die cycle.

With your previous model, I made a slight modification，I'll talk about it。

Let's say we have 8 tasks: H1, H2, H3, H4 with LV_TASK_PRIO_HIGHEST priority and The respective priorities of M1, M2, M3 and M4 are LV_TASK_PRIO_HIGH, LV_TASK_PRIO_MID, LV_TASK_PRIO_LOW, LV_TASK_PRIO_LOWEST.

When we poll the list and M2 is executed then H1, H2, H3, H4, M1 will be checked again.If meanwhile M1、M3 and M4 become ready then M1 it will be executed.

If M1 do something long then ,H1, H2, H3, H4 will be checked again. Then M3,M4 after the executed of each may be run again after M1.  


What I want to say is that the long executions of the kind of tasks you said earlier, if they exist, are likely to iterate over each other's tasks, causing the program to cycle through.


I submitted before the two linked list of programs think so, to ensure that the outer loop call lv_task_handler function, its internal task list in order of priority, each task has at least one execution opportunity.

Because the lv_task_handler function is called by the loop, the next call lv_task_handler function, or by priority from high to low order of execution.

**Comment by chenshijianworkgit** [comment]
LL_READ function is also a loop, if you jump out of a loop, LL_READ function will read back from the list header, then the beginning of this judge will set it to NULL, and then continue to find out.

if(tmp == task_interruper) {
            task_interruper = NULL;     /*From this point only task after the interrupter comes, so the       
                                                       interrupter is not interesting anymore*/
            continue;
}

**Comment by kisvegabor** [comment]
Hi,

You are right, I messed the `end_flag`, it is required. 

In your suggestion: Use the "names" from your example (H1, H2 ...). What if M1 become ready very often (just for example in every milliseconds) An mean while H1 will be ready in every 10 milliseconds. Then the expected behavior is to after each M1 run check Hx and execute H1 when ready.

If I understood your code well then you remove the executed H1 from `lv_task_ll` there fore it has no chance to run again when M1 is executed. As you said in your implementation: *"each task has at least one execution opportunity"* However THe HIGHEST priority newer should wait until all lower priority task is ready.

Here is my refined code with and_flag:

```c
/* Run all task from the highest to the lowest priority
 * If a lower priority task is executed check task again from the highest priority
 * but on the priority of executed tasks don't run tasks before the executed*/
lv_task_t * task_interruper = NULL;
lv_task_t * tmp;
do {
    end_flag = 1;
    LL_READ(lv_task_ll,tmp){

        /*Here is the interrupter task. Don't execute it again.*/
        if(tmp == task_interruper) {
            task_interruper = NULL;     /*From this point only task after the interrupter comes, so the interrupter is not interesting anymore*/
            continue;
        }

        /*Just try to run the tasks with highest priority.*/
        if(tmp->prio == LV_TASK_PRIO_HIGHEST) {
            lv_task_exec(tmp);
        }
        /*Tasks with higher priority then the interrupted shall be run in every case*/
        else if(task_interruper) {
            if(tmp->prio > task_interruper->prio) {
                if(lv_task_exec(tmp)) {
                    task_interruper = tmp;  /*Check all tasks again from the highest priority */
                    end_flag = 0;
                    break;
                }
            }
        }
        /* It is no interrupter task or we already reached it earlier.
         * Just run the remaining tasks*/
        else {
            if(lv_task_exec(tmp)) {
                task_interruper = tmp;  /*Check all tasks again from the highest priority */
                end_flag = 0;
                break;
            }
        }
    }
} while(end_flag);
```

**Comment by chenshijianworkgit** [comment]
Hi,
Yes, there are two linked list of words that you say, I was in order to avoid having a task frequently executed and take a long time。

May I did not understand the meaning of your previous code to achieve, you now see the code As long as the implementation of a non-highest priority task exit lv_task_handler function?

**Comment by chenshijianworkgit** [comment]
run a non-highest-priority task and exit the lv_task_handler function?

**Comment by chenshijianworkgit** [comment]
The two linked lists I implemented put the runed of high-priority tasks on other linked lists, in the situation that the high-priority tasks may not be queried in time。

Now discuss your code, whether end_flag assignment is wrong, because these two pieces of code in the loop will lapse.

if(tmp == task_interruper)
    ....

else if(task_interruper)
    ....

**Comment by kisvegabor** [comment]
Hi,
you are right. I didn't test the my code... :( The last line should be `while(!end_flag);` So until at leas one non-highest priority task is executed restart the polling. 

But I can't see the problem with the snippet you mentioned:
```c
if(tmp == task_interruper)
....

else if(task_interruper)
....
```
The `if` just ignores the interrupter task. Later in the `else if` run the tasks with higher priority then the interrupter. This structure won't run the tasks with priority of the interrupter (which is the desired behavior).

**Comment by chenshijianworkgit** [comment]
Hi,
After modifying the end_flag flag, these two judgments are valid.

This can not see any problem , look at the test results.

**Comment by kisvegabor** [comment]
Okay, I will make some test tomorrow.

**Comment by kisvegabor** [comment]
Hi,

I added a test in `lv_examples/lv_test/lv_test_misc/lv_test_task.c` and ad your changes to `lvgl/beta`.
Can you check them?

**Comment by chenshijianworkgit** [comment]
Okay, I'll see tomorrow, Happy New Year.

**Comment by kisvegabor** [comment]
Okay, happy new year!

**Comment by kisvegabor** [comment]
I close according to #99

**Pull request closed without merging**
