### PR TITLE
chore: make lv_utils as public and align function prototype with stdlib

### PR DESCRIPTION
**Pull request by XuNeo**
### Description of the feature or fix

1. chore(stdlib): use int as return type for strcmp and memcmp
    To keep the prototype same as stdlib
2.  chore(utils): make utils public
_lv_utils_bsearch has been renamed to lv_utils_bsearch for public usage. Function prototype is same as bsearch

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Please update all `lv_string_*.c` files.

**Review by liamHowatt — APPROVED** [review]
While I think it's important to match standard function signatures, I don't necessarily understand the need to return `int` from comparison functions as a general rule. In any case, LGTM.

**Review by FASTSHIFT — APPROVED** [review]

**Comment by kisvegabor** [comment]
> I don't necessarily understand the need to return int from comparison functions as a general rule. In any case, LGTM.

Well, as this PR show the  `int` return value is needed for `bsearch`. With this you can decide if a string is smaller or larger than an other one.

**Comment by liamHowatt** [comment]
I was wondering why all compare functions got the `int` return type, but now I realize that's so they can be used as callbacks to `bsearch`. Got it.

**Pull request merged**
