### PR TITLE
fix(sysmon): increase FPS sampling rate

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

Reduced FPS statistics period from 1000ms to 300ms.

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [x] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [x] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [x] Use typed pointers instead of `void *` pointers
- [x] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [x] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [x] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [x] `struct`s should be used via an API and not modified directly via their elements.
- [x] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [x] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [x] Arguments must be named in H files too.
- [x] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
[Here](https://github.com/lvgl/lvgl/issues/4221#issuecomment-1558929192) we were talking about adding some more info to sysmon.

What do you think about adding these?
```
CPU 38%, 30 FPS (12 redraws)
Render: 2ms, Flush: 1ms
```

**Comment by FASTSHIFT** [comment]
> [Here](https://github.com/lvgl/lvgl/issues/4221#issuecomment-1558929192) we were talking about adding some more info to sysmon.
> 
> What do you think about adding these?
> 
> ```
> CPU 38%, 30 FPS (12 redraws)
> Render: 2ms, Flush: 1ms
> ```

I agree, how can we measure the flush time, add a timestamp to the call_flush_cb or throw an event externally? Note that when using DMA+double draw buffer mode, the screen refresh and lvgl rendering are parallel, is this something to consider?

**Comment by FASTSHIFT** [comment]
I added count printing for redraw and refr in frame rate printing:

```bash
sysmon: 59 FPS (redraw: 2 / refr: 18), render 0 ms, CPU 1%
sysmon: 59 FPS (redraw: 0 / refr: 17), render 0 ms, CPU 1%
sysmon: 58 FPS (redraw: 1 / refr: 18), render 0 ms, CPU 2%
sysmon: 60 FPS (redraw: 1 / refr: 18), render 0 ms, CPU 3%
sysmon: 59 FPS (redraw: 1 / refr: 18), render 0 ms, CPU 3%
sysmon: 60 FPS (redraw: 1 / refr: 18), render 0 ms, CPU 2%
sysmon: 59 FPS (redraw: 1 / refr: 18), render 0 ms, CPU 2%
sysmon: 59 FPS (redraw: 1 / refr: 18), render 0 ms, CPU 1%
sysmon: 60 FPS (redraw: 1 / refr: 18), render 0 ms, CPU 1%
```

The reason I didn't display the label on the screen was that displaying too much data would be crowded and ugly on a small resolution device.

**Comment by kisvegabor** [comment]
> I agree, how can we measure the flush time, add a timestamp to the call_flush_cb or throw an event externally?

We could send `FLUSH_START` and `FLUSH_READY` events too where we can measure the flush time.

> Note that when using DMA+double draw buffer mode, the screen refresh and lvgl rendering are parallel, is this something to consider?

Yes, we should consider it too.

----

> The reason I didn't display the label on the screen was that displaying too much data would be crowded and ugly on a small resolution device.

Let reiterate. I think these are the things we should display:
- CPU busy
- render count: can be dropped IMO
- FPS:  avg time between `REFR_START`s (max is limited by the call period the refr timer)
- render time: avg time between `RENDER_START` and `RENDER_END`
- flush time: avg time between `FLUSH_START` and `FLUSH_END`
- total time: avg time between `RENDER_START` and `FLUSH_END` (it might be difficult to know which render start refers to which flush end with 2 draw buffers)


```
CPU 38%, 30 FPS
7 ms (4 | 3)
```

Where the last line means:
```
total time ms (render time | flush time)
```

I think it's not to long.

---

BTW, I think we can remove `disp->last_render_start_time` as it can measured if required in the `RENDER_START` event.

**Comment by FASTSHIFT** [comment]
> ```
> CPU 38%, 30 FPS
> 7 ms (4 | 3)
> ```
> 
> Where the last line means:
> 
> ```
> total time ms (render time | flush time)
> ```
> 
> I think it's not to long.

240x240 resolution, when both `LV_USE_PERF_MONITOR` and `LV_USE_MEM_MONITOR` are enabled, the display will overlap:
image

**Comment by FASTSHIFT** [comment]
> BTW, I think we can remove disp->last_render_start_time as it can measured if required in the RENDER_START event.

Done.

> flush time: avg time between FLUSH_START and FLUSH_END

Done.

I still recommend using LV_LOG output in detail, which is convenient for recording and observation, and now the LOG is like this:
```bash
sysmon: 61 FPS (redraw: 1 / refr: 18), render 1ms (flush 1ms), CPU 12%
sysmon: 61 FPS (redraw: 1 / refr: 19), render 1ms (flush 1ms), CPU 19%
sysmon: 61 FPS (redraw: 1 / refr: 18), render 1ms (flush 1ms), CPU 21%
sysmon: 61 FPS (redraw: 1 / refr: 19), render 1ms (flush 1ms), CPU 21%
sysmon: 61 FPS (redraw: 1 / refr: 18), render 1ms (flush 1ms), CPU 22%
sysmon: 61 FPS (redraw: 1 / refr: 19), render 1ms (flush 1ms), CPU 22%
sysmon: 61 FPS (redraw: 1 / refr: 18), render 1ms (flush 1ms), CPU 24%
sysmon: 61 FPS (redraw: 1 / refr: 19), render 1ms (flush 1ms), CPU 20%
sysmon: 62 FPS (redraw: 1 / refr: 18), render 1ms (flush 1ms), CPU 20%
sysmon: 61 FPS (redraw: 1 / refr: 19), render 1ms (flush 1ms), CPU 24%
```

**Comment by kisvegabor** [comment]
I agree to print a detailed log. It's also helpful to draw a chart from it later.

However, I'd like have simple real time data as well. Let's consider the 240 width as a minimum target where both mem and perf monitor should fit. Actually we need only a little bit of extra space. 

What about removing the "used" word from the mem monitor? 
```
12.3kB, 28%
19% frag.
```

**Comment by kdschlosser** [comment]
@FASTSHIFT 

Would it not be better to capture the current ticks and store that and then increment the frame count when the buffer gets drawn. Keep the existing mechanism that uses the timer and when that callback gets called to do the math to calculate the FPS. Doing it this way would mean it would make no difference when the function gets called to do the calculations becaause the calculation would assume thing.

```
fps = 1000 / ((stop_tick - start_tick) / frame_count)
```

example is...
```
start_tick = 100
stop_tick = 1350
frame_count = 65

fps = 1000 / ((1350 - 100) / 65)
fps = 1000 / (1250 / 65)
fps = 1000 / 19.23076923076923
fps = 52
```
    uint32_t fps = info->refr_elaps_sum ? (1000 * info->frame_cnt / info->refr_elaps_sum) : 0;

Once the calculation has been done then the start time gets set to the current tick and the frame count gets zeroed out. 
can also easily make this integer math right up to the point where the label gets set for the FPS.

doing this would take care of any inconsistencies in when lv_task_handler gets called. With the way it is done currently is it assumed that lv_task_hander is being called in a multiple of exactly 1 second, if it's not that is going to cause the calculation to be skewed.

**Comment by FASTSHIFT** [comment]
> I agree to print a detailed log. It's also helpful to draw a chart from it later.
> 
> However, I'd like have simple real time data as well. Let's consider the 240 width as a minimum target where both mem and perf monitor should fit. Actually we need only a little bit of extra space.
> 
> What about removing the "used" word from the mem monitor?
> 
> ```
> 12.3kB, 28%
> 19% frag.
> ```

All features are done, I think it's time to consider merging.

**Comment by FASTSHIFT** [comment]
LOG printing effect:
```bash
sysmon: 64 FPS (refr: 19 | redraw: 1 | flush: 1), refr 0ms (render 0ms | flush 1ms), CPU 0%
sysmon: 62 FPS (refr: 18 | redraw: 1 | flush: 1), refr 0ms (render 0ms | flush 1ms), CPU 0%
sysmon: 64 FPS (refr: 18 | redraw: 1 | flush: 1), refr 0ms (render 1ms | flush 0ms), CPU 0%
sysmon: 64 FPS (refr: 18 | redraw: 1 | flush: 1), refr 0ms (render 0ms | flush 1ms), CPU 0%
sysmon: 64 FPS (refr: 18 | redraw: 1 | flush: 1), refr 0ms (render 0ms | flush 0ms), CPU 0%
sysmon: 65 FPS (refr: 19 | redraw: 1 | flush: 1), refr 0ms (render 0ms | flush 0ms), CPU 0%
sysmon: 64 FPS (refr: 18 | redraw: 1 | flush: 1), refr 0ms (render 0ms | flush 2ms), CPU 0%
```

UI display effect:
image

**Comment by kisvegabor** [comment]
Cool :sunglasses: 
Thank you so much! Merging!

**Pull request merged**
