### PR TITLE
feature(arm2d): Add ARM2d support for older Cortex-M/SC

### PR DESCRIPTION
**Pull request by hpfaz**
### Description of the feature or fix

Add support for ARM2D acceleration without using NEON or HELIUM

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by XuNeo — APPROVED** [review]

**Comment by FASTSHIFT** [comment]
[Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig#L244) also needs to be updated along with it.

**Comment by kisvegabor** [comment]
I also find it cleaner. cc @GorgonMeducer

**Comment by GorgonMeducer** [comment]
The most important thing is that Arm-2D can **NOT** bring any performance boosts for old Cortex-M processors.

**Comment by hpfaz** [comment]
Hi @GorgonMeducer, 

Thank you for this in-depth answer. From what I understand, ARM-2D currently provides performance improvements only on cores supporting Helium. 
I wrongly assumed that older cortex-m cores would benefit from using the library's default software implementation.

**Comment by GorgonMeducer** [comment]
@hpfaz 

Arm-2D Synchronous mode can only accelerate Helium and Helium-ACI-based acceleration, which are only available on Armv8.1-m Architecture.  You will see several Cortex-M55/Cortex-M85 devices this year. 

For Arm-2D Asynchronous mode, it works as a regular Draw Unit (as it is fundamentally a 2D-GPU driver for DMAC-350). 

We have separate macro options to enable the Arm-2D Synchronous and Asynchronous modes, so no worry.

Again, thank you for your contribution. 

Have a nice day.

**Pull request closed without merging**
