### PR TITLE
docs:(pt-br) new README layout

### PR DESCRIPTION
**Pull request by iamrafaelmelo**
### Description of the feature or fix

Switch to new README layout

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by iamrafaelmelo** [comment]
@kisvegabor Sorry, I forgot you created a branch for this, so I ended up creating another branch.

**Comment by kisvegabor** [comment]
Thank you!
Yesterday I updated the Examples part. You can mostly copy-paste it, there is only 4 titles which should be translated. 
Could you add it too?

**Comment by iamrafaelmelo** [comment]
> Thank you! Yesterday I updated the Examples part. You can mostly copy-paste it, there is only 4 titles which should be translated. Could you add it too?

👍🏽

**Comment by kisvegabor** [comment]
Looks great! Thank you again :slightly_smiling_face:

**Comment by iamrafaelmelo** [comment]
> Looks great! Thank you again 🙂

it's a pleasure

**Pull request merged**
