### PR TITLE
fix lv_dropdown_get_selected_str

### PR DESCRIPTION
**Pull request by paulh002**
This fix checks for nullptr when the dropbox does not have content
Added a check for nullptr on dropdown->options if NULL then return buf[0]='\0';

### CODE REVIEW

**Comment by kisvegabor** [comment]
Looks good thanks.

Just please run  `scripts/code-format.py` or format the code like [this](https://github.com/lvgl/lvgl/runs/4583375375?check_suite_focus=true#step:6:28).

**Review by paulh002 — COMMENTED** [review]
updated formatting

**Comment by paulh002** [comment]
have run scripts/code-format.py

**Comment by kisvegabor** [comment]
Merging, thank you!

**Pull request merged**
