### PR TITLE
Handle LV_EVENT_CANCEL in list/group

### PR DESCRIPTION
**Pull request by tehkillerbee**
See #1655 for details

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thanks for the PR.

As I've mentioned in the original discussion some events are already forwarded to the button [here](https://github.com/lvgl/lvgl/blob/master/src/lv_widgets/lv_list.c#L667-L698).

I there a reason why can't we add it there as well?

**Comment by tehkillerbee** [comment]
I see what you mean but since the CANCEL button has a LV_SIGNAL_CONTROL signal type, it will never be passed on to the list button, hence the event never triggers. How do you suggest I change it?

**Comment by kisvegabor** [comment]
Oh sorry, you are right. I missed that the cancel even has no signal counterpart. 

Then your solution is fine.

**Comment by tehkillerbee** [comment]
I did find an alternative way to handle the issue - but then you need to have multiple event handlers - one for the list and one for the button :)

**Comment by kisvegabor** [comment]
I've commented in the issue.

**Pull request merged**
