### PR TITLE
fix(spinbox): add missing update value

### PR DESCRIPTION
**Pull request by mvladic**
Added lv_spinbox_updatevalue when step is changed with the pointer input.

### CODE REVIEW

**Comment by mvladic** [comment]
I made a mistake in the first commit, so I created another commit. Let me know if this is ok or if you want me to create another PR.

**Review by kisvegabor — APPROVED** [review]
Thanks!

**Review by liamHowatt — APPROVED** [review]
Thanks! I'm trying to understand what it fixes. Could you please explain a little bit?

**Comment by kisvegabor** [comment]
It fixes https://github.com/lvgl/lvgl/issues/6702

**Comment by kisvegabor** [comment]
Liam, please merge if all look good.

**Pull request merged**
