### PR TITLE
Fix key release sending click and release event

### PR DESCRIPTION
**Pull request by upbeat27**
Key release was sending both click + release events.

### CODE REVIEW

**Comment by embeddedt** [comment]
@kisvegabor Is this intentional?

**Comment by upbeat27** [comment]
OK - I see now that I removed the click event entirely.
I thought this was a duplicate click.

So, I think instead the click should in the
 ```c
if(data->state == LV_INDEV_STATE_PR && prev_state == LV_INDEV_STATE_REL)
```
 block.

To me, it doesn't really make sense that click + release would both occur on release.
Which begs the question: what is the difference between click and press?

Also:
Every single `lv_event_send` in `indev_*_proc` should be checked for the return value. It is possible the obj is deleted, but this isn't checked. Only 
```c
if(i->proc.reset_query) return; /*The object might be deleted*/
```
is checked.

**Comment by kisvegabor** [comment]
> Key release was sending both click + release events.
In case of KEYPAD there is no difference between CLICK and RELEASE. I added both of them to be consequent. In POINTER type they are a little bit different. See the comments here:
https://github.com/littlevgl/lvgl/blob/dev-6.0/src/lv_core/lv_obj.h#L78-L102
So with KEYPAD just one of them (I suggest CLICK) and use it in your event callback.

> Every single lv_event_send in indev_*_proc should be checked for the return value. It is possible the obj is deleted, but this isn't checked.

See this: https://github.com/littlevgl/lvgl/blob/dev-6.0/src/lv_core/lv_obj.c#L430
`lv_obj_del`  calls `lv_indev_reset` which sets `proc.reset_query`.

**Comment by upbeat27** [comment]
Closing this because it doesn't fix anything.
I don't think CLICK and RELEASE meaning the same thing for keypad makes sense, but that would be a separate issue.

**Comment by kisvegabor** [comment]
Some parts of the new code in `dev-6.0`  (like this) are just my vision and not discussed at all. So it's absolutely not sure that it's perfect in its current form. I'm very curious to hear any feedback.

To separate CLICK and RELEASE in case of POINTER input devices makes sense due to dragging.

However, I'm not sure calling both CLICK and RELEASE  in case of KAYPAD really makes sense.  I did it in order to work in the same way as a not dragged object with POINTER input device. Do you have a better, more intuitive idea?

**Pull request closed without merging**
