### PR TITLE
fix(style): merge scaler and noscalar variant into one

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

since there is no real difference between these two version

### Checkpoints
- [X] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by embeddedt** [comment]
There was a reason these were split. IIRC it's because the cast [here](https://github.com/lvgl/lvgl/pull/2072/files#diff-087bc0640cf295c3c4163edd16816cf31cf35db2ce45f57d6b7bd8c6b9c5f67bR64) causes a warning/error in C and/or C++ (I forget which) for non-scalar values.

**Comment by xiaoxiang781216** [comment]
Yes, that is why I select the version which has the cast. This one can work with both c and c++.

**Comment by embeddedt** [comment]
I tested with `-Wpedantic`, this is an example of the warnings I get:

```
lv_core/lv_obj_style_dec.h:80:5: note: in expansion of macro '_OBJ_GET_STYLE'
   80 |     _OBJ_GET_STYLE(prop_name, func_name, value_type, style_type)                                                         \
      |     ^~~~~~~~~~~~~~
lv_core/lv_obj_style_dec.h:156:1: note: in expansion of macro '_LV_OBJ_STYLE_SET_GET_DECLARE'
  156 | _LV_OBJ_STYLE_SET_GET_DECLARE(LINE_COLOR, line_color, lv_color_t, _color)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lv_core/lv_obj_style_dec.h: In function 'lv_obj_get_style_image_recolor':
lv_core/lv_obj_style_dec.h:64:16: warning: ISO C forbids casting nonscalar to the same type [-Wpedantic]
   64 |         return (value_type)_lv_obj_get_style##style_type(obj, part, LV_STYLE_##prop_name);          \
      |                ^
```

**Comment by xiaoxiang781216** [comment]
@embeddedt you are right, the cast version will generate the warning for lv_color_t struct. But, I found that the cast isn't really needed at all, so please review the new change which is more simpler and safer now.

**Comment by embeddedt** [comment]
Unfortunately the C++ compiler is now determined to find fault with your change. :wink: It won't allow implicit conversions from `void *` to `char *`.

```
lv_core/lv_obj_style_dec.h: In function 'const lv_font_t* lv_obj_get_style_value_font(const lv_obj_t*, uint8_t)':
lv_core/lv_obj_style_dec.h:64:45: error: invalid conversion from 'const void*' to 'const lv_font_t*' {aka 'const _lv_font_struct*'} [-fpermissive]
   64 |         return _lv_obj_get_style##style_type(obj, part, LV_STYLE_##prop_name);                      \
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             const void*
lv_core/lv_obj_style_dec.h:80:5: note: in expansion of macro '_OBJ_GET_STYLE'
   80 |     _OBJ_GET_STYLE(prop_name, func_name, value_type, style_type)                                                         \
      |     ^~~~~~~~~~~~~~
lv_core/lv_obj_style_dec.h:140:1: note: in expansion of macro '_LV_OBJ_STYLE_SET_GET_DECLARE'
  140 | _LV_OBJ_STYLE_SET_GET_DECLARE(VALUE_FONT, value_font, const lv_font_t *, _ptr)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lv_core/lv_obj_style_dec.h: In function 'const char* lv_obj_get_style_value_str(const lv_obj_t*, uint8_t)':
lv_core/lv_obj_style_dec.h:64:45: error: invalid conversion from 'const void*' to 'const char*' [-fpermissive]
   64 |         return _lv_obj_get_style##style_type(obj, part, LV_STYLE_##prop_name);                      \
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             const void*
lv_core/lv_obj_style_dec.h:80:5: note: in expansion of macro '_OBJ_GET_STYLE'
   80 |     _OBJ_GET_STYLE(prop_name, func_name, value_type, style_type)                                                         \
      |     ^~~~~~~~~~~~~~
lv_core/lv_obj_style_dec.h:141:1: note: in expansion of macro '_LV_OBJ_STYLE_SET_GET_DECLARE'
  141 | _LV_OBJ_STYLE_SET_GET_DECLARE(VALUE_STR, value_str, const char *, _ptr)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by xiaoxiang781216** [comment]
Yes, C++ doesn't allow void * convert to other pointer type, but I think extern "C" should tell the compiler switch to C mode.

**Comment by embeddedt** [comment]
I'm pretty sure extern "C" only changes the calling convention. I don't think it can change the C++ rule about pointer conversions (though it would be *extremely* useful if it did).

**Comment by xiaoxiang781216** [comment]
Ok, _OBJ_GET_STYLE get two version now:

1. C version without cast to avoid the warning, but depend on the relax C conversion rule
2. C++ version with cast to mitigate the strict C++ conversion rule, but depend on C++ nonscalar cast(actually C++ constructor)

Could you try agian with your case?

**Comment by embeddedt** [comment]
Both cases fail, however, if I invert the if condition to be `!defined(__cplusplus)`, everything seems to work.

With C file:
```
lv_core/lv_obj_style_dec.h: In function 'lv_obj_get_style_scale_end_color':
lv_core/lv_obj_style_dec.h:71:16: warning: ISO C forbids casting nonscalar to the same type [-Wpedantic]
   71 |         return (value_type)_lv_obj_get_style##style_type(obj, part, LV_STYLE_##prop_name);          \
```

With C++ file:

```
lv_core/lv_obj_style_dec.h: In function 'const lv_font_t* lv_obj_get_style_value_font(const lv_obj_t*, uint8_t)':
lv_core/lv_obj_style_dec.h:65:45: error: invalid conversion from 'const void*' to 'const lv_font_t*' {aka 'const _lv_font_struct*'} [-fpermissive]
   65 |         return _lv_obj_get_style##style_type(obj, part, LV_STYLE_##prop_name);                      \
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             const void*
```

**Comment by xiaoxiang781216** [comment]
Sorry, I use the wrong condition, your suggestion is right. The updated PR should be in the good shape now.

**Review by embeddedt — APPROVED** [review]
Builds without warnings on both now! Thanks!

**Comment by kisvegabor** [comment]
Great!
Thanks for the update and testing!

FYI, in v8 I have rather written a simple [python script](https://github.com/lvgl/lvgl/blob/dev-v8/scripts/style_api_gen.py) to generate these static inline functions. (See e.g. [here](https://github.com/lvgl/lvgl/blob/dev-v8/src/lv_core/lv_obj_style.h#L199)) Some people complain about the current form is hard to read. (And I think they are right)

**Pull request merged**
