### PR TITLE
feat(gen_json): adds option to gen_json to build without docstrings

### PR DESCRIPTION
**Pull request by kdschlosser**
Currently, in the MicroPython binding gen_json.py is used to properly map a callbacks userdata that is stored in a nonpublic structure. While doing this works without any issues it takes a bit of additional time for the gen_json.py script to run. This additional time is caused by the parsing of the docstrings from the header files. The docstrings do not need to be parsed in order to provide the information that the MicroPython binding code generator needs in order to work. Having the ability to turn off the docstrings will speed up the compile time, it also removes doxygen as a dependency to compile the binding.

I have also removed the threading from the gen_json.py script that was used to output dots to stdout. Having this causes issues if importing the gen_json.py script instead of running it using a subprocess.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kdschlosser** [comment]
@liamHowatt 
@kisvegabor

**Comment by kisvegabor** [comment]
I've tested it and both
```
time python3 gen_json.py --no-docstrings
``` 

and 

```
time python3 gen_json.py 
```

was running in ~30 sec. Is it expected?

**Comment by kdschlosser** [comment]
I had a missing comma in the code.

This is what I get for a difference in speed with and without the new build argument.

without: 71966 milliseconds
with: 3623 milliseconds

It makes a really big difference.

The biggest thing is the added dependency to build the binding which is used to collect the LVGL docstrings and they end up not even being used in the binding. no reason why doxygen and pycparser should be a requirement to compile the binding. pycparser ends up being an external requirement is due to the one that is attached to the binding is not what ends up being used because the call to run gen_json is done in a subprocess so it's not going to pick up on the one that is packaged with the binding.

**Comment by vwheeler63** [comment]
@kdschlosser   Nice work, sir!

**Comment by kdschlosser** [comment]
@vwheeler63 

are you seeing a speed difference between when using the new parameter?

**Comment by kisvegabor** [comment]
Now it's 1sec vs 34sec. Great work!

**Review by kisvegabor — APPROVED** [review]

**Review by liamHowatt — COMMENTED** [review]
:100: amazing but `"macros"` is now empty.

I use it to generate a binding and it's been such a fantastically useful tool!

**Comment by kdschlosser** [comment]
There is no way to get the macros to get spit out by the preprocessor those being populated was done strictly using doxygen because it has it's own internal preprocessor.lexer that it uses to collect that data. For the purposes of the MicroPython binding there is no parsing of the macros comntained in the JSON so it ends up being moot anyhow.

If at some point in time a person decides to dive in and give the binding code generator script an overhaul using only the JSON data then having the docstrings might be of use if and only if the code generator was also building a python stub file that represented the entire binding API docstrings and all. If that was done then Sphinx could be used to read the stub file and generate documentation for the binding.

rewriting that binding script is no small feat. It would take quite some time to do and there is going to be a point where it is going to have some kind of a complete failure that will force someone to rewrite it.

In my spin on the MicroPython binding I have made a lot of changes to the code generator. I have removed a lot of functions that get generated that didn't need to be there and I removed all of the print functions for all of the different structures as they add a very large amount of additional code size and memory use from all of the strings in those functions. I have been shipping away at it to remove unneeded things. The work I have done as reduced the compiled binary size by 300K which is a pretty large number when you are dealing with devices that have storage measured in megabytes.

Man I remember my first PC. 8088 processor with an 8086 math coprocessor, 512K of base memory with an expansion card to bring it up to 640K. That card was the size of video cards made today. 10MB MFM HDD, 5.25" floppy drive. 9" monochrome monitor.  OYE!!!

**Comment by kdschlosser** [comment]
@liamHowatt 

This is an optional thing to use. so you don't have to turn it on if you don't want to.

**Review by liamHowatt — APPROVED** [review]
Got it, so it's a known thing that macros require the docstring step.

**Comment by kdschlosser** [comment]
Yes it is known. there is no reason in the current binding's state to slow the build down to collect the docstrings since they are not used and neither are the macros.

You are going to need to update the binding adding the new gen_json parameter.

**Comment by vwheeler63** [comment]
> @vwheeler63
> 
> are you seeing a speed difference between when using the new parameter?

With the `--no-docstrings` option, it runs in approximately 4.6 seconds.

Without it, I get this:
```
Traceback (most recent call last):
  File "E:\Dev\Clients\WGA\lvgl\lvgl\lvgl\scripts\gen_json\gen_json.py", line 182, in run
    ast.setup_docs(no_docstrings, temp_directory)
  File "E:\Dev\Clients\WGA\lvgl\lvgl\lvgl\scripts\gen_json\pycparser_monkeypatch.py", line 609, in setup_docs
    docs = doc_builder.XMLSearch(temp_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Dev\Clients\WGA\lvgl\lvgl\lvgl\docs\doc_builder.py", line 1367, in __init__
    sys.stdout.write(out)
```

So if I change that doc_builder.py line 1367 to
```py
sys.stdout.write(out.decode("utf-8"))
```

then I get:
```
Traceback (most recent call last):
  File "E:\Dev\Clients\WGA\lvgl\lvgl\lvgl\scripts\gen_json\gen_json.py", line 182, in run
    ast.setup_docs(no_docstrings, temp_directory)
  File "E:\Dev\Clients\WGA\lvgl\lvgl\lvgl\scripts\gen_json\pycparser_monkeypatch.py", line 609, in setup_docs
    docs = doc_builder.XMLSearch(temp_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Dev\Clients\WGA\lvgl\lvgl\lvgl\docs\doc_builder.py", line 1370, in __init__
    sys.stderr.write(err)
```

So if I change doc_builder.py line 1370 to
```py
sys.stderr.write(err.decode("utf-8"))
```

Then Doxygen will not run because the `gen_json.py` code assumes the temporary directory and the scripts directory are on the same drive.

I COULD SWEAR I submitted a fix for all of the above about 4 weeks ago (when we discussed it), but I am not seeing it in any of my pending PRs....

**Pull request merged**
