### PR TITLE
[v6.0] Allow setting width and height individually on window button

### PR DESCRIPTION
**Pull request by turoksama**
Hi,
  Well, may somebody need to set its width & height separately?

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Good point, it really might be useful. But it's would be an API breaking change so let's postpone it until the `dev-6.0` branch will be created.

**Comment by turoksama** [comment]
Hi,
 So, will v5.3 be released right now? I'm eager to try.

**Comment by kisvegabor** [comment]
It will be released next week!

**Comment by turoksama** [comment]
👍Awesome!

**Pull request closed without merging**
