### PR TITLE
[v8/v7]workaround for rare crashes

### PR DESCRIPTION
**Pull request by alfiezhao**
### Test environment
QT simulator on PC & embedded software on cortex cm7 hardware
Up to 9 UI tasks (more than 4 widgets in each task) running at the same time & up to 4 UI tasks visible on the LCD screen
Frequently task switch, UI visibility change and widget content change happen in the background
Already used mutex lock to protect lv_task_handler() and widget content/visibility update

### Very rare crashes experienced (pretty hard to replicate, but still possible)
1, Null pointer access in lv_group.c lv_group_remove_obj(), g->obj_focus is null.
if(*g->obj_focus == obj) {

2, wild pointer or null pointer access in lv_obj.c where event_temp_data_head, or event_act_param, or event_act_user_data_cb are used. One of them becomes null or wild pointer but the lv function believes not.

### Workaround
1, Just added a pointer vilidity check to avoid this happening.
There may be a bug related to focus somewhere but I haven't got a chance to find it and fix.
2, Put event id, event param, event user data into a struct type and pass it to event handler directly without using any global variables.
With the workaround, crashes never happen again.

### Checkpoints
No idea, just want to raise a discussion or code review.
Better solutions are welcome.

### CODE REVIEW

**Comment by embeddedt** [comment]
The `obj_focus` NULL check looks fine to me; this shouldn't break any code.

However, I am not so sure about the event change. It seems to me that this is a major refactoring of the event system without a clear description of the flaw in the old approach. I feel like this may be hiding the bug and not completely solving it.

EDIT: While the event changes could be applied to v8 (since it's a major version), they cannot be applied to v7 as it must remain API-compatible.

**Comment by kisvegabor** [comment]
I also agree with the group-related changes.

I've just pushed a rework to `v8`'s events here https://github.com/lvgl/lvgl/tree/feat/new-event
It's a little bit similar to your changes to the event system.

**Comment by alfiezhao** [comment]
@embeddedt @kisvegabor 
I am not 100% sure about the obj change as well.
But those obj functions using global variables may be used indirectly by different UI tasks, and there is no mutex lock to protect those global variables, so you couldn't fix it outside the libaray by adding a mutex lock.
It's OK if UI changes and task swithes not very often, but for a system like I built, UI tasks swith frequently and the chance of switching task and modifing a global variable at the same time is very high, that's why crashes are seen now and then in my test.

**Comment by embeddedt** [comment]
I could be wrong, but I think proper use of a mutex should handle this case
correctly. `lv_task_handler` is running on one OS thread which means that
all events are going to get fired from that thread. As long as the mutex is
around lv_task_handler and all of the other threads' API calls, I don't see
a way for there to be concurrent access to the event variables.

**Comment by alfiezhao** [comment]
I checked the logic of that part many time and agree with your opinion, theoretically. @embeddedt 
In fact, how to find where needs a mutex lock is a big problem for the end user and lvgl would not be a robust library easy to use. Honestly I don't want to add mutex locks everywhere before and after each lv function in my project.
Using mutex lock is essential in a multiple task system but it would make lvgl robuster and easier to use if we can reduce the reliance on using mutex.

**Comment by embeddedt** [comment]
I completely understand. The mutexes can be quite annoying to use. However, if you are not currently putting a mutex around every lv function, that is very likely to be the reason why you are experiencing these random crashes. Your event change will probably only solve a specific race condition - there could be others.

In regards to reducing the need for mutexes in the long-term, there are two options:

* Only touch lv functions from one thread (the one calling `lv_task_handler`), and use your operating system's messaging mechanism to have that thread update UI objects. This avoids the need for mutexes altogether.
* Add multithreaded support to LVGL. It requires more discussion, as this introduces another level of complexity due to the need to unlock/lock multiple objects.

**Comment by alfiezhao** [comment]
I can make this problem clearer using an example. 
Leave lv_task_handler aside as there must be a lock protecting it. 
In task A,  update widget A, send lv event, task switched when  modifying a global event variable inside. 
In task B,  update widget B, send lv event, task switched when modifying the same global event variable. 
Based on current event design,  for thread safe, updating widget A and B couldn't happen at the same time. So here is the question,  do we have to build a connection between widget A and B in different tasks? I think the answer is NO. Just remove the global variable in the event function and make it re-entry one,  then the connection between them will be gone,  and the use of muted lock in your app will be very simple, one for lv task handler,  the other shared by all UI tasks,  and widgets in different UI tasks can be updated independently and concurrently.

**Comment by embeddedt** [comment]
There are other shared variables which two separate widgets can potentially
change. The only safe approach is to use the mutex whenever calling any lv
function.

**Comment by alfiezhao** [comment]
I am not talking about other shared variables. 
I was saying we don't have to use those shared variables for event processing. @embeddedt

**Comment by alfiezhao** [comment]
@kisvegabor 
Just saw you updated the event logic and I have reverted my code change to the event and only keep the fix for group.

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
@alfiezhao Thank you!
There are many conflicts at this moment. Could you reopen the PR with only the group related fix?

Regarding the thread safety: I don't really what would be the best way to do this. It's also possible that you have a global `lv_obj_t * btn1` that is accessed from 2 threads. So basically every `lv_` API function that writes any object needs to lock/unlock a mutex. And it sounds a little bit extragerrated.

**Pull request closed without merging**
