### PR TITLE
fix(kconfig): skip lv_conf.h by default

### LINKED ISSUE #4926: Finalize v9
Continue #3298 (see for the changes too)

### Schedule
1. **December 4**: Feature stop, start updating the docs and testing
2. **December 18**: Release candidate version and call to test
3. **January 15**: Release v9.0

### 1. Features to finalize
We don't add any new features but finalize these ongoing ones 
- [ ] Image decoder fine tuning (@XuNeo )
- [ ] Online image converter (@W-Mai)
- [ ] Cache update (@W-Mai and @FASTSHIFT #4835 )
- [x] Scale needle handling (@lhdjply ? #4917)
- [ ] Pointer scroll support (@kisvegabor / @XuNeo #4909)
- [ ] Add ESP-LCD support (@zjanosy  #4507)
- [ ] Add support for at least 3 display controller (@zjanosy)
- [x] Remove the MicroPython examples and replace them with a test (@kdschlosser #4645)

### 2. Prepare for release candidate (by December 18)
Docs review
- [x] [Porting](https://docs.lvgl.io/master/porting/index.html) (@kisvegabor )
- [x] [Drivers](https://docs.lvgl.io/master/integration/index.html) ( :warning: Help wanted)
- [x] [Widgets](https://docs.lvgl.io/master/widgets/index.html) (@kisvegabor )
- [x] [Overview](https://docs.lvgl.io/master/overview/index.html) (especially the image part)  ( :warning: Help wanted)

Demos end examples
- [x] [Examples](https://docs.lvgl.io/master/examples.html) (@kisvegabor )
- [ ] Review and update demos (@kisvegabor )

Others
- [x] Migration guide (@kisvegabor)
- [x] **Call to test and announce release candidate**  (@kisvegabor )
 
### 3. Fixes and last touches (by January 15)
Mainly for January
- [ ] CI update with more config options (@XuNeo and @kisvegabor)
- [ ] Final NXP drivers (@nicusorcitu)
- [ ] Arm2D support? (@GorgonMeducer )
- [ ] Project update (E.g. Eclipse, VSCode, etc)  ( :warning:  Help wanted)
- [x] Changelog (@kisvegabor)
- [ ] **Release** (@kisvegabor )

### PR DESCRIPTION
**Pull request by kisvegabor**
### Description of the feature or fix

fixes https://github.com/lvgl/lvgl/issues/4926#issuecomment-1923010736

cc @espzav @tore-espressif 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by espzav** [comment]
Hi @kisvegabor I added this PR: https://github.com/lvgl/lvgl/pull/5614/files which solving it too.

**Comment by kisvegabor** [comment]
I would keep the Kconfig as neutral as possible. If we start adding vendor specific things, I'm afraid we will have many of those.

**Comment by espzav** [comment]
> I would keep the Kconfig as neutral as possible. If we start adding vendor specific things, I'm afraid we will have many of those.

@kisvegabor I understand. But we are looking for any solution, how to set some specific oprions for all our projects. We wantes to do it in `esp_lvgl_port` component. We are not able to do it there, because `choice` is not possible to change by `select XXX`. If we want to make default (recommended) settings for all IDF/BSP examples, we can put it only into example `sdkconfig.default`. Same for customers project. Please, could you help us to find solution for this?

@tore-espressif Have you got any other input for this, please?

**Review by FASTSHIFT — APPROVED** [review]

**Review by PGNetHun — APPROVED** [review]

**Comment by tore-espressif** [comment]
> @tore-espressif Have you got any other input for this, please?

Your proposed solution in #5614 LGTM

**Comment by kisvegabor** [comment]
It seems this issue is more complicated than it seemed. I'll merge this now as hot fix and let's continue the discussion in #5624

**Pull request merged**
