### PR TITLE
Page end padding

### PR DESCRIPTION
**Pull request by BrianPugh**
Added define macros for whether or not the end padding should be included for scrolling in a page. This is useful when your content barely fits in the page and scrollbar is set to auto. Scrolling just to see the bottom/right empty padding seems a bit silly.

I don't see this being super useful to a lot of people, but its a simple tweak. This could also be set at runtime if we change it to attributes of the page's `ext`. There are free bits in the sb field, so it wouldn't take up any additional memory.

### CODE REVIEW

**Comment by kisvegabor** [comment]
I see your goal and its really reasonable. 
If I understood well your code prevents scrolling if the scrolling can show only the right/bottom padding.

I'd like to suggest a more general approach. Just not display the scrollbar if there is no more content to show.
It's easy to implement, just remove the `* 2` here: https://github.com/littlevgl/lvgl/blob/dev-5.3/lv_objx/lv_page.c#L1098

And I can imagine a new element in `lv_sb_mode_t`:  `LV_SB_MODE_NO_DUMMY` which can work like `lv_page_set_sb_mode(page, LV_SB_MODE_AUTO | LV_SB_MODE_NO_DUMMY)`.

I'd prefer this approach because it doesn't limit the functionality of the page which might be important for other objects.

**Comment by BrianPugh** [comment]
I've been a little busy, I'll try to get to these pull requests some time in the next few days.

**Comment by BrianPugh** [comment]
So to clarify:

In af88bdc I set a macro to remove the `*2` in 4 places:

* Vertical scrollable area (allows screen to scroll up/down)
* Horizontal scrollable area (allows screen to scroll left/right)
* Show Vertical scrollbar
* Show Horizontal scrollbar

You're suggesting to just hide the scrollbar, but still allow the content to move even if there is only padding to show, correct?

**Comment by kisvegabor** [comment]
Great!

> You're suggesting to just hide the scrollbar, but still allow the content to move even if there is only padding to show, correct?

Yes, my suggestion was to leave the scrolling enabled just don't display scrollbars. IMO, disabling the scrolling too might be confusing for the user. What do you think?

**Comment by BrianPugh** [comment]
I think that if the screen is scrollable, and the scrollbar mode is set to AUTO, then the scrollbar should always be shown regardless if it's just padding content.

For my exact issue, i can just resolve it by removing the vertical padding and offsetting my page object, was just seeing if this could evolve into a useful feature.

**Comment by kisvegabor** [comment]
> For my exact issue, i can just resolve it by removing the vertical padding and offsetting my page object, was just seeing if this could evolve into a useful feature.

Glad to hear that you solved it! 

If there is top padding but the bottom padding is not visible the user might try to scroll to see if there was something else still there. And he would expect to see the bottom padding. Else he might think that the scrolling is not working.

I don't see a really good solution for it right now, so I vote for leaving it as it is now.

**Comment by BrianPugh** [comment]
closing this as there is no action to take. Thanks!

**Comment by kisvegabor** [comment]
I thank you too!

**Pull request closed without merging**
