### PR TITLE
chore(cmsis-pack): Update cmsis pack for v9.3.0-dev

### PR DESCRIPTION
**Pull request by GorgonMeducer**
A clear and concise description of what the bug or new feature is.

- Update cmsis-pack for v9.2.1
- Minor fixes in lv_demo_benchmark

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
Catch up with #6845

**Review by FASTSHIFT — DISMISSED** [review]

**Review by kisvegabor — DISMISSED** [review]
Thank you Gabriel!

**Comment by kisvegabor** [comment]
Oh, wait! Svg was merged to master.

**Comment by GorgonMeducer** [comment]
SVG has been added already. As I mentioned before, the pack contains #6845

**Review by liamHowatt — COMMENTED** [review]
Looks good. Is it waiting for the v9.2.1 release before merging?

**Comment by kisvegabor** [comment]
Ah, I see the root of the confusion. v9.2.1 is released based on the `release/v9.2` branch, but this PR is targeting `master`. Can we handle patch releases like this in CMSIS-PACKs?

No that `master` already has a lot of features which won't be added in v9.2.1

**Comment by kisvegabor** [comment]
Just make sure that we are on the same page. If we had an update for v8.4 (`release/v8.4`) what could we do with CMSIS packs? 

I thought we can host the new packs in the related `release/v*.*` branch. If that's the case, we don't need to update `master` now just `release/v9.2` where there were only bugfixes.

**Comment by GorgonMeducer** [comment]
> Just make sure that we are on the same page. If we had an update for v8.4 (release/v8.4 branch) what could we do with CMSIS packs?

The cmsis-pack for v8.4 is based on the v8.4 branch.

> I thought we can host the new packs in the related release/v*.* branch. 

Well, this is new to me. In the past, for example, v9.0.0, v9.1.0 and v9.2.0, all those packs are created on master branch. So for me, I thought that v9 packs will be always created based on master and v8.x packs will created based on dedicated v8 branch.

This is truly the first time you said that a v9 cmsis-pack (v9.2.1) should based on a dedicated branch rather than the master.

It is OK to create cmsis-pack based on a specified branch, but you should let me know rather than assume I do that you thought without clearly telling me, especially under the background that we used master to create v9 packs in the past.

**Comment by GorgonMeducer** [comment]
> we don't need to update master now just release/v9.2 where there were only bugfixes.

This PR is already ready. I can rename it as v9.3.0-dev. And the most important thing is that the PDSC needs an update. Even if we don't do it now, we need to update the PDSC in the future when we decide to release v9.3.0. 

@kisvegabor

**Comment by GorgonMeducer** [comment]
rename this cmsis-pack as v9.3.0-dev

**Comment by GorgonMeducer** [comment]
Please review @kisvegabor 
- v9.2.1 cmsis-pack based on the v9.2 branch #7092 
- v9.3.0-dev cmsis-pack based on the master #7080

**Comment by GorgonMeducer** [comment]
Soon I guess.

**Review by liamHowatt — APPROVED** [review]

**Comment by kisvegabor** [comment]
Sorry Gabriel, I thought you are aware of our release policy. Anyway, next time I'll be more careful. Thank you!

**Review by kisvegabor — APPROVED** [review]

**Comment by kisvegabor** [comment]
@Linjieqiang 
I've just opened https://github.com/lvgl/lvgl/issues/7098 to track the release of v9.2.1. We still need to fix a problem reported [here](https://github.com/lvgl/lvgl/pull/6981#issuecomment-2417037919).

**Comment by GorgonMeducer** [comment]
> Sorry Gabriel, I thought you are aware of our release policy. Anyway, next time I'll be more careful. Thank you!

It's also my problem. I should trace the community policy more often. 
Thank you for merging this PR.

Have a nice day.

**Pull request merged**
