### PR TITLE
Placeholder text for lv_ta

### PR DESCRIPTION
**Pull request by MiSimon**
Added a second label to lv_ta, this label is used as text placeholder and will only be visible if the text area contains no text.

LV_TA_STYLE_PLACEHOLDER was added to assign a style to the placeholder label.

### CODE REVIEW

**Comment by kisvegabor** [comment]
I've added some fixes:
- If somehow the scrollable has a style with non zero padding the to label needs to positioned to the same coordinates.  It normally not happens with the TA but can happen with an object derived from TA. Test with: `lv_page_set_style(ta, LV_PAGE_STYLE_SCRL, &lv_style_plain);`
- in `placeholder_update` is used `ta_text[0] == '\0'` instead of `strlen` because `len` was used only to decide the length is `0` or `not 0`;
- use `LV_LABEL_LONG_BREAK` by default
- handle the placeholder in `lv_ta_set_one_line()`

What do think about the changes?

**Comment by MiSimon** [comment]
Maybe we should check the font height of the label and the placeholder in lv_ta_set_one_line, just in case someone uses a bigger font for the placeholder.

**Comment by kisvegabor** [comment]
Good idea.  
However, if the two fonts are different - and we take into account the placeholder's font height too - then the TA height will be changed when the first character is entered and change again when the last character is deleted. IMO it'd look ugly. So I vote for leaving the height according to the main label's font.

**Comment by MiSimon** [comment]
Then we leave it as it is, i don't believe that many people would like to use two different fonts or font sizes for the text and the placeholder.

**Comment by kisvegabor** [comment]
Ok, then I merge it!

Thank you for your PRs for Text area. You made it really better! :+1:

**Comment by prestonbrown** [comment]
Root cause: `WizardWifiStep::cleanup()` calls `clear_network_list()` which uses `safe_delete_deferred()` on each network item. These queue async timer deletes that race with `lv_obj_clean(content)` synchronous parent deletion, corrupting the heap. When the WiFi step is recreated, `lv_xml_create` → `XML_GetBuffer` → `lv_malloc` hits the corrupted heap and aborts.

Fix: removed `clear_network_list()` from cleanup — the framework handles all child deletion.

**Pull request merged**
