### PR TITLE
fix(arc): Free memory when drawing full-circle arc

### PR DESCRIPTION
**Pull request by DCSBL**
### Description of the feature or fix

Please see #2868 

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by DCSBL** [comment]
This fixes #2868 for me. Keep in mind that this is my first PR for LVGL; I have no idea if this can cause other issues.

**Review by embeddedt — APPROVED** [review]

**Comment by embeddedt** [comment]
Thanks!

**Comment by DCSBL** [comment]
Is this something that will be released with, for example, ~8.0.3~ 8.1.x?

**Comment by embeddedt** [comment]
The commit which added the bug isn't in 8.0, so I don't think the same fix is needed there.

We probably need to release 8.1.1 soon, however.

**Comment by DCSBL** [comment]
Eh, yeah that is what I wanted to ask but didn't. Thanks 👍

**Pull request merged**
