### PR TITLE
Change int32_t to int16_t in animation functions to fix warnings

### PR DESCRIPTION
**Pull request by BrianPugh**

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]
A better option might be to use `lv_anim_value_t`; that way it would be compatible with future updates to the library.

https://github.com/littlevgl/lvgl/blob/22195f34554886ff1c9ab1b537c8168b2f6afcae/src/lv_misc/lv_anim.h#L38-L39

**Comment by kisvegabor** [comment]
@embeddedt I agree, `lv_anim_value_t` would be more consistent.

**Comment by BrianPugh** [comment]
alright going through this now; I'm also doing some minor anim fixing in general, will push a commit soon

**Comment by BrianPugh** [comment]
Just pushed a bunch of changes

Notable changes:

1. Made some `anim` struct variables in objects exist only if animations are enabled. Also rearranged the structs for better packing.
2. changed the dtype of `size` in `lv_list` from a `uint32_t` to a `uint16_t`. I think that it's impractical to exceed 65535 items in a list, given lvgl's intended targets. The device would probably need >10MB of RAM just for the list. Also who would want to scroll through that.

I haven't tested this with animation disabled in the pc_simulator, will have to do that later today.

**Comment by BrianPugh** [comment]
I am actually unable to build using pc_simulator_sdl_eclipse on the `dev-6.0` branch. @kisvegabor  @embeddedt can you look into it

**Comment by embeddedt** [comment]
@BrianPugh There are a few issues which I am now fixing. I'll let you know once I've pushed the updates.

**Comment by embeddedt** [comment]
@BrianPugh It should be working now. You'll need to pull and update the submodules.

**Comment by BrianPugh** [comment]
Thanks @embeddedt ! Question: should the `edge_flash` feature of `lv_page` require animations to be enabled?

**Comment by embeddedt** [comment]
@BrianPugh It already does...

https://github.com/littlevgl/lvgl/blob/ba3e7d1da6e3215631b59114860b6ade2268c0be/src/lv_objx/lv_page.c#L582-L603

Maybe I'm misunderstanding something?

**Comment by BrianPugh** [comment]
I'm just wrapping more variables in the `ext` struct in `#if LV_USE_ANIMATION` to save some memory, and thusly have to wrap some function calls as well; so just double checking that this is true. I'll commit more stuff this evening.

**Comment by BrianPugh** [comment]
Alright, everything compiles and functions now when animations are enabled/disabled. This saves memory by removing all animation or edge_flash references when animations are disabled. I'm believe this is ready for merging.

**Comment by kisvegabor** [comment]
It seems working here too. Thank you very much for the fixes!

**Pull request merged**
