### PR TITLE
lv_task_cb_t definition and casting to prevent warnings in lv_task_cr…

### PR DESCRIPTION
**Pull request by BrianPugh**
…eate calls

### CODE REVIEW

**Comment by BrianPugh** [comment]
really, now that I know whats going on, it should really be `typedef void (*lv_task_cb_t)(lv_task_t *);` for greater clarity and to fix some compiler warnings.

**Comment by embeddedt** [comment]
(cc @kisvegabor)

**Comment by kisvegabor** [comment]
@BrianPugh 
Meanwhile, I've also fixed some of these issues. Can you test with the latest version again?

**Comment by BrianPugh** [comment]
Your updates seem good, making this PR unnecessary. Thanks!

**Comment by kisvegabor** [comment]
Thank you for the feedback!

**Pull request closed without merging**
