### PR TITLE
First CI action for performance check of LVGL code base with SO3

### PR DESCRIPTION
**Pull request by daniel-rossier**
### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by daniel-rossier** [comment]
Currently, the workflow uses the LVGL code base as deployed in SO3. Of course, we will find adapt the workflow to pick up the code in the master branch from LVGL and incorporate in SO3 usr/lib/lvgl directory. But we need to be careful with the small patches required to be SO3 compliant. 
Anyway, I would like to create a branch from master dedicated to so3_lvgl workflow tuning & optimization.

**Comment by kisvegabor** [comment]
Thank you, Daniel.

image
So it runs in 3 minutes? Amazing! :1st_place_medal: 

I've created the `ci/perf_test` branch and rebased this PR there. I've noticed that all other CI actions are removed. Was it intentional?

**Comment by daniel-rossier** [comment]
Great! Thank you Gàbor. Sorry for the other CI actions. I guess I removed them to go faster. They will be restored.

**Comment by daniel-rossier** [comment]
Do I have permission to push commits on this branch? I also noticed that check_perf.yml was missing.

**Comment by kisvegabor** [comment]
You can push commits to your branch and this PR will be updated automatically.

**Comment by daniel-rossier** [comment]
What do you mean with "your brach", is it the ci/perf_test branch? or a branch from my fork?
Because I get the following message when trying to push on the branch:
```
rossierd@rossierd-xps-15-9520:~/lvgl/lvgl$ git branch
* ci/perf_test
  master
rossierd@rossierd-xps-15-9520:~/lvgl/lvgl$ git push
ERROR: Permission to lvgl/lvgl.git denied to daniel-rossier.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
rossierd@rossierd-xps-15-9520:~/lvgl/lvgl$ 

```

**Comment by kisvegabor** [comment]
I mean the branch from your fork.

**Comment by daniel-rossier** [comment]
I'm currently moving from the vexpress machine to "virt" to be able use a more recent version of U-boot and to have recent version of QEMU too. However, this requires to patch QEMU to have the CLCD, keyboard and mouse support as before. SO3 does not implement virtio drivers.

**Comment by daniel-rossier** [comment]
Is it possible to re-open this PR?
Just a matter of time and availability.

**Comment by kisvegabor** [comment]
Sure!

**Comment by daniel-rossier** [comment]
Things are moving as much as possible. Migrated to QEMU/virt instead of vexpress, but it required some patches for framebuffer support as for vExpress.

**Comment by daniel-rossier** [comment]
I'm on it. I'm finalizing the deployment. Then, I will need specific objectives for further testings.

**Comment by daniel-rossier** [comment]
Still ongoing... Holidays times and higher prioritiy activities.

**Comment by daniel-rossier** [comment]
Still ongoing...

**Comment by daniel-rossier** [comment]
I'm about to release a new version of SO3. Then, I will be able to take this version for this environment, and go ahead with the CI.

**Comment by daniel-rossier** [comment]
SO3 2023.6.0 has been released on github. I will do the adaptation to have a 64-bit QEMU/virt version for the non-regression performance test as well.

**Comment by daniel-rossier** [comment]
I started to validate LVGL on QEMU/virt64 but I'm facing an issue in the draw area function, so investigations are ongoing.

**Comment by kisvegabor** [comment]
Let me know if you need an help with that?

**Comment by daniel-rossier** [comment]
> Let me know if you need an help with that?

Thanks Gàbor! So far, I suspect an issue in our internal mapping function.

**Comment by daniel-rossier** [comment]
Still fixing the 64-bit bug (on my free time, so it's not going fast ;-))

**Comment by daniel-rossier** [comment]
UPD 10.10.23: well, the bug was due to the tlsf memory allocator which used a pool of 32 KB. Increasing to 64 KB solved the issue.

**Comment by daniel-rossier** [comment]
Now, I made significant progress on this PR. It is now possible to get a file as artifact which summarizes the duration of a function execution. The workflow action contains the release to be checked, for instance the v8.3 as currently.
Also as example, the current stress app looks for the delay of lv_timer_handler() execution.

I will document the whole process in the coming days.

**Comment by daniel-rossier** [comment]
Namely, the yaml script is still at early stage, but is full functional. I will improve it with some configuration variables - for example to choose which branch of LVGL must be checked .
Furthermore, the CI produces an simple file artifact which should be processed and raises some notifications in case of threshold exceeding, etc.

**Comment by daniel-rossier** [comment]
Apparently, the only check from the CI which failed is something related to ``codecov``:

```
[2023-10-19T17:24:42.966Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Could not find a repository, try using repo upload token', code='not_found')}
[2023-10-19T17:24:42.966Z] ['verbose'] The error stack is: Error: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Could not find a repository, try using repo upload token', code='not_found')}
    at main (/snapshot/repo/dist/src/index.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-10-19T17:24:42.9[66](https://github.com/daniel-rossier/lvgl/actions/runs/6578091673/job/17871075340#step:6:67)Z] ['verbose'] End of uploader: 1175 milliseconds
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov' failed with exit code 255
```

**Comment by kisvegabor** [comment]
Thank you Daniel. 

I think it should be based on `master` as now 1,674 files were changed :slightly_smiling_face:

**Comment by kisvegabor** [comment]
I've changed the target branch to master and now there only 9 changed files.

**Comment by daniel-rossier** [comment]
Thanks Gàbor, I guessed I had rebased to master, but it didn't seem to be the case.

**Comment by kisvegabor** [comment]
The target branch (where you would like to merge the PR) can be changed on GitHub here: 
image

Anyway, please let me know if there is a brief docs about the usage so that I can try it out. 
Can't wait to see how it works!  :slightly_smiling_face:

**Comment by daniel-rossier** [comment]
@AnthoJack is now following this ongoing development. He will set up the documentation very soon.

**Comment by daniel-rossier** [comment]
> We need some feedback on this pull request.
> 
> Now we mark this as "stale" because there was no activity here for 14 days.
> 
> Remove the "stale" label or comment else this will be closed in 7 days.

Okay, holidays time :-)

**Comment by daniel-rossier** [comment]
> > We need some feedback on this pull request.
> > Now we mark this as "stale" because there was no activity here for 14 days.
> > Remove the "stale" label or comment else this will be closed in 7 days.
> 
> Okay, holidays time :-)

Anthony needs to  finalize the instrumentation part with a custom `mcount()` function and should push a first version this week hopefully. Then this PR could be finalized.

**Comment by AnthoJack** [comment]
Hi @kisvegabor,

I've been working with @daniel-rossier on some tools and documentation to use when writing performance tests for LVGL in SO3. We had the idea of using gcc's profiler ("-p" option) to calculate the execution time of functions without requiring the developper to get timestamps manually before and after the function's execution. However, gcc only adds enough code to call a function at the start of a function but not at the end so we designed and implemented a custom function to "hack" the stack and allow another function to be executed at the end. You can find more information about it [here](https://github.com/smartobjectoriented/so3/blob/40-expand-and-document-lvgl-perf-tests/doc/source/lvgl.rst)

The functions provide timestamps of the start and end of functions from a file compiled with the profiler option. I've written some doc about its usage [here](https://github.com/daniel-rossier/lvgl/blob/master/docs/cicd/index.rst)

After that, a custom script retrieves the timestamps from the log of the program's execution, calculates the functions' execution time and finds the name of the functions in the elf file. The script is found [here](https://github.com/smartobjectoriented/so3/blob/40-expand-and-document-lvgl-perf-tests/scripts/prof_analyzer.sh) and I wrote a small test program [here](https://github.com/smartobjectoriented/so3/tree/40-expand-and-document-lvgl-perf-tests/usr/src/prof_test)

We would like your input as to how to continue from here

Best regards

**Comment by kisvegabor** [comment]
Hey,

Thank you for the update! 

>  we designed and implemented a custom function to "hack" the stack and allow another function to be executed at the end. 

Wow, that's really something! 

> After that, a custom script retrieves the timestamps from the log of the program's execution, calculates the functions' execution time and finds the name of the functions in the elf file. The script is found [here](https://github.com/smartobjectoriented/so3/blob/40-expand-and-document-lvgl-perf-tests/scripts/prof_analyzer.sh) and I wrote a small test program [here](https://github.com/smartobjectoriented/so3/tree/40-expand-and-document-lvgl-perf-tests/usr/src/prof_test)

I think something like this would be easier to use for us:
```c
uint32_t  start = get_cycle_count();
lv_area_intersect(...)
lv_style_set_border_width(...)
uint32_t  end = get_cycle_count();

uint32_t diff = end - start;
assert(diff < 1000);
```
This we can profile any code snippets, not only LVGL functions and we can easily test the result.

Is it also possible?

**Comment by kisvegabor** [comment]
I see, thank you for the explanation. 

To see that everything is really working together. Could you add a real test which can fail if the measured time is too long?

**Comment by AnthoJack** [comment]
Hi,
Just to give you a little run down of what I'm working on right now.

The idea is to eventually have the action work as shown in this diagram 
LvglCheckPerfAction
The files names are subject to change but the concept is as follows:

1. The action retrieves the commit of LVGL that triggered the action and the dockerfile from SO3
2. The Dockerfile generates an image that executes SO3 with an LVGL program built with our profiling tool
3. Within docker, the output of SO3 is analysed by a bash script to generate a list of functions with their execution time.
4. The resulting file is copied to the github action context and stored as an artifact
5. The data contained in the retrieved file is compared by a python script to the thresholds set (and eventual previous execution results). The script generates a report showing which functions have failed to respect their set threshold, which functions are slower than their previous execution...etc
6. The report is stored as an artifact and if any function failed to meet its expected threshold, the action fails. Otherwise, the action succeeds

I've implemented and tested the different scripts necessary to analyse the program's output and generate a performance report from the different files. Now I need to implement the action and I should be able to give you a working example in 1-2 weeks

PS: Currently, the profiling program and threshold file are stored in the SO3 repository. Ideally, they should end up in the LVGL repository so that people working on new features are also responsible for writing the profiled functions. We'll need to discuss about where I can place the files for it 

Best regards

**Comment by kisvegabor** [comment]
Sounds great! Thank you for putting all these together!

We can have a new `perf` folder [here](https://github.com/lvgl/lvgl/tree/master/tests) to store all the related data including the reference execution times.

**Comment by AnthoJack** [comment]
Hi @kisvegabor,
Sorry for the delay, we had to fix some things to make the action work but it should be OK now.
You can go [there](https://github.com/daniel-rossier/lvgl/actions/workflows/check_perf.yml) to have a look at the action. You should see that the penultimate action run has failed due to one function overshooting its set threshold and the last action succeded (I changed the threshold). Everything should still work as per the diagram I posted in this thread

SO3 had to undergo some modifications to make things work which are currently only on a specific branch that the action is set to use. Once everything is as you want it and we do the final merge, I'll change the action just before so that it uses the main branch of SO3

Please let me know if there is anything more you want to know

**Comment by kisvegabor** [comment]
Thank you for the update!  It looks easy to use and manage! To proceed step by step I suggest finalizing this PR and merging it to a feature branch. After that we can add a few more tests as an experiment and if all works well we can merge it to master. What do you think?

@liamHowatt could you also take look at it? The summary is [here](https://github.com/lvgl/lvgl/pull/4122/files#diff-f1d9e8444d36c3c1c0c0f83209d810868f92876cfab21d04dd369b52dabfaa55).

**Comment by kisvegabor** [comment]
Cool! I've created the `ci/perf_test` branch. Please re-target this PR to this branch.

**Comment by AnthoJack** [comment]
@kisvegabor Thanks but I don't have the permissions required to modify the base branch for this PR. Any way I can obtain them ?

**Comment by kisvegabor** [comment]
I modified the base.

**Comment by AnthoJack** [comment]
Hello,
I've been working on syncing our fork with the upstream bu this has led to some problems due to the CMakeList that changed. Will keep you posted

**Comment by AnthoJack** [comment]
I've managed to fix the problem and now the action seems to [work fine on our fork](https://github.com/daniel-rossier/lvgl/actions/runs/9514973340/job/26228259681) with the newest version of LVGL. On the original repo, it doesn't due to the job's id being different but ultimately it is an easy fix once the PR is merged

**Comment by kisvegabor** [comment]
I've rebased the `ci/perf-test` branch on `master` and now only 19 files have been changed. I merge this PR to now to have fixed point. 
In a new PR please fix the code formatting issue (by running `scripty/code-format.py`) and the Job ID.

**Pull request merged**
