### PR TITLE
Add support for GD32F450 "IPA" 2D GPU.

### PR DESCRIPTION
**Pull request by trollcop**
Hardware appears to be buggy, see the discussion at https://github.com/lvgl/lvgl/issues/3618

### Description of the feature or fix

Adding support for GD32F450 "IPA" 2D accelerator for fills/alpha blending.

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

If I must update the docs, I'll do it I guess.

### CODE REVIEW

**Comment by trollcop** [comment]
Thanks to the errata discussion in #3618 I've added fixes which make this GPU module usable.

I've verified it working with RGB565 input on 800x480 LCD, running `lv_demo_benchmark()` in both -O0 and -Os/-Ofast release modes.

Due to the hardware fill bug, the wait_cb functionality cannot be used (while IPA is filling, it may trash stack/related vars nearby), so I've made every GPU operation wait for it's completion, a hard wait for FILL, and a busywait calling wait_cb for the 2D copy/alphablend, since those do not trash nearby memory regions.

I guess this can be tested and/or merged, as it does work around all the current bugs.

**Comment by embeddedt** [comment]
Do you all think it is worth adding functionality to LVGL to oversize the buffer slightly for buggy hardware like this? From what I can tell, if the buffer were two pixels larger, the blocking would not be necessary.

**Comment by trollcop** [comment]
> Do you all think it is worth adding functionality to LVGL to oversize the buffer slightly for buggy hardware like this? From what I can tell, if the buffer were two pixels larger, the blocking would not be necessary.

That was the first thing I tried, but I either did it wrong or something, but even increasing the buffer size by one line would still crash with non-backing up fill operation.

**Comment by kisvegabor** [comment]
> Do you all think it is worth adding functionality to LVGL to oversize the buffer slightly for buggy hardware like this? From what I can tell, if the buffer were two pixels larger, the blocking would not be necessary.

I'm not convinced either. We are still investigating if a workaround exists. If this GPU can be supported at least to some extent it can serve as reference and can be good starting point when the HW issue is fixed.

**Comment by trollcop** [comment]
The python build test failing looks to be unrelated to this code? I've fixed all the other issues.

**Comment by kisvegabor** [comment]
The CI error could be resolved by rebasing to master. 

However let's come to conclusion about the usefulness of adding a little bit buggy, not so fast GPU. What do you think?

@embeddedt

**Comment by embeddedt** [comment]
Has GD officially explained the reasoning behind the two-pixel backup approach? I'd be fine with adding it if the errata were clearly documented, and we had a good enough workaround, but right now it sounds like the documented errata doesn't match reality.

**Comment by kisvegabor** [comment]
True, now it's the "seems working somehow" situation.

**Comment by trollcop** [comment]
> Has GD officially explained the reasoning behind the two-pixel backup approach? I'd be fine with adding it if the errata were clearly documented, and we had a good enough workaround, but right now it sounds like the documented errata doesn't match reality.

I'm in an email thread with them (was out of office for a bit, now back) trying to get more detail. I also have their FAE guys in a wechat group and will follow up to understand the discrepancy between errata saying 1 pixel and them backing up two.

Also I was told this *has* been fixed in F470 (the HW i'm using is F450)

**Comment by kisvegabor** [comment]
Great, please keep us posted :slightly_smiling_face:

**Comment by trollcop** [comment]
I have an update which explains why need to backup 1 or 2 pixels.

I did some testing, printing out the address of the tail of the fill buffer pointer, as well as the 2 backed up pixels, and the fill pixel:

here, [2000a682 AE74AE74->4227AE74] is %p of end_ptr, followed by backup[0][1], followed by end_ptr[0][1]

```
157,"lv_draw_gd32_ipa_blend_fill: 20001316 (365 x 51) stride=370, color=4227 [2000a682 AE74AE74->4227AE74]" one
158,"lv_draw_gd32_ipa_blend_fill: 20001458 (204 x 51) stride=370, color=6B02 [2000a7c4 FFFFFFFF->6B026B02]" two
159,"lv_draw_gd32_ipa_blend_fill: 20001542 (87 x 5) stride=370, color=45DD [200023b6 6B026B02->45DD6B02]" one
160,"lv_draw_gd32_ipa_blend_fill: 20001348 (248 x 51) stride=370, color=94A9 [2000a6b4 AE74AE74->94A994A9]" two
161,"lv_draw_gd32_ipa_blend_fill: 2000130c (73 x 51) stride=370, color=AE74 [2000a678 AE74AE74->AE74AE74]" two
162,"lv_draw_gd32_ipa_blend_fill: 2000a90c (370 x 51) stride=370, color=FFFF [20013c78 AE74AE74->FFFFFFFF]" two
163,"lv_draw_gd32_ipa_blend_fill: 2000a916 (365 x 51) stride=370, color=4227 [20013c82 AE74AE74->4227AE74]" one
164,"lv_draw_gd32_ipa_blend_fill: 2000aa58 (204 x 51) stride=370, color=6B02 [20013dc4 FFFFFFFF->6B026B02]" two
165,"lv_draw_gd32_ipa_blend_fill: 2000a948 (248 x 19) stride=370, color=94A9 [2000e034 42274227->94A994A9]" two
166,"lv_draw_gd32_ipa_blend_fill: 2000a90c (73 x 51) stride=370, color=AE74 [20013c78 AE74AE74->AE74AE74]" two
167,"lv_draw_gd32_ipa_blend_fill: 2000130c (370 x 7) stride=370, color=FFFF [20002748 AE74AE74->FFFFFFFF]" two
168,"lv_draw_gd32_ipa_blend_fill: 20001316 (365 x 7) stride=370, color=4227 [20002752 AE74AE74->4227AE74]" one
169,"lv_draw_gd32_ipa_blend_fill: 20001458 (204 x 7) stride=370, color=6B02 [20002894 94A994A9->6B026B02]" two
170,"lv_draw_gd32_ipa_blend_fill: 2000130c (73 x 7) stride=370, color=AE74 [20002748 AE74AE74->AE74AE74]" two
171,"lv_draw_gd32_ipa_blend_fill: 2000a90c (259 x 74) stride=259, color=FFFF [20013ec8 FFFFFFFF->FFFFFFFF]" two
172,"lv_draw_gd32_ipa_blend_fill: 2000130c (259 x 74) stride=259, color=FFFF [2000a8c8 FFFFFFFF->FFFFFFFF]" two
173,"lv_draw_gd32_ipa_blend_fill: 2000a90c (259 x 74) stride=259, color=FFFF [20013ec8 FFFFFFFF->FFFFFFFF]" two
174,"lv_draw_gd32_ipa_blend_fill: 2000130c (259 x 46) stride=259, color=FFFF [20007020 FFFFFFFF->FFFFFFFF]" two
175,"lv_draw_gd32_ipa_blend_fill: 2000a90c (259 x 74) stride=259, color=FFFF [20013ec8 FFFFFFFF->FFFFFFFF]" two
176,"lv_draw_gd32_ipa_blend_fill: 2000c1fe (169 x 62) stride=259, color=1163 [20013f72 00000000->11630000]" one
177,"lv_draw_gd32_ipa_blend_fill: 200103bc (47 x 30) stride=259, color=9DA6 [20014070 00000000->9DA69DA6]" two
178,"lv_draw_gd32_ipa_blend_fill: 2000b334 (175 x 69) stride=259, color=0907 [20013ed2 FFFFFFFF->0907FFFF]" one
179,"lv_draw_gd32_ipa_blend_fill: 2000130c (259 x 74) stride=259, color=FFFF [2000a8c8 FFFFFFFF->FFFFFFFF]" two
180,"lv_draw_gd32_ipa_blend_fill: 200013b6 (169 x 49) stride=259, color=1163 [200076dc FFFFFFFF->11631163]" two
181,"lv_draw_gd32_ipa_blend_fill: 200014b4 (47 x 74) stride=259, color=9DA6 [2000aa70 FFFFFFFF->9DA69DA6]" two
182,"lv_draw_gd32_ipa_blend_fill: 20001316 (175 x 74) stride=259, color=0907 [2000a8d2 FFFFFFFF->0907FFFF]" one
183,"lv_draw_gd32_ipa_blend_fill: 2000a90c (259 x 30) stride=259, color=FFFF [2000e5c0 FFFFFFFF->FFFFFFFF]" two
184,"lv_draw_gd32_ipa_blend_fill: 2000aab4 (47 x 30) stride=259, color=9DA6 [2000e768 11631163->9DA69DA6]" two
185,"lv_draw_gd32_ipa_blend_fill: 2000a916 (175 x 30) stride=259, color=0907 [2000e5ca 09070907->09070907]" two
186,"lv_draw_gd32_ipa_blend_fill: 2000130c (575 x 33) stride=575, color=FFFF [2000a74a 09070907->FFFF0907]" one
187,"lv_draw_gd32_ipa_blend_fill: 2000a90c (575 x 33) stride=575, color=FFFF [20013d4a 09070907->FFFF0907]" one
188,"lv_draw_gd32_ipa_blend_fill: 2000ca22 (365 x 26) stride=575, color=4227 [20013eee FFFFFFFF->4227FFFF]" one
189,"lv_draw_gd32_ipa_blend_fill: 20010ec6 (204 x 11) stride=575, color=6B02 [20014030 00000000->6B026B02]" two
190,"lv_draw_gd32_ipa_blend_fill: 2000130c (575 x 33) stride=575, color=FFFF [2000a74a 09070907->FFFF0907]" one
```

as you can see, sometimes fill is one, sometimes fill is two. Why? Most likely hardware is doing some optimization to do 32bit writes to the fill buffer. When the end_ptr is aligned on 32bit, the hardware fill will clobber 2 pixels. When not, it will only clobber one.

I added a test case like this:

```
    const bool unalign = (((uint32_t)end_ptr & 0x3) == 0);

    /*Work around hardware bug in IPA which clobbers 2 pixels after the fill*/
    backup[0] = end_ptr[0];
    if (unalign)
        backup[1] = end_ptr[1];

   // fill

    end_ptr[0] = backup[0];
    if (unalign)
        end_ptr[1] = backup[1];
```

And verified that with this additional logic, there are no crashes during entire lv_demo_benchmark.

I've cc'd GD people about this to hear confirmation, but at least this answers the question of "why" 1 or 2 pixels clobber.

**Comment by kisvegabor** [comment]
Amazing, thanks for the update. Let's wait what GD says. 

If we are confident about what's going on I'm ok with merging it because it can be a good startig point of further developments.

**Comment by trollcop** [comment]
Got an official confirmation from GD:

> Because our bus is accessed in a 32-bit manner, so when the address is not 32-bit aligned and DLOFF is not 0, this problem is highlighted.
>  Of course, it only exists in the GD32F450 series and it has been fixed on the GD32F470 series.
> Whether it is 16-bit, 24-bit or 32-bit [talking about pixel modes], saving and restoring end_ptr[0] and end_ptr[1] is the safest way. Because 450 will only have one more word of data at most, even if it is not 32-bit aligned, it is only one more word of data.
> The situation does have different combinations, but in the future we mainly recommend the chip whose this bug has been fixed, this problem will no longer exist in the future series.

Which seems to correlate with the data I've logged during fill operations.

**Comment by embeddedt** [comment]
In that case can the backup logic be wrapped in `#if defined(GD32F450)`, or are there prior chips to it which also have the issue?

**Comment by trollcop** [comment]
Hmm, that's a very good point. The peripheral in 450 and 470 is the same. Also, I guess I should add 470 support in this, at least with defines, and only include the fix when 450 is used.

**Comment by embeddedt** [comment]
One other issue came to mind. In a multithreaded system, the scheduler would need to be locked here, otherwise another thread’s memory could potentially be clobbered, right? If so, I don’t think we need to solve it but it should be documented somewhere.

**Comment by trollcop** [comment]
> One other issue came to mind. In a multithreaded system, the scheduler would need to be locked here, otherwise another thread’s memory could potentially be clobbered, right? If so, I don’t think we need to solve it but it should be documented somewhere.

Does LVGL provide some locking primitives? But yeah... maybe throw a warning in lv_conf that this isn't thread-safe on F450? Anyone who cares enough to use it will probably read it...

**Comment by embeddedt** [comment]
> Does LVGL provide some locking primitives?

Unfortunately, not at the moment, because they'd be platform and OS-specific.

>  But yeah... maybe throw a warning in lv_conf that this isn't thread-safe on F450?

Ok, a comment near the setting should be fine since it's disabled by default.

**Comment by GorgonMeducer** [comment]
When you add this GPU support, please also update the PDSC file in the `env_support/cmsis-pack` folder.
You can take other GPUs as an example.

**Comment by trollcop** [comment]
> When you add this GPU support, please also update the PDSC file in the `env_support/cmsis-pack` folder. You can take other GPUs as an example.

Sounds good, despite using keil I never did understand the purpose of their "pack" ecosystem, I prefer my projects to be standalone and always buildable anywhere with or without internet connection. Anyway the process looks a little complicated so maybe better you (as maintainer of that folder (?)) do it once this PR has been merged? If it ever will be that is.

**Comment by GorgonMeducer** [comment]
@trollcop OK, no problem.  By the way, when deploying any cmsis-packs to any project, the internet is NOT required.

**Comment by kisvegabor** [comment]
From my side we can merge it. Are there anything else still needs to be added/fixed?

**Comment by trollcop** [comment]
> From my side we can merge it. Are there anything else still needs to be added/fixed?

I would be interested in adding accelerated image copy routine (the one I commented earlier), but I would prefer to do that after this is merged and once I figure out how to actually use it.

**Comment by kisvegabor** [comment]
Okay! I agree to proceed in smaller steps.

**Comment by kisvegabor** [comment]
Oh, I almost forgot. @GorgonMeducer asked 
> When you add this GPU support, please also update the PDSC file in the env_support/cmsis-pack folder.

Could you handle it?

**Comment by GorgonMeducer** [comment]
If you can merge it now, then this PR can be integrated into the cmsis-pack of Sept monthly update.

**Comment by kisvegabor** [comment]
I can merge it now if you update the PDSC file or we can wait for @trollcop's response.

**Comment by trollcop** [comment]
I already said I'd prefer the original maintainer to update the pack as the
process seems a bit involved

**Comment by GorgonMeducer** [comment]
@kisvegabor please merge this PR so that I can update the PDSC now

**Comment by kisvegabor** [comment]
@trollcop sorry, I missed that.

Merging now.

**Comment by GorgonMeducer** [comment]
@trollcop  Just for your information, the PDSC update work is very simple:

image

https://github.com/lvgl/lvgl/pull/3718/files#diff-2f293708b4de91b61eb41cae5ffbdebec7e49d51a576aa6ed083e73ef0d2e431

That's all, nothing special. That's why I said you could do it by taking other GPUs as a reference. 

It takes me only 5mins. But anyway, I did it for you.

image

**Pull request merged**
