### PR TITLE
fix(imagebutton): clipped area of mid part

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

Discovered while debugging issue #5803
Related to PR #5719

#### Before
image

#### After
image

When a sub clip of the mid part of the imagebutton is redrawn it draws it with respect to the top-left-corner because the clip coords are passed to `lv_draw_image` instead of the image part coords. Can be reproduced with `lv_example_imagebutton_1` and the play/pause button of `lv_demo_music` by moving something off of the mid part, such as a mouse cursor image.

Also, I'm not sure why, but the first draw of the mid part is also wrong too on my simulator only when I use `COLOR_DEPTH` 24 or 32, but fine for 16:
image
(fixed by these changes)
Edit: this was because of partial render mode

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by W-Mai — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
Looks good, thank you for the fix!

**Comment by kisvegabor** [comment]
Hm, [something](https://github.com/lvgl/lvgl/actions/runs/8256196428/job/22604656631?pr=5849) is not okay with the tests. I don't it's related though.

**Comment by W-Mai** [comment]
It's weird. The log is missing.

**Comment by kisvegabor** [comment]
It seems it's stuck an infinite loop somewhere. Works well locally.

Running the CI again, maybe just a temporal issue.

**Comment by kisvegabor** [comment]
Yep, temporal issue. All passed now.

**Review by PGNetHun — APPROVED** [review]

**Pull request merged**
