### PR TITLE
feat(docs):  plea for proper word-wrapping in `.rst` files.

### PR DESCRIPTION
**Pull request by vwheeler63**
While with `.md` files, it is important to allow paragraphs to flow off to the right with one long line so that when they are formatted as `.html` files, the paragraphs will word-wrap with the width of the browser, this is not true with reStructuredText (`.rst` files).  [Sphinx](https://www.sphinx-doc.org/en/master/) and its underlying [docutils parsing engine](https://docutils.sourceforge.io/docs/) conveniently combine grouped text into a proper paragraph with that word-wrapping behavior.  This allows the source text documents to be nicely word-wrapped so that they are more readable in text- and code-editors that do not have wide editing windows.  So please accept my plea that this is the normal practice for LVGL docs:  wrap the text around column 86.  Wrapping at *exactly* column 86 is not important, but readability and ease of editing is.

cc:  @kisvegabor @FASTSHIFT @liamHowatt @faxe1008 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.  Done.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.  n/a
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.  n/a
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).  n/a
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).  n/a
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.  Done.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — DISMISSED** [review]
I'm ok with that.

**Comment by vwheeler63** [comment]
> I'm ok with that.

Sorry I invalidated your approval:  I added one small modification before I realized you had given your approval.

**Review by kisvegabor — DISMISSED** [review]

**Comment by vwheeler63** [comment]
@kisvegabor , in re-reviewing this today I realized that `./docs/details/main-components/display.rst` has been edited since this was originally submitted, and the author (Fabian Blatz) added a helpful line at the end of the paragraph the starts on line 491 "The :cpp:func:`lv_draw_sw_i1_convert_to_vtiled` function is used...".  And if we merged this, it would delete the helpful information he added.  So I went to this branch and added that line back in so my changes to that paragraph would not overwrite his changes (preserving the information he added).  The info he added is:  "For more details, refer to the
implementation in :cpp:func:`lv_draw_sw_i1_convert_to_vtiled` in :file:`src/draw/sw/lv_draw_sw.c`."

Unfortunately, that meant I needed to do another commit, which will (once again) invalidate your approval.  Sorry about that.

**Review by kisvegabor — APPROVED** [review]
:+1:

**Review by liamHowatt — APPROVED** [review]
Nice!

**Pull request merged**
