### PR TITLE
Add ability to enable/disable borders on table

### PR DESCRIPTION
**Pull request by embeddedt**
@kisvegabor 

I've tested this on the PC simulator.

It also has the effect of removing the table's background. If that's undesirable, I'll figure out how to change that.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Have you tried to adjust `LV_STYLE_TABLE_CELL` to remove cell borders?

**Comment by embeddedt** [comment]
@kisvegabor Oops... I didn't realize that the cells were styled that way. :disappointed: 

Still, I think it would be ideal to have the ability to turn it on and off for all of the cells at once. The way it has been described it looks like a user would potentially have to change 4 different styles to be able to uniformly disable backgrounds on the table. Or perhaps I'm missing something. What do you think?

**Comment by kisvegabor** [comment]
By default, all cells have "TYPE 1" so you only need to modify `LV_TABLE_STYLE_CELL1`. I think it's still an acceptable burden and the rest of the library works this way too. 

If we added this function, we could find other object types where "style overwriting" object parameters could be used. So I think we should add this only for tables.

I'm thinking about a general, local style change solution for a long time but didn't find a good way yet. Its goal would be to easily (with few lines of code) override basic attributes like colors. Similarly then in HTML: 
- classes are like `lv_style`
- and element styles can overwrite class settings locally.

Do you think some improvements in the regard would be useful?

**Comment by embeddedt** [comment]
@kisvegabor I like the idea, but we should find a way to make it as simple for the user as possible. I don't think that we should introduce another variant of `lv_style_t` though.

**Comment by kisvegabor** [comment]
> I like the idea, but we should find a way to make it as simple for the user as possible. I don't think that we should introduce another variant of lv_style_t though.

I agree. I think we have plenty of new features for v6.0 and we should deal with it later. What do you think?

**Comment by embeddedt** [comment]
@kisvegabor Since it's a backwards compatible change, I think it's fine to save it for the next minor release. I'll close this pull request.

**Pull request closed without merging**
