### PR TITLE
feat(fbdev): Allow forcing refresh

### PR DESCRIPTION
**Pull request by Johennes**
### Description of the feature or fix

A clear and concise description of what the bug or new feature is. This feature exists in the old fbdev driver in lv_drivers.

### Notes

- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html)
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
What the problem does it resolves? Tearing?

**Comment by Johennes** [comment]
Sorry, I was mistaken. This didn't exist in lv_drivers upstream. We had only made the change on our fork. The issue that spawned this is https://gitlab.com/cherrypicker/unl0kr/-/issues/34. On some devices the screen would stay black or only render the area that had changed. The problem doesn't occur anymore when using direct rendering together with the force refresh feature from this PR.

**Comment by kisvegabor** [comment]
I see, thank you! Would it make sense to enable it by default?

**Comment by Johennes** [comment]
No, I wouldn't recommend that actually. When I enable this on my laptop, it's causing a noticeable performance impact. It's not negatively noticeable on the device affected by the issue. But I'd definitely only turn it on when needed. In our app we've just made it a config setting.

**Comment by kisvegabor** [comment]
All clear, thank you. Final question: would you be interested in adding docs for the frame buffer device driver? Similar to [this](https://docs.lvgl.io/master/integration/driver/X11.html).

**Comment by Johennes** [comment]
Good idea. I've added some rudimentary docs.

**Comment by kisvegabor** [comment]
It was quick! Thank you! :slightly_smiling_face:

**Review by kisvegabor — APPROVED** [review]

**Pull request merged**
