### PR TITLE
fix(scale): correct scale_set_arc_properties function

### PR DESCRIPTION
**Pull request by lizhaoming634**
A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — DISMISSED** [review]
Oh, it's such and important bug fix that it's breaking change in case of some UIs. Anyway, I think we should merge it.

**Review by liamHowatt — COMMENTED** [review]
Just wondering if it's worth adding `LV_STYLE_ARC_IMAGE_SRC` too, or not. What are your thoughts?

**Comment by kisvegabor** [comment]
> Just wondering if it's worth adding LV_STYLE_ARC_IMAGE_SRC too, or not. What are your thoughts?

Good idea, I see no reason to skip it.

**Comment by lizhaoming634** [comment]
I may have done something wrong, how should I solve this problem? I synchronized the master and branch of my fork.

**Comment by lizhaoming634** [comment]
I hope I didn't mess it up

**Review by YobieZhou — APPROVED** [review]

**Review by kissa96 — APPROVED** [review]

**Review by liamHowatt — APPROVED** [review]
Thanks!

**Review by kisvegabor — APPROVED** [review]
Nice, thank you!

**Pull request merged**
