### PR TITLE
Button matrix hidden buttons

### PR DESCRIPTION
**Pull request by patricklaf**
Update button matrix to really hide buttons with LV_BTNM_CTRL_HIDDEN control parameter.

### CODE REVIEW

**Comment by embeddedt** [comment]
I think the current behavior is intentional. It allows you to put space between buttons by using an invisible one.

**Comment by patricklaf** [comment]
It could be interesting to have something like LV_BTNM_CTRL_SPACE instead.
In facts I need to change the text of a button at runtime, RECORD or PLAY, and without changing the whole map it is not possible. I tried this way to have two buttons defined, one hidden and one visible at a time.

**Comment by patricklaf** [comment]
It causes problem BTW. I need to change get_button_from_point this way to get the real id:
```cpp
    for(i = 0; i < ext->btn_cnt; i++) {
        if (!button_is_hidden(ext->ctrl_bits[i])) {
            lv_area_copy(&btn_area, &ext->button_areas[i]);
            btn_area.x1 += btnm_cords.x1;
            btn_area.y1 += btnm_cords.y1;
            btn_area.x2 += btnm_cords.x1;
            btn_area.y2 += btnm_cords.y1;
            if(lv_area_is_point_on(&btn_area, p) != false) {
                break;
            }
        }
    }
```

**Comment by embeddedt** [comment]
>  I need to change the text of a button at runtime

Why doesn't it work if you just change the string with `RECORD` to `PLAY`?

```c
const char *btnm_map[] = { "btn1", "btn2", "btn3", "RECORD", "" };
lv_btnm_set_map(btnm, btnm_map);
/* ... later */
btnm_map[3] = "PLAY";
lv_btnm_set_map(btnm, btnm_map);
```

**Comment by patricklaf** [comment]
> Why doesn't it work if you just change the string with `RECORD` to `PLAY`?

Because at first, I thought it was not optimal to set the whole map again.
After studying the internals of the button matrix, I see that every time one modify the maps, buttons or controls, all is reprocessed.
So, it is possible to implement simply what I propose, LV_BTNM_CTRL_HIDDEN to hide button and LV_BTNM_CTRL_SPACE to insert space between buttons.
Not really needed for my goal but maybe useful for others.

**Comment by kisvegabor** [comment]
The button matrix really reprocessed everything on `lv_btnm_set_map` but I think it's not a problem because it happens very rarely and the reprocessing doesn't take too much time.

Hiding buttons - as you suggest - also would require some reprocessing because the size of the other buttons in line would change.

**Comment by patricklaf** [comment]
> Hiding buttons - as you suggest - also would require some reprocessing because the size of the other buttons in line would change.

Yes. And now that I know the difference between `const char*` and `const char* const` I will revert my changes .
If there is nothing to add, I will close this PR soon.
Thanks @embeddedt and @kisvegabor for your comments.

**Comment by kisvegabor** [comment]
@patricklaf 
I think we can close this PR.
Thank you for the idea anyway!

**Pull request closed without merging**
