### PR TITLE
chore(text): move "_" funcs to private h

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

In response to #5899.

Part of the gradual transition to having private header files instead of `_` functions.

- First commit:
  - Move private `_` text functions to private header.
  - Include the private header in source files that depend on the private functions.
  - Make `extern` text function pointers `const`.
- Second commit (do we want this, @kisvegabor?):
  - Bulk rename private functions. Remove the leading `_`s.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by XuNeo** [comment]
Let's add the old APIs started with `_` to api_map.h too in case if anyone actually has used them.

**Comment by liamHowatt** [comment]
I had to include the private header in the api map, which is included by lvgl.h so the private header is ultimately included everywhere lvgl.h is but at least the intent is clear. 🙂️

**Comment by XuNeo** [comment]
Emmm, I think what @sparkles43 wants is to make `lv_text_` public, we may add those directly to `lv_txt.h`?

**Comment by kisvegabor** [comment]
I think it's important to have only the really essential API function included from `lvgl.h`. LVGL's API is already very large.

Therefore I suggest this:
- Bulk rename `_lv_text` to `lv_text`
- Do not add API mapping as the `_lv` function weren't part of the public API so far either
- If anyone needs to use the `lv_text_*` functions they can include `lv_text_private.h` in their code.

What do you think?

**Comment by XuNeo** [comment]
I think functions in `private.h` should never be used in user application, and that's most developer would/should follow.

For the lv_text case, the static `lv_text_utf8_` APIs can be moved to a public place like utils/lv_utf8.h and make it public since it doesn't depend on other modules. And there's a real need for it now.

**Comment by sparkles43** [comment]
> I think functions in private.h should never be used in user application, and that's most developer would/should follow.

I agree with @XuNeo. This is basically why I opened my issue about lv_text.

> - Bulk rename _lv_text to lv_text
> - Do not add API mapping as the _lv function weren't part of the public API so far either

I think the remaining points - @kisvegabor made - make good sense.

> For the lv_text case, the static lv_text_utf8_ APIs can be moved to a public place like utils/lv_utf8.h and make it public since it doesn't depend on other modules. And there's a real need for it now.

- Until now I thought of the internal switching as an advantage. But of course the user could do checks on his/her own to guarantee UTF-8 is used.
- If we moved the UTF8 implementation to a separate file `utils/lv_utf8.h` that would make the private text processing `lv_text.h` depend on a public API which would make changes to the private API portion harder (e.g. format change away from `uint32_t` for UTF-8 characters would require an adapter in the `lv_text.c`)
  - I guess we would move the complexity of the API to a lower level in that case `utils/lv_utf8.h`, `utils/lv_ascii.h`

I am not strictly against the proposal but in this case we should take a look at which variant implies what maintenance efforts. Additionally we should think about the likelihood of changes to the API 🤔

**Comment by kisvegabor** [comment]
Keeping the API smaller is very important. Ideally only the real core features (widgets, events, animation, styles, etc) should be public.

> I think functions in private.h should never be used in user application, and that's most developer would/should follow.

Normally it really shouldn't be used by the users, however if they want to use it for any reason they can do that. in general `private.h` files can be used by the developers e.g. if they are adding a new widget, or something similar. So I would phrase it like "Private headers shall be used only by the advanced users for advanced things".

> I am not strictly against the proposal but in this case we should take a look at which variant implies what maintenance efforts. Additionally we should think about the likelihood of changes to the API 🤔

At some point probably we will rework the whole typesetting interface, so these functions will be completely rewritten too. In light of that the more we hide is better.

**Review by kisvegabor — DISMISSED** [review]

**Review by XuNeo — DISMISSED** [review]

**Comment by liamHowatt** [comment]
Should new private headers go in here?
https://github.com/liamHowatt/lvgl/blob/6127a82713485a26f7fb68e0dfe2d3e9ac639c41/src/lvgl_private.h

**Comment by kisvegabor** [comment]
> Should new private headers go in here?
 
Ah, yes! The purpose of `lv_private.h` is to have a simple way to easily include the whole LVGL API like this:
```c
#include "lvgl.h"
#include "lv_private.h"
```

**Comment by liamHowatt** [comment]
FYI here are all the *_private.h headers I could find in `master`.

```
./src/libs/freetype/lv_freetype_private.h
./src/indev/lv_indev_private.h ✅️
./src/display/lv_display_private.h ✅️
./src/misc/cache/lv_cache_entry_private.h
./src/misc/cache/lv_cache_private.h
```

**Review by XuNeo — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]

**Pull request merged**
