### PR TITLE
fix(btnmatrix): Take border sides into account

### LINKED ISSUE #3721: lv_obj_set_content_width & lv_obj_set_content_height don't take border side into account
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

I haven't spent time reproducing this in a simulator but I'm fairly certain that I see the issue in the source code.

### Describe the bug

The functions [`lv_obj_set_content_width`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_obj_pos.c#L249) and [`lv_obj_set_content_height`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_obj_pos.c#L258) subtract the border width from the object width but they don't check which border sides are hidden. As a result, when only the top border is active, the border width will erroneously be subtracted twice.

### To Reproduce

I spotted this in a keyboard widget, styled with

```
lv_style_set_border_side(&(styles.keyboard), LV_BORDER_SIDE_TOP);
lv_style_set_border_width(&(styles.keyboard), lv_dpx(theme->keyboard.border_width));
```
The button matrix inside the keyboard leaves empty space on the right and bottom side because the available width and height were calculated too low due to the border width subtractions.

### Expected behavior

The border width should only be subtracted when the respective border side is active, e.g.

```
lv_coord_t lv_obj_get_content_width(const lv_obj_t * obj)
{
    LV_ASSERT_OBJ(obj, MY_CLASS);

    lv_coord_t left = lv_obj_get_style_pad_left(obj, LV_PART_MAIN);
    lv_coord_t right = lv_obj_get_style_pad_right(obj, LV_PART_MAIN);
    lv_coord_t border_width = lv_obj_get_style_border_width(obj, LV_PART_MAIN);

    lv_border_side_t border_side = lv_obj_get_style_border_side(obj, LV_PART_MAIN);

    lv_coord_t width = lv_obj_get_width(obj) - left - right;
    
    if (border_side & LV_BORDER_SIDE_LEFT) {
        width -= border_width;
    }
    if (border_side & LV_BORDER_SIDE_RIGHT) {
        width -= border_width;
    }

    return width;
}
```

### Screenshots or video

pmos-light-800x480

### LINKED ISSUE #3722: btnmatrix doesn't take border width into account when calculating button positions
### Perform all steps below and tick them with [x]
- [x] Read the [FAQ](https://docs.lvgl.io/master/intro/index.html#faq)
- [x] Check the related part of the [Documentation](https://docs.lvgl.io/)
- [x] Update lvgl to the latest version
- [ ] Reproduce the issue in a [Simulator](https://docs.lvgl.io/latest/en/html/get-started/pc-simulator.html)

I haven't spent time reproducing this in a simulator but I'm fairly certain that I see the issue in the source code.

### Describe the bug

When computing the button positions, the button matrix only takes the [top](https://github.com/lvgl/lvgl/blob/master/src/widgets/btnmatrix/lv_btnmatrix.c#L141) and [left](https://github.com/lvgl/lvgl/blob/master/src/widgets/btnmatrix/lv_btnmatrix.c#L166) padding into account but not the top and left border. As a result, when there is e.g. a top border, the buttons will draw over the border.

### To Reproduce

I noticed this when investigating #3721.

### Expected behavior

The border side and width should be evaluated e.g. via

```
lv_coord_t border_width = lv_obj_get_style_border_width(obj, LV_PART_MAIN);
lv_border_side_t border_side = lv_obj_get_style_border_side(obj, LV_PART_MAIN);
lv_coord_t border_top = border_side & LV_BORDER_SIDE_TOP ? border_width : 0;
lv_coord_t border_left = border_side & LV_BORDER_SIDE_LEFT ? border_width : 0;
```

and then be added to `ptop` and `pleft`.

### Screenshots or video

The effect can be seen in the screenshot on #3721.

### PR DESCRIPTION
**Pull request by Johennes**
### Description of the feature or fix

This adds / removes the border width for the sides where the border is actually active when computing content sizes and offsets the button positions by the border width on the sides where the border is active.

I had to update the screenshots used in the tests but I think they are actually correct now. The old btnm_1.png had 18px from the left edge to button A and 20px from button B to the right edge. The new one has 20px on both sides.

Fixes: #3721
Fixes: #3722

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
I think in the end we need additional functions too. E.g. `lv_obj_get_style_space_left` which combines padding and border on the respective side. And these functions needs to be used in `lv_btnmatrix` here:
https://github.com/lvgl/lvgl/blob/e40a82a1b75ba39f8774589144eb701793a47dea/src/widgets/btnmatrix/lv_btnmatrix.c#L107-L108

Without it the position of the buttons will be still shifted. What do you think?

**Comment by kisvegabor** [comment]
I just saw in #3726 that you also noticed that issue.  As getting padding+border is quite common I suggest adding 4 dedicated functions for it [here](https://github.com/lvgl/lvgl/blob/master/src/core/lv_obj_style.h#L234).

**Comment by Johennes** [comment]
Yes, good point. I'll look into that. :+1:

**Comment by Johennes** [comment]
@kisvegabor I have extracted the utility functions now. I also merged #3726 into this PR so that it's easier to test.

**Comment by kisvegabor** [comment]
Perfect! Thank you very much!

I think we can use these new functions in many other places but we can update those places gradually as we find them.

**Pull request merged**
