### PR TITLE
Add binding for PikaScript.

### PR DESCRIPTION
**Pull request by pikasTech**
### Description of the feature or fix

Add binding for PikaScript.

[PikaScript](https://github.com/pikasTech/pikascript) is an ultralightweight python engine that can run with 4KB of RAM and 32KB of Flash (such as STM32G030C8 and STM32F103C8), and is very easy to deploy and expand.

More details to see: [PikaScript and lvgl: Make Python Lighter, Easier and Smarter](https://blog.lvgl.io/2022-08-24/pikascript-and-lvgl)

The available Python APIs are in the `pika_lvgl.pyi`, and you need copy the `pika_lvgl.pyi` to the root path of pikascript, then `import pika_lvgl` in `main.py`.

The available simulation project on windows:  https://github.com/pikasTech/lv_pikascript

More document about PikaScript: https://pikadoc.readthedocs.io/en/latest/index.html

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
Can you add an `#ifdef PIKASCRIPT` or similar guard to C files to be sure they won't be pick up by Eclipse or other IDE?

**Comment by embeddedt** [comment]
@pikasTech Do you plan to make a Linux simulator project available at some point? If/when you do, I can add another CI action on our end to verify that building this binding still works.

**Comment by kisvegabor** [comment]
I'd be also curious about a Linux simulator :slightly_smiling_face:

**Comment by pikasTech** [comment]
> @pikasTech Do you plan to make a Linux simulator project available at some point? If/when you do, I can add another CI action on our end to verify that building this binding still works.

I will try for that, thanks!

**Comment by pikasTech** [comment]
> @pikasTech Do you plan to make a Linux simulator project available at some point? If/when you do, I can add another CI action on our end to verify that building this binding still works.

@embeddedt 
Now the Linux simulator project is available at: 
https://github.com/pikasTech/lv_port_pc_vscode_pikascript

**Comment by embeddedt** [comment]
@pikasTech Thanks! Is it possible to use submodules instead of copying the LVGL source into the tree directly? This is necessary for the CI action to select the right LVGL commit at checkout time.

**Comment by pikasTech** [comment]
> @pikasTech Thanks! Is it possible to use submodules instead of copying the LVGL source into the tree directly? This is necessary for the CI action to select the right LVGL commit at checkout time.

Okay, now the LVGL is a submodule in this repo.

**Comment by pikasTech** [comment]
@kisvegabor 
Maybe I can move the lv_pikascript repository to the lvgl organization? That way users can find it at https://github.com/lvgl/lv_pikascript, which might help more to increase the activity of the community.
What do you think about this option? Do you think this is appropriate?
🙂

**Comment by kisvegabor** [comment]
I'm absolutely open to it. Usually I offer it to people how create something great but I thought you'd prefer hosting it in PikaScript's organisation. 

So please add me as admin to the repo and I'll transfer it here.

Thank you very much! :relaxed:

**Comment by pikasTech** [comment]
> I'm absolutely open to it. Usually I offer it to people how create something great but I thought you'd prefer hosting it in PikaScript's organisation.
> 
> So please add me as admin to the repo and I'll transfer it here.
> 
> Thank you very much! ☺️

I'm investing you in the https://github.com/pikascript-demo organization as the owner, I'm not sure if it works. If need any help, just @me ☺️

**Comment by kisvegabor** [comment]
I've just transferred the repo here: https://github.com/lvgl/lv_binding_pikascript

What could be the nest step? :slightly_smiling_face:

**Comment by pikasTech** [comment]
> I've just transferred the repo here: https://github.com/lvgl/lv_binding_pikascript
> 
> What could be the nest step? 🙂

I will continue to maintain this repository and then add more lvgl api's as well as make sure the kernel for pikascript is relatively new.

**Comment by kisvegabor** [comment]
Sounds great! Thank you very much!

**Pull request merged**
