### PR TITLE
fix(cmake): fix installation with cmake --install

### PR DESCRIPTION
**Pull request by etag4048**
fixes issue #6787 #6478

The ``DESTINATION`` arg of the ``install`` directives located in ``env_support/cmake/custom.cmake`` being hardcoded to the default value of ``CMAKE_INSTALL_PREFIX`` resulted in a broken ``cmake_install.cmake`` file

If the user wants to use cmake to install lvgl headers and libraries to a custom location it can be done
at installation time with the following command ``cmake --install build_dir --prefix /usr/custom/``

Please note that currently ``lvgl.pc`` is not generated properly when ``--prefix`` is used.
There is an entire discussion on this subject in the cmake forums, the workaround is to set CMAKE_INSTALL_PREFIX at configuration time using the ``-D`` argument

https://discourse.cmake.org/t/how-to-generate-pc-pkg-config-file-supporting-prefix-of-the-cmake-install/4109

### CODE REVIEW

**Comment by kisvegabor** [comment]
#7127 is merged. Is it ready to merge too?

**Comment by etag4048** [comment]
@kisvegabor I will attempt to add the missing commit before the Thursday evening, now busy with other things.

**Comment by kisvegabor** [comment]
Let us know when it's ready to review.

**Comment by etag4048** [comment]
@kisvegabor Ready.

**Review by kisvegabor — APPROVED** [review]
It's hard to tell for me if it's really better this way, but I trust your expertise :slightly_smiling_face:

**Comment by etag4048** [comment]
@kisvegabor It works with or without specifying a prefix, I've also removed the paths that are destined for executables. Since lvgl is a library, not an executable.

**Review by liamHowatt — APPROVED** [review]

**Pull request merged**
