### PR TITLE
Update lv_color.h

### PR DESCRIPTION
**Pull request by ali-rostami**
fix a compile error.

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by ali-rostami** [comment]
can't understand the reason for the problem. any idea?

**Comment by kisvegabor** [comment]
Applying the modification I see this warning locally too.

In #2311 you mentioned that you see `"expected expression before { token"` GCC warning. Let's try to figure out why you see this warning with the original code and others don't.  

Do you see the original error without your project code, only using LVGL and creating a button or so.

**Comment by ali-rostami** [comment]
Oops, found it.
The problem was for lv_lib_png, and after I updated it to the latest changes, the problem solved.
So I will remove the PR.
thanks.

**Comment by kisvegabor** [comment]
So is there a bug in `lv_lib_png`?

**Comment by ali-rostami** [comment]
> So is there a bug in `lv_lib_png`?

No It's O.K. You have fixed it [here](https://github.com/lvgl/lv_lib_png/commit/f932791e14b28565af976ec7850955113c8e6ba7).

**Comment by kisvegabor** [comment]
Ah, great! :slightly_smiling_face:

**Comment by andrewrt** [comment]
I'm seeing this error in lvgl 8.0.2 -not sure how this https://github.com/lvgl/lv_lib_png/commit/f932791e14b28565af976ec7850955113c8e6ba7 fixes the bug - it goes from using LV_COLOR_MAKE to lv_color_make. 

Doesn't that mean the original problem in LV_COLOR_MAKE -> LV_COLOR_MAKE16 still exists or am I missing something?

**Comment by kisvegabor** [comment]
@andrewrt 
lv_color_make is implement like this:
```c
static inline lv_color_t lv_color_make(uint8_t r, uint8_t g, uint8_t b)
{
    return _LV_COLOR_MAKE_TYPE_HELPER LV_COLOR_MAKE(r, g, b);
}
```

`_LV_COLOR_MAKE_TYPE_HELPER` should make it compiler friendly. 


Exactly what error do you see? Do you see it with the master branch of lvgl too?

**Comment by andrewrt** [comment]
@kisvegabor , 
I'm seeing the same error as seen in https://github.com/lvgl/lvgl/issues/2311  :
Screen Shot 2021-10-04 at 2 43 42 PM
 
I did the same work around as @ali-rostami did there in order to avoid the error, update to:
```c
#define LV_COLOR_MAKE16(r8, g8, b8) (_LV_COLOR_MAKE_TYPE_HELPER{{(uint8_t)((b8 >> 3) & 0x1FU), (uint8_t)((g8 >> 2) & 0x3FU), (uint8_t)((r8 >> 3) & 0x1FU)}})
```

I am calling LV_COLOR_MAKE in other preprocessor defs - so this may be a hint about the problem, eg:
```c
#define CUSTOM_COLOR_BLUE  		(LV_COLOR_MAKE(0x08, 0x77, 0xFB))
```
etc etc.

And this is using the v8.0.2 tag in github from lvgl. 
I'm currently in the middle of porting hell from 7.x to 8.x, so figured i'd go with latest stable official release as I sort out my own problems.  Once I have my UI working again, I can try bleeding edge master head

**Comment by kisvegabor** [comment]
Does this work?
```
#define CUSTOM_COLOR_BLUE  		(lv_color_make(0x08, 0x77, 0xFB))
```

Or
```c
#define CUSTOM_COLOR_BLUE  		(lv_color_hex(0x0877FB))
```

**Comment by andrewrt** [comment]
I've finished the migration from lvgl7 to lvgl8 now. 
Tested 
```c
#define CUSTOM_COLOR_BLUE  		(lv_color_make(0x08, 0x77, 0xFB))
```
and it seems to work after reverting lv_color.h to
```c
//#define LV_COLOR_MAKE16(r8, g8, b8) (_LV_COLOR_MAKE_TYPE_HELPER{{(uint8_t)((b8 >> 3) & 0x1FU), (uint8_t)((g8 >> 2) & 0x3FU), (uint8_t)((r8 >> 3) & 0x1FU)}})
# define LV_COLOR_MAKE16(r8, g8, b8) {{(uint8_t)((b8 >> 3) & 0x1FU), (uint8_t)((g8 >> 2) & 0x3FU), (uint8_t)((r8 >> 3) & 0x1FU)}}
```

Would this mean that LV_COLOR_MAKE should not be callable from preprocessor defines directly? Seems to be the case...

**Comment by kisvegabor** [comment]
> Would this mean that LV_COLOR_MAKE should not be callable from preprocessor defines directly? Seems to be the case...

Yes, it shouldn't. `lv_color_make()` should be used instead.

**Pull request closed without merging**
