### PR TITLE
fix(disp): need save the new driver pointer in lv_disp_drv_update

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

Minor fix.

### Checkpoints
- [ ] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by embeddedt** [comment]
Is there any possibility of this function being called within an event handler, etc.? If so, the driver reference inside the display will change, but if there's any rendering functions holding a reference to the old one, they will keep using that.

IMO we shouldn't allow changing the pointer after registration.

**Comment by kisvegabor** [comment]
> Is there any possibility of this function being called within an event handler, etc.? If so, the driver reference inside the display will change, but if there's any rendering functions holding a reference to the old one, they will keep using that.


Reconfiguring the driver in the middle of the drawing process doesn't sound lifelike to me. Can you mention a real life example when it can happen or is it just a theoretical issue?

**Comment by embeddedt** [comment]
What happens if `lv_disp_set_rotation` is called from a dropdown's `VALUE_CHANGED` handler? I could be wrong but I think `lv_disp_drv_update` ends up getting called.

EDIT: I just realized that that is an event handler, not a drawing handler. Does anything for events keep a reference to the display driver?

**Comment by kisvegabor** [comment]
> What happens if lv_disp_set_rotation is called from a dropdown's VALUE_CHANGED handler? I could be wrong but I think lv_disp_drv_update ends up getting called.

I think the only issue that can happen in this case is the already invalidated areas become "invalid" after the rotation. However, the rotation invalidates the whole screen anyway. 

> I just realized that that is an event handler, not a drawing handler. Does anything for events keep a reference to the display driver?

No, they don't. However, in v8 there are events that are used to hook the drawing. E.g. to modify the cells of a table one-by-one. I'm not sure what happens if you update the driver in one of these events but I doubt that it has a reasonable purpose.

**Comment by embeddedt** [comment]
Okay; it doesn't sound like it will be a problem in practice. Let's merge it.

**Comment by kisvegabor** [comment]
Added manually here: 4a0dbffc

**Pull request closed without merging**
