### PR TITLE
feat(docs): add Chinese translation (jump link)

### PR DESCRIPTION
**Pull request by 100ask**
# Preview

image

**out_html**: [http://photos.100ask.net/lvgl/out_html.7z](http://photos.100ask.net/lvgl/out_html.7z)

### CODE REVIEW

**Comment by XuNeo** [comment]
Hi,
Are those changes to the PNG files necessary? I'm not familiar with building the doc, could you enlighten me how to custom the actual link `link_to_translation` uses?

**Comment by 100ask** [comment]
> Are those changes to the PNG files necessary?

Oh, this is my bad.
Actually, I did not make any changes to the PNG file. This was caused by transferring between multiple platforms. 
If necessary, I will resubmit after your review. @kisvegabor

**Comment by 100ask** [comment]
> how to custom the actual link `link_to_translation` uses?

reference: 

- [https://www.sphinx-doc.org/zh-cn/master/extdev/index.html](https://www.sphinx-doc.org/zh-cn/master/extdev/index.html)
- [http://protips.readthedocs.io/link-roles.html](http://protips.readthedocs.io/link-roles.html)

**Comment by kisvegabor** [comment]
Hi,

Thank you! The changes look good to me, but I wonder what the proper order of actions is. I think:
1. Make the Chinese version public
2. Update this PR to point to the published docs
3. Merge this PR

Just out of curiosity, how fast are the the docs.lvgl.io and lvgl.io web pages in China? Just slow, or painfully slow?

**Comment by kisvegabor** [comment]
By the way, does the interactive examples also work in the translated docs?

**Comment by 100ask** [comment]
> Thank you! The changes look good to me, but I wonder what the proper order of actions is. I think:
> 
> 1. Make the Chinese version public
> 2. Update this PR to point to the published [docs](https://lvgl.100ask.net/master/)
> 3. Merge this PR

1. [√Ready] Make the Chinese version public: [https://lvgl.100ask.net/master](https://lvgl.100ask.net/master) and [https://github.com/100askTeam/100ask_lvgl_docs](https://github.com/100askTeam/100ask_lvgl_docs)
2.  [√Ready] Update this PR to point to the published docs: [https://github.com/lvgl/lvgl/pull/5750/files#diff-c0c4cb5906308d1f7c5556f9315fb33cbb518c28892fb3bcacfcb6973b1685f5R40](https://github.com/lvgl/lvgl/pull/5750/files#diff-c0c4cb5906308d1f7c5556f9315fb33cbb518c28892fb3bcacfcb6973b1685f5R40)
image

3. [×Waiting for merge] Merge this PR

**Comment by 100ask** [comment]
> Just out of curiosity, how fast are the the docs.lvgl.io and lvgl.io web pages in China? Just slow, or painfully slow?

For the vast majority of people without special networks,  docs.lvgl.io is slow and painful.

**Comment by 100ask** [comment]
> By the way, does the interactive examples also work in the translated docs?

Of course, lvgl.100ask.net has the same reading effect as docs.lvgl.io.

**Comment by kisvegabor** [comment]
Great! 

So now we have the Chinese translation at  [https://lvgl.100ask.net](https://lvgl.100ask.net/master/examples.html) but it's slow in China. How will we make it fast in China. Will you mirror it somewhere? If so I think we needed to add the fast URL in the links of the English docs.

**Comment by YobeZhou** [comment]
> Great!
> 
> So now we have the Chinese translation at [https://lvgl.100ask.net](https://lvgl.100ask.net/master/examples.html) but it's slow in China. How will we make it fast in China. Will you mirror it somewhere? If so I think we needed to add the fast URL in the links of the English docs.

https://lvgl.100ask.net very fast in China because it hosts servers within China instead of GitHub pages.

**Comment by 100ask** [comment]
> but it's slow in China. How will we make it fast in China.

`docs.lvgl.io` slow and painful(unstable) in China because  it hosts on GitHub Pages.

> Will you mirror it somewhere?

This has been achieved.

`https://lvgl.100ask.net` very fast in China because it hosts servers within China instead of GitHub pages.

**Review by kisvegabor — DISMISSED** [review]
All clear,  thank you!

**Comment by 100ask** [comment]
> Are those changes to the PNG files necessary?

@XuNeo Hi, 
Do I need to make changes?
Actually, I did not make any changes to the PNG file. This was caused by transferring between multiple platforms.

**Comment by 100ask** [comment]
> Yes, please remove those changes to PNGs and JPGs.

hi, @XuNeo 
Corrected.
Thank you very much for your review!

**Review by XuNeo — APPROVED** [review]
LTGM. Thank you!

**Comment by IAMMX** [comment]
I have a question, how about the update speed of https://lvgl.100ask.net? For example, lvgl's document is updated. Can https://lvgl.100ask.net be updated synchronously?

**Comment by 100ask** [comment]
> I have a question, how about the update speed of https://lvgl.100ask.net? For example, lvgl's document is updated. Can https://lvgl.100ask.net be updated synchronously?



> I have a question, how about the update speed of https://lvgl.100ask.net? For example, lvgl's document is updated. Can https://lvgl.100ask.net be updated synchronously?

We will check at least once a week (manually) to maintain synchronization.

**Comment by IAMMX** [comment]
> We will check at least once a week (manually) to maintain synchronization.

# lvgl

image

# 100ask

image

I compared it and found that this littelefs was updated two weeks ago, but it has not been updated on https://lvgl.100ask.net/.

**Comment by 100ask** [comment]
> We will check at least once a week (manually) to maintain synchronization.

After this PR merge (there may be changes to the document during the merge process), this operation will be executed. Otherwise, we will maintain synchronization every 1-3 months.

**Pull request closed without merging**
