### PR TITLE
feat(others): add animator porting

### PR DESCRIPTION
**Pull request by cnjhb**
animator is an animation generator that automatically generates animations by simply describing the final state of an object's properties.

use case:
```
static void rsroad_show(lv_event_t* e)
{
    lv_obj_anim(ui_bottomBar,
        "y", 230,
        NULL);
    lv_obj_anim(ui_bottomBar,
        "w", 960,
        "deleted_cb", bottombar_del_cb,
        NULL);

    lv_obj_anim(ui_bat,
        "y", 195,
        NULL);
    lv_obj_anim(ui_setlist,
        "x", -650,
        NULL);
    lv_obj_anim(ui_GearLbl,
        "x", 0,
        "y", 82,
        NULL);
    lv_obj_anim(ui_SpeedLabel2,
        "x", 0,
        "y", -118,
        NULL);
    lv_obj_anim(ui_SpeedUnitLabel1,
        "opa", 255,
        "y", 290,
        NULL);
    lv_obj_anim(ui_rsroad,
        "opa", 255,
        NULL);
    lv_obj_anim(ui_VwSlider,
        "x", -679,
        "y", 233,
        NULL);
    lv_obj_anim(ui_VwSlider1,
        "x", 679,
        "y", 233,
        NULL);
    lv_obj_t* vwsld = ui_comp_get_child(ui_VwSlider, UI_COMP_VWSLIDER_CONTAINER18);
    lv_obj_t* vwsld1 = ui_comp_get_child(ui_VwSlider1, UI_COMP_VWSLIDER_CONTAINER18);
    lv_obj_anim(vwsld,
        "y", 0,
        NULL);
    lv_obj_anim(vwsld1,
        "y", 0,
        NULL);
    lv_obj_anim(ui_SpeedUnitLabel1,
        "opa", 255,
        "y", 290,
        NULL);
}
static void rsroad_hide(lv_event_t* e)
{
    lv_obj_anim(ui_rsroad,
        "opa", 0,
        NULL);
    lv_obj_anim(ui_SpeedUnitLabel1,
        "opa", 0,
        NULL);
}
static void classic_show(lv_event_t* e)
{
    lv_obj_anim(ui_setlist,
        "x", 0,
        NULL);
    lv_obj_anim(ui_GearLbl,
        "x", -570,
        "y", 0,
        NULL);
    lv_obj_anim(ui_SpeedLabel2,
        "x", 570,
        "y", 0,
        NULL);
    lv_obj_anim(ui_bottomBar,
        "w", 600,
        "deleted_cb", bottombar_del_cb,
        NULL);
    lv_obj_anim(ui_bottomBar,
        "y", 200,
        NULL);
    lv_obj_t* vwsld = ui_comp_get_child(ui_VwSlider, UI_COMP_VWSLIDER_CONTAINER18);
    lv_obj_t* vwsld1 = ui_comp_get_child(ui_VwSlider1, UI_COMP_VWSLIDER_CONTAINER18);
    lv_obj_anim(vwsld,
        "y", -70,
        NULL);
    lv_obj_anim(vwsld1,
        "y", -70,
        NULL);
    lv_obj_anim(ui_bat,
        "y", 225,
        NULL);
    lv_obj_anim(ui_spdwatch,
        "x", 570,
        "opa", 255,
        NULL);
    lv_obj_anim(ui_engspdwatch,
        "x", -570,
        "opa", 255,
        NULL);
    lv_obj_anim(ui_VwSlider,
        "x", -570,
        "y", 245,
        NULL);
    lv_obj_anim(ui_VwSlider1,
        "x", 570,
        "y", 245,
        NULL);
}

static void classic_hide(lv_event_t* e)
{
    lv_obj_anim(ui_engspdwatch,
        "opa", 0,
        "x", 0,
        NULL);
    lv_obj_anim(ui_spdwatch,
        "opa", 0,
        "x", 0,
        NULL);
}
```

### CODE REVIEW

**Comment by cnjhb** [comment]
https://github.com/user-attachments/assets/5b6a6071-c816-4ed8-9956-b1034e276091

**Comment by liamHowatt** [comment]
Thanks for showing how an implementation could look. To make the CI pass, you will need to make this feature disabled by default until enabled in lv_conf.h, since it depends on an external library header. Add a config option to lv_conf_template.h.

Fixes: #7226

**Comment by kisvegabor** [comment]
It sounds interesting, and I see that a feature like tis could be useful. As might have heard that we are working on our UI editor (#6985) where me might need something like this. 

Unfortunately, I can't see exactly what we might need I would wait until we see the exact requirements.  The animation handling in the editor is scheduled to 2025 Q2. 

Until that feel free to keep polishing this PR, but I can't promise that we will merge it. 🙁

Not that we don't add new features to v8.4. to it should target the master branch.

**Comment by cnjhb** [comment]
> It may be that this alternative animation API should not be added, but we can discuss it.
> 
> Does this actually need to include those external headers? Does it actually depend on glib?

It mainly relies on glib's GHashtable and GValue.
GHashtable I think can be replaced by [stb_ds.h](https://github.com/nothings/stb/blob/master/stb_ds.h) from nothings.
GValue I haven't found a ready-made replacement for so far, maybe we can build a simplified version of it ourselves?

**Comment by cnjhb** [comment]
> It may be that this alternative animation API should not be added, but we can discuss it.
> 
> Does this actually need to include those external headers? Does it actually depend on glib?

I think we should add this style of animation api, this style of api is very convenient for implementing simple animations. It is an addition to the original api.

**Comment by cnjhb** [comment]
> It sounds interesting, and I see that a feature like tis could be useful. Maybe you have heard that we are working on our UI editor (#6985) where me might need something like this.
> 
> Unfortunately, I can't see exactly what we will need and I would wait until we see the exact requirements. The animation handling in the editor is scheduled to 2025 Q2.
> 
> Until that feel free to keep polishing this PR, but I can't promise that we will merge it. 🙁
> 
> Note that we don't add new features to v8.4. So it should target the master branch.

Can new features be added to version 8.5?

**Comment by kisvegabor** [comment]
> Can new features be added to version 8.5? I'm not familiar with LVGL 9 as I use LVGL 8 mostly at work, but I guess I'll be using LVGL 9 next year.

We are not adding new features to any v8 versions, just bug fixing. :slightly_smiling_face:

**Pull request closed without merging**
