### PR TITLE
lv_scale: Update with feedback

### LINKED ISSUE #4551: lv_scale updates
### Introduce the problem

Updates based on observations from @kisvegabor made during `lv_scale` integration.
- Using `float` should be avoided. Instead some up scaling or smart ordering of operation should be used.
- The horizontal and vertical scale should consider the horizontal and vertical padding respectively. That is the ticks should start after the left/top padding and stop before the right/bottom padding.

### Examples and cases
N/A

### Suggested solution
Fix both observations

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Fixes #4551 

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `lv_global_t` structure in [`lv_global.h`](https://github.com/lvgl/lvgl/blob/master/src/core/lv_global.h) and mark the variable with `(LV_GLOBAL_DEFAULT()->variable)` when it's used. See a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the following needs to be followed (see a detailed description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)):
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by C47D** [comment]
For reference, this is the current renders of the examples (using float) commit 140369c5c:

Example 1
image

Example 2
image

Example 3
image

Example 4
image

Example 5
image

**Comment by C47D** [comment]
With cba96dd9338a11089ffd38ea0404e1be49ebda78 all floats were removed, this is the result on all the examples, I think they look good.

Example 1

Example 2

**Comment by kisvegabor** [comment]
Looks good, thank you. If there is nothing else for now please mark the PR as ready, and I will merge it.

**Comment by kisvegabor** [comment]
Ah I see, the padding update is still missing.

**Comment by C47D** [comment]
Yep, padding is still missing. I'll work on it later today.

**Comment by C47D** [comment]
@kisvegabor is it just me or the last space (tick 39 - 40) in example 1 is bigger than the previous spaces? That's the rounding issue I talked about in our chat.

**Comment by C47D** [comment]
@kisvegabor with 44c3c14 I tried to avoid using floats by reordering the operations, I think the examples looks ok, let me know what do you think

**Comment by kisvegabor** [comment]
Thank you, Carlos. I'll be on a holiday tomorrow and the weekend, so I can test it on Monday.

**Comment by kisvegabor** [comment]
Thank you Carlos, it look good so far: :+1: 

In the practice I found that on one more place padding  would be useful. If we add padding to the `LV_PART_TICKS` we should start the **only ticks** inside the line. Something line:
```
________________________________________________________________
 pad_left |          |          |          |          |  pad_right
```

Could you still add it?

**Comment by C47D** [comment]
@kisvegabor This means no padding in main part and padding in `LV_PART_TICKS` or they should be added together?

**Comment by C47D** [comment]
Hi, this is my test code

```c
  lv_obj_t * scale = lv_scale_create(lv_scr_act());
  lv_obj_set_size(scale, lv_pct(50), 100);
  lv_scale_set_mode(scale, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
  lv_obj_center(scale);

  lv_scale_set_label_show(scale, true);

  lv_scale_set_total_tick_count(scale, 30);
  lv_scale_set_major_tick_every(scale, 5);

  lv_scale_set_major_tick_length(scale, 10);
  lv_scale_set_minor_tick_length(scale, 5);
  lv_scale_set_range(scale, 10, 40);

  lv_obj_set_style_bg_color(scale, lv_color_hex3(0xf00), 0);
  lv_obj_set_style_bg_opa(scale, LV_OPA_20, 0);

  lv_obj_set_style_pad_right(scale, 10, 0);
  lv_obj_set_style_pad_left(scale, 10, 0);
  lv_obj_set_style_pad_top(scale, 10, 0);
  lv_obj_set_style_pad_bottom(scale, 10, 0);

  lv_obj_set_style_pad_right(scale, 10, LV_PART_TICKS);
  lv_obj_set_style_pad_left(scale, 10, LV_PART_TICKS);
  lv_obj_set_style_pad_top(scale, 10, LV_PART_TICKS);
  lv_obj_set_style_pad_bottom(scale, 10, LV_PART_TICKS);
```

And the result when the scale mode is `LV_SCALE_HORIZONTAL_BOTTOM`

image

When scale mode is `LV_SCALE_HORIZONTAL_TOP`
image

---

Changing size from `lv_obj_set_size(scale, lv_pct(50), 100);` to `lv_obj_set_size(scale, 100, lv_pct(50));`

When scale mode is `LV_SCALE_VERTICAL_RIGHT`
image

When scale mode is `LV_SCALE_VERTICAL_LEFT`
image

**Comment by kisvegabor** [comment]
Thank you Carlos. I'll continue testing and open a new issue if required!

**Comment by C47D** [comment]
> Thank you Carlos. I'll continue testing and open a new issue if required!

Always happy to help :smile_cat:

**Pull request merged**
