### PR TITLE
Change all text related indices from 16-bit to 32-bit integers throughout whole library.

### PR DESCRIPTION
**Pull request by pete-pjb**
Hopefully I haven't missed anything! I have tested with my project and this fixes all my issues relating to text indices overflowing.

### CODE REVIEW

**Comment by embeddedt** [comment]
@pete-pjb The CLA bot is having issues because the commits aren't being associated with your GitHub account. Could you fix that? ([GitHub has some tips here](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user).)

**Review by embeddedt — APPROVED** [review]

**Comment by pete-pjb** [comment]
Hi @embeddedt 

It looks like my VPN had gone down when I did the commit which means my Eclipse environment can't see the git configuration file on my office server and it's used the local computer name instead....

I can't seem to do much about this so I guess I should probably close the pull request and re-submit? Or can you delete it from your end?

What do you think?

Note I have signed the CLA agreement...

Kind Regards,

Pete

**Comment by embeddedt** [comment]
If @kisvegabor approves, we can just merge it, since you have signed the CLA and it's obvious that your account owns the PR and repository. :slightly_smiling_face:

**Comment by pete-pjb** [comment]
Okay thanks @embeddedt, saves the hassle of re-submitting... I will make sure my VPN connection is connected before pushing my changes in future!   :blush:

**Comment by kisvegabor** [comment]
Sure, no problem! :slightly_smiling_face: 

Thank you for the improvement!

**Pull request merged**
