### PR TITLE
feat(api_map): adds guards to api mapping

### LINKED ISSUE #6268: lv_api_map_v8.h has no consideration for things that are enabled/disabled
### LVGL version

v9.x

### What happened?

I just noticed when reading over the header files that there is no testing being done as to what is enabled or disabled in LVGL before defining macros or setting different types.. There should be checking done to ensure a widget is enabled before defining a macro or creating a type that is dependent on a type that might be in a widget. 

### How to reproduce?

```c
#define lv_btnmatrix_create                  lv_buttonmatrix_create
#define lv_btnmatrix_set_map                 lv_buttonmatrix_set_map
#define lv_btnmatrix_set_ctrl_map            lv_buttonmatrix_set_ctrl_map
#define lv_btnmatrix_set_selected_btn        lv_buttonmatrix_set_selected_button
#define lv_btnmatrix_set_btn_ctrl            lv_buttonmatrix_set_button_ctrl
#define lv_btnmatrix_clear_btn_ctrl          lv_buttonmatrix_clear_button_ctrl
#define lv_btnmatrix_set_btn_ctrl_all        lv_buttonmatrix_set_button_ctrl_all
#define lv_btnmatrix_clear_btn_ctrl_all      lv_buttonmatrix_clear_button_ctrl_all
#define lv_btnmatrix_set_btn_width           lv_buttonmatrix_set_button_width
#define lv_btnmatrix_set_one_checked         lv_buttonmatrix_set_one_checked
#define lv_btnmatrix_get_map                 lv_buttonmatrix_get_map
#define lv_btnmatrix_get_selected_btn        lv_buttonmatrix_get_selected_button
#define lv_btnmatrix_get_btn_text            lv_buttonmatrix_get_button_text
#define lv_btnmatrix_has_button_ctrl         lv_buttonmatrix_has_button_ctrl
#define lv_btnmatrix_get_one_checked         lv_buttonmatrix_get_one_checked
```

should read

```c
#if LV_USE_BTNMATRIX
#define lv_btnmatrix_create                  lv_buttonmatrix_create
#define lv_btnmatrix_set_map                 lv_buttonmatrix_set_map
#define lv_btnmatrix_set_ctrl_map            lv_buttonmatrix_set_ctrl_map
#define lv_btnmatrix_set_selected_btn        lv_buttonmatrix_set_selected_button
#define lv_btnmatrix_set_btn_ctrl            lv_buttonmatrix_set_button_ctrl
#define lv_btnmatrix_clear_btn_ctrl          lv_buttonmatrix_clear_button_ctrl
#define lv_btnmatrix_set_btn_ctrl_all        lv_buttonmatrix_set_button_ctrl_all
#define lv_btnmatrix_clear_btn_ctrl_all      lv_buttonmatrix_clear_button_ctrl_all
#define lv_btnmatrix_set_btn_width           lv_buttonmatrix_set_button_width
#define lv_btnmatrix_set_one_checked         lv_buttonmatrix_set_one_checked
#define lv_btnmatrix_get_map                 lv_buttonmatrix_get_map
#define lv_btnmatrix_get_selected_btn        lv_buttonmatrix_get_selected_button
#define lv_btnmatrix_get_btn_text            lv_buttonmatrix_get_button_text
#define lv_btnmatrix_has_button_ctrl         lv_buttonmatrix_has_button_ctrl
#define lv_btnmatrix_get_one_checked         lv_buttonmatrix_get_one_checked
#endif /* LV_USE_BTNMATRIX */
```

There are lots of them that need to have this done.

Where you really run into issues is with things like this...

```c
typedef lv_buttonmatrix_ctrl_t      lv_btnmatrix_ctrl_t;
```

That's going to fail 100% of the time if the button matrix is not enabled.

### PR DESCRIPTION
**Pull request by kdschlosser**
Fixes #6268

### Description of the feature or fix

There were no guards in place for things that can be enabled or disabled. These needed to be added to the api map for version 8

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Damn, you are right! Could you do the same for `lv_api_map_v9.h` too? It's much shorter. :slightly_smiling_face:

**Comment by kdschlosser** [comment]
I don't believe it needs to be done for the V9 map. I will double check it tho.

**Comment by XuNeo** [comment]
Could you try to use #define instead of typdef?

```c
#define lv_coord_t                      int32_t
#define lv_res_t                        lv_result_t
#define lv_img_dsc_t                    lv_image_dsc_t
#define lv_disp_t                       lv_display_t
#define lv_disp_rotation_t              lv_display_rotation_t
#define lv_disp_render_t                lv_display_render_mode_t
#define lv_anim_ready_cb_t              lv_anim_completed_cb_t
#define lv_scr_load_anim_t              lv_screen_load_anim_t
#define lv_btnmatrix_ctrl_t             lv_buttonmatrix_ctrl_t
```

**Comment by kdschlosser** [comment]
I am not the one that write the files originally. I was just adding the guards for when something is disabled. 

I had thought that defines would have been the way to go with this and I am not sure of the reasoning why they were not used. So we are on the same page as far as that goes. There could be a reason why things are typedef'd instead of using macros.

**Comment by kisvegabor** [comment]
I used `typedef`s because they might be produce better compiler errors and warnings. However probably it's not so important. Defines are ok for me too.

**Review by liamHowatt — APPROVED** [review]

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
