### PR TITLE
fix(anim): fix compile warnings

### PR DESCRIPTION
**Pull request by XuNeo**
### Fix warnings mentioned in #4296

Fix -Werror=float-conversion

LVGL involes no float calculation, I added a macro `BEZIER_CONST_VAL` for clarity

CFLAGS for simulator has been update to include `-Werror=float-conversion` [in this PR](https://github.com/lvgl/lv_port_pc_eclipse/pull/122)

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
I've merged #4296, please rebase this PR to `master`.

And please add `Werror=float-conversion` to the [tests](https://github.com/lvgl/lvgl/blob/master/tests/CMakeLists.txt#L109) too.

**Comment by amirgon** [comment]
https://github.com/lvgl/lvgl/blob/3ac7cb0230308134b7da0ee8c9b25d498716dd0e/src/misc/lv_math.h#L37

Micropython bindings does not bind C macros.  
Can this be changed to static inline function instead?

**Comment by XuNeo** [comment]
The Micropython is failing on `lv.bezier3`. Is this module automatically generated from source code? I'll add a new commit to rename it to `lv.cubic_bezier` to check if that fixes.

**Comment by XuNeo** [comment]
`test_spinner ` is failing, I'm checking now.

**Comment by XuNeo** [comment]
Hi Gabor, 

I accidently find out that this anim path(on right, `cubic-bezier(.42,.58,0,1)`) looks better than ease-in-out(`cubic-bezier(.42,0,.58,1)`). What do you think?

https://github.com/lvgl/lvgl/assets/25867991/02d13af8-bb12-47dc-a95c-3035fad5f49d

**Comment by kisvegabor** [comment]
The right spinner really looks better! Let's go for it! Once you update the reference images of the spinner test, please update the bezier curve here in this PR too.

**Comment by XuNeo** [comment]
The spinner anim path is updated, tests pass. Micropython rp2 port is still failing. It doesn't look like relevant to this PR.

**Comment by kisvegabor** [comment]
I also think the MicroPython issue is unrelated. Thank you for the fix!

**Pull request merged**
