### PR TITLE
checkbox: Check for mem allocation failure in set_text

### PR DESCRIPTION
**Pull request by C47D**
### Description of the feature or fix

Handle memory allocation failure in `lv_checkbox_set_text` and add test.

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [ ] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [ ] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [ ] Use typed pointers instead of `void *` pointers
- [ ] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [ ] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [ ] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [ ] `struct`s should be used via an API and not modified directly via their elements.
- [ ] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [ ] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [ ] Arguments must be named in H files too.
- [ ] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by C47D** [comment]
@kisvegabor is it safe to pass `NULL` to `strcpy` as `src` parameter? I've take a look at the [c reference](https://en.cppreference.com/w/c/string/byte/strcpy) and I think it isn't. For `strlen` when the `str` parameter is [NULL the return value is 0](https://en.cppreference.com/w/c/string/byte/strlen).

I think it would be safer like this:
```c
void lv_checkbox_set_text(lv_obj_t * obj, const char * txt)
{
    lv_checkbox_t * cb = (lv_checkbox_t *)obj;

    if (NULL != txt)
    {
        size_t len = 0;

#if LV_USE_ARABIC_PERSIAN_CHARS
        len = _lv_txt_ap_calc_bytes_cnt(txt);
#else
        len = strlen(txt);
#endif

        if(!cb->static_txt) cb->txt = lv_realloc(cb->txt, len + 1);
        else cb->txt = lv_malloc(len + 1);

        LV_ASSERT_MALLOC(cb->txt);
        if(NULL == cb->txt) return;

#if LV_USE_ARABIC_PERSIAN_CHARS
        _lv_txt_ap_proc(txt, cb->txt);
#else
        strcpy(cb->txt, txt);
#endif

        cb->static_txt = 0;
    }

    lv_obj_refresh_self_size(obj);
    lv_obj_invalidate(obj);
}
```

**Comment by kisvegabor** [comment]
> is it safe to pass NULL to strcpy as src parameter?

I don't think it's safe either.

**Comment by C47D** [comment]
I can include the above code snippet in this request, if you think it is ok.

**Comment by kisvegabor** [comment]
Yes, please. But please use `if (txt == NULL) return;` to have less nesting.

BTW, sometimes I see people using `if(NULL != txt)` instead of `if (txt != NULL)`. Do you know what is the advantage of having the constant expression first?

**Comment by pete-pjb** [comment]
Hi @kisvegabor ,

See [this](https://stackoverflow.com/questions/370366/why-put-the-constant-before-the-variable-in-a-comparison)


cc @C47D

**Comment by kisvegabor** [comment]
I see, thank you Pete! :slightly_smiling_face:

**Comment by C47D** [comment]
Yup, the link @pete-pjb provided is the reason I tent to use NULL (or any other constant for that matter) at the left side of the comparison.

@kisvegabor I've updated the behavior of the function and also added a test for it. There's another manual work I did to count the number of times malloc was called, which could be done automagically by having a mocking capability in the unit tests.

**Comment by C47D** [comment]
> Yes, please. But please use if (txt == NULL) return; to have less nesting.

I think that's not possible because according to the docs when passing NULL the text should be refreshed, so it can't return early.

**Comment by kisvegabor** [comment]
You are right, Let's no with your solution.  I merge it. 

Do we need mocking on other places too?

**Comment by C47D** [comment]
Maybe not, let's find out writing more tests :)

**Pull request merged**
