### PR TITLE
Reorganize Documentation

### PR DESCRIPTION
**Pull request by vwheeler63**
0.  Executive Summary:

    - This PR is a MAJOR re-organization of much of the introductory content of the documentation -- the material new LVGL programmers need early in their learning sequence to get up and coding with LVGL, and having wins with it, as quickly as possible.

    - In my opinion, the quality of the documentation from the viewpoint of a programmer new to LVGL is now about 3X clearer and more usable than what it was.  Many errors and ambiguities were corrected with coherent, clear explanations in a logical order.

    - Technical details on many topics are now in one place and easy to find.  Between Gábor and I, we found what must have been 8-10 different major [and important] topics that were scattered in 2, 3 and sometimes 4 different places, that are now consolidated in one place, and in many cases re-written or at least thoroughly edited for clarity.

    - Here is where you can see what it will look like:  http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/index.html    Note that EXAMPLES and VERSION numbers do not work on this web server, as it needs to be on the actual documents host for these to work.

    - Details are below.

1.  The docs directory structure was reorganized to give each topic exactly one place to go, not 2, or 3 or 4 as was previously the case (and happened).

    The old structure invited certain topics to go into multiple locations (e.g. full explanations of how to set up a project, and about 8 other topics that are now consolidated).  This structure clarifies for the writer/editor where new topics (or updates to old ones) should go.

    There are now 2 major sections of the documentation from the viewpoint of content (not the table of contents, though they are related).  A)  introductory material that orients new programmers (./docs/intro/), and B) reference material (./docs/details/), in which each topic is fully covered and in one place.  (No material is in the introductory material that is not also in the reference material.  And introductory material mostly refers to the reference material for details.)

    The directory structure reflects these sections, and is also reflected in the HTML URL paths that are generated.

    I am hopeful that this directory structure and new location of topics will be self-explanatory to programmers adding to the documentation in the future.  But I will be adding some guidelines in the ./docs/README.md just in case it isn't perfectly self-explanatory.

2.  In the Introduction, Overview, Getting Started, Adding LVGL to Your Project, Modules and Base Widget sections, anywhere from 1/3 to 2/3 of the material was majorly re-written (consolidated and unified) into a coherent logical whole in clear English.  Basics such as the relationship between Screens, Displays and Widgets is far, FAR better explained now and will give a much more helpful "springboard" to get programmers new to LVGL up and winning with LVGL as fast as possible.

    Each section was designed to answer the questions:  "What is it?", "What does it do?", and "How does it do it?" as early as possible to make it easier for anyone (beginner and experienced) users to find what they are looking for and quickly get up to speed with it.  (Though there was good material before, there were places where this quality was lacking.)

    The result of `#1` and `#2` above is all-around WAY better documentation -- it is easier to get oriented for programmers new to LVGL, and easier to find things for experienced LVGL programmers.

4.  The term "Widget" was being badly conflated with the term "object" and "obj".  This undoubtedly propagated from the fact that the Base Widget's data type was 'lv_obj_t'.  The damage done caused the term "object" to be ubiquitous in the documentation when it meant "Widget".

    There are legitimate times when the term "object" should be used:  Display object, cursor object, and many other types of objects that are NOT widgets.  But the term "object", and "obj", "obj1", "obj2" etc. where it meant "Widget" was converted to "Widget", "widget1", "widget2", etc..  (There were probably close to a thousand such instances of this.  Note that I was VERY careful not to miss any instances where "object" was the correct term.)

    This included significant edits to comments in 3 code files:
    - ./scripts/style_api_gen.py  which generates ./docs/details/base-widget/styles/style-properties.rst
    - ./src/core/lv_group.h  (terms match updated documentation)
    - ./src/misc/lv_event.h  (terms match updated documentation)

5.  Consolidated (unified) content previously scattered in 2-4 places:

    - setting up LVGL in your project,
    - LVGL basics coverage of objects, widgets, events, parts, states,
        styles, themes,
    - base object,
    - calls used to create and modify widgets,
    - layers,
    - display,
    - input devices,
    - widget groups,
    - coordinates,
    - widget size,
    - widget position,
    - widget alignment,
    - several others I did not record.

6.  Thanks to the versatility of reStructuredText and Sphinx (our primary documentation-generation logic), the Table of Contents (TOC, that makes up page links and the navigation-tree) has ZERO to do with the underlying directory structure.  As far as it is concerned, the path to the documents is irrelevant.  It gives full control to the writer/editor as to how the TOC is organized.

7.  For reviewers, unfortunately, this is one of those cases where studying the CHANGES isn't going to do much good where there was a lot of re-writing, because of the extent of those changes is going to hide what really happened.  For the consolidated (unified) content, some of it was re-written, and some of it that was actually duplicate was disposed of.

    Example:  [ Introduction > Overview > LVGL Basics ]  was a major reorganization of this description of "basics", which was previously scattered.  It is now together in one, coherent whole, in the sequence needed for the reader to get an accurate understanding of the basics.  The various sub-sections of this page (down to "Events") now pull together this important, orienting material in an accurate, clear and in-sequence way for readers new to LVGL.

    Instead, instead of trying to decipher "what happened" using the DIFFs (where there was a lot of re-writing), use this link to see the end result of the reorganization.

    http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/index.html

    That said, you can rest assured that I was very careful to preserve everything except things which actually WERE duplicate or redundant.  Consolodating topics revealed these things so the actual SIZE of the documentation is now exactly what it was minus only the small amount that was removed for redundancy.

8.  There are 2 legitimate Sphinx warnings that are generated:

    - <tmpdir>/intro/index.rst: WARNING: document isn't included in any toctree
    - <tmpdir>/details/index.rst: WARNING: document isn't included in any toctree

    This is intentional.  The reason these are legitimate is that this gives a way to:

    - have the Introduction and Reference sub-pages immediately visible in the top-level table of contents without hiding them in a sub-page.  So this:

            Introduction

              - Introduction   <-- link

            Details

              - Details        <-- link

            ...

      turns into this:

            Introduction

              - Introduction
              - Overview
              - Getting Started
              - Add LVGL to Your Project

            Details

              - Configuration
              - Modules
              - Base Object
              - Widgets
              - Other Components
              - Examples
              - Debugging
              - Integration and Drivers
              - 3rd-Party Libraries

            ...

      Note that these are direct links to sub-pages.  This is an intentional departure from our usual practice of capturing a group of sub-pages under an INDEX.RST file which generates an `index.html` file, but winds up hiding the sub-pages in the higher-level TOC.

      The `index.rst` file would not even be needed except when a user types THIS into his browser:

          https://docs.lvgl.io/master/intro/

      the web server will look for an `index.html` file and will not find it, and serve a 404 (file not found) error instead. So I added the `index.rst` file (that does not appear in this TOC) in order to generate the needed `index.html`.  (I realize there are ways to get web servers to serve up other "default" pages in a directory, but this avoids the need for that.)  This way, when the user tries the above he will get a nice-looking page that contains the sub-pages, and look like this:

            Introduction

              - Introduction
              - Overview
              - Getting Started
              - Add LVGL to Your Project

      The presence of this index.rst file NOT connected to any TOC generates the warning.

9.  Besides re-writing many parts of the beginning half of the documentation (for clarity, and use of standard English), some parts were found (and corrected) that were just plain wrong.  For example:

        https://docs.lvgl.io/master/overview/display.html#background

    stated that every `lv_display_t` object has a

        - background color
        - background image, and
        - opacity properties.

    This is not even vaguely correct, and probably occurred because the writer was confusing Screens and Displays.  This was thoroughly corrected, and the material re-located where it belonged:  with the (now thorough) description of Screens under Base Object (not under Display, though the use of Screens as layers is correctly covered under Display).  There were a handful of others (e.g. in cases where there are multiple displays, the Default Display was reported to be the LAST one created, but it is actually the FIRST one created according to the C code).

10.  Finally, `@example` Doxygen command was removed from ./src/widgets/label/lv_label.h  because it does not do what the writer expected, and for this reason it is not one of the supported Doxygen commands.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.  DONE!
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.  n/a
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.  n/a
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).  n/a
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).  n/a
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.  Done.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.  Done.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hey Vic,

First of all, thank you! 

Wow it's way more changed files than I anticipated. 😅 I'm afraid it will be hard to merged because of merge conflicts. 

A few notes:
- Can we break it into 2-3 PRs? E g. It seems the obj-> widget refactoring modified most of the files. Can it have its own PR?
-We were talking about redirecting the old links. Can it be added too?
- I think in "Add LVGL to Your Project" we should also mention displays and indevs. Maybe just one short introductionary pages for each and link to the long description in the Modules 
- IMO we can improve the style of the flow charts. I can take care of them. 

I also saw a few smaller things and can comment about them Monday or Tuesday.

**Comment by vwheeler63** [comment]
Hi, Gábor!  ( @kisvegabor )

About moving the obj -> widget renaming into its own PR, I can do that.  (Note, I have obligations for the next 10-12 hours or so, so there will be a delay.)

Please refresh my memory about

> * We were talking about redirecting the old links. Can it be added too?

If that was about finding the long list of website hyperlinks that were bad, I was hoping to move that into a separate project, because it takes a separate thought process.  I know I did find a lot of hard-coded HTTP hyperlinks that had the old path in them, and fixed them so they would either use the Sphinx syntax, or lacking that (e.g. in 'jp' and 'zh' translation files not shown here) have the correct new-path URLs in them.

> I think in "Add LVGL to Your Project" we should also mention displays and indevs

Displays and indev are mentioned right in the beginning as step 3 in the 6-step process.  Are you talking about adding more detail for step 3?  That seems do-able.

>  IMO we can improve the style of the flow charts. I can take care of them.

I was leaving the use of draw.io until last because that will be a long learning curve for me.  If you are already up to speed on that, that would be awesome!  

Let me know on the above.

Kind regards,
Vic

**Comment by kisvegabor** [comment]
> About moving the obj -> widget renaming into its own PR, I can do that. (Note, I have obligations for the next 10-12 hours or so, so there will be a delay.)

Great! It should lower the number of changed files greatly. If it breaks too much, let's leave it as it is. 

Here you can see what changed in the docs recently. Please make sure that these are not lost during the reorganization. 

>> Please refresh my memory about

> We were talking about redirecting the old links. Can it be added too?

It was the [sphinx-reredirects](https://pypi.org/project/sphinx-reredirects/) plugin to make sure that at least the major docs page are redirected to their new location. 

> Displays and indev are mentioned right in the beginning as step 3 in the 6-step process. Are you talking about adding more detail for step 3? That seems do-able.

Ah I see now, however I think this structure could be improved:
image
What about this ToC?
- Add LVGL to Your Project  
   - Get LVGL  
   - Build LVGL
      - Make and Cmake
      - Managed builds 
   - Configuration 
      - lv_conf.h
      - Kconfig
   - Connect LVGL to the hardware 
      - Tick interface
      - Display interface
      - Input device interface
   - Timer handler
   - Operating Systems and Interrupts

Drawing Pipeline is not needed to add LVGL to your project. Maybe make it a "Module"?

---

A few assorted notes:
- Rename "Overview" to "The basics of LVGL"
- The ToC of Overview/LVGL Basics seems to flat. Can it be grouped somehow?
- In "LVGL Basics" regarding the section from "Display Refresh Sequence" to "Widgets" I think something lighter more direct description would be help the users more. For example (not well phrased sentences, just for illustratin): You need to create displays for each physical displays, create screen widgets on them, and widget on the screens. To handle touch, mouse, keypad, etc, Input devices (indev) shall be created. Tick is needed to tell LVGL what time is it. lv_timer_handler is main schedule of LVGL. Periodically it refreshed the displays, reads the input devices, fires events, runs the animations and the user created timers. (Links to each module)
- "Getting started" is a little bit redundant with "Overview"/
- Rename "Modules" to "Main Components"?
- "Main Components" followed by "Other Components"/"The basics of LVGL". It's also short for its own main chapter. Can it be migrated into "The basics of LVGL" as "Step to learn LVGL" (or so)?

**Comment by vwheeler63** [comment]
> It was the [sphinx-reredirects](https://pypi.org/project/sphinx-reredirects/) plugin to make sure that at least the major docs page are redirected to their new location.

I don't remember discussing that, but I do remember talking about how it would be better to instead of having hyperlinks leading to a specific commit (e.g. https://github.com/lvgl/lvgl/blob/84b28ff688b9b8b33682191c37554194d5ae1950/examples/anim/lv_example_anim_1.c  under Examples for Animation) to be a branch instead.  And if that is what you were referring to, I found out how to do that just last night, and it involves a slight change to the `lv_example.py` in its code that embeds the hyperlinks.  Was that it?

Re your thoughts on the ToC -- I like that much better.  Will implement.

> Rename "Overview" to "The basics of LVGL"

Okay.

> The ToC of Overview/LVGL Basics seems to flat. Can it be grouped somehow?

I will look into this.  I may have some questions or present some ideas to you for feedback/review.

> In "LVGL Basics" regarding the section from "Display Refresh Sequence" to "Widgets" I think something lighter more direct description would be help the users more. For example (not well phrased sentences, just for illustratin): You need to create displays for each physical displays, create screen widgets on them, and widget on the screens. To handle touch, mouse, keypad, etc, Input devices (indev) shall be created. Tick is needed to tell LVGL what time is it. lv_timer_handler is main schedule of LVGL. Periodically it refreshed the displays, reads the input devices, fires events, runs the animations and the user created timers. (Links to each module)

Excellent summary/overview!  I will blend this in.

> "Getting started" is a little bit redundant with "Overview"/

I agree...  It begs for, perhaps, a different presentation on the main buttons as well.  I was trying to keep the words on the main buttons on the landing page, but let me re-think that, as there may be a "cleaner" presentation without the logical overlap.

> Rename "Modules" to "Main Components"?

I like it!  :-)  Will do.

> "Main Components" followed by "Other Components"/"The basics of LVGL". It's also short for its own main chapter. Can it be migrated into "The basics of LVGL" as "Step to learn LVGL" (or so)?

I am not clear on what is meant here.  I agree with the renaming of Modules to "Main Components", and then "pairing" that with "Other Components".  However, I feel fairly strongly that the "basics" (i.e. how it works) should be very early in the presentation.  Reason:  there is a teaching principle that teaching achieves better and faster success when it orients the student very early by answering these basic questions as soon as possible:  "What is it?", "What does it do?", and "How does it do it?".  The answers to the last 2 questions together also answer "When would this be useful in my project?" since the reader (we presume) knows the nature of his project.

So regarding "It's also short for its own main chapter" -- which "chapter" are you referring to here?

**Comment by vwheeler63** [comment]
Hi, Gábor!  ( @kisvegabor )

One more thing:  under "Other Components", I was thinking its child topics should be ordered (if they are not already) in the order in which a person new to LVGL would want to look into them.  If you agree, if it was me, I would put "Observer" at the top, but I am not familiar with these components, so if you would not mind, I would like to get some feedback on the ordering of topics under this heading, if it is not already as it should be.

Kind regards,
Vic

**Comment by vwheeler63** [comment]
Closing this and will be re-submitted as 2 separate PRs: one with just word changes, and the other where the changes involve document structure and links so it doesn't break the docs build.

**Comment by vwheeler63** [comment]
> Here you can see what changed in the docs recently. Please make sure that these are not lost during the reorganization.

I paid attention to the docs changes recently, and made sure all those changes are included.

**Comment by vwheeler63** [comment]
> It was the [sphinx-reredirects](https://pypi.org/project/sphinx-reredirects/) plugin to make sure that at least the major docs page are redirected to their new location.

It works!  👍

**Comment by vwheeler63** [comment]
> What about this ToC?
> 
>     * Add LVGL to Your Project
>       
>       * Get LVGL
>       * Build LVGL
>         
>         * Make and Cmake
>         * Managed builds
>       * Configuration
>         
>         * lv_conf.h
>         * Kconfig
>       * Connect LVGL to the hardware
>         
>         * Tick interface
>         * Display interface
>         * Input device interface
>       * Timer handler
>       * Operating Systems and Interrupts

Where do you see Sleep Management in this?  Perhaps renaming "Operating Systems and Interrupts" to "Threading Considerations" and having it as a section there?

**Comment by vwheeler63** [comment]
Hi, Gábor!

Okay, all of the above is done and reflected in the ["demo" website](http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/), except for the clarification needed.  Search for "I am not clear on what is meant here".

Kind regards,
Vic

**Comment by kisvegabor** [comment]
Excellent! 

> I am not clear on what is meant here...

Sorry it seems a few lines were messed up here. I meant
-  "Getting started" is a little bit redundant with "Overview"/"The basics of LVGL". It's also short for its own main chapter. Can it be migrated into "The basics of LVGL" as "Step to learn LVGL" (or so)?

**Comment by kisvegabor** [comment]
I still see a few minor things that we could discuss, but it's better merge the large changes and modify it it small steps.

**Comment by vwheeler63** [comment]
> * "Getting started" is a little bit redundant with "Overview"/"The basics of LVGL". It's also short for its own main chapter. Can it be migrated into "The basics of LVGL" as "Step to learn LVGL" (or so)?

Oh!  Now I get it -- the "Getting Started" is a little short, and can it be merged in with Basics....   Hmmm....  I like the alternate title....  Let me think about how I can make it fit under the "Basics" umbrella.  Then I will submit.

**Comment by vwheeler63** [comment]
> "Step to learn LVGL" (or so)?

I got it!  I got it!  (Bright idea.)  It can go at the end of "LVGL Basics" as a "Deeper Learning" section -- a concept similar to "Further Reading"!   And the "Getting Started" button can lead to that section and be called 'Deeper Learning"!

Of course!!

I'll put that together to see how you like it.  Meanwhile, I agree, a PR is appropriate, and we can make small changes after as needed.

**Comment by vwheeler63** [comment]
@kisvegabor Ta-daaaa  http://crystal-clear-research.com/for_gabor/demo/docs.lvgl.io/master/intro/basics.html

**Pull request closed without merging**
