### PR TITLE
perf(os): optimize OS API calls without OS mode

### PR DESCRIPTION
**Pull request by FASTSHIFT**
Since compilation does not necessarily optimize cross-file empty functions well (-O3 optimization alone is not enough unless LTO optimization is enabled), In the absence of an operating system, use inline functions to help compile optimizations and avoid the call overhead of the OS API to ensure no performance penalty.

Especially in scenarios where large amounts of text are used, cache requests will be very frequent, resulting in many meaningless `lv_mutex` calls.

The following figure compares the results of the [decompilation analysis tool](https://github.com/NationalSecurityAgency/ghidra) and the trace data.

Fix before:
image

image

Fix after:
image

image

It is measured that the `lv_cache_acquire` function can reduce the time consumption by more than 100us per frame on real devices. 

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
Assembly code and address of `lv_mutex_lock`:
image

After calculation, the address difference between the `lv_cache_acquire` function and the `lv_mutex_lock` function is more than 25K bytes, which can easily trigger an instruction cache miss and waste cache line space.

**Comment by FASTSHIFT** [comment]
image
The same effect can be achieved by using static inline, which can maintain the characteristics of the function.

**Review by uLipe — DISMISSED** [review]
Nice work!

**Review by uLipe — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
Great!

**Pull request merged**
