### PR TITLE
fixs draw pattern stack-use-after-scope error

### PR DESCRIPTION
**Pull request by FlyLu**
### Description of the feature or fix

radius_mask_param is a local variable, only valid in the following lines 1273 and 1276.
I noticed that the lv_draw_mask_add function only saves a pointer.

https://github.com/lvgl/lvgl/blob/60be7c1ceecf26bcc7413e80ddb2f154a5f6b5e5/src/lv_draw/lv_draw_rect.c#L1273-L1281

If the lv_draw_img function is executed, the invalid variable will be accessed in the lv_draw_mask_apply  function.

https://github.com/lvgl/lvgl/blob/60be7c1ceecf26bcc7413e80ddb2f154a5f6b5e5/src/lv_draw/lv_draw_mask.c#L106-L111

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Update CHANGELOG.md
- [x] Update the documentation

### CODE REVIEW

**Comment by FlyLu** [comment]
I found this problem using GCC [AddressSanitizerte ](https://en.wikipedia.org/wiki/AddressSanitizer)function
Easy to use as follows：
```C
CFLAGS  += -fsanitize=address 
LDFLAGS += -fsanitize=address
```

**Comment by kisvegabor** [comment]
Nice catch! Thank you!

Please really update the CHANGELOG :wink:

**Comment by embeddedt** [comment]
@kisvegabor Perhaps we should look into a bot which automatically creates CHANGELOG entries based on commit names; it would reduce the overhead of making a pull request.

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
> @kisvegabor Perhaps we should look into a bot which automatically creates CHANGELOG entries based on commit names; it would reduce the overhead of making a pull request.

Good idea. What about this? https://github.com/lob/generate-changelog

I started to use [commitizen](https://github.com/commitizen/cz-cli) (which is great stuff IMO) and seemingly `generate-changelog` works well with its format.

**Comment by embeddedt** [comment]
Looks good!

**Comment by FlyLu** [comment]
> Please really update the CHANGELOG 😉

Got it, I have updated the CHANGELOG.md

**Comment by kisvegabor** [comment]
@embeddedt 
I added it to the ROADMAP to not forget it: https://github.com/lvgl/lvgl/commit/762c0a3274dc7a576a620fc72cb4a9dfe27bc4b6

@FlyLu 
Thank you, merging!

**Pull request merged**
