### PR TITLE
fix(cmake) remove main component dependency

### PR DESCRIPTION
**Pull request by starfire24680**
### Description of the feature or fix

Backport from #2420

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update [CHANGELOG.md](https://github.com/lvgl/lvgl/blob/master/docs/CHANGELOG.md)
- [ ] Update the documentation

### CODE REVIEW

**Comment by C47D** [comment]
Seems like #2420 wasn't applied to other branches, thanks for sending this PR 😄

**Comment by amirgon** [comment]
This would break the Micropython ESP32 port.
See https://github.com/lvgl/lvgl/pull/2444

**Comment by starfire24680** [comment]
> This would break the Micropython ESP32 port.
> See #2444

Fixed now

**Review by embeddedt — APPROVED** [review]

**Comment by kisvegabor** [comment]
@amirgon do you also approve this PR?

**Review by amirgon — APPROVED** [review]

**Comment by amirgon** [comment]
> @amirgon do you also approve this PR?

Yes.

**Comment by kisvegabor** [comment]
Thanks you!

@amirgon 
How could you approve it like this?
image


I can add people only with write access as reviewer.

**Comment by embeddedt** [comment]
As far as I know, any GitHub user can approve PRs, however, it does not count towards the required approvals on repositories with that feature enabled unless they have write access.

You cannot, however, request random users to review a PR.

**Comment by amirgon** [comment]
> @amirgon
> How could you approve it like this?
> image
> 
> I can add people only with write access as reviewer.



> As far as I know, any GitHub user can approve PRs, however, it does not count towards the required approvals on repositories with that feature enabled unless they have write access.

Correct,
I just started a review and approved it with no comments.

**Comment by kisvegabor** [comment]
Ohh, good to know, thanks.

**Pull request merged**
