### PR TITLE
fix(vg_lite): remove redundant MOVE_TO operations

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

This will cause the path to be displayed abnormally if it is not closed.
image

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by XuNeo — APPROVED** [review]

**Review by W-Mai — APPROVED** [review]

**Comment by W-Mai** [comment]
Oh, this visualization tool is so cool, how can I find this tool?
ceeb653ely8hmzzl533zhg204b05rx6p

**Comment by FASTSHIFT** [comment]
> Oh, this visualization tool is so cool, how can I find this tool? ceeb653ely8hmzzl533zhg204b05rx6p [ ceeb653ely8hmzzl533zhg204b05rx6p ](https://private-user-images.githubusercontent.com/24841247/306950073-52d98764-3665-4467-837b-ed81a6f1f6b4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTY0MTksIm5iZiI6MTcwODU5NjExOSwicGF0aCI6Ii8yNDg0MTI0Ny8zMDY5NTAwNzMtNTJkOTg3NjQtMzY2NS00NDY3LTgzN2ItZWQ4MWE2ZjFmNmI0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OGFhYjEzYjZkYmJmOTFiMWIyZGE2YmNiNjc0MzdlYTBiMDZlYzYyN2Y5YzQ0YWRiMTBiZmRmYTZlN2I4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTWjuX-Itao0kk7HvequN1z24yb9Mg03Tk7A0XfVZhk) [ ](https://private-user-images.githubusercontent.com/24841247/306950073-52d98764-3665-4467-837b-ed81a6f1f6b4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTY0MTksIm5iZiI6MTcwODU5NjExOSwicGF0aCI6Ii8yNDg0MTI0Ny8zMDY5NTAwNzMtNTJkOTg3NjQtMzY2NS00NDY3LTgzN2ItZWQ4MWE2ZjFmNmI0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OGFhYjEzYjZkYmJmOTFiMWIyZGE2YmNiNjc0MzdlYTBiMDZlYzYyN2Y5YzQ0YWRiMTBiZmRmYTZlN2I4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTWjuX-Itao0kk7HvequN1z24yb9Mg03Tk7A0XfVZhk)

It's here: https://github.com/W-Mai/vegravis

**Comment by W-Mai** [comment]
> It's here: https://github.com/W-Mai/vegravis

Thank you!

**Comment by FASTSHIFT** [comment]
@kisvegabor 
This PR should also be merged, unlike the vector modifications :)

**Review by kisvegabor — APPROVED** [review]

**Pull request merged**
