### PR TITLE
refact(monitor): refact system monitor component

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

1. Assign `perf_info` statically.
2. Fix typo `LV_USE_PERF_MONITOR_LOG_MDOE` -> `LV_USE_PERF_MONITOR_LOG_MODE`.
3. Add missing `LV_USE_PERF_MONITOR_LOG_MODE` configuration.
4. Fix MP binding build errors.
5. rename `lv_monitor` -> `lv_sysmon`

### Checkpoints
- [x] Run `code-format.py` from the scripts folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed
- [ ] Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant. 
- [ ] Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- [ ] If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/release/v8.3/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/release/v8.3/Kconfig).
 
Be sure the following conventions are followed:
- [x] Follow the [Styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Prefer `enum`s instead of macros. If inevitable to use `define`s export them with `LV_EXPORT_CONST_INT(defined_value)` right after the `define`.
- [x] In function arguments prefer `type name[]` declaration for array parameters instead of `type * name`
- [x] Use typed pointers instead of `void *` pointers
- [x] Do not `malloc` into a static or global variables. Instead declare the variable in `LV_ITERATE_ROOTS` list in [`lv_gc.h`](https://github.com/lvgl/lvgl/blob/master/src/misc/lv_gc.h) and mark the variable with `GC_ROOT(variable)` when it's used. See a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#memory-management).
- [x] Widget constructor must follow the `lv_<widget_name>_create(lv_obj_t * parent)` pattern.
- [x] Widget members function must start with `lv_<modul_name>` and should receive `lv_obj_t *` as first argument which is a pointer to widget object itself.  
- [x] `struct`s should be used via an API and not modified directly via their elements.
- [x] `struct` APIs should follow the widgets' conventions. That is to receive a pointer to the `struct` as the first argument, and the prefix of the `struct` name should be used as the prefix of the function name too (e.g.  `lv_disp_set_default(lv_disp_t * disp)`)
- [x] Functions and `struct`s which are not part of the public API must begin with underscore in order to mark them as "private".
- [x] Arguments must be named in H files too.
- [x] To register and use callbacks one of the followings needs to be followed (see a detaild description [here](https://docs.lvgl.io/master/get-started/bindings/micropython.html#callbacks)): 
  - For both the registration function and the callback pass a pointer to a `struct` as the first argument. The `struct` must contain `void * user_data` field.
  - The last argument of the registration function must be `void * user_data` and the same `user_data` needs to be passed as the last argument of the callback.
  - Callback types not following these conventions should end with `xcb_t`.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Can we figure out a new name for this component as suggested [here](https://github.com/lvgl/lvgl/pull/4121#issuecomment-1529482192)? I think `sysmon` could be a better, less generic name.

**Comment by FASTSHIFT** [comment]
> Can we figure out a new name for this component as suggested [here](https://github.com/lvgl/lvgl/pull/4121#issuecomment-1529482192)? I think `sysmon` could be a better, less generic name.

These are some of the names ChatGPT suggested:

PerformanceTracker
MetricsCollector
ResourceMonitor
EfficiencyObserver
Speedometer
HealthCheck
OptimizationInspector
CapacityWatcher
UtilizationAnalyzer
WorkloadProfiler
What about `lv_metrics`?

**Comment by kisvegabor** [comment]
> These are some of the names ChatGPT suggested:

Just out of curiosity, what was the prompt?

> What about lv_metrics?

I'm ok with that.

**Comment by FASTSHIFT** [comment]
> > These are some of the names ChatGPT suggested:
> 
> Just out of curiosity, what was the prompt?
> 
> > What about lv_metrics?
> 
> I'm ok with that.

I am using the Chinese prompt, after trying to translate into English:
> I implemented a performance monitor component. What could I call it other than Monitor.

 I asked again, and here is its new recommendation:
1. Observer
2. Tracker
3. Inspector
4. Sentinel
5. Watcher
6. Auditor
7. Examiner
8. Surveyor
9. Analyzer
10. Evaluator

**Comment by kisvegabor** [comment]
> I asked again, and here is its new recommendation:

These are good, but IMO not really good. Let's ask a native speaker :smile: 
@kdschlosser Do you have any idea how to name a generic widget that is used for the FPS and memory usage indicators? 
image

Now it's called monitor but it's confusing a little bit.

**Comment by kisvegabor** [comment]
I have an idea! `lv_stat`? 
But TBH `lv_metrics` sounds better. :smile:

**Comment by kdschlosser** [comment]
resource monitor
system information

**Comment by kdschlosser** [comment]
system resources
performance monitor
asset monitor
system load


something you  you should add is the bits per second the frame buffer is being written to the display. All that has to be done is the size of the buffer needs to be saved and the time when the flush callback gets called. the stop time is when the flush ready function gets called. FPS is a number that can be altered by buffer sizes. How fast the frame buffer is being written is very useful to see where a bottle neck might be.

**Comment by kdschlosser** [comment]
lv_perfmon "performance monitor"

**Comment by FASTSHIFT** [comment]
> I have an idea! `lv_stat`? But TBH `lv_metrics` sounds better. 😄

`lv_stat` seems better because it sounds louder and shorter.😄

**Comment by FASTSHIFT** [comment]
> lv_perfmon "performance monitor"

D8 7X4 6U_93CP14TS1ZJU4

Can memory monitoring also be called "performance monitor"? Users can also add any data they want to monitor.

**Comment by FASTSHIFT** [comment]
Why does MP binding CI fail to compile? Is it because of a naming conflict with `stat()`?
image

**Comment by kisvegabor** [comment]
> system information

`lv_sysinfo`?

> Why does MP binding CI fail to compile? Is it because of a naming conflict with stat()?

Don't worry about it, I'll fix in `lv_micropython` when it's merged.

**Comment by FASTSHIFT** [comment]
> `lv_sysinfo`?

or `lv_sysmon`?

> Don't worry about it, I'll fix in `lv_micropython` when it's merged.

OK

**Comment by kisvegabor** [comment]
> or lv_sysmon?

Ok for me.

**Comment by FASTSHIFT** [comment]
> > or lv_sysmon?
> 
> Ok for me.

Done.

**Comment by FASTSHIFT** [comment]
> > or lv_sysmon?
> 
> Ok for me.

Done

**Comment by kisvegabor** [comment]
Looks good, thank you!

**Pull request merged**
