### PR TITLE
add lv_btnm_get_pressed

### PR DESCRIPTION
**Pull request by kisvegabor**
Extend the API of lv_btn with lv_btnm_get_pressed

### CODE REVIEW

**Comment by embeddedt** [comment]
Looks okay, but will the change in `lv_btnm_get_toggled` break old code even though its a bugfix?

**Comment by kisvegabor** [comment]
Yes, it's a bugfix, because `0` is still a valid a button id.

**Comment by kisvegabor** [comment]
@embeddedt Do you agree to merge it?

**Comment by embeddedt** [comment]
@kisvegabor Looks good!

**Pull request merged**
