### PR TITLE
feat(obj): add lv_obj_null_on_delete

### LINKED ISSUE #6571: lv_obj_is_valid() and lv_scr_act() doesnt work
### LVGL version

v9.0.1 / master

### What happened?

Hello,
I have a touchscreen project with multiple displays. I enable the transition between screens with events on the buttons. In the relevant event, I use the lv_screen_load_anim() function with the 'auto_del' parameter set to 'true'. To check which screen I'm on in a different function of the project, I do the following check:
`f (lv_obj_is_valid(ps_screen_audio) == true && lv_scr_act() == ps_screen_audio) {`

Normally, it is expected to enter here only when the active screen is ps_screen_audio, but a different screen that is active 3-4 screens ago and then deleted with 'auto_del' can also pass here.

How can we prevent this problem?

### How to reproduce?

To enter new screen with touch event:
```
static void v_TOUCHEVENT_AudioBack(lv_event_t *e)
{
    lv_indev_wait_release(lv_indev_get_act());
    v_SCREEN_MainInit();
    lv_obj_clean(lv_scr_act());
    lv_screen_load_anim(ps_screen_main, LV_SCR_LOAD_ANIM_NONE, 0, 0, true);
}
```
To check the active screen:
` if (lv_obj_is_valid(ps_screen_main) == true && lv_scr_act() == ps_screen_main) {}`

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

Fixes #6571
Related to #6395

Set an object pointer to `NULL` when it gets deleted.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by W-Mai** [comment]
Will the event still be triggered when obj is deleted?

**Comment by liamHowatt** [comment]
Correct, it will not interfere with the object deletion process. It just sets some external pointer to the object to `NULL`.

**Comment by kisvegabor** [comment]
It's great that you have added this long wanted feature.

Please also mention this new API [here](https://docs.lvgl.io/master/overview/obj.html#create-and-delete-objects).

**Review by kisvegabor — APPROVED** [review]
Thank you! Nice example!

**Review by XuNeo — APPROVED** [review]

**Pull request merged**
