### PR TITLE
Improve compatibility with C++ 14 

### LINKED ISSUE #1837: lv_color1_t is incompatible with C++ versions before C++20
**Describe the bug**

Designated initializers were not supported by the C++ standard before C++20. The following macro in `lv_color.h` depends on a designated initializer:

https://github.com/lvgl/lvgl/blob/fff3a00de241493cb80b260bed18cd622e809644/src/lv_misc/lv_color.h#L629

**To Reproduce**

Attempt to compile LVGL in 1bpp color mode.

**Expected behavior**

Compilation should succeed without needing to use C++20 mode.

**Additional context**

Originally reported here: https://forum.lvgl.io/t/use-lvgl-with-c/3410/3?u=embeddedt

Because `lv_color1_t` is a union I'm not sure how we would go about fixing this. Versions of C++ before C++20 seem to use C89 initializer semantics, meaning that we can only initialize the first member of a union.

### PR DESCRIPTION
**Pull request by kolotoff**
Here two small fix:
1) MSVC 2019 compiler error "C2397 conversion from 'int' to 'uint8_t' requires a narrowing conversion" introduced by Fix #1837
2) Remove last designated initializers in lv_color_mix_with_alpha

This fix tested with Microsoft Visual Studio 2019 16.7.5(C++14, 17, 20), IAR 8.50.6, Keil v5.31(ARM Compiler V6)

### CODE REVIEW

**Comment by kolotoff** [comment]
Found strange behavior with IAR and color depth 1, please wait for my fix

**Comment by embeddedt** [comment]
I had a sneaking suspicion when I wrote "last designated initializer" that another one would show up before long. It turns out I was right. :laughing:

**Comment by kisvegabor** [comment]
Huh, it gets crazy with the differences between Visual Studio, IAR, Keil, Cpp. 

Anyway, it looks good to me, but we can't test it with all the compilers. So hopefully it still fine the others too.

**Comment by kolotoff** [comment]
@embeddedt, Hope, I have removed the "last designated initializer". But, I'm not sure too)

**Comment by kolotoff** [comment]
@kisvegabor please, pay attention to lv_color1_t, the field "full" moved to begin of struct.
I got strange case in IAR: second bit of .full was always 1 with initialization via lv_color_make function.
Now, the problem solved, you can merge it

**Comment by embeddedt** [comment]
Thanks - hopefully we have solved all the outstanding C++ issues now.

**Comment by kisvegabor** [comment]
>  please, pay attention to lv_color1_t, the field "full" moved to begin of struct.

Yes, I've noticed that and it looks like a good idea. 

Thank you for the PR!

**Pull request merged**
