### PR TITLE
fix(calendar): fix lv_calendar_gregorian_to_chinese compile error

### LINKED ISSUE #6892: lv_calendar_chinese.h(47,23): error C2526: “lv_calendar_gregorian_to_chinese”: C 链接函数无法返回 C++ 类“_lv_calendar_chinese_t”
### LVGL version

9.3

### What happened?

mvs compile：
lv_calendar_chinese.h(47,23): error C2526: “lv_calendar_gregorian_to_chinese”: C link can not reture  C++ class“_lv_calendar_chinese_t”

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by lhdjply**
fix(calendar): fix lv_calendar_gregorian_to_chinese compile error

Fixes #6892

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — DISMISSED** [review]
Thanks!

**Comment by lhdjply** [comment]
@xinsuinizhuan

**Comment by xinsuinizhuan** [comment]
> @xinsuinizhuan

ok. the master could not commit?

**Comment by lhdjply** [comment]
> > @xinsuinizhuan
> 
> ok. the master could not commit?

？？？？？？
Isn't this submitting a merge request to the master? Please first understand what a pull request is.

**Review by kisvegabor — APPROVED** [review]
Thank you!

**Review by liamHowatt — APPROVED** [review]

**Pull request merged**
