### PR TITLE
Add animations to switch control

### LINKED ISSUE #549: Animations on switch control
I'm interested in adding animation to the switch control, somewhat like what you see in this picture.

kcod

Would this be a viable feature for `dev-5.3`?

### PR DESCRIPTION
**Pull request by embeddedt**
This pull request adds support for an animated switch control. It resolves #549.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

I tried your code and found some parts where it can be simplified. Meanwhile, I played with it something wasn't clear to me. So far the switch supported to drag the knob to the opposite position. I'm sure it's a must-have feature. Clicking on it is is more natural. In fact, removing this feature would simplify things further. What do you think?

**Comment by embeddedt** [comment]
@kisvegabor I'm not sure exactly what you are asking. Which method of interaction do you propose to remove? In real life you physically have to slide the switch. I'm sure many users will just click it though.

**Comment by kisvegabor** [comment]
> So far the switch supported to drag the knob to the opposite position. I'm sure it's a must-have feature. Clicking on it is is more natural. 

Sorry, I meant to write:  I'm sure it's **not** a must-have feature.  

So I suggest to removing the support of sliding. What do you think?

**Comment by embeddedt** [comment]
@kisvegabor I would prefer to keep sliding support because other smartphone platforms support using a switch in that manner. If sliding support is removed, however, it would have be removed for switches with and without animations. Currently switches without animations still support sliding. Are you okay with that inconsistency?

> I tried your code and found some parts where it can be simplified.

I was expecting that. :smiley: I hadn't quite finished cleaning it up yet, but I wanted to see if you liked the behavior.

**Comment by kisvegabor** [comment]
I pushed my proposed simplifications. I also found a bug when I tried to repeatedly click on the minimum value. In this case, the switch should change state but it didn't work for me.

My changes are mainly about the animation. The key thing is `lv_anim_create` automatically deletes the same animation if exits so you don't have to use an `lv_anim_t` variable to keep track with it. In addition, I tried to use `LV_SWITCH_SLIDER_ANIM_MAX` range even if the animation is disabled.

One thing still not working for me properly.:
1. The switch is in min. state
2. I click on min. state
3. The switch animates to max
4. Click the min again
5. The switch jumps there immediately.


IMO we should avoid this fast changes and it should be animated.

Video: [sw.mp4.zip](https://github.com/littlevgl/lvgl/files/2593934/sw.mp4.zip)

**Comment by embeddedt** [comment]
@kisvegabor You are correct. I investigated and this is caused by the fact that the switch is based on a slider. I tried to fix this before by immediately changing the slider value so that the user wouldn't see it, but it didn't look right and doesn't seem to function anymore.

How would you suggest fixing this behavior? Should I prevent click messages from ever reaching the slider?

**Comment by kisvegabor** [comment]
Hi,

It's really not so simple to solve this. I saved the pressed x coordinate to see if an explicit slide happened.
[sw2.mp4.zip](https://github.com/littlevgl/lvgl/files/2598373/sw2.mp4.zip)
What do you think?

I noticed that the API needs to be extended with `lv_sw_on/off_anim` else there would be no way to set the state immediately. In `v6.0` it should be changed to `lv_sw_on(sw, anim_en)`. Do you agree?

.

**Comment by embeddedt** [comment]
@kisvegabor That is a great solution! I apologize for not thinking of it earlier. It looks like your corner case is resolved by that.

At the moment, yes, I think it would be better to add a new function.

**Comment by kisvegabor** [comment]
Great! :)
Then I think this feature is ready! Do you agree to merge it?

**Comment by embeddedt** [comment]
@kisvegabor Glad to hear that! Merging now. Thanks for the help resolving the issues.

**Comment by kisvegabor** [comment]
@embeddedt I also thank you for this great improvement!

**Pull request merged**
