### PR TITLE
docs(global): fixes

### PR DESCRIPTION
**Pull request by becseya**
This PR contains formal docs fixes of #6367 as errors unrelated to FS were found.
It also introduces a CI workflow that checks for these kinds of error in the future.

### CODE REVIEW

**Comment by kisvegabor** [comment]
It shouldn't required in light of @kdschlosser and @vwheeler63's [updates](https://github.com/lvgl/lvgl/issues/6480). Could you confirm it?

**Comment by vwheeler63** [comment]
Hi, Gabor and @becseya !  ( @kisvegabor )

Good question.  And I have a thorough answer here.  Kevin (@kdschlosser ) has done major re-working of `build.py` (and I hope he submits his PR soon as he made a lot of changes to LVGL source files as well that would be helpful to have in what I am doing).  However, the change I see (adding argument `skip_doxy` to bypass running Doxygen) I do not believe is a feasible change since the whole data flow (per my understanding) goes like this:

```
`Doxygen` (XML output) ==> `breathe` ==> `sphinx` ==> LVGL HTML documentation
```

so running of Doxygen is mandatory.  I do not think Doxygen's HTML output is used in the final documentation however.  And I see that Kevin (in the branch he is working on) has turned off the `GENERATE_HTML` Doxygen configuration value from `YES` to `NO`.  So once Kevin submits his PR, that appears to fulfill the intended result.  It would be good to confirm what I have said here with @kdschlosser .  My view of Kevin's work is `kdschlosser/lvgl` repository, not from his local workstation, so my information may be out of date.

As for the changes in the .RST files, I had a close look at these, and they are all fine and will not create merge conflicts with Kevin's (as-yet-unsubmitted) work -- with the following exceptions here which should be removed from this PR so as not to cause merge conflicts.  Reason stated next to each case and the last would be best for @becseya and @kdschlosser to coordinate since they both appear to have legitimate changes in the same line:

- `./docs/porting/display.rst` should be withdrawn from this PR.  Reason:  Kevin did a major re-work of this file and caught the 2 spaces you correctly inserted already.

- `./docs/porting/indev.rst` should be withdrawn from this PR.  Reason:  Kevin did a major re-work of this file and already caught the space you correctly removed.

-`./docs/widgets/image.rst` should be withdrawn from this PR, but needs coordination between @becseya and @kdschlosser because both of you changed that same line in different ways.  I suggest Kevin have a look at it and (if still applicable) apply @becseya 's change into your submission.  In @becseya 's version:

```
:cpp:expr:`LV_IMAGE_DECLARE(converted_img_var)`.
```

and in Kevin's version (what he has pushed to his `kdschlosser/lvgl` repo):

```
:c:macro:`LV_IMAGE_DECLARE`.
```

and the original (currently in `lvgl/master` branch):

```
:cpp:macro:`LV_IMAGE_DECLARE(converted_img_var)`.
```

Note to @kdschlosser :  @becseya changed `:cpp:macro:...` to `:cpp:expr:...`.  Assuming your change from `cpp` to `c` is correct, and becseya's change from `macro` to `expr` is correct, then it looks like it should be `:c:expr:...`?  I leave that to sort out between you two.

Kind regards,
Vic

**Comment by kdschlosser** [comment]
you are correct that the HTML output from doxygen is not used at all. The only thing that is used are the XML files it generates. Everything that gets generated only for the purpose of building the documentation gets placed into a temp directory and cleaned up once the build finishes. The "out_html" folder that gets created is the documentation that was built.

To comment about the turning off of doxygen. this is not able to be done. @vwheeler63 's outline of how the build is done is 100% correct. doxygen is a requirement and cannot be turned off.

**Comment by becseya** [comment]
it is not required in the light of 6480

**Pull request closed without merging**
