### PR TITLE
feat(refr): support REAL FPS mode

### PR DESCRIPTION
**Pull request by shuai132**
### Description of the feature or fix

1. no need volatile
2. calculate FPS should from last draw end to this draw end. **AND SHOULD NOT use begin to end of one draw .**

BTW, a lot of demo declare it's HIGH FPS, which was wrong in fact, because the FPS showing is not correct.

Details:
* before(wrong FPS):
800FPS is not possible! and which not equals/close to 30FPS below. And 30FPS on the bottom right is alway 30!!!

image

* after:
~28FPS on my laptop.

image

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by GorgonMeducer** [comment]
I cannot agree with this idea:
> calculate FPS should from last draw end to this draw end. AND SHOULD NOT use begin to end of one draw .

The measurement's purpose is to evaluate the performance of LVGL but not the whole embedded system. When you start from "the last draw end to this draw end", the whole embedded system latency is involved, introducing a lot of external noise into the performance evaluation of LVGL. 

In fact, we even introduced a method to remove the latency introduced by the LCD driver (i.e. `disp_flush`) in the benchmark project. 

Image that someone reports a performance-related issue, we will kindly ask he/she to run the benchmark project and show us the result. If rather than concentrating on measuring the performance of LVGL but measuring the performance of the whole software system, we have to either 1) ask he/she to use a standard environment/platform (RTOS or bare-metal) and/or 2) unnecessarily ask for more information about the whole software environment. 

Obviously, this is not good for locating the issue or understanding the potential problem.

**Comment by shuai132** [comment]
>  The measurement's purpose is to evaluate the performance of LVGL but not the whole embedded system. 

As you mentioned, there are indeed reasons to only measure FPS for LVGL.
But measuring the real FPS of the entire system is also very useful and necessary. Especially for the real project, it is not meaningful to just look the FPS of LVGL, but also to take into account the impact of other operations on the FPS (noise and LCD driver latency).

for example:
1. Compare the effects of various rendering implementations on FPS
2. Overall FPS performance of the software
3. Want to measure the overall maximum frame rate (including rendering and other logic)

Since both measurements are meaningful, it is recommended to add a configuration item for the user to choose, such as LV_USE_PERF_MONITOR_SYSTEM_FPS in the above submission (of course the definition in config.h is missing)

Then configure LV_DEF_REFR_PERIOD=1 to get a general understanding of system performance.


Finally, I can continue to refine it if needed, otherwise I can close this MR after a further discussion.

**Comment by GorgonMeducer** [comment]
Let's see what @kisvegabor will say.

**Comment by embeddedt** [comment]
I'm not @kisvegabor, but I agree it would be worthwhile to support both options.

**Comment by shuai132** [comment]
Any suggestion？@kisvegabor

**Comment by kisvegabor** [comment]
[Here](https://github.com/lvgl/lvgl/pull/3416#issuecomment-1187571475) we were talking about introducing FAST and VISUAL modes. It makes sense to have a REAL (or so) mode too. 

If someone is interested in it, a PR would be highly appreciated to add these modes.

**Comment by shuai132** [comment]
Yes, the `Real` mode are not only useful for benchmarking, but also important for user products.
This MR is all we need to do! It works both benchmark and user app. It's ready to merge.

Just define `LV_USE_PERF_MONITOR_SYSTEM_FPS` (or `LV_USE_PERF_MONITOR_REAL_FPS` is better?)

I will learn add it to kconfig/v_conf_template.h and commit it later. it will be here:
image

any suggestions? @kisvegabor

**Comment by shuai132** [comment]
By the way, I think `Real` FPS should be enabled by default on LV_USE_MEM_MONITOR.

Because, what most people cared about is the real FPS. But now, it will alway be 33FPS by default, even the code is:
```
while(1) {
  lv_timer_handler();
  my_delay_ms(100);
}
```
Obviously, the real FPS will be ~10.

**Comment by shuai132** [comment]
I open a new PR instead of this one, please review when you have time.
@kisvegabor

**Pull request merged**
