### PR TITLE
fix warning/error with lv_conf.h option

### PR DESCRIPTION
**Pull request by Zaltora**
I found some warning and i fix it when user change some settings in lv_conf.h

I discovered that this function seem do not be used (line 72):
`static void (*px_fp)(lv_coord_t x, lv_coord_t y, const lv_area_t * mask, lv_color_t color, lv_opa_t opa) = lv_rpx;`

It is WIP, don't merge now

### CODE REVIEW

**Comment by kisvegabor** [comment]
Okay, thanks!

**Comment by Zaltora** [comment]
Fix warning and error compilation for theses options:
```
#define USE_LV_ANIMATION    
#define USE_LV_SHADOW      
#define USE_LV_GROUP        
#define USE_LV_GPU         
#define USE_LV_FILESYSTEM      
```
We can disable Filesystem now, Do it before was buggy.
Still WIP

**Comment by kisvegabor** [comment]
Thank you, I will test your updates!

**Comment by Zaltora** [comment]
Didn't found anything else yet. Ready for merge.
Need feedback from your tests.

**Comment by kisvegabor** [comment]
Thank you very much! 
Now I merge it to `beta` test it and write back!

**Comment by kisvegabor** [comment]
Hi,
I tested your changes. They were correct and worked well!
I reviewed the dependencies of object types and fixed them.

Now your changes are released in v5.0.2.

Thank you very much for your contribution!

**Pull request merged**
