### PR TITLE
fix(docs/README.md): reworked to handle several things

### PR DESCRIPTION
**Pull request by vwheeler63**
- Remove horizontal rules as requested.
- Grammar corrected.
- Edited for clarity.
- Artificial line wraps (as `.md` files produce when the internal text is readable) removed, so that line wrapping will occur with browser width.
- Stated requirement for 2 blank lines after lists and code blocks removed as these do not always improve readability.
- 2 blank lines over headings requirement reinforced, since these always improve readability.
- File content examples outdented to left edge to more accurately portray file content.
- Several clarifications and added.
- Precise reStructuredText terms used.
- Error of only one colon after `.. code-block::` directive fixed (all ReST and Sphinx directives other than link targets must have 2 colons).
- "Paragraph" clarified as "Sub Sub Sub Section" since not everyone will know Doxygen's `@paragraph` command marks the lowest-level Doxygen section heading.
- Examples for linking to code in API pages clarified with solutions.

Addresses request expressed by Gábor at end of PR #6916.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.  n/a
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.  n/a
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.  n/a
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).  n/a
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).  n/a
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.  @kisvegabor 
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kissa96 — APPROVED** [review]
LGTM

**Review by kisvegabor — DISMISSED** [review]
:+1:

**Comment by vwheeler63** [comment]
@kisvegabor @liamHowatt 

Good morning/afternoon, Gentlemen!

I realized yesterday when I wrote a "dissertation" in PR #6910 that this document needed to be updated.  Since it only had 1 approval thus far, I thought now was the right time to do it.  However, since the changes did not seem very helpful, I also exported the `.md` file as HTML and have posted it [here.  This is much easier to review to see what it will really look like than in the DIFF.](http://crystal-clear-research.com/for_gabor/demo/README.html).

Thanks in advance for your time.  I think this will help as the updated hyperlink syntax is both flexible and robust (survives documents being moved without breaking links).

Kind regards,
Vic

**Review by kisvegabor — APPROVED** [review]

**Comment by vwheeler63** [comment]
@liamHowatt In case you missed it, [this link](http://crystal-clear-research.com/for_gabor/demo/README.html) lets you look at the final appearance.

**Review by liamHowatt — APPROVED** [review]
It reads very well!

**Comment by vwheeler63** [comment]
> It reads very well!

Thank you, sir!

**Pull request merged**
