### PR TITLE
Test "middle"-decoder

### PR DESCRIPTION
**Pull request by beibean**
PR to test middle decoder as discussed [here](https://forum.littlevgl.com/t/use-middle-decoder-for-images/164).

test_middle_decoder.c file is added with images source font and RLE function

### CODE REVIEW

**Comment by kisvegabor** [comment]
`test_middle_decoder.h` seems missing.

**Comment by beibean** [comment]
> `test_middle_decoder.h` seems missing.

Effectively, I just added source images and RLE function, just for you to use it wherever your want. So, for that test_middle_decoder.c, the header would only declare this function:

```c
extern lv_res_t          ICON_LVGL_runLength  (lv_img_decoder_t * decoder, lv_img_decoder_dsc_t * dsc);
```

**Comment by kisvegabor** [comment]
I've tested and found some issue:
- You need to call the built in open [at the end](https://github.com/littlevgl/lvgl/pull/1136/commits/7e0ab5483f056a9abefd0aecf4afaefdf536ad06#diff-cdc1e06ce44b5344cf1ae89076248fa4R325)
- You need to [tell that](https://github.com/littlevgl/lvgl/pull/1136/commits/7e0ab5483f056a9abefd0aecf4afaefdf536ad06#diff-cdc1e06ce44b5344cf1ae89076248fa4R242) you can't process INDEXED_4 format to let it to built-in functions
- I replaced the `BOOL_E` types with `bool` to compile it.

Now it works well for me:
```c
    lv_img_decoder_t * decoder = lv_img_decoder_create();
    lv_img_decoder_set_open_cb(decoder, ICON_LVGL_runLength);
    lv_img_decoder_set_info_cb(decoder, lv_img_decoder_built_in_info);
    lv_img_decoder_set_read_line_cb(decoder, lv_img_decoder_built_in_read_line);
    lv_img_decoder_set_close_cb(decoder, lv_img_decoder_built_in_close);

    extern const lv_img_dsc_t RLE_ICONS[];
    lv_obj_t * img = lv_img_create(lv_scr_act(), NULL);
    lv_img_set_src(img, &RLE_ICONS[0]);


    extern const lv_img_dsc_t LVGL_GRADIENT_image[];
    img = lv_img_create(lv_scr_act(), NULL);
    lv_img_set_src(img, &LVGL_GRADIENT_image[1]);
    lv_obj_set_pos(img, 30, 30);
```
image

**Comment by beibean** [comment]
> You need to tell that you can't process INDEXED_4 format to let it to built-in functions

Making this change works perfect for me. 😉 

> You need to call the built in open at the end

This is working for me without making call to the function 

```c
lv_img_decoder_built_in_open(decoder, dsc);
```
once RLE de-compression is finished.

Do you know why could this be possible? 
Maybe because of the change from ```c LV_IMG_CF_USER_ENCODED_0 to LV_IMG_CF_ALPHA_4BIT```. 

I do not fully understand the image drawing flow, but it seems reasonable what you purpose.

> I replaced the BOOL_E types with bool to compile it.

Sorry for that, I am used to use BOOL_E enum and did not realize.

**Comment by kisvegabor** [comment]
> Making this change works perfect for me. wink

Great! :slightly_smiling_face: 
I'll integrate the changes in master soon.

> This is working for me without making call to the function ...

Actually, it's really possible because `lv_img_decoder_built_in_open` does nothing with ALPHA_X images. While I was trying to finding the issues I added it because it is logical to really open the image the preprocessed image. 

> Sorry for that, I am used to use BOOL_E enum and did not realize.

No problem.

**Comment by beibean** [comment]
> Actually, it's really possible because lv_img_decoder_built_in_open does nothing with ALPHA_X images. While I was trying to finding the issues I added it because it is logical to really open the image the preprocessed image.

That is why, now I understand.


Feel free to merge any changes you want and make changes yourself!

**Comment by kisvegabor** [comment]
I update the `master` manually.

One thing has changed: you need to add a custom info function too because from now the built-in supports only the built-in formats. 
It worked for me:
```c
lv_res_t ICON_LVGL_runLength_info(lv_img_decoder_t * decoder, const void * src, lv_img_header_t * header)
{
    (void)decoder; /*Unused*/

    lv_img_src_t src_type = lv_img_src_get_type(src);
    if(src_type == LV_IMG_SRC_VARIABLE) {
        lv_img_cf_t cf = ((lv_img_dsc_t *)src)->header.cf;
        if(cf != LV_IMG_CF_USER_ENCODED_0) return LV_RES_INV;

        header->w  = ((lv_img_dsc_t *)src)->header.w;
        header->h  = ((lv_img_dsc_t *)src)->header.h;
        header->cf = ((lv_img_dsc_t *)src)->header.cf;
        return LV_RES_OK;
    } else {
        return LV_RES_INV;
    }
}
```
  
Can you test it with the lates master?

**Comment by beibean** [comment]
Seems perfect to me 👍  

I can't test it until monday though. I'll let you know then.

**Comment by beibean** [comment]
Working perfect 👍

I close the pull request.

Thanks!

**Comment by kisvegabor** [comment]
Awesome! Thank you for the feedback!

**Pull request closed without merging**
