### PR TITLE
Tileview: new object type

### PR DESCRIPTION
**Pull request by kisvegabor**
This a new object type called tileview. It's a container which can be used well on small displays, e.g. on smart-watches.
tileview

Test code:
```c
void tileview_test(void)
{
    static const lv_point_t vp[] = {
                   {1,0},          /*First row: only the middle tile*/
            {0,1}, {1,1}, {1,2},   /*Second row: all tree tiles */
                   {2,1}, {2,2},   /*Third row: middle and right tile*/
            {LV_COORD_MIN, LV_COORD_MIN}};

    lv_obj_t * t;
    t = lv_tileview_create(lv_scr_act(), NULL);
    lv_tileview_set_valid_positions(t, vp);
    lv_tileview_set_edge_flash(t, true);

    lv_obj_t * label;

    /*x0, y1 container*/
    lv_obj_t * p01 = lv_obj_create(t, NULL);
    lv_obj_set_click(p01, true);
    lv_obj_set_style(p01, &lv_style_pretty_color);
    lv_obj_set_size(p01, lv_obj_get_width(t), lv_obj_get_height(t));
    lv_tileview_add_element(t, p01);

    /*Add a  button at x0, y1*/
    lv_obj_t * b01 = lv_btn_create(p01, NULL);
    lv_tileview_add_element(t, b01);
    lv_obj_align(b01, NULL, LV_ALIGN_CENTER, 0, 50);
    label = lv_label_create(b01, NULL);
    lv_label_set_text(label, "Button");

    /*Add a label to indicate the position*/
    label = lv_label_create(p01, NULL);
    lv_label_set_text(label, "x0, y1");
    lv_obj_align(label, NULL, LV_ALIGN_CENTER, 0, 0);

    /*x1, y1 container*/
    lv_obj_t * p11 = lv_obj_create(t, p01);
    lv_obj_align(p11, p01, LV_ALIGN_OUT_RIGHT_MID, 0, 0);
    lv_tileview_add_element(t, p11);

    /*Add a label to indicate the position*/
    label = lv_label_create(p11, NULL);
    lv_label_set_text(label, "x1, y1");
    lv_obj_align(label, NULL, LV_ALIGN_CENTER, 0, 0);

    /*x1, y2 list*/
    lv_obj_t * list12 = lv_list_create(t, NULL);
    lv_obj_set_size(list12, LV_HOR_RES, LV_VER_RES);
    lv_obj_align(list12, p11, LV_ALIGN_OUT_BOTTOM_MID, 0, 0);
    lv_list_set_scroll_propagation(list12, true);
    lv_tileview_add_element(t, list12);

    lv_obj_t * list_btn;
    list_btn = lv_list_add(list12, NULL, "One", NULL);
    lv_tileview_add_element(t, list_btn);

    list_btn = lv_list_add(list12, NULL, "Two", NULL);
    lv_tileview_add_element(t, list_btn);

    list_btn = lv_list_add(list12, NULL, "Three", NULL);
    lv_tileview_add_element(t, list_btn);

    list_btn = lv_list_add(list12, NULL, "Four", NULL);
    lv_tileview_add_element(t, list_btn);

    list_btn = lv_list_add(list12, NULL, "Five", NULL);
    lv_tileview_add_element(t, list_btn);

    list_btn = lv_list_add(list12, NULL, "Six", NULL);
    lv_tileview_add_element(t, list_btn);

    list_btn = lv_list_add(list12, NULL, "Seven", NULL);
    lv_tileview_add_element(t, list_btn);

    /*x1, y0 container*/
    lv_obj_t * p10 = lv_obj_create(t, p01);
    lv_tileview_add_element(t, p10);

    /*Add a label to indicate the position*/
    label = lv_label_create(p10, NULL);
    lv_label_set_text(label, "x1, y0");
    lv_obj_align(label, NULL, LV_ALIGN_CENTER, 0, 0);
    lv_obj_align(p10, p11, LV_ALIGN_OUT_TOP_MID, 0, 0);

    /*x2, y1 container*/
    lv_obj_t * p21 = lv_obj_create(t, p01);
    lv_tileview_add_element(t, p21);
    lv_obj_align(p21, p11, LV_ALIGN_OUT_RIGHT_MID, 0, 0);

    /*Add a label to indicate the position*/
    label = lv_label_create(p21, NULL);
    lv_label_set_text(label, "x2, y1");
    lv_obj_align(label, NULL, LV_ALIGN_CENTER, 0, 0);

    /*x2, y1 container*/
    lv_obj_t * p22 = lv_obj_create(t, p01);
    lv_tileview_add_element(t, p22);
    lv_obj_align(p22, p21, LV_ALIGN_OUT_BOTTOM_MID, 0, 0);

    /*Add a label to indicate the position*/
    label = lv_label_create(p22, NULL);
    lv_label_set_text(label, "x2, y2");
    lv_obj_align(label, NULL, LV_ALIGN_CENTER, 0, 0);

    /*Focus on a tile (the list)*/
    lv_tileview_set_tile_act(t, 1, 2, true);
}

```

### CODE REVIEW

**Comment by embeddedt** [comment]
It appears that you have mixed some commits from #584 in with this pull request.

**Comment by kisvegabor** [comment]
@embeddedt Yes, I used the "edge flash" feature in the tileview too. Is it a problem to mix commit this way? By the way, what do you think, how long should I wait to merge my own PR if don't get feedback? How shall we manage this? 5 or 7 days?

**Comment by kisvegabor** [comment]
> @kisvegabor To be honest with you, I think you should just merge your own PRs right away. Since they are not being merged to master but instead to dev-5.3, they will still get tested and people can always open new issues.

Okay, I will do this way. It will prevent the cases like this in the future.

**Comment by kisvegabor** [comment]
GitHub was smart. When I merged this PR, GitHub saw that page_flash's commits were merged too so marked that PR as merged.

**Comment by embeddedt** [comment]
@kisvegabor That's actually pretty neat! That should help prevent any conflicts in the future.

**Pull request merged**
