### PR TITLE
fix(theme_default):  fix omitted style for selected text in `lv_textarea`

### LINKED ISSUE #7321: Text Selection in TextArea Not Showing Up
### LVGL version

v9.3

### Platform

Visual Studio in `lvgl/lv_port_pc_visual_studio` project

### What happened?

The code in `lv_label` shows that it is able to *show* selected text, but leaves it up to client software to cause selected text to "happen".  `lv_textarea` contains those behaviors and automates a basic subset of behaviors for selecting text with a `pointer` type input device.  However, using `lv_example_textarea_1()`, I could not get any selected text to show up, no matter what I tried.

Example:  in a Text-Area Widget, with cursor here::
```
     [ABCD|EFGHIJKLMNOP]
          ^
```
dragging to the left or to the right did not make any selected text appear.

Gábor (@kisvegabor) discovered this "seeming" omission was not because there was no "selected text", but it was because a style different from the existing text had not been set for the `LV_PART_SELECTED` part in the default theme.  I will submit a PR shortly that includes the fix for that.

### How to reproduce?

In `lvgl/lv_port_pc_visual_studio` repository, run the `lv_example_textarea_1()` example.

### PR DESCRIPTION
**Pull request by vwheeler63**
Selected text, even though it existed, was not showing up in TextArea examples.  The bug was merely a style to show the text as selected was omitted from the Default Theme -- remedied with this PR.

Credit goes to @kisvegabor for finding the cause.

Resolves #7321

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.  n/a
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.  n/a
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.  n/a
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).  n/a
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).  Done.
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.  Done.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.  Done.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by kisvegabor — APPROVED** [review]
Thank you Vic!

**Comment by liamHowatt** [comment]
Sorry, I'm trying to verify the fix. Should it be possible in `lv_example_textarea_1` to select text in the textarea with this fix? I can't seem to get the text to be selected with my pointer indev. It would be good to have this.

**Comment by vwheeler63** [comment]
> Sorry, I'm trying to verify the fix. Should it be possible in `lv_example_textarea_1` to select text in the textarea with this fix? I can't seem to get the text to be selected with my pointer indev. It would be good to have this.

Hi, @liamHowatt !

That example wasn't meant to have text selected, but if you want to set it up as a test environment, you merely need to add this line of code somewhere after the `lv_textarea_t` object is created:
```c
    lv_textarea_set_text_selection(ta, true);
```

**Comment by vwheeler63** [comment]
> We should rather write a simple screen shot compare test for it [here](https://github.com/lvgl/lvgl/blob/master/tests/src/test_cases/widgets/test_textarea.c).

Excellent idea!  Is there a project going on to implement TDD in LVGL?  I see a lot of tests being added, and I find it encouraging!  (I've worked on projects where there is a thorough test bed, and they were wonderful to work with and added so much certainty at release time!)

**Comment by kisvegabor** [comment]
It's not test driven but we at least test what we already have and what we newly add.

**Comment by uLipe** [comment]
Just a very minor comment, The two commits are necessary? style fixing at the part of the code changed it is implicitly part of the commit scope.

I suggest to squash into a single commit, and if needed mention in the commit body the style fix.

**Comment by vwheeler63** [comment]
> I suggest to squash into a single commit, and if needed mention in the commit body the style fix.

It is my understanding that when this is merged it effectively does squash the 2 commits together.  Then this branch is deleted and `git` will eventually clean up (i.e. delete) those 2 commits after a while since the reference to them (the branch) is gone.  So at the moment, it is simply a record of that fact that I forgot to run `code-format.py` locally and only found out about the problem after I submitted the first commit.

**Comment by vwheeler63** [comment]
> It's not test driven but we at least test what we already have and what we newly add.

Hi, Gábor!

I had a situation today where I needed to update one of the tests — specifically `test_scale.c` and I could not find what calls these tests.  The code I added I tested elsewhere (in one of the `scale` examples) so I know it works, but still it would be nice to be able to utilize these.  Can you advise?

**Comment by kisvegabor** [comment]
> I suggest to squash into a single commit, and if needed mention in the commit body the style fix.

Unless it's explicitly requested by the author of  PR we squash the PRs anyways. 

> I had a situation today where I needed to update one of the tests — specifically test_scale.c and I could not find what calls these tests. The code I added I tested elsewhere (in one of the scale examples) so I know it works, but still it would be nice to be able to utilize these. Can you advise?

You can run the tests locally like this:
```
cd tests
./main.py test
```

See more info [here](https://github.com/lvgl/lvgl/tree/master/tests#readme).

**Comment by vwheeler63** [comment]
> You can run the tests locally like this:

Thank you!

**Comment by kisvegabor** [comment]
Did it work?

**Review by uLipe — APPROVED** [review]

**Comment by kisvegabor** [comment]
I recommend using WSL under Windows. :slightly_frowning_face:

**Review by liamHowatt — APPROVED** [review]
> ```c
>     lv_textarea_set_text_selection(ta, true);
> ```

Of course. Thank you. I promise I tried to find this API before I asked.

Great find and great solution.

**Comment by vwheeler63** [comment]
> I recommend using WSL under Windows.

Got it.  Thank you!  One of these days I'm gonna have to break out my Ubuntu WSL....

**Pull request merged**
