### PR TITLE
Fix image zooming causes unexpected object size.

### PR DESCRIPTION
**Pull request by XuNeo**
Related to issue #2283

### CODE REVIEW

**Comment by embeddedt** [comment]
I'm not sure if we can take this fix now, as 8.0 has been released, and a change like this in 8.1 would break backwards compatibility.

**Comment by kisvegabor** [comment]
Thank you! I tested the latest changes and found this issue:

On press the zoom is not symmetrical and the image is not repeated. It's repeated with `zoom = 400` but still asymetric.
```c  
lv_obj_t* obj = lv_obj_create(lv_scr_act());
lv_obj_set_size(obj, 250, 250);
lv_obj_set_flex_flow(obj, LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(obj, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

lv_obj_t* img = lv_img_create(obj);
lv_img_set_src(img, &img_clothes);
lv_obj_set_style_bg_color(img, lv_color_black(), 0);
lv_obj_set_style_bg_opa(img, LV_OPA_COVER, 0);
lv_obj_set_style_transform_zoom(img, 450, LV_STATE_PRESSED);
lv_obj_add_flag(img, LV_OBJ_FLAG_CLICKABLE);
lv_obj_set_size(img, 100, 100);
```
i1

**Comment by kisvegabor** [comment]
I've pushed a fix to make LVGL automatically detect size change. So it's not required to send `LV_EVENT_SIZE_CHANGED` manually.

**Comment by embeddedt** [comment]
Hopefully https://github.com/lvgl/lvgl/commit/27d88de899e91cd5bb9fc69fe9d71cb180cfb44b silences Codecov; my previous fix didn't work for some reason.

**Comment by XuNeo** [comment]
Thanks Gabor, I have fixed the issue you pointed out.
The zoomed image is always repeated when object size is larger than image, starts from left up corner.
zoom-compressed

**Comment by kisvegabor** [comment]
Sorry for the late reply. I've tested the latest version and it worked well!

I've pushed some minor fixes and refactoring.  Do you agree with them?

**Comment by XuNeo** [comment]
Thanks Gabor. I agree, please go ahead.

**Comment by kisvegabor** [comment]
Great! I've just updated the docs and merged.

Thank you very much!

**Pull request merged**
