### PR TITLE
update my dev fork

### PR DESCRIPTION
**Pull request by pete-pjb**

### CODE REVIEW

**Comment by embeddedt** [comment]
@pete-pjb Hmm.. we already merged the previous PR. I don't think there are any new commits in this one, am I correct?

**Comment by pete-pjb** [comment]
HI @embeddedt,

Sorry this was a mistake! can you delete it...

You merged the last PR before I had finished updating from Gabors comments.  I was trying to update my fork to do another PR and I have accidentally got the pull request the wrong way around.  I'm an idiot sorry!!!

**Comment by embeddedt** [comment]
> I'm an idiot sorry!!!

No problem. It happens to all of us. :slightly_smiling_face:

**Comment by kisvegabor** [comment]
> I'm an idiot sorry!!!

Don't worry, nothing wrong has happened. :slightly_frowning_face: 

I updated `dev` from `master`. The chart fix should be there. Please file a new PR based on `dev`.

**Comment by pete-pjb** [comment]
Thanks for your patience @embeddedt and @kisvegabor,  I will get the new PR sorted shortly. 😊

**Pull request closed without merging**
