### PR TITLE
feat(refr): add backward compatibility for LV_COLOR_16_SWAP

### LINKED ISSUE #6104: Add back CONFIG_LV_COLOR_16_SWAP
### Introduce the problem

While migrating all existing project using lvgl on Nuttx, https://github.com/apache/nuttx/pull/11780, many configurations have enabled CONFIG_LV_COLOR_16_SWAP. It may be a common issue others will face too.

```bash
nuttx/boards/risc-v/esp32c3-legacy/esp32c3-devkit/configs/lvgl/defconfig:38:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32/esp32-2432S028/configs/lvgl/defconfig:39:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32/esp32-wrover-kit/configs/lvgl/defconfig:44:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32s2/esp32s2-kaluga-1/configs/lvgl_ili9341/defconfig:42:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32s2/esp32s2-kaluga-1/configs/lvgl_st7789/defconfig:44:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32s3/esp32s3-box/configs/lvgl-3/defconfig:56:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32s3/esp32s3-box/configs/lvgl/defconfig:59:CONFIG_LV_COLOR_16_SWAP=y
nuttx/boards/xtensa/esp32/ttgo_t_display_esp32/configs/lvgl_lcd/defconfig:45:CONFIG_LV_COLOR_16_SWAP=y
nuttx/defconfig:39:CONFIG_LV_COLOR_16_SWAP=y
```

### Proposal

Add equivalent configuration option `CONFIG_LV_COLOR_16_SW_SWAP` that does the swap by software just before `flush_cb` by calling `lv_draw_sw_rgb565_swap`.

Update existing configuration to use `CONFIG_LV_COLOR_16_SW_SWAP` instead.

### PR DESCRIPTION
**Pull request by kisvegabor**
fixes #6104

### Description of the feature or fix

A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by XuNeo** [comment]
Thank you Gabor. Should we also add `LV_COLOR_16_SWAP` option to lv_conf.h and Kconfig?

**Review by PGNetHun — APPROVED** [review]
Thanks. Will it remain in future too?

**Comment by kisvegabor** [comment]
> Should we also add LV_COLOR_16_SWAP option to lv_conf.h and Kconfig?

My understanding was the goals of this update is to make previous drivers and configs work with v9 too. In light of that, I wouldn't add it the config files in v9 because this way people probably will start using it again. If it's really needed the users can add it manually (or it will be picked up from the old configs) What do you think?

> Thanks. Will it remain in future too?

We can leave it for a major versions. Maybe adding a `#warning` could be useful too.

**Review by liamHowatt — APPROVED** [review]

**Comment by kisvegabor** [comment]
Merging it now. @XuNeo let me know you think we need to do more with it.

**Pull request merged**
