### PR TITLE
Espressif IDF component manager

### PR DESCRIPTION
**Pull request by tore-espressif**
### Description of the feature or fix
This PR adds a workflow for automatic upload to Espressif's component service on successful release of new version.

Idf-component-manager is a new function that allows ESP-IDF users to integrate software package into their project seamlessly.
We'd like the LVGL project to be one of the first external components, hosted on our component service.

More information about idf-component manager can be found in [Espressif API guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-component-manager.html) or [PyPi registry](https://pypi.org/project/idf-component-manager/). The component service itself is hosted [here](https://components.espressif.com/).

In order to upload to Espressif's registry, an API token must be added to Github secrets (see [.github/workflows/esp_upload_component.yml  line 19](https://github.com/lvgl/lvgl/blob/b7733e0d0d338ae8ad9d5f890a7cbd6803dfc7ec/.github/workflows/esp_upload_component.yml#L19)), I can send it to you in private message, if you agree.

### Checkpoints
- [x] Add ESP_IDF token to Github secrets

### CODE REVIEW

**Comment by C47D** [comment]
It seems like a great new capability, are you planning to use LVGL as a managed component on the lv_port_esp32 project? I guess it could be possible to upload the last v7 version of LVGL as well as the latest?

**Comment by kisvegabor** [comment]
> We'd like the LVGL project to be one of the first external components, hosted on our component service.

It would be great :) 

> In order to upload to Espressif's registry, an API token must be added to Github secrets (see .github/workflows/esp_upload_component.yml line 19), I can send it to you in private message, if you agree.

No problem, please send it to gabor@lvgl.io

**Comment by tore-espressif** [comment]
> No problem, please send it to gabor@lvgl.io

Done!

> It seems like a great new capability, are you planning to use LVGL as a managed component on the lv_port_esp32 project?

Yes, we will have a similar PR in https://github.com/lvgl/lvgl_esp32_drivers/ (after we have our 1.0.0 release) and then we can update lv_port_esp32 to use idf-component-manager. (lvgl_esp32_drivers component will require lvgl component).

> I guess it could be possible to upload the last v7 version of LVGL as well as the latest?

Yes, after this PR gets merged, I'll upload v7 and current manually.

**Comment by kisvegabor** [comment]
>> No problem, please send it to gabor@lvgl.io
> Done!

I've added the tokens. Can I merge this PR?

**Comment by tore-espressif** [comment]
Yes, it's ready. We will have to wait for first run until next release though.
I'll keep an eye on it.

**Comment by kisvegabor** [comment]
Great, thank you!

**Comment by tore-espressif** [comment]
Versions 7.11.0 and 8.0.2 uploaded:
https://components.espressif.com/component/lvgl/lvgl

(MIT license is not automatically detected, I'll notify the component-manager team to accept British English Licence.txt too)

**Pull request merged**
