### PR TITLE
decide text animation's direction based on base_dir

### PR DESCRIPTION
**Pull request by KamranAghlami**
This PR is made to remedy #2080's "Files Changed" problem.

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]
@kisvegabor Should this go to v7 or v8?

**Comment by kisvegabor** [comment]
IMO we can consider it as a fix and merge to v7. What do you think?

**Comment by embeddedt** [comment]
Sure; the previous behavior was largely undesirable anyways.

**Comment by KamranAghlami** [comment]
Nice! 
Thanks @kisvegabor & @embeddedt

**Comment by kisvegabor** [comment]
We thank you too! :slightly_smiling_face:

**Pull request merged**
