### PR TITLE
feat(async): add async call after render

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Description of the feature or fix

Related discussion: https://github.com/lvgl/lvgl/issues/3457

### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
I think it solves only one particular issue: do something after rendering. But there can be many others, such as do something
- before rendering
- on display flush ready
- before flushing the display
- when logging something
- etc

So I find solving only this case too specific.

**Comment by FASTSHIFT** [comment]
> I think it solves only one particular issue: do something after rendering. But there can be many others, such as do something
> 
> * before rendering
> * on display flush ready
> * before flushing the display
> * when logging something
> * etc
> 
> So I find solving only this case too specific.

Do you mean to complete these events?

**Comment by kisvegabor** [comment]
I think we should leave to the user to manage these triggers as it works the best in his application.

**Comment by FASTSHIFT** [comment]
> I think we should leave to the user to manage these triggers as it works the best in his application.

Something like this interface? https://github.com/lvgl/lvgl/pull/3274

**Comment by kisvegabor** [comment]
Yes, be already have `monitor_cb` for this scenario.

**Comment by FASTSHIFT** [comment]
I need an event that is not related to whether the render is executed or not, but after the render ends, because obj may be outside the screen, lvgl may not be rendered and will not execute `monitor_cb`.

**Comment by FASTSHIFT** [comment]
Consider using a unified event callback function? 
such as:
`disp_refr->driver->render_start_cb(disp_refr->driver);`
change to
`disp_refr->driver->event_cb(disp_refr->driver, LV_DISP_EVENT_RENDER_START, param);`

**Comment by kisvegabor** [comment]
> Consider using a unified event callback function?

Amazing idea. I was planning to do the same with animations too. Are you interested in sending a PR?

**Comment by FASTSHIFT** [comment]
> > Consider using a unified event callback function?
> 
> Amazing idea. I was planning to do the same with animations too. Are you interested in sending a PR?

Yes, but will it cause the current display porting to change too much?

**Comment by kisvegabor** [comment]
Now we are working on v9. This the time to make breaking changes. :slightly_smiling_face:

**Comment by FASTSHIFT** [comment]
I added `refr_finish_cb` to achieve this effect https://github.com/lvgl/lvgl/pull/3502

**Pull request closed without merging**
