### PR TITLE
Misc(format) repo cleanup

### PR DESCRIPTION
**Pull request by kissa96**
A clear and concise description of what the bug or new feature is.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kissa96** [comment]
@liamHowatt @kisvegabor Giga cleanup commit. Please check. 99% ws changes

**Review by liamHowatt — COMMENTED** [review]
Based on a small sample of files, it looks like the "end of line sequence" was changed for all files which is why it shows so many lines changed. It used to be LF (`\n`) (Unix style line ending) and now is CRLF (`\r\n`) (Windows style line ending). Is there a strong case for one VS the other?

**Comment by kissa96** [comment]
Not really. One can argue that a proper new line is a combination of CR and LF, since TTYs needed both. Nowadays it doesn't matter, as it is handled properly, but still. It remains a topic of constant disagreement. I've specifically let the hooks decide the auto fix, and it looks like CRLF won. But at least now it is uniform everywhere.

**Comment by liamHowatt** [comment]
Since the case isn't strong, probably keep it how it was. It hasn't caused an issue for Windows users from what we've heard so far.

**Comment by kisvegabor** [comment]
>  Since the case isn't strong, probably keep it how it was. It hasn't caused an issue for Windows users from what we've heard so far.

I agree that we shouldn't change 700 files without a strong reason. Please keep using `\n`s.

**Comment by kisvegabor** [comment]
Closing as there is not real issue which is solved by this large scale change.

**Pull request closed without merging**
