### PR TITLE
fix(Makefile): add missing lv_draw_transform and lv_draw_sw_transform

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [ ] Update the documentation

### CODE REVIEW

**Comment by embeddedt** [comment]
Do we need a simple CI runner that confirms the Makefiles work properly?

**Comment by kisvegabor** [comment]
> Do we need a simple CI runner that confirms the Makefiles work properly?

It'd be great. Just a simple build test using `LV_CONF_SKIP` to go with the default settings from `lv_conf_internal.h`

**Comment by embeddedt** [comment]
I've added one.

**Comment by kisvegabor** [comment]
Great! :+1:

**Pull request merged**
