### PR TITLE
action functions for calendar object

### PR DESCRIPTION
**Pull request by ali-rostami**
Add action functions to calendar object so then we can use a calendar as an input for a date.

### CODE REVIEW

**Comment by kisvegabor** [comment]
I mean is there a more user-friendly method to get the pressed data than using 
`lv_calendar_ext_t * ext = lv_obj_get_ext_attr(calendar);`?

**Comment by ali-rostami** [comment]
oh, I didn't think about it.
How about adding fucntion like this:
```c
/**
 * Get the the pressed date.
 * @param calendar pointer to a calendar object
 * @return pointer to an `lv_calendar_date_t` variable containing the pressed date.
 */
lv_calendar_date_t * lv_calendar_get_pressed_date(const lv_obj_t * calendar)
{
    lv_calendar_ext_t * ext = lv_obj_get_ext_attr(calendar);
    return &ext->pressed_date;
}
```
sounds good?

**Comment by kisvegabor** [comment]
Sounds perfect!

**Comment by ali-rostami** [comment]
done:)

**Comment by kisvegabor** [comment]
Awesome!  :)
Thank you for this great feature!

**Pull request merged**
