### PR TITLE
docs(monkey) add monkey missing from toctree

### PR DESCRIPTION
**Pull request by FASTSHIFT**
### Checkpoints
- [x] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [x] Run `code-format.py` from the `scripts` folder. [astyle](http://astyle.sourceforge.net/install.html) needs to be installed.
- [x] Update the documentation

### CODE REVIEW

**Comment by FASTSHIFT** [comment]
@kisvegabor 
Could you please help me check the reason why the online document about monkey has not been updated?

**Comment by kisvegabor** [comment]
It was required to enable the Monkey in [lv_sim_emscripten](https://github.com/lvgl/lv_sim_emscripten) too. 
Now it's there: https://docs.lvgl.io/master/others/monkey.html

It might be more demonstrative if there were some buttons on the screen of the examples. What do you think?

**Comment by FASTSHIFT** [comment]
@kisvegabor 
Can it be used with `lv_demo_widgets()`? like this:
```C
int main(void)
{
    ...
    lv_example_monkey_1();
    lv_demo_widgets();
    while(1) {
        lv_timer_handler();
        delay(5);
    }
}
```

**Comment by kisvegabor** [comment]
> Can it be used with lv_demo_widgets()? like this:

@embeddedt ? :slightly_smiling_face:

**Comment by embeddedt** [comment]
Once `lv_demos` is merged into this repository, yes, because we could just call it from the end of `lv_example_monkey_1`.

At the moment I think it'd be difficult without adding special logic to the build system for this one example.

**Comment by kisvegabor** [comment]
I merged lv_demos to lvgl/master.

More info here: #2900

**Pull request merged**
