### PR TITLE
fix(Windows): use global lock

### LINKED ISSUE #6059: close the frame, break!
### LVGL version

v9.1.1

### What happened?

in windows，when close the pop window，break:
图片
because the disp_refr_timer is NULL in lv_sysmon.c

### How to reproduce?

_No response_

### LINKED ISSUE #6428: Compile Error with Code Blocks 20.03 (solved)
### LVGL version

v9.1.0

### What happened?

I get an compile error from the following branch:
https://github.com/lvgl/lv_port_win_codeblocks

lvgl\src\drivers\windows\lv_windows_context.c|141|error: 'CREATE_WAITABLE_TIMER_MANUAL_RESET' undeclared (first use in this function)|
lvgl\src\drivers\windows\lv_windows_context.c|141|note: each undeclared identifier is reported only once for each function it appears in|
lvgl\src\drivers\windows\lv_windows_context.c|142|error: 'CREATE_WAITABLE_TIMER_HIGH_RESOLUTION' undeclared (first use in this function)|
||=== Build finished: 2 error(s), 4 warning(s) (2 minute(s), 1 second(s)) ===|

### How to reproduce?

add following lines to this file:
lvgl\src\drivers\windows\lv_windows_context.c

 #define CREATE_WAITABLE_TIMER_MANUAL_RESET 1
 #define CREATE_WAITABLE_TIMER_HIGH_RESOLUTION 2

### PR DESCRIPTION
**Pull request by liamHowatt**
### Description of the feature or fix

Fixes #6059

Use the LVGL global lock in the Windows backend to control access to data and LVGL APIs shared with the Windows backend thread message callback.

Prevent memory faults, especially when the display is deleted.

CC @MouriNaruto

Fixes #6428

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by MouriNaruto** [comment]
In my opinion, I hope this PR can reduce the usage of lv_lock and lv_unlock for improving the maintenance work.

Maybe we can lv_lock before the `switch(uMsg)` in `lv_windows_window_message_callback`, and lv_unlock before `return DefWindowProcW(hWnd, uMsg, wParam, lParam);` and `return 0;` in `lv_windows_window_message_callback`

Kenji Mouri

**Comment by MouriNaruto** [comment]
It is still too much. Here is my idea:

- Revert changes in `docs/integration/driver/windows.rst` because there is no synchronization issue before the `lv_timer_handler` loop.
- Revert changes in `src/drivers/windows/lv_windows_context.c`, `src/drivers/windows/lv_windows_display.c`, and `src/drivers/windows/lv_windows_context.h`, and `src/drivers/windows/lv_windows_input.c` because here is my simplified version: 
[lv_windows_changes_20260627.zip](https://github.com/user-attachments/files/16017784/lv_windows_changes_20260627.zip). (It also has the fixes for https://github.com/lvgl/lvgl/issues/6428.)

Kenji Mouri

**Comment by liamHowatt** [comment]
Wow, that is much better. Thank you.

I'm still stubborn about the lock in the user code before the timer loop. After the display is created, the Windows thread is calling the LVGL API. The timer callback is safe because it acquires the lock, and I believe the user code must acquire the lock to be safe too.

**Review by MouriNaruto — APPROVED** [review]

**Review by kisvegabor — APPROVED** [review]
:+1:

**Comment by liamHowatt** [comment]
Whoever merges, please paste this in the extended description. I think that should work.
```
Co-authored-by: Kenji Mouri (Qi Lu) <KurikoMouri@outlook.jp>
```

**Review by FASTSHIFT — APPROVED** [review]

**Pull request merged**
