### PR TITLE
fix(format): remove 0x prefix from %p

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
### Description of the feature or fix

since %p already add this prefix automatically

### Checkpoints
- [X] Follow the [styling guide](https://github.com/lvgl/lvgl/blob/master/docs/CODING_STYLE.md)
- [ ] Update CHANGELOG.md
- [ ] Update the documentation

### CODE REVIEW

**Comment by kisvegabor** [comment]
`printf` really adds it but our `lv_printf` doesn't:
```c
  LV_LOG_USER("%p", main);
  printf("%p\n", main);
```
```
[User]	(0.000)	 main: 0000562A7294FA47 	(in main.c line #82)
0x562a7294fa47
```

We can either
- add 0x prefix to lv_printf ( based on https://github.com/mpaland/printf)
- open an issue in the original repo
- remove the 0x prefix. No prefix is better than 0x0x

What do you think?

**Comment by xiaoxiang781216** [comment]
@kisvegabor I will proide a patch to make `lv_printf` more compatible with the standard.

**Comment by kisvegabor** [comment]
Perfect! :slightly_smiling_face:

**Comment by xiaoxiang781216** [comment]
@kisvegabor please try the new patch.

**Comment by embeddedt** [comment]
According to https://github.com/mpaland/printf/pull/90 `%p` isn't even standardized, however, I would agree that adding the prefix makes more sense.

**Review by embeddedt — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Yes, the output of %p is implemention defined, the change make the output more like glibc's.

**Comment by kisvegabor** [comment]
That was fast! :slightly_smiling_face:
Looks good to me too, merging.

**Pull request merged**
