### PR TITLE
feat(png): add png8 bit support

### PR DESCRIPTION
**Pull request by XuNeo**
### Description of the feature or fix

For hardwares support indexed8 image, decode PNGs with palette to indexed color format, so GPU can use it directly.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.10](https://github.com/szepeviktor/astyle/releases/tag/v3.4.10) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by kisvegabor** [comment]
Good idea! Please add a test, and we are good to go.

**Review by PGNetHun — CHANGES_REQUESTED** [review]
Sorry, but I think we should not change this 3rd party library file (`lodepng.c`) too much, we need to check first whether we can solve our problem with existing library functions.

As I see [lodepng_decode_memory](https://github.com/lvandeve/lodepng/blob/master/lodepng.h#L153) function has a `colortype` parameter, and [LCT_PALETTE](https://github.com/lvandeve/lodepng/blob/master/lodepng.h#L124) enum value might be worth to check, and investigate whether it helps us to accomplish what we want.

Btw this `lodepng.c` file is outdated (20201017 vs [latest 20230410](https://github.com/lvandeve/lodepng/blob/master/lodepng.h) ), so that's why we should also avoid heavily changing 3rd party library files;  upgrading will be simpler if not so many things are changed.

**Comment by XuNeo** [comment]
I don't see how to make the draw buffer alloc function work without hacking into lodepng source code. I'd like adding original code plus lvgl patches applied.

**Comment by kisvegabor** [comment]
> I'd like adding original code plus lvgl patches applied.

Do you mean store `lodepng.patch` next to the `lodepng.c` and apply it when `lodepng` is updated?

**Comment by XuNeo** [comment]
> Do you mean store `lodepng.patch` next to the `lodepng.c` and apply it when `lodepng` is updated?

Yes, but the code in lvgl repo should be already patched, so users can use it out-of-box, just like current status.
In the mean time, if we need to upgrade lodepng. Then grab the latest version source code and patch it again.


For this PR, we still need to find a better way instead of hacking into lodepng to make such big modification. I'm currently investigating `libpng`, and hope can get some ideads.

**Pull request closed without merging**
