### PR TITLE
Update QNX documentation as the build directory changed

### PR DESCRIPTION
**Pull request by elahav**
### Description of the feature or fix

The last commit in #6507 changed moved the QNX build directory under `env_support`. Update the documentation to reflect that.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` ([astyle](http://astyle.sourceforge.net/install.html) version [v3.4.12](https://github.com/szepeviktor/astyle/releases/tag/v3.4.12) needs to be installed) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Comment by jarxon** [comment]
Looks good to me.  I don't think I have approval permissions though.

**Comment by kisvegabor** [comment]
Thanks!

I've just noticed that a new [`lv_conf.h`](https://github.com/lvgl/lvgl/blob/master/env_support/qnx/lv_conf.h) file was added in the qnx folder. We should remove that if possible. The recommended workflow is that the user copies `lv_conf_template.h` next to the `lvgl` folder or to the path specified by `LV_CONF_PATH`. There there shouldn't be "ready-to-use" config files in the driver.

An other note: on LVGL v9 have an operating system abstraction layer for some OS-es. Would it make sense to add it for QNX too? See an example for [pthread](https://github.com/lvgl/lvgl/blob/master/src/osal/lv_pthread.c).

**Comment by elahav** [comment]
@kisvegabor the reason I added the `lv_conf.h` file is that the workflow I enabled via the build directory is slightly different than the normal one. You can still follow the standard LVGL way of adding the source to your project, setting up your own `lv_conf.h` file and building the application and LVGL as one executable. The build directory, on the other hand, enables a ready-to-use library (static and shared), which is why it needs a pre-populated conf header.

If that doesn't make sense or doesn't fit with the way LVGL does things I can certainly revisit.

**Comment by kisvegabor** [comment]
Having a dedicated `lv_conf.h` makes maintenance more difficult as we need to continuously update that `lv_conf.h`. If people would like to build a standalone library they can still copy `lv_conf_template.h` next to the `lvgl` folder and set it up themselves. 
Could it really work?

**Comment by elahav** [comment]
That's a very good point about maintenance. I've created a new pull request #6596 to generate the header at build time from the template. What do you think?
I will update the documentation to make it clear that you can use LVGL for a QNX project in two ways:
1. The standard LVGL way of including the source with your project
2. As a library

**Comment by elahav** [comment]
> An other note: on LVGL v9 have an operating system abstraction layer for some OS-es. Would it make sense to add it for QNX too? See an example for [pthread](https://github.com/lvgl/lvgl/blob/master/src/osal/lv_pthread.c).

`LV_OS_PTHREAD` would work on QNX

**Review by kisvegabor — DISMISSED** [review]
Looks good, thank you!

**Review by liamHowatt — COMMENTED** [review]
I think I spotted one more near the bottom
```make
LDFLAGS=-lscreen -llvgl -L$(LVGL_DIR)/qnx/aarch64/so.le
```

**Comment by elahav** [comment]
> I think I spotted one more near the bottom
> 
> ```makefile
> LDFLAGS=-lscreen -llvgl -L$(LVGL_DIR)/qnx/aarch64/so.le
> ```

Fixed, thanks. I also renamed `LVGL_DIR` in the mekafile example to `LVGL_ROOT` to be more consistent with the rest of the document.

**Review by liamHowatt — APPROVED** [review]
Thanks!

**Review by kisvegabor — APPROVED** [review]

**Pull request merged**
